/**
 * Flash Cards Configuration - Food Category
 * 
 * Defines flash card content and settings for the food category
 * Each card maps to a question ID from the food questions
 * Cards are dynamically generated by compositing:
 * - A background image
 * - A character with an emotion
 * - An object image
 * - Text overlay
 */

export const foodFlashCardsConfig = {
  // Total number of cards
  totalCards: 10,
  
  // Canvas display size
  canvasWidth: 360,
  canvasHeight: 240,
  
  // Default background for all cards (can be overridden per card)
  defaultBackground: 'purple.png',
  
  // Default character for all cards (can be overridden per card)
  defaultCharacter: 'elvis',
  
  // Default emotion for all cards (can be overridden per card)
  defaultEmotion: 'laughing.png',
  
  // Flash card data: Maps card indices to question IDs
  // These are the featured vocabulary items shown in flash cards
  cards: [
    { 
      questionId: 'food_001', // la sandía - the watermelon
      object: 'la sandía.svg', // TODO: Replace with .png once proper images are created
      emotion: 'pleased.png',
    },
    { 
      questionId: 'food_002', // el plátano - the banana
      object: 'el plátano.svg', // TODO: Replace with .png once proper images are created
      emotion: 'laughing.png',
    },
    { 
      questionId: 'food_003', // la manzana - the apple
      object: 'la manzana.svg', // TODO: Replace with .png once proper images are created
      emotion: 'pleased.png',
    },
    { 
      questionId: 'food_004', // la naranja - the orange
      object: 'la naranja.svg', // TODO: Replace with .png once proper images are created
      emotion: 'welcoming.png',
    },
    { 
      questionId: 'food_009', // la piña - the pineapple
      object: 'la piña.svg', // TODO: Replace with .png once proper images are created
      emotion: 'laughing.png',
    },
    { 
      questionId: 'food_036', // la pizza - the pizza
      object: 'la pizza.svg', // TODO: Replace with .png once proper images are created
      emotion: 'pleased.png',
    },
    { 
      questionId: 'food_037', // la hamburguesa - the hamburger
      object: 'la hamburguesa.svg', // TODO: Replace with .png once proper images are created
      emotion: 'laughing.png',
    },
    { 
      questionId: 'food_039', // el taco - the taco
      object: 'el taco.svg', // TODO: Replace with .png once proper images are created
      emotion: 'pleased.png',
    },
    { 
      questionId: 'food_043', // el pollo - the chicken
      object: 'el pollo.svg', // TODO: Replace with .png once proper images are created
      emotion: 'welcoming.png',
    },
    { 
      questionId: 'food_069', // el helado - the ice cream
      object: 'el helado.svg', // TODO: Replace with .png once proper images are created
      emotion: 'laughing.png',
    },
  ],
  
  // Category-specific text styling (optional - overrides defaults)
  text: {
    spanish: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#333',
      maxWidth: 320,
      lineHeight: 1.3,
    },
    english: {
      fontSize: 18,
      fontWeight: 'normal',
      color: '#666',
      maxWidth: 320,
      lineHeight: 1.2,
    },
    verticalSpacing: 15,
    topMargin: 60,
  },
  
  // Diamond animation (optional - overrides defaults)
  diamond: {
    animationSpeed: 0.008,
    fadeMin: 0.4,
    fadeMax: 1.0,
    size: 45,
    positionX: 30,
    positionY: 30,
  },
};
