/**
 * ACCOMMODATION Category Questions
 * Category: accommodation
 */

export const accommodationQuestions = [
{
    id: 'accommodation_001',
    emoji: '🏨',
    question: '¿Dónde te hospedas cuando viajas?',
    translation: 'Where do you stay when you travel?',
    options: ['hotel', 'hostal', 'posada'],
    correctAnswer: 'hotel',
    hint: 'Hotel - lodging for travelers, from French "hôtel"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_002',
    emoji: '🛏️',
    question: '¿Dónde duermes en el hotel?',
    translation: 'Where do you sleep in the hotel?',
    options: ['cama', 'el catre', 'la litera'],
    correctAnswer: 'cama',
    hint: 'Bed - furniture for sleeping, hotel rooms have "cama individual" or "doble"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_003',
    emoji: '🔑',
    question: '¿Qué usas para abrir la puerta de tu habitación?',
    translation: 'What do you use to open your room door?',
    options: ['llave', 'la llave maestra', 'el llavero'],
    correctAnswer: 'llave',
    hint: 'Key - opens locks, from Latin "clavis", modern hotels use key cards',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_004',
    emoji: '🚪',
    question: '¿Por dónde entras a la habitación?',
    translation: 'Where do you enter the room?',
    options: ['puerta', 'la entrada', 'el portal'],
    correctAnswer: 'puerta',
    hint: 'Door - entrance to room, "puerta" from Latin "porta"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_005',
    emoji: '🪟',
    question: '¿Por dónde entra la luz del sol?',
    translation: 'Where does sunlight come in?',
    options: ['ventana', 'el ventanal', 'la claraboya'],
    correctAnswer: 'ventana',
    hint: 'Window - lets in light and air, "ventana" from Latin "ventus" (wind)',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_006',
    emoji: '🛁',
    question: '¿Dónde te bañas con agua acumulada?',
    translation: 'Where do you bathe in standing water?',
    options: ['bañera', 'la tina', 'la bañadera'],
    correctAnswer: 'bañera',
    hint: 'Bathtub - fill with water for bath, "tina" also used in Latin America',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_007',
    emoji: '🚿',
    question: '¿Dónde te bañas de pie?',
    translation: 'Where do you bathe standing up?',
    options: ['ducha', 'la regadera', 'la ducha de mano'],
    correctAnswer: 'ducha',
    hint: 'Shower - spray of water for washing, "regadera" in Mexico',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_008',
    emoji: '🪑',
    question: '¿En qué te sientas?',
    translation: 'What do you sit on?',
    options: ['silla', 'el asiento', 'el taburete'],
    options: ['silla', 'el asiento', 'el taburete'],
    correctAnswer: 'silla',
    hint: 'Chair - furniture for sitting, "silla" from Latin "sella"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_009',
    emoji: '🛋️',
    question: '¿En qué mueble te relajas en la sala?',
    translation: 'What piece of furniture do you relax on in the living room?',
    options: ['sofá', 'el sillón', 'el diván'],
    correctAnswer: 'sofá',
    hint: 'Sofa/couch - comfortable seating for multiple people',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_010',
    emoji: '🪞',
    question: '¿Dónde ves tu reflejo?',
    translation: 'Where do you see your reflection?',
    options: ['espejo', 'el espejo de mano', 'el espejo de cuerpo entero'],
    correctAnswer: 'espejo',
    hint: 'Mirror - reflects your image, "espejo" from Latin "speculum"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_011',
    emoji: '🕯️',
    question: '¿Qué enciendes para dar luz romántica?',
    translation: 'What do you light to give romantic light?',
    options: ['una vela', 'el cirio', 'la candela'],
    correctAnswer: 'una vela',
    hint: 'Candle - wax with flame for light, emergency or romantic lighting',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_012',
    emoji: '💡',
    question: '¿Qué pones en la lámpara para dar luz?',
    translation: 'What do you put in the lamp to give light?',
    options: ['un foco', 'la bombilla', 'el bombillo'],
    correctAnswer: 'un foco',
    hint: 'Light bulb - "foco" in Latin America, "bombilla" in Spain',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_013',
    emoji: '🧹',
    question: '¿Con qué barres el piso?',
    translation: 'What do you sweep the floor with?',
    options: ['una escoba', 'el cepillo', 'la escobilla'],
    correctAnswer: 'una escoba',
    hint: 'Broom - sweeps floors with bristles, housekeeping tool',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_014',
    emoji: '🧺',
    question: '¿Dónde pones la ropa sucia?',
    translation: 'Where do you put dirty clothes?',
    options: ['una cesta', 'una canasta', 'un cesto'],
    correctAnswer: 'una cesta',
    hint: 'Basket - woven container, "canasta" also used for basket',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_015',
    emoji: '🧴',
    question: '¿Con qué te lavas las manos?',
    translation: 'What do you wash your hands with?',
    options: ['el jabón', 'el jabón líquido', 'la pastilla de jabón'],
    correctAnswer: 'el jabón',
    hint: 'Soap - cleans body and hands, hotels provide small bars',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_016',
    emoji: '🧻',
    question: '¿Qué papel usas en el baño?',
    translation: 'What paper do you use in the bathroom?',
    options: ['el papel higiénico', 'el papel de baño', 'el papel sanitario'],
    correctAnswer: 'el papel higiénico',
    hint: 'Toilet paper - bathroom essential, "papel de baño" also used',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_017',
    emoji: '🧼',
    question: '¿Con qué te lavas en la ducha?',
    translation: 'What do you wash yourself with in the shower?',
    options: ['el jabón', 'el jabón de tocador', 'el jabonera'],
    correctAnswer: 'el jabón',
    hint: 'Soap - for washing, "jabón" from Arabic "sabun"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_018',
    emoji: '🛌',
    question: '¿Qué actividad es esta?',
    translation: 'What activity is this?',
    options: ['dormir', 'descansar', 'reposar'],
    correctAnswer: 'dormir',
    hint: 'Sleeping - rest in bed, "dormir" is to sleep, "acostarse" is to lie down',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_019',
    emoji: '🏡',
    question: '¿Dónde vive una familia?',
    translation: 'Where does a family live?',
    options: ['la casa', 'el hogar', 'la vivienda'],
    correctAnswer: 'la casa',
    hint: 'House - private dwelling, "hogar" means home',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_020',
    emoji: '🏢',
    question: '¿Qué estructura tiene muchos pisos?',
    translation: 'What structure has many floors?',
    options: ['el edificio', 'el rascacielos', 'la construcción'],
    correctAnswer: 'el edificio',
    hint: 'Building - multi-story structure, "edificio" from Latin "aedificium"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },

  // Hotel Rooms & Types (30 questions)
  {
    id: 'accommodation_022',
    emoji: 'la habitación doble.png',
    question: '¿Qué habitación tiene dos camas?',
    translation: 'What room has two beds?',
    options: ['la habitación doble', 'la doble con dos camas', 'la habitación twin'],
    correctAnswer: 'la habitación doble',
    hint: 'Double room - two beds or one large bed, "doble" means double',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_023',
    emoji: '🛌',
    question: '¿Qué habitación es para una persona?',
    translation: 'What room is for one person?',
    options: ['la habitación individual', 'la habitación sencilla', 'la habitación simple'],
    correctAnswer: 'la habitación individual',
    hint: 'Single room - one person occupancy, "sencilla" also used',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_024',
    emoji: 'la suite.png',
    question: '¿Qué habitación de lujo tiene sala de estar?',
    translation: 'What luxury room has a living room?',
    options: ['la suite', 'la suite ejecutiva', 'la suite presidencial'],
    correctAnswer: 'la suite',
    hint: 'Suite - luxury hotel room with separate living area, from French',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_025',
    emoji: '🪟',
    question: '¿Por dónde entra la luz natural?',
    translation: 'Where does natural light come in?',
    options: ['la ventana', 'el ventanal', 'la claraboya'],
    correctAnswer: 'la ventana',
    hint: 'Window - for light and fresh air, balcony rooms have better views',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_027',
    emoji: '🪞',
    question: '¿Dónde te miras para arreglarte?',
    translation: 'Where do you look at yourself to get ready?',
    options: ['el espejo', 'el espejo de cuerpo entero', 'el espejo del baño'],
    correctAnswer: 'el espejo',
    hint: 'Mirror - check appearance, bathrooms have large mirrors',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_028',
    emoji: '🛋️',
    question: '¿Dónde te sientas cómodamente?',
    translation: 'Where do you sit comfortably?',
    options: ['el sofá', 'el sillón', 'el diván'],
    correctAnswer: 'el sofá',
    hint: 'Sofa - comfortable seating, suites have sitting areas',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_029',
    emoji: '🪑',
    question: '¿Dónde te sientas en la mesa?',
    translation: 'Where do you sit at the table?',
    options: ['la silla', 'el asiento', 'la butaca'],
    correctAnswer: 'la silla',
    hint: 'Chair - single seat for desk or table work',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_030',
    emoji: 'almohada.png',
    question: '¿Qué pones en la cama para dormir cómodo?',
    translation: 'What do you put on the bed to sleep comfortably?',
    options: ['la almohada', 'el cojín', 'la almohada de plumas'],
    options: ['la almohada', 'el cojín', 'la almohada de plumas'],
    correctAnswer: 'la almohada',
    hint: 'Pillow - for head support, hotels usually provide two per bed',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_031',
    emoji: 'la manta.png',
    question: '¿Qué usas para cubrirte cuando hace frío?',
    translation: 'What do you use to cover yourself when it\'s cold?',
    options: ['la manta', 'la cobija', 'la frazada'],
    correctAnswer: 'la manta',
    hint: 'Blanket - keeps warm, "cobija" in Latin America, "frazada" also used',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_032',
    emoji: 'el colchón.png',
    question: '¿Qué cubres con sábanas?',
    translation: 'What do you cover with sheets?',
    options: ['el colchón', 'el somier', 'la base de la cama'],
    correctAnswer: 'el colchón',
    hint: 'Mattress - covered with sheets, "colchón" from Arabic "almatraha"',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_033',
    emoji: 'las cortinas.png',
    question: '¿Qué cierras para tener privacidad?',
    translation: 'What do you close for privacy?',
    options: ['las cortinas', 'las persianas', 'las contraventanas'],
    correctAnswer: 'las cortinas',
    hint: 'Curtains - block light and provide privacy, "persianas" are blinds',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_034',
    emoji: '💡',
    question: '¿Qué enciendes para iluminar la habitación?',
    translation: 'What do you turn on to light the room?',
    options: ['la lámpara', 'la luz', 'el foco'],
    correctAnswer: 'la lámpara',
    hint: 'Lamp - electric light, bedside lamps common in hotel rooms',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_035',
    emoji: '📺',
    question: '¿Qué miras en la habitación del hotel?',
    translation: 'What do you look at in the hotel room?',
    options: ['la televisión', 'la tele', 'el televisor'],
    correctAnswer: 'la televisión',
    hint: 'TV - most hotel rooms include television with cable channels',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_036',
    emoji: '❄️',
    question: '¿Qué te enfría cuando hace calor?',
    translation: 'What cools you when it\'s hot?',
    options: ['el aire acondicionado', 'el clima', 'el AC'],
    correctAnswer: 'el aire acondicionado',
    hint: 'Air conditioning - cooling system, essential in hot climates',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_037',
    emoji: '🔥',
    question: '¿Qué te calienta cuando hace frío?',
    translation: 'What heats you when it\'s cold?',
    options: ['la calefacción', 'el radiador', 'la estufa'],
    correctAnswer: 'la calefacción',
    hint: 'Heating - warms room in cold weather, "climatización" is climate control',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_038',
    emoji: '🚿',
    question: '¿Dónde te bañas en el hotel?',
    translation: 'Where do you bathe in the hotel?',
    options: ['la ducha', 'la regadera', 'la ducha de mano'],
    correctAnswer: 'la ducha',
    hint: 'Shower - for quick washing, most hotel bathrooms have shower',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_039',
    emoji: '🛁',
    question: '¿Dónde tomas un baño relajante?',
    translation: 'Where do you take a relaxing bath?',
    options: ['la bañera', 'la tina', 'la bañadera'],
    correctAnswer: 'la bañera',
    hint: 'Bathtub - for soaking bath, luxury hotels have spa tubs',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_040',
    emoji: '🚽',
    question: '¿Qué usas en el baño del hotel?',
    translation: 'What do you use in the hotel bathroom?',
    options: ['el inodoro', 'el retrete', 'el váter'],
    options: ['el inodoro', 'el retrete', 'el váter'],
    correctAnswer: 'el inodoro',
    hint: 'Toilet - "inodoro" means odorless, "retrete" or "váter" also used',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_041',
    emoji: '🧻',
    question: '¿Qué papel hay en el baño?',
    translation: 'What paper is in the bathroom?',
    options: ['el papel higiénico', 'el papel de baño', 'el papel sanitario'],
    correctAnswer: 'el papel higiénico',
    hint: 'Toilet paper - bathroom essential, hotels restock daily',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_042',
    emoji: '🧴',
    question: '¿Qué líquido usas para lavarte las manos?',
    translation: 'What liquid do you use to wash your hands?',
    options: ['el jabón', 'el jabón líquido', 'la pastilla de jabón'],
    correctAnswer: 'el jabón',
    hint: 'Soap - for cleaning hands, hotels provide bars or liquid soap',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_043',
    emoji: '🧴',
    question: '¿Qué usas para lavarte el pelo?',
    translation: 'What do you use to wash your hair?',
    options: ['el champú', 'el shampoo', 'el jabón para el cabello'],
    correctAnswer: 'el champú',
    hint: 'Shampoo - for washing hair, from Hindi "champo" (to massage)',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_044',
    emoji: '🧖',
    question: '¿Con qué te secas después de la ducha?',
    translation: 'What do you dry yourself with after the shower?',
    options: ['la toalla', 'la toalla de baño', 'la toallita'],
    correctAnswer: 'la toalla',
    hint: 'Towel - for drying body, hotels provide bath and hand towels',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_045',
    emoji: '🪮',
    question: '¿Con qué te peinas el cabello?',
    translation: 'What do you comb your hair with?',
    options: ['el peine', 'la peineta', 'la peinilla'],
    correctAnswer: 'el peine',
    hint: 'Comb - for styling hair, "cepillo" is brush',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_046',
    emoji: '🪥',
    question: '¿Con qué te lavas los dientes?',
    translation: 'What do you brush your teeth with?',
    options: ['el cepillo de dientes', 'el cepillo dental', 'la escobilla dental'],
    correctAnswer: 'el cepillo de dientes',
    hint: 'Toothbrush - for dental hygiene, brush teeth twice daily',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_047',
    emoji: 'la pasta de dientes.png',
    question: '¿Qué pasta usas con el cepillo de dientes?',
    translation: 'What paste do you use with the toothbrush?',
    options: ['la pasta de dientes', 'la pasta dental', 'el dentífrico'],
    correctAnswer: 'la pasta de dientes',
    hint: 'Toothpaste - "dentífrico" also used, cleans and protects teeth',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_048',
    emoji: '🪒',
    question: '¿Con qué te afeitas?',
    translation: 'What do you shave with?',
    options: ['el rastrillo', 'la navaja', 'la afeitadora'],
    correctAnswer: 'el rastrillo',
    hint: 'Razor - for shaving, "navaja" in Spain, "afeitadora" is electric',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_049',
    emoji: '💨',
    question: '¿Qué usas para secarte el pelo rápido?',
    translation: 'What do you use to dry your hair quickly?',
    options: ['el secador de pelo', 'la secadora', 'el secador'],
    correctAnswer: 'el secador de pelo',
    hint: 'Hair dryer - blows hot air, most hotels provide in bathroom',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_050',
    emoji: 'la habitación con vista.png',
    question: '¿Qué habitación tiene vista al mar?',
    translation: 'What room has an ocean view?',
    options: ['la habitación con vista', 'la habitación con vista al mar', 'la habitación frente al mar'],
    correctAnswer: 'la habitación con vista',
    hint: 'Room with view - ocean or city view costs more than interior',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },

  // Hotel Services & Amenities (40 questions)
  {
    id: 'accommodation_051',
    emoji: '🔑',
    question: '¿Qué recibes en la recepción para abrir tu habitación?',
    translation: 'What do you receive at reception to open your room?',
    options: ['la llave', 'la llave de la habitación', 'el llavero'],
    correctAnswer: 'la llave',
    hint: 'Key - to unlock room, traditional metal or modern key card',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_052',
    emoji: '💳',
    question: '¿Qué tarjeta moderna abre puertas de hotel?',
    translation: 'What modern card opens hotel doors?',
    options: ['la tarjeta llave', 'la llave electrónica', 'la llave magnética'],
    correctAnswer: 'la tarjeta llave',
    hint: 'Key card - electronic hotel key, swipe or tap to unlock',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_053',
    emoji: 'la recepción.png',
    question: '¿Dónde haces check-in en el hotel?',
    translation: 'Where do you check in at the hotel?',
    options: ['la recepción', 'el mostrador', 'la conserjería'],
    correctAnswer: 'la recepción',
    hint: 'Reception/front desk - where you register and get room key',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_054',
    emoji: '👨‍💼',
    question: '¿Quién trabaja en la recepción?',
    translation: 'Who works at the reception?',
    options: ['el recepcionista', 'el conserje', 'el empleado de mostrador'],
    correctAnswer: 'el recepcionista',
    hint: 'Receptionist - front desk staff, helps with check-in and information',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_055',
    emoji: '🧳',
    question: '¿Quién te ayuda con las maletas?',
    translation: 'Who helps you with the luggage?',
    options: ['el botones', 'el maletero', 'el mozo de equipaje'],
    correctAnswer: 'el botones',
    hint: 'Bellhop - carries luggage to room, "mozo de equipaje" also used',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_056',
    emoji: '🧹',
    question: '¿Quién limpia tu habitación?',
    translation: 'Who cleans your room?',
    options: ['la camarera', 'la mucama', 'la empleada de limpieza'],
    correctAnswer: 'la camarera',
    hint: 'Housekeeper - cleans rooms daily, "mucama" in some regions',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_057',
    emoji: '🛎️',
    question: '¿Qué tocas para llamar al servicio?',
    translation: 'What do you press to call service?',
    options: ['el timbre', 'la campanilla', 'el botón de servicio'],
    correctAnswer: 'el timbre',
    hint: 'Bell - ring for service, "campanilla" at reception desk',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_058',
    emoji: '🍽️',
    question: '¿Qué servicio lleva comida a tu habitación?',
    translation: 'What service brings food to your room?',
    options: ['el servicio a la habitación', 'el servicio de cuarto', 'el room service'],
    correctAnswer: 'el servicio a la habitación',
    hint: 'Room service - delivers food to your room, available 24/7 in some hotels',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_059',
    emoji: '🍳',
    question: '¿Qué comida está incluida por la mañana?',
    translation: 'What meal is included in the morning?',
    options: ['el desayuno', 'el desayuno incluido', 'el desayuno buffet'],
    correctAnswer: 'el desayuno',
    hint: 'Breakfast - morning meal, many hotels include in room rate',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_060',
    emoji: '🥐',
    question: '¿Qué desayuno incluye café y pan?',
    translation: 'What breakfast includes coffee and bread?',
    options: ['el desayuno continental', 'el desayuno europeo', 'el desayuno ligero'],
    options: ['el desayuno continental', 'el desayuno europeo', 'el desayuno ligero'],
    correctAnswer: 'el desayuno continental',
    hint: 'Continental breakfast - light European style with coffee, bread, pastries',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_061',
    emoji: '🏊',
    question: '¿Dónde nadas en el hotel?',
    translation: 'Where do you swim in the hotel?',
    options: ['la piscina', 'la alberca', 'la pileta'],
    correctAnswer: 'la piscina',
    hint: 'Swimming pool - "alberca" in Mexico, common hotel amenity',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_062',
    emoji: '💪',
    question: '¿Dónde haces ejercicio en el hotel?',
    translation: 'Where do you exercise in the hotel?',
    options: ['el gimnasio', 'el gym', 'la sala de fitness'],
    correctAnswer: 'el gimnasio',
    hint: 'Gym - exercise facility with equipment, free for hotel guests',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_063',
    emoji: '🧖',
    question: '¿Dónde te relajas con masajes?',
    translation: 'Where do you relax with massages?',
    options: ['el spa', 'el centro de bienestar', 'el balneario'],
    correctAnswer: 'el spa',
    hint: 'Spa - wellness center for massages and relaxation treatments',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_064',
    emoji: '🍷',
    question: '¿Dónde tomas bebidas y socializas?',
    translation: 'Where do you have drinks and socialize?',
    options: ['el bar', 'el bar del hotel', 'el lounge'],
    correctAnswer: 'el bar',
    hint: 'Bar - serves alcoholic and non-alcoholic drinks, social area',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_065',
    emoji: '🍴',
    question: '¿Dónde comes en el hotel?',
    translation: 'Where do you eat in the hotel?',
    options: ['el restaurante', 'el comedor', 'el área de restaurantes'],
    correctAnswer: 'el restaurante',
    hint: 'Restaurant - dining facility, many hotels have multiple restaurants',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_066',
    emoji: 'el wifi.png',
    question: '¿Qué internet gratis ofrece el hotel?',
    translation: 'What free internet does the hotel offer?',
    options: ['el wifi', 'el Wi-Fi', 'la conexión inalámbrica'],
    correctAnswer: 'el wifi',
    hint: 'WiFi - wireless internet, now standard amenity in most hotels',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_067',
    emoji: '🅿️',
    question: '¿Dónde dejas el coche en el hotel?',
    translation: 'Where do you leave the car at the hotel?',
    options: ['el estacionamiento', 'el aparcamiento', 'el parqueadero'],
    correctAnswer: 'el estacionamiento',
    hint: 'Parking lot - "aparcamiento" in Spain, "parqueadero" in some regions',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_068',
    emoji: '🚗',
    question: '¿Qué servicio te lleva gratis al aeropuerto?',
    translation: 'What service takes you to the airport for free?',
    options: ['el shuttle', 'el servicio de traslado', 'el transporte del hotel'],
    correctAnswer: 'el shuttle',
    hint: 'Shuttle - free hotel bus service to airport, "servicio de traslado"',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_069',
    emoji: '🧺',
    question: '¿Dónde lavan tu ropa en el hotel?',
    translation: 'Where do they wash your clothes in the hotel?',
    options: ['la lavandería', 'el servicio de lavandería', 'la tintorería'],
    correctAnswer: 'la lavandería',
    hint: 'Laundry - service to wash clothes, extra fee usually applies',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_070',
    emoji: '🔒',
    question: '¿Dónde guardas objetos de valor?',
    translation: 'Where do you store valuables?',
    options: ['la caja fuerte', 'la caja de seguridad', 'el cofre'],
    options: ['la caja fuerte', 'la caja de seguridad', 'el cofre'],
    correctAnswer: 'la caja fuerte',
    hint: 'Safe box - secure storage for valuables, in room or at front desk',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_071',
    emoji: '🛗',
    question: '¿Qué usas para subir al piso 10?',
    translation: 'What do you use to go up to the 10th floor?',
    options: ['el ascensor', 'el elevador', 'el montacargas'],
    correctAnswer: 'el ascensor',
    hint: 'Elevator - "ascensor" in Spain, "elevador" in Latin America',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_072',
    emoji: '🪜',
    question: '¿Qué subes si el ascensor no funciona?',
    translation: 'What do you climb if the elevator doesn\'t work?',
    options: ['las escaleras', 'la escalera', 'los escalones'],
    correctAnswer: 'las escaleras',
    hint: 'Stairs - emergency exit route when elevator breaks down',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_073',
    emoji: '🚪',
    question: '¿Qué piso tiene salida directa a la calle?',
    translation: 'What floor has direct access to the street?',
    options: ['la planta baja', 'el primer piso', 'el nivel de calle'],
    correctAnswer: 'la planta baja',
    hint: 'Ground floor - "primer piso" in Latin America, street level',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_074',
    emoji: '🏢',
    question: '¿Qué piso está arriba de todo?',
    translation: 'What floor is at the very top?',
    options: ['el último piso', 'el piso superior', 'la planta alta'],
    correctAnswer: 'el último piso',
    hint: 'Top floor - highest level, often has best views',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_075',
    emoji: '🌃',
    question: '¿Qué terraza está en el techo?',
    translation: 'What terrace is on the roof?',
    options: ['la azotea', 'la terraza', 'el rooftop'],
    correctAnswer: 'la azotea',
    hint: 'Rooftop - "terraza" on roof, often has bar or pool',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_076',
    emoji: '🪴',
    question: '¿Qué área verde tiene el hotel?',
    translation: 'What green area does the hotel have?',
    options: ['el jardín', 'el jardín del hotel', 'los jardines'],
    correctAnswer: 'el jardín',
    hint: 'Garden - landscaped area with plants and flowers',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_077',
    emoji: '🌳',
    question: '¿Qué área exterior tiene césped y plantas?',
    translation: 'What outdoor area has grass and plants?',
    options: ['el parque', 'el jardín', 'la zona verde'],
    correctAnswer: 'el parque',
    hint: 'Park - outdoor green space for relaxation and walking',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_078',
    emoji: '🎮',
    question: '¿Dónde juegan los niños en el hotel?',
    translation: 'Where do children play in the hotel?',
    options: ['la sala de juegos', 'el área de juegos', 'el salón recreativo'],
    correctAnswer: 'la sala de juegos',
    hint: 'Game room - entertainment area for children with toys and games',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_079',
    emoji: '💼',
    question: '¿Dónde trabajas con computadora en el hotel?',
    translation: 'Where do you work with a computer in the hotel?',
    options: ['el centro de negocios', 'la sala de negocios', 'el business center'],
    correctAnswer: 'el centro de negocios',
    hint: 'Business center - work area with computers, printers, and internet',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_080',
    emoji: '🎭',
    question: '¿Dónde hay eventos y conferencias?',
    translation: 'Where are there events and conferences?',
    options: ['el salón de eventos', 'la sala de conferencias', 'el salón de banquetes'],
    correctAnswer: 'el salón de eventos',
    hint: 'Event hall for conferences',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_081',
    emoji: '🔔',
    question: '¿Qué servicio está disponible 24 horas?',
    translation: 'What service is available 24 hours?',
    options: ['la recepción 24 horas', 'el servicio 24/7', 'la atención continua'],
    correctAnswer: 'la recepción 24 horas',
    hint: '24-hour front desk service',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_082',
    emoji: '🚨',
    question: '¿Qué sale si hay fuego?',
    translation: 'What comes out if there is fire?',
    options: ['la alarma de incendios', 'la alarma de fuego', 'el detector de humo'],
    correctAnswer: 'la alarma de incendios',
    hint: 'Fire alarm warning system',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_083',
    emoji: '🧯',
    question: '¿Qué usas para apagar un incendio pequeño?',
    translation: 'What do you use to put out a small fire?',
    options: ['el extintor', 'el extinguidor', 'el matafuegos'],
    correctAnswer: 'el extintor',
    hint: 'Fire extinguisher',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_084',
    emoji: '🚪',
    question: '¿Por dónde sales en emergencia?',
    translation: 'Where do you exit in an emergency?',
    options: ['la salida de emergencia', 'la salida de escape', 'la vía de evacuación'],
    correctAnswer: 'la salida de emergencia',
    hint: 'Emergency exit route',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_085',
    emoji: '📞',
    question: '¿Qué usas para llamar a recepción?',
    translation: 'What do you use to call reception?',
    options: ['el teléfono de habitación', 'el teléfono del cuarto', 'el teléfono interno'],
    correctAnswer: 'el teléfono de habitación',
    hint: 'Room phone to call front desk',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_086',
    emoji: '🧊',
    question: '¿Dónde consigues hielo en el hotel?',
    translation: 'Where do you get ice in the hotel?',
    options: ['la máquina de hielo', 'la hielera', 'el dispensador de hielo'],
    correctAnswer: 'la máquina de hielo',
    hint: 'Ice machine in hallway',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_087',
    emoji: '☕',
    question: '¿Qué máquina hace café en la habitación?',
    translation: 'What machine makes coffee in the room?',
    options: ['la cafetera', 'la máquina de café', 'el percolador'],
    correctAnswer: 'la cafetera',
    hint: 'Coffee maker in room',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_088',
    emoji: '🧃',
    question: '¿Dónde guardas bebidas frías?',
    translation: 'Where do you store cold drinks?',
    options: ['el minibar', 'el minifrigorífico', 'la nevera pequeña'],
    correctAnswer: 'el minibar',
    hint: 'Small refrigerator with drinks',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_089',
    emoji: '🎬',
    question: '¿Qué canal de televisión cuesta dinero?',
    translation: 'What TV channel costs money?',
    options: ['el pay-per-view', 'el pago por evento', 'el canal de pago'],
    correctAnswer: 'el pay-per-view',
    hint: 'Movies you pay to watch',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_090',
    emoji: '🔌',
    question: '¿Dónde conectas tu teléfono?',
    translation: 'Where do you plug in your phone?',
    options: ['el enchufe', 'el tomacorriente', 'la toma de corriente'],
    correctAnswer: 'el enchufe',
    hint: 'Electrical outlet for charging',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },

  // Booking & Check-in/out (30 questions)
  {
    id: 'accommodation_091',
    emoji: '📅',
    question: '¿Qué haces antes de llegar al hotel?',
    translation: 'What do you do before arriving at the hotel?',
    options: ['reservar', 'hacer una reserva', 'reservar una habitación'],
    correctAnswer: 'reservar',
    hint: 'Make a reservation',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_092',
    emoji: '📝',
    question: '¿Qué número confirma tu reserva?',
    translation: 'What number confirms your reservation?',
    options: ['el número de confirmación', 'el código de reserva', 'el número de reserva'],
    correctAnswer: 'el número de confirmación',
    hint: 'Confirmation number for booking',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_093',
    emoji: 'el check-in.png',
    question: '¿Qué proceso haces al llegar?',
    translation: 'What process do you do upon arrival?',
    options: ['el check-in', 'el registro', 'la entrada'],
    correctAnswer: 'el check-in',
    hint: 'Registration upon arrival',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_094',
    emoji: 'el check-in.png',
    question: '¿Qué proceso haces al salir?',
    translation: 'What process do you do when leaving?',
    options: ['el check-out', 'la salida', 'el cierre'],
    correctAnswer: 'el check-out',
    hint: 'Departure process',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_095',
    emoji: '🕐',
    question: '¿A qué hora puedes entrar a tu habitación?',
    translation: 'What time can you enter your room?',
    options: ['la hora de check-in', 'la hora de entrada', 'la hora de registro'],
    correctAnswer: 'la hora de check-in',
    hint: 'Check-in time, usually afternoon',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_096',
    emoji: '🕚',
    question: '¿A qué hora debes dejar la habitación?',
    translation: 'What time must you leave the room?',
    options: ['la hora de check-out', 'la hora de salida', 'la hora límite'],
    correctAnswer: 'la hora de check-out',
    hint: 'Check-out time, usually morning',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_097',
    emoji: '🌙',
    question: '¿Cuántas noches te quedas?',
    translation: 'How many nights are you staying?',
    options: ['la estancia', 'la estadía', 'la permanencia'],
    correctAnswer: 'la estancia',
    hint: 'Length of stay',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_098',
    emoji: '💰',
    question: '¿Qué pagas por quedarte en el hotel?',
    translation: 'What do you pay to stay in the hotel?',
    options: ['la tarifa', 'la tarifa por noche', 'el precio'],
    correctAnswer: 'la tarifa',
    hint: 'Rate or price per night',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_099',
    emoji: '💵',
    question: '¿Qué dinero extra das por buen servicio?',
    translation: 'What extra money do you give for good service?',
    options: ['la propina', 'la gratificación', 'el extra'],
    correctAnswer: 'la propina',
    hint: 'Tip for good service',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_100',
    emoji: '💳',
    question: '¿Qué dejas como garantía?',
    translation: 'What do you leave as a guarantee?',
    options: ['el depósito', 'el depósito de garantía', 'la fianza'],
    correctAnswer: 'el depósito',
    hint: 'Security deposit',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_101',
    emoji: '🧾',
    question: '¿Qué documento prueba tu pago?',
    translation: 'What document proves your payment?',
    options: ['la factura', 'el recibo', 'el comprobante'],
    correctAnswer: 'la factura',
    hint: 'Invoice or receipt',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_102',
    emoji: '🆔',
    question: '¿Qué documento muestras al hacer check-in?',
    translation: 'What document do you show when checking in?',
    options: ['la identificación', 'el DNI', 'la cédula'],
    correctAnswer: 'la identificación',
    hint: 'ID card or passport',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_103',
    emoji: '🛂',
    question: '¿Qué documento necesitas para viajar?',
    translation: 'What document do you need to travel?',
    options: ['el pasaporte', 'el pasaporte internacional', 'los papeles'],
    correctAnswer: 'el pasaporte',
    hint: 'Passport for international travel',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_104',
    emoji: '📋',
    question: '¿Qué llenas con tus datos personales?',
    translation: 'What do you fill out with your personal information?',
    options: ['el formulario de registro', 'la planilla', 'el formulario'],
    correctAnswer: 'el formulario de registro',
    hint: 'Registration form with personal info',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_105',
    emoji: '⭐',
    question: '¿Qué hotel tiene el mejor servicio?',
    translation: 'What hotel has the best service?',
    options: ['el hotel de cinco estrellas', 'el hotel 5 estrellas', 'el hotel de lujo'],
    correctAnswer: 'el hotel de cinco estrellas',
    hint: 'Five-star luxury hotel',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_106',
    emoji: '🏨',
    question: '¿Qué alojamiento es barato para jóvenes?',
    translation: 'What accommodation is cheap for young people?',
    options: ['el hostal', 'el albergue', 'el albergue juvenil'],
    options: ['el hostal', 'el albergue', 'el albergue juvenil'],
    correctAnswer: 'el hostal',
    hint: 'Hostel for budget travelers',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_107',
    emoji: '🏖️',
    question: '¿Qué hotel está en la playa con todo incluido?',
    translation: 'What hotel is on the beach with all-inclusive?',
    options: ['el resort', 'el complejo turístico', 'el hotel de playa'],
    correctAnswer: 'el resort',
    hint: 'Beach resort with all-inclusive',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_108',
    emoji: '🛣️',
    question: '¿Qué alojamiento está en la carretera?',
    translation: 'What accommodation is on the highway?',
    options: ['el motel', 'el motor hotel', 'el hotel de carretera'],
    correctAnswer: 'el motel',
    hint: 'Roadside motel for travelers',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_109',
    emoji: '🏡',
    question: '¿Qué alojamiento es una casa pequeña?',
    translation: 'What accommodation is a small house?',
    options: ['la cabaña', 'el refugio', 'la casita'],
    correctAnswer: 'la cabaña',
    hint: 'Cabin in nature',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_110',
    emoji: '🏰',
    question: '¿Qué alojamiento es una casa grande y lujosa?',
    translation: 'What accommodation is a large luxurious house?',
    options: ['la villa', 'la mansión', 'la casa de lujo'],
    correctAnswer: 'la villa',
    hint: 'Luxury villa or mansion',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_111',
    emoji: '🏠',
    question: '¿Qué alquilas con cocina y sala?',
    translation: 'What do you rent with a kitchen and living room?',
    options: ['el apartamento', 'el departamento', 'el piso'],
    correctAnswer: 'el apartamento',
    hint: 'Apartment with kitchen',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_112',
    emoji: '🏕️',
    question: '¿Dónde duermes en tienda de campaña?',
    translation: 'Where do you sleep in a tent?',
    options: ['el camping', 'el campamento', 'el área de acampar'],
    correctAnswer: 'el camping',
    hint: 'Campground for tents',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_113',
    emoji: '🛏️',
    question: '¿Qué incluye el precio de la habitación?',
    translation: 'What does the room price include?',
    options: ['el alojamiento y desayuno', 'la cama y desayuno', 'el B&B'],
    correctAnswer: 'el alojamiento y desayuno',
    hint: 'Bed and breakfast included',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_114',
    emoji: '🍽️',
    question: '¿Qué plan incluye todas las comidas?',
    translation: 'What plan includes all meals?',
    options: ['la pensión completa', 'el plan completo', 'todas las comidas'],
    correctAnswer: 'la pensión completa',
    hint: 'Full board with all meals',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_115',
    emoji: '🥗',
    question: '¿Qué plan incluye desayuno y cena?',
    translation: 'What plan includes breakfast and dinner?',
    options: ['la media pensión', 'el plan medio', 'dos comidas'],
    correctAnswer: 'la media pensión',
    hint: 'Half board - breakfast and dinner',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_116',
    emoji: '🍹',
    question: '¿Qué incluye comidas, bebidas y actividades?',
    translation: 'What includes meals, drinks, and activities?',
    options: ['el todo incluido', 'el all-inclusive', 'el plan completo'],
    correctAnswer: 'el todo incluido',
    hint: 'All-inclusive package',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_117',
    emoji: '❌',
    question: '¿Qué haces si no puedes ir?',
    translation: 'What do you do if you can\'t go?',
    options: ['cancelar la reserva', 'anular la reserva', 'cancelar'],
    correctAnswer: 'cancelar la reserva',
    hint: 'Cancel your reservation',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_118',
    emoji: '📅',
    question: '¿Qué haces si cambias las fechas?',
    translation: 'What do you do if you change the dates?',
    options: ['modificar la reserva', 'cambiar la reserva', 'ajustar la reserva'],
    correctAnswer: 'modificar la reserva',
    hint: 'Modify reservation dates',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_119',
    emoji: '✅',
    question: '¿Qué haces para asegurar tu reserva?',
    translation: 'What do you do to secure your reservation?',
    options: ['confirmar', 'confirmar la reserva', 'asegurar'],
    correctAnswer: 'confirmar',
    hint: 'Confirm your booking',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_120',
    emoji: '⏰',
    question: '¿Qué pides si llegas muy temprano?',
    translation: 'What do you ask for if you arrive very early?',
    options: ['el check-in temprano', 'la entrada anticipada', 'el check-in anticipado'],
    correctAnswer: 'el check-in temprano',
    hint: 'Early check-in request',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },

  // Problems & Complaints (30 questions)
  {
    id: 'accommodation_121',
    emoji: '🔧',
    question: '¿Qué no funciona si no hay agua caliente?',
    translation: 'What doesn\'t work if there\'s no hot water?',
    options: ['el calentador', 'el boiler', 'el termo'],
    correctAnswer: 'el calentador',
    hint: 'Water heater is broken',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_122',
    emoji: '❄️',
    question: '¿Qué está roto si hace mucho calor?',
    translation: 'What is broken if it\'s very hot?',
    options: ['el aire acondicionado', 'el AC', 'el clima'],
    correctAnswer: 'el aire acondicionado',
    hint: 'Air conditioning not working',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_123',
    emoji: '📡',
    question: '¿Qué no funciona si no hay internet?',
    translation: 'What doesn\'t work if there\'s no internet?',
    options: ['el wifi', 'el Wi-Fi', 'la conexión'],
    correctAnswer: 'el wifi',
    hint: 'Internet connection problem',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_124',
    emoji: '📺',
    question: '¿Qué problema hay si no ves nada?',
    translation: 'What\'s the problem if you can\'t see anything?',
    options: ['la televisión rota', 'el televisor dañado', 'la tele descompuesta'],
    correctAnswer: 'la televisión rota',
    hint: 'TV is not working',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_125',
    emoji: '💡',
    question: '¿Qué se quemó si no hay luz?',
    translation: 'What burned out if there\'s no light?',
    options: ['el foco', 'la bombilla', 'el bombillo'],
    correctAnswer: 'el foco',
    hint: 'Light bulb burned out',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_126',
    emoji: '🚿',
    question: '¿Qué problema hay si no sale agua?',
    translation: 'What\'s the problem if water doesn\'t come out?',
    options: ['la tubería tapada', 'la cañería obstruida', 'el desagüe bloqueado'],
    correctAnswer: 'la tubería tapada',
    hint: 'Clogged pipes or plumbing issue',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_127',
    emoji: '🚽',
    question: '¿Qué problema hay si el agua no baja?',
    translation: 'What\'s the problem if the water doesn\'t drain?',
    options: ['el inodoro tapado', 'el retrete obstruido', 'el váter bloqueado'],
    correctAnswer: 'el inodoro tapado',
    hint: 'Toilet is clogged',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_128',
    emoji: '🧹',
    question: '¿Qué problema hay si está sucia?',
    translation: 'What\'s the problem if it\'s dirty?',
    options: ['la habitación no limpiada', 'el cuarto sucio', 'la habitación sin limpiar'],
    correctAnswer: 'la habitación no limpiada',
    hint: 'Room not cleaned',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_129',
    emoji: '🦟',
    question: '¿Qué problema hay con insectos?',
    translation: 'What\'s the problem with insects?',
    options: ['los mosquitos', 'los zancudos', 'los bichos'],
    correctAnswer: 'los mosquitos',
    hint: 'Mosquitoes in room',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_130',
    emoji: '🔊',
    question: '¿Qué problema hay si escuchas a los vecinos?',
    translation: 'What\'s the problem if you hear the neighbors?',
    options: ['el mucho ruido', 'el ruido excesivo', 'el escándalo'],
    options: ['el mucho ruido', 'el ruido excesivo', 'el escándalo'],
    correctAnswer: 'el mucho ruido',
    hint: 'Too much noise',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_131',
    emoji: '🛏️',
    question: '¿Qué problema hay si no descansas bien?',
    translation: 'What\'s the problem if you don\'t rest well?',
    options: ['la cama incómoda', 'el colchón duro', 'la cama mala'],
    correctAnswer: 'la cama incómoda',
    hint: 'Uncomfortable bed',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_132',
    emoji: '🧴',
    question: '¿Qué falta en el baño?',
    translation: 'What\'s missing in the bathroom?',
    options: ['los artículos de tocador', 'las amenidades', 'los productos de baño'],
    correctAnswer: 'los artículos de tocador',
    hint: 'Toiletries missing',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_133',
    emoji: '🧻',
    question: '¿Qué necesitas más en el baño?',
    translation: 'What do you need more of in the bathroom?',
    options: ['el papel higiénico', 'el papel de baño', 'el papel sanitario'],
    correctAnswer: 'el papel higiénico',
    hint: 'Need more toilet paper',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_134',
    emoji: '🧖',
    question: '¿Qué necesitas más para secarte?',
    translation: 'What do you need more of to dry yourself?',
    options: ['las toallas', 'las toallas de baño', 'las toallitas'],
    correctAnswer: 'las toallas',
    hint: 'Need more towels',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_135',
    emoji: '🛏️',
    question: '¿Qué necesitas cambiar si están sucias?',
    translation: 'What do you need to change if they\'re dirty?',
    options: ['las sábanas', 'la ropa de cama', 'las cobijas'],
    correctAnswer: 'las sábanas',
    hint: 'Dirty sheets need changing',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_136',
    emoji: '🔑',
    question: '¿Qué problema hay si no abre la puerta?',
    translation: 'What problem is there if the door won\'t open?',
    options: ['la llave no funciona', 'la tarjeta no sirve', 'la llave está dañada'],
    correctAnswer: 'la llave no funciona',
    hint: 'Key card not working',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_137',
    emoji: '🚪',
    question: '¿Qué problema hay si no cierra bien?',
    translation: 'What\'s the problem if it doesn\'t close well?',
    options: ['la puerta rota', 'la puerta dañada', 'la cerradura mala'],
    correctAnswer: 'la puerta rota',
    hint: 'Door doesn\'t close properly',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_138',
    emoji: '🪟',
    question: '¿Qué no se puede abrir?',
    translation: 'What can\'t be opened?',
    options: ['la ventana atascada', 'la ventana trabada', 'la ventana bloqueada'],
    correctAnswer: 'la ventana atascada',
    hint: 'Window is stuck',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_139',
    emoji: '🔒',
    question: '¿Qué problema de seguridad hay?',
    translation: 'What security problem is there?',
    options: ['la cerradura rota', 'el seguro dañado', 'la cerradura mala'],
    correctAnswer: 'la cerradura rota',
    hint: 'Lock is broken',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_140',
    emoji: '😤',
    question: '¿Qué haces si no estás satisfecho?',
    translation: 'What do you do if you\'re not satisfied?',
    options: ['hacer una queja', 'presentar un reclamo', 'quejarse'],
    correctAnswer: 'hacer una queja',
    hint: 'Make a complaint',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_141',
    emoji: '🔄',
    question: '¿Qué pides si la habitación tiene problemas?',
    translation: 'What do you ask for if the room has problems?',
    options: ['el cambio de habitación', 'la nueva habitación', 'otra habitación'],
    correctAnswer: 'el cambio de habitación',
    hint: 'Request room change',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_142',
    emoji: '💵',
    question: '¿Qué pides si el servicio fue malo?',
    translation: 'What do you ask for if the service was bad?',
    options: ['el reembolso', 'la devolución', 'el dinero de vuelta'],
    correctAnswer: 'el reembolso',
    hint: 'Request refund for bad service',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_143',
    emoji: '🆓',
    question: '¿Qué te dan si hubo un problema?',
    translation: 'What do they give you if there was a problem?',
    options: ['el descuento', 'la rebaja', 'el descuento compensatorio'],
    correctAnswer: 'el descuento',
    hint: 'Discount for inconvenience',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_144',
    emoji: '⬆️',
    question: '¿Qué mejora te dan sin costo?',
    translation: 'What upgrade do they give you at no cost?',
    options: ['la mejora de habitación', 'el upgrade', 'la mejora gratis'],
    correctAnswer: 'la mejora de habitación',
    hint: 'Free room upgrade',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_145',
    emoji: '🛠️',
    question: '¿Quién arregla cosas rotas?',
    translation: 'Who fixes broken things?',
    options: ['el mantenimiento', 'el personal de mantenimiento', 'el técnico'],
    correctAnswer: 'el mantenimiento',
    hint: 'Maintenance staff fixes things',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_146',
    emoji: '⏱️',
    question: '¿Qué pides si quieres quedarte más tarde?',
    translation: 'What do you ask for if you want to stay later?',
    options: ['el check-out tardío', 'la salida tardía', 'el check-out extendido'],
    correctAnswer: 'el check-out tardío',
    hint: 'Late check-out request',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_147',
    emoji: '🧳',
    question: '¿Dónde guardas las maletas después del check-out?',
    translation: 'Where do you store luggage after check-out?',
    options: ['la custodia de equipaje', 'el guardaequipaje', 'el depósito de maletas'],
    correctAnswer: 'la custodia de equipaje',
    hint: 'Luggage storage service',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_148',
    emoji: '🔎',
    question: '¿Qué haces si perdiste algo?',
    translation: 'What do you do if you lost something?',
    options: ['reportar objetos perdidos', 'ir a objetos perdidos', 'reportar la pérdida'],
    correctAnswer: 'reportar objetos perdidos',
    hint: 'Report to lost and found',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_149',
    emoji: '📝',
    question: '¿Qué dejas al final de tu estancia?',
    translation: 'What do you leave at the end of your stay?',
    options: ['la reseña', 'la opinión', 'el comentario'],
    correctAnswer: 'la reseña',
    hint: 'Write a review of your stay',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_150',
    emoji: '⭐',
    question: '¿Cuántas estrellas das si estuvo excelente?',
    translation: 'How many stars do you give if it was excellent?',
    options: ['cinco estrellas', '5 estrellas', 'las cinco estrellas'],
    correctAnswer: 'cinco estrellas',
    hint: 'Five stars for excellent service',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },

  // Additional Accommodation Phrases (5 questions)
  {
    id: 'accommodation_151',
    emoji: '💺',
    question: '¿Cómo preguntas "Can I sit here?"',
    translation: 'Can I sit here?',
    options: ['¿puedo sentarme aquí?', '¿me puedo sentar aquí?', '¿puedo estar aquí?'],
    correctAnswer: '¿puedo sentarme aquí?',
    hint: 'Can I sit here? - "puedo" (can I), "sentarme" (sit myself - reflexive), "aquí" (here)',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_152',
    emoji: '🍽️',
    question: '¿Cómo preguntas "When do you open the restaurant?"',
    translation: 'When do you open the restaurant?',
    options: ['¿cuándo abren el restaurante?', '¿a qué hora abren el restaurante?', '¿cuándo abre el restaurante?'],
    correctAnswer: '¿cuándo abren el restaurante?',
    hint: 'When do you open - "cuándo" (when), "abren" (you all open - 3rd person plural for business)',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_153',
    emoji: 'el check-in.png',
    question: '¿Cómo dices "I need to checkout"?',
    translation: 'I need to checkout',
    options: ['necesito hacer el checkout', 'necesito salir de la habitación', 'tengo que hacer checkout'],
    correctAnswer: 'necesito hacer el checkout',
    hint: 'I need to checkout - "necesito" (I need), "hacer el checkout" (do checkout), also "check-out"',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_154',
    emoji: '🚕',
    question: '¿Cómo preguntas "Can you call me a taxi?"',
    translation: 'Can you call me a taxi?',
    options: ['¿puede llamarme un taxi?', '¿me puede llamar un taxi?', '¿podría llamarme un taxi?'],
    correctAnswer: '¿puede llamarme un taxi?',
    hint: 'Can you call me a taxi? - "puede" (can you formal), "llamarme" (call me), "un taxi" (a taxi)',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_155',
    emoji: 'toallas.png',
    question: '¿Cómo dices "We need towels"?',
    translation: 'We need towels',
    options: ['necesitamos toallas', 'nos hacen falta toallas', 'queremos toallas'],
    correctAnswer: 'necesitamos toallas',
    hint: 'We need towels - "necesitamos" (we need), "toallas" (towels), common hotel request',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_156',
    emoji: '🛀🏻',
    question: '¿Qué pides si quieres relajarte con un baño?',
    translation: 'What do you ask for if you want to relax with a bath?',
    options: ['una habitación con bañera', 'un cuarto con tina', 'una habitación con baño completo'],
    correctAnswer: 'una habitación con bañera',
    hint: 'Room with bathtub - for relaxing soaks, not just shower, luxury amenity in hotels',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_157',
    emoji: '🪠',
    question: '¿Qué usas para destapar el inodoro?',
    translation: 'What do you use to unclog the toilet?',
    options: ['el destapacaños', 'el desatascador', 'la bomba de baño'],
    correctAnswer: 'el destapacaños',
    hint: 'Plunger - for unclogging toilets, "desatascador" in Spain, essential bathroom tool',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_158',
    emoji: 'está deteriorado.png',
    question: '¿Cómo describes un alojamiento en mal estado?',
    translation: 'How do you describe accommodation in poor condition?',
    options: ['está deteriorado', 'está abandonado', 'está descuidado'],
    correctAnswer: 'está deteriorado',
    hint: 'Run-down/deteriorated - old and in poor condition, needs repairs and maintenance',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_159',
    emoji: '💆🏻‍♀️',
    question: '¿Qué servicio de relajación reservas en el spa del hotel?',
    translation: 'What relaxation service do you book at the hotel spa?',
    options: ['un masaje', 'una sesión de yoga', 'un tratamiento facial'],
    correctAnswer: 'un masaje',
    hint: 'Massage - relaxation service at hotel spa, therapeutic bodywork',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_160',
    emoji: '👨🏻‍💻',
    question: '¿Qué necesitas para conectarte a internet en el hotel?',
    translation: 'What do you need to connect to the internet at the hotel?',
    options: ['el wifi', 'el televisor', 'el teléfono'],
    correctAnswer: 'el wifi',
    hint: 'WiFi - wireless internet connection, most hotels provide free WiFi access',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_161',
    emoji: '⛲️',
    question: '¿Qué decoración de agua encuentras en el hotel o resort?',
    translation: 'What water decoration do you find at the hotel or resort?',
    options: ['la fuente', 'la piscina', 'el jacuzzi'],
    correctAnswer: 'la fuente',
    hint: 'Fountain - decorative water feature at hotels/resorts, from Latin "fons" (spring)',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_162',
    emoji: '🚱',
    question: '¿Qué preguntas sobre el agua del grifo?',
    translation: 'What do you ask about tap water?',
    options: ['¿es potable el agua?', '¿hay agua caliente?', '¿funciona el agua?'],
    correctAnswer: '¿es potable el agua?',
    hint: 'Is the water drinkable? - important safety question when traveling, tap water safety varies by location',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_163',
    emoji: 'wall-thermostat.png',
    question: '¿Qué usas para controlar la temperatura en la habitación?',
    translation: 'What do you use to control the temperature in the room?',
    options: ['el termostato', 'el control remoto', 'el interruptor'],
    correctAnswer: 'el termostato',
    hint: 'Wall thermostat - device that regulates heating and cooling systems',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_164',
    emoji: 'smart-door-lock.png',
    question: '¿Qué tipo de cerradura moderna usan muchos hoteles?',
    translation: 'What type of modern lock do many hotels use?',
    options: ['la cerradura inteligente', 'la cerradura tradicional', 'el candado'],
    correctAnswer: 'la cerradura inteligente',
    hint: 'Smart door lock - electronic lock that can be controlled with keycard or smartphone',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_165',
    emoji: 'massage-chair.png',
    question: '¿Qué mueble especial te ayuda a relajarte?',
    translation: 'What special furniture helps you relax?',
    options: ['la silla de masaje', 'el sillón reclinable', 'el sofá cama'],
    correctAnswer: 'la silla de masaje',
    hint: 'Massage chair - motorized chair that provides therapeutic massage',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_166',
    emoji: 'universal-travel-adapter.png',
    question: '¿Qué necesitas para enchufar dispositivos de otros países?',
    translation: 'What do you need to plug in devices from other countries?',
    options: ['el adaptador universal', 'el cable de extensión', 'el enchufe múltiple'],
    correctAnswer: 'el adaptador universal',
    hint: 'Universal travel adapter - allows plugs from different countries to fit various outlet types',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_167',
    emoji: 'window-blinds.png',
    question: '¿Qué usas para bloquear la luz de la ventana?',
    translation: 'What do you use to block window light?',
    options: ['las persianas', 'las cortinas', 'los estores'],
    correctAnswer: 'las persianas',
    hint: 'Window blinds - horizontal or vertical slats that control light and privacy',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_168',
    emoji: 'garage.png',
    question: '¿Dónde guardas el auto en casa?',
    translation: 'Where do you keep the car at home?',
    options: ['el garaje', 'el cochera', 'el aparcamiento'],
    correctAnswer: 'el garaje',
    hint: 'Garage - enclosed space for parking vehicles at a residence',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_169',
    emoji: 'janitor.png',
    question: '¿Quién se encarga del mantenimiento y limpieza del edificio?',
    translation: 'Who is in charge of building maintenance and cleaning?',
    options: ['el conserje', 'el portero', 'el guardia'],
    correctAnswer: 'el conserje',
    hint: 'Janitor - person responsible for cleaning and maintaining a building',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_170',
    emoji: 'parking-garage.png',
    question: '¿Dónde estacionas el auto en un edificio de apartamentos?',
    translation: 'Where do you park the car in an apartment building?',
    options: ['el estacionamiento cubierto', 'la calle', 'el patio'],
    correctAnswer: 'el estacionamiento cubierto',
    hint: 'Parking garage - multi-level structure for vehicle parking',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_171',
    emoji: 'escalator.png',
    question: '¿Qué escaleras mecánicas te llevan entre pisos?',
    translation: 'What mechanical stairs take you between floors?',
    options: ['la escalera eléctrica', 'el ascensor', 'la escalera de caracol'],
    correctAnswer: 'la escalera eléctrica',
    hint: 'Escalator - moving staircase that transports people between levels',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_172',
    emoji: 'light-switch.png',
    question: '¿Qué tocas para encender o apagar la luz?',
    translation: 'What do you touch to turn the light on or off?',
    options: ['el interruptor', 'el enchufe', 'el fusible'],
    correctAnswer: 'el interruptor',
    hint: 'Light switch - device that controls electrical flow to lights',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_173',
    emoji: 'door-peephole.png',
    question: '¿Por dónde miras para ver quién está afuera?',
    translation: 'Where do you look to see who is outside?',
    options: ['la mirilla', 'la ventanilla', 'el ojo de buey'],
    correctAnswer: 'la mirilla',
    hint: 'Door peephole - small opening in a door to see visitors',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_174',
    emoji: 'basement.png',
    question: '¿Qué parte de la casa está bajo tierra?',
    translation: 'What part of the house is underground?',
    options: ['el sótano', 'el ático', 'el garaje'],
    correctAnswer: 'el sótano',
    hint: 'Basement - floor of a building that is partly or entirely below ground level',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_175',
    emoji: 'clothes-iron.png',
    question: '¿Qué aparato usas para quitar las arrugas de la ropa?',
    translation: 'What appliance do you use to remove wrinkles from clothes?',
    options: ['la plancha', 'la secadora', 'la lavadora'],
    correctAnswer: 'la plancha',
    hint: 'Clothes iron - heated device that presses and smooths fabric',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_176',
    emoji: 'cottage.png',
    question: '¿Qué tipo de casa pequeña está en el campo?',
    translation: 'What type of small house is in the countryside?',
    options: ['la cabaña', 'el chalet', 'el bungaló'],
    correctAnswer: 'la cabaña',
    hint: 'Cottage - small, cozy house typically in a rural or semi-rural location',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_177',
    emoji: 'door-handle.png',
    question: '¿Qué parte de la puerta agarras para abrirla?',
    translation: 'What part of the door do you grab to open it?',
    options: ['la manija', 'el picaporte', 'la aldaba'],
    correctAnswer: 'la manija',
    hint: 'Door handle - lever or knob used to open and close doors',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_178',
    emoji: 'apartment-building.png',
    question: '¿Cómo se llama el edificio con muchas viviendas?',
    translation: 'What is the building with many homes called?',
    options: ['el edificio de apartamentos', 'la torre', 'el complejo'],
    correctAnswer: 'el edificio de apartamentos',
    hint: 'Apartment building - multi-story structure containing separate residential units',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_179',
    emoji: 'microwave-oven.png',
    question: '¿Qué electrodoméstico calienta comida rápidamente?',
    translation: 'What appliance heats food quickly?',
    options: ['el microondas', 'el horno', 'la estufa'],
    correctAnswer: 'el microondas',
    hint: 'Microwave oven - kitchen appliance that heats food using electromagnetic radiation',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_180',
    emoji: 'slippers.png',
    question: '¿Qué calzado cómodo usas dentro de la casa?',
    translation: 'What comfortable footwear do you wear inside the house?',
    options: ['las pantuflas', 'las sandalias', 'los zapatos'],
    correctAnswer: 'las pantuflas',
    hint: 'Slippers - soft, comfortable shoes worn indoors',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_181',
    emoji: 'doorknob.png',
    question: '¿Qué giras para abrir la puerta?',
    translation: 'What do you turn to open the door?',
    options: ['el pomo', 'la manija', 'el pestillo'],
    correctAnswer: 'el pomo',
    hint: 'Doorknob - round handle that turns to open a door',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_182',
    emoji: 'hand-sanitizer.png',
    question: '¿Qué producto usas para desinfectar las manos sin agua?',
    translation: 'What product do you use to disinfect hands without water?',
    options: ['el desinfectante de manos', 'el jabón líquido', 'la crema para manos'],
    correctAnswer: 'el desinfectante de manos',
    hint: 'Hand sanitizer - alcohol-based gel that kills germs without water',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_183',
    emoji: 'drain-stopper.png',
    question: '¿Qué pones en el desagüe para retener el agua?',
    translation: 'What do you put in the drain to hold water?',
    options: ['el tapón', 'la tapa', 'el filtro'],
    correctAnswer: 'el tapón',
    hint: 'Drain stopper - plug that blocks water from draining in sinks or tubs',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_184',
    emoji: 'mini-fridge.png',
    question: '¿Qué electrodoméstico pequeño mantiene fría la comida?',
    translation: 'What small appliance keeps food cold?',
    options: ['el mini refrigerador', 'la hielera', 'el congelador'],
    correctAnswer: 'el mini refrigerador',
    hint: 'Mini fridge - compact refrigerator often found in hotel rooms',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_185',
    emoji: 'fireplace.png',
    question: '¿Dónde haces fuego dentro de la casa para calentar?',
    translation: 'Where do you make a fire inside the house to heat?',
    options: ['la chimenea', 'la estufa', 'el horno'],
    correctAnswer: 'la chimenea',
    hint: 'Fireplace - structure for containing fire, used for heating and ambiance',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_186',
    emoji: 'soundproof-booth.png',
    question: '¿Qué espacio aislado usas para llamadas privadas?',
    translation: 'What isolated space do you use for private calls?',
    options: ['la cabina insonorizada', 'la oficina', 'el cuarto privado'],
    correctAnswer: 'la cabina insonorizada',
    hint: 'Soundproof booth - enclosed space designed to block external noise',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_187',
    emoji: 'hotel-room-safe.png',
    question: '¿Dónde guardas objetos de valor en la habitación del hotel?',
    translation: 'Where do you store valuables in the hotel room?',
    options: ['la caja fuerte', 'el armario', 'el cajón'],
    correctAnswer: 'la caja fuerte',
    hint: 'Hotel room safe - secure lockbox for storing valuables',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_188',
    emoji: 'parking-barrier-gate.png',
    question: '¿Qué barrera controla la entrada al estacionamiento?',
    translation: 'What barrier controls entry to the parking lot?',
    options: ['la barrera de estacionamiento', 'la puerta automática', 'el portón'],
    correctAnswer: 'la barrera de estacionamiento',
    hint: 'Parking barrier gate - mechanical arm that controls vehicle access',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_189',
    emoji: 'turnstile.png',
    question: '¿Qué puerta giratoria controla el acceso de personas?',
    translation: 'What rotating door controls people access?',
    options: ['el torniquete', 'la puerta giratoria', 'la barrera'],
    correctAnswer: 'el torniquete',
    hint: 'Turnstile - rotating gate that allows one person to pass at a time',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_190',
    emoji: 'lodge.png',
    question: '¿Qué tipo de alojamiento rústico está en la naturaleza?',
    translation: 'What type of rustic accommodation is in nature?',
    options: ['el refugio', 'el hostal', 'el hotel boutique'],
    correctAnswer: 'el refugio',
    hint: 'Lodge - rustic accommodation typically in natural settings',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_191',
    emoji: 'power-bar.png',
    question: '¿Qué usas para conectar varios dispositivos a la vez?',
    translation: 'What do you use to connect several devices at once?',
    options: ['la regleta', 'el adaptador', 'el cable'],
    correctAnswer: 'la regleta',
    hint: 'Power bar/strip - device with multiple electrical outlets',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_192',
    emoji: 'elevator.png',
    question: '¿Qué máquina te lleva a diferentes pisos?',
    translation: 'What machine takes you to different floors?',
    options: ['el ascensor', 'la escalera eléctrica', 'el montacargas'],
    correctAnswer: 'el ascensor',
    hint: 'Elevator - mechanical lift for transporting people between floors',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_193',
    emoji: 'locker.png',
    question: '¿Dónde guardas tus cosas con llave en el gimnasio?',
    translation: 'Where do you store your things with a lock in the gym?',
    options: ['el casillero', 'el armario', 'el estante'],
    correctAnswer: 'el casillero',
    hint: 'Locker - secure storage compartment with a lock',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_194',
    emoji: 'hair-dryer.png',
    question: '¿Qué aparato usas para secar el cabello?',
    translation: 'What device do you use to dry hair?',
    options: ['el secador de pelo', 'el cepillo', 'la toalla'],
    correctAnswer: 'el secador de pelo',
    hint: 'Hair dryer - electrical device that blows hot air to dry hair',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_195',
    emoji: 'smart-plug.png',
    question: '¿Qué dispositivo controla aparatos eléctricos remotamente?',
    translation: 'What device controls electrical appliances remotely?',
    options: ['el enchufe inteligente', 'el control remoto', 'el interruptor'],
    correctAnswer: 'el enchufe inteligente',
    hint: 'Smart plug - device that adds remote control capabilities to regular appliances',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_196',
    emoji: 'airport-baggage-cart.png',
    question: '¿Qué carrito usas para transportar maletas en el aeropuerto?',
    translation: 'What cart do you use to transport suitcases at the airport?',
    options: ['el carrito de equipaje', 'el carro de compras', 'la carretilla'],
    correctAnswer: 'el carrito de equipaje',
    hint: 'Airport baggage cart - wheeled cart for transporting luggage',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_197',
    emoji: 'radiator.png',
    question: '¿Qué aparato de metal calienta la habitación con agua caliente?',
    translation: 'What metal appliance heats the room with hot water?',
    options: ['el radiador', 'el calentador', 'la estufa'],
    correctAnswer: 'el radiador',
    hint: 'Radiator - heating device that uses hot water or steam',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_198',
    emoji: 'water-purification.png',
    question: '¿Qué sistema limpia el agua para beber?',
    translation: 'What system cleans water for drinking?',
    options: ['el purificador de agua', 'el filtro de aire', 'el destilador'],
    correctAnswer: 'el purificador de agua',
    hint: 'Water purification - system that removes contaminants from water',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_199',
    emoji: ' electric-fan.png',
    question: '¿Qué aparato eléctrico mueve el aire para refrescar?',
    translation: 'What electrical device moves air to cool?',
    options: ['el ventilador', 'el aire acondicionado', 'el extractor'],
    correctAnswer: 'el ventilador',
    hint: 'Electric fan - device with rotating blades that circulates air',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_200',
    emoji: 'room.png',
    question: '¿Cómo se llama cada espacio dentro de una casa?',
    translation: 'What is each space inside a house called?',
    options: ['la habitación', 'el pasillo', 'la sala'],
    correctAnswer: 'la habitación',
    hint: 'Room - enclosed space within a building',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_201',
    emoji: 'door-stopper.png',
    question: '¿Qué objeto mantiene la puerta abierta?',
    translation: 'What object keeps the door open?',
    options: ['el tope de puerta', 'el pasador', 'el pestillo'],
    correctAnswer: 'el tope de puerta',
    hint: 'Door stopper - device that prevents a door from closing',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_202',
    emoji: 'sink.png',
    question: '¿Dónde te lavas las manos en el baño?',
    translation: 'Where do you wash your hands in the bathroom?',
    options: ['el lavabo', 'la bañera', 'la ducha'],
    correctAnswer: 'el lavabo',
    hint: 'Sink - basin with running water for washing',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
];
