/**
 * ACCOMMODATION Category Questions
 * Category: accommodation
 */

export const accommodationQuestions = [
{
    id: 'accommodation_001',
    emoji: '🏨',
    question: '¿Dónde te hospedas cuando viajas?',
    options: ['hotel', 'hostal', 'posada'],
    correctAnswer: 'hotel',
    hint: 'Hotel - lodging for travelers, from French "hôtel"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_002',
    emoji: '🛏️',
    question: '¿Dónde duermes en el hotel?',
    options: ['cama', 'el catre', 'la litera'],
    correctAnswer: 'cama',
    hint: 'Bed - furniture for sleeping, hotel rooms have "cama individual" or "doble"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_003',
    emoji: '🔑',
    question: '¿Qué usas para abrir la puerta de tu habitación?',
    options: ['llave', 'la llave maestra', 'el llavero'],
    correctAnswer: 'llave',
    hint: 'Key - opens locks, from Latin "clavis", modern hotels use key cards',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_004',
    emoji: '🚪',
    question: '¿Por dónde entras a la habitación?',
    options: ['puerta', 'la entrada', 'el portal'],
    correctAnswer: 'puerta',
    hint: 'Door - entrance to room, "puerta" from Latin "porta"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_005',
    emoji: '🪟',
    question: '¿Por dónde entra la luz del sol?',
    options: ['ventana', 'el ventanal', 'la claraboya'],
    correctAnswer: 'ventana',
    hint: 'Window - lets in light and air, "ventana" from Latin "ventus" (wind)',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_006',
    emoji: '🛁',
    question: '¿Dónde te bañas con agua acumulada?',
    options: ['bañera', 'la tina', 'la bañadera'],
    correctAnswer: 'bañera',
    hint: 'Bathtub - fill with water for bath, "tina" also used in Latin America',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_007',
    emoji: '🚿',
    question: '¿Dónde te bañas de pie?',
    options: ['ducha', 'la regadera', 'la ducha de mano'],
    correctAnswer: 'ducha',
    hint: 'Shower - spray of water for washing, "regadera" in Mexico',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_008',
    emoji: '🪑',
    question: '¿En qué te sientas?',
    options: ['silla', 'el asiento', 'el taburete'],
    options: ['silla', 'el asiento', 'el taburete'],
    correctAnswer: 'silla',
    hint: 'Chair - furniture for sitting, "silla" from Latin "sella"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_009',
    emoji: '🛋️',
    question: '¿En qué mueble te relajas en la sala?',
    options: ['sofá', 'el sillón', 'el diván'],
    correctAnswer: 'sofá',
    hint: 'Sofa/couch - comfortable seating for multiple people',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_010',
    emoji: '🪞',
    question: '¿Dónde ves tu reflejo?',
    options: ['espejo', 'el espejo de mano', 'el espejo de cuerpo entero'],
    correctAnswer: 'espejo',
    hint: 'Mirror - reflects your image, "espejo" from Latin "speculum"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_011',
    emoji: '🕯️',
    question: '¿Qué enciendes para dar luz romántica?',
    options: ['una vela', 'el cirio', 'la candela'],
    correctAnswer: 'una vela',
    hint: 'Candle - wax with flame for light, emergency or romantic lighting',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_012',
    emoji: '💡',
    question: '¿Qué pones en la lámpara para dar luz?',
    options: ['un foco', 'la bombilla', 'el bombillo'],
    correctAnswer: 'un foco',
    hint: 'Light bulb - "foco" in Latin America, "bombilla" in Spain',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_013',
    emoji: '🧹',
    question: '¿Con qué barres el piso?',
    options: ['una escoba', 'el cepillo', 'la escobilla'],
    correctAnswer: 'una escoba',
    hint: 'Broom - sweeps floors with bristles, housekeeping tool',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_014',
    emoji: '🧺',
    question: '¿Dónde pones la ropa sucia?',
    options: ['una cesta', 'una canasta', 'un cesto'],
    correctAnswer: 'una cesta',
    hint: 'Basket - woven container, "canasta" also used for basket',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_015',
    emoji: '🧴',
    question: '¿Con qué te lavas las manos?',
    options: ['el jabón', 'el jabón líquido', 'la pastilla de jabón'],
    correctAnswer: 'el jabón',
    hint: 'Soap - cleans body and hands, hotels provide small bars',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_016',
    emoji: '🧻',
    question: '¿Qué papel usas en el baño?',
    options: ['el papel higiénico', 'el papel de baño', 'el papel sanitario'],
    correctAnswer: 'el papel higiénico',
    hint: 'Toilet paper - bathroom essential, "papel de baño" also used',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_017',
    emoji: '🧼',
    question: '¿Con qué te lavas en la ducha?',
    options: ['el jabón', 'el jabón de tocador', 'el jabonera'],
    correctAnswer: 'el jabón',
    hint: 'Soap - for washing, "jabón" from Arabic "sabun"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_018',
    emoji: '🛌',
    question: '¿Qué actividad es esta?',
    options: ['dormir', 'descansar', 'reposar'],
    correctAnswer: 'dormir',
    hint: 'Sleeping - rest in bed, "dormir" is to sleep, "acostarse" is to lie down',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_019',
    emoji: '🏡',
    question: '¿Dónde vive una familia?',
    options: ['la casa', 'el hogar', 'la vivienda'],
    correctAnswer: 'la casa',
    hint: 'House - private dwelling, "hogar" means home',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_020',
    emoji: '🏢',
    question: '¿Qué estructura tiene muchos pisos?',
    options: ['el edificio', 'el rascacielos', 'la construcción'],
    correctAnswer: 'el edificio',
    hint: 'Building - multi-story structure, "edificio" from Latin "aedificium"',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },

  // Hotel Rooms & Types (30 questions)
  {
    id: 'accommodation_022',
    emoji: '🛏️',
    question: '¿Qué habitación tiene dos camas?',
    options: ['la habitación doble', 'la doble con dos camas', 'la habitación twin'],
    correctAnswer: 'la habitación doble',
    hint: 'Double room - two beds or one large bed, "doble" means double',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_023',
    emoji: '👤',
    question: '¿Qué habitación es para una persona?',
    options: ['la habitación individual', 'la habitación sencilla', 'la habitación simple'],
    correctAnswer: 'la habitación individual',
    hint: 'Single room - one person occupancy, "sencilla" also used',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_024',
    emoji: '🏨',
    question: '¿Qué habitación de lujo tiene sala de estar?',
    options: ['la suite', 'la suite ejecutiva', 'la suite presidencial'],
    correctAnswer: 'la suite',
    hint: 'Suite - luxury hotel room with separate living area, from French',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_025',
    emoji: '🪟',
    question: '¿Por dónde entra la luz natural?',
    options: ['la ventana', 'el ventanal', 'la claraboya'],
    correctAnswer: 'la ventana',
    hint: 'Window - for light and fresh air, balcony rooms have better views',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_027',
    emoji: '🪞',
    question: '¿Dónde te miras para arreglarte?',
    options: ['el espejo', 'el espejo de cuerpo entero', 'el espejo del baño'],
    correctAnswer: 'el espejo',
    hint: 'Mirror - check appearance, bathrooms have large mirrors',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_028',
    emoji: '🛋️',
    question: '¿Dónde te sientas cómodamente?',
    options: ['el sofá', 'el sillón', 'el diván'],
    correctAnswer: 'el sofá',
    hint: 'Sofa - comfortable seating, suites have sitting areas',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_029',
    emoji: '🪑',
    question: '¿Dónde te sientas en la mesa?',
    options: ['la silla', 'el asiento', 'la butaca'],
    correctAnswer: 'la silla',
    hint: 'Chair - single seat for desk or table work',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_030',
    emoji: '🛏️',
    question: '¿Qué pones en la cama para dormir cómodo?',
    options: ['la almohada', 'el cojín', 'la almohada de plumas'],
    options: ['la almohada', 'el cojín', 'la almohada de plumas'],
    correctAnswer: 'la almohada',
    hint: 'Pillow - for head support, hotels usually provide two per bed',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_031',
    emoji: '🛏️',
    question: '¿Qué usas para cubrirte cuando hace frío?',
    options: ['la manta', 'la cobija', 'la frazada'],
    correctAnswer: 'la manta',
    hint: 'Blanket - keeps warm, "cobija" in Latin America, "frazada" also used',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_032',
    emoji: '🛏️',
    question: '¿Qué cubres con sábanas?',
    options: ['el colchón', 'el somier', 'la base de la cama'],
    correctAnswer: 'el colchón',
    hint: 'Mattress - covered with sheets, "colchón" from Arabic "almatraha"',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_033',
    emoji: '🪟',
    question: '¿Qué cierras para tener privacidad?',
    options: ['las cortinas', 'las persianas', 'las contraventanas'],
    correctAnswer: 'las cortinas',
    hint: 'Curtains - block light and provide privacy, "persianas" are blinds',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_034',
    emoji: '💡',
    question: '¿Qué enciendes para iluminar la habitación?',
    options: ['la lámpara', 'la luz', 'el foco'],
    correctAnswer: 'la lámpara',
    hint: 'Lamp - electric light, bedside lamps common in hotel rooms',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_035',
    emoji: '📺',
    question: '¿Qué miras en la habitación del hotel?',
    options: ['la televisión', 'la tele', 'el televisor'],
    correctAnswer: 'la televisión',
    hint: 'TV - most hotel rooms include television with cable channels',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_036',
    emoji: '❄️',
    question: '¿Qué te enfría cuando hace calor?',
    options: ['el aire acondicionado', 'el clima', 'el AC'],
    correctAnswer: 'el aire acondicionado',
    hint: 'Air conditioning - cooling system, essential in hot climates',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_037',
    emoji: '🔥',
    question: '¿Qué te calienta cuando hace frío?',
    options: ['la calefacción', 'el radiador', 'la estufa'],
    correctAnswer: 'la calefacción',
    hint: 'Heating - warms room in cold weather, "climatización" is climate control',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_038',
    emoji: '🚿',
    question: '¿Dónde te bañas en el hotel?',
    options: ['la ducha', 'la regadera', 'la ducha de mano'],
    correctAnswer: 'la ducha',
    hint: 'Shower - for quick washing, most hotel bathrooms have shower',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_039',
    emoji: '🛁',
    question: '¿Dónde tomas un baño relajante?',
    options: ['la bañera', 'la tina', 'la bañadera'],
    correctAnswer: 'la bañera',
    hint: 'Bathtub - for soaking bath, luxury hotels have spa tubs',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_040',
    emoji: '🚽',
    question: '¿Qué usas en el baño del hotel?',
    options: ['el inodoro', 'el retrete', 'el váter'],
    options: ['el inodoro', 'el retrete', 'el váter'],
    correctAnswer: 'el inodoro',
    hint: 'Toilet - "inodoro" means odorless, "retrete" or "váter" also used',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_041',
    emoji: '🧻',
    question: '¿Qué papel hay en el baño?',
    options: ['el papel higiénico', 'el papel de baño', 'el papel sanitario'],
    correctAnswer: 'el papel higiénico',
    hint: 'Toilet paper - bathroom essential, hotels restock daily',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_042',
    emoji: '🧴',
    question: '¿Qué líquido usas para lavarte las manos?',
    options: ['el jabón', 'el jabón líquido', 'la pastilla de jabón'],
    correctAnswer: 'el jabón',
    hint: 'Soap - for cleaning hands, hotels provide bars or liquid soap',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_043',
    emoji: '🧴',
    question: '¿Qué usas para lavarte el pelo?',
    options: ['el champú', 'el shampoo', 'el jabón para el cabello'],
    correctAnswer: 'el champú',
    hint: 'Shampoo - for washing hair, from Hindi "champo" (to massage)',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_044',
    emoji: '🧖',
    question: '¿Con qué te secas después de la ducha?',
    options: ['la toalla', 'la toalla de baño', 'la toallita'],
    correctAnswer: 'la toalla',
    hint: 'Towel - for drying body, hotels provide bath and hand towels',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_045',
    emoji: '🪮',
    question: '¿Con qué te peinas el cabello?',
    options: ['el peine', 'la peineta', 'la peinilla'],
    correctAnswer: 'el peine',
    hint: 'Comb - for styling hair, "cepillo" is brush',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_046',
    emoji: '🪥',
    question: '¿Con qué te lavas los dientes?',
    options: ['el cepillo de dientes', 'el cepillo dental', 'la escobilla dental'],
    correctAnswer: 'el cepillo de dientes',
    hint: 'Toothbrush - for dental hygiene, brush teeth twice daily',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_047',
    emoji: '🧴',
    question: '¿Qué pasta usas con el cepillo de dientes?',
    options: ['la pasta de dientes', 'la pasta dental', 'el dentífrico'],
    correctAnswer: 'la pasta de dientes',
    hint: 'Toothpaste - "dentífrico" also used, cleans and protects teeth',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_048',
    emoji: '🪒',
    question: '¿Con qué te afeitas?',
    options: ['el rastrillo', 'la navaja', 'la afeitadora'],
    correctAnswer: 'el rastrillo',
    hint: 'Razor - for shaving, "navaja" in Spain, "afeitadora" is electric',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_049',
    emoji: '💨',
    question: '¿Qué usas para secarte el pelo rápido?',
    options: ['el secador de pelo', 'la secadora', 'el secador'],
    correctAnswer: 'el secador de pelo',
    hint: 'Hair dryer - blows hot air, most hotels provide in bathroom',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_050',
    emoji: '🚪',
    question: '¿Qué habitación tiene vista al mar?',
    options: ['la habitación con vista', 'la habitación con vista al mar', 'la habitación frente al mar'],
    correctAnswer: 'la habitación con vista',
    hint: 'Room with view - ocean or city view costs more than interior',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },

  // Hotel Services & Amenities (40 questions)
  {
    id: 'accommodation_051',
    emoji: '🔑',
    question: '¿Qué recibes en la recepción para abrir tu habitación?',
    options: ['la llave', 'la llave de la habitación', 'el llavero'],
    correctAnswer: 'la llave',
    hint: 'Key - to unlock room, traditional metal or modern key card',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_052',
    emoji: '💳',
    question: '¿Qué tarjeta moderna abre puertas de hotel?',
    options: ['la tarjeta llave', 'la llave electrónica', 'la llave magnética'],
    correctAnswer: 'la tarjeta llave',
    hint: 'Key card - electronic hotel key, swipe or tap to unlock',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_053',
    emoji: '🏨',
    question: '¿Dónde haces check-in en el hotel?',
    options: ['la recepción', 'el mostrador', 'la conserjería'],
    correctAnswer: 'la recepción',
    hint: 'Reception/front desk - where you register and get room key',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_054',
    emoji: '👨‍💼',
    question: '¿Quién trabaja en la recepción?',
    options: ['el recepcionista', 'el conserje', 'el empleado de mostrador'],
    correctAnswer: 'el recepcionista',
    hint: 'Receptionist - front desk staff, helps with check-in and information',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_055',
    emoji: '🧳',
    question: '¿Quién te ayuda con las maletas?',
    options: ['el botones', 'el maletero', 'el mozo de equipaje'],
    correctAnswer: 'el botones',
    hint: 'Bellhop - carries luggage to room, "mozo de equipaje" also used',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_056',
    emoji: '🧹',
    question: '¿Quién limpia tu habitación?',
    options: ['la camarera', 'la mucama', 'la empleada de limpieza'],
    correctAnswer: 'la camarera',
    hint: 'Housekeeper - cleans rooms daily, "mucama" in some regions',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_057',
    emoji: '🛎️',
    question: '¿Qué tocas para llamar al servicio?',
    options: ['el timbre', 'la campanilla', 'el botón de servicio'],
    correctAnswer: 'el timbre',
    hint: 'Bell - ring for service, "campanilla" at reception desk',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_058',
    emoji: '🍽️',
    question: '¿Qué servicio lleva comida a tu habitación?',
    options: ['el servicio a la habitación', 'el servicio de cuarto', 'el room service'],
    correctAnswer: 'el servicio a la habitación',
    hint: 'Room service - delivers food to your room, available 24/7 in some hotels',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_059',
    emoji: '🍳',
    question: '¿Qué comida está incluida por la mañana?',
    options: ['el desayuno', 'el desayuno incluido', 'el desayuno buffet'],
    correctAnswer: 'el desayuno',
    hint: 'Breakfast - morning meal, many hotels include in room rate',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_060',
    emoji: '🥐',
    question: '¿Qué desayuno incluye café y pan?',
    options: ['el desayuno continental', 'el desayuno europeo', 'el desayuno ligero'],
    options: ['el desayuno continental', 'el desayuno europeo', 'el desayuno ligero'],
    correctAnswer: 'el desayuno continental',
    hint: 'Continental breakfast - light European style with coffee, bread, pastries',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_061',
    emoji: '🏊',
    question: '¿Dónde nadas en el hotel?',
    options: ['la piscina', 'la alberca', 'la pileta'],
    correctAnswer: 'la piscina',
    hint: 'Swimming pool - "alberca" in Mexico, common hotel amenity',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_062',
    emoji: '💪',
    question: '¿Dónde haces ejercicio en el hotel?',
    options: ['el gimnasio', 'el gym', 'la sala de fitness'],
    correctAnswer: 'el gimnasio',
    hint: 'Gym - exercise facility with equipment, free for hotel guests',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_063',
    emoji: '🧖',
    question: '¿Dónde te relajas con masajes?',
    options: ['el spa', 'el centro de bienestar', 'el balneario'],
    correctAnswer: 'el spa',
    hint: 'Spa - wellness center for massages and relaxation treatments',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_064',
    emoji: '🍷',
    question: '¿Dónde tomas bebidas y socializas?',
    options: ['el bar', 'el bar del hotel', 'el lounge'],
    correctAnswer: 'el bar',
    hint: 'Bar - serves alcoholic and non-alcoholic drinks, social area',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_065',
    emoji: '🍴',
    question: '¿Dónde comes en el hotel?',
    options: ['el restaurante', 'el comedor', 'el área de restaurantes'],
    correctAnswer: 'el restaurante',
    hint: 'Restaurant - dining facility, many hotels have multiple restaurants',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_066',
    emoji: '📶',
    question: '¿Qué internet gratis ofrece el hotel?',
    options: ['el wifi', 'el Wi-Fi', 'la conexión inalámbrica'],
    correctAnswer: 'el wifi',
    hint: 'WiFi - wireless internet, now standard amenity in most hotels',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_067',
    emoji: '🅿️',
    question: '¿Dónde dejas el coche en el hotel?',
    options: ['el estacionamiento', 'el aparcamiento', 'el parqueadero'],
    correctAnswer: 'el estacionamiento',
    hint: 'Parking lot - "aparcamiento" in Spain, "parqueadero" in some regions',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_068',
    emoji: '🚗',
    question: '¿Qué servicio te lleva gratis al aeropuerto?',
    options: ['el shuttle', 'el servicio de traslado', 'el transporte del hotel'],
    correctAnswer: 'el shuttle',
    hint: 'Shuttle - free hotel bus service to airport, "servicio de traslado"',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_069',
    emoji: '🧺',
    question: '¿Dónde lavan tu ropa en el hotel?',
    options: ['la lavandería', 'el servicio de lavandería', 'la tintorería'],
    correctAnswer: 'la lavandería',
    hint: 'Laundry - service to wash clothes, extra fee usually applies',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_070',
    emoji: '🔒',
    question: '¿Dónde guardas objetos de valor?',
    options: ['la caja fuerte', 'la caja de seguridad', 'el cofre'],
    options: ['la caja fuerte', 'la caja de seguridad', 'el cofre'],
    correctAnswer: 'la caja fuerte',
    hint: 'Safe box - secure storage for valuables, in room or at front desk',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_071',
    emoji: '🛗',
    question: '¿Qué usas para subir al piso 10?',
    options: ['el ascensor', 'el elevador', 'el montacargas'],
    correctAnswer: 'el ascensor',
    hint: 'Elevator - "ascensor" in Spain, "elevador" in Latin America',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_072',
    emoji: '🪜',
    question: '¿Qué subes si el ascensor no funciona?',
    options: ['las escaleras', 'la escalera', 'los escalones'],
    correctAnswer: 'las escaleras',
    hint: 'Stairs - emergency exit route when elevator breaks down',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_073',
    emoji: '🚪',
    question: '¿Qué piso tiene salida directa a la calle?',
    options: ['la planta baja', 'el primer piso', 'el nivel de calle'],
    correctAnswer: 'la planta baja',
    hint: 'Ground floor - "primer piso" in Latin America, street level',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_074',
    emoji: '🏢',
    question: '¿Qué piso está arriba de todo?',
    options: ['el último piso', 'el piso superior', 'la planta alta'],
    correctAnswer: 'el último piso',
    hint: 'Top floor - highest level, often has best views',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_075',
    emoji: '🌃',
    question: '¿Qué terraza está en el techo?',
    options: ['la azotea', 'la terraza', 'el rooftop'],
    correctAnswer: 'la azotea',
    hint: 'Rooftop - "terraza" on roof, often has bar or pool',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_076',
    emoji: '🪴',
    question: '¿Qué área verde tiene el hotel?',
    options: ['el jardín', 'el jardín del hotel', 'los jardines'],
    correctAnswer: 'el jardín',
    hint: 'Garden - landscaped area with plants and flowers',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_077',
    emoji: '🌳',
    question: '¿Qué área exterior tiene césped y plantas?',
    options: ['el parque', 'el jardín', 'la zona verde'],
    correctAnswer: 'el parque',
    hint: 'Park - outdoor green space for relaxation and walking',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_078',
    emoji: '🎮',
    question: '¿Dónde juegan los niños en el hotel?',
    options: ['la sala de juegos', 'el área de juegos', 'el salón recreativo'],
    correctAnswer: 'la sala de juegos',
    hint: 'Game room - entertainment area for children with toys and games',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_079',
    emoji: '💼',
    question: '¿Dónde trabajas con computadora en el hotel?',
    options: ['el centro de negocios', 'la sala de negocios', 'el business center'],
    correctAnswer: 'el centro de negocios',
    hint: 'Business center - work area with computers, printers, and internet',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_080',
    emoji: '🎭',
    question: '¿Dónde hay eventos y conferencias?',
    options: ['el salón de eventos', 'la sala de conferencias', 'el salón de banquetes'],
    correctAnswer: 'el salón de eventos',
    hint: 'Event hall for conferences',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_081',
    emoji: '🔔',
    question: '¿Qué servicio está disponible 24 horas?',
    options: ['la recepción 24 horas', 'el servicio 24/7', 'la atención continua'],
    correctAnswer: 'la recepción 24 horas',
    hint: '24-hour front desk service',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_082',
    emoji: '🚨',
    question: '¿Qué sale si hay fuego?',
    options: ['la alarma de incendios', 'la alarma de fuego', 'el detector de humo'],
    correctAnswer: 'la alarma de incendios',
    hint: 'Fire alarm warning system',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_083',
    emoji: '🧯',
    question: '¿Qué usas para apagar un incendio pequeño?',
    options: ['el extintor', 'el extinguidor', 'el matafuegos'],
    correctAnswer: 'el extintor',
    hint: 'Fire extinguisher',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_084',
    emoji: '🚪',
    question: '¿Por dónde sales en emergencia?',
    options: ['la salida de emergencia', 'la salida de escape', 'la vía de evacuación'],
    correctAnswer: 'la salida de emergencia',
    hint: 'Emergency exit route',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_085',
    emoji: '📞',
    question: '¿Qué usas para llamar a recepción?',
    options: ['el teléfono de habitación', 'el teléfono del cuarto', 'el teléfono interno'],
    correctAnswer: 'el teléfono de habitación',
    hint: 'Room phone to call front desk',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_086',
    emoji: '🧊',
    question: '¿Dónde consigues hielo en el hotel?',
    options: ['la máquina de hielo', 'la hielera', 'el dispensador de hielo'],
    correctAnswer: 'la máquina de hielo',
    hint: 'Ice machine in hallway',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_087',
    emoji: '☕',
    question: '¿Qué máquina hace café en la habitación?',
    options: ['la cafetera', 'la máquina de café', 'el percolador'],
    correctAnswer: 'la cafetera',
    hint: 'Coffee maker in room',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_088',
    emoji: '🧃',
    question: '¿Dónde guardas bebidas frías?',
    options: ['el minibar', 'el minifrigorífico', 'la nevera pequeña'],
    correctAnswer: 'el minibar',
    hint: 'Small refrigerator with drinks',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_089',
    emoji: '🎬',
    question: '¿Qué canal de televisión cuesta dinero?',
    options: ['el pay-per-view', 'el pago por evento', 'el canal de pago'],
    correctAnswer: 'el pay-per-view',
    hint: 'Movies you pay to watch',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_090',
    emoji: '🔌',
    question: '¿Dónde conectas tu teléfono?',
    options: ['el enchufe', 'el tomacorriente', 'la toma de corriente'],
    correctAnswer: 'el enchufe',
    hint: 'Electrical outlet for charging',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },

  // Booking & Check-in/out (30 questions)
  {
    id: 'accommodation_091',
    emoji: '📅',
    question: '¿Qué haces antes de llegar al hotel?',
    options: ['reservar', 'hacer una reserva', 'reservar una habitación'],
    correctAnswer: 'reservar',
    hint: 'Make a reservation',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_092',
    emoji: '📝',
    question: '¿Qué número confirma tu reserva?',
    options: ['el número de confirmación', 'el código de reserva', 'el número de reserva'],
    correctAnswer: 'el número de confirmación',
    hint: 'Confirmation number for booking',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_093',
    emoji: '🏨',
    question: '¿Qué proceso haces al llegar?',
    options: ['el check-in', 'el registro', 'la entrada'],
    correctAnswer: 'el check-in',
    hint: 'Registration upon arrival',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_094',
    emoji: '👋',
    question: '¿Qué proceso haces al salir?',
    options: ['el check-out', 'la salida', 'el cierre'],
    correctAnswer: 'el check-out',
    hint: 'Departure process',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_095',
    emoji: '🕐',
    question: '¿A qué hora puedes entrar a tu habitación?',
    options: ['la hora de check-in', 'la hora de entrada', 'la hora de registro'],
    correctAnswer: 'la hora de check-in',
    hint: 'Check-in time, usually afternoon',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_096',
    emoji: '🕚',
    question: '¿A qué hora debes dejar la habitación?',
    options: ['la hora de check-out', 'la hora de salida', 'la hora límite'],
    correctAnswer: 'la hora de check-out',
    hint: 'Check-out time, usually morning',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_097',
    emoji: '🌙',
    question: '¿Cuántas noches te quedas?',
    options: ['la estancia', 'la estadía', 'la permanencia'],
    correctAnswer: 'la estancia',
    hint: 'Length of stay',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_098',
    emoji: '💰',
    question: '¿Qué pagas por quedarte en el hotel?',
    options: ['la tarifa', 'la tarifa por noche', 'el precio'],
    correctAnswer: 'la tarifa',
    hint: 'Rate or price per night',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_099',
    emoji: '💵',
    question: '¿Qué dinero extra das por buen servicio?',
    options: ['la propina', 'la gratificación', 'el extra'],
    correctAnswer: 'la propina',
    hint: 'Tip for good service',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_100',
    emoji: '💳',
    question: '¿Qué dejas como garantía?',
    options: ['el depósito', 'el depósito de garantía', 'la fianza'],
    correctAnswer: 'el depósito',
    hint: 'Security deposit',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_101',
    emoji: '🧾',
    question: '¿Qué documento prueba tu pago?',
    options: ['la factura', 'el recibo', 'el comprobante'],
    correctAnswer: 'la factura',
    hint: 'Invoice or receipt',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_102',
    emoji: '🆔',
    question: '¿Qué documento muestras al hacer check-in?',
    options: ['la identificación', 'el DNI', 'la cédula'],
    correctAnswer: 'la identificación',
    hint: 'ID card or passport',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_103',
    emoji: '🛂',
    question: '¿Qué documento necesitas para viajar?',
    options: ['el pasaporte', 'el pasaporte internacional', 'los papeles'],
    correctAnswer: 'el pasaporte',
    hint: 'Passport for international travel',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_104',
    emoji: '📋',
    question: '¿Qué llenas con tus datos personales?',
    options: ['el formulario de registro', 'la planilla', 'el formulario'],
    correctAnswer: 'el formulario de registro',
    hint: 'Registration form with personal info',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_105',
    emoji: '⭐',
    question: '¿Qué hotel tiene el mejor servicio?',
    options: ['el hotel de cinco estrellas', 'el hotel 5 estrellas', 'el hotel de lujo'],
    correctAnswer: 'el hotel de cinco estrellas',
    hint: 'Five-star luxury hotel',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_106',
    emoji: '🏨',
    question: '¿Qué alojamiento es barato para jóvenes?',
    options: ['el hostal', 'el albergue', 'el albergue juvenil'],
    options: ['el hostal', 'el albergue', 'el albergue juvenil'],
    correctAnswer: 'el hostal',
    hint: 'Hostel for budget travelers',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_107',
    emoji: '🏖️',
    question: '¿Qué hotel está en la playa con todo incluido?',
    options: ['el resort', 'el complejo turístico', 'el hotel de playa'],
    correctAnswer: 'el resort',
    hint: 'Beach resort with all-inclusive',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_108',
    emoji: '🛣️',
    question: '¿Qué alojamiento está en la carretera?',
    options: ['el motel', 'el motor hotel', 'el hotel de carretera'],
    correctAnswer: 'el motel',
    hint: 'Roadside motel for travelers',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_109',
    emoji: '🏡',
    question: '¿Qué alojamiento es una casa pequeña?',
    options: ['la cabaña', 'el refugio', 'la casita'],
    correctAnswer: 'la cabaña',
    hint: 'Cabin in nature',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_110',
    emoji: '🏰',
    question: '¿Qué alojamiento es una casa grande y lujosa?',
    options: ['la villa', 'la mansión', 'la casa de lujo'],
    correctAnswer: 'la villa',
    hint: 'Luxury villa or mansion',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_111',
    emoji: '🏠',
    question: '¿Qué alquilas con cocina y sala?',
    options: ['el apartamento', 'el departamento', 'el piso'],
    correctAnswer: 'el apartamento',
    hint: 'Apartment with kitchen',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_112',
    emoji: '🏕️',
    question: '¿Dónde duermes en tienda de campaña?',
    options: ['el camping', 'el campamento', 'el área de acampar'],
    correctAnswer: 'el camping',
    hint: 'Campground for tents',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_113',
    emoji: '🛏️',
    question: '¿Qué incluye el precio de la habitación?',
    options: ['el alojamiento y desayuno', 'la cama y desayuno', 'el B&B'],
    correctAnswer: 'el alojamiento y desayuno',
    hint: 'Bed and breakfast included',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_114',
    emoji: '🍽️',
    question: '¿Qué plan incluye todas las comidas?',
    options: ['la pensión completa', 'el plan completo', 'todas las comidas'],
    correctAnswer: 'la pensión completa',
    hint: 'Full board with all meals',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_115',
    emoji: '🥗',
    question: '¿Qué plan incluye desayuno y cena?',
    options: ['la media pensión', 'el plan medio', 'dos comidas'],
    correctAnswer: 'la media pensión',
    hint: 'Half board - breakfast and dinner',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_116',
    emoji: '🍹',
    question: '¿Qué incluye comidas, bebidas y actividades?',
    options: ['el todo incluido', 'el all-inclusive', 'el plan completo'],
    correctAnswer: 'el todo incluido',
    hint: 'All-inclusive package',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_117',
    emoji: '❌',
    question: '¿Qué haces si no puedes ir?',
    options: ['cancelar la reserva', 'anular la reserva', 'cancelar'],
    correctAnswer: 'cancelar la reserva',
    hint: 'Cancel your reservation',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_118',
    emoji: '📅',
    question: '¿Qué haces si cambias las fechas?',
    options: ['modificar la reserva', 'cambiar la reserva', 'ajustar la reserva'],
    correctAnswer: 'modificar la reserva',
    hint: 'Modify reservation dates',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_119',
    emoji: '✅',
    question: '¿Qué haces para asegurar tu reserva?',
    options: ['confirmar', 'confirmar la reserva', 'asegurar'],
    correctAnswer: 'confirmar',
    hint: 'Confirm your booking',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_120',
    emoji: '⏰',
    question: '¿Qué pides si llegas muy temprano?',
    options: ['el check-in temprano', 'la entrada anticipada', 'el check-in anticipado'],
    correctAnswer: 'el check-in temprano',
    hint: 'Early check-in request',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },

  // Problems & Complaints (30 questions)
  {
    id: 'accommodation_121',
    emoji: '🔧',
    question: '¿Qué no funciona si no hay agua caliente?',
    options: ['el calentador', 'el boiler', 'el termo'],
    correctAnswer: 'el calentador',
    hint: 'Water heater is broken',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_122',
    emoji: '❄️',
    question: '¿Qué está roto si hace mucho calor?',
    options: ['el aire acondicionado', 'el AC', 'el clima'],
    correctAnswer: 'el aire acondicionado',
    hint: 'Air conditioning not working',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_123',
    emoji: '📡',
    question: '¿Qué no funciona si no hay internet?',
    options: ['el wifi', 'el Wi-Fi', 'la conexión'],
    correctAnswer: 'el wifi',
    hint: 'Internet connection problem',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_124',
    emoji: '📺',
    question: '¿Qué problema hay si no ves nada?',
    options: ['la televisión rota', 'el televisor dañado', 'la tele descompuesta'],
    correctAnswer: 'la televisión rota',
    hint: 'TV is not working',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_125',
    emoji: '💡',
    question: '¿Qué se quemó si no hay luz?',
    options: ['el foco', 'la bombilla', 'el bombillo'],
    correctAnswer: 'el foco',
    hint: 'Light bulb burned out',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_126',
    emoji: '🚿',
    question: '¿Qué problema hay si no sale agua?',
    options: ['la tubería tapada', 'la cañería obstruida', 'el desagüe bloqueado'],
    correctAnswer: 'la tubería tapada',
    hint: 'Clogged pipes or plumbing issue',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_127',
    emoji: '🚽',
    question: '¿Qué problema hay si el agua no baja?',
    options: ['el inodoro tapado', 'el retrete obstruido', 'el váter bloqueado'],
    correctAnswer: 'el inodoro tapado',
    hint: 'Toilet is clogged',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_128',
    emoji: '🧹',
    question: '¿Qué problema hay si está sucia?',
    options: ['la habitación no limpiada', 'el cuarto sucio', 'la habitación sin limpiar'],
    correctAnswer: 'la habitación no limpiada',
    hint: 'Room not cleaned',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_129',
    emoji: '🦟',
    question: '¿Qué problema hay con insectos?',
    options: ['los mosquitos', 'los zancudos', 'los bichos'],
    correctAnswer: 'los mosquitos',
    hint: 'Mosquitoes in room',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_130',
    emoji: '🔊',
    question: '¿Qué problema hay si escuchas a los vecinos?',
    options: ['el mucho ruido', 'el ruido excesivo', 'el escándalo'],
    options: ['el mucho ruido', 'el ruido excesivo', 'el escándalo'],
    correctAnswer: 'el mucho ruido',
    hint: 'Too much noise',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_131',
    emoji: '🛏️',
    question: '¿Qué problema hay si no descansas bien?',
    options: ['la cama incómoda', 'el colchón duro', 'la cama mala'],
    correctAnswer: 'la cama incómoda',
    hint: 'Uncomfortable bed',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_132',
    emoji: '🧴',
    question: '¿Qué falta en el baño?',
    options: ['los artículos de tocador', 'las amenidades', 'los productos de baño'],
    correctAnswer: 'los artículos de tocador',
    hint: 'Toiletries missing',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_133',
    emoji: '🧻',
    question: '¿Qué necesitas más en el baño?',
    options: ['el papel higiénico', 'el papel de baño', 'el papel sanitario'],
    correctAnswer: 'el papel higiénico',
    hint: 'Need more toilet paper',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_134',
    emoji: '🧖',
    question: '¿Qué necesitas más para secarte?',
    options: ['las toallas', 'las toallas de baño', 'las toallitas'],
    correctAnswer: 'las toallas',
    hint: 'Need more towels',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_135',
    emoji: '🛏️',
    question: '¿Qué necesitas cambiar si están sucias?',
    options: ['las sábanas', 'la ropa de cama', 'las cobijas'],
    correctAnswer: 'las sábanas',
    hint: 'Dirty sheets need changing',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_136',
    emoji: '🔑',
    question: '¿Qué problema hay si no abre la puerta?',
    options: ['la llave no funciona', 'la tarjeta no sirve', 'la llave está dañada'],
    correctAnswer: 'la llave no funciona',
    hint: 'Key card not working',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_137',
    emoji: '🚪',
    question: '¿Qué problema hay si no cierra bien?',
    options: ['la puerta rota', 'la puerta dañada', 'la cerradura mala'],
    correctAnswer: 'la puerta rota',
    hint: 'Door doesn\'t close properly',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_138',
    emoji: '🪟',
    question: '¿Qué no se puede abrir?',
    options: ['la ventana atascada', 'la ventana trabada', 'la ventana bloqueada'],
    correctAnswer: 'la ventana atascada',
    hint: 'Window is stuck',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_139',
    emoji: '🔒',
    question: '¿Qué problema de seguridad hay?',
    options: ['la cerradura rota', 'el seguro dañado', 'la cerradura mala'],
    correctAnswer: 'la cerradura rota',
    hint: 'Lock is broken',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_140',
    emoji: '😤',
    question: '¿Qué haces si no estás satisfecho?',
    options: ['hacer una queja', 'presentar un reclamo', 'quejarse'],
    correctAnswer: 'hacer una queja',
    hint: 'Make a complaint',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_141',
    emoji: '🔄',
    question: '¿Qué pides si la habitación tiene problemas?',
    options: ['el cambio de habitación', 'la nueva habitación', 'otra habitación'],
    correctAnswer: 'el cambio de habitación',
    hint: 'Request room change',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_142',
    emoji: '💵',
    question: '¿Qué pides si el servicio fue malo?',
    options: ['el reembolso', 'la devolución', 'el dinero de vuelta'],
    correctAnswer: 'el reembolso',
    hint: 'Request refund for bad service',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_143',
    emoji: '🆓',
    question: '¿Qué te dan si hubo un problema?',
    options: ['el descuento', 'la rebaja', 'el descuento compensatorio'],
    correctAnswer: 'el descuento',
    hint: 'Discount for inconvenience',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_144',
    emoji: '⬆️',
    question: '¿Qué mejora te dan sin costo?',
    options: ['la mejora de habitación', 'el upgrade', 'la mejora gratis'],
    correctAnswer: 'la mejora de habitación',
    hint: 'Free room upgrade',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_145',
    emoji: '🛠️',
    question: '¿Quién arregla cosas rotas?',
    options: ['el mantenimiento', 'el personal de mantenimiento', 'el técnico'],
    correctAnswer: 'el mantenimiento',
    hint: 'Maintenance staff fixes things',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
  {
    id: 'accommodation_146',
    emoji: '⏱️',
    question: '¿Qué pides si quieres quedarte más tarde?',
    options: ['el check-out tardío', 'la salida tardía', 'el check-out extendido'],
    correctAnswer: 'el check-out tardío',
    hint: 'Late check-out request',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_147',
    emoji: '🧳',
    question: '¿Dónde guardas las maletas después del check-out?',
    options: ['la custodia de equipaje', 'el guardaequipaje', 'el depósito de maletas'],
    correctAnswer: 'la custodia de equipaje',
    hint: 'Luggage storage service',
    points: 15,
    category: 'accommodation',
    difficulty: 'hard',
  },
  {
    id: 'accommodation_148',
    emoji: '🔎',
    question: '¿Qué haces si perdiste algo?',
    options: ['reportar objetos perdidos', 'ir a objetos perdidos', 'reportar la pérdida'],
    correctAnswer: 'reportar objetos perdidos',
    hint: 'Report to lost and found',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_149',
    emoji: '📝',
    question: '¿Qué dejas al final de tu estancia?',
    options: ['la reseña', 'la opinión', 'el comentario'],
    correctAnswer: 'la reseña',
    hint: 'Write a review of your stay',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_150',
    emoji: '⭐',
    question: '¿Cuántas estrellas das si estuvo excelente?',
    options: ['cinco estrellas', '5 estrellas', 'las cinco estrellas'],
    correctAnswer: 'cinco estrellas',
    hint: 'Five stars for excellent service',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },

  // Additional Accommodation Phrases (5 questions)
  {
    id: 'accommodation_151',
    emoji: '💺',
    question: '¿Cómo preguntas "Can I sit here?"',
    options: ['¿puedo sentarme aquí?', '¿me puedo sentar aquí?', '¿puedo estar aquí?'],
    correctAnswer: '¿puedo sentarme aquí?',
    hint: 'Can I sit here? - "puedo" (can I), "sentarme" (sit myself - reflexive), "aquí" (here)',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_152',
    emoji: '🍽️',
    question: '¿Cómo preguntas "When do you open the restaurant?"',
    options: ['¿cuándo abren el restaurante?', '¿a qué hora abren el restaurante?', '¿cuándo abre el restaurante?'],
    correctAnswer: '¿cuándo abren el restaurante?',
    hint: 'When do you open - "cuándo" (when), "abren" (you all open - 3rd person plural for business)',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_153',
    emoji: '🚪',
    question: '¿Cómo dices "I need to checkout"?',
    options: ['necesito hacer el checkout', 'necesito salir de la habitación', 'tengo que hacer checkout'],
    correctAnswer: 'necesito hacer el checkout',
    hint: 'I need to checkout - "necesito" (I need), "hacer el checkout" (do checkout), also "check-out"',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_154',
    emoji: '🚕',
    question: '¿Cómo preguntas "Can you call me a taxi?"',
    options: ['¿puede llamarme un taxi?', '¿me puede llamar un taxi?', '¿podría llamarme un taxi?'],
    correctAnswer: '¿puede llamarme un taxi?',
    hint: 'Can you call me a taxi? - "puede" (can you formal), "llamarme" (call me), "un taxi" (a taxi)',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_155',
    emoji: '🧴',
    question: '¿Cómo dices "We need towels"?',
    options: ['necesitamos toallas', 'nos hacen falta toallas', 'queremos toallas'],
    correctAnswer: 'necesitamos toallas',
    hint: 'We need towels - "necesitamos" (we need), "toallas" (towels), common hotel request',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_156',
    emoji: '🛀🏻',
    question: '¿Qué pides si quieres relajarte con un baño?',
    options: ['una habitación con bañera', 'un cuarto con tina', 'una habitación con baño completo'],
    correctAnswer: 'una habitación con bañera',
    hint: 'Room with bathtub - for relaxing soaks, not just shower, luxury amenity in hotels',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_157',
    emoji: '🪠',
    question: '¿Qué usas para destapar el inodoro?',
    options: ['el destapacaños', 'el desatascador', 'la bomba de baño'],
    correctAnswer: 'el destapacaños',
    hint: 'Plunger - for unclogging toilets, "desatascador" in Spain, essential bathroom tool',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_158',
    emoji: '🏚',
    question: '¿Cómo describes un alojamiento en mal estado?',
    options: ['está deteriorado', 'está abandonado', 'está descuidado'],
    correctAnswer: 'está deteriorado',
    hint: 'Run-down/deteriorated - old and in poor condition, needs repairs and maintenance',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_159',
    emoji: '💆🏻‍♀️',
    question: '¿Qué servicio de relajación reservas en el spa del hotel?',
    options: ['un masaje', 'una sesión de yoga', 'un tratamiento facial'],
    correctAnswer: 'un masaje',
    hint: 'Massage - relaxation service at hotel spa, therapeutic bodywork',
    points: 10,
    category: 'accommodation',
    difficulty: 'medium',
  },
  {
    id: 'accommodation_160',
    emoji: '👨🏻‍💻',
    question: '¿Qué necesitas para conectarte a internet en el hotel?',
    options: ['el wifi', 'el televisor', 'el teléfono'],
    correctAnswer: 'el wifi',
    hint: 'WiFi - wireless internet connection, most hotels provide free WiFi access',
    points: 5,
    category: 'accommodation',
    difficulty: 'easy',
  },
];
