/**
 * Animals Category Questions
 * Category: animals
 */

export const animalsQuestions = [
{
    id: 'animals_001',
    emoji: '🐕',
    question: '¿Cuál es un animal doméstico común?',
    options: ['el perro', 'el lobo', 'el zorro'],
    correctAnswer: 'el perro',
    hint: 'Dog - man\'s best friend, "canis" in Latin',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_002',
    emoji: '🐈',
    question: '¿Qué animal dice "miau"?',
    options: ['el gato', 'el ratón', 'el loro'],
    correctAnswer: 'el gato',
    hint: 'Cat - independent pet, "felino" in scientific terms',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_003',
    emoji: '🐭',
    question: '¿Qué animal pequeño vive en las casas?',
    options: ['el ratón', 'la hormiga', 'la cucaracha'],
    correctAnswer: 'el ratón',
    hint: 'Mouse - small rodent, "ratoncillo" is diminutive',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_004',
    emoji: '🐀',
    question: '¿Qué roedor es más grande que el ratón?',
    options: ['la rata', 'el hamster', 'el conejillo de indias'],
    correctAnswer: 'la rata',
    hint: 'Rat - larger rodent, intelligent, often kept as pets',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_005',
    emoji: '🐹',
    question: '¿Qué roedor pequeño tiene bolsas en las mejillas?',
    options: ['el hamster', 'el ratón', 'el gerbil'],
    correctAnswer: 'el hamster',
    hint: 'Hamster - small rodent, cheek pouches, stores food, popular pet',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_006',
    emoji: '🐿️',
    question: '¿Qué animal come frutos secos en el árbol?',
    options: ['la ardilla', 'el pájaro', 'la catarita'],
    correctAnswer: 'la ardilla',
    hint: 'Squirrel - bushy tail, climbs trees, collects nuts',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_007',
    emoji: '🐇',
    question: '¿Qué animal tiene orejas largas?',
    options: ['el conejo', 'el venado', 'la cabra'],
    correctAnswer: 'el conejo',
    hint: 'Rabbit - hops around, "conej�🐇illo de indias" is guinea pig',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_005',
    emoji: '🦁',
    question: '¿Cuál es el rey de la selva?',
    options: ['el león', 'el tigre', 'el elefante'],
    correctAnswer: 'el león',
    hint: 'Lion - has a mane, roars loudly, symbol of courage',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_006',
    emoji: '🐯',
    question: '¿Qué animal tiene rayas naranjas?',
    options: ['el tigre', 'el leopardo', 'el gato montés'],
    correctAnswer: 'el tigre',
    hint: 'Tiger - striped big cat, endangered species',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_007',
    emoji: '🐘',
    question: '¿Qué animal tiene una trompa?',
    options: ['el elefante', 'la jirafa', 'el cocodrilo'],
    correctAnswer: 'el elefante',
    hint: 'Elephant - largest land animal, has tusks',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_008',
    emoji: '🦒',
    question: '¿Qué animal tiene el cuello más largo?',
    options: ['la jirafa', 'el avestruz', 'la llama'],
    correctAnswer: 'la jirafa',
    hint: 'Giraffe - tallest land animal, African herbivore',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_009',
    emoji: '🦓',
    question: '¿Qué animal tiene rayas blancas y negras?',
    options: ['la cebra', 'el caballo', 'el burro'],
    correctAnswer: 'la cebra',
    hint: 'Zebra - related to horses, African animal, striped',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_010',
    emoji: '🦏',
    question: '¿Qué animal tiene un cuerno en la nariz?',
    options: ['el rinoceronte', 'el alce', 'el búfalo'],
    correctAnswer: 'el rinoceronte',
    hint: 'Rhinoceros - large African animal, endangered',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_011',
    emoji: '🐻',
    question: '¿Qué animal grande vive en el bosque?',
    options: ['el oso', 'el ciervo', 'el puma'],
    correctAnswer: 'el oso',
    hint: 'Bear - large mammal, hibernates in winter',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_012',
    emoji: '🦊',
    question: '¿Qué animal es parecido al perro pero salvaje?',
    options: ['el zorro', 'el lobo', 'el chacal'],
    correctAnswer: 'el zorro',
    hint: 'Fox - cunning animal, reddish fur, similar to dog',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_013',
    emoji: '🐺',
    question: '¿Qué animal aúlla a la luna?',
    options: ['el lobo', 'el perro', 'el coyote'],
    correctAnswer: 'el lobo',
    hint: 'Wolf - wild canine, hunts in packs, endangered in many places',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_014',
    emoji: '🐄',
    question: '¿Qué animal produce leche?',
    options: ['la vaca', 'la oveja', 'la cabra'],
    correctAnswer: 'la vaca',
    hint: 'Cow - dairy animal, bovine, "ternera" for calf',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_015',
    emoji: '🐷',
    question: '¿Qué animal tiene cola rizada?',
    options: ['el cerdo', 'el cordero', 'el caballo'],
    correctAnswer: 'el cerdo',
    hint: 'Pig - farm animal, curly tail, "cochinillo" for piglet',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_016',
    emoji: '🐑',
    question: '¿Qué animal produce lana?',
    options: ['la oveja', 'la cabra', 'el cerdo'],
    correctAnswer: 'la oveja',
    hint: 'Sheep - woolly farm animal, "carnero" for ram',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_017',
    emoji: '🐐',
    question: '¿Qué animal trepa bien en las montañas?',
    options: ['la cabra', 'el cordero', 'la oveja'],
    correctAnswer: 'la cabra',
    hint: 'Goat - climbs steep terrain, agile, produces milk',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_018',
    emoji: '🐴',
    question: '¿Qué animal montas para viajar?',
    options: ['el caballo', 'el burro', 'el camello'],
    correctAnswer: 'el caballo',
    hint: 'Horse - large hoofed animal, rides quickly, "yegua" for mare',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_019',
    emoji: '🦘',
    question: '¿Qué animal salta y viene de Australia?',
    options: ['el canguro', 'el koala', 'el wombat'],
    correctAnswer: 'el canguro',
    hint: 'Kangaroo - jumps on hind legs, Australian, carries baby in pouch',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_020',
    emoji: '🐨',
    question: '¿Qué animal come eucalipto?',
    options: ['el koala', 'el canguro', 'el oso panda'],
    correctAnswer: 'el koala',
    hint: 'Koala - looks like bear, eats eucalyptus leaves, Australian marsupial',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_021',
    emoji: '🐼',
    question: '¿Qué animal gigante es blanco y negro?',
    options: ['el oso panda', 'el oso polar', 'el tejón'],
    correctAnswer: 'el oso panda',
    hint: 'Panda - endangered, eats bamboo, from China',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_022',
    emoji: '🐍',
    question: '¿Qué animal doméstico es una mascotas en casas?',
    options: ['la serpiente', 'el cocodrilo', 'el iguana'],
    correctAnswer: 'la serpiente',
    hint: 'Snake - can be kept as exotic pet, some docile species',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_023',
    emoji: '🦁',
    question: '¿Cuál es el felino salvaje más grande de América?',
    options: ['el puma', 'el jaguár', 'el ocelote'],
    correctAnswer: 'el jaguár',
    hint: 'Jaguar - spotted big cat, largest cat in Americas, endangered',
    points: 10,
    category: 'animals',
    difficulty: 'medium',
  },
  {
    id: 'animals_024',
    emoji: '🐒',
    question: '¿Qué animal es parecido a los humanos?',
    options: ['el mono', 'el simio', 'el chimpancé'],
    correctAnswer: 'el mono',
    hint: 'Monkey - primate with tail, swings in trees, intelligent',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_025',
    emoji: '🦍',
    question: '¿Qué primate grande tiene brazos muy largos?',
    options: ['el gorila', 'el orangután', 'el chimpancé'],
    correctAnswer: 'el gorila',
    hint: 'Gorilla - largest primate, endangered, knuckle-walks, very strong',
    points: 10,
    category: 'animals',
    difficulty: 'medium',
  },
  {
    id: 'animals_026',
    emoji: '🦅',
    question: '¿Qué pájaro grande vuela muy alto?',
    options: ['el águila', 'el halcón', 'el cóndor'],
    correctAnswer: 'el águila',
    hint: 'Eagle - large bird of prey, symbol of strength and freedom',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_027',
    emoji: '🦉',
    question: '¿Qué pájaro ve bien de noche?',
    options: ['el búho', 'la lechuza', 'el cuervo'],
    correctAnswer: 'el búho',
    hint: 'Owl - nocturnal bird of prey, large eyes, rotates head',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_028',
    emoji: '🦜',
    question: '¿Qué pájaro colorido puede hablar?',
    options: ['el loro', 'el papagayo', 'el periquito'],
    correctAnswer: 'el loro',
    hint: 'Parrot - intelligent, colorful, mimics sounds and words',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_029',
    emoji: '🦆',
    question: '¿Qué pájaro acuático tiene pico plano?',
    options: ['el pato', 'la gaviota', 'el cisne'],
    correctAnswer: 'el pato',
    hint: 'Duck - waterfowl, quacks, waddles on land',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_030',
    emoji: '🦢',
    question: '¿Qué pájaro blanco es elegante?',
    options: ['el cisne', 'el pato', 'la gaviota'],
    correctAnswer: 'el cisne',
    hint: 'Swan - large water bird, elegant, white or black species',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_031',
    emoji: '🦚',
    question: '¿Qué pájaro tiene plumas de muchos colores?',
    options: ['el pavo real', 'el loro', 'el faisán'],
    correctAnswer: 'el pavo real',
    hint: 'Peacock - displays colorful feathers, Indian bird, very beautiful',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_032',
    emoji: '🐢',
    question: '¿Qué animal tiene caparazón?',
    options: ['la tortuga', 'el cangrejo', 'el caracol'],
    correctAnswer: 'la tortuga',
    hint: 'Turtle - reptile with hard shell, can live long time',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_033',
    emoji: '🦎',
    question: '¿Qué animal pequeño tiene cola larga?',
    options: ['la lagartija', 'el camaleón', 'la iguana'],
    correctAnswer: 'la lagartija',
    hint: 'Lizard - small reptile, can detach tail, sunbathes',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_034',
    emoji: '🐊',
    question: '¿Qué animal verde vive en el río?',
    options: ['el cocodrilo', 'la serpiente', 'la tortuga'],
    correctAnswer: 'el cocodrilo',
    hint: 'Crocodile - large reptile, sharp teeth, ancient predator',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_035',
    emoji: '🐙',
    question: '¿Qué animal marino tiene ocho brazos?',
    options: ['el pulpo', 'la medusa', 'el calamar'],
    correctAnswer: 'el pulpo',
    hint: 'Octopus - eight tentacles, intelligent, changes color',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_036',
    emoji: '🦑',
    question: '¿Qué animal marino parece el pulpo?',
    options: ['el calamar', 'la medusa', 'el caracol'],
    correctAnswer: 'el calamar',
    hint: 'Squid - similar to octopus, ten tentacles, emits ink',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_037',
    emoji: '🐠',
    question: '¿Qué animal vive en el agua?',
    options: ['el pez', 'el pescado', 'la aleta'],
    correctAnswer: 'el pez',
    hint: 'Fish - aquatic animal, has gills and fins, "pescado" means cooked fish',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_038',
    emoji: '🦈',
    question: '¿Qué pez es peligroso?',
    options: ['el tiburón', 'la sardina', 'la trucha'],
    correctAnswer: 'el tiburón',
    hint: 'Shark - dangerous predator, sharp teeth, appears in all oceans',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_039',
    emoji: '🐋',
    question: '¿Qué animal marino es el más grande?',
    options: ['la ballena', 'el tiburón', 'el delfín'],
    correctAnswer: 'la ballena',
    hint: 'Whale - largest animal on Earth, marine mammal, endangered species',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_040',
    emoji: '🐬',
    question: '¿Qué animal marino es inteligente y amigable?',
    options: ['el delfín', 'la ballena', 'el tiburón'],
    correctAnswer: 'el delfín',
    hint: 'Dolphin - intelligent marine mammal, friendly to humans, playful',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_041',
    emoji: '🦭',
    question: '¿Qué animal tiene bigotes y vive en el hielo?',
    options: ['la foca', 'la morsa', 'el oso polar'],
    correctAnswer: 'la foca',
    hint: 'Seal - marine mammal, whiskers, lives in cold waters',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_042',
    emoji: '🦀',
    question: '¿Qué animal tiene diez patas?',
    options: ['el cangrejo', 'el camarón', 'la langosta'],
    correctAnswer: 'el cangrejo',
    hint: 'Crab - crustacean with claws, walks sideways, edible',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_043',
    emoji: '🦞',
    question: '¿Qué animal parece un cangrejo grande?',
    options: ['la langosta', 'el camarón', 'la ostra'],
    correctAnswer: 'la langosta',
    hint: 'Lobster - large crustacean, delicacy, expensive',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_044',
    emoji: '🦗',
    question: '¿Qué insecto hace ruido por la noche?',
    options: ['el grillo', 'la cigarra', 'el saltamontes'],
    correctAnswer: 'el grillo',
    hint: 'Cricket - insect, chirps at night, jumps, used in sports',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_045',
    emoji: '🦋',
    question: '¿Qué insecto tiene alas coloridas?',
    options: ['la mariposa', 'la polilla', 'la libélula'],
    correctAnswer: 'la mariposa',
    hint: 'Butterfly - colorful insect, goes through metamorphosis',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_046',
    emoji: '🐝',
    question: '¿Qué insecto produce miel?',
    options: ['la abeja', 'la avispa', 'el abejorro'],
    correctAnswer: 'la abeja',
    hint: 'Bee - produces honey, pollinates flowers, lives in colonies',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_047',
    emoji: '🐜',
    question: '¿Qué insecto pequeño trabaja en equipo?',
    options: ['la hormiga', 'la termita', 'el escarabajo'],
    correctAnswer: 'la hormiga',
    hint: 'Ant - social insect, works in colonies, carries leaves',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_048',
    emoji: '🦗',
    question: '¿Qué insecto salta alto?',
    options: ['el saltamontes', 'la cucaracha', 'el escarabajo'],
    correctAnswer: 'el saltamontes',
    hint: 'Grasshopper - jumps far, green color, eats plants',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_049',
    emoji: '🐛',
    question: '¿Cuál es la larva de la mariposa?',
    options: ['la oruga', 'la pupa', 'el gusano'],
    correctAnswer: 'la oruga',
    hint: 'Caterpillar - larva stage of butterfly, eats leaves, colorful',
    points: 10,
    category: 'animals',
    difficulty: 'medium',
  },
  {
    id: 'animals_050',
    emoji: '🦇',
    question: '¿Qué animal vuela de noche?',
    options: ['el murciélago', 'el búho', 'la lechuza'],
    correctAnswer: 'el murciélago',
    hint: 'Bat - only mammal that flies, uses echolocation, nocturnal',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_058',
    emoji: '🦢',
    question: '¿Qué pájaro blanco es elegante?',
    options: ['el cisne', 'el pato', 'la gaviota'],
    correctAnswer: 'el cisne',
    hint: 'Swan - large water bird, elegant, white or black species',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_059',
    emoji: '🦚',
    question: '¿Qué pájaro tiene plumas de muchos colores?',
    options: ['el pavo real', 'el loro', 'el faisán'],
    correctAnswer: 'el pavo real',
    hint: 'Peacock - displays colorful feathers, Indian bird, very beautiful',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_060',
    emoji: '🐢',
    question: '¿Qué animal tiene caparazón?',
    options: ['la tortuga', 'el cangrejo', 'el caracol'],
    correctAnswer: 'la tortuga',
    hint: 'Turtle - reptile with hard shell, can live long time',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_061',
    emoji: '🦃',
    question: '¿Qué ave grande se come tradicionalmente en Acción de Gracias?',
    options: ['el pavo', 'el pollo', 'el ganso'],
    correctAnswer: 'el pavo',
    hint: 'Turkey - large bird traditionally eaten at Thanksgiving and Christmas',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_062',
    emoji: '🐂',
    question: '¿Cómo se llama la vaca macho?',
    options: ['el toro', 'el buey', 'el carnero'],
    correctAnswer: 'el toro',
    hint: 'Bull - male cow, strong and powerful animal',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_063',
    emoji: '🐓',
    question: '¿Cómo se llama el pollo macho que canta por la mañana?',
    options: ['el gallo', 'el pollo', 'el pavo'],
    correctAnswer: 'el gallo',
    hint: 'Rooster - male chicken, crows at dawn, has colorful feathers',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_064',
    emoji: '🐔',
    question: '¿Qué ave de granja pone huevos?',
    options: ['la gallina', 'el gallo', 'el pato'],
    correctAnswer: 'la gallina',
    hint: 'Chicken/Hen - farm bird, lays eggs, female of rooster',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_065',
    emoji: '🐣',
    question: '¿Cómo se llama el bebé que sale del huevo?',
    options: ['el pollito', 'el patito', 'el pajarito'],
    correctAnswer: 'el pollito',
    hint: 'Chick - baby bird that hatches from egg, young chicken',
    points: 5,
    category: 'animals',
    difficulty: 'easy',
  },
];
