/**
 * BEACH & ACTIVITIES Category Questions
 * Category: beach
 */

export const beachQuestions = [
{
    id: 'beach_001',
    emoji: '🏖️',
    question: '¿Qué lugar es?',
    options: ['la playa', 'la costa', 'la orilla'],
    correctAnswer: 'la playa',
    hint: 'Beach - sandy shore by ocean, from Latin "plagia" (shore)',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_002',
    emoji: '🏊',
    question: '¿Qué actividad es?',
    options: ['nadar', 'la natación', 'ir a nadar'],
    correctAnswer: 'nadar',
    hint: 'Swim - water movement, from Latin "natare", essential beach activity',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_003',
    emoji: '🏄',
    question: '¿Qué actividad es?',
    options: ['surf', 'hacer surf', 'el surf'],
    correctAnswer: 'surf',
    hint: 'Surfing - ride waves on board, popular in Spain and Mexico',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_004',
    emoji: '🤿',
    question: '¿Qué actividad es?',
    options: ['bucear', 'el buceo', 'hacer snorkel'],
    correctAnswer: 'bucear',
    hint: 'Dive - explore underwater with mask and snorkel, Caribbean excellent',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_005',
    emoji: '☀️',
    question: '¿Qué brilla en el cielo y da calor?',
    options: ['el sol', 'el astro rey', 'el sol ardiente'],
    correctAnswer: 'el sol',
    hint: 'Sun - provides light and heat, "tomar el sol" means sunbathe',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_006',
    emoji: '🌊',
    question: '¿Qué forma el mar cuando se mueve?',
    options: ['la ola', 'la onda', 'el oleaje'],
    correctAnswer: 'la ola',
    hint: 'Wave - moving water, surfers love big waves, from Latin "unda"',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_007',
    emoji: '🏝️',
    question: '¿Qué lugar es?',
    options: ['la isla', 'el islote', 'el atolón'],
    correctAnswer: 'la isla',
    hint: 'Island - land surrounded by water, Canary Islands famous in Spain',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_008',
    emoji: '⛱️',
    question: '¿Qué usas para dar sombra en la playa?',
    options: ['la sombrilla', 'el parasol', 'la sombrilla de playa'],
    correctAnswer: 'la sombrilla',
    hint: 'Beach umbrella - provides shade, "paraguas" for rain',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_009',
    emoji: '🩱',
    question: '¿Qué ropa es?',
    options: ['el traje de baño', 'el bañador', 'el swimsuit'],
    correctAnswer: 'el traje de baño',
    hint: 'Swimsuit - "bañador" also used, essential for swimming',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_010',
    emoji: '🕶️',
    question: '¿Qué proteges tus ojos del sol con esto?',
    options: ['las gafas de sol', 'los lentes de sol', 'los anteojos de sol'],
    correctAnswer: 'las gafas de sol',
    hint: 'Sunglasses - protect eyes from UV rays, "lentes de sol" in Latin America',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_011',
    emoji: '🧴',
    question: '¿Qué necesitas en la playa?',
    options: ['el protector solar', 'el bloqueador solar', 'la crema solar'],
    correctAnswer: 'el protector solar',
    hint: 'Sunscreen - prevents sunburn, SPF 30+ recommended, "bloqueador solar" also used',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_012',
    emoji: '🏐',
    question: '¿Qué deporte es?',
    options: ['el voleibol', 'el vóley', 'el vóleibol'],
    correctAnswer: 'el voleibol',
    hint: 'Volleyball - beach sport with net, "vóley playa" is beach volleyball',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_013',
    emoji: '🐚',
    question: '¿Qué coleccionas en la arena?',
    options: ['la concha', 'la concha marina', 'el caracol marino'],
    correctAnswer: 'la concha',
    hint: 'Seashell - former mollusk home, beautiful to collect on beach',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_014',
    emoji: '🌴',
    question: '¿Qué árbol es?',
    options: ['la palmera', 'la palma', 'el cocotero'],
    correctAnswer: 'la palmera',
    hint: 'Palm tree - tropical tree, provides coconuts and shade at beach',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_015',
    emoji: '🥥',
    question: '¿Qué fruta es?',
    options: ['el coco', 'el coco verde', 'la nuez de coco'],
    correctAnswer: 'el coco',
    hint: 'Coconut - tropical fruit from palm tree, agua de coco refreshing',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  
  // Water Activities (20 questions)
  {
    id: 'beach_016',
    emoji: '🏊',
    question: '¿Qué estás haciendo?',
    options: ['nadar', 'la natación', 'bañarse'],
    correctAnswer: 'nadar',
    hint: 'Swimming - propelling through water, good exercise and fun',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_017',
    emoji: '🏄',
    question: '¿Qué deporte es?',
    options: ['surf', 'hacer surf', 'el surf'],
    correctAnswer: 'surf',
    hint: 'Surfing - riding waves on board, originated in Polynesia, popular worldwide',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_018',
    emoji: '🤿',
    question: '¿Qué actividad es?',
    options: ['bucear', 'el buceo', 'hacer snorkel'],
    correctAnswer: 'bucear',
    hint: 'Diving - underwater exploration with mask, snorkel, or scuba gear',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_019',
    emoji: '⛵',
    question: '¿Qué barco usa el viento para moverse?',
    options: ['el velero', 'el bote de vela', 'la embarcación de vela'],
    correctAnswer: 'el velero',
    hint: 'Sailboat - wind-powered vessel, "vela" is sail, eco-friendly navigation',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_020',
    emoji: '🚤',
    question: '¿Qué tipo de barco es?',
    options: ['la lancha', 'la lancha motora', 'la lancha rápida'],
    correctAnswer: 'la lancha',
    hint: 'Motorboat - fast speedboat, "lancha rápida" for speed, popular for water sports',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_021',
    emoji: '🛶',
    question: '¿Qué embarcación es?',
    options: ['la canoa', 'la piragua', 'el kayak'],
    correctAnswer: 'la canoa',
    hint: 'Canoe - small paddle boat, indigenous origin, "piragua" also used',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_022',
    emoji: '🎣',
    question: '¿Qué actividad es?',
    options: ['pescar', 'la pesca', 'ir de pesca'],
    correctAnswer: 'pescar',
    hint: 'Fishing - catching fish with rod and bait, relaxing beach activity',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_023',
    emoji: '🐟',
    question: '¿Qué animal es?',
    options: ['el pez', 'el pescado', 'el pececillo'],
    correctAnswer: 'el pez',
    hint: 'Fish - aquatic animal with gills, "pescado" when caught for food',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_024',
    emoji: '🐠',
    question: '¿Qué pez colorido vive en aguas cálidas?',
    options: ['el pez tropical', 'el pez de colores', 'el pez exótico'],
    correctAnswer: 'el pez tropical',
    hint: 'Tropical fish - colorful warm-water fish, beautiful in coral reefs',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_025',
    emoji: '🦈',
    question: '¿Qué animal marino es?',
    options: ['el tiburón', 'el escualo', 'el jaquetón'],
    correctAnswer: 'el tiburón',
    hint: 'Shark - apex predator, from "tiburón" (ancient Taíno word)',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_026',
    emoji: '🐬',
    question: '¿Qué animal marino es?',
    options: ['el delfín', 'el delfín nariz de botella', 'el cetáceo'],
    correctAnswer: 'el delfín',
    hint: 'Dolphin - intelligent mammal, friendly and playful, from Greek "delphis"',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_027',
    emoji: '🐳',
    question: '¿Qué animal es?',
    options: ['la ballena', 'el cetáceo', 'la ballena azul'],
    correctAnswer: 'la ballena',
    hint: 'Whale - largest animal on Earth, blue whale can reach 30m long',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_028',
    emoji: '🦀',
    question: '¿Qué criatura es?',
    options: ['el cangrejo', 'el crustáceo', 'la jaiba'],
    correctAnswer: 'el cangrejo',
    hint: 'Crab - walks sideways, has claws, hides in sand on beach',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_029',
    emoji: '🦞',
    question: '¿Qué marisco es?',
    options: ['la langosta', 'el bogavante', 'la langosta de mar'],
    correctAnswer: 'la langosta',
    hint: 'Lobster - expensive seafood delicacy, red when cooked',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_030',
    emoji: '🦑',
    question: '¿Qué criatura marina es?',
    options: ['el calamar', 'la jibia', 'el chipirón'],
    correctAnswer: 'el calamar',
    hint: 'Squid - has tentacles and shoots ink for defense, calamari dish',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_031',
    emoji: '🐙',
    question: '¿Qué animal marino es?',
    options: ['el pulpo', 'el pulpo común', 'el cefalópodo'],
    correctAnswer: 'el pulpo',
    hint: 'Octopus - eight arms, highly intelligent, can change color',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_032',
    emoji: '🪼',
    question: '¿Qué animal marino puede picar?',
    options: ['la medusa', 'la aguamala', 'la aguaviva'],
    correctAnswer: 'la medusa',
    hint: 'Jellyfish - can sting, gelatinous body, "aguamala" in some regions',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_033',
    emoji: '⭐',
    question: '¿Qué es esto del mar?',
    options: ['la estrella de mar', 'el asteroidea', 'la estrella marina'],
    correctAnswer: 'la estrella de mar',
    hint: 'Starfish - five-pointed sea creature, can regenerate lost arms',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_034',
    emoji: '🐚',
    question: '¿Qué encuentras en la playa?',
    options: ['la concha', 'la concha marina', 'el caracol'],
    correctAnswer: 'la concha',
    hint: 'Seashell - mollusk\'s former home, makes ocean sound when held to ear',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_035',
    emoji: '🌊',
    question: '¿Qué montan los surfistas?',
    options: ['la ola', 'la onda', 'el oleaje'],
    correctAnswer: 'la ola',
    hint: 'Wave - moving water ridge, surfers ride them, "oleaje" is surf',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  
  // Beach Equipment & Items (20 questions)
  {
    id: 'beach_036',
    emoji: '🏖️',
    question: '¿Qué pones en la arena para dar sombra?',
    options: ['la sombrilla de playa', 'el parasol', 'la sombrilla playera'],
    correctAnswer: 'la sombrilla de playa',
    hint: 'Provides shade at the beach',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_037',
    emoji: '🩱',
    question: '¿Qué ropa es?',
    options: ['el traje de baño', 'el bañador', 'el swimsuit'],
    correctAnswer: 'el traje de baño',
    hint: 'What you wear swimming',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_038',
    emoji: '🩳',
    question: '¿Qué son estos?',
    options: ['el bañador', 'el traje de baño', 'el short de baño'],
    correctAnswer: 'el bañador',
    hint: 'Men\'s swimming attire',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_039',
    emoji: '🕶️',
    question: '¿Qué son estos?',
    options: ['las gafas de sol', 'los lentes de sol', 'los anteojos de sol'],
    correctAnswer: 'las gafas de sol',
    hint: 'Protect your eyes from the sun',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_040',
    emoji: '🧴',
    question: '¿Qué esencial de playa es esto?',
    options: ['el protector solar', 'el bloqueador solar', 'la crema solar'],
    correctAnswer: 'el protector solar',
    hint: 'Sunscreen - protects skin from UV damage, reapply every 2 hours',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_041',
    emoji: '🩴',
    question: '¿Qué calzado es?',
    options: ['las chanclas', 'las chancletas', 'las sandalias de playa'],
    correctAnswer: 'las chanclas',
    hint: 'Flip-flops - beach sandals, easy on/off, "sandalias" also used',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_042',
    emoji: '🧊',
    question: '¿Qué usas en una hielera?',
    options: ['el hielo', 'el hielo picado', 'los cubitos de hielo'],
    correctAnswer: 'el hielo',
    hint: 'Ice - frozen water, keeps food/drinks cold, melts slowly',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_043',
    emoji: '🧺',
    question: '¿Qué llevas a la playa?',
    options: ['la cesta de playa', 'la canasta', 'el bolso de playa'],
    correctAnswer: 'la cesta de playa',
    hint: 'Beach basket - woven carrier for towels and supplies',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_044',
    emoji: '🪣',
    question: '¿Qué usan los niños para hacer castillos de arena?',
    options: ['el cubo', 'la cubeta', 'el balde'],
    correctAnswer: 'el cubo',
    hint: 'Bucket - container for carrying sand and water, shapes sand',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_045',
    emoji: '🏰',
    question: '¿Qué construyes con arena?',
    options: ['el castillo de arena', 'la fortaleza de arena', 'la construcción de arena'],
    correctAnswer: 'el castillo de arena',
    hint: 'Sandcastle - classic beach building activity, use wet sand',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_046',
    emoji: '🎭',
    question: '¿Qué usas en el agua?',
    options: ['la máscara de buceo', 'las gafas de buceo', 'la máscara submarina'],
    correctAnswer: 'la máscara de buceo',
    hint: 'Diving mask - waterproof eyewear, "gafas de buceo" also used',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_047',
    emoji: '🏊‍♂️',
    question: '¿Qué usas para nadar más rápido?',
    options: ['las aletas', 'las patas de rana', 'los flippers'],
    correctAnswer: 'las aletas',
    hint: 'Flippers - swim fins for propulsion, "patas de rana" (frog feet)',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_048',
    emoji: '🛟',
    question: '¿Qué dispositivo de seguridad es?',
    options: ['el salvavidas', 'el flotador', 'el aro salvavidas'],
    correctAnswer: 'el salvavidas',
    hint: 'Life preserver - ring buoy for rescue, also means lifeguard person',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_049',
    emoji: '🎈',
    question: '¿Qué es esto inflable?',
    options: ['el globo', 'el globo inflable', 'el balón'],
    correctAnswer: 'el globo',
    hint: 'Balloon - inflatable with air or helium, floats and pops',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_050',
    emoji: '🏐',
    question: '¿Qué deporte de playa usa esta pelota?',
    options: ['el voleibol de playa', 'el vóley playa', 'el beach volleyball'],
    correctAnswer: 'el voleibol de playa',
    hint: 'Beach volleyball - played on sand over net, Olympic sport',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_051',
    emoji: '🥏',
    question: '¿Qué juguete es?',
    options: ['el frisbee', 'el disco volador', 'el disco'],
    correctAnswer: 'el frisbee',
    hint: 'Frisbee - flying disc you throw and catch, "disco volador" in Spanish',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_052',
    emoji: '🪁',
    question: '¿Qué vuelas en una playa ventosa?',
    options: ['la cometa', 'el papalote', 'el volantín'],
    correctAnswer: 'la cometa',
    hint: 'Kite - flies on string in wind, "papalote" in Mexico',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_053',
    emoji: '📸',
    question: '¿Qué usas para tomar fotos?',
    options: ['la cámara', 'la cámara fotográfica', 'la cámara digital'],
    correctAnswer: 'la cámara',
    hint: 'Camera - captures memories, smartphone cameras now common',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_054',
    emoji: '🎒',
    question: '¿En qué llevas tus cosas?',
    options: ['la mochila', 'la bolsa', 'el morral'],
    correctAnswer: 'la mochila',
    hint: 'Backpack - carries beach gear on shoulders, hands-free',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_055',
    emoji: '💧',
    question: '¿Qué bebes cuando tienes sed?',
    options: ['el agua', 'el agua potable', 'el agua fresca'],
    correctAnswer: 'el agua',
    hint: 'Water - essential hydration, especially important in sun',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  
  // Nature & Environment (20 questions)
  {
    id: 'beach_056',
    emoji: '☀️',
    question: '¿Qué brilla en el cielo?',
    options: ['el sol', 'el astro rey', 'el sol radiante'],
    correctAnswer: 'el sol',
    hint: 'Sun - star providing daylight, "tomar el sol" means sunbathe',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_057',
    emoji: '🌙',
    question: '¿Qué brilla de noche?',
    options: ['la luna', 'la luna llena', 'el satélite natural'],
    correctAnswer: 'la luna',
    hint: 'Moon - reflects sunlight at night, phases change monthly',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_058',
    emoji: '⭐',
    question: '¿Qué ves en el cielo nocturno?',
    options: ['la estrella', 'el astro', 'la estrella brillante'],
    correctAnswer: 'la estrella',
    hint: 'Star - distant sun, twinkles in night sky, from Latin "stella"',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_059',
    emoji: '☁️',
    question: '¿Qué está en el cielo?',
    options: ['la nube', 'la nubosidad', 'el nubarrón'],
    correctAnswer: 'la nube',
    hint: 'Cloud - water vapor condensed, brings shade and rain',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_060',
    emoji: '🌤️',
    question: '¿Qué clima es?',
    options: ['parcialmente nublado', 'medio nublado', 'nuboso parcial'],
    correctAnswer: 'parcialmente nublado',
    hint: 'Partly cloudy - sun and clouds together, mixed weather',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_061',
    emoji: '⛅',
    question: '¿Qué clima es?',
    options: ['nublado', 'nuboso', 'cubierto de nubes'],
    correctAnswer: 'nublado',
    hint: 'Cloudy - sky covered with clouds, less sun',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_062',
    emoji: '🌧️',
    question: '¿Qué clima es?',
    options: ['la lluvia', 'la precipitación', 'el aguacero'],
    correctAnswer: 'la lluvia',
    hint: 'Rain - water falling from clouds, "llover" means to rain',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_063',
    emoji: '⛈️',
    question: '¿Qué tiempo hace?',
    options: ['la tormenta', 'la tempestad', 'el temporal'],
    correctAnswer: 'la tormenta',
    hint: 'Storm - severe weather with thunder, lightning, "tempestad" also used',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_064',
    emoji: '🌈',
    question: '¿Qué aparece después de la lluvia?',
    options: ['el arcoíris', 'el arco iris', 'el arcoiris'],
    correctAnswer: 'el arcoíris',
    hint: 'Rainbow - colorful arc of light, seven colors spectrum',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_065',
    emoji: '💨',
    question: '¿Qué mueve las hojas de los árboles?',
    options: ['el viento', 'la brisa', 'el aire'],
    correctAnswer: 'el viento',
    hint: 'Wind - moving air, "brisa" is gentle breeze',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_066',
    emoji: '🏝️',
    question: '¿Qué tierra está rodeada de agua?',
    options: ['la isla', 'el islote', 'el atolón'],
    correctAnswer: 'la isla',
    hint: 'Island - land completely surrounded by water, tropical paradises',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_067',
    emoji: '⛱️',
    question: '¿Dónde estás?',
    options: ['en la playa', 'en la costa', 'en la orilla'],
    correctAnswer: 'en la playa',
    hint: 'At the beach - sandy shore by ocean, perfect for relaxing',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_068',
    emoji: '🏔️',
    question: '¿Qué elevación es muy alta?',
    options: ['la montaña', 'el monte', 'la sierra'],
    correctAnswer: 'la montaña',
    hint: 'Mountain - very tall landform, from Latin "montanea" (mountainous)',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_069',
    emoji: '🌋',
    question: '¿Qué montaña arroja lava?',
    options: ['el volcán', 'el volcán activo', 'el cráter'],
    correctAnswer: 'el volcán',
    hint: 'Volcano - mountain that can erupt with lava, from Vulcan (fire god)',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_070',
    emoji: '🏞️',
    question: '¿Dónde protege una nación la naturaleza?',
    options: ['el parque nacional', 'una reserva de parque nacional', 'el área protegida'],
    correctAnswer: 'una reserva de parque nacional',
    hint: 'National park - protected nature reserve, preserves wildlife',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_071',
    emoji: '🌲',
    question: '¿Qué árbol es?',
    options: ['el pino', 'la conífera', 'el abeto'],
    correctAnswer: 'el pino',
    hint: 'Pine tree - evergreen conifer, has needles and cones',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_072',
    emoji: '🌳',
    question: '¿Qué planta grande tiene tronco y ramas?',
    options: ['el árbol', 'el árbol frondoso', 'el árbol de hojas'],
    correctAnswer: 'el árbol',
    hint: 'Tree - large plant with trunk and branches, provides shade',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_073',
    emoji: '🌺',
    question: '¿Qué flor crece en climas cálidos?',
    options: ['la flor tropical', 'la hibisco', 'la flor exótica'],
    correctAnswer: 'la flor tropical',
    hint: 'Tropical flower - hibiscus common, bright colors in warm climates',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_074',
    emoji: '🌻',
    question: '¿Qué flor es?',
    options: ['el girasol', 'el mirasol', 'la flor de sol'],
    correctAnswer: 'el girasol',
    hint: 'Sunflower - follows sun\'s movement, "gira" (turns) + "sol" (sun)',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_075',
    emoji: '🌹',
    question: '¿Qué flor es?',
    options: ['la rosa', 'la rosa roja', 'el rosal'],
    correctAnswer: 'la rosa',
    hint: 'Rose - classic romantic flower, has thorns, symbol of love',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  
  // Outdoor Activities & Sports (25 questions)
  {
    id: 'beach_076',
    emoji: '🚶',
    question: '¿Qué estás haciendo?',
    options: ['caminar', 'andar', 'pasear'],
    correctAnswer: 'caminar',
    hint: 'Walking - moving on foot at normal pace, good exercise',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_077',
    emoji: '🏃',
    question: '¿Qué estás haciendo?',
    options: ['correr', 'trotar', 'el jogging'],
    correctAnswer: 'correr',
    hint: 'Running - moving faster than walking, cardio exercise',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_078',
    emoji: '🚴',
    question: '¿Qué actividad es?',
    options: ['andar en bicicleta', 'montar en bici', 'el ciclismo'],
    correctAnswer: 'andar en bicicleta',
    hint: 'Biking - riding bicycle, "montar en bici" also used',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_079',
    emoji: '🏇',
    question: '¿Qué deporte es?',
    options: ['montar a caballo', 'la equitación', 'cabalgar'],
    correctAnswer: 'montar a caballo',
    hint: 'Horseback riding - equestrian sport, "equitación" formal term',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_080',
    emoji: '⛷️',
    question: '¿Qué deporte de invierno es?',
    options: ['esquiar', 'el esquí', 'el esquí alpino'],
    correctAnswer: 'esquiar',
    hint: 'Skiing - sliding on snow with skis, popular in Pyrenees and Andes',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_081',
    emoji: '🏂',
    question: '¿Qué deporte es?',
    options: ['el snowboard', 'la tabla de nieve', 'el snowboarding'],
    correctAnswer: 'el snowboard',
    hint: 'Snowboarding - boarding on snow slopes, like surfing on snow',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_082',
    emoji: '🧗',
    question: '¿Qué estás haciendo?',
    options: ['escalar', 'el alpinismo', 'la escalada'],
    correctAnswer: 'escalar',
    hint: 'Climbing - ascending mountains or walls, requires strength',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_083',
    emoji: '🏌️',
    question: '¿Qué deporte es?',
    options: ['el golf', 'el minigolf', 'jugar al golf'],
    correctAnswer: 'el golf',
    hint: 'Golf - hit ball into 18 holes with clubs, precision sport',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_084',
    emoji: '🎾',
    question: '¿Qué deporte es?',
    options: ['el tenis', 'el tenis de mesa', 'el pádel'],
    correctAnswer: 'el tenis',
    hint: 'Tennis - racket sport with yellow ball, Wimbledon famous',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_085',
    emoji: '🏀',
    question: '¿Qué deporte es?',
    options: ['el básquetbol', 'el baloncesto', 'el basquetbol'],
    correctAnswer: 'el básquetbol',
    hint: 'Basketball - shoot ball through hoop, "baloncesto" in Spain',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_086',
    emoji: '⚽',
    question: '¿Qué deporte es?',
    options: ['el fútbol', 'el balompié', 'el soccer'],
    correctAnswer: 'el fútbol',
    hint: 'Soccer - world\'s most popular sport, "el deporte rey" (king sport)',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_087',
    emoji: '🏈',
    question: '¿Qué deporte es?',
    options: ['el fútbol americano', 'el football americano', 'el fútbol gringo'],
    correctAnswer: 'el fútbol americano',
    hint: 'American football - popular in USA, NFL Super Bowl famous',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_088',
    emoji: '⚾',
    question: '¿Qué deporte es?',
    options: ['el béisbol', 'el beisbol', 'el baseball'],
    correctAnswer: 'el béisbol',
    hint: 'Baseball - America\'s pastime, bat and ball sport, 9 innings',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_089',
    emoji: '🥎',
    question: '¿Qué deporte es?',
    options: ['el softball', 'el sófbol', 'el softbol'],
    correctAnswer: 'el softball',
    hint: 'Softball - like baseball with larger ball, underhand pitching',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_090',
    emoji: '🎱',
    question: '¿Qué juego es?',
    options: ['el billar', 'el pool', 'la mesa de billar'],
    correctAnswer: 'el billar',
    hint: 'Billiards - pool table game, hit balls with cue stick',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_091',
    emoji: '🎳',
    question: '¿Qué deporte es?',
    options: ['los bolos', 'el boliche', 'el bowling'],
    correctAnswer: 'los bolos',
    hint: 'Bowling - knock down pins with ball, "boliche" in Latin America',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_092',
    emoji: '🎯',
    question: '¿Qué lanzas al tablero circular?',
    options: ['los dardos', 'el juego de dardos', 'la diana'],
    correctAnswer: 'los dardos',
    hint: 'Darts - throw pointed missiles at circular board target',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_093',
    emoji: '🏹',
    question: '¿Qué deporte es?',
    options: ['el tiro con arco', 'la arquería', 'el arco y flecha'],
    correctAnswer: 'el tiro con arco',
    hint: 'Archery - shoot arrows with bow, "arquería" also used, Olympic sport',
    points: 15,
    category: 'beach',
    difficulty: 'hard',
  },
  {
    id: 'beach_094',
    emoji: '🥊',
    question: '¿Qué deporte es?',
    options: ['el boxeo', 'el pugilismo', 'el boxear'],
    correctAnswer: 'el boxeo',
    hint: 'Boxing - fighting with gloves in ring, "púgil" is boxer',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_095',
    emoji: '🤺',
    question: '¿Qué deporte es?',
    options: ['la esgrima', 'el esgrimir', 'la esgrima deportiva'],
    correctAnswer: 'la esgrima',
    hint: 'Fencing - sword fighting sport with foil, épée, or sabre',
    points: 15,
    category: 'beach',
    difficulty: 'hard',
  },
  {
    id: 'beach_096',
    emoji: '🥋',
    question: '¿Qué arte marcial es?',
    options: ['el karate', 'el kárate', 'el karate-do'],
    correctAnswer: 'el karate',
    hint: 'Karate - Japanese martial art, "empty hand" striking techniques',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_097',
    emoji: '🏋️',
    question: '¿Qué haces en el gimnasio?',
    options: ['levantar pesas', 'el levantamiento de pesas', 'pesas'],
    correctAnswer: 'levantar pesas',
    hint: 'Weightlifting - lifting weights builds muscle, "pesas" are weights',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_098',
    emoji: '🤸',
    question: '¿Qué actividad es?',
    options: ['la gimnasia', 'la gimnasia artística', 'la gimnasia deportiva'],
    correctAnswer: 'la gimnasia',
    hint: 'Gymnastics - acrobatic exercises, balance and flexibility sport',
    points: 10,
    category: 'beach',
    difficulty: 'medium',
  },
  {
    id: 'beach_099',
    emoji: '🧘',
    question: '¿Qué práctica es?',
    options: ['el yoga', 'la yoga', 'el hatha yoga'],
    correctAnswer: 'el yoga',
    hint: 'Yoga - mind-body practice from India, breathing and poses',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_100',
    emoji: '🎪',
    question: '¿Qué entretenimiento es?',
    options: ['el circo', 'el circo ambulante', 'la carpa'],
    correctAnswer: 'el circo',
    hint: 'Circus - acrobats, clowns, animals perform, from Latin "circus" (ring)',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
  {
    id: 'beach_101',
    emoji: '🌵',
    question: '¿Qué planta tiene espinas y crece en el desierto?',
    options: ['el cactus', 'la palmera', 'el aloe'],
    correctAnswer: 'el cactus',
    hint: 'Cactus - desert plant with spines, stores water, survives in hot dry climates',
    points: 5,
    category: 'beach',
    difficulty: 'easy',
  },
];
