/**
 * Business Category Questions (Office, Construction & Industry)
 * Category: business
 * IDs: business_001 - business_100
 */

export const businessQuestions = [
 
  {
    id: 'business_001',
    emoji: 'approval.png',
    question: '¿Cómo se obtiene un permiso de construcción?',
    translation: 'How does a building permit get issued?',
    options: ['se obtiene en la oficina de la ciudad', 'se obtiene en la biblioteca', 'se obtiene en el supermercado'],
    correctAnswer: 'se obtiene en la oficina de la ciudad',
    hint: 'Building permits are typically issued by the city office',
    usageExample: 'El permiso de construcción se obtiene en la oficina de la ciudad después de revisar los planos.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_002',
    emoji: 'calculator.png',
    question: '¿Qué usas para hacer cálculos matemáticos en la oficina?',
    translation: 'What do you use to do mathematical calculations in the office?',
    options: ['la calculadora', 'la computadora', 'el teléfono'],
    correctAnswer: 'la calculadora',
    hint: 'Small electronic device specifically designed for quick math calculations',
    usageExample: 'Necesito la calculadora para sumar estos números rápidamente.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_003',
    emoji: 'stapler.png',
    question: '¿Con qué herramienta sujetas papeles juntos en la oficina?',
    translation: 'What tool do you use to fasten papers together in the office?',
    options: ['la engrapadora', 'la perforadora', 'las tijeras'],
    correctAnswer: 'la engrapadora',
    hint: 'Office tool that uses metal fasteners to bind papers together',
    usageExample: 'Usa la engrapadora para unir estos documentos antes de enviarlos.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_004',
    emoji: 'filing-cabinet.png',
    question: '¿Dónde guardas documentos importantes en la oficina?',
    translation: 'Where do you store important documents in the office?',
    options: ['el archivador', 'el escritorio', 'la papelera'],
    correctAnswer: 'el archivador',
    hint: 'Tall furniture with drawers used for organizing and storing files',
    usageExample: 'Los contratos se guardan en el archivador del segundo piso.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_005',
    emoji: 'safety-helmet.png',
    question: '¿Qué equipo de protección usas en la cabeza en una construcción?',
    translation: 'What protective equipment do you wear on your head at a construction site?',
    options: ['el casco de seguridad', 'la gorra', 'el sombrero'],
    correctAnswer: 'el casco de seguridad',
    hint: 'Hard protective headgear required on construction sites',
    usageExample: 'Todos deben usar el casco de seguridad en la obra.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'calm',
  },

  {
    id: 'business_006',
    emoji: 'measuring-tape.png',
    question: '¿Con qué herramienta mides distancias en construcción?',
    translation: 'What tool do you use to measure distances in construction?',
    options: ['la cinta métrica', 'la regla', 'el nivel'],
    correctAnswer: 'la cinta métrica',
    hint: 'Flexible measuring tool that extends and retracts; used by carpenters and builders',
    usageExample: 'Usa la cinta métrica para medir la longitud de la pared.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_007',
    emoji: 'laptop-charger.png',
    question: '¿Qué necesitas para cargar tu computadora portátil?',
    translation: 'What do you need to charge your laptop?',
    options: ['el cargador de portátil', 'el cable USB', 'la batería'],
    correctAnswer: 'el cargador de portátil',
    hint: 'Power adapter with cable that connects laptop to electrical outlet',
    usageExample: 'Olvidé el cargador de portátil en casa y ahora la batería está baja.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_008',
    emoji: 'water-cooler.png',
    question: '¿Dónde tomas agua fría en la oficina?',
    translation: 'Where do you get cold water in the office?',
    options: ['el enfriador de agua', 'el refrigerador', 'la fuente'],
    correctAnswer: 'el enfriador de agua',
    hint: 'Large dispenser that provides cold and hot water; common gathering spot in offices',
    usageExample: 'Voy al enfriador de agua para llenar mi botella.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_009',
    emoji: 'desk-lamp.png',
    question: '¿Qué usas para iluminar tu escritorio mientras trabajas?',
    translation: 'What do you use to light your desk while working?',
    options: ['la lámpara de escritorio', 'la linterna', 'la vela'],
    correctAnswer: 'la lámpara de escritorio',
    hint: 'Small adjustable light that sits on your work surface for task lighting',
    usageExample: 'Enciende la lámpara de escritorio porque necesito más luz para leer.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_010',
    emoji: 'screwdriver.png',
    question: '¿Con qué herramienta aprietas o afloja tornillos?',
    translation: 'What tool do you use to tighten or loosen screws?',
    options: ['el destornillador', 'el martillo', 'la llave inglesa'],
    correctAnswer: 'el destornillador',
    hint: 'Hand tool with a handle and metal shaft; used for turning screws',
    usageExample: 'Pásame el destornillador para arreglar esta silla.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_011',
    emoji: 'desktop-computer.png',
    question: '¿Qué tipo de computadora usas en el escritorio de la oficina?',
    translation: 'What type of computer do you use on the office desk?',
    options: ['la computadora de escritorio', 'la laptop', 'la tableta'],
    correctAnswer: 'la computadora de escritorio',
    hint: 'Computer that stays in one place with a separate monitor, keyboard, and tower',
    usageExample: 'Mi computadora de escritorio tiene dos monitores para trabajar mejor.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_012',
    emoji: 'copier.png',
    question: '¿Qué máquina usas para duplicar documentos en la oficina?',
    translation: 'What machine do you use to duplicate documents in the office?',
    options: ['la copiadora', 'la impresora', 'el escáner'],
    correctAnswer: 'la copiadora',
    hint: 'Office machine that makes identical copies of paper documents',
    usageExample: 'Necesito hacer cinco copias, ¿dónde está la copiadora?',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_013',
    emoji: 'paper-shredder.png',
    question: '¿Con qué máquina destruyes documentos confidenciales?',
    translation: 'What machine do you use to destroy confidential documents?',
    options: ['la trituradora de papel', 'la copiadora', 'la engrapadora'],
    correctAnswer: 'la trituradora de papel',
    hint: 'Machine that cuts paper into tiny strips or pieces for security',
    usageExample: 'Usa la trituradora de papel para destruir estos documentos antiguos.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_014',
    emoji: 'envelope.png',
    question: '¿En qué pones una carta antes de enviarla por correo?',
    translation: 'What do you put a letter in before sending it by mail?',
    options: ['el sobre', 'la carpeta', 'el folder'],
    correctAnswer: 'el sobre',
    hint: 'Paper container used to mail letters; you write the address on it',
    usageExample: 'Escribe la dirección en el sobre antes de enviarlo.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_015',
    emoji: 'binder.png',
    question: '¿Qué usas para organizar papeles con anillos metálicos?',
    translation: 'What do you use to organize papers with metal rings?',
    options: ['la carpeta de argollas', 'el folder', 'el cuaderno'],
    correctAnswer: 'la carpeta de argollas',
    hint: 'Organizational tool with rings that hold punched papers together',
    usageExample: 'Organizaré estos reportes en la carpeta de argollas azul.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_016',
    emoji: 'pencil-sharpener.png',
    question: '¿Con qué afilas los lápices?',
    translation: 'What do you use to sharpen pencils?',
    options: ['el sacapuntas', 'la goma de borrar', 'las tijeras'],
    correctAnswer: 'el sacapuntas',
    hint: 'Small device that sharpens pencil tips by shaving the wood',
    usageExample: 'Mi lápiz está sin punta, necesito el sacapuntas.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_017',
    emoji: 'tape-dispenser.png',
    question: '¿Qué herramienta de escritorio tiene cinta adhesiva?',
    translation: 'What desk tool holds adhesive tape?',
    options: ['el dispensador de cinta', 'la engrapadora', 'el cortador'],
    correctAnswer: 'el dispensador de cinta',
    hint: 'Desktop holder with a serrated edge for cutting tape',
    usageExample: 'Busca el dispensador de cinta para pegar este cartel.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_018',
    emoji: 'staples.png',
    question: '¿Qué pequeños objetos metálicos usa la engrapadora?',
    translation: 'What small metal objects does the stapler use?',
    options: ['las grapas', 'los clips', 'los alfileres'],
    correctAnswer: 'las grapas',
    hint: 'Small bent metal fasteners that go through paper',
    usageExample: 'La engrapadora no funciona porque se acabaron las grapas.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_019',
    emoji: 'copy-paper.png',
    question: '¿Qué tipo de papel usas en la impresora o copiadora?',
    translation: 'What type of paper do you use in the printer or copier?',
    options: ['el papel de copia', 'el papel de regalo', 'el papel higiénico'],
    correctAnswer: 'el papel de copia',
    hint: 'Standard white sheets used for printing and copying documents',
    usageExample: 'Compré una resma de papel de copia para la impresora.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_020',
    emoji: 'ergonomic-mouse.png',
    question: '¿Qué dispositivo ergonómico usas para mover el cursor?',
    translation: 'What ergonomic device do you use to move the cursor?',
    options: ['el ratón ergonómico', 'el teclado', 'el monitor'],
    correctAnswer: 'el ratón ergonómico',
    hint: 'Computer input device designed to reduce hand and wrist strain',
    usageExample: 'El ratón ergonómico me ayuda a prevenir dolor en la muñeca.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_021',
    emoji: 'cubicle.png',
    question: '¿Cómo se llama el espacio de trabajo separado por paneles?',
    translation: 'What do you call the workspace separated by panels?',
    options: ['el cubículo', 'la oficina privada', 'la sala de juntas'],
    correctAnswer: 'el cubículo',
    hint: 'Individual workspace divided by partitions in an open office',
    usageExample: 'Mi escritorio está en el cubículo número 12.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_022',
    emoji: 'office.png',
    question: '¿Dónde trabajas si tienes un empleo de oficina?',
    translation: 'Where do you work if you have an office job?',
    options: ['en la oficina', 'en la fábrica', 'en el campo'],
    correctAnswer: 'en la oficina',
    hint: 'Indoor workplace with desks, computers, and administrative tasks',
    usageExample: 'Trabajo en la oficina de lunes a viernes.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_023',
    emoji: 'office-building.png',
    question: '¿Cómo se llama el edificio donde están muchas oficinas?',
    translation: 'What do you call the building where many offices are located?',
    options: ['el edificio de oficinas', 'el centro comercial', 'el hospital'],
    correctAnswer: 'el edificio de oficinas',
    hint: 'Tall structure that houses multiple businesses and workspaces',
    usageExample: 'Nuestra empresa está en el edificio de oficinas del centro.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_024',
    emoji: 'board-room.png',
    question: '¿Dónde se reúne la junta directiva de una empresa?',
    translation: 'Where does the board of directors of a company meet?',
    options: ['en la sala de juntas', 'en el cubículo', 'en el almacén'],
    correctAnswer: 'en la sala de juntas',
    hint: 'Formal meeting room with a large table for executive discussions',
    usageExample: 'La reunión de directores será en la sala de juntas a las 3pm.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_025',
    emoji: 'meeting.png',
    question: '¿Cómo se llama cuando varias personas se reúnen para discutir trabajo?',
    translation: 'What do you call it when several people gather to discuss work?',
    options: ['la reunión', 'la fiesta', 'el descanso'],
    correctAnswer: 'la reunión',
    hint: 'Scheduled gathering of colleagues to discuss business matters',
    usageExample: 'Tenemos una reunión importante mañana por la mañana.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'determined',
  },

  {
    id: 'business_026',
    emoji: 'presentation.png',
    question: '¿Qué haces cuando muestras información a un grupo con diapositivas?',
    translation: 'What do you do when you show information to a group with slides?',
    options: ['una presentación', 'una entrevista', 'una llamada'],
    correctAnswer: 'una presentación',
    hint: 'Formal display of information, often using slides or visuals',
    usageExample: 'Voy a dar una presentación sobre las ventas del trimestre.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'anxious',
  },

  {
    id: 'business_027',
    emoji: 'break-room.png',
    question: '¿Dónde descansas y tomas café en el trabajo?',
    translation: 'Where do you rest and have coffee at work?',
    options: ['en la sala de descanso', 'en la sala de juntas', 'en el estacionamiento'],
    correctAnswer: 'en la sala de descanso',
    hint: 'Common area where employees relax, eat lunch, and socialize',
    usageExample: 'Nos vemos en la sala de descanso durante el almuerzo.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_028',
    emoji: 'stale-coffee.png',
    question: '¿Cómo se llama el café que está frío y viejo?',
    translation: 'What do you call coffee that is cold and old?',
    options: ['el café pasado', 'el café fresco', 'el café premium'],
    correctAnswer: 'el café pasado',
    hint: 'Coffee that has been sitting too long and lost its freshness',
    usageExample: 'Este café pasado sabe horrible, voy a hacer uno fresco.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'disgusted',
  },

  {
    id: 'business_029',
    emoji: 'punch-clock.png',
    question: '¿Con qué registras tu hora de entrada y salida en el trabajo?',
    translation: 'What do you use to record your arrival and departure time at work?',
    options: ['el reloj checador', 'el calendario', 'la alarma'],
    correctAnswer: 'el reloj checador',
    hint: 'Time tracking device that employees use to clock in and out',
    usageExample: 'Marca tu entrada en el reloj checador al llegar.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_030',
    emoji: 'fingerprint-scanner.png',
    question: '¿Qué dispositivo de seguridad lee tu huella digital?',
    translation: 'What security device reads your fingerprint?',
    options: ['el escáner de huellas', 'la cámara', 'el teclado'],
    correctAnswer: 'el escáner de huellas',
    hint: 'Biometric device that identifies people by their fingerprints',
    usageExample: 'Usa el escáner de huellas para entrar al edificio.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_031',
    emoji: 'safety-boots.png',
    question: '¿Qué calzado de protección usas en una construcción?',
    translation: 'What protective footwear do you wear at a construction site?',
    options: ['las botas de seguridad', 'las sandalias', 'los zapatos deportivos'],
    correctAnswer: 'las botas de seguridad',
    hint: 'Heavy-duty boots with steel toes for protecting feet at work sites',
    usageExample: 'No olvides ponerte las botas de seguridad antes de entrar al sitio.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'calm',
  },

  {
    id: 'business_032',
    emoji: 'tool-belt.png',
    question: '¿Qué te pones en la cintura para llevar herramientas?',
    translation: 'What do you wear around your waist to carry tools?',
    options: ['el cinturón de herramientas', 'la mochila', 'el bolsillo'],
    correctAnswer: 'el cinturón de herramientas',
    hint: 'Belt with pouches and loops worn by workers to hold tools',
    usageExample: 'El carpintero lleva todas sus herramientas en el cinturón de herramientas.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_033',
    emoji: 'work-light.png',
    question: '¿Qué iluminación portátil usas en áreas de trabajo oscuras?',
    translation: 'What portable lighting do you use in dark work areas?',
    options: ['la lámpara de trabajo', 'la vela', 'el fósforo'],
    correctAnswer: 'la lámpara de trabajo',
    hint: 'Bright portable light used on construction sites and workshops',
    usageExample: 'Enciende la lámpara de trabajo para ver mejor en este rincón.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_034',
    emoji: 'respirator-mask.png',
    question: '¿Qué equipo de protección usas para evitar respirar polvo o químicos?',
    translation: 'What protective equipment do you use to avoid breathing dust or chemicals?',
    options: ['la máscara respiradora', 'los lentes de seguridad', 'los guantes'],
    correctAnswer: 'la máscara respiradora',
    hint: 'Protective mask that filters air to protect lungs from hazards',
    usageExample: 'Debes usar la máscara respiradora cuando pintes con aerosol.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'anxious',
  },

  {
    id: 'business_035',
    emoji: 'building-crane.png',
    question: '¿Qué máquina grande levanta materiales pesados en construcción?',
    translation: 'What large machine lifts heavy materials in construction?',
    options: ['la grúa de construcción', 'el montacargas', 'la excavadora'],
    correctAnswer: 'la grúa de construcción',
    hint: 'Tall machine with a long arm used to lift and move heavy loads',
    usageExample: 'La grúa de construcción está levantando vigas de acero.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_036',
    emoji: 'blueprints.png',
    question: '¿Cómo se llaman los planos técnicos de un edificio?',
    translation: 'What do you call the technical plans of a building?',
    options: ['los planos', 'los mapas', 'los dibujos'],
    correctAnswer: 'los planos',
    hint: 'Detailed architectural drawings showing how to construct a building',
    usageExample: 'El arquitecto revisó los planos antes de comenzar la obra.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_037',
    emoji: 'chordless-drill.png',
    question: '¿Qué herramienta eléctrica sin cable usas para hacer agujeros?',
    translation: 'What cordless power tool do you use to make holes?',
    options: ['el taladro inalámbrico', 'el destornillador', 'la sierra'],
    correctAnswer: 'el taladro inalámbrico',
    hint: 'Battery-powered tool that drills holes and drives screws',
    usageExample: 'Préstame el taladro inalámbrico para hacer estos agujeros.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_038',
    emoji: 'nail-gun.png',
    question: '¿Qué herramienta neumática dispara clavos rápidamente?',
    translation: 'What pneumatic tool shoots nails quickly?',
    options: ['la pistola de clavos', 'el martillo', 'la grapadora'],
    correctAnswer: 'la pistola de clavos',
    hint: 'Power tool that drives nails into wood or other materials with compressed air',
    usageExample: 'La pistola de clavos hace el trabajo mucho más rápido.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_039',
    emoji: 'arc-welder.png',
    question: '¿Con qué equipo unes metales usando calor intenso?',
    translation: 'What equipment do you use to join metals using intense heat?',
    options: ['la soldadora de arco', 'el soplete', 'el horno'],
    correctAnswer: 'la soldadora de arco',
    hint: 'Machine that uses electricity to melt and fuse metal pieces together',
    usageExample: 'Solo un experto debe usar la soldadora de arco.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'anxious',
  },

  {
    id: 'business_040',
    emoji: 'soldering-iron.png',
    question: '¿Qué herramienta caliente usas para unir componentes electrónicos?',
    translation: 'What hot tool do you use to join electronic components?',
    options: ['el cautín', 'el destornillador', 'el soldador'],
    correctAnswer: 'el cautín',
    hint: 'Handheld tool with a heated tip used to melt solder for electronics',
    usageExample: 'Usa el cautín para soldar estos componentes del circuito.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_041',
    emoji: 'drill-press.png',
    question: '¿Qué máquina estacionaria usas para perforar con precisión?',
    translation: 'What stationary machine do you use for precise drilling?',
    options: ['el taladro de columna', 'el taladro de mano', 'la sierra'],
    correctAnswer: 'el taladro de columna',
    hint: 'Fixed drill machine mounted on a stand for accurate vertical drilling',
    usageExample: 'El taladro de columna es perfecto para agujeros precisos.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_042',
    emoji: 'lathe.png',
    question: '¿Qué máquina gira la pieza para dar forma cilíndrica?',
    translation: 'What machine rotates the workpiece to create cylindrical shapes?',
    options: ['el torno', 'el taladro', 'la fresadora'],
    correctAnswer: 'el torno',
    hint: 'Machine that spins material to shape it with cutting tools',
    usageExample: 'En el torno puedo dar forma a piezas cilíndricas de metal.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_043',
    emoji: 'cnc-machine.png',
    question: '¿Qué máquina controlada por computadora hace cortes precisos?',
    translation: 'What computer-controlled machine makes precise cuts?',
    options: ['la máquina CNC', 'el taladro manual', 'la sierra eléctrica'],
    correctAnswer: 'la máquina CNC',
    hint: 'Automated machine controlled by computer programs for precision manufacturing',
    usageExample: 'La máquina CNC produce piezas con tolerancias muy precisas.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_044',
    emoji: 'factory.png',
    question: '¿Dónde se fabrican productos en grandes cantidades?',
    translation: 'Where are products manufactured in large quantities?',
    options: ['en la fábrica', 'en la oficina', 'en la tienda'],
    correctAnswer: 'en la fábrica',
    hint: 'Industrial facility with machines and workers producing goods at scale',
    usageExample: 'Mi hermano trabaja en la fábrica de automóviles.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_045',
    emoji: 'robot.png',
    question: '¿Qué máquina automática hace trabajos repetitivos en fábricas?',
    translation: 'What automatic machine does repetitive work in factories?',
    options: ['el robot', 'la computadora', 'el montacargas'],
    correctAnswer: 'el robot',
    hint: 'Programmable machine that performs tasks automatically in manufacturing',
    usageExample: 'El robot puede ensamblar 100 piezas por hora.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_046',
    emoji: 'trowel.png',
    question: '¿Con qué herramienta aplicas y alisas el cemento?',
    translation: 'What tool do you use to apply and smooth cement?',
    options: ['la llana', 'la pala', 'el rastrillo'],
    correctAnswer: 'la llana',
    hint: 'Flat handheld tool used by masons to spread and level mortar or concrete',
    usageExample: 'Necesito la llana para alisar el cemento del piso.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_047',
    emoji: 'plumbing.png',
    question: '¿Qué oficio se encarga de tuberías y sistemas de agua?',
    translation: 'What trade deals with pipes and water systems?',
    options: ['la plomería', 'la carpintería', 'la electricidad'],
    correctAnswer: 'la plomería',
    hint: 'Trade involving installation and repair of water pipes and fixtures',
    usageExample: 'Llamé al especialista en plomería para arreglar la tubería.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_048',
    emoji: 'cleaning-cart.png',
    question: '¿Qué carrito usa el personal de limpieza con productos y trapeadores?',
    translation: 'What cart does cleaning staff use with products and mops?',
    options: ['el carrito de limpieza', 'el carrito de compras', 'la carretilla'],
    correctAnswer: 'el carrito de limpieza',
    hint: 'Mobile cart containing cleaning supplies, mops, and trash bags',
    usageExample: 'El personal de limpieza empuja el carrito de limpieza por los pasillos.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_049',
    emoji: 'floor-cleaner.png',
    question: '¿Qué máquina grande limpia pisos de manera profunda?',
    translation: 'What large machine deep cleans floors?',
    options: ['la limpiadora de pisos', 'la aspiradora', 'el trapeador'],
    correctAnswer: 'la limpiadora de pisos',
    hint: 'Industrial machine that scrubs and cleans large floor areas',
    usageExample: 'La limpiadora de pisos deja el suelo brillante.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_050',
    emoji: 'floor-polisher.png',
    question: '¿Qué máquina hace brillar los pisos?',
    translation: 'What machine makes floors shine?',
    options: ['la pulidora de pisos', 'la aspiradora', 'el trapeador'],
    correctAnswer: 'la pulidora de pisos',
    hint: 'Machine with rotating pads that buffs and polishes floor surfaces',
    usageExample: 'Usamos la pulidora de pisos cada semana en el pasillo principal.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_051',
    emoji: 'laser-engraver.png',
    question: '¿Qué máquina usa láser para grabar diseños en materiales?',
    translation: 'What machine uses laser to engrave designs on materials?',
    options: ['la grabadora láser', 'la impresora', 'la copiadora'],
    correctAnswer: 'la grabadora láser',
    hint: 'Precision machine that uses focused laser beams to etch patterns on various surfaces',
    usageExample: 'La grabadora láser puede personalizar estos llaveros.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_052',
    emoji: 'orbital-sander.png',
    question: '¿Qué herramienta eléctrica usas para lijar superficies de madera?',
    translation: 'What power tool do you use to sand wood surfaces?',
    options: ['la lijadora orbital', 'el taladro', 'la sierra'],
    correctAnswer: 'la lijadora orbital',
    hint: 'Power tool with circular sanding pad that smooths wood surfaces',
    usageExample: 'Pasa la lijadora orbital sobre la superficie para alisarla.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_053',
    emoji: 'satellite-dish.png',
    question: '¿Qué antena parabólica recibe señales de comunicación satelital?',
    translation: 'What parabolic antenna receives satellite communication signals?',
    options: ['la antena parabólica', 'la antena de radio', 'el router'],
    correctAnswer: 'la antena parabólica',
    hint: 'Dish-shaped antenna that receives signals from satellites in space',
    usageExample: 'Instalaron una antena parabólica en el techo del edificio.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_054',
    emoji: '3d-printer.png',
    question: '¿Qué máquina crea objetos tridimensionales capa por capa?',
    translation: 'What machine creates three-dimensional objects layer by layer?',
    options: ['la impresora 3D', 'la fotocopiadora', 'el escáner'],
    correctAnswer: 'la impresora 3D',
    hint: 'Advanced machine that builds physical objects from digital designs using additive manufacturing',
    usageExample: 'La impresora 3D tardó seis horas en hacer esta pieza.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_055',
    emoji: 'access-badge.png',
    question: '¿Qué tarjeta usas para entrar a edificios seguros?',
    translation: 'What card do you use to enter secure buildings?',
    options: ['la tarjeta de acceso', 'la tarjeta de crédito', 'la licencia de conducir'],
    correctAnswer: 'la tarjeta de acceso',
    hint: 'Security badge that grants entry to restricted areas',
    usageExample: 'No olvides traer tu tarjeta de acceso para entrar al edificio.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_056',
    emoji: 'accounting.png',
    question: '¿Qué departamento maneja las finanzas y los libros contables?',
    translation: 'What department handles finances and accounting books?',
    options: ['la contabilidad', 'el almacén', 'el marketing'],
    correctAnswer: 'la contabilidad',
    hint: 'Department responsible for managing financial records and transactions',
    usageExample: 'El departamento de contabilidad está revisando los gastos del mes.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_057',
    emoji: 'air-compressor.png',
    question: '¿Qué máquina produce aire comprimido para herramientas neumáticas?',
    translation: 'What machine produces compressed air for pneumatic tools?',
    options: ['el compresor de aire', 'el ventilador', 'la bomba de agua'],
    correctAnswer: 'el compresor de aire',
    hint: 'Machine that pressurizes air to power tools and inflate tires',
    usageExample: 'El compresor de aire alimenta todas las herramientas neumáticas.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_058',
    emoji: 'band-saw.png',
    question: '¿Qué sierra tiene una hoja continua en forma de banda?',
    translation: 'What saw has a continuous blade in the shape of a band?',
    options: ['la sierra de banda', 'la sierra circular', 'la sierra de mano'],
    correctAnswer: 'la sierra de banda',
    hint: 'Power saw with a long blade loop for cutting curves and irregular shapes',
    usageExample: 'La sierra de banda es ideal para cortar curvas en madera.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_059',
    emoji: 'belt-sander.png',
    question: '¿Qué lijadora usa una banda de lija continua?',
    translation: 'What sander uses a continuous sanding belt?',
    options: ['la lijadora de banda', 'la lijadora orbital', 'el papel de lija'],
    correctAnswer: 'la lijadora de banda',
    hint: 'Power sander with a looped abrasive belt for aggressive material removal',
    usageExample: 'La lijadora de banda remueve material rápidamente.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_060',
    emoji: 'bolt-cutter.png',
    question: '¿Con qué herramienta cortas cadenas y candados gruesos?',
    translation: 'What tool do you use to cut chains and thick padlocks?',
    options: ['la cizalla', 'las tijeras', 'el martillo'],
    correctAnswer: 'la cizalla',
    hint: 'Heavy-duty cutting tool with long handles for cutting through metal',
    usageExample: 'Necesitamos la cizalla para cortar este candado oxidado.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'determined',
  },

  {
    id: 'business_061',
    emoji: 'chainsaw.png',
    question: '¿Con qué herramienta motorizada cortas árboles y madera gruesa?',
    translation: 'What motorized tool do you use to cut trees and thick wood?',
    options: ['la motosierra', 'la sierra de mano', 'el hacha'],
    correctAnswer: 'la motosierra',
    hint: 'Powerful portable saw with rotating chain for cutting through wood',
    usageExample: 'Ten cuidado al usar la motosierra, es muy peligrosa.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_062',
    emoji: 'chisel.png',
    question: '¿Con qué herramienta manual tallás o cortas madera con precisión?',
    translation: 'What hand tool do you use to carve or cut wood precisely?',
    options: ['el cincel', 'el martillo', 'el destornillador'],
    correctAnswer: 'el cincel',
    hint: 'Sharp-edged hand tool used with a mallet for shaping wood or stone',
    usageExample: 'Usa el cincel y el martillo para tallar esta decoración.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_063',
    emoji: 'conveyor-belt.png',
    question: '¿Qué sistema automático mueve productos en una fábrica?',
    translation: 'What automatic system moves products in a factory?',
    options: ['la banda transportadora', 'la carretilla', 'el montacargas'],
    correctAnswer: 'la banda transportadora',
    hint: 'Continuous moving belt that transports items along an assembly line',
    usageExample: 'La banda transportadora mueve las cajas al área de empaque.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_064',
    emoji: 'cybersecurity.png',
    question: '¿Qué práctica protege sistemas informáticos contra ataques digitales?',
    translation: 'What practice protects computer systems against digital attacks?',
    options: ['la ciberseguridad', 'el antivirus', 'el firewall'],
    correctAnswer: 'la ciberseguridad',
    hint: 'Field focused on protecting networks, devices, and data from cyber threats',
    usageExample: 'Nuestra empresa invierte mucho en ciberseguridad.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'determined',
  },

  {
    id: 'business_065',
    emoji: 'datacenter.png',
    question: '¿Dónde se almacenan y procesan grandes cantidades de datos?',
    translation: 'Where is large amounts of data stored and processed?',
    options: ['el centro de datos', 'la biblioteca', 'la oficina'],
    correctAnswer: 'el centro de datos',
    hint: 'Facility housing servers and networking equipment for data storage and processing',
    usageExample: 'El centro de datos tiene sistemas de enfriamiento especiales.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_066',
    emoji: 'ear-protectors.png',
    question: '¿Qué equipo de protección usas para proteger tus oídos del ruido?',
    translation: 'What protective equipment do you use to protect your ears from noise?',
    options: ['los protectores auditivos', 'los audífonos', 'los lentes'],
    correctAnswer: 'los protectores auditivos',
    hint: 'Safety equipment worn over ears to reduce loud noise exposure',
    usageExample: 'Usa los protectores auditivos porque las máquinas hacen mucho ruido.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'calm',
  },

  {
    id: 'business_067',
    emoji: 'embroidery-machine.png',
    question: '¿Qué máquina cose diseños decorativos automáticamente en tela?',
    translation: 'What machine automatically sews decorative designs on fabric?',
    options: ['la máquina de bordar', 'la máquina de coser', 'la plancha'],
    correctAnswer: 'la máquina de bordar',
    hint: 'Specialized sewing machine that creates intricate patterns and designs on fabric',
    usageExample: 'La máquina de bordar puede hacer diseños muy complejos.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_068',
    emoji: 'floor-jack.png',
    question: '¿Qué herramienta usas para levantar vehículos del suelo?',
    translation: 'What tool do you use to lift vehicles off the ground?',
    options: ['el gato hidráulico', 'la grúa', 'el montacargas'],
    correctAnswer: 'el gato hidráulico',
    hint: 'Wheeled hydraulic device that lifts cars for maintenance and repairs',
    usageExample: 'Levanta el coche con el gato hidráulico para cambiar la llanta.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_069',
    emoji: 'forklift.png',
    question: '¿Qué vehículo industrial usa para levantar y mover paletas?',
    translation: 'What industrial vehicle do you use to lift and move pallets?',
    options: ['el montacargas', 'el camión', 'la grúa'],
    correctAnswer: 'el montacargas',
    hint: 'Powered industrial truck with fork-shaped prongs for lifting heavy loads',
    usageExample: 'El operador del montacargas está moviendo las paletas.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_070',
    emoji: 'generator.png',
    question: '¿Qué máquina produce electricidad cuando no hay energía?',
    translation: 'What machine produces electricity when there is no power?',
    options: ['el generador', 'la batería', 'el panel solar'],
    correctAnswer: 'el generador',
    hint: 'Backup power machine that converts fuel into electrical energy',
    usageExample: 'Encendimos el generador porque se fue la luz.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_071',
    emoji: 'hammer-drill.png',
    question: '¿Qué taladro también martilla mientras perfora materiales duros?',
    translation: 'What drill also hammers while drilling through hard materials?',
    options: ['el taladro percutor', 'el taladro normal', 'el destornillador eléctrico'],
    correctAnswer: 'el taladro percutor',
    hint: 'Power drill with hammering action for drilling into concrete and masonry',
    usageExample: 'Necesitas el taladro percutor para perforar concreto.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_072',
    emoji: 'hammer.png',
    question: '¿Con qué herramienta básica golpeas clavos?',
    translation: 'What basic tool do you use to hit nails?',
    options: ['el martillo', 'el destornillador', 'la llave'],
    correctAnswer: 'el martillo',
    hint: 'Common hand tool with a heavy head for driving nails into wood',
    usageExample: 'Dame el martillo para clavar este cuadro en la pared.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_073',
    emoji: 'heat-gun.png',
    question: '¿Qué herramienta produce aire muy caliente para quitar pintura?',
    translation: 'What tool produces very hot air to remove paint?',
    options: ['la pistola de calor', 'el secador de pelo', 'la plancha'],
    correctAnswer: 'la pistola de calor',
    hint: 'Electric tool that blows extremely hot air for stripping paint and shrinking materials',
    usageExample: 'Usa la pistola de calor para quitar la pintura vieja.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_074',
    emoji: 'hydraulic-press.png',
    question: '¿Qué máquina usa presión hidráulica para comprimir o dar forma a materiales?',
    translation: 'What machine uses hydraulic pressure to compress or shape materials?',
    options: ['la prensa hidráulica', 'el tornillo de banco', 'el martillo'],
    correctAnswer: 'la prensa hidráulica',
    hint: 'Powerful machine that uses fluid pressure to exert tremendous force for shaping metal',
    usageExample: 'La prensa hidráulica puede ejercer toneladas de presión.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_075',
    emoji: 'laser-level.png',
    question: '¿Qué herramienta proyecta una línea láser para nivelar con precisión?',
    translation: 'What tool projects a laser line to level precisely?',
    options: ['el nivel láser', 'el nivel de burbuja', 'la regla'],
    correctAnswer: 'el nivel láser',
    hint: 'Electronic leveling tool that projects a laser beam for accurate alignment',
    usageExample: 'El nivel láser proyecta una línea perfectamente recta.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_076',
    emoji: 'leaf-blower.png',
    question: '¿Qué herramienta motorizada usa para soplar hojas y escombros?',
    translation: 'What motorized tool do you use to blow leaves and debris?',
    options: ['la sopladora de hojas', 'la aspiradora', 'el rastrillo'],
    correctAnswer: 'la sopladora de hojas',
    hint: 'Powered tool that blows air to clear leaves and debris from outdoor areas',
    usageExample: 'Usa la sopladora de hojas para limpiar el patio.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_077',
    emoji: 'level.png',
    question: '¿Con qué herramienta verificas si una superficie está horizontal?',
    translation: 'What tool do you use to check if a surface is level?',
    options: ['el nivel de burbuja', 'la regla', 'la cinta métrica'],
    correctAnswer: 'el nivel de burbuja',
    hint: 'Tool with a liquid-filled tube and air bubble to check if surfaces are perfectly horizontal',
    usageExample: 'Verifica con el nivel de burbuja que el estante esté derecho.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_078',
    emoji: 'lobby.png',
    question: '¿Dónde esperas antes de entrar a una oficina o reunión?',
    translation: 'Where do you wait before entering an office or meeting?',
    options: ['en el vestíbulo', 'en el baño', 'en el estacionamiento'],
    correctAnswer: 'en el vestíbulo',
    hint: 'Entry area or reception space in a building where visitors wait',
    usageExample: 'Espérame en el vestíbulo, bajo en cinco minutos.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_079',
    emoji: 'metalworking-file.png',
    question: '¿Con qué herramienta manual limas metal para alisarlo?',
    translation: 'What hand tool do you use to file metal to smooth it?',
    options: ['la lima de metal', 'el papel de lija', 'la sierra'],
    correctAnswer: 'la lima de metal',
    hint: 'Metal hand tool with rough surface for smoothing and shaping metal edges',
    usageExample: 'Usa la lima de metal para suavizar los bordes ásperos.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_080',
    emoji: 'microscope.png',
    question: '¿Con qué instrumento ves objetos muy pequeños ampliados?',
    translation: 'What instrument do you use to see very small objects magnified?',
    options: ['el microscopio', 'el telescopio', 'la lupa'],
    correctAnswer: 'el microscopio',
    hint: 'Scientific instrument with lenses that magnifies tiny objects for detailed examination',
    usageExample: 'Bajo el microscopio puedes ver las células claramente.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_081',
    emoji: 'money-counter.png',
    question: '¿Qué máquina cuenta billetes automáticamente?',
    translation: 'What machine counts bills automatically?',
    options: ['la contadora de dinero', 'la caja registradora', 'la calculadora'],
    correctAnswer: 'la contadora de dinero',
    hint: 'Machine that rapidly counts and verifies paper currency',
    usageExample: 'La contadora de dinero verificó que había 5000 dólares.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_082',
    emoji: 'nut-and-bolt.png',
    question: '¿Qué par de piezas metálicas se atornillan juntas para sujetar?',
    translation: 'What pair of metal pieces screw together to fasten?',
    options: ['la tuerca y el perno', 'el clavo y el martillo', 'el tornillo y el destornillador'],
    correctAnswer: 'la tuerca y el perno',
    hint: 'Threaded fastener pair where one piece screws into the other',
    usageExample: 'Aprieta la tuerca y el perno con la llave.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_083',
    emoji: 'pipe-flange.png',
    question: '¿Qué pieza metálica circular une dos secciones de tubería?',
    translation: 'What circular metal piece connects two sections of pipe?',
    options: ['la brida de tubería', 'la tuerca', 'el perno'],
    correctAnswer: 'la brida de tubería',
    hint: 'Flat circular fitting bolted to pipe ends to create a sealed connection',
    usageExample: 'Necesitamos una brida de tubería para conectar estas secciones.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_084',
    emoji: 'post-hole-digger.png',
    question: '¿Con qué herramienta cavas agujeros profundos para postes?',
    translation: 'What tool do you use to dig deep holes for posts?',
    options: ['el cavador de postes', 'la pala', 'el pico'],
    correctAnswer: 'el cavador de postes',
    hint: 'Two-handled tool with clamping blades for digging narrow, deep holes for fence posts',
    usageExample: 'Usa el cavador de postes para hacer agujeros para la cerca.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_085',
    emoji: 'rivet-gun.png',
    question: '¿Qué herramienta usas para unir láminas de metal con remaches?',
    translation: 'What tool do you use to join metal sheets with rivets?',
    options: ['la remachadora', 'la grapadora', 'el martillo'],
    correctAnswer: 'la remachadora',
    hint: 'Tool that squeezes and deforms rivets to permanently fasten metal plates together',
    usageExample: 'La remachadora une permanentemente estas láminas de metal.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_086',
    emoji: 'roof-renovation.png',
    question: '¿Qué tipo de proyecto repara o reemplaza el techo de un edificio?',
    translation: 'What type of project repairs or replaces the roof of a building?',
    options: ['la renovación de techo', 'la pintura exterior', 'la instalación eléctrica'],
    correctAnswer: 'la renovación de techo',
    hint: 'Construction project focused on fixing or replacing roofing materials',
    usageExample: 'La renovación de techo tomará tres semanas.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_087',
    emoji: 'safety-air-horn.png',
    question: '¿Qué dispositivo de seguridad produce un sonido muy fuerte para alertar?',
    translation: 'What safety device produces a very loud sound to alert?',
    options: ['la bocina de seguridad', 'la alarma de incendios', 'el silbato'],
    correctAnswer: 'la bocina de seguridad',
    hint: 'Compressed air horn used to signal warnings on work sites and emergencies',
    usageExample: 'Toca la bocina de seguridad para alertar a todos.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'anxious',
  },

  {
    id: 'business_088',
    emoji: 'safety-mirror.png',
    question: '¿Qué espejo convexo usas para ver esquinas ciegas en almacenes?',
    translation: 'What convex mirror do you use to see blind corners in warehouses?',
    options: ['el espejo de seguridad', 'el espejo de baño', 'el espejo retrovisor'],
    correctAnswer: 'el espejo de seguridad',
    hint: 'Curved mirror mounted at intersections to improve visibility and prevent accidents',
    usageExample: 'Instalamos un espejo de seguridad en esa esquina peligrosa.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'calm',
  },

  {
    id: 'business_089',
    emoji: 'sandblaster.png',
    question: '¿Qué máquina usa arena a presión para limpiar o alisar superficies?',
    translation: 'What machine uses pressurized sand to clean or smooth surfaces?',
    options: ['la arenadora', 'la pulidora', 'la lijadora'],
    correctAnswer: 'la arenadora',
    hint: 'Machine that shoots abrasive material at high speed to remove paint or rust from surfaces',
    usageExample: 'La arenadora quitó toda la pintura del metal.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_090',
    emoji: 'scissor-lift .png',
    question: '¿Qué plataforma elevadora de tijera usas para trabajar en alturas?',
    translation: 'What scissor lift platform do you use to work at heights?',
    options: ['la plataforma de tijera', 'la escalera', 'el andamio'],
    correctAnswer: 'la plataforma de tijera',
    hint: 'Mobile elevated work platform with crisscross support that extends vertically',
    usageExample: 'Sube a la plataforma de tijera para alcanzar el techo.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_091',
    emoji: 'screw.png',
    question: '¿Qué sujetador con rosca usas con un destornillador?',
    translation: 'What threaded fastener do you use with a screwdriver?',
    options: ['el tornillo', 'el clavo', 'el perno'],
    correctAnswer: 'el tornillo',
    hint: 'Threaded metal fastener that is turned into material to hold things together',
    usageExample: 'Necesito un tornillo más largo para este proyecto.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_092',
    emoji: 'shipping-container.png',
    question: '¿En qué gran caja metálica se transportan mercancías por barco?',
    translation: 'What large metal box is used to transport goods by ship?',
    options: ['el contenedor de carga', 'el camión', 'la caja de cartón'],
    correctAnswer: 'el contenedor de carga',
    hint: 'Standardized metal box used for shipping goods internationally by sea, rail, or truck',
    usageExample: 'El contenedor de carga llegó del puerto esta mañana.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_093',
    emoji: 'steel-i-beam.png',
    question: '¿Qué viga de acero en forma de I se usa en la construcción de edificios?',
    translation: 'What I-shaped steel beam is used in building construction?',
    options: ['la viga de acero', 'el tubo', 'la columna'],
    correctAnswer: 'la viga de acero',
    hint: 'Heavy I-shaped structural steel used to support buildings and bridges',
    usageExample: 'La viga de acero soporta todo el peso del segundo piso.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_094',
    emoji: 'tap-wrench .png',
    question: '¿Con qué herramienta creas roscas internas en agujeros de metal?',
    translation: 'What tool do you use to create internal threads in metal holes?',
    options: ['el macho de roscar', 'el taladro', 'el destornillador'],
    correctAnswer: 'el macho de roscar',
    hint: 'Threading tool with handle used to cut threads inside holes for screws and bolts',
    usageExample: 'Usa el macho de roscar para hacer roscas en ese agujero.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_095',
    emoji: 'thermal-camera.png',
    question: '¿Qué cámara detecta diferencias de temperatura mediante imágenes?',
    translation: 'What camera detects temperature differences through images?',
    options: ['la cámara térmica', 'la cámara digital', 'la cámara de seguridad'],
    correctAnswer: 'la cámara térmica',
    hint: 'Imaging device that shows heat patterns and temperature variations',
    usageExample: 'La cámara térmica detectó una fuga de calor en la pared.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_096',
    emoji: 'tilt-truck.png',
    question: '¿Qué carrito industrial se inclina para vaciar su contenido?',
    translation: 'What industrial cart tilts to empty its contents?',
    options: ['el carrito basculante', 'la carretilla', 'el carrito de compras'],
    correctAnswer: 'el carrito basculante',
    hint: 'Heavy-duty wheeled cart that tilts forward to dump materials easily',
    usageExample: 'Lleva los escombros al basurero con el carrito basculante.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_097',
    emoji: 'transistor.png',
    question: '¿Qué componente electrónico amplifica o conmuta señales?',
    translation: 'What electronic component amplifies or switches signals?',
    options: ['el transistor', 'el capacitor', 'la resistencia'],
    correctAnswer: 'el transistor',
    hint: 'Semiconductor device fundamental to modern electronics and computing',
    usageExample: 'El transistor es fundamental en todos los circuitos modernos.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_098',
    emoji: 'welding-apron.png',
    question: '¿Qué protección se usa durante trabajos de soldadura?',
    translation: 'What protection is worn during welding work?',
    options: ['el delantal de soldadura', 'el chaleco reflectante', 'el cinturón de herramientas'],
    correctAnswer: 'el delantal de soldadura',
    hint: 'Leather protective garment that shields the body from sparks and heat',
    usageExample: 'Ponte el delantal de soldadura antes de comenzar.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'calm',
  },

  {
    id: 'business_099',
    emoji: 'workbench.png',
    question: '¿Dónde se realizan trabajos manuales y reparaciones?',
    translation: 'Where are manual tasks and repairs performed?',
    options: ['el banco de trabajo', 'el escritorio', 'el mostrador'],
    correctAnswer: 'el banco de trabajo',
    hint: 'Sturdy table with tools and vise for workshop projects',
    usageExample: 'Tengo todas mis herramientas organizadas en el banco de trabajo.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'pleased',
  },

  {
    id: 'business_100',
    emoji: 'wrench.png',
    question: '¿Qué herramienta se usa para apretar tuercas y pernos?',
    translation: 'What tool is used to tighten nuts and bolts?',
    options: ['la llave', 'el destornillador', 'el martillo'],
    correctAnswer: 'la llave',
    hint: 'Essential hand tool with adjustable or fixed jaw for turning fasteners',
    usageExample: 'Préstame la llave para apretar estas tuercas.',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_101',
    emoji: 'architect.png',
    question: '¿Cómo se dice "architect"?',
    translation: 'How do you say "architect"?',
    options: ['el arquitecto', 'el ingeniero', 'el diseñador'],
    correctAnswer: 'el arquitecto',
    hint: 'Professional who designs buildings and structures',
    usageExample: 'El arquitecto diseñó un edificio hermoso y funcional.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_102',
    emoji: 'automobile-factory .png',
    question: '¿Dónde se fabrican automóviles en grandes cantidades?',
    translation: 'Where are automobiles manufactured in large quantities?',
    options: ['la fábrica de automóviles', 'el taller mecánico', 'el concesionario'],
    correctAnswer: 'la fábrica de automóviles',
    hint: 'Industrial facility where cars are assembled on production lines',
    usageExample: 'La fábrica de automóviles produce mil vehículos al día.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_103',
    emoji: 'automotive-detailer.png',
    question: '¿Cómo se dice "automotive detailer"?',
    translation: 'How do you say "automotive detailer"?',
    options: ['el detallador automotriz', 'el mecánico', 'el lavador de autos'],
    correctAnswer: 'el detallador automotriz',
    hint: 'Professional who cleans, polishes, and restores cars to pristine condition',
    usageExample: 'El detallador automotriz dejó el auto como nuevo.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_104',
    emoji: 'bulldozer.png',
    question: '¿Cómo se dice "bulldozer"?',
    translation: 'How do you say "bulldozer"?',
    options: ['el bulldózer', 'la excavadora', 'el tractor'],
    correctAnswer: 'el bulldózer',
    hint: 'Powerful construction vehicle with a large blade for pushing earth and debris',
    usageExample: 'El bulldózer está nivelando el terreno para la construcción.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_105',
    emoji: 'businessman.png',
    question: '¿Cómo se dice "businessman"?',
    translation: 'How do you say "businessman"?',
    options: ['el hombre de negocios', 'el cliente', 'el vendedor'],
    correctAnswer: 'el hombre de negocios',
    hint: 'Professional man engaged in commercial or industrial business',
    usageExample: 'El hombre de negocios viaja mucho por su trabajo.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_106',
    emoji: 'carpenter.png',
    question: '¿Quién trabaja con madera construyendo muebles y estructuras?',
    translation: 'Who works with wood building furniture and structures?',
    options: ['el carpintero', 'el albañil', 'el pintor'],
    correctAnswer: 'el carpintero',
    hint: 'Skilled tradesperson who cuts, shapes, and installs wooden structures',
    usageExample: 'El carpintero está haciendo muebles a medida para la casa.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },


  {
    id: 'business_108',
    emoji: 'chain-block.png',
    question: '¿Con qué dispositivo manual levantas cargas pesadas usando una cadena?',
    translation: 'What manual device do you use to lift heavy loads using a chain?',
    options: ['el polipasto de cadena', 'la grúa', 'el gato hidráulico'],
    correctAnswer: 'el polipasto de cadena',
    hint: 'Mechanical chain hoist operated by pulling a hand chain to lift heavy objects',
    usageExample: 'Usa el polipasto de cadena para levantar ese motor.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'determined',
  },

  {
    id: 'business_109',
    emoji: 'circuit-breaker-panel.png',
    question: '¿Dónde cortas la electricidad de circuitos individuales en un edificio?',
    translation: 'Where do you cut off electricity to individual circuits in a building?',
    options: ['el panel de interruptores', 'el enchufe', 'el medidor eléctrico'],
    correctAnswer: 'el panel de interruptores',
    hint: 'Electrical box with switches that control power to different areas of a building',
    usageExample: 'El panel de interruptores controla toda la electricidad del edificio.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'calm',
  },

  {
    id: 'business_110',
    emoji: 'circular-saw.png',
    question: '¿Qué sierra tiene una hoja redonda que gira rápidamente?',
    translation: 'What saw has a round blade that spins rapidly?',
    options: ['la sierra circular', 'la sierra de mano', 'la sierra de calar'],
    correctAnswer: 'la sierra circular',
    hint: 'Power saw with a rotating circular blade for making straight cuts in wood',
    usageExample: 'Corta la madera con la sierra circular siguiendo la línea.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_111',
    emoji: 'computer-engineer.png',
    question: '¿Quién diseña y desarrolla hardware y software de computadoras?',
    translation: 'Who designs and develops computer hardware and software?',
    options: ['el ingeniero informático', 'el electricista', 'el técnico de soporte'],
    correctAnswer: 'el ingeniero informático',
    hint: 'Professional who applies engineering principles to create computer systems',
    usageExample: 'El ingeniero informático desarrolló un nuevo sistema de software.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_112',
    emoji: 'concrete-mixer.png',
    question: '¿Qué máquina de obra mezcla arena, cemento y agua para hacer concreto?',
    translation: 'What construction machine mixes sand, cement and water to make concrete?',
    options: ['la hormigonera', 'la excavadora', 'el bulldózer'],
    correctAnswer: 'la hormigonera',
    hint: 'Rotating drum machine that combines ingredients to create ready-mix concrete',
    usageExample: 'La hormigonera está mezclando concreto para los cimientos.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_113',
    emoji: 'construction-worker.png',
    question: '¿Quién trabaja en obras de construcción usando casco y herramientas?',
    translation: 'Who works on construction sites using a helmet and tools?',
    options: ['el trabajador de construcción', 'el arquitecto', 'el ingeniero'],
    correctAnswer: 'el trabajador de construcción',
    hint: 'Laborer who performs physical tasks on building sites',
    usageExample: 'El trabajador de construcción instaló las ventanas nuevas.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_114',
    emoji: 'designer.png',
    question: '¿Quién crea conceptos visuales y soluciones estéticas para proyectos?',
    translation: 'Who creates visual concepts and aesthetic solutions for projects?',
    options: ['el diseñador', 'el contador', 'el abogado'],
    correctAnswer: 'el diseñador',
    hint: 'Creative professional who develops visual ideas and designs',
    usageExample: 'El diseñador creó un logotipo moderno para la empresa.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_115',
    emoji: 'drain-snake.png',
    question: '¿Con qué herramienta flexible destapar tuberías obstruidas?',
    translation: 'What flexible tool do you use to unclog blocked pipes?',
    options: ['la serpiente de drenaje', 'el destapador', 'la llave inglesa'],
    correctAnswer: 'la serpiente de drenaje',
    hint: 'Long flexible cable tool that plumbers feed into drains to clear blockages',
    usageExample: 'Usa la serpiente de drenaje para destapar el lavabo.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'determined',
  },

  {
    id: 'business_116',
    emoji: 'dust-collector.png',
    question: '¿Qué sistema aspira polvo y virutas en talleres de carpintería?',
    translation: 'What system sucks up dust and chips in woodworking shops?',
    options: ['el colector de polvo', 'la aspiradora doméstica', 'el ventilador'],
    correctAnswer: 'el colector de polvo',
    hint: 'Industrial vacuum system that removes sawdust and debris from the air',
    usageExample: 'El colector de polvo mantiene el aire limpio en el taller.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_117',
    emoji: 'electrician-fish-tape.png',
    question: '¿Con qué cinta flexible pasan los electricistas cables por conductos?',
    translation: 'What flexible tape do electricians use to pull cables through conduits?',
    options: ['la cinta pescacables', 'la cinta métrica', 'la cinta adhesiva'],
    correctAnswer: 'la cinta pescacables',
    hint: 'Stiff wire or tape electricians push through pipes to guide wires',
    usageExample: 'Usa la cinta pescacables para pasar el cable por el conducto.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'determined',
  },

  {
    id: 'business_118',
    emoji: 'electrician.png',
    question: '¿Quién instala y repara sistemas eléctricos en edificios y casas?',
    translation: 'Who installs and repairs electrical systems in buildings and houses?',
    options: ['el electricista', 'el plomero', 'el carpintero'],
    correctAnswer: 'el electricista',
    hint: 'Skilled tradesperson who works with wiring, circuits, and electrical installations',
    usageExample: 'El electricista está instalando las luces del edificio nuevo.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_119',
    emoji: 'excavator.png',
    question: '¿Qué máquina de construcción cava y mueve tierra con un brazo largo?',
    translation: 'What construction machine digs and moves earth with a long arm?',
    options: ['la excavadora', 'el bulldózer', 'la grúa'],
    correctAnswer: 'la excavadora',
    hint: 'Heavy machinery with a rotating cab and hydraulic arm with bucket for digging',
    usageExample: 'La excavadora cavó los cimientos en dos días.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_120',
    emoji: 'farmer.png',
    question: '¿Quién cultiva la tierra y cosecha alimentos para ganarse la vida?',
    translation: 'Who cultivates the land and harvests food for a living?',
    options: ['el agricultor', 'el jardinero', 'el ganadero'],
    correctAnswer: 'el agricultor',
    hint: 'Person who grows crops and raises animals on a farm',
    usageExample: 'El agricultor cosecha trigo en sus campos.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_121',
    emoji: 'forge.png',
    question: '¿Dónde calienta el herrero el metal para darle forma?',
    translation: 'Where does the blacksmith heat metal to shape it?',
    options: ['la fragua', 'el horno', 'el taller'],
    correctAnswer: 'la fragua',
    hint: 'Furnace or hearth where metal is heated until it glows red-hot for forging',
    usageExample: 'El herrero calienta el metal en la fragua hasta que brilla.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_122',
    emoji: 'front-end-loader.png',
    question: '¿Qué vehículo de construcción carga material con una pala frontal grande?',
    translation: 'What construction vehicle loads material with a large front bucket?',
    options: ['la cargadora frontal', 'la excavadora', 'el bulldózer'],
    correctAnswer: 'la cargadora frontal',
    hint: 'Heavy equipment with a wide bucket on the front for scooping and moving earth',
    usageExample: 'La cargadora frontal está llenando el camión con tierra.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_123',
    emoji: 'graphic-designer.png',
    question: '¿Quién crea logotipos, carteles y diseños visuales para empresas?',
    translation: 'Who creates logos, posters and visual designs for companies?',
    options: ['el diseñador gráfico', 'el ilustrador', 'el fotógrafo'],
    correctAnswer: 'el diseñador gráfico',
    hint: 'Professional who creates visual communications and brand designs using digital tools',
    usageExample: 'El diseñador gráfico diseñó el póster para el evento.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_124',
    emoji: 'Illustrator.png',
    question: '¿Quién dibuja imágenes artísticas para libros, revistas y publicaciones?',
    translation: 'Who draws artistic images for books, magazines and publications?',
    options: ['el ilustrador', 'el diseñador gráfico', 'el pintor'],
    correctAnswer: 'el ilustrador',
    hint: 'Artist who creates custom drawings and artwork for print and digital media',
    usageExample: 'El ilustrador dibujó todas las imágenes del libro.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_125',
    emoji: 'Interior-designer.png',
    question: '¿Quién planifica y decora espacios interiores de casas y oficinas?',
    translation: 'Who plans and decorates interior spaces of homes and offices?',
    options: ['el diseñador de interiores', 'el arquitecto', 'el constructor'],
    correctAnswer: 'el diseñador de interiores',
    hint: 'Professional who selects colors, furniture, and layouts to create functional and beautiful indoor spaces',
    usageExample: 'El diseñador de interiores eligió colores cálidos para la sala.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_126',
    emoji: 'inventor.png',
    question: '¿Quién crea nuevos dispositivos o métodos que nunca existieron antes?',
    translation: 'Who creates new devices or methods that never existed before?',
    options: ['el inventor', 'el mecánico', 'el vendedor'],
    correctAnswer: 'el inventor',
    hint: 'Creative person who develops original ideas and prototypes for new products or solutions',
    usageExample: 'El inventor creó un dispositivo que ahorra energía.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_127',
    emoji: 'investor.png',
    question: '¿Quién pone dinero en negocios esperando obtener ganancias?',
    translation: 'Who puts money into businesses hoping to make profits?',
    options: ['el inversionista', 'el empleado', 'el cliente'],
    correctAnswer: 'el inversionista',
    hint: 'Person who provides capital to businesses or projects expecting financial returns',
    usageExample: 'El inversionista puso dinero en tres empresas nuevas.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_128',
    emoji: 'isolation-cabinet.png',
    question: '¿En qué cabina aislada graban músicos amplificadores sin molestar?',
    translation: 'In what isolated cabinet do musicians record amplifiers without disturbing?',
    options: ['la cabina de aislamiento', 'el estudio', 'el armario'],
    correctAnswer: 'la cabina de aislamiento',
    hint: 'Soundproof enclosure that contains loud equipment for recording without external noise',
    usageExample: 'Grabamos la guitarra en la cabina de aislamiento.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_129',
    emoji: 'lawyer.png',
    question: '¿Quién representa a personas en tribunales y asuntos legales?',
    translation: 'Who represents people in courts and legal matters?',
    options: ['el abogado', 'el juez', 'el notario'],
    correctAnswer: 'el abogado',
    hint: 'Legal professional who provides counsel and defends clients in legal proceedings',
    usageExample: 'El abogado representó al cliente en la corte.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_130',
    emoji: 'mechanic.png',
    question: '¿Quién repara motores y sistemas mecánicos de vehículos?',
    translation: 'Who repairs engines and mechanical systems of vehicles?',
    options: ['el mecánico', 'el electricista', 'el pintor de autos'],
    correctAnswer: 'el mecánico',
    hint: 'Skilled technician who diagnoses and fixes problems in cars and other machinery',
    usageExample: 'El mecánico reparó el motor en tres horas.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_131',
    emoji: 'metal-press-machine.png',
    question: '¿Qué máquina industrial aplasta y moldea láminas de metal?',
    translation: 'What industrial machine crushes and molds metal sheets?',
    options: ['la prensa de metal', 'el torno', 'la soldadora'],
    correctAnswer: 'la prensa de metal',
    hint: 'Heavy machinery that uses tremendous force to stamp and shape metal into desired forms',
    usageExample: 'La prensa de metal estampó 500 piezas hoy.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_132',
    emoji: 'micrometer.png',
    question: '¿Con qué instrumento de precisión mides dimensiones muy pequeñas?',
    translation: 'With what precision instrument do you measure very small dimensions?',
    options: ['el micrómetro', 'la cinta métrica', 'la regla'],
    correctAnswer: 'el micrómetro',
    hint: 'Precision tool that measures thickness and diameter with extreme accuracy in millimeters',
    usageExample: 'Usa el micrómetro para medir el grosor exacto.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_133',
    emoji: 'natural-gas-installer.png',
    question: '¿Quién instala y conecta líneas de gas natural en edificios?',
    translation: 'Who installs and connects natural gas lines in buildings?',
    options: ['el instalador de gas natural', 'el plomero', 'el electricista'],
    correctAnswer: 'el instalador de gas natural',
    hint: 'Specialized technician who works with gas pipes and equipment for heating and cooking',
    usageExample: 'El instalador de gas natural conectó la estufa.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_134',
    emoji: 'paint-mixing-machine.png',
    question: '¿Qué máquina agita y mezcla diferentes colores de pintura?',
    translation: 'What machine shakes and mixes different paint colors?',
    options: ['la mezcladora de pintura', 'la licuadora', 'la batidora'],
    correctAnswer: 'la mezcladora de pintura',
    hint: 'Machine found in hardware stores that blends paint pigments to create custom colors',
    usageExample: 'La mezcladora de pintura preparó el color exacto que pedí.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_135',
    emoji: 'pallet-jack.png',
    question: '¿Con qué herramienta manual levantas y mueves paletas pesadas?',
    translation: 'With what manual tool do you lift and move heavy pallets?',
    options: ['el gato hidráulico de paletas', 'el montacargas', 'la carretilla'],
    correctAnswer: 'el gato hidráulico de paletas',
    hint: 'Hand-operated hydraulic device with forks that slides under pallets to lift them slightly off the ground',
    usageExample: 'Usa el gato hidráulico de paletas para mover esas cajas.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_136',
    emoji: 'plastic-sheeting.png',
    question: '¿Con qué material plástico cubres superficies para protegerlas durante la construcción?',
    translation: 'With what plastic material do you cover surfaces to protect them during construction?',
    options: ['la lámina de plástico', 'la lona', 'el papel'],
    correctAnswer: 'la lámina de plástico',
    hint: 'Thin plastic sheets used to protect floors, furniture, and create moisture barriers',
    usageExample: 'Cubre el piso con la lámina de plástico antes de pintar.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_137',
    emoji: 'plumber.png',
    question: '¿Quién repara tuberías, grifos y sistemas de agua en casas?',
    translation: 'Who repairs pipes, faucets and water systems in houses?',
    options: ['el plomero', 'el electricista', 'el carpintero'],
    correctAnswer: 'el plomero',
    hint: 'Tradesperson who installs and fixes water supply and drainage systems',
    usageExample: 'El plomero arregló la fuga de agua en el baño.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_138',
    emoji: 'road-grader.png',
    question: '¿Qué máquina de construcción nivela y alisa superficies de carreteras?',
    translation: 'What construction machine levels and smooths road surfaces?',
    options: ['la niveladora de caminos', 'el bulldózer', 'la aplanadora'],
    correctAnswer: 'la niveladora de caminos',
    hint: 'Large vehicle with a long blade that creates flat, even surfaces for roads',
    usageExample: 'La niveladora de caminos está preparando la nueva carretera.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_139',
    emoji: 'rolling-ladder.png',
    question: '¿Qué escalera con ruedas se desliza por rieles en bibliotecas y almacenes?',
    translation: 'What ladder with wheels slides along rails in libraries and warehouses?',
    options: ['la escalera rodante', 'la escalera de tijera', 'la escalera fija'],
    correctAnswer: 'la escalera rodante',
    hint: 'Mobile ladder that rolls on a track system to access high shelves safely',
    usageExample: 'Usa la escalera rodante para alcanzar los libros del estante superior.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_140',
    emoji: 'safety-harness.png',
    question: '¿Qué equipo de protección te atas al cuerpo para prevenir caídas en alturas?',
    translation: 'What protective equipment do you strap to your body to prevent falls from heights?',
    options: ['el arnés de seguridad', 'el cinturón', 'la cuerda'],
    correctAnswer: 'el arnés de seguridad',
    hint: 'Full-body strapping system that connects to anchor points to catch workers if they fall',
    usageExample: 'Ponte el arnés de seguridad antes de subir al techo.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'calm',
  },

  {
    id: 'business_141',
    emoji: 'sawhorse.png',
    question: '¿Sobre qué caballete de madera apoyas tablas para cortarlas?',
    translation: 'On what wooden support do you rest boards to cut them?',
    options: ['el caballete de trabajo', 'el banco de trabajo', 'la mesa'],
    correctAnswer: 'el caballete de trabajo',
    hint: 'A-frame support stand used by carpenters to hold wood at working height',
    usageExample: 'Coloca la tabla sobre el caballete de trabajo para cortarla.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_142',
    emoji: 'scaffolding.png',
    question: '¿Qué estructura temporal de tubos y plataformas usan los trabajadores en edificios altos?',
    translation: 'What temporary structure of tubes and platforms do workers use on tall buildings?',
    options: ['el andamio', 'la escalera', 'la plataforma de tijera'],
    correctAnswer: 'el andamio',
    hint: 'Modular metal framework that provides elevated working platforms around buildings under construction',
    usageExample: 'Instalaron el andamio alrededor del edificio para las reparaciones.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_143',
    emoji: 'sharpening-stone.png',
    question: '¿Con qué piedra abrasiva afilas cuchillos y herramientas de corte?',
    translation: 'With what abrasive stone do you sharpen knives and cutting tools?',
    options: ['la piedra de afilar', 'el papel de lija', 'la lima'],
    correctAnswer: 'la piedra de afilar',
    hint: 'Flat stone surface used to grind and hone blade edges to make them sharp',
    usageExample: 'Afila el cuchillo con la piedra de afilar.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_144',
    emoji: 'shipping-scale.png',
    question: '¿Con qué báscula pesas paquetes para calcular el costo de envío?',
    translation: 'With what scale do you weigh packages to calculate shipping cost?',
    options: ['la báscula de envío', 'la báscula de baño', 'la báscula de cocina'],
    correctAnswer: 'la báscula de envío',
    hint: 'Commercial scale used in post offices and warehouses to determine package weight for mailing',
    usageExample: 'Pesa el paquete en la báscula de envío para calcular el costo.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_145',
    emoji: 'soap-dispenser.png',
    question: '¿Qué dispositivo de pared dispensa jabón líquido en baños públicos?',
    translation: 'What wall device dispenses liquid soap in public bathrooms?',
    options: ['el dispensador de jabón', 'el secador de manos', 'el toallero'],
    correctAnswer: 'el dispensador de jabón',
    hint: 'Wall-mounted container that releases soap when you push or pump it',
    usageExample: 'El dispensador de jabón está vacío, hay que llenarlo.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_146',
    emoji: 'software-developer.png',
    question: '¿Quién escribe código de programación para crear aplicaciones y programas?',
    translation: 'Who writes programming code to create applications and programs?',
    options: ['el desarrollador de software', 'el diseñador gráfico', 'el técnico de soporte'],
    correctAnswer: 'el desarrollador de software',
    hint: 'Professional programmer who builds software applications and systems',
    usageExample: 'El desarrollador de software programó la aplicación en tres meses.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_147',
    emoji: 'table-saw.png',
    question: '¿Qué sierra estacionaria de carpintería tiene la hoja montada en una mesa?',
    translation: 'What stationary carpentry saw has the blade mounted on a table?',
    options: ['la sierra de mesa', 'la sierra circular', 'la sierra de mano'],
    correctAnswer: 'la sierra de mesa',
    hint: 'Large workshop saw with blade protruding through table surface for precise straight cuts',
    usageExample: 'La sierra de mesa hace cortes perfectamente rectos.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_148',
    emoji: 'urban-planner.png',
    question: '¿Quién diseña el desarrollo y organización de ciudades y zonas urbanas?',
    translation: 'Who designs the development and organization of cities and urban areas?',
    options: ['el urbanista', 'el arquitecto', 'el ingeniero civil'],
    correctAnswer: 'el urbanista',
    hint: 'Professional who plans land use, transportation, and community development for cities',
    usageExample: 'El urbanista planificó el nuevo parque de la ciudad.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_149',
    emoji: 'ux-designer.png',
    question: '¿Quién diseña la experiencia del usuario en aplicaciones y sitios web?',
    translation: 'Who designs the user experience in applications and websites?',
    options: ['el diseñador UX', 'el programador', 'el gerente de proyecto'],
    correctAnswer: 'el diseñador UX',
    hint: 'Professional who creates intuitive and user-friendly digital interfaces and interactions',
    usageExample: 'El diseñador UX mejoró la navegación del sitio web.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_150',
    emoji: 'warehouse-rack.png',
    question: '¿En qué estructura metálica de almacén se apilan productos en paletas?',
    translation: 'On what metal warehouse structure are products stacked on pallets?',
    options: ['el estante de almacén', 'el archivador', 'la mesa de trabajo'],
    correctAnswer: 'el estante de almacén',
    hint: 'Heavy-duty shelving system with multiple levels for storing large quantities of goods',
    usageExample: 'Los productos están organizados en el estante de almacén.',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_151',
    emoji: 'welding-curtain.png',
    question: '¿Qué cortina protectora bloquea la luz brillante de la soldadura?',
    translation: 'What protective curtain blocks the bright light from welding?',
    options: ['la cortina de soldadura', 'la lona', 'la pantalla'],
    correctAnswer: 'la cortina de soldadura',
    hint: 'Flame-resistant barrier that shields others from welding sparks and harmful UV light',
    usageExample: 'Coloca la cortina de soldadura para proteger a los demás trabajadores.',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'calm',
  },

];
