/**
 * Business Category Questions (Office, Construction & Industry)
 * Category: business
 * IDs: business_001 - business_100
 */

export const businessQuestions = [
 
  {
    id: 'business_001',
    emoji: 'approval.png',
    question: '¿Cómo se obtiene un permiso de construcción?',
    translation: 'How does a building permit get issued?',
    options: ['se obtiene en la oficina de la ciudad', 'se obtiene en la biblioteca', 'se obtiene en el supermercado'],
    correctAnswer: 'se obtiene en la oficina de la ciudad',
    hint: 'Building permits are typically issued by the city office',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_002',
    emoji: 'calculator.png',
    question: '¿Qué usas para hacer cálculos matemáticos en la oficina?',
    translation: 'What do you use to do mathematical calculations in the office?',
    options: ['la calculadora', 'la computadora', 'el teléfono'],
    correctAnswer: 'la calculadora',
    hint: 'Small electronic device specifically designed for quick math calculations',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_003',
    emoji: 'stapler.png',
    question: '¿Con qué herramienta sujetas papeles juntos en la oficina?',
    translation: 'What tool do you use to fasten papers together in the office?',
    options: ['la engrapadora', 'la perforadora', 'las tijeras'],
    correctAnswer: 'la engrapadora',
    hint: 'Office tool that uses metal fasteners to bind papers together',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_004',
    emoji: 'filing-cabinet.png',
    question: '¿Dónde guardas documentos importantes en la oficina?',
    translation: 'Where do you store important documents in the office?',
    options: ['el archivador', 'el escritorio', 'la papelera'],
    correctAnswer: 'el archivador',
    hint: 'Tall furniture with drawers used for organizing and storing files',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_005',
    emoji: 'safety-helmet.png',
    question: '¿Qué equipo de protección usas en la cabeza en una construcción?',
    translation: 'What protective equipment do you wear on your head at a construction site?',
    options: ['el casco de seguridad', 'la gorra', 'el sombrero'],
    correctAnswer: 'el casco de seguridad',
    hint: 'Hard protective headgear required on construction sites',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'calm',
  },

  {
    id: 'business_006',
    emoji: 'measuring-tape.png',
    question: '¿Con qué herramienta mides distancias en construcción?',
    translation: 'What tool do you use to measure distances in construction?',
    options: ['la cinta métrica', 'la regla', 'el nivel'],
    correctAnswer: 'la cinta métrica',
    hint: 'Flexible measuring tool that extends and retracts; used by carpenters and builders',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_007',
    emoji: 'laptop-charger.png',
    question: '¿Qué necesitas para cargar tu computadora portátil?',
    translation: 'What do you need to charge your laptop?',
    options: ['el cargador de portátil', 'el cable USB', 'la batería'],
    correctAnswer: 'el cargador de portátil',
    hint: 'Power adapter with cable that connects laptop to electrical outlet',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_008',
    emoji: 'water-cooler.png',
    question: '¿Dónde tomas agua fría en la oficina?',
    translation: 'Where do you get cold water in the office?',
    options: ['el enfriador de agua', 'el refrigerador', 'la fuente'],
    correctAnswer: 'el enfriador de agua',
    hint: 'Large dispenser that provides cold and hot water; common gathering spot in offices',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_009',
    emoji: 'desk-lamp.png',
    question: '¿Qué usas para iluminar tu escritorio mientras trabajas?',
    translation: 'What do you use to light your desk while working?',
    options: ['la lámpara de escritorio', 'la linterna', 'la vela'],
    correctAnswer: 'la lámpara de escritorio',
    hint: 'Small adjustable light that sits on your work surface for task lighting',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_010',
    emoji: 'screwdriver.png',
    question: '¿Con qué herramienta aprietas o afloja tornillos?',
    translation: 'What tool do you use to tighten or loosen screws?',
    options: ['el destornillador', 'el martillo', 'la llave inglesa'],
    correctAnswer: 'el destornillador',
    hint: 'Hand tool with a handle and metal shaft; used for turning screws',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_011',
    emoji: 'desktop-computer.png',
    question: '¿Qué tipo de computadora usas en el escritorio de la oficina?',
    translation: 'What type of computer do you use on the office desk?',
    options: ['la computadora de escritorio', 'la laptop', 'la tableta'],
    correctAnswer: 'la computadora de escritorio',
    hint: 'Computer that stays in one place with a separate monitor, keyboard, and tower',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_012',
    emoji: 'copier.png',
    question: '¿Qué máquina usas para duplicar documentos en la oficina?',
    translation: 'What machine do you use to duplicate documents in the office?',
    options: ['la copiadora', 'la impresora', 'el escáner'],
    correctAnswer: 'la copiadora',
    hint: 'Office machine that makes identical copies of paper documents',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_013',
    emoji: 'paper-shredder.png',
    question: '¿Con qué máquina destruyes documentos confidenciales?',
    translation: 'What machine do you use to destroy confidential documents?',
    options: ['la trituradora de papel', 'la copiadora', 'la engrapadora'],
    correctAnswer: 'la trituradora de papel',
    hint: 'Machine that cuts paper into tiny strips or pieces for security',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_014',
    emoji: 'envelope.png',
    question: '¿En qué pones una carta antes de enviarla por correo?',
    translation: 'What do you put a letter in before sending it by mail?',
    options: ['el sobre', 'la carpeta', 'el folder'],
    correctAnswer: 'el sobre',
    hint: 'Paper container used to mail letters; you write the address on it',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_015',
    emoji: 'binder.png',
    question: '¿Qué usas para organizar papeles con anillos metálicos?',
    translation: 'What do you use to organize papers with metal rings?',
    options: ['la carpeta de argollas', 'el folder', 'el cuaderno'],
    correctAnswer: 'la carpeta de argollas',
    hint: 'Organizational tool with rings that hold punched papers together',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_016',
    emoji: 'pencil-sharpener.png',
    question: '¿Con qué afilas los lápices?',
    translation: 'What do you use to sharpen pencils?',
    options: ['el sacapuntas', 'la goma de borrar', 'las tijeras'],
    correctAnswer: 'el sacapuntas',
    hint: 'Small device that sharpens pencil tips by shaving the wood',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_017',
    emoji: 'tape-dispenser.png',
    question: '¿Qué herramienta de escritorio tiene cinta adhesiva?',
    translation: 'What desk tool holds adhesive tape?',
    options: ['el dispensador de cinta', 'la engrapadora', 'el cortador'],
    correctAnswer: 'el dispensador de cinta',
    hint: 'Desktop holder with a serrated edge for cutting tape',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_018',
    emoji: 'staples.png',
    question: '¿Qué pequeños objetos metálicos usa la engrapadora?',
    translation: 'What small metal objects does the stapler use?',
    options: ['las grapas', 'los clips', 'los alfileres'],
    correctAnswer: 'las grapas',
    hint: 'Small bent metal fasteners that go through paper',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_019',
    emoji: 'copy-paper.png',
    question: '¿Qué tipo de papel usas en la impresora o copiadora?',
    translation: 'What type of paper do you use in the printer or copier?',
    options: ['el papel de copia', 'el papel de regalo', 'el papel higiénico'],
    correctAnswer: 'el papel de copia',
    hint: 'Standard white sheets used for printing and copying documents',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_020',
    emoji: 'ergonomic-mouse.png',
    question: '¿Qué dispositivo ergonómico usas para mover el cursor?',
    translation: 'What ergonomic device do you use to move the cursor?',
    options: ['el ratón ergonómico', 'el teclado', 'el monitor'],
    correctAnswer: 'el ratón ergonómico',
    hint: 'Computer input device designed to reduce hand and wrist strain',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_021',
    emoji: 'cubicle.png',
    question: '¿Cómo se llama el espacio de trabajo separado por paneles?',
    translation: 'What do you call the workspace separated by panels?',
    options: ['el cubículo', 'la oficina privada', 'la sala de juntas'],
    correctAnswer: 'el cubículo',
    hint: 'Individual workspace divided by partitions in an open office',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_022',
    emoji: 'office.png',
    question: '¿Dónde trabajas si tienes un empleo de oficina?',
    translation: 'Where do you work if you have an office job?',
    options: ['en la oficina', 'en la fábrica', 'en el campo'],
    correctAnswer: 'en la oficina',
    hint: 'Indoor workplace with desks, computers, and administrative tasks',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_023',
    emoji: 'office-building.png',
    question: '¿Cómo se llama el edificio donde están muchas oficinas?',
    translation: 'What do you call the building where many offices are located?',
    options: ['el edificio de oficinas', 'el centro comercial', 'el hospital'],
    correctAnswer: 'el edificio de oficinas',
    hint: 'Tall structure that houses multiple businesses and workspaces',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_024',
    emoji: 'board-room.png',
    question: '¿Dónde se reúne la junta directiva de una empresa?',
    translation: 'Where does the board of directors of a company meet?',
    options: ['en la sala de juntas', 'en el cubículo', 'en el almacén'],
    correctAnswer: 'en la sala de juntas',
    hint: 'Formal meeting room with a large table for executive discussions',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_025',
    emoji: 'meeting.png',
    question: '¿Cómo se llama cuando varias personas se reúnen para discutir trabajo?',
    translation: 'What do you call it when several people gather to discuss work?',
    options: ['la reunión', 'la fiesta', 'el descanso'],
    correctAnswer: 'la reunión',
    hint: 'Scheduled gathering of colleagues to discuss business matters',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'determined',
  },

  {
    id: 'business_026',
    emoji: 'presentation.png',
    question: '¿Qué haces cuando muestras información a un grupo con diapositivas?',
    translation: 'What do you do when you show information to a group with slides?',
    options: ['una presentación', 'una entrevista', 'una llamada'],
    correctAnswer: 'una presentación',
    hint: 'Formal display of information, often using slides or visuals',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'anxious',
  },

  {
    id: 'business_027',
    emoji: 'break-room.png',
    question: '¿Dónde descansas y tomas café en el trabajo?',
    translation: 'Where do you rest and have coffee at work?',
    options: ['en la sala de descanso', 'en la sala de juntas', 'en el estacionamiento'],
    correctAnswer: 'en la sala de descanso',
    hint: 'Common area where employees relax, eat lunch, and socialize',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_028',
    emoji: 'stale-coffee.png',
    question: '¿Cómo se llama el café que está frío y viejo?',
    translation: 'What do you call coffee that is cold and old?',
    options: ['el café pasado', 'el café fresco', 'el café premium'],
    correctAnswer: 'el café pasado',
    hint: 'Coffee that has been sitting too long and lost its freshness',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'disgusted',
  },

  {
    id: 'business_029',
    emoji: 'punch-clock.png',
    question: '¿Con qué registras tu hora de entrada y salida en el trabajo?',
    translation: 'What do you use to record your arrival and departure time at work?',
    options: ['el reloj checador', 'el calendario', 'la alarma'],
    correctAnswer: 'el reloj checador',
    hint: 'Time tracking device that employees use to clock in and out',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_030',
    emoji: 'fingerprint-scanner.png',
    question: '¿Qué dispositivo de seguridad lee tu huella digital?',
    translation: 'What security device reads your fingerprint?',
    options: ['el escáner de huellas', 'la cámara', 'el teclado'],
    correctAnswer: 'el escáner de huellas',
    hint: 'Biometric device that identifies people by their fingerprints',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_031',
    emoji: 'safety-boots.png',
    question: '¿Qué calzado de protección usas en una construcción?',
    translation: 'What protective footwear do you wear at a construction site?',
    options: ['las botas de seguridad', 'las sandalias', 'los zapatos deportivos'],
    correctAnswer: 'las botas de seguridad',
    hint: 'Heavy-duty boots with steel toes for protecting feet at work sites',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'calm',
  },

  {
    id: 'business_032',
    emoji: 'tool-belt.png',
    question: '¿Qué te pones en la cintura para llevar herramientas?',
    translation: 'What do you wear around your waist to carry tools?',
    options: ['el cinturón de herramientas', 'la mochila', 'el bolsillo'],
    correctAnswer: 'el cinturón de herramientas',
    hint: 'Belt with pouches and loops worn by workers to hold tools',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_033',
    emoji: 'work-light.png',
    question: '¿Qué iluminación portátil usas en áreas de trabajo oscuras?',
    translation: 'What portable lighting do you use in dark work areas?',
    options: ['la lámpara de trabajo', 'la vela', 'el fósforo'],
    correctAnswer: 'la lámpara de trabajo',
    hint: 'Bright portable light used on construction sites and workshops',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_034',
    emoji: 'respirator-mask.png',
    question: '¿Qué equipo de protección usas para evitar respirar polvo o químicos?',
    translation: 'What protective equipment do you use to avoid breathing dust or chemicals?',
    options: ['la máscara respiradora', 'los lentes de seguridad', 'los guantes'],
    correctAnswer: 'la máscara respiradora',
    hint: 'Protective mask that filters air to protect lungs from hazards',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'anxious',
  },

  {
    id: 'business_035',
    emoji: 'building-crane.png',
    question: '¿Qué máquina grande levanta materiales pesados en construcción?',
    translation: 'What large machine lifts heavy materials in construction?',
    options: ['la grúa de construcción', 'el montacargas', 'la excavadora'],
    correctAnswer: 'la grúa de construcción',
    hint: 'Tall machine with a long arm used to lift and move heavy loads',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_036',
    emoji: 'blueprints.png',
    question: '¿Cómo se llaman los planos técnicos de un edificio?',
    translation: 'What do you call the technical plans of a building?',
    options: ['los planos', 'los mapas', 'los dibujos'],
    correctAnswer: 'los planos',
    hint: 'Detailed architectural drawings showing how to construct a building',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_037',
    emoji: 'chordless-drill.png',
    question: '¿Qué herramienta eléctrica sin cable usas para hacer agujeros?',
    translation: 'What cordless power tool do you use to make holes?',
    options: ['el taladro inalámbrico', 'el destornillador', 'la sierra'],
    correctAnswer: 'el taladro inalámbrico',
    hint: 'Battery-powered tool that drills holes and drives screws',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_038',
    emoji: 'nail-gun.png',
    question: '¿Qué herramienta neumática dispara clavos rápidamente?',
    translation: 'What pneumatic tool shoots nails quickly?',
    options: ['la pistola de clavos', 'el martillo', 'la grapadora'],
    correctAnswer: 'la pistola de clavos',
    hint: 'Power tool that drives nails into wood or other materials with compressed air',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_039',
    emoji: 'arc-welder.png',
    question: '¿Con qué equipo unes metales usando calor intenso?',
    translation: 'What equipment do you use to join metals using intense heat?',
    options: ['la soldadora de arco', 'el soplete', 'el horno'],
    correctAnswer: 'la soldadora de arco',
    hint: 'Machine that uses electricity to melt and fuse metal pieces together',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'anxious',
  },

  {
    id: 'business_040',
    emoji: 'soldering-iron.png',
    question: '¿Qué herramienta caliente usas para unir componentes electrónicos?',
    translation: 'What hot tool do you use to join electronic components?',
    options: ['el cautín', 'el destornillador', 'el soldador'],
    correctAnswer: 'el cautín',
    hint: 'Handheld tool with a heated tip used to melt solder for electronics',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_041',
    emoji: 'drill-press.png',
    question: '¿Qué máquina estacionaria usas para perforar con precisión?',
    translation: 'What stationary machine do you use for precise drilling?',
    options: ['el taladro de columna', 'el taladro de mano', 'la sierra'],
    correctAnswer: 'el taladro de columna',
    hint: 'Fixed drill machine mounted on a stand for accurate vertical drilling',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_042',
    emoji: 'lathe.png',
    question: '¿Qué máquina gira la pieza para dar forma cilíndrica?',
    translation: 'What machine rotates the workpiece to create cylindrical shapes?',
    options: ['el torno', 'el taladro', 'la fresadora'],
    correctAnswer: 'el torno',
    hint: 'Machine that spins material to shape it with cutting tools',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_043',
    emoji: 'cnc-machine.png',
    question: '¿Qué máquina controlada por computadora hace cortes precisos?',
    translation: 'What computer-controlled machine makes precise cuts?',
    options: ['la máquina CNC', 'el taladro manual', 'la sierra eléctrica'],
    correctAnswer: 'la máquina CNC',
    hint: 'Automated machine controlled by computer programs for precision manufacturing',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_044',
    emoji: 'factory.png',
    question: '¿Dónde se fabrican productos en grandes cantidades?',
    translation: 'Where are products manufactured in large quantities?',
    options: ['en la fábrica', 'en la oficina', 'en la tienda'],
    correctAnswer: 'en la fábrica',
    hint: 'Industrial facility with machines and workers producing goods at scale',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_045',
    emoji: 'robot.png',
    question: '¿Qué máquina automática hace trabajos repetitivos en fábricas?',
    translation: 'What automatic machine does repetitive work in factories?',
    options: ['el robot', 'la computadora', 'el montacargas'],
    correctAnswer: 'el robot',
    hint: 'Programmable machine that performs tasks automatically in manufacturing',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_046',
    emoji: 'trowel.png',
    question: '¿Con qué herramienta aplicas y alisas el cemento?',
    translation: 'What tool do you use to apply and smooth cement?',
    options: ['la llana', 'la pala', 'el rastrillo'],
    correctAnswer: 'la llana',
    hint: 'Flat handheld tool used by masons to spread and level mortar or concrete',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_047',
    emoji: 'plumbing.png',
    question: '¿Qué oficio se encarga de tuberías y sistemas de agua?',
    translation: 'What trade deals with pipes and water systems?',
    options: ['la plomería', 'la carpintería', 'la electricidad'],
    correctAnswer: 'la plomería',
    hint: 'Trade involving installation and repair of water pipes and fixtures',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_048',
    emoji: 'cleaning-cart.png',
    question: '¿Qué carrito usa el personal de limpieza con productos y trapeadores?',
    translation: 'What cart does cleaning staff use with products and mops?',
    options: ['el carrito de limpieza', 'el carrito de compras', 'la carretilla'],
    correctAnswer: 'el carrito de limpieza',
    hint: 'Mobile cart containing cleaning supplies, mops, and trash bags',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_049',
    emoji: 'floor-cleaner.png',
    question: '¿Qué máquina grande limpia pisos de manera profunda?',
    translation: 'What large machine deep cleans floors?',
    options: ['la limpiadora de pisos', 'la aspiradora', 'el trapeador'],
    correctAnswer: 'la limpiadora de pisos',
    hint: 'Industrial machine that scrubs and cleans large floor areas',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_050',
    emoji: 'floor-polisher.png',
    question: '¿Qué máquina hace brillar los pisos?',
    translation: 'What machine makes floors shine?',
    options: ['la pulidora de pisos', 'la aspiradora', 'el trapeador'],
    correctAnswer: 'la pulidora de pisos',
    hint: 'Machine with rotating pads that buffs and polishes floor surfaces',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_051',
    emoji: 'laser-engraver.png',
    question: '¿Qué máquina usa láser para grabar diseños en materiales?',
    translation: 'What machine uses laser to engrave designs on materials?',
    options: ['la grabadora láser', 'la impresora', 'la copiadora'],
    correctAnswer: 'la grabadora láser',
    hint: 'Precision machine that uses focused laser beams to etch patterns on various surfaces',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_052',
    emoji: 'orbital-sander.png',
    question: '¿Qué herramienta eléctrica usas para lijar superficies de madera?',
    translation: 'What power tool do you use to sand wood surfaces?',
    options: ['la lijadora orbital', 'el taladro', 'la sierra'],
    correctAnswer: 'la lijadora orbital',
    hint: 'Power tool with circular sanding pad that smooths wood surfaces',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_053',
    emoji: 'satellite-dish.png',
    question: '¿Qué antena parabólica recibe señales de comunicación satelital?',
    translation: 'What parabolic antenna receives satellite communication signals?',
    options: ['la antena parabólica', 'la antena de radio', 'el router'],
    correctAnswer: 'la antena parabólica',
    hint: 'Dish-shaped antenna that receives signals from satellites in space',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_054',
    emoji: '3d-printer.png',
    question: '¿Qué máquina crea objetos tridimensionales capa por capa?',
    translation: 'What machine creates three-dimensional objects layer by layer?',
    options: ['la impresora 3D', 'la fotocopiadora', 'el escáner'],
    correctAnswer: 'la impresora 3D',
    hint: 'Advanced machine that builds physical objects from digital designs using additive manufacturing',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_055',
    emoji: 'access-badge.png',
    question: '¿Qué tarjeta usas para entrar a edificios seguros?',
    translation: 'What card do you use to enter secure buildings?',
    options: ['la tarjeta de acceso', 'la tarjeta de crédito', 'la licencia de conducir'],
    correctAnswer: 'la tarjeta de acceso',
    hint: 'Security badge that grants entry to restricted areas',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_056',
    emoji: 'accounting.png',
    question: '¿Qué departamento maneja las finanzas y los libros contables?',
    translation: 'What department handles finances and accounting books?',
    options: ['la contabilidad', 'el almacén', 'el marketing'],
    correctAnswer: 'la contabilidad',
    hint: 'Department responsible for managing financial records and transactions',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_057',
    emoji: 'air-compressor.png',
    question: '¿Qué máquina produce aire comprimido para herramientas neumáticas?',
    translation: 'What machine produces compressed air for pneumatic tools?',
    options: ['el compresor de aire', 'el ventilador', 'la bomba de agua'],
    correctAnswer: 'el compresor de aire',
    hint: 'Machine that pressurizes air to power tools and inflate tires',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_058',
    emoji: 'band-saw.png',
    question: '¿Qué sierra tiene una hoja continua en forma de banda?',
    translation: 'What saw has a continuous blade in the shape of a band?',
    options: ['la sierra de banda', 'la sierra circular', 'la sierra de mano'],
    correctAnswer: 'la sierra de banda',
    hint: 'Power saw with a long blade loop for cutting curves and irregular shapes',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_059',
    emoji: 'belt-sander.png',
    question: '¿Qué lijadora usa una banda de lija continua?',
    translation: 'What sander uses a continuous sanding belt?',
    options: ['la lijadora de banda', 'la lijadora orbital', 'el papel de lija'],
    correctAnswer: 'la lijadora de banda',
    hint: 'Power sander with a looped abrasive belt for aggressive material removal',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_060',
    emoji: 'bolt-cutter.png',
    question: '¿Con qué herramienta cortas cadenas y candados gruesos?',
    translation: 'What tool do you use to cut chains and thick padlocks?',
    options: ['la cizalla', 'las tijeras', 'el martillo'],
    correctAnswer: 'la cizalla',
    hint: 'Heavy-duty cutting tool with long handles for cutting through metal',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'determined',
  },

  {
    id: 'business_061',
    emoji: 'chainsaw.png',
    question: '¿Con qué herramienta motorizada cortas árboles y madera gruesa?',
    translation: 'What motorized tool do you use to cut trees and thick wood?',
    options: ['la motosierra', 'la sierra de mano', 'el hacha'],
    correctAnswer: 'la motosierra',
    hint: 'Powerful portable saw with rotating chain for cutting through wood',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_062',
    emoji: 'chisel.png',
    question: '¿Con qué herramienta manual tallás o cortas madera con precisión?',
    translation: 'What hand tool do you use to carve or cut wood precisely?',
    options: ['el cincel', 'el martillo', 'el destornillador'],
    correctAnswer: 'el cincel',
    hint: 'Sharp-edged hand tool used with a mallet for shaping wood or stone',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_063',
    emoji: 'conveyor-belt.png',
    question: '¿Qué sistema automático mueve productos en una fábrica?',
    translation: 'What automatic system moves products in a factory?',
    options: ['la banda transportadora', 'la carretilla', 'el montacargas'],
    correctAnswer: 'la banda transportadora',
    hint: 'Continuous moving belt that transports items along an assembly line',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_064',
    emoji: 'cybersecurity.png',
    question: '¿Qué práctica protege sistemas informáticos contra ataques digitales?',
    translation: 'What practice protects computer systems against digital attacks?',
    options: ['la ciberseguridad', 'el antivirus', 'el firewall'],
    correctAnswer: 'la ciberseguridad',
    hint: 'Field focused on protecting networks, devices, and data from cyber threats',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'determined',
  },

  {
    id: 'business_065',
    emoji: 'datacenter.png',
    question: '¿Dónde se almacenan y procesan grandes cantidades de datos?',
    translation: 'Where is large amounts of data stored and processed?',
    options: ['el centro de datos', 'la biblioteca', 'la oficina'],
    correctAnswer: 'el centro de datos',
    hint: 'Facility housing servers and networking equipment for data storage and processing',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_066',
    emoji: 'ear-protectors.png',
    question: '¿Qué equipo de protección usas para proteger tus oídos del ruido?',
    translation: 'What protective equipment do you use to protect your ears from noise?',
    options: ['los protectores auditivos', 'los audífonos', 'los lentes'],
    correctAnswer: 'los protectores auditivos',
    hint: 'Safety equipment worn over ears to reduce loud noise exposure',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'calm',
  },

  {
    id: 'business_067',
    emoji: 'embroidery-machine.png',
    question: '¿Qué máquina cose diseños decorativos automáticamente en tela?',
    translation: 'What machine automatically sews decorative designs on fabric?',
    options: ['la máquina de bordar', 'la máquina de coser', 'la plancha'],
    correctAnswer: 'la máquina de bordar',
    hint: 'Specialized sewing machine that creates intricate patterns and designs on fabric',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_068',
    emoji: 'floor-jack.png',
    question: '¿Qué herramienta usas para levantar vehículos del suelo?',
    translation: 'What tool do you use to lift vehicles off the ground?',
    options: ['el gato hidráulico', 'la grúa', 'el montacargas'],
    correctAnswer: 'el gato hidráulico',
    hint: 'Wheeled hydraulic device that lifts cars for maintenance and repairs',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_069',
    emoji: 'forklift.png',
    question: '¿Qué vehículo industrial usa para levantar y mover paletas?',
    translation: 'What industrial vehicle do you use to lift and move pallets?',
    options: ['el montacargas', 'el camión', 'la grúa'],
    correctAnswer: 'el montacargas',
    hint: 'Powered industrial truck with fork-shaped prongs for lifting heavy loads',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_070',
    emoji: 'generator.png',
    question: '¿Qué máquina produce electricidad cuando no hay energía?',
    translation: 'What machine produces electricity when there is no power?',
    options: ['el generador', 'la batería', 'el panel solar'],
    correctAnswer: 'el generador',
    hint: 'Backup power machine that converts fuel into electrical energy',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_071',
    emoji: 'hammer-drill.png',
    question: '¿Qué taladro también martilla mientras perfora materiales duros?',
    translation: 'What drill also hammers while drilling through hard materials?',
    options: ['el taladro percutor', 'el taladro normal', 'el destornillador eléctrico'],
    correctAnswer: 'el taladro percutor',
    hint: 'Power drill with hammering action for drilling into concrete and masonry',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_072',
    emoji: 'hammer.png',
    question: '¿Con qué herramienta básica golpeas clavos?',
    translation: 'What basic tool do you use to hit nails?',
    options: ['el martillo', 'el destornillador', 'la llave'],
    correctAnswer: 'el martillo',
    hint: 'Common hand tool with a heavy head for driving nails into wood',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_073',
    emoji: 'heat-gun.png',
    question: '¿Qué herramienta produce aire muy caliente para quitar pintura?',
    translation: 'What tool produces very hot air to remove paint?',
    options: ['la pistola de calor', 'el secador de pelo', 'la plancha'],
    correctAnswer: 'la pistola de calor',
    hint: 'Electric tool that blows extremely hot air for stripping paint and shrinking materials',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_074',
    emoji: 'hydraulic-press.png',
    question: '¿Qué máquina usa presión hidráulica para comprimir o dar forma a materiales?',
    translation: 'What machine uses hydraulic pressure to compress or shape materials?',
    options: ['la prensa hidráulica', 'el tornillo de banco', 'el martillo'],
    correctAnswer: 'la prensa hidráulica',
    hint: 'Powerful machine that uses fluid pressure to exert tremendous force for shaping metal',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_075',
    emoji: 'laser-level.png',
    question: '¿Qué herramienta proyecta una línea láser para nivelar con precisión?',
    translation: 'What tool projects a laser line to level precisely?',
    options: ['el nivel láser', 'el nivel de burbuja', 'la regla'],
    correctAnswer: 'el nivel láser',
    hint: 'Electronic leveling tool that projects a laser beam for accurate alignment',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_076',
    emoji: 'leaf-blower.png',
    question: '¿Qué herramienta motorizada usa para soplar hojas y escombros?',
    translation: 'What motorized tool do you use to blow leaves and debris?',
    options: ['la sopladora de hojas', 'la aspiradora', 'el rastrillo'],
    correctAnswer: 'la sopladora de hojas',
    hint: 'Powered tool that blows air to clear leaves and debris from outdoor areas',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_077',
    emoji: 'level.png',
    question: '¿Con qué herramienta verificas si una superficie está horizontal?',
    translation: 'What tool do you use to check if a surface is level?',
    options: ['el nivel de burbuja', 'la regla', 'la cinta métrica'],
    correctAnswer: 'el nivel de burbuja',
    hint: 'Tool with a liquid-filled tube and air bubble to check if surfaces are perfectly horizontal',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_078',
    emoji: 'lobby.png',
    question: '¿Dónde esperas antes de entrar a una oficina o reunión?',
    translation: 'Where do you wait before entering an office or meeting?',
    options: ['en el vestíbulo', 'en el baño', 'en el estacionamiento'],
    correctAnswer: 'en el vestíbulo',
    hint: 'Entry area or reception space in a building where visitors wait',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_079',
    emoji: 'metalworking-file.png',
    question: '¿Con qué herramienta manual limas metal para alisarlo?',
    translation: 'What hand tool do you use to file metal to smooth it?',
    options: ['la lima de metal', 'el papel de lija', 'la sierra'],
    correctAnswer: 'la lima de metal',
    hint: 'Metal hand tool with rough surface for smoothing and shaping metal edges',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_080',
    emoji: 'microscope.png',
    question: '¿Con qué instrumento ves objetos muy pequeños ampliados?',
    translation: 'What instrument do you use to see very small objects magnified?',
    options: ['el microscopio', 'el telescopio', 'la lupa'],
    correctAnswer: 'el microscopio',
    hint: 'Scientific instrument with lenses that magnifies tiny objects for detailed examination',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'excited',
  },

  {
    id: 'business_081',
    emoji: 'money-counter.png',
    question: '¿Qué máquina cuenta billetes automáticamente?',
    translation: 'What machine counts bills automatically?',
    options: ['la contadora de dinero', 'la caja registradora', 'la calculadora'],
    correctAnswer: 'la contadora de dinero',
    hint: 'Machine that rapidly counts and verifies paper currency',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  {
    id: 'business_082',
    emoji: 'nut-and-bolt.png',
    question: '¿Qué par de piezas metálicas se atornillan juntas para sujetar?',
    translation: 'What pair of metal pieces screw together to fasten?',
    options: ['la tuerca y el perno', 'el clavo y el martillo', 'el tornillo y el destornillador'],
    correctAnswer: 'la tuerca y el perno',
    hint: 'Threaded fastener pair where one piece screws into the other',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_083',
    emoji: 'pipe-flange.png',
    question: '¿Qué pieza metálica circular une dos secciones de tubería?',
    translation: 'What circular metal piece connects two sections of pipe?',
    options: ['la brida de tubería', 'la tuerca', 'el perno'],
    correctAnswer: 'la brida de tubería',
    hint: 'Flat circular fitting bolted to pipe ends to create a sealed connection',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_084',
    emoji: 'post-hole-digger.png',
    question: '¿Con qué herramienta cavas agujeros profundos para postes?',
    translation: 'What tool do you use to dig deep holes for posts?',
    options: ['el cavador de postes', 'la pala', 'el pico'],
    correctAnswer: 'el cavador de postes',
    hint: 'Two-handled tool with clamping blades for digging narrow, deep holes for fence posts',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_085',
    emoji: 'rivet-gun.png',
    question: '¿Qué herramienta usas para unir láminas de metal con remaches?',
    translation: 'What tool do you use to join metal sheets with rivets?',
    options: ['la remachadora', 'la grapadora', 'el martillo'],
    correctAnswer: 'la remachadora',
    hint: 'Tool that squeezes and deforms rivets to permanently fasten metal plates together',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_086',
    emoji: 'roof-renovation.png',
    question: '¿Qué tipo de proyecto repara o reemplaza el techo de un edificio?',
    translation: 'What type of project repairs or replaces the roof of a building?',
    options: ['la renovación de techo', 'la pintura exterior', 'la instalación eléctrica'],
    correctAnswer: 'la renovación de techo',
    hint: 'Construction project focused on fixing or replacing roofing materials',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'business_087',
    emoji: 'safety-air-horn.png',
    question: '¿Qué dispositivo de seguridad produce un sonido muy fuerte para alertar?',
    translation: 'What safety device produces a very loud sound to alert?',
    options: ['la bocina de seguridad', 'la alarma de incendios', 'el silbato'],
    correctAnswer: 'la bocina de seguridad',
    hint: 'Compressed air horn used to signal warnings on work sites and emergencies',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'anxious',
  },

  {
    id: 'business_088',
    emoji: 'safety-mirror.png',
    question: '¿Qué espejo convexo usas para ver esquinas ciegas en almacenes?',
    translation: 'What convex mirror do you use to see blind corners in warehouses?',
    options: ['el espejo de seguridad', 'el espejo de baño', 'el espejo retrovisor'],
    correctAnswer: 'el espejo de seguridad',
    hint: 'Curved mirror mounted at intersections to improve visibility and prevent accidents',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'calm',
  },

  {
    id: 'business_089',
    emoji: 'sandblaster.png',
    question: '¿Qué máquina usa arena a presión para limpiar o alisar superficies?',
    translation: 'What machine uses pressurized sand to clean or smooth surfaces?',
    options: ['la arenadora', 'la pulidora', 'la lijadora'],
    correctAnswer: 'la arenadora',
    hint: 'Machine that shoots abrasive material at high speed to remove paint or rust from surfaces',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_090',
    emoji: 'scissor-lift .png',
    question: '¿Qué plataforma elevadora de tijera usas para trabajar en alturas?',
    translation: 'What scissor lift platform do you use to work at heights?',
    options: ['la plataforma de tijera', 'la escalera', 'el andamio'],
    correctAnswer: 'la plataforma de tijera',
    hint: 'Mobile elevated work platform with crisscross support that extends vertically',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_091',
    emoji: 'screw.png',
    question: '¿Qué sujetador con rosca usas con un destornillador?',
    translation: 'What threaded fastener do you use with a screwdriver?',
    options: ['el tornillo', 'el clavo', 'el perno'],
    correctAnswer: 'el tornillo',
    hint: 'Threaded metal fastener that is turned into material to hold things together',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  {
    id: 'business_092',
    emoji: 'shipping-container.png',
    question: '¿En qué gran caja metálica se transportan mercancías por barco?',
    translation: 'What large metal box is used to transport goods by ship?',
    options: ['el contenedor de carga', 'el camión', 'la caja de cartón'],
    correctAnswer: 'el contenedor de carga',
    hint: 'Standardized metal box used for shipping goods internationally by sea, rail, or truck',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_093',
    emoji: 'steel-i-beam.png',
    question: '¿Qué viga de acero en forma de I se usa en la construcción de edificios?',
    translation: 'What I-shaped steel beam is used in building construction?',
    options: ['la viga de acero', 'el tubo', 'la columna'],
    correctAnswer: 'la viga de acero',
    hint: 'Heavy I-shaped structural steel used to support buildings and bridges',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'business_094',
    emoji: 'tap-wrench .png',
    question: '¿Con qué herramienta creas roscas internas en agujeros de metal?',
    translation: 'What tool do you use to create internal threads in metal holes?',
    options: ['el macho de roscar', 'el taladro', 'el destornillador'],
    correctAnswer: 'el macho de roscar',
    hint: 'Threading tool with handle used to cut threads inside holes for screws and bolts',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  {
    id: 'business_095',
    emoji: 'thermal-camera.png',
    question: '¿Qué cámara detecta diferencias de temperatura mediante imágenes?',
    translation: 'What camera detects temperature differences through images?',
    options: ['la cámara térmica', 'la cámara digital', 'la cámara de seguridad'],
    correctAnswer: 'la cámara térmica',
    hint: 'Imaging device that shows heat patterns and temperature variations',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_096',
    emoji: 'tilt-truck.png',
    question: '¿Qué carrito industrial se inclina para vaciar su contenido?',
    translation: 'What industrial cart tilts to empty its contents?',
    options: ['el carrito basculante', 'la carretilla', 'el carrito de compras'],
    correctAnswer: 'el carrito basculante',
    hint: 'Heavy-duty wheeled cart that tilts forward to dump materials easily',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  {
    id: 'business_097',
    emoji: 'transistor.png',
    question: '¿Qué componente electrónico amplifica o conmuta señales?',
    translation: 'What electronic component amplifies or switches signals?',
    options: ['el transistor', 'el capacitor', 'la resistencia'],
    correctAnswer: 'el transistor',
    hint: 'Semiconductor device fundamental to modern electronics and computing',
    points: 15,
    category: 'business',
    difficulty: 'hard',
    emotion: 'excited',
  },

  {
    id: 'business_098',
    emoji: 'welding-apron.png',
    question: '¿Qué protección se usa durante trabajos de soldadura?',
    translation: 'What protection is worn during welding work?',
    options: ['el delantal de soldadura', 'el chaleco reflectante', 'el cinturón de herramientas'],
    correctAnswer: 'el delantal de soldadura',
    hint: 'Leather protective garment that shields the body from sparks and heat',
    points: 10,
    category: 'business',
    difficulty: 'medium',
    emotion: 'calm',
  },

  {
    id: 'business_099',
    emoji: 'workbench.png',
    question: '¿Dónde se realizan trabajos manuales y reparaciones?',
    translation: 'Where are manual tasks and repairs performed?',
    options: ['el banco de trabajo', 'el escritorio', 'el mostrador'],
    correctAnswer: 'el banco de trabajo',
    hint: 'Sturdy table with tools and vise for workshop projects',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'pleased',
  },

  {
    id: 'business_100',
    emoji: 'wrench.png',
    question: '¿Qué herramienta se usa para apretar tuercas y pernos?',
    translation: 'What tool is used to tighten nuts and bolts?',
    options: ['la llave', 'el destornillador', 'el martillo'],
    correctAnswer: 'la llave',
    hint: 'Essential hand tool with adjustable or fixed jaw for turning fasteners',
    points: 5,
    category: 'business',
    difficulty: 'easy',
    emotion: 'neutral',
  },

];
