/**
 * DAILY ROUTINES Category Questions
 * Category: daily_routines
 */

export const dailyRoutinesQuestions = [
  // Morning Routine (1-20)
  {
    id: 'daily_001',
    emoji: '⏰',
    question: '¿Qué haces cuando suena el despertador?',
    options: ['me despierto', 'me duermo', 'desayuno'],
    correctAnswer: 'me despierto',
    hint: 'Wake up - reflexive verb "despertarse", starts your day',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_002',
    emoji: '🛏️',
    question: '¿Qué haces después de despertarte?',
    options: ['me levanto', 'me acuesto', 'duermo'],
    correctAnswer: 'me levanto',
    hint: 'Get up - "levantarse" from "levantar" (to lift/raise)',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_003',
    emoji: '🚿',
    question: '¿Qué haces en el baño por la mañana?',
    options: ['me ducho', 'me peino', 'me visto'],
    correctAnswer: 'me ducho',
    hint: 'Shower - "ducharse", from "ducha" (shower)',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_004',
    emoji: '🪥',
    question: '¿Qué haces con el cepillo de dientes?',
    options: ['me cepillo los dientes', 'me peino', 'me lavo las manos'],
    correctAnswer: 'me cepillo los dientes',
    hint: 'Brush teeth - "cepillarse los dientes"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_005',
    emoji: '💇',
    question: '¿Qué haces con el peine?',
    options: ['me peino', 'me afeito', 'me maquillo'],
    correctAnswer: 'me peino',
    hint: 'Comb hair - "peinarse" from "peine" (comb)',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_006',
    emoji: '👔',
    question: '¿Qué haces con la ropa?',
    options: ['me visto', 'me ducho', 'me siento'],
    correctAnswer: 'me visto',
    hint: 'Get dressed - "vestirse" from "vestir"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_007',
    emoji: '🍳',
    question: '¿Qué haces antes de ir al trabajo?',
    options: ['desayuno', 'almuerzo', 'ceno'],
    correctAnswer: 'desayuno',
    hint: 'Have breakfast - "desayunar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_008',
    emoji: '☕',
    question: '¿Qué bebes por la mañana?',
    options: ['café', 'cerveza', 'vino'],
    correctAnswer: 'café',
    hint: 'Coffee - common morning beverage',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_009',
    emoji: '🪒',
    question: '¿Qué hace un hombre con la barba?',
    options: ['se afeita', 'se peina', 'se ducha'],
    correctAnswer: 'se afeita',
    hint: 'Shave - "afeitarse"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_010',
    emoji: '💄',
    question: '¿Qué hace alguien con el maquillaje?',
    options: ['se maquilla', 'se afeita', 'se ducha'],
    correctAnswer: 'se maquilla',
    hint: 'Put on makeup - "maquillarse"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_011',
    emoji: '🧴',
    question: '¿Qué haces después de la ducha?',
    options: ['me seco', 'me mojo', 'me duermo'],
    correctAnswer: 'me seco',
    hint: 'Dry off - "secarse"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_012',
    emoji: '👟',
    question: '¿Qué haces con los zapatos?',
    options: ['me los pongo', 'me los quito', 'los como'],
    correctAnswer: 'me los pongo',
    hint: 'Put on - "ponerse"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_013',
    emoji: '🪞',
    question: '¿Dónde te miras por la mañana?',
    options: ['en el espejo', 'en la cama', 'en la cocina'],
    correctAnswer: 'en el espejo',
    hint: 'Mirror - "espejo"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_014',
    emoji: '🧼',
    question: '¿Qué haces con las manos antes de comer?',
    options: ['me lavo las manos', 'me ducho', 'me acuesto'],
    correctAnswer: 'me lavo las manos',
    hint: 'Wash hands - "lavarse las manos"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_015',
    emoji: '🎒',
    question: '¿Qué preparas antes de salir?',
    options: ['la mochila', 'la cama', 'el desayuno'],
    correctAnswer: 'la mochila',
    hint: 'Backpack - "mochila"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_016',
    emoji: '🔑',
    question: '¿Qué necesitas para salir de casa?',
    options: ['las llaves', 'la almohada', 'la ducha'],
    correctAnswer: 'las llaves',
    hint: 'Keys - "llaves"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_017',
    emoji: '🚪',
    question: '¿Qué haces cuando sales de casa?',
    options: ['cierro la puerta', 'abro la ventana', 'enciendo la luz'],
    correctAnswer: 'cierro la puerta',
    hint: 'Close the door - "cerrar la puerta"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_018',
    emoji: '📱',
    question: '¿Qué revisas por la mañana?',
    options: ['el móvil', 'la almohada', 'el armario'],
    correctAnswer: 'el móvil',
    hint: 'Mobile phone - "móvil"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_019',
    emoji: '🌅',
    question: '¿Cuándo te despiertas?',
    options: ['por la mañana', 'por la noche', 'al mediodía'],
    correctAnswer: 'por la mañana',
    hint: 'In the morning - "por la mañana"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_020',
    emoji: '⏱️',
    question: '¿Qué programas para despertarte?',
    options: ['el despertador', 'el televisor', 'el ordenador'],
    correctAnswer: 'el despertador',
    hint: 'Alarm clock - "despertador"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },

  // Work/School Day (21-40)
  {
    id: 'daily_021',
    emoji: '🚗',
    question: '¿Cómo vas al trabajo?',
    options: ['en coche', 'en cama', 'en ducha'],
    correctAnswer: 'en coche',
    hint: 'By car - "en coche"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_022',
    emoji: '🚌',
    question: '¿Qué transporte público usas?',
    options: ['el autobús', 'la almohada', 'la ducha'],
    correctAnswer: 'el autobús',
    hint: 'Bus - "autobús"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_023',
    emoji: '🚇',
    question: '¿Qué tomas en la ciudad para ir rápido?',
    options: ['el metro', 'la cama', 'el desayuno'],
    correctAnswer: 'el metro',
    hint: 'Subway/Metro - "metro"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_024',
    emoji: '🚶',
    question: '¿Cómo vas si está cerca?',
    options: ['camino', 'vuelo', 'nado'],
    correctAnswer: 'camino',
    hint: 'Walk - "caminar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_025',
    emoji: '💼',
    question: '¿Qué llevas al trabajo?',
    options: ['el maletín', 'la almohada', 'la ducha'],
    correctAnswer: 'el maletín',
    hint: 'Briefcase - "maletín"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_026',
    emoji: '💻',
    question: '¿Qué usas para trabajar?',
    options: ['el ordenador', 'la cama', 'la ducha'],
    correctAnswer: 'el ordenador',
    hint: 'Computer - "ordenador"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_027',
    emoji: '📧',
    question: '¿Qué revisas en el trabajo?',
    options: ['los correos', 'las almohadas', 'las duchas'],
    correctAnswer: 'los correos',
    hint: 'Emails - "correos"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_028',
    emoji: '📞',
    question: '¿Qué haces para comunicarte?',
    options: ['llamo por teléfono', 'duermo', 'me ducho'],
    correctAnswer: 'llamo por teléfono',
    hint: 'Make a phone call - "llamar por teléfono"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_029',
    emoji: '🤝',
    question: '¿Qué tienes con tus colegas?',
    options: ['reuniones', 'duchas', 'siestas'],
    correctAnswer: 'reuniones',
    hint: 'Meetings - "reuniones"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_030',
    emoji: '📝',
    question: '¿Qué haces con los documentos?',
    options: ['escribo', 'duermo', 'como'],
    correctAnswer: 'escribo',
    hint: 'Write - "escribir"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_031',
    emoji: '☕',
    question: '¿Qué tomas durante el trabajo?',
    options: ['un café', 'una siesta', 'una ducha'],
    correctAnswer: 'un café',
    hint: 'A coffee - common work break',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_032',
    emoji: '🍴',
    question: '¿Qué haces al mediodía?',
    options: ['almuerzo', 'desayuno', 'ceno'],
    correctAnswer: 'almuerzo',
    hint: 'Have lunch - "almorzar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_033',
    emoji: '🏢',
    question: '¿Dónde trabajas?',
    options: ['en la oficina', 'en la cama', 'en la ducha'],
    correctAnswer: 'en la oficina',
    hint: 'In the office - "en la oficina"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_034',
    emoji: '📚',
    question: '¿Qué haces en la escuela?',
    options: ['estudio', 'duermo', 'cocino'],
    correctAnswer: 'estudio',
    hint: 'Study - "estudiar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_035',
    emoji: '📖',
    question: '¿Qué haces con los libros?',
    options: ['leo', 'como', 'duermo'],
    correctAnswer: 'leo',
    hint: 'Read - "leer"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_036',
    emoji: '✏️',
    question: '¿Con qué escribes?',
    options: ['con un lápiz', 'con una cama', 'con una ducha'],
    correctAnswer: 'con un lápiz',
    hint: 'With a pencil - "lápiz"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_037',
    emoji: '👨‍🏫',
    question: '¿A quién escuchas en clase?',
    options: ['al profesor', 'a la cama', 'a la ducha'],
    correctAnswer: 'al profesor',
    hint: 'To the teacher - "profesor"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_038',
    emoji: '📓',
    question: '¿Dónde escribes las notas?',
    options: ['en el cuaderno', 'en la cama', 'en la ducha'],
    correctAnswer: 'en el cuaderno',
    hint: 'In the notebook - "cuaderno"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_039',
    emoji: '🎓',
    question: '¿Qué haces con las tareas?',
    options: ['las hago', 'las duermo', 'las como'],
    correctAnswer: 'las hago',
    hint: 'Do them - "hacer las tareas"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_040',
    emoji: '⏰',
    question: '¿Cuándo sales del trabajo?',
    options: ['por la tarde', 'por la mañana', 'al amanecer'],
    correctAnswer: 'por la tarde',
    hint: 'In the afternoon - "por la tarde"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },

  // Afternoon/Evening (41-60)
  {
    id: 'daily_041',
    emoji: '🏠',
    question: '¿Qué haces después del trabajo?',
    options: ['vuelvo a casa', 'me despierto', 'desayuno'],
    correctAnswer: 'vuelvo a casa',
    hint: 'Return home - "volver a casa"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_042',
    emoji: '👟',
    question: '¿Qué te quitas al llegar a casa?',
    options: ['los zapatos', 'el desayuno', 'la ducha'],
    correctAnswer: 'los zapatos',
    hint: 'Take off shoes - "quitarse los zapatos"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_043',
    emoji: '🛋️',
    question: '¿Dónde descansas en casa?',
    options: ['en el sofá', 'en la oficina', 'en el autobús'],
    correctAnswer: 'en el sofá',
    hint: 'On the sofa - "sofá"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_044',
    emoji: '📺',
    question: '¿Qué haces para relajarte?',
    options: ['veo la televisión', 'trabajo', 'estudio'],
    correctAnswer: 'veo la televisión',
    hint: 'Watch TV - "ver la televisión"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_045',
    emoji: '🍽️',
    question: '¿Qué haces por la tarde/noche?',
    options: ['ceno', 'desayuno', 'almuerzo'],
    correctAnswer: 'ceno',
    hint: 'Have dinner - "cenar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_046',
    emoji: '🍳',
    question: '¿Qué haces en la cocina?',
    options: ['cocino', 'duermo', 'me ducho'],
    correctAnswer: 'cocino',
    hint: 'Cook - "cocinar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_047',
    emoji: '🧹',
    question: '¿Qué haces para mantener limpia la casa?',
    options: ['limpio', 'duermo', 'como'],
    correctAnswer: 'limpio',
    hint: 'Clean - "limpiar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_048',
    emoji: '🍽️',
    question: '¿Qué haces después de comer?',
    options: ['lavo los platos', 'me despierto', 'desayuno'],
    correctAnswer: 'lavo los platos',
    hint: 'Wash the dishes - "lavar los platos"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_049',
    emoji: '👕',
    question: '¿Qué haces con la ropa sucia?',
    options: ['lavo la ropa', 'como la ropa', 'duermo la ropa'],
    correctAnswer: 'lavo la ropa',
    hint: 'Wash clothes - "lavar la ropa"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_050',
    emoji: '🧺',
    question: '¿Dónde pones la ropa limpia?',
    options: ['en el armario', 'en la cocina', 'en el baño'],
    correctAnswer: 'en el armario',
    hint: 'In the closet - "armario"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_051',
    emoji: '📱',
    question: '¿Qué usas para hablar con amigos?',
    options: ['el teléfono', 'la almohada', 'el plato'],
    correctAnswer: 'el teléfono',
    hint: 'The phone - "teléfono"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_052',
    emoji: '🎮',
    question: '¿Qué haces para divertirte?',
    options: ['juego', 'trabajo', 'limpio'],
    correctAnswer: 'juego',
    hint: 'Play - "jugar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_053',
    emoji: '🎵',
    question: '¿Qué escuchas en casa?',
    options: ['música', 'platos', 'zapatos'],
    correctAnswer: 'música',
    hint: 'Music - "música"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_054',
    emoji: '🏃',
    question: '¿Qué haces para hacer ejercicio?',
    options: ['corro', 'duermo', 'como'],
    correctAnswer: 'corro',
    hint: 'Run - "correr"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_055',
    emoji: '🚴',
    question: '¿Qué haces en bicicleta?',
    options: ['monto en bicicleta', 'duermo', 'cocino'],
    correctAnswer: 'monto en bicicleta',
    hint: 'Ride a bike - "montar en bicicleta"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_056',
    emoji: '🧘',
    question: '¿Qué haces para relajarte?',
    options: ['medito', 'trabajo', 'limpio'],
    correctAnswer: 'medito',
    hint: 'Meditate - "meditar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_057',
    emoji: '📖',
    question: '¿Qué haces antes de dormir?',
    options: ['leo un libro', 'desayuno', 'me despierto'],
    correctAnswer: 'leo un libro',
    hint: 'Read a book - "leer un libro"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_058',
    emoji: '👨‍👩‍👧',
    question: '¿Con quién pasas tiempo en casa?',
    options: ['con mi familia', 'con mi ordenador', 'con mi ducha'],
    correctAnswer: 'con mi familia',
    hint: 'With my family - "familia"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_059',
    emoji: '🎬',
    question: '¿Qué ves en la noche?',
    options: ['una película', 'un desayuno', 'un despertador'],
    correctAnswer: 'una película',
    hint: 'A movie - "película"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_060',
    emoji: '🍿',
    question: '¿Qué comes viendo una película?',
    options: ['palomitas', 'zapatos', 'llaves'],
    correctAnswer: 'palomitas',
    hint: 'Popcorn - "palomitas"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },

  // Night Routine (61-80)
  {
    id: 'daily_061',
    emoji: '🌙',
    question: '¿Cuándo te acuestas?',
    options: ['por la noche', 'por la mañana', 'al mediodía'],
    correctAnswer: 'por la noche',
    hint: 'At night - "por la noche"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_062',
    emoji: '😴',
    question: '¿Qué haces en la cama?',
    options: ['duermo', 'cocino', 'trabajo'],
    correctAnswer: 'duermo',
    hint: 'Sleep - "dormir"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_063',
    emoji: '🛌',
    question: '¿Qué haces cuando tienes sueño?',
    options: ['me acuesto', 'me levanto', 'me despierto'],
    correctAnswer: 'me acuesto',
    hint: 'Go to bed - "acostarse"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_064',
    emoji: '👔',
    question: '¿Qué haces con la ropa antes de dormir?',
    options: ['me desvisto', 'me visto', 'me ducho'],
    correctAnswer: 'me desvisto',
    hint: 'Get undressed - "desvestirse"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_065',
    emoji: '👔',
    question: '¿Qué te pones para dormir?',
    options: ['el pijama', 'el traje', 'los zapatos'],
    correctAnswer: 'el pijama',
    hint: 'Pajamas - "pijama"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_066',
    emoji: '🪥',
    question: '¿Qué haces antes de acostarte?',
    options: ['me lavo los dientes', 'desayuno', 'me despierto'],
    correctAnswer: 'me lavo los dientes',
    hint: 'Brush teeth - "lavarse/cepillarse los dientes"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_067',
    emoji: '💡',
    question: '¿Qué haces con las luces?',
    options: ['apago las luces', 'enciendo las luces', 'como las luces'],
    correctAnswer: 'apago las luces',
    hint: 'Turn off the lights - "apagar las luces"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_068',
    emoji: '🚪',
    question: '¿Qué haces con la puerta de noche?',
    options: ['cierro la puerta', 'abro la puerta', 'como la puerta'],
    correctAnswer: 'cierro la puerta',
    hint: 'Close the door - "cerrar la puerta"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_069',
    emoji: '🪟',
    question: '¿Qué cierras antes de dormir?',
    options: ['la ventana', 'el desayuno', 'el despertador'],
    correctAnswer: 'la ventana',
    hint: 'The window - "ventana"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_070',
    emoji: '🔔',
    question: '¿Qué pones para mañana?',
    options: ['la alarma', 'la cena', 'la ducha'],
    correctAnswer: 'la alarma',
    hint: 'The alarm - "alarma"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_071',
    emoji: '📵',
    question: '¿Qué debes apagar antes de dormir?',
    options: ['el móvil', 'la cama', 'la almohada'],
    correctAnswer: 'el móvil',
    hint: 'The mobile phone - "móvil"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_072',
    emoji: '🛏️',
    question: '¿Qué preparas para dormir bien?',
    options: ['la cama', 'el desayuno', 'el trabajo'],
    correctAnswer: 'la cama',
    hint: 'The bed - "cama"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_073',
    emoji: '🌡️',
    question: '¿Qué ajustas para dormir cómodo?',
    options: ['la temperatura', 'el desayuno', 'el autobús'],
    correctAnswer: 'la temperatura',
    hint: 'The temperature - "temperatura"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_074',
    emoji: '😌',
    question: '¿Cómo te sientes antes de dormir?',
    options: ['cansado', 'hambriento', 'despierto'],
    correctAnswer: 'cansado',
    hint: 'Tired - "cansado"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_075',
    emoji: '🙏',
    question: '¿Qué hacen algunas personas antes de dormir?',
    options: ['rezan', 'desayunan', 'trabajan'],
    correctAnswer: 'rezan',
    hint: 'Pray - "rezar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_076',
    emoji: '💭',
    question: '¿Qué haces cuando no puedes dormir?',
    options: ['pienso', 'como', 'trabajo'],
    correctAnswer: 'pienso',
    hint: 'Think - "pensar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_077',
    emoji: '🥛',
    question: '¿Qué bebes antes de dormir?',
    options: ['leche', 'café', 'cerveza'],
    correctAnswer: 'leche',
    hint: 'Milk - "leche", helps sleep',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_078',
    emoji: '🧸',
    question: '¿Con qué duermen los niños?',
    options: ['un peluche', 'un ordenador', 'un maletín'],
    correctAnswer: 'un peluche',
    hint: 'A stuffed animal - "peluche"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_079',
    emoji: '😴',
    question: '¿Cuántas horas duermes?',
    options: ['ocho horas', 'dos minutos', 'veinte horas'],
    correctAnswer: 'ocho horas',
    hint: 'Eight hours - healthy amount',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_080',
    emoji: '💤',
    question: '¿Qué te desea alguien antes de dormir?',
    options: ['buenas noches', 'buen día', 'buen viaje'],
    correctAnswer: 'buenas noches',
    hint: 'Good night - "buenas noches"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },

  // Weekend & Special Activities (81-100)
  {
    id: 'daily_081',
    emoji: '🛌',
    question: '¿Qué haces el fin de semana?',
    options: ['descanso', 'trabajo mucho', 'estudio más'],
    correctAnswer: 'descanso',
    hint: 'Rest - "descansar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_082',
    emoji: '🛍️',
    question: '¿Qué haces en el supermercado?',
    options: ['compro', 'duermo', 'trabajo'],
    correctAnswer: 'compro',
    hint: 'Buy - "comprar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_083',
    emoji: '🎉',
    question: '¿Qué haces con tus amigos?',
    options: ['salgo', 'duermo', 'trabajo'],
    correctAnswer: 'salgo',
    hint: 'Go out - "salir"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_084',
    emoji: '🍽️',
    question: '¿Qué haces en un restaurante?',
    options: ['como fuera', 'cocino', 'limpio'],
    correctAnswer: 'como fuera',
    hint: 'Eat out - "comer fuera"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_085',
    emoji: '🎬',
    question: '¿Qué haces en el cine?',
    options: ['veo una película', 'cocino', 'duermo'],
    correctAnswer: 'veo una película',
    hint: 'Watch a movie - "ver una película"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_086',
    emoji: '🏃',
    question: '¿Qué haces en el parque?',
    options: ['hago ejercicio', 'trabajo', 'cocino'],
    correctAnswer: 'hago ejercicio',
    hint: 'Exercise - "hacer ejercicio"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_087',
    emoji: '👨‍👩‍👧',
    question: '¿Qué haces con tu familia?',
    options: ['paso tiempo', 'trabajo', 'duermo'],
    correctAnswer: 'paso tiempo',
    hint: 'Spend time - "pasar tiempo"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_088',
    emoji: '📞',
    question: '¿Qué haces para hablar con alguien lejos?',
    options: ['llamo', 'duermo', 'como'],
    correctAnswer: 'llamo',
    hint: 'Call - "llamar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_089',
    emoji: '✉️',
    question: '¿Qué envías a tus amigos?',
    options: ['mensajes', 'almohadas', 'duchas'],
    correctAnswer: 'mensajes',
    hint: 'Messages - "mensajes"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_090',
    emoji: '🎨',
    question: '¿Qué haces como pasatiempo?',
    options: ['pinto', 'trabajo', 'limpio'],
    correctAnswer: 'pinto',
    hint: 'Paint - "pintar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_091',
    emoji: '🎸',
    question: '¿Qué haces con un instrumento?',
    options: ['toco música', 'como', 'duermo'],
    correctAnswer: 'toco música',
    hint: 'Play music - "tocar música"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_092',
    emoji: '📸',
    question: '¿Qué haces con momentos especiales?',
    options: ['tomo fotos', 'duermo', 'trabajo'],
    correctAnswer: 'tomo fotos',
    hint: 'Take photos - "tomar fotos"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_093',
    emoji: '🌳',
    question: '¿Qué haces en la naturaleza?',
    options: ['paseo', 'trabajo', 'cocino'],
    correctAnswer: 'paseo',
    hint: 'Walk/stroll - "pasear"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_094',
    emoji: '🐕',
    question: '¿Qué haces con tu perro?',
    options: ['paseo al perro', 'como al perro', 'duermo al perro'],
    correctAnswer: 'paseo al perro',
    hint: 'Walk the dog - "pasear al perro"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_095',
    emoji: '💆',
    question: '¿Qué haces para cuidarte?',
    options: ['me relajo', 'trabajo más', 'limpio más'],
    correctAnswer: 'me relajo',
    hint: 'Relax - "relajarse"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_096',
    emoji: '🧘',
    question: '¿Qué haces para tu bienestar?',
    options: ['cuido mi salud', 'trabajo sin parar', 'duermo todo el día'],
    correctAnswer: 'cuido mi salud',
    hint: 'Take care of health - "cuidar mi salud"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_097',
    emoji: '💪',
    question: '¿Qué haces en el gimnasio?',
    options: ['entreno', 'duermo', 'cocino'],
    correctAnswer: 'entreno',
    hint: 'Train/work out - "entrenar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_098',
    emoji: '🏊',
    question: '¿Qué haces en la piscina?',
    options: ['nado', 'duermo', 'trabajo'],
    correctAnswer: 'nado',
    hint: 'Swim - "nadar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_099',
    emoji: '🎯',
    question: '¿Qué planeas para el día?',
    options: ['organizo mis tareas', 'duermo todo el día', 'no hago nada'],
    correctAnswer: 'organizo mis tareas',
    hint: 'Organize tasks - "organizar las tareas"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_100',
    emoji: '✅',
    question: '¿Qué haces al final del día?',
    options: ['reflexiono', 'empiezo a trabajar', 'desayuno'],
    correctAnswer: 'reflexiono',
    hint: 'Reflect - "reflexionar"',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_101',
    emoji: '♻️',
    question: '¿Qué haces con el plástico y el papel usado?',
    options: ['reciclo', 'lo tiro todo junto', 'lo guardo'],
    correctAnswer: 'reciclo',
    hint: 'Recycle - "reciclar", separating waste for environmental care',
    points: 10,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_102',
    emoji: '🪚',
    question: '¿Con qué herramienta cortas la madera?',
    options: ['la sierra', 'el martillo', 'el destornillador'],
    correctAnswer: 'la sierra',
    hint: 'Saw - tool for cutting wood, "serrar" is to saw',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_103',
    emoji: '🧰',
    question: '¿Dónde guardas las herramientas?',
    options: ['en la caja de herramientas', 'en el armario', 'en la nevera'],
    correctAnswer: 'en la caja de herramientas',
    hint: 'Toolbox - "caja de herramientas", container for storing tools',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_104',
    emoji: '🔨',
    question: '¿Con qué herramienta clavas clavos en la madera?',
    options: ['el martillo', 'el destornillador', 'la sierra'],
    correctAnswer: 'el martillo',
    hint: 'Hammer - "martillo", tool for driving nails into wood',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_105',
    emoji: '🧽',
    question: '¿Con qué limpias los platos y las superficies?',
    options: ['la esponja', 'el trapo', 'la escoba'],
    correctAnswer: 'la esponja',
    hint: 'Sponge - "esponja", absorbent tool for cleaning dishes and surfaces',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
  {
    id: 'daily_106',
    emoji: '🪤',
    question: '¿Qué pones para atrapar ratones?',
    options: ['la trampa', 'la esponja', 'el martillo'],
    correctAnswer: 'la trampa',
    hint: 'Trap - "trampa", device to catch mice or pests',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
  },
];
