/**
 * DAILY ROUTINES Category Questions
 * Category: daily_routines
 */

export const dailyRoutinesQuestions = [
  // Morning Routine (1-20)
  {
    id: 'daily_001',
    emoji: '⏰',
    question: '¿Qué haces cuando suena el despertador?',
    translation: 'What do you do when the alarm rings?',
    options: ['me despierto', 'me duermo', 'desayuno'],
    correctAnswer: 'me despierto',
    hint: 'Wake up - reflexive verb "despertarse", starts your day',
    usageExample: 'Cuando suena el despertador, me despierto inmediatamente.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'daily_002',
    emoji: '🛏️',
    question: '¿Qué haces después de despertarte?',
    translation: 'What do you do after waking up?',
    options: ['me levanto', 'me acuesto', 'duermo'],
    correctAnswer: 'me levanto',
    hint: 'Get up - "levantarse" from "levantar" (to lift/raise)',
    usageExample: 'Después de despertarme, me levanto de la cama rápidamente.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_003',
    emoji: '🚿',
    question: '¿Qué haces en el baño por la mañana?',
    translation: 'What do you do in the bathroom in the morning?',
    options: ['me ducho', 'me peino', 'me visto'],
    correctAnswer: 'me ducho',
    hint: 'Shower - "ducharse", from "ducha" (shower)',
    usageExample: 'Por la mañana, me ducho con agua caliente para despertarme.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_004',
    emoji: '🪥',
    question: '¿Qué haces con el cepillo de dientes?',
    translation: 'What do you do with the toothbrush?',
    options: ['me cepillo los dientes', 'me peino', 'me lavo las manos'],
    correctAnswer: 'me cepillo los dientes',
    hint: 'Brush teeth - "cepillarse los dientes"',
    usageExample: 'Después de desayunar, me cepillo los dientes para mantenerlos limpios.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_005',
    emoji: '💇',
    question: '¿Qué haces con el peine?',
    translation: 'What do you do with the comb?',
    options: ['me peino', 'me afeito', 'me maquillo'],
    correctAnswer: 'me peino',
    hint: 'Comb hair - "peinarse" from "peine" (comb)',
    usageExample: 'Uso el peine y me peino frente al espejo.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_006',
    emoji: '👔',
    question: '¿Qué haces con la ropa?',
    translation: 'What do you do with the clothes?',
    options: ['me visto', 'me ducho', 'me siento'],
    correctAnswer: 'me visto',
    hint: 'Get dressed - "vestirse" from "vestir"',
    usageExample: 'Escojo mi ropa y me visto rápidamente para no llegar tarde.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_007',
    emoji: '🍳',
    question: '¿Qué haces antes de ir al trabajo?',
    translation: 'What do you do before going to work?',
    options: ['desayuno', 'almuerzo', 'ceno'],
    correctAnswer: 'desayuno',
    hint: 'Have breakfast - "desayunar"',
    usageExample: 'Antes de ir al trabajo, desayuno huevos y tostadas.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_008',
    emoji: '☕',
    question: '¿Qué bebes por la mañana?',
    translation: 'What do you drink in the morning?',
    options: ['café', 'cerveza', 'vino'],
    correctAnswer: 'café',
    hint: 'Coffee - common morning beverage',
    usageExample: 'Por la mañana, bebo café para tener energía.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'daily_009',
    emoji: '🪒',
    question: '¿Qué hace un hombre con la barba?',
    translation: 'What does a man do with his beard?',
    options: ['se afeita', 'se peina', 'se ducha'],
    correctAnswer: 'se afeita',
    hint: 'Shave - "afeitarse"',
    usageExample: 'Mi padre se afeita la barba cada mañana.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_010',
    emoji: '💄',
    question: '¿Qué hace alguien con el maquillaje?',
    translation: 'What does someone do with makeup?',
    options: ['se maquilla', 'se afeita', 'se ducha'],
    correctAnswer: 'se maquilla',
    hint: 'Put on makeup - "maquillarse"',
    usageExample: 'Mi hermana se maquilla antes de salir a trabajar.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'daily_011',
    emoji: '🧴',
    question: '¿Qué haces después de la ducha?',
    translation: 'What do you do after the shower?',
    options: ['me seco', 'me mojo', 'me duermo'],
    correctAnswer: 'me seco',
    hint: 'Dry off - "secarse"',
    usageExample: 'Después de la ducha, me seco con una toalla limpia.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_012',
    emoji: '👟',
    question: '¿Qué haces con los zapatos?',
    translation: 'What do you do with your shoes?',
    options: ['me los pongo', 'me los quito', 'los como'],
    correctAnswer: 'me los pongo',
    hint: 'Put on - "ponerse"',
    usageExample: 'Cada mañana me los pongo antes de salir de casa.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_013',
    emoji: '🪞',
    question: '¿Dónde te miras por la mañana?',
    translation: 'Where do you look at yourself in the morning?',
    options: ['en el espejo', 'en la cama', 'en la cocina'],
    correctAnswer: 'en el espejo',
    hint: 'Mirror - "espejo"',
    usageExample: 'Me miro en el espejo para ver cómo me queda la ropa.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_014',
    emoji: '🧼',
    question: '¿Qué haces con las manos antes de comer?',
    translation: 'What do you do with your hands before eating?',
    options: ['me lavo las manos', 'me ducho', 'me acuesto'],
    correctAnswer: 'me lavo las manos',
    hint: 'Wash hands - "lavarse las manos"',
    usageExample: 'Antes de comer, siempre me lavo las manos con jabón.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_015',
    emoji: '🎒',
    question: '¿Qué preparas antes de salir?',
    translation: 'What do you prepare before leaving?',
    options: ['la mochila', 'la cama', 'el desayuno'],
    correctAnswer: 'la mochila',
    hint: 'Backpack - "mochila"',
    usageExample: 'Preparo la mochila con mis libros antes de ir a la escuela.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_016',
    emoji: '🔑',
    question: '¿Qué necesitas para salir de casa?',
    translation: 'What do you need to leave the house?',
    options: ['las llaves', 'la almohada', 'la ducha'],
    correctAnswer: 'las llaves',
    hint: 'Keys - "llaves"',
    usageExample: 'Necesito las llaves para abrir la puerta de casa.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'daily_017',
    emoji: '🚪',
    question: '¿Qué haces cuando sales de casa?',
    translation: 'What do you do when you leave the house?',
    options: ['cierro la puerta', 'abro la ventana', 'enciendo la luz'],
    correctAnswer: 'cierro la puerta',
    hint: 'Close the door - "cerrar la puerta"',
    usageExample: 'Cuando salgo de casa, cierro la puerta con llave.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_018',
    emoji: '📱',
    question: '¿Qué revisas por la mañana?',
    translation: 'What do you check in the morning?',
    options: ['el móvil', 'la almohada', 'el armario'],
    correctAnswer: 'el móvil',
    hint: 'Mobile phone - "móvil"',
    usageExample: 'Por la mañana reviso el móvil para ver los mensajes.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'daily_019',
    emoji: '🌅',
    question: '¿Cuándo te despiertas?',
    translation: 'When do you wake up?',
    options: ['por la mañana', 'por la noche', 'al mediodía'],
    correctAnswer: 'por la mañana',
    hint: 'In the morning - "por la mañana"',
    usageExample: 'Normalmente me despierto por la mañana a las siete.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_020',
    emoji: '⏱️',
    question: '¿Qué programas para despertarte?',
    translation: 'What do you set to wake up?',
    options: ['el despertador', 'el televisor', 'el ordenador'],
    correctAnswer: 'el despertador',
    hint: 'Alarm clock - "despertador"',
    usageExample: 'Programo el despertador para las seis de la mañana.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'anxious',
  },

  // Work/School Day (21-40)
  {
    id: 'daily_021',
    emoji: '🚗',
    question: '¿Cómo vas al trabajo?',
    translation: 'How do you go to work?',
    options: ['en coche', 'en cama', 'en ducha'],
    correctAnswer: 'en coche',
    hint: 'By car - "en coche"',
    usageExample: 'Voy al trabajo en coche porque vivo lejos.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_025',
    emoji: '💼',
    question: '¿Qué llevas al trabajo?',
    translation: 'What do you take to work?',
    options: ['el maletín', 'la almohada', 'la ducha'],
    correctAnswer: 'el maletín',
    hint: 'Briefcase - "maletín"',
    usageExample: 'Llevo el maletín con mis documentos importantes.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_026',
    emoji: '💻',
    question: '¿Qué usas para trabajar?',
    translation: 'What do you use to work?',
    options: ['el ordenador', 'la cama', 'la ducha'],
    correctAnswer: 'el ordenador',
    hint: 'Computer - "ordenador"',
    usageExample: 'Uso el ordenador para escribir informes y enviar correos.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_027',
    emoji: '📧',
    question: '¿Qué revisas en el trabajo?',
    translation: 'What do you check at work?',
    options: ['los correos', 'las almohadas', 'las duchas'],
    correctAnswer: 'los correos',
    hint: 'Emails - "correos"',
    usageExample: 'Cada mañana reviso los correos para ver los mensajes nuevos.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'daily_029',
    emoji: '🤝',
    question: '¿Qué tienes con tus colegas?',
    translation: 'What do you have with your colleagues?',
    options: ['reuniones', 'duchas', 'siestas'],
    correctAnswer: 'reuniones',
    hint: 'Meetings - "reuniones"',
    usageExample: 'Tengo reuniones con mis colegas todos los lunes.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_031',
    emoji: '☕',
    question: '¿Qué tomas durante el trabajo?',
    translation: 'What do you have during work?',
    options: ['un café', 'una siesta', 'una ducha'],
    correctAnswer: 'un café',
    hint: 'A coffee - common work break',
    usageExample: 'Durante el descanso, tomo un café para recargar energía.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_032',
    emoji: '🍴',
    question: '¿Qué haces al mediodía?',
    translation: 'What do you do at noon?',
    options: ['almuerzo', 'desayuno', 'ceno'],
    correctAnswer: 'almuerzo',
    hint: 'Have lunch - "almorzar"',
    usageExample: 'Al mediodía, almuerzo con mis compañeros de trabajo.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_034',
    emoji: '📚',
    question: '¿Qué haces en la escuela?',
    translation: 'What do you do at school?',
    options: ['estudio', 'duermo', 'cocino'],
    correctAnswer: 'estudio',
    hint: 'Study - "estudiar"',
    usageExample: 'En la escuela, estudio matemáticas y ciencias.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_035',
    emoji: '📖',
    question: '¿Qué haces con los libros?',
    translation: 'What do you do with books?',
    options: ['leo', 'como', 'duermo'],
    correctAnswer: 'leo',
    hint: 'Read - "leer"',
    usageExample: 'Cuando tengo tiempo libre, leo libros de aventuras.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_036',
    emoji: '✏️',
    question: '¿Con qué escribes?',
    translation: 'What do you write with?',
    options: ['con un lápiz', 'con una cama', 'con una ducha'],
    correctAnswer: 'con un lápiz',
    hint: 'With a pencil - "lápiz"',
    usageExample: 'Escribo mis apuntes con un lápiz en clase.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_037',
    emoji: '👨‍🏫',
    question: '¿A quién escuchas en clase?',
    translation: 'Who do you listen to in class?',
    options: ['al profesor', 'a la cama', 'a la ducha'],
    correctAnswer: 'al profesor',
    hint: 'To the teacher - "profesor"',
    usageExample: 'En clase, escucho al profesor con atención.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_038',
    emoji: '📓',
    question: '¿Dónde escribes las notas?',
    translation: 'Where do you write notes?',
    options: ['en el cuaderno', 'en la cama', 'en la ducha'],
    correctAnswer: 'en el cuaderno',
    hint: 'In the notebook - "cuaderno"',
    usageExample: 'Escribo las notas importantes en el cuaderno.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_039',
    emoji: '🎓',
    question: '¿Qué haces con las tareas?',
    translation: 'What do you do with homework?',
    options: ['las hago', 'las duermo', 'las como'],
    correctAnswer: 'las hago',
    hint: 'Do them - "hacer las tareas"',
    usageExample: 'Después de la escuela, las hago en mi habitación.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'daily_040',
    emoji: '⏰',
    question: '¿Cuándo sales del trabajo?',
    translation: 'When do you leave work?',
    options: ['por la tarde', 'por la mañana', 'al amanecer'],
    correctAnswer: 'por la tarde',
    hint: 'In the afternoon - "por la tarde"',
    usageExample: 'Salgo del trabajo por la tarde a las cinco.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },

  // Afternoon/Evening (41-60)
  {
    id: 'daily_041',
    emoji: '🏠',
    question: '¿Qué haces después del trabajo?',
    translation: 'What do you do after work?',
    options: ['vuelvo a casa', 'me despierto', 'desayuno'],
    correctAnswer: 'vuelvo a casa',
    hint: 'Return home - "volver a casa"',
    usageExample: 'Después del trabajo, vuelvo a casa para descansar.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_042',
    emoji: '👟',
    question: '¿Qué te quitas al llegar a casa?',
    translation: 'What do you take off when you arrive home?',
    options: ['los zapatos', 'el desayuno', 'la ducha'],
    correctAnswer: 'los zapatos',
    hint: 'Take off shoes - "quitarse los zapatos"',
    usageExample: 'Cuando llego a casa, me quito los zapatos y me pongo pantuflas.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_043',
    emoji: '🛋️',
    question: '¿Dónde descansas en casa?',
    translation: 'Where do you rest at home?',
    options: ['en el sofá', 'en la oficina', 'en el autobús'],
    correctAnswer: 'en el sofá',
    hint: 'On the sofa - "sofá"',
    usageExample: 'Me gusta descansar en el sofá después de un día largo.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_044',
    emoji: '📺',
    question: '¿Qué haces para relajarte?',
    translation: 'What do you do to relax?',
    options: ['veo la televisión', 'trabajo', 'estudio'],
    correctAnswer: 'veo la televisión',
    hint: 'Watch TV - "ver la televisión"',
    usageExample: 'Por las noches, veo la televisión con mi familia.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_045',
    emoji: '🍽️',
    question: '¿Qué haces por la tarde/noche?',
    translation: 'What do you do in the afternoon/evening?',
    options: ['ceno', 'desayuno', 'almuerzo'],
    correctAnswer: 'ceno',
    hint: 'Have dinner - "cenar"',
    usageExample: 'Por la noche, ceno con mi familia a las ocho.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_046',
    emoji: '🍳',
    question: '¿Qué haces en la cocina?',
    translation: 'What do you do in the kitchen?',
    options: ['cocino', 'duermo', 'me ducho'],
    correctAnswer: 'cocino',
    hint: 'Cook - "cocinar"',
    usageExample: 'Cada noche cocino la cena para toda la familia.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_047',
    emoji: '🧹',
    question: '¿Qué haces para mantener limpia la casa?',
    translation: 'What do you do to keep the house clean?',
    options: ['limpio', 'duermo', 'como'],
    correctAnswer: 'limpio',
    hint: 'Clean - "limpiar"',
    usageExample: 'Los fines de semana, limpio la casa con cuidado.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_048',
    emoji: '🍽️',
    question: '¿Qué haces después de comer?',
    translation: 'What do you do after eating?',
    options: ['lavo los platos', 'me despierto', 'desayuno'],
    correctAnswer: 'lavo los platos',
    hint: 'Wash the dishes - "lavar los platos"',
    usageExample: 'Después de cenar, lavo los platos y los seco.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_049',
    emoji: '👕',
    question: '¿Qué haces con la ropa sucia?',
    translation: 'What do you do with dirty clothes?',
    options: ['lavo la ropa', 'como la ropa', 'duermo la ropa'],
    correctAnswer: 'lavo la ropa',
    hint: 'Wash clothes - "lavar la ropa"',
    usageExample: 'Cada semana lavo la ropa sucia en la lavadora.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_050',
    emoji: '🧺',
    question: '¿Dónde pones la ropa limpia?',
    translation: 'Where do you put clean clothes?',
    options: ['en el armario', 'en la cocina', 'en el baño'],
    correctAnswer: 'en el armario',
    hint: 'In the closet - "armario"',
    usageExample: 'Después de planchar, guardo la ropa limpia en el armario.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_051',
    emoji: '📱',
    question: '¿Qué usas para hablar con amigos?',
    translation: 'What do you use to talk with friends?',
    options: ['el teléfono', 'la almohada', 'el plato'],
    correctAnswer: 'el teléfono',
    hint: 'The phone - "teléfono"',
    usageExample: 'Uso el teléfono para llamar a mis amigos por la noche.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'daily_052',
    emoji: '🎮',
    question: '¿Qué haces para divertirte?',
    translation: 'What do you do to have fun?',
    options: ['juego', 'trabajo', 'limpio'],
    correctAnswer: 'juego',
    hint: 'Play - "jugar"',
    usageExample: 'Por las tardes, juego videojuegos para divertirme.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'daily_053',
    emoji: '🎵',
    question: '¿Qué escuchas en casa?',
    translation: 'What do you listen to at home?',
    options: ['música', 'platos', 'zapatos'],
    correctAnswer: 'música',
    hint: 'Music - "música"',
    usageExample: 'Me gusta escuchar música mientras cocino.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'daily_054',
    emoji: '🏃',
    question: '¿Qué haces para hacer ejercicio?',
    translation: 'What do you do to exercise?',
    options: ['corro', 'duermo', 'como'],
    correctAnswer: 'corro',
    hint: 'Run - "correr"',
    usageExample: 'Cada mañana corro en el parque para mantenerme en forma.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_055',
    emoji: '🚴',
    question: '¿Qué haces en bicicleta?',
    translation: 'What do you do on a bicycle?',
    options: ['monto en bicicleta', 'duermo', 'cocino'],
    correctAnswer: 'monto en bicicleta',
    hint: 'Ride a bike - "montar en bicicleta"',
    usageExample: 'Los domingos monto en bicicleta por el parque.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_056',
    emoji: '🧘',
    question: '¿Qué haces para relajarte?',
    translation: 'What do you do to relax?',
    options: ['medito', 'trabajo', 'limpio'],
    correctAnswer: 'medito',
    hint: 'Meditate - "meditar"',
    usageExample: 'Por las noches medito para calmar mi mente.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_057',
    emoji: '📖',
    question: '¿Qué haces antes de dormir?',
    translation: 'What do you do before sleeping?',
    options: ['leo un libro', 'desayuno', 'me despierto'],
    correctAnswer: 'leo un libro',
    hint: 'Read a book - "leer un libro"',
    usageExample: 'Antes de dormir, leo un libro en la cama.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_058',
    emoji: '👨‍👩‍👧',
    question: '¿Con quién pasas tiempo en casa?',
    translation: 'Who do you spend time with at home?',
    options: ['con mi familia', 'con mi ordenador', 'con mi ducha'],
    correctAnswer: 'con mi familia',
    hint: 'With my family - "familia"',
    usageExample: 'Por las noches paso tiempo con mi familia viendo televisión.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'daily_059',
    emoji: '🎬',
    question: '¿Qué ves en la noche?',
    translation: 'What do you watch at night?',
    options: ['una película', 'un desayuno', 'un despertador'],
    correctAnswer: 'una película',
    hint: 'A movie - "película"',
    usageExample: 'Los viernes por la noche veo una película con mis amigos.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'daily_060',
    emoji: '🍿',
    question: '¿Qué comes viendo una película?',
    translation: 'What do you eat while watching a movie?',
    options: ['palomitas', 'zapatos', 'llaves'],
    correctAnswer: 'palomitas',
    hint: 'Popcorn - "palomitas"',
    usageExample: 'Cuando veo una película, siempre como palomitas.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },

  // Night Routine (61-80)
  {
    id: 'daily_061',
    emoji: '🌙',
    question: '¿Cuándo te acuestas?',
    translation: 'When do you go to bed?',
    options: ['por la noche', 'por la mañana', 'al mediodía'],
    correctAnswer: 'por la noche',
    hint: 'At night - "por la noche"',
    usageExample: 'Normalmente me acuesto por la noche a las diez.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_062',
    emoji: '😴',
    question: '¿Qué haces en la cama?',
    translation: 'What do you do in bed?',
    options: ['duermo', 'cocino', 'trabajo'],
    correctAnswer: 'duermo',
    hint: 'Sleep - "dormir"',
    usageExample: 'Cada noche duermo ocho horas para descansar bien.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_063',
    emoji: '🛌',
    question: '¿Qué haces cuando tienes sueño?',
    translation: 'What do you do when you\'re sleepy?',
    options: ['me acuesto', 'me levanto', 'me despierto'],
    correctAnswer: 'me acuesto',
    hint: 'Go to bed - "acostarse"',
    usageExample: 'Cuando tengo sueño, me acuesto temprano.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_064',
    emoji: '👔',
    question: '¿Qué haces con la ropa antes de dormir?',
    translation: 'What do you do with clothes before sleeping?',
    options: ['me desvisto', 'me visto', 'me ducho'],
    correctAnswer: 'me desvisto',
    hint: 'Get undressed - "desvestirse"',
    usageExample: 'Antes de ponerme el pijama, me desvisto en mi habitación.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_065',
    emoji: '👔',
    question: '¿Qué te pones para dormir?',
    translation: 'What do you put on to sleep?',
    options: ['el pijama', 'el traje', 'los zapatos'],
    correctAnswer: 'el pijama',
    hint: 'Pajamas - "pijama"',
    usageExample: 'Cada noche me pongo el pijama antes de acostarme.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_066',
    emoji: '🪥',
    question: '¿Qué haces antes de acostarte?',
    translation: 'What do you do before going to bed?',
    options: ['me lavo los dientes', 'desayuno', 'me despierto'],
    correctAnswer: 'me lavo los dientes',
    hint: 'Brush teeth - "lavarse/cepillarse los dientes"',
    usageExample: 'Siempre me lavo los dientes antes de acostarme.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_067',
    emoji: '💡',
    question: '¿Qué haces con las luces?',
    translation: 'What do you do with the lights?',
    options: ['apago las luces', 'enciendo las luces', 'como las luces'],
    correctAnswer: 'apago las luces',
    hint: 'Turn off the lights - "apagar las luces"',
    usageExample: 'Antes de dormir, apago las luces de toda la casa.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_068',
    emoji: '🚪',
    question: '¿Qué haces con la puerta de noche?',
    translation: 'What do you do with the door at night?',
    options: ['cierro la puerta', 'abro la puerta', 'como la puerta'],
    correctAnswer: 'cierro la puerta',
    hint: 'Close the door - "cerrar la puerta"',
    usageExample: 'Por seguridad, cierro la puerta con llave cada noche.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_069',
    emoji: '🪟',
    question: '¿Qué cierras antes de dormir?',
    translation: 'What do you close before sleeping?',
    options: ['la ventana', 'el desayuno', 'el despertador'],
    correctAnswer: 'la ventana',
    hint: 'The window - "ventana"',
    usageExample: 'En invierno cierro la ventana para no pasar frío.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_070',
    emoji: '🔔',
    question: '¿Qué pones para mañana?',
    translation: 'What do you set for tomorrow?',
    options: ['la alarma', 'la cena', 'la ducha'],
    correctAnswer: 'la alarma',
    hint: 'The alarm - "alarma"',
    usageExample: 'Cada noche pongo la alarma para despertarme temprano.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_071',
    emoji: '📵',
    question: '¿Qué debes apagar antes de dormir?',
    translation: 'What should you turn off before sleeping?',
    options: ['el móvil', 'la cama', 'la almohada'],
    correctAnswer: 'el móvil',
    hint: 'The mobile phone - "móvil"',
    usageExample: 'Apago el móvil antes de dormir para descansar mejor.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_072',
    emoji: '🛏️',
    question: '¿Qué preparas para dormir bien?',
    translation: 'What do you prepare to sleep well?',
    options: ['la cama', 'el desayuno', 'el trabajo'],
    correctAnswer: 'la cama',
    hint: 'The bed - "cama"',
    usageExample: 'Preparo la cama con sábanas limpias cada semana.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_073',
    emoji: '🌡️',
    question: '¿Qué ajustas para dormir cómodo?',
    translation: 'What do you adjust to sleep comfortably?',
    options: ['la temperatura', 'el desayuno', 'el autobús'],
    correctAnswer: 'la temperatura',
    hint: 'The temperature - "temperatura"',
    usageExample: 'Ajusto la temperatura del aire acondicionado antes de dormir.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_074',
    emoji: '😌',
    question: '¿Cómo te sientes antes de dormir?',
    translation: 'How do you feel before sleeping?',
    options: ['cansado', 'hambriento', 'despierto'],
    correctAnswer: 'cansado',
    hint: 'Tired - "cansado"',
    usageExample: 'Después de un día largo, me siento muy cansado.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_075',
    emoji: '🙏',
    question: '¿Qué hacen algunas personas antes de dormir?',
    translation: 'What do some people do before sleeping?',
    options: ['rezan', 'desayunan', 'trabajan'],
    correctAnswer: 'rezan',
    hint: 'Pray - "rezar"',
    usageExample: 'Algunas personas rezan antes de dormir cada noche.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_076',
    emoji: '💭',
    question: '¿Qué haces cuando no puedes dormir?',
    translation: 'What do you do when you can\'t sleep?',
    options: ['pienso', 'como', 'trabajo'],
    correctAnswer: 'pienso',
    hint: 'Think - "pensar"',
    usageExample: 'Cuando no puedo dormir, pienso en cosas tranquilas.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'daily_077',
    emoji: '🥛',
    question: '¿Qué bebes antes de dormir?',
    translation: 'What do you drink before sleeping?',
    options: ['leche', 'café', 'cerveza'],
    correctAnswer: 'leche',
    hint: 'Milk - "leche", helps sleep',
    usageExample: 'Tomo un vaso de leche tibia antes de dormir.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_078',
    emoji: '🧸',
    question: '¿Con qué duermen los niños?',
    translation: 'What do children sleep with?',
    options: ['un peluche', 'un ordenador', 'un maletín'],
    correctAnswer: 'un peluche',
    hint: 'A stuffed animal - "peluche"',
    usageExample: 'Mi hija duerme con un peluche de osito.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_079',
    emoji: '😴',
    question: '¿Cuántas horas duermes?',
    translation: 'How many hours do you sleep?',
    options: ['ocho horas', 'dos minutos', 'veinte horas'],
    correctAnswer: 'ocho horas',
    hint: 'Eight hours - healthy amount',
    usageExample: 'Intento dormir ocho horas cada noche para estar descansado.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_080',
    emoji: '💤',
    question: '¿Qué te desea alguien antes de dormir?',
    translation: 'What does someone wish you before sleeping?',
    options: ['buenas noches', 'buen día', 'buen viaje'],
    correctAnswer: 'buenas noches',
    hint: 'Good night - "buenas noches"',
    usageExample: 'Antes de dormir, mi madre me dice buenas noches.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },

  // Weekend & Special Activities (81-100)
  {
    id: 'daily_081',
    emoji: '🛌',
    question: '¿Qué haces el fin de semana?',
    translation: 'What do you do on the weekend?',
    options: ['descanso', 'trabajo mucho', 'estudio más'],
    correctAnswer: 'descanso',
    hint: 'Rest - "descansar"',
    usageExample: 'El fin de semana descanso y recupero energía.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_082',
    emoji: '🛍️',
    question: '¿Qué haces en el supermercado?',
    translation: 'What do you do in the supermarket?',
    options: ['compro', 'duermo', 'trabajo'],
    correctAnswer: 'compro',
    hint: 'Buy - "comprar"',
    usageExample: 'En el supermercado compro frutas y verduras frescas.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_083',
    emoji: '🎉',
    question: '¿Qué haces con tus amigos?',
    translation: 'What do you do with your friends?',
    options: ['salgo', 'duermo', 'trabajo'],
    correctAnswer: 'salgo',
    hint: 'Go out - "salir"',
    usageExample: 'Los sábados salgo con mis amigos a divertirnos.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'daily_084',
    emoji: '🍽️',
    question: '¿Qué haces en un restaurante?',
    translation: 'What do you do in a restaurant?',
    options: ['como fuera', 'cocino', 'limpio'],
    correctAnswer: 'como fuera',
    hint: 'Eat out - "comer fuera"',
    usageExample: 'A veces como fuera con mi familia en un restaurante.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_085',
    emoji: '🎬',
    question: '¿Qué haces en el cine?',
    translation: 'What do you do at the cinema?',
    options: ['veo una película', 'cocino', 'duermo'],
    correctAnswer: 'veo una película',
    hint: 'Watch a movie - "ver una película"',
    usageExample: 'En el cine veo una película de acción.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'daily_086',
    emoji: '🏃',
    question: '¿Qué haces en el parque?',
    translation: 'What do you do in the park?',
    options: ['hago ejercicio', 'trabajo', 'cocino'],
    correctAnswer: 'hago ejercicio',
    hint: 'Exercise - "hacer ejercicio"',
    usageExample: 'Por las mañanas hago ejercicio en el parque cerca de mi casa.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_087',
    emoji: '👨‍👩‍👧',
    question: '¿Qué haces con tu familia?',
    translation: 'What do you do with your family?',
    options: ['paso tiempo', 'trabajo', 'duermo'],
    correctAnswer: 'paso tiempo',
    hint: 'Spend time - "pasar tiempo"',
    usageExample: 'Los domingos paso tiempo con mi familia en casa.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'daily_088',
    emoji: '📞',
    question: '¿Qué haces para hablar con alguien lejos?',
    translation: 'What do you do to talk with someone far away?',
    options: ['llamo', 'duermo', 'como'],
    correctAnswer: 'llamo',
    hint: 'Call - "llamar"',
    usageExample: 'Cada semana llamo a mis abuelos por teléfono.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_089',
    emoji: '✉️',
    question: '¿Qué envías a tus amigos?',
    translation: 'What do you send to your friends?',
    options: ['mensajes', 'almohadas', 'duchas'],
    correctAnswer: 'mensajes',
    hint: 'Messages - "mensajes"',
    usageExample: 'Envío mensajes a mis amigos todos los días.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'daily_090',
    emoji: '🎨',
    question: '¿Qué haces como pasatiempo?',
    translation: 'What do you do as a hobby?',
    options: ['pinto', 'trabajo', 'limpio'],
    correctAnswer: 'pinto',
    hint: 'Paint - "pintar"',
    usageExample: 'Como pasatiempo, pinto cuadros de paisajes.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_091',
    emoji: '🎸',
    question: '¿Qué haces con un instrumento?',
    translation: 'What do you do with an instrument?',
    options: ['toco música', 'como', 'duermo'],
    correctAnswer: 'toco música',
    hint: 'Play music - "tocar música"',
    usageExample: 'Por las tardes toco música con mi guitarra.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_092',
    emoji: '📸',
    question: '¿Qué haces con momentos especiales?',
    translation: 'What do you do with special moments?',
    options: ['tomo fotos', 'duermo', 'trabajo'],
    correctAnswer: 'tomo fotos',
    hint: 'Take photos - "tomar fotos"',
    usageExample: 'En las vacaciones tomo fotos de los lugares que visito.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'daily_093',
    emoji: '🌳',
    question: '¿Qué haces en la naturaleza?',
    translation: 'What do you do in nature?',
    options: ['paseo', 'trabajo', 'cocino'],
    correctAnswer: 'paseo',
    hint: 'Walk/stroll - "pasear"',
    usageExample: 'Me gusta ir a la montaña y paseo entre los árboles.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_094',
    emoji: '🐕',
    question: '¿Qué haces con tu perro?',
    translation: 'What do you do with your dog?',
    options: ['paseo al perro', 'como al perro', 'duermo al perro'],
    correctAnswer: 'paseo al perro',
    hint: 'Walk the dog - "pasear al perro"',
    usageExample: 'Cada mañana y noche paseo al perro por el vecindario.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_095',
    emoji: '💆',
    question: '¿Qué haces para cuidarte?',
    translation: 'What do you do to take care of yourself?',
    options: ['me relajo', 'trabajo más', 'limpio más'],
    correctAnswer: 'me relajo',
    hint: 'Relax - "relajarse"',
    usageExample: 'Después de trabajar, me relajo leyendo un libro.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_096',
    emoji: '🧘',
    question: '¿Qué haces para tu bienestar?',
    translation: 'What do you do for your wellbeing?',
    options: ['cuido mi salud', 'trabajo sin parar', 'duermo todo el día'],
    correctAnswer: 'cuido mi salud',
    hint: 'Take care of health - "cuidar mi salud"',
    usageExample: 'Para mi bienestar, cuido mi salud comiendo bien.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_097',
    emoji: '💪',
    question: '¿Qué haces en el gimnasio?',
    translation: 'What do you do at the gym?',
    options: ['entreno', 'duermo', 'cocino'],
    correctAnswer: 'entreno',
    hint: 'Train/work out - "entrenar"',
    usageExample: 'Tres veces a la semana entreno en el gimnasio.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_098',
    emoji: '🏊',
    question: '¿Qué haces en la piscina?',
    translation: 'What do you do in the pool?',
    options: ['nado', 'duermo', 'trabajo'],
    correctAnswer: 'nado',
    hint: 'Swim - "nadar"',
    usageExample: 'En verano nado en la piscina para refrescarme.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_099',
    emoji: '🎯',
    question: '¿Qué planeas para el día?',
    translation: 'What do you plan for the day?',
    options: ['organizo mis tareas', 'duermo todo el día', 'no hago nada'],
    correctAnswer: 'organizo mis tareas',
    hint: 'Organize tasks - "organizar las tareas"',
    usageExample: 'Cada mañana organizo mis tareas para ser más productivo.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_100',
    emoji: '✅',
    question: '¿Qué haces al final del día?',
    translation: 'What do you do at the end of the day?',
    options: ['reflexiono', 'empiezo a trabajar', 'desayuno'],
    correctAnswer: 'reflexiono',
    hint: 'Reflect - "reflexionar"',
    usageExample: 'Al final del día, reflexiono sobre lo que logré.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_101',
    emoji: '♻️',
    question: '¿Qué haces con el plástico y el papel usado?',
    translation: 'What do you do with used plastic and paper?',
    options: ['reciclo', 'lo tiro todo junto', 'lo guardo'],
    correctAnswer: 'reciclo',
    hint: 'Recycle - "reciclar", separating waste for environmental care',
    usageExample: 'Para cuidar el medio ambiente, reciclo el plástico y el papel.',
    points: 10,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_102',
    emoji: '🪚',
    question: '¿Con qué herramienta cortas la madera?',
    translation: 'What tool do you use to cut wood?',
    options: ['la sierra', 'el martillo', 'el destornillador'],
    correctAnswer: 'la sierra',
    hint: 'Saw - tool for cutting wood, "serrar" is to saw',
    usageExample: 'Para cortar la madera, uso la sierra con cuidado.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_103',
    emoji: '🧰',
    question: '¿Dónde guardas las herramientas?',
    translation: 'Where do you store the tools?',
    options: ['en la caja de herramientas', 'en el armario', 'en la nevera'],
    correctAnswer: 'en la caja de herramientas',
    hint: 'Toolbox - "caja de herramientas", container for storing tools',
    usageExample: 'Guardo todas mis herramientas en la caja de herramientas del garaje.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_104',
    emoji: '🔨',
    question: '¿Con qué herramienta clavas clavos en la madera?',
    translation: 'What tool do you use to drive nails into wood?',
    options: ['el martillo', 'el destornillador', 'la sierra'],
    correctAnswer: 'el martillo',
    hint: 'Hammer - "martillo", tool for driving nails into wood',
    usageExample: 'Para colgar el cuadro, uso el martillo y un clavo.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_105',
    emoji: '🧽',
    question: '¿Con qué limpias los platos y las superficies?',
    translation: 'What do you clean dishes and surfaces with?',
    options: ['la esponja', 'el trapo', 'la escoba'],
    correctAnswer: 'la esponja',
    hint: 'Sponge - "esponja", absorbent tool for cleaning dishes and surfaces',
    usageExample: 'Uso la esponja con jabón para limpiar los platos.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_106',
    emoji: '🪤',
    question: '¿Qué pones para atrapar ratones?',
    translation: 'What do you set to catch mice?',
    options: ['la trampa', 'la esponja', 'el martillo'],
    correctAnswer: 'la trampa',
    hint: 'Trap - "trampa", device to catch mice or pests',
    usageExample: 'Puse la trampa en la cocina para atrapar al ratón.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'daily_107',
    emoji: '📬',
    question: '¿Qué recibes en el buzón de tu casa?',
    translation: 'What do you receive in your home mailbox?',
    options: ['el correo', 'la comida', 'el agua'],
    correctAnswer: 'el correo',
    hint: 'Mail - "correo", letters and packages delivered to your mailbox',
    usageExample: 'Cada día reviso el buzón y recojo el correo.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_108',
    emoji: 'back-scratcher.png',
    question: '¿Qué usas cuando no puedes alcanzar tu espalda para rascarte?',
    translation: 'What do you use when you can\'t reach your back to scratch it?',
    options: ['el rascador de espalda', 'el peine', 'la esponja'],
    correctAnswer: 'el rascador de espalda',
    hint: 'Back scratcher - "rascador de espalda", useful tool to scratch hard-to-reach spots',
    usageExample: 'Cuando me pica la espalda, uso el rascador de espalda.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_109',
    emoji: 'shoe-rack.png',
    question: '¿Dónde organizas y guardas tus zapatos?',
    translation: 'Where do you organize and store your shoes?',
    options: ['el zapatero', 'el armario', 'la mesa'],
    correctAnswer: 'el zapatero',
    hint: 'Shoe rack - "zapatero", furniture for organizing and storing shoes',
    usageExample: 'Organizo todos mis zapatos en el zapatero de la entrada.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_110',
    emoji: 'baby-mobile.png',
    question: '¿Qué cuelgas sobre la cuna del bebé para entretenerlo?',
    translation: 'What do you hang over the baby\'s crib to entertain them?',
    options: ['el móvil de cuna', 'la lámpara', 'el juguete'],
    correctAnswer: 'el móvil de cuna',
    hint: 'Baby mobile - "móvil de cuna", decorative toy that hangs above a crib',
    usageExample: 'Colgué el móvil de cuna sobre la cama del bebé.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'daily_111',
    emoji: 'bathroom.png',
    question: '¿Dónde te duchas y te lavas las manos?',
    translation: 'Where do you shower and wash your hands?',
    options: ['el baño', 'la cocina', 'el dormitorio'],
    correctAnswer: 'el baño',
    hint: 'Bathroom - "baño", room for personal hygiene activities',
    usageExample: 'Me ducho y me lavo las manos en el baño.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_112',
    emoji: 'bed-tray.png',
    question: '¿Qué usas para desayunar en la cama?',
    translation: 'What do you use to have breakfast in bed?',
    options: ['la bandeja de cama', 'el plato', 'la mesa'],
    correctAnswer: 'la bandeja de cama',
    hint: 'Bed tray - "bandeja de cama", portable tray for eating in bed',
    usageExample: 'Uso la bandeja de cama para desayunar los domingos.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_113',
    emoji: 'bedside-lamp.png',
    question: '¿Qué enciendes en la mesita de noche para leer antes de dormir?',
    translation: 'What do you turn on at the nightstand to read before sleeping?',
    options: ['la lámpara de noche', 'la televisión', 'el reloj'],
    correctAnswer: 'la lámpara de noche',
    hint: 'Bedside lamp - "lámpara de noche", small lamp for reading in bed',
    usageExample: 'Enciendo la lámpara de noche para leer antes de dormir.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_114',
    emoji: 'bucket.png',
    question: '¿Qué usas para llevar agua cuando limpias el piso?',
    translation: 'What do you use to carry water when cleaning the floor?',
    options: ['el cubo', 'la taza', 'la botella'],
    correctAnswer: 'el cubo',
    hint: 'Bucket - "cubo", container for carrying water and cleaning',
    usageExample: 'Lleno el cubo de agua para limpiar el piso de la cocina.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_115',
    emoji: 'bunk-bed.png',
    question: '¿En qué tipo de cama duermen dos personas, una arriba y otra abajo?',
    translation: 'What type of bed do two people sleep in, one above and one below?',
    options: ['la litera', 'el sofá', 'la cama individual'],
    correctAnswer: 'la litera',
    hint: 'Bunk bed - "litera", bed with two levels stacked vertically',
    usageExample: 'Mis hijos duermen en la litera de su habitación.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'daily_116',
    emoji: 'child-potty.png',
    question: '¿Qué usa un niño pequeño para aprender a usar el baño?',
    translation: 'What does a small child use to learn to use the bathroom?',
    options: ['el orinal', 'la silla', 'la bañera'],
    correctAnswer: 'el orinal',
    hint: 'Child potty - "orinal", small toilet for potty training',
    usageExample: 'Mi hijo usa el orinal para aprender a ir al baño.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'daily_117',
    emoji: 'cobweb-duster.png',
    question: '¿Qué usas para quitar telarañas de las esquinas del techo?',
    translation: 'What do you use to remove cobwebs from ceiling corners?',
    options: ['el plumero de telarañas', 'la escoba', 'el trapo'],
    correctAnswer: 'el plumero de telarañas',
    hint: 'Cobweb duster - "plumero de telarañas", long tool for removing spider webs',
    usageExample: 'Limpio las esquinas del techo con el plumero de telarañas.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'daily_118',
    emoji: 'computer-repair-technician.png',
    question: '¿A quién llamas cuando tu computadora no funciona?',
    translation: 'Who do you call when your computer doesn\'t work?',
    options: ['el técnico de computadoras', 'el cocinero', 'el jardinero'],
    correctAnswer: 'el técnico de computadoras',
    hint: 'Computer repair technician - "técnico de computadoras", professional who fixes computers',
    usageExample: 'Llamé al técnico de computadoras porque mi laptop no enciende.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_119',
    emoji: 'disaster.png',
    question: '¿Cómo describes cuando algo sale muy mal en casa?',
    translation: 'How do you describe when something goes very wrong at home?',
    options: ['un desastre', 'una fiesta', 'una sorpresa'],
    correctAnswer: 'un desastre',
    hint: 'Disaster - "desastre", when things go terribly wrong',
    usageExample: 'La cocina quedó hecha un desastre después de la fiesta.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'daily_120',
    emoji: 'dish-drying-rack.png',
    question: '¿Dónde pones los platos para que se sequen después de lavarlos?',
    translation: 'Where do you put dishes to dry after washing them?',
    options: ['el escurridor de platos', 'el horno', 'el refrigerador'],
    correctAnswer: 'el escurridor de platos',
    hint: 'Dish drying rack - "escurridor de platos", rack for air-drying clean dishes',
    usageExample: 'Pongo los platos limpios en el escurridor de platos.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_121',
    emoji: 'dishwasher-machine.png',
    question: '¿Qué máquina lava los platos automáticamente?',
    translation: 'What machine washes dishes automatically?',
    options: ['el lavavajillas', 'la lavadora', 'la secadora'],
    correctAnswer: 'el lavavajillas',
    hint: 'Dishwasher - "lavavajillas", appliance that cleans dishes automatically',
    usageExample: 'Meto los platos sucios en el lavavajillas después de cenar.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_122',
    emoji: 'dryer -machine.png',
    question: '¿Qué máquina seca la ropa después de lavarla?',
    translation: 'What machine dries clothes after washing them?',
    options: ['la secadora', 'la lavadora', 'el refrigerador'],
    correctAnswer: 'la secadora',
    hint: 'Dryer - "secadora", appliance that dries wet clothes',
    usageExample: 'Seco la ropa en la secadora cuando llueve.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_123',
    emoji: 'dustpan.png',
    question: '¿Qué usas con la escoba para recoger la basura del suelo?',
    translation: 'What do you use with the broom to collect trash from the floor?',
    options: ['el recogedor', 'el cubo', 'la bolsa'],
    correctAnswer: 'el recogedor',
    hint: 'Dustpan - "recogedor", tool for collecting swept dirt and debris',
    usageExample: 'Uso la escoba y el recogedor para barrer la cocina.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_124',
    emoji: 'electric-kettle.png',
    question: '¿Qué usas para hervir agua rápidamente?',
    translation: 'What do you use to boil water quickly?',
    options: ['la tetera eléctrica', 'el microondas', 'la licuadora'],
    correctAnswer: 'la tetera eléctrica',
    hint: 'Electric kettle - "tetera eléctrica", appliance for quickly heating water',
    usageExample: 'Caliento el agua para el té en la tetera eléctrica.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_125',
    emoji: 'floor-lamp.png',
    question: '¿Qué lámpara alta pones en el suelo para iluminar una sala?',
    translation: 'What tall lamp do you put on the floor to light a room?',
    options: ['la lámpara de pie', 'la vela', 'el foco'],
    correctAnswer: 'la lámpara de pie',
    hint: 'Floor lamp - "lámpara de pie", tall standing lamp for room lighting',
    usageExample: 'Enciendo la lámpara de pie cuando leo en el sofá.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_126',
    emoji: 'garbage-can.png',
    question: '¿Dónde tiras la basura en casa?',
    translation: 'Where do you throw away trash at home?',
    options: ['el bote de basura', 'el refrigerador', 'el armario'],
    correctAnswer: 'el bote de basura',
    hint: 'Garbage can - "bote de basura", container for household waste',
    usageExample: 'Tiro los papeles usados en el bote de basura.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'daily_127',
    emoji: 'glue-gun.png',
    question: '¿Qué herramienta usas para pegar cosas con pegamento caliente?',
    translation: 'What tool do you use to glue things with hot glue?',
    options: ['la pistola de pegamento', 'el martillo', 'las tijeras'],
    correctAnswer: 'la pistola de pegamento',
    hint: 'Glue gun - "pistola de pegamento", tool that melts glue sticks for crafts',
    usageExample: 'Hago manualidades usando la pistola de pegamento.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_128',
    emoji: 'keychain.png',
    question: '¿Qué usas para mantener todas tus llaves juntas?',
    translation: 'What do you use to keep all your keys together?',
    options: ['el llavero', 'la bolsa', 'el cinturón'],
    correctAnswer: 'el llavero',
    hint: 'Keychain - "llavero", ring or chain for holding keys together',
    usageExample: 'Guardo todas mis llaves en el llavero.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_129',
    emoji: 'knife-sharpener.png',
    question: '¿Qué usas para afilar los cuchillos?',
    translation: 'What do you use to sharpen knives?',
    options: ['el afilador de cuchillos', 'la tabla de cortar', 'el tenedor'],
    correctAnswer: 'el afilador de cuchillos',
    hint: 'Knife sharpener - "afilador de cuchillos", tool for sharpening dull knife blades',
    usageExample: 'Uso el afilador de cuchillos antes de cortar la carne.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_130',
    emoji: 'laundry-basket.png',
    question: '¿Dónde pones la ropa sucia antes de lavarla?',
    translation: 'Where do you put dirty clothes before washing them?',
    options: ['la cesta de ropa', 'el armario', 'la cama'],
    correctAnswer: 'la cesta de ropa',
    hint: 'Laundry basket - "cesta de ropa", basket for collecting dirty clothes',
    usageExample: 'Pongo la ropa sucia en la cesta de ropa.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_131',
    emoji: 'measuring-cup.png',
    question: '¿Qué usas para medir ingredientes cuando cocinas?',
    translation: 'What do you use to measure ingredients when cooking?',
    options: ['la taza medidora', 'el plato', 'el vaso'],
    correctAnswer: 'la taza medidora',
    hint: 'Measuring cup - "taza medidora", cup with markings for precise measurements',
    usageExample: 'Mido la harina con la taza medidora para el pastel.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_132',
    emoji: 'mixer.png',
    question: '¿Qué electrodoméstico usas para mezclar masa o batir huevos?',
    translation: 'What appliance do you use to mix dough or beat eggs?',
    options: ['la batidora', 'la licuadora', 'el horno'],
    correctAnswer: 'la batidora',
    hint: 'Mixer - "batidora", electric appliance for mixing and beating ingredients',
    usageExample: 'Mezclo la masa del pastel con la batidora.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_133',
    emoji: 'mowing-the-lawn.png',
    question: '¿Qué haces para mantener el césped corto?',
    translation: 'What do you do to keep the grass short?',
    options: ['cortar el césped', 'regar las plantas', 'plantar flores'],
    correctAnswer: 'cortar el césped',
    hint: 'Mowing the lawn - "cortar el césped", cutting grass to maintain a yard',
    usageExample: 'Los domingos me gusta cortar el césped del jardín.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_134',
    emoji: 'paper-towel-dispenser.png',
    question: '¿De dónde sacas toallas de papel en la cocina?',
    translation: 'Where do you get paper towels from in the kitchen?',
    options: ['el dispensador de toallas de papel', 'el horno', 'el refrigerador'],
    correctAnswer: 'el dispensador de toallas de papel',
    hint: 'Paper towel dispenser - "dispensador de toallas de papel", holder for paper towel rolls',
    usageExample: 'Saco una toalla del dispensador de toallas de papel para secar las manos.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_135',
    emoji: 'park-bench.png',
    question: '¿Dónde te sientas cuando vas al parque?',
    translation: 'Where do you sit when you go to the park?',
    options: ['el banco del parque', 'la mesa', 'el suelo'],
    correctAnswer: 'el banco del parque',
    hint: 'Park bench - "banco del parque", outdoor seating in public parks',
    usageExample: 'Me siento en el banco del parque a leer un libro.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_136',
    emoji: 'pet-bowl.png',
    question: '¿Dónde pones la comida para tu perro o gato?',
    translation: 'Where do you put food for your dog or cat?',
    options: ['el plato de mascota', 'el plato grande', 'la olla'],
    correctAnswer: 'el plato de mascota',
    hint: 'Pet bowl - "plato de mascota", dish for pet food and water',
    usageExample: 'Lleno el plato de mascota con comida para mi gato.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_137',
    emoji: 'plastic-drawers.png',
    question: '¿Dónde guardas objetos pequeños en cajones de plástico?',
    translation: 'Where do you store small items in plastic drawers?',
    options: ['el organizador de cajones', 'la nevera', 'el horno'],
    correctAnswer: 'el organizador de cajones',
    hint: 'Plastic drawers - "organizador de cajones", storage unit with plastic drawer compartments',
    usageExample: 'Guardo mis cosas en el organizador de cajones del cuarto.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_138',
    emoji: 'playpen.png',
    question: '¿Dónde pones al bebé para que juegue de forma segura?',
    translation: 'Where do you put the baby to play safely?',
    options: ['el corral', 'la mesa', 'el sofá'],
    correctAnswer: 'el corral',
    hint: 'Playpen - "corral", enclosed area where babies can play safely',
    usageExample: 'Pongo al bebé en el corral mientras preparo la cena.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_139',
    emoji: 'record-player.png',
    question: '¿Qué aparato usas para escuchar discos de vinilo?',
    translation: 'What device do you use to listen to vinyl records?',
    options: ['el tocadiscos', 'la radio', 'el televisor'],
    correctAnswer: 'el tocadiscos',
    hint: 'Record player - "tocadiscos", device for playing vinyl records',
    usageExample: 'Escucho música clásica en el tocadiscos de mi abuelo.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_140',
    emoji: 'record.png',
    question: '¿Qué disco redondo de vinilo pones en el tocadiscos?',
    translation: 'What round vinyl disc do you put on the record player?',
    options: ['el disco de vinilo', 'el CD', 'la cinta'],
    correctAnswer: 'el disco de vinilo',
    hint: 'Record - "disco de vinilo", vinyl disc with recorded music',
    usageExample: 'Mi papá tiene una colección de discos de vinilo muy antigua.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_141',
    emoji: 'recycling-bin.png',
    question: '¿Dónde pones botellas y papeles para reciclar?',
    translation: 'Where do you put bottles and paper to recycle?',
    options: ['el contenedor de reciclaje', 'el horno', 'el armario'],
    correctAnswer: 'el contenedor de reciclaje',
    hint: 'Recycling bin - "contenedor de reciclaje", container for recyclable materials',
    usageExample: 'Tiro las botellas de plástico en el contenedor de reciclaje.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_142',
    emoji: 'remote-control.png',
    question: '¿Qué usas para cambiar los canales de la televisión?',
    translation: 'What do you use to change TV channels?',
    options: ['el control remoto', 'el teléfono', 'las llaves'],
    correctAnswer: 'el control remoto',
    hint: 'Remote control - "control remoto", device for controlling TV and electronics from a distance',
    usageExample: 'Uso el control remoto para cambiar los canales de la tele.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_143',
    emoji: 'solar-panel.png',
    question: '¿Qué usas en el techo para generar electricidad del sol?',
    translation: 'What do you use on the roof to generate electricity from the sun?',
    options: ['el panel solar', 'la antena', 'la chimenea'],
    correctAnswer: 'el panel solar',
    hint: 'Solar panel - "panel solar", device that converts sunlight into electricity',
    usageExample: 'Tenemos el panel solar en el techo para ahorrar energía.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_144',
    emoji: 'spilled-coffee.png',
    question: '¿Qué pasa cuando accidentalmente tiras tu café?',
    translation: 'What happens when you accidentally knock over your coffee?',
    options: ['café derramado', 'café frío', 'café nuevo'],
    correctAnswer: 'café derramado',
    hint: 'Spilled coffee - "café derramado", coffee that has been knocked over',
    usageExample: 'Limpié el café derramado de la mesa con una servilleta.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'daily_145',
    emoji: 'tablecloth.png',
    question: '¿Qué pones sobre la mesa para protegerla y decorarla?',
    translation: 'What do you put on the table to protect and decorate it?',
    options: ['el mantel', 'la almohada', 'la toalla'],
    correctAnswer: 'el mantel',
    hint: 'Tablecloth - "mantel", cloth covering for tables',
    usageExample: 'Pongo el mantel blanco para la cena especial.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_146',
    emoji: 'thermos.png',
    question: '¿Qué usas para mantener tu café caliente durante horas?',
    translation: 'What do you use to keep your coffee hot for hours?',
    options: ['el termo', 'el vaso', 'el plato'],
    correctAnswer: 'el termo',
    hint: 'Thermos - "termo", insulated container that keeps drinks hot or cold',
    usageExample: 'Llevo el termo con café caliente al trabajo.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_147',
    emoji: 'tissue-paper.png',
    question: '¿Qué usas cuando te suenas la nariz?',
    translation: 'What do you use when you blow your nose?',
    options: ['el pañuelo de papel', 'la toalla', 'la servilleta'],
    correctAnswer: 'el pañuelo de papel',
    hint: 'Tissue paper - "pañuelo de papel", disposable paper for wiping nose',
    usageExample: 'Cuando estoy resfriado uso el pañuelo de papel.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'daily_148',
    emoji: 'toaster.png',
    question: '¿Qué electrodoméstico usas para tostar el pan?',
    translation: 'What appliance do you use to toast bread?',
    options: ['la tostadora', 'el horno', 'la licuadora'],
    correctAnswer: 'la tostadora',
    hint: 'Toaster - "tostadora", appliance for making toast',
    usageExample: 'Preparo el desayuno con la tostadora cada mañana.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_149',
    emoji: 'tool-cabinet.png',
    question: '¿Dónde guardas tus herramientas organizadas?',
    translation: 'Where do you keep your tools organized?',
    options: ['el armario de herramientas', 'el refrigerador', 'el armario de ropa'],
    correctAnswer: 'el armario de herramientas',
    hint: 'Tool cabinet - "armario de herramientas", storage for tools and equipment',
    usageExample: 'Guardo el martillo y los destornilladores en el armario de herramientas.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_150',
    emoji: 'vacuum-cleaner .png',
    question: '¿Qué usas para limpiar alfombras y aspirar polvo?',
    translation: 'What do you use to clean carpets and vacuum dust?',
    options: ['la aspiradora', 'la escoba', 'el trapo'],
    correctAnswer: 'la aspiradora',
    hint: 'Vacuum cleaner - "aspiradora", machine that sucks up dirt and dust',
    usageExample: 'Paso la aspiradora por toda la casa los sábados.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_151',
    emoji: 'washing-machine.png',
    question: '¿Qué máquina usas para lavar la ropa?',
    translation: 'What machine do you use to wash clothes?',
    options: ['la lavadora', 'la secadora', 'el horno'],
    correctAnswer: 'la lavadora',
    hint: 'Washing machine - "lavadora", appliance for cleaning clothes',
    usageExample: 'Pongo la ropa sucia en la lavadora y la enciendo.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_152',
    emoji: 'weed-whacker.png',
    question: '¿Qué herramienta usas para cortar hierbas y malezas?',
    translation: 'What tool do you use to cut weeds and grass?',
    options: ['la desbrozadora', 'el martillo', 'las tijeras'],
    correctAnswer: 'la desbrozadora',
    hint: 'Weed whacker - "desbrozadora", tool for trimming weeds and grass',
    usageExample: 'Uso la desbrozadora para limpiar las orillas del jardín.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_153',
    emoji: 'wheelbarrow.png',
    question: '¿Qué usas para transportar tierra y materiales pesados en el jardín?',
    translation: 'What do you use to transport dirt and heavy materials in the garden?',
    options: ['la carretilla', 'la caja', 'la bolsa'],
    correctAnswer: 'la carretilla',
    hint: 'Wheelbarrow - "carretilla", cart with one wheel for moving heavy loads',
    usageExample: 'Transporto la tierra con la carretilla hasta el jardín.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_154',
    emoji: 'window-cleaner.png',
    question: '¿Qué usas para limpiar las ventanas?',
    translation: 'What do you use to clean windows?',
    options: ['el limpiacristales', 'el martillo', 'la escoba'],
    correctAnswer: 'el limpiacristales',
    hint: 'Window cleaner - "limpiacristales", tool or product for cleaning windows',
    usageExample: 'Limpio las ventanas de casa con el limpiacristales.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_155',
    emoji: '🎧',
    question: '¿Qué te pones en las orejas para escuchar música?',
    translation: 'What do you put in your ears to listen to music?',
    options: ['los audífonos', 'los auriculares', 'los cascos'],
    correctAnswer: 'los audífonos',
    hint: 'Headphones - "auriculares" in Spain, "audífonos" in Latin America',
    usageExample: 'Me pongo los audífonos para escuchar música en el metro.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_156',
    emoji: '📚',
    question: '¿Qué haces con un libro?',
    translation: 'What do you do with a book?',
    options: ['leer', 'la lectura', 'leyendo'],
    correctAnswer: 'leer',
    hint: 'Reading - "leer" means to read, essential for learning languages',
    usageExample: 'Me gusta leer un libro antes de dormir.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_157',
    emoji: '✍️',
    question: '¿Qué haces cuando creas un texto?',
    translation: 'What do you do when you create a text?',
    options: ['escribir', 'la escritura', 'redactar'],
    correctAnswer: 'escribir',
    hint: 'Writing - "escribir" creates text, from Latin "scribere"',
    usageExample: 'Necesito escribir un correo para mi jefe.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_158',
    emoji: '📖',
    question: '¿Dónde encuentras libros para leer gratis?',
    translation: 'Where do you find books to read for free?',
    options: ['la biblioteca', 'la librería', 'la sala de lectura'],
    correctAnswer: 'la biblioteca',
    hint: 'Library - free book lending, from Greek "bibliotheke" (book repository)',
    usageExample: 'Voy a la biblioteca para estudiar y leer libros.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_159',
    emoji: '📰',
    question: '¿Qué lees para saber las noticias del día?',
    translation: 'What do you read to know the day\'s news?',
    options: ['el periódico', 'el diario', 'la prensa'],
    correctAnswer: 'el periódico',
    hint: 'Newspaper - daily news publication, "diario" also means newspaper',
    usageExample: 'Leo el periódico mientras desayuno.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_160',
    emoji: '✏️',
    question: '¿Qué usas para escribir y borrar?',
    translation: 'What do you use to write and erase?',
    options: ['el lápiz', 'el lapicero', 'el portaminas'],
    correctAnswer: 'el lápiz',
    hint: 'Pencil - graphite writing tool, erasable unlike pen ("pluma")',
    usageExample: 'Escribo mis notas con el lápiz en clase.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_161',
    emoji: '🧸',
    question: '¿Qué animal de peluche es popular?',
    translation: 'What stuffed animal is popular?',
    options: ['el oso de peluche', 'el osito', 'el peluche'],
    correctAnswer: 'el oso de peluche',
    hint: 'Teddy bear - soft stuffed toy, "peluche" means plush',
    usageExample: 'Mi hija duerme abrazando su oso de peluche.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },

    {
    id: 'daily_162',
    emoji: '🖍️',
    question: '¿Con qué dibujan los niños?',
    translation: 'What do children draw with?',
    options: ['el crayón', 'la crayola', 'el color'],
    correctAnswer: 'el crayón',
    hint: 'Crayon - wax sticks in colors, "crayola" brand name commonly used',
    usageExample: 'Los niños pintan con el crayón en la escuela.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'daily_163',
    emoji: 'bathroom-scale.png',
    question: '¿En qué te pesas en el baño?',
    translation: 'What do you weigh yourself on in the bathroom?',
    options: ['la báscula', 'la balanza', 'el peso'],
    correctAnswer: 'la báscula',
    hint: 'Bathroom scale - device for weighing yourself, digital or analog',
    usageExample: 'Me peso en la báscula todos los lunes.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_164',
    emoji: 'bedroom.png',
    question: '¿Dónde duermes en tu casa?',
    translation: 'Where do you sleep in your house?',
    options: ['el dormitorio', 'la recámara', 'la habitación'],
    correctAnswer: 'el dormitorio',
    hint: 'Bedroom - room for sleeping, "recámara" common in Mexico',
    usageExample: 'Descanso en el dormitorio después de un día largo.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_165',
    emoji: 'blackboard-chalk.png',
    question: '¿Con qué escribes en el pizarrón?',
    translation: 'What do you write with on the blackboard?',
    options: ['el gis', 'la tiza', 'el marcador'],
    correctAnswer: 'el gis',
    hint: 'Chalk - white stick for writing on blackboard, "tiza" also used',
    usageExample: 'El maestro escribe con el gis en el pizarrón.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_166',
    emoji: 'bottle-opener.png',
    question: '¿Qué usas para abrir botellas?',
    translation: 'What do you use to open bottles?',
    options: ['el destapador', 'el abrebotellas', 'el abridor'],
    correctAnswer: 'el destapador',
    hint: 'Bottle opener - tool to remove bottle caps, kitchen essential',
    usageExample: 'Abro las botellas con el destapador en la cocina.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_167',
    emoji: 'childs-wagon.png',
    question: '¿En qué carrito jalan los niños sus juguetes?',
    translation: 'What wagon do children pull their toys in?',
    options: ['el carrito de juguete', 'el vagón', 'la carretilla'],
    correctAnswer: 'el carrito de juguete',
    hint: "Child's wagon - four-wheeled cart children pull with handle",
    usageExample: 'Mi hijo lleva sus juguetes en el carrito de juguete.',
    points: 10,
    category: 'daily_routines',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'daily_168',
    emoji: 'chimney.png',
    question: '¿Por dónde sale el humo de la casa?',
    translation: 'Where does smoke come out of the house?',
    options: ['la chimenea', 'el tubo', 'la salida'],
    correctAnswer: 'la chimenea',
    hint: 'Chimney - structure for venting smoke from fireplace',
    usageExample: 'El humo sale por la chimenea en invierno.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_169',
    emoji: 'curtains.png',
    question: '¿Qué cuelgas en las ventanas para privacidad?',
    translation: 'What do you hang on windows for privacy?',
    options: ['las cortinas', 'las persianas', 'los visillos'],
    correctAnswer: 'las cortinas',
    hint: 'Curtains - fabric window coverings for privacy and decoration',
    usageExample: 'Cierro las cortinas cuando sale el sol.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_170',
    emoji: 'dog-leash.png',
    question: '¿Qué usas para pasear al perro?',
    translation: 'What do you use to walk the dog?',
    options: ['la correa', 'la cadena', 'el arnés'],
    correctAnswer: 'la correa',
    hint: 'Dog leash - strap to control dog during walks',
    usageExample: 'Pongo la correa a mi perro para salir a caminar.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'daily_171',
    emoji: 'doodle.png',
    question: '¿Qué haces cuando dibujas sin pensar?',
    translation: 'What do you do when you draw without thinking?',
    options: ['garabatear', 'dibujar', 'rayar'],
    correctAnswer: 'garabatear',
    hint: 'Doodle - casual, mindless drawing or scribbling',
    usageExample: 'A veces me gusta garabatear mientras hablo por teléfono.',
    points: 10,
    category: 'daily_routines',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'daily_172',
    emoji: 'drawer-liner.png',
    question: '¿Qué pones en el fondo de los cajones?',
    translation: 'What do you put on the bottom of drawers?',
    options: ['el forro de cajón', 'el papel', 'la alfombra'],
    correctAnswer: 'el forro de cajón',
    hint: 'Drawer liner - protective paper or fabric lining inside drawers',
    usageExample: 'Pongo el forro de cajón para proteger la madera.',
    points: 10,
    category: 'daily_routines',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'daily_173',
    emoji: 'exam.png',
    question: '¿Qué haces para evaluar tu conocimiento?',
    translation: 'What do you do to evaluate your knowledge?',
    options: ['el examen', 'la prueba', 'el test'],
    correctAnswer: 'el examen',
    hint: 'Exam - test to evaluate knowledge, "prueba" also common',
    usageExample: 'Estudio mucho antes de hacer el examen de matemáticas.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'daily_174',
    emoji: 'floor-fan.png',
    question: '¿Qué ventilador pones en el piso?',
    translation: 'What fan do you put on the floor?',
    options: ['el ventilador de piso', 'el abanico', 'el aire'],
    correctAnswer: 'el ventilador de piso',
    hint: 'Floor fan - standing fan placed on ground for air circulation',
    usageExample: 'Enciendo el ventilador de piso cuando hace calor.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_175',
    emoji: 'funnel.png',
    question: '¿Qué usas para verter líquidos sin derramar?',
    translation: 'What do you use to pour liquids without spilling?',
    options: ['el embudo', 'la jarra', 'el tubo'],
    correctAnswer: 'el embudo',
    hint: 'Funnel - cone-shaped tool for pouring liquids into containers',
    usageExample: 'Uso el embudo para llenar las botellas sin derramar.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_176',
    emoji: 'graffiti.png',
    question: '¿Qué arte urbano ves en las paredes?',
    translation: 'What urban art do you see on walls?',
    options: ['el grafiti', 'el mural', 'la pintura'],
    correctAnswer: 'el grafiti',
    hint: 'Graffiti - street art spray-painted on walls and buildings',
    usageExample: 'Hay mucho grafiti en las paredes del centro.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_177',
    emoji: 'hammock.png',
    question: '¿Dónde te relajas colgado entre dos árboles?',
    translation: 'Where do you relax hanging between two trees?',
    options: ['la hamaca', 'la red', 'la cama'],
    correctAnswer: 'la hamaca',
    hint: 'Hammock - suspended bed for relaxing outdoors',
    usageExample: 'Me acuesto en la hamaca a descansar en el jardín.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_178',
    emoji: 'house-painting.png',
    question: '¿Qué haces cuando renuevas las paredes de tu casa?',
    translation: 'What do you do when you renew your house walls?',
    options: ['pintar la casa', 'renovar', 'decorar'],
    correctAnswer: 'pintar la casa',
    hint: 'House painting - applying new paint to home exterior or interior',
    usageExample: 'Vamos a pintar la casa de color azul este verano.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_179',
    emoji: 'knitting.png',
    question: '¿Qué haces con agujas y lana?',
    translation: 'What do you do with needles and yarn?',
    options: ['tejer', 'coser', 'bordar'],
    correctAnswer: 'tejer',
    hint: 'Knitting - creating fabric by interlocking loops of yarn with needles',
    usageExample: 'Mi abuela me enseñó a tejer una bufanda.',
    points: 10,
    category: 'daily_routines',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'daily_180',
    emoji: 'lint-roller.png',
    question: '¿Qué usas para quitar pelusa de la ropa?',
    translation: 'What do you use to remove lint from clothes?',
    options: ['el rodillo quitapelusas', 'el cepillo', 'la escoba'],
    correctAnswer: 'el rodillo quitapelusas',
    hint: 'Lint roller - sticky roller for removing lint and pet hair from fabric',
    usageExample: 'Paso el rodillo quitapelusas por mi traje negro.',
    points: 10,
    category: 'daily_routines',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'daily_181',
    emoji: 'living-room.png',
    question: '¿Dónde recibes visitas en tu casa?',
    translation: 'Where do you receive guests in your house?',
    options: ['la sala', 'el living', 'la estancia'],
    correctAnswer: 'la sala',
    hint: 'Living room - main room for entertaining and relaxing',
    usageExample: 'Vemos televisión en la sala con toda la familia.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_182',
    emoji: 'mist-humidifier.png',
    question: '¿Qué aparato agrega humedad al aire?',
    translation: 'What device adds moisture to the air?',
    options: ['el humidificador', 'el vaporizador', 'el difusor'],
    correctAnswer: 'el humidificador',
    hint: 'Humidifier - device that increases humidity in dry air',
    usageExample: 'Uso el humidificador en invierno porque el aire está muy seco.',
    points: 10,
    category: 'daily_routines',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'daily_183',
    emoji: 'mouse-trap.png',
    question: '¿Qué usas para atrapar ratones?',
    translation: 'What do you use to catch mice?',
    options: ['la ratonera', 'la trampa', 'el cebo'],
    correctAnswer: 'la ratonera',
    hint: 'Mouse trap - device for catching mice in the house',
    usageExample: 'Puse la ratonera en el sótano porque escuché un ratón.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_184',
    emoji: 'oven-mitt.png',
    question: '¿Qué te pones para sacar cosas calientes del horno?',
    translation: 'What do you wear to take hot things from the oven?',
    options: ['el guante de cocina', 'la manopla', 'el agarrador'],
    correctAnswer: 'el guante de cocina',
    hint: 'Oven mitt - thick glove for handling hot cookware',
    usageExample: 'Uso el guante de cocina para sacar la pizza del horno.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_185',
    emoji: 'pen-holder.png',
    question: '¿Dónde guardas tus plumas en el escritorio?',
    translation: 'Where do you keep your pens on the desk?',
    options: ['el portalápices', 'el lapicero', 'el organizador'],
    correctAnswer: 'el portalápices',
    hint: 'Pen holder - container for organizing pens and pencils on desk',
    usageExample: 'Tengo mis plumas organizadas en el portalápices del escritorio.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_186',
    emoji: 'seam-ripper.png',
    question: '¿Qué herramienta usas para descoser?',
    translation: 'What tool do you use to remove stitches?',
    options: ['el descosedor', 'la tijera', 'la aguja'],
    correctAnswer: 'el descosedor',
    hint: 'Seam ripper - small tool with sharp point for removing stitches',
    usageExample: 'Uso el descosedor para quitar la costura mal hecha.',
    points: 15,
    category: 'daily_routines',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'daily_187',
    emoji: 'sewing-kit.png',
    question: '¿Qué conjunto de herramientas usas para coser?',
    translation: 'What set of tools do you use for sewing?',
    options: ['el kit de costura', 'la caja de costura', 'el costurero'],
    correctAnswer: 'el kit de costura',
    hint: 'Sewing kit - collection of needles, thread, and tools for sewing',
    usageExample: 'Siempre llevo el kit de costura cuando viajo.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_188',
    emoji: 'sewing-machine.png',
    question: '¿Qué máquina usas para coser ropa?',
    translation: 'What machine do you use to sew clothes?',
    options: ['la máquina de coser', 'la cosedora', 'la bordadora'],
    correctAnswer: 'la máquina de coser',
    hint: 'Sewing machine - electric device for stitching fabric together',
    usageExample: 'Mi mamá hace ropa con la máquina de coser.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_189',
    emoji: 'shoe-polish.png',
    question: '¿Qué usas para dar brillo a los zapatos?',
    translation: 'What do you use to shine shoes?',
    options: ['la grasa para zapatos', 'la cera', 'el betún'],
    correctAnswer: 'la grasa para zapatos',
    hint: 'Shoe polish - waxy substance for cleaning and shining leather shoes',
    usageExample: 'Uso la grasa para zapatos para limpiar mis botas de cuero.',
    points: 10,
    category: 'daily_routines',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'daily_190',
    emoji: 'shower-curtain.png',
    question: '¿Qué cuelgas en la regadera para evitar mojar el piso?',
    translation: 'What do you hang in the shower to avoid wetting the floor?',
    options: ['la cortina de baño', 'la mampara', 'el plástico'],
    correctAnswer: 'la cortina de baño',
    hint: 'Shower curtain - waterproof barrier to contain shower water',
    usageExample: 'Cierro la cortina de baño para que no salpique agua.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_191',
    emoji: 'smart-tv.png',
    question: '¿Qué televisión se conecta a internet?',
    translation: 'What television connects to the internet?',
    options: ['el televisor inteligente', 'el Smart TV', 'la tele moderna'],
    correctAnswer: 'el televisor inteligente',
    hint: 'Smart TV - internet-connected television with apps and streaming',
    usageExample: 'Veo películas en el televisor inteligente de la sala.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_192',
    emoji: 'sock-organizer.png',
    question: '¿Dónde organizas tus calcetines?',
    translation: 'Where do you organize your socks?',
    options: ['el organizador de calcetines', 'el cajón', 'la caja'],
    correctAnswer: 'el organizador de calcetines',
    hint: 'Sock organizer - storage solution for keeping socks paired and tidy',
    usageExample: 'Guardo mis calcetines en el organizador de calcetines.',
    points: 10,
    category: 'daily_routines',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'daily_193',
    emoji: 'spray-mop.png',
    question: '¿Qué trapeador rocía líquido mientras limpias?',
    translation: 'What mop sprays liquid while you clean?',
    options: ['el trapeador con atomizador', 'el spray mop', 'el trapeador'],
    correctAnswer: 'el trapeador con atomizador',
    hint: 'Spray mop - mop with built-in spray bottle for cleaning solution',
    usageExample: 'Limpio el piso rápidamente con el trapeador con atomizador.',
    points: 10,
    category: 'daily_routines',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'daily_194',
    emoji: 'stepping-stool.png',
    question: '¿Qué usas para alcanzar lugares altos?',
    translation: 'What do you use to reach high places?',
    options: ['el banquito', 'el escalón', 'la escalera'],
    correctAnswer: 'el banquito',
    hint: 'Stepping stool - small platform for reaching higher shelves',
    usageExample: 'Me subo en el banquito para alcanzar los platos de arriba.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_195',
    emoji: 'stool.png',
    question: '¿En qué te sientas sin respaldo?',
    translation: 'What do you sit on without a backrest?',
    options: ['el taburete', 'el banco', 'la silla'],
    correctAnswer: 'el taburete',
    hint: 'Stool - seat without back or arms, often at bar or kitchen',
    usageExample: 'Me siento en el taburete de la cocina para desayunar.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_196',
    emoji: 'study.png',
    question: '¿Dónde trabajas o lees en casa?',
    translation: 'Where do you work or read at home?',
    options: ['el estudio', 'la oficina', 'el escritorio'],
    correctAnswer: 'el estudio',
    hint: 'Study - room for working, reading, and intellectual activities',
    usageExample: 'Trabajo desde casa en el estudio.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_197',
    emoji: 'studying.png',
    question: '¿Qué haces cuando aprendes para un examen?',
    translation: 'What do you do when you learn for an exam?',
    options: ['estudiar', 'leer', 'practicar'],
    correctAnswer: 'estudiar',
    hint: 'Studying - reviewing and learning material for tests or knowledge',
    usageExample: 'Tengo que estudiar para el examen de mañana.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'daily_198',
    emoji: 'swing.png',
    question: '¿En qué se mecen los niños en el parque?',
    translation: 'What do children swing on in the park?',
    options: ['el columpio', 'la hamaca', 'el balancín'],
    correctAnswer: 'el columpio',
    hint: 'Swing - hanging seat that moves back and forth, playground favorite',
    usageExample: 'Los niños juegan en el columpio del parque.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'daily_199',
    emoji: 'toilet-paper-holder.png',
    question: '¿Dónde pones el rollo de papel en el baño?',
    translation: 'Where do you put the toilet paper roll in the bathroom?',
    options: ['el portapapel', 'el soporte', 'el gancho'],
    correctAnswer: 'el portapapel',
    hint: 'Toilet paper holder - wall-mounted holder for bathroom tissue',
    usageExample: 'Cambié el rollo vacío en el portapapel del baño.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_200',
    emoji: 'toilet-plunger.png',
    question: '¿Qué usas para desatascar el inodoro?',
    translation: 'What do you use to unclog the toilet?',
    options: ['el destapacaños', 'la bomba', 'el desatascador'],
    correctAnswer: 'el destapacaños',
    hint: 'Toilet plunger - rubber suction tool for clearing toilet clogs',
    usageExample: 'Uso el destapacaños cuando el inodoro se tapa.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_201',
    emoji: 'toilet-step-stool.png',
    question: '¿Qué banquito usan los niños en el baño?',
    translation: 'What stool do children use in the bathroom?',
    options: ['el banquito de baño', 'el escalón', 'el taburete'],
    correctAnswer: 'el banquito de baño',
    hint: 'Toilet step stool - small platform helping children reach toilet and sink',
    usageExample: 'Mi hijo usa el banquito de baño para lavarse las manos.',
    points: 10,
    category: 'daily_routines',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'daily_202',
    emoji: 'video-doorbell.png',
    question: '¿Qué timbre tiene cámara?',
    translation: 'What doorbell has a camera?',
    options: ['el timbre con video', 'el video portero', 'el Ring'],
    correctAnswer: 'el timbre con video',
    hint: 'Video doorbell - smart doorbell with camera for seeing visitors',
    usageExample: 'Veo quién llega con el timbre con video de la puerta.',
    points: 10,
    category: 'daily_routines',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'daily_203',
    emoji: 'watering-can.png',
    question: '¿Con qué riegas las plantas?',
    translation: 'What do you water plants with?',
    options: ['la regadera', 'la manguera', 'el rociador'],
    correctAnswer: 'la regadera',
    hint: 'Watering can - container with spout for watering plants by hand',
    usageExample: 'Riego las flores del jardín con la regadera.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'daily_204',
    emoji: 'wedding.png',
    question: '¿Qué ceremonia celebra el matrimonio?',
    translation: 'What ceremony celebrates marriage?',
    options: ['la boda', 'el matrimonio', 'la ceremonia'],
    correctAnswer: 'la boda',
    hint: 'Wedding - marriage ceremony and celebration, "boda" from vows',
    usageExample: 'Fuimos a la boda de mi prima el sábado.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'daily_205',
    emoji: 'window-screen.png',
    question: '¿Qué pones en la ventana para evitar insectos?',
    translation: 'What do you put on windows to keep out insects?',
    options: ['el mosquitero', 'la malla', 'la red'],
    correctAnswer: 'el mosquitero',
    hint: 'Window screen - mesh barrier that lets air in but keeps bugs out',
    usageExample: 'Puse el mosquitero en la ventana para que no entren moscas.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'daily_206',
    emoji: 'wood-planks.png',
    question: '¿Qué tablas de madera usas para construir?',
    translation: 'What wooden boards do you use to build?',
    options: ['las tablas de madera', 'los tablones', 'las vigas'],
    correctAnswer: 'las tablas de madera',
    hint: 'Wood planks - flat wooden boards used in construction and carpentry',
    usageExample: 'Compré las tablas de madera para hacer una mesa.',
    points: 5,
    category: 'daily_routines',
    difficulty: 'easy',
    emotion: 'neutral',
  },

];
