/**
 * DIRECTIONS Category Questions
 * Category: directions
 */

export const directionsQuestions = [
{
    id: 'directions_001',
    emoji: '⬆️',
    question: '¿Qué dirección es?',
    translation: 'What direction is it?',
    options: ['arriba', 'hacia arriba', 'para arriba'],
    correctAnswer: 'arriba',
    hint: 'Up - higher position, opposite of "abajo" (down)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_002',
    emoji: '⬇️',
    question: '¿Qué dirección es?',
    translation: 'What direction is it?',
    options: ['abajo', 'hacia abajo', 'para abajo'],
    correctAnswer: 'abajo',
    hint: 'Down - lower position, from "a" + "bajo" (low)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_003',
    emoji: '➡️',
    question: '¿Qué dirección es?',
    translation: 'What direction is it?',
    options: ['derecha', 'a la derecha', 'hacia la derecha'],
    correctAnswer: 'derecha',
    hint: 'Right - from Latin "directa" (straight), opposite of left',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_004',
    emoji: '⬅️',
    question: '¿Qué dirección es?',
    translation: 'What direction is it?',
    options: ['izquierda', 'a la izquierda', 'hacia la izquierda'],
    correctAnswer: 'izquierda',
    hint: 'Left - from Basque "ezker", opposite of right',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_005',
    emoji: '🗺️',
    question: '¿Qué consultas para orientarte en la ciudad?',
    translation: 'What do you check to orient yourself in the city?',
    options: ['el mapa', 'el plano', 'la carta'],
    correctAnswer: 'el mapa',
    hint: 'Map - shows geography and locations, from Latin "mappa mundi" (world cloth)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_006',
    emoji: '🧭',
    question: '¿Qué instrumento siempre apunta al norte?',
    translation: 'What instrument always points north?',
    options: ['la brújula', 'el compás', 'la compass'],
    correctAnswer: 'la brújula',
    hint: 'Compass - points north with magnetic needle, essential navigation tool',
    points: 10,
    category: 'directions',
    difficulty: 'medium',
  },
  {
    id: 'directions_007',
    emoji: '🏛️',
    question: '¿Dónde ves arte e historia?',
    translation: 'Where do you see art and history?',
    options: ['el museo', 'el museo de arte', 'la galería'],
    correctAnswer: 'el museo',
    hint: 'Museum - displays art and history, from Greek "mouseion" (temple of muses)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_008',
    emoji: '⛪',
    question: '¿Dónde vas a rezar o a misa?',
    translation: 'Where do you go to pray or to mass?',
    options: ['la iglesia', 'el templo', 'la capilla'],
    correctAnswer: 'la iglesia',
    hint: 'Church - place of worship, from Greek "ekklesia" (assembly)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_009',
    emoji: '🏦',
    question: '¿Dónde depositas o retiras dinero?',
    translation: 'Where do you deposit or withdraw money?',
    options: ['el banco', 'la sucursal', 'la institución financiera'],
    correctAnswer: 'el banco',
    hint: 'Bank - financial institution for money, also means "bench" in Spanish',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_010',
    emoji: '🏪',
    question: '¿Dónde compras productos?',
    translation: 'Where do you buy products?',
    options: ['la tienda', 'el comercio', 'el negocio'],
    correctAnswer: 'la tienda',
    hint: 'Store - where you buy goods, "tienda de abarrotes" is grocery store',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_011',
    emoji: '🏥',
    question: '¿Dónde van los enfermos graves?',
    translation: 'Where do seriously ill people go?',
    options: ['el hospital', 'el centro médico', 'la clínica'],
    correctAnswer: 'el hospital',
    hint: 'Hospital - medical facility for serious care, from Latin "hospes" (guest)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_012',
    emoji: '💊',
    question: '¿Dónde puedes comprar esto?',
    translation: 'Where can you buy this?',
    options: ['la farmacia', 'la botica', 'la droguería'],
    correctAnswer: 'la farmacia',
    hint: 'Pharmacy - sells medicine and prescriptions, "botica" also used',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_013',
    emoji: '🏖️',
    question: '¿Qué lugar es?',
    translation: 'What place is it?',
    options: ['la playa', 'la costa', 'la orilla'],
    correctAnswer: 'la playa',
    hint: 'Beach - sandy shore by ocean, popular destination for sun and swimming',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_014',
    emoji: '🏞️',
    question: '¿Cómo se llama un gran espacio verde público?',
    translation: 'What is a large public green space called?',
    options: ['el parque', 'el jardín público', 'el área verde'],
    correctAnswer: 'el parque',
    hint: 'Park - public green space, "jardín" is smaller garden',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_015',
    emoji: '🌉',
    question: '¿Qué estructura cruza un río o valle?',
    translation: 'What structure crosses a river or valley?',
    options: ['el puente', 'el viaducto', 'el paso elevado'],
    correctAnswer: 'el puente',
    hint: 'Bridge - crosses over water or valley, landmark for giving directions',
    points: 10,
    category: 'directions',
    difficulty: 'medium',
  },

  // Giving Directions (15 questions)
  {
    id: 'directions_016',
    emoji: '↩️',
    question: '¿Qué haces para volver?',
    translation: 'What do you do to return?',
    options: ['regresar', 'volver', 'retornar'],
    correctAnswer: 'regresar',
    hint: 'Return/go back - "volver" also means to return, from "re-" + "gresar"',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_017',
    emoji: '➡️',
    question: '¿Qué haces para avanzar?',
    translation: 'What do you do to advance?',
    options: ['seguir adelante', 'continuar', 'ir recto'],
    correctAnswer: 'seguir adelante',
    hint: 'Continue forward - "adelante" means ahead, keep going straight',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_018',
    emoji: '↪️',
    question: '¿Qué haces en la esquina?',
    translation: 'What do you do at the corner?',
    options: ['doblar', 'girar', 'voltear'],
    correctAnswer: 'doblar',
    hint: 'Turn - "girar" and "voltear" also mean turn at corner',
    points: 10,
    category: 'directions',
    difficulty: 'medium',
  },
  {
    id: 'directions_019',
    emoji: '↖️',
    question: '¿Cómo doblas a la izquierda?',
    translation: 'How do you turn left?',
    options: ['girar a la izquierda', 'dar vuelta a la izquierda', 'voltear a la izquierda'],
    correctAnswer: 'girar a la izquierda',
    hint: 'Turn left - "girar" from Latin "gyrare" (to rotate)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_020',
    emoji: '↗️',
    question: '¿Cómo doblas a la derecha?',
    translation: 'How do you turn right?',
    options: ['girar a la derecha', 'dar vuelta a la derecha', 'voltear a la derecha'],
    correctAnswer: 'girar a la derecha',
    hint: 'Turn right - at next intersection or corner',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_021',
    emoji: '🔀',
    question: '¿Dónde se encuentran dos calles?',
    translation: 'Where do two streets meet?',
    options: ['la esquina', 'el rincón', 'el ángulo'],
    correctAnswer: 'la esquina',
    hint: 'Corner - where streets intersect, common reference point',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_022',
    emoji: '📏',
    question: '¿Qué es una sección de calle?',
    translation: 'What is a section of street?',
    options: ['la cuadra', 'la manzana', 'el block'],
    correctAnswer: 'la cuadra',
    hint: 'City block - "manzana" in Spain, distance between corners',
    points: 10,
    category: 'directions',
    difficulty: 'medium',
  },
  {
    id: 'directions_023',
    emoji: '🚶',
    question: '¿Cuánto tiempo toma llegar?',
    translation: 'How long does it take to arrive?',
    options: ['cinco minutos a pie', 'cinco minutos caminando', 'cinco minutos de caminata'],
    correctAnswer: 'cinco minutos a pie',
    hint: 'Five minutes walking - "a pie" means on foot, common time estimate',
    points: 10,
    category: 'directions',
    difficulty: 'medium',
  },
  {
    id: 'directions_024',
    emoji: '📍',
    question: '¿Dónde estás ahora?',
    translation: 'Where are you now?',
    options: ['aquí', 'acá', 'en este lugar'],
    correctAnswer: 'aquí',
    hint: 'Here - current location, from Latin "hac" (this way)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_025',
    emoji: '👉',
    question: '¿Dónde está lejos de ti?',
    translation: 'Where is far from you?',
    options: ['allá', 'allí', 'ahí'],
    correctAnswer: 'allá',
    hint: 'Over there - far away, distant location from speaker',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_026',
    emoji: '👆',
    question: '¿Dónde está cerca?',
    translation: 'Where is near?',
    options: ['allí', 'ahí', 'allá'],
    correctAnswer: 'allí',
    hint: 'There - nearby but not here, medium distance from speaker',
    points: 10,
    category: 'directions',
    difficulty: 'medium',
  },
  {
    id: 'directions_027',
    emoji: '🏃',
    question: '¿Qué está al final de la calle?',
    translation: 'What is at the end of the street?',
    options: ['al fondo', 'al final', 'en el fondo'],
    correctAnswer: 'al fondo',
    hint: 'At the end/back - furthest point, "fondo" means bottom/depth',
    points: 10,
    category: 'directions',
    difficulty: 'medium',
  },
  {
    id: 'directions_028',
    emoji: '🚶‍♂️',
    question: '¿Qué está al otro lado?',
    translation: 'What is on the other side?',
    options: ['enfrente', 'al frente', 'de frente'],
    correctAnswer: 'enfrente',
    hint: 'In front/across - opposite side, "frente" means front/face',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_029',
    emoji: '👥',
    question: '¿Qué está junto a ti?',
    translation: 'What is next to you?',
    options: ['al lado', 'junto a', 'a un lado'],
    correctAnswer: 'al lado',
    hint: 'Next to/beside - immediately adjacent, "lado" means side',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_030',
    emoji: '🔙',
    question: '¿Qué está atrás de ti?',
    translation: 'What is behind you?',
    options: ['detrás', 'atrás', 'por detrás'],
    correctAnswer: 'detrás',
    hint: 'Behind - in back, opposite of "delante" (in front)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },

  // Locations & Landmarks (20 questions)
  {
    id: 'directions_031',
    emoji: '🏛️',
    question: '¿Qué edificio tiene gobierno?',
    translation: 'What building has the government?',
    options: ['el ayuntamiento', 'la municipalidad', 'la alcaldía'],
    correctAnswer: 'el ayuntamiento',
    hint: 'City hall - local government building, "municipalidad" in Latin America',
    points: 10,
    category: 'directions',
    difficulty: 'medium',
  },
  {
    id: 'directions_032',
    emoji: '🏤',
    question: '¿Dónde envías cartas?',
    translation: 'Where do you send letters?',
    options: ['la oficina de correos', 'correos', 'el correo'],
    correctAnswer: 'la oficina de correos',
    hint: 'Post office - "correos" is mail service, send letters and packages',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_033',
    emoji: '🏫',
    question: '¿Dónde estudian los niños?',
    translation: 'Where do children study?',
    options: ['la escuela', 'el colegio', 'la escuela primaria'],
    correctAnswer: 'la escuela',
    hint: 'School - "colegio" for primary/secondary, from Latin "schola"',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_034',
    emoji: '🏢',
    question: '¿Dónde trabaja la gente?',
    translation: 'Where do people work?',
    options: ['la oficina', 'el despacho', 'el lugar de trabajo'],
    correctAnswer: 'la oficina',
    hint: 'Office - workplace for desk jobs, business building',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_035',
    emoji: '🏨',
    question: '¿Dónde se quedan los turistas?',
    translation: 'Where do tourists stay?',
    options: ['el hotel', 'el hostal', 'la posada'],
    correctAnswer: 'el hotel',
    hint: 'Hotel - temporary lodging, from French "hôtel" (mansion)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_036',
    emoji: '🏪',
    question: '¿Dónde compras artículos pequeños?',
    translation: 'Where do you buy small items?',
    options: ['la tienda de conveniencia', 'la tiendita', 'la bodega'],
    correctAnswer: 'la tienda de conveniencia',
    hint: 'Convenience store - small shop, "tiendita" or "bodega" in some regions',
    points: 10,
    category: 'directions',
    difficulty: 'medium',
  },
  {
    id: 'directions_037',
    emoji: '🏬',
    question: '¿Qué centro tiene muchas tiendas?',
    translation: 'What center has many stores?',
    options: ['el centro comercial', 'la plaza comercial', 'el mall'],
    correctAnswer: 'el centro comercial',
    hint: 'Shopping mall - indoor complex, "plaza comercial" in Mexico',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_038',
    emoji: '🍽️',
    question: '¿Dónde comes fuera de casa?',
    translation: 'Where do you eat outside the house?',
    options: ['el restaurante', 'el restorán', 'el comedor'],
    correctAnswer: 'el restaurante',
    hint: 'Restaurant - "restaurar" means restore, restores hunger with food',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_039',
    emoji: '☕',
    question: '¿Dónde tomas café?',
    translation: 'Where do you drink coffee?',
    options: ['la cafetería', 'el café', 'el coffee shop'],
    correctAnswer: 'la cafetería',
    hint: 'Coffee shop - "café" in Spain, serves coffee and light meals',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_040',
    emoji: '🎭',
    question: '¿Dónde ves obras de teatro?',
    translation: 'Where do you watch plays?',
    options: ['el teatro', 'el auditorio', 'la sala de teatro'],
    correctAnswer: 'el teatro',
    hint: 'Theater - for live plays, from Greek "theatron" (viewing place)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_041',
    emoji: '🎬',
    question: '¿Dónde ves películas?',
    translation: 'Where do you watch movies?',
    options: ['el cine', 'el cinematógrafo', 'la sala de cine'],
    correctAnswer: 'el cine',
    hint: 'Cinema - movie theater, short for "cinematógrafo" (moving pictures)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_042',
    emoji: '🖼️',
    question: '¿Dónde ves arte?',
    translation: 'Where do you see art?',
    options: ['el museo', 'el museo de arte', 'la galería'],
    correctAnswer: 'el museo',
    hint: 'Museum - "museo de arte" is art museum, Prado in Madrid famous',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_043',
    emoji: '🏟️',
    question: '¿Dónde ves deportes?',
    translation: 'Where do you watch sports?',
    options: ['el estadio', 'el campo deportivo', 'la arena'],
    correctAnswer: 'el estadio',
    hint: 'Stadium - large sports venue, Camp Nou in Barcelona holds 99,000',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_044',
    emoji: '⛪',
    question: '¿Qué edificio religioso es grande?',
    translation: 'What religious building is large?',
    options: ['la catedral', 'la iglesia catedral', 'la basílica'],
    correctAnswer: 'la catedral',
    hint: 'Cathedral - main church of diocese, Sagrada Familia iconic in Barcelona',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_045',
    emoji: '🕌',
    question: '¿Qué templo tiene cúpula?',
    translation: 'What temple has a dome?',
    options: ['la mezquita', 'el templo musulmán', 'la mezquita mayor'],
    correctAnswer: 'la mezquita',
    hint: 'Mosque - Islamic place of worship, Córdoba Mosque famous in Spain',
    points: 10,
    category: 'directions',
    difficulty: 'medium',
  },
  {
    id: 'directions_046',
    emoji: '🏛️',
    question: '¿Qué templo antiguo tiene columnas?',
    translation: 'What ancient temple has columns?',
    options: ['el templo', 'el santuario', 'el lugar de culto'],
    correctAnswer: 'el templo',
    hint: 'Temple - ancient religious building, from Latin "templum" (sacred space)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_047',
    emoji: '🌆',
    question: '¿Qué es el centro de la ciudad?',
    translation: 'What is the center of the city?',
    options: ['el centro', 'el centro histórico', 'el downtown'],
    correctAnswer: 'el centro',
    hint: 'Downtown - "centro histórico" is historic center, main business area',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_048',
    emoji: '🏘️',
    question: '¿Qué área está fuera del centro?',
    translation: 'What area is outside the center?',
    options: ['el suburbio', 'las afueras', 'la periferia'],
    correctAnswer: 'el suburbio',
    hint: 'Suburb - residential area outside center, "afueras" also used',
    points: 10,
    category: 'directions',
    difficulty: 'medium',
  },
  {
    id: 'directions_049',
    emoji: '🏞️',
    question: '¿Qué área tiene naturaleza?',
    translation: 'What area has nature?',
    options: ['el campo', 'la campiña', 'el área rural'],
    correctAnswer: 'el campo',
    hint: 'Countryside - rural area, from Latin "campus" (field)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
  {
    id: 'directions_050',
    emoji: '🏙️',
    question: '¿Qué lugar tiene muchos edificios?',
    translation: 'What place has many buildings?',
    options: ['la ciudad', 'la urbe', 'el área urbana'],
    correctAnswer: 'la ciudad',
    hint: 'City - urban area with tall buildings, from Latin "civitas" (citizenship)',
    points: 5,
    category: 'directions',
    difficulty: 'easy',
  },
];
