/**
 * EMERGENCIES Category Questions
 * Category: emergencies
 */

export const emergenciesQuestions = [
{
    id: 'emergencies_001',
    emoji: '🚑',
    question: '¿Qué vehículo lleva a los enfermos al hospital?',
    options: ['la ambulancia', 'el vehículo de emergencia', 'el coche de urgencias'],
    correctAnswer: 'la ambulancia',
    hint: 'Ambulance - emergency medical vehicle, from Latin "ambulare" (to walk)',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_002',
    emoji: '🚨',
    question: '¿Qué situación requiere ayuda inmediata?',
    options: ['la emergencia', 'la urgencia', 'la crisis'],
    correctAnswer: 'la emergencia',
    hint: 'Emergency - urgent situation requiring immediate action, dial 112 (Europe) or 911 (Americas)',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_003',
    emoji: '👮',
    question: '¿Quién es?',
    options: ['el policía', 'el agente', 'el oficial'],
    correctAnswer: 'el policía',
    hint: 'Police officer - "la policía" is the force, maintains order and safety',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_004',
    emoji: '🚒',
    question: '¿Qué vehículo apaga incendios?',
    options: ['el camión de bomberos', 'el carro de bomberos', 'la autobomba'],
    correctAnswer: 'el camión de bomberos',
    hint: 'Fire truck - carries water and equipment, "bomberos" from "bomba" (pump)',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_005',
    emoji: '🏥',
    question: '¿Dónde vas en una emergencia?',
    options: ['el hospital', 'el centro médico', 'el centro de salud'],
    correctAnswer: 'el hospital',
    hint: 'Hospital - emergency medical facility, "sala de urgencias" is ER',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_006',
    emoji: '👨‍⚕️',
    question: '¿Quién es?',
    options: ['el doctor', 'el médico', 'el facultativo'],
    correctAnswer: 'el doctor',
    hint: 'Doctor - medical physician, "médico" also used, from Latin "docere" (to teach)',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_007',
    emoji: '💊',
    question: '¿Qué tomas cuando estás enfermo?',
    options: ['la medicina', 'el medicamento', 'el remedio'],
    correctAnswer: 'la medicina',
    hint: 'Medicine - drug for treatment, "medicamento" more formal, "remedio" for remedy',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_008',
    emoji: '🤒',
    question: '¿Cómo está la persona?',
    options: ['enferma', 'mala', 'indispuesta'],
    correctAnswer: 'enferma',
    hint: 'Sick - ill with disease, "enfermo/a" from Latin "infirmus" (not firm/weak)',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_009',
    emoji: '🤕',
    question: '¿Qué tiene la persona?',
    options: ['la herida', 'la lesión', 'el traumatismo'],
    correctAnswer: 'la herida',
    hint: 'Wound - injury breaking skin, from Latin "ferire" (to strike)',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_010',
    emoji: '🩹',
    question: '¿Con qué cubres una herida?',
    options: ['el vendaje', 'la venda', 'el apósito'],
    correctAnswer: 'el vendaje',
    hint: 'Bandage - wraps wound, "venda" is the strip material itself',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_011',
    emoji: '💉',
    question: '¿Qué te ponen con una aguja?',
    options: ['la inyección', 'la vacuna', 'la jeringa'],
    correctAnswer: 'la inyección',
    hint: 'Injection - shot with needle, "vacuna" is vaccine type',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_012',
    emoji: '🌡️',
    question: '¿Con qué mides la fiebre?',
    options: ['el termómetro', 'el medidor de temperatura', 'el termómetro clínico'],
    correctAnswer: 'el termómetro',
    hint: 'Thermometer - measures temperature, from Greek "therme" (heat) + "metron" (measure)',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_013',
    emoji: '😷',
    question: '¿Qué usa la persona?',
    options: ['la mascarilla', 'el cubrebocas', 'el tapabocas'],
    correctAnswer: 'la mascarilla',
    hint: 'Face mask - prevents disease spread, "cubrebocas" or "tapabocas" in Latin America',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_014',
    emoji: '🩺',
    question: '¿Con qué escucha el doctor tu corazón?',
    options: ['el estetoscopio', 'el fonendoscopio', 'el estetoscope'],
    correctAnswer: 'el estetoscopio',
    hint: 'Stethoscope - listens to heart/lungs, from Greek "stethos" (chest) + "skopein" (examine)',
    points: 15,
    category: 'emergencies',
    difficulty: 'hard',
  },
  {
    id: 'emergencies_015',
    emoji: '🧴',
    question: '¿Qué usas para matar gérmenes?',
    options: ['el desinfectante', 'el antiséptico', 'el sanitizante'],
    correctAnswer: 'el desinfectante',
    hint: 'Disinfectant - kills germs, alcohol gel common type',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },

  // Emergency Situations & Responses (15 questions)
  {
    id: 'emergencies_016',
    emoji: '📞',
    question: '¿Qué número llamas en emergencia?',
    options: ['el número de emergencia', 'el 112', 'el 911'],
    correctAnswer: 'el número de emergencia',
    hint: 'Emergency number - 112 in Spain/Europe, 911 in Mexico/Americas, always free',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_017',
    emoji: '🚨',
    question: '¿Qué llamas si hay un crimen?',
    options: ['la policía', 'la poli', 'las autoridades'],
    correctAnswer: 'la policía',
    hint: 'Police - for crime and public safety, "la poli" colloquial',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_018',
    emoji: '🔥',
    question: '¿Qué llamas si hay fuego?',
    options: ['los bomberos', 'el cuerpo de bomberos', 'los firefighters'],
    correctAnswer: 'los bomberos',
    hint: 'Firefighters - fight fires and rescue, "cuerpo de bomberos" is fire department',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_019',
    emoji: '🤕',
    question: '¿Qué llamas si alguien está herido?',
    options: ['la ambulancia', 'el servicio médico', 'la emergencia médica'],
    correctAnswer: 'la ambulancia',
    hint: 'Ambulance - for medical emergencies, paramedics provide first aid',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_020',
    emoji: '🏥',
    question: '¿A dónde te llevan en ambulancia?',
    options: ['el hospital', 'urgencias', 'emergencias'],
    correctAnswer: 'el hospital',
    hint: 'Hospital - trauma center, "urgencias" or "emergencias" is emergency department',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_021',
    emoji: '🆘',
    question: '¿Qué gritas cuando necesitas ayuda?',
    options: ['ayuda', 'socorro', 'auxilio'],
    correctAnswer: 'ayuda',
    hint: 'Help - "¡socorro!" also means help, from Latin "adjutare" (to assist)',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_022',
    emoji: '🚪',
    question: '¿Por dónde sales rápido?',
    options: ['la salida de emergencia', 'la salida de urgencia', 'la salida de seguridad'],
    correctAnswer: 'la salida de emergencia',
    hint: 'Emergency exit - marked with green signs, always keep clear',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_023',
    emoji: '🧯',
    question: '¿Qué usas para apagar fuego?',
    options: ['el extintor', 'el extinguidor', 'el matafuegos'],
    correctAnswer: 'el extintor',
    hint: 'Fire extinguisher - red cylinder, "extinguidor" also used in Latin America',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_024',
    emoji: '🚨',
    question: '¿Qué suena cuando hay peligro?',
    options: ['la alarma', 'la sirena', 'el aviso'],
    correctAnswer: 'la alarma',
    hint: 'Alarm - warning sound, from Italian "allarme" (to arms!)',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_025',
    emoji: '⚠️',
    question: '¿Qué símbolo indica riesgo?',
    options: ['el peligro', 'el riesgo', 'la advertencia'],
    correctAnswer: 'el peligro',
    hint: 'Danger - warning sign, "riesgo" is risk, triangle symbol universal',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_026',
    emoji: '🆘',
    question: '¿Qué necesitas urgentemente?',
    options: ['la ayuda urgente', 'el socorro', 'la asistencia inmediata'],
    correctAnswer: 'la ayuda urgente',
    hint: 'Urgent help - "socorro" for distress call, SOS international signal',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_027',
    emoji: '🩹',
    question: '¿Qué haces con una herida?',
    options: ['curar', 'tratar', 'atender'],
    correctAnswer: 'curar',
    hint: 'Treat/heal - "curar" also means cure, apply first aid to wounds',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_028',
    emoji: '🚑',
    question: '¿Dónde va el paciente en ambulancia?',
    options: ['la sala de emergencias', 'urgencias', 'el departamento de emergencias'],
    correctAnswer: 'la sala de emergencias',
    hint: 'Emergency room - ER/ED, "urgencias" in Spain, critical care department',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_029',
    emoji: '🧑‍⚕️',
    question: '¿Quién te atiende en emergencia?',
    options: ['el médico de urgencias', 'el doctor de emergencias', 'el médico de emergencias'],
    correctAnswer: 'el médico de urgencias',
    hint: 'Emergency doctor - ER physician, specialized in urgent care',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_030',
    emoji: '🚨',
    question: '¿Qué situación requiere acción inmediata?',
    options: ['la emergencia', 'la urgencia', 'la crisis'],
    correctAnswer: 'la emergencia',
    hint: 'Emergency - urgent crisis, from Latin "emergere" (to arise suddenly)',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },

  // Medical Symptoms & Conditions (20 questions)
  {
    id: 'emergencies_031',
    emoji: '🤒',
    question: '¿Qué tienes cuando hay fiebre?',
    options: ['la temperatura alta', 'la fiebre', 'la calentura'],
    correctAnswer: 'la temperatura alta',
    hint: 'High temperature - fever over 38°C/100.4°F, "calentura" colloquial',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_032',
    emoji: '🤧',
    question: '¿Qué haces cuando estás resfriado?',
    options: ['estornudar', 'toser', 'sonarse la nariz'],
    correctAnswer: 'estornudar',
    hint: 'Sneeze - from cold or allergies, "catarro" is head cold',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_033',
    emoji: '😷',
    question: '¿Qué usas para no contagiar?',
    options: ['la mascarilla', 'el cubrebocas', 'el tapabocas'],
    correctAnswer: 'la mascarilla',
    hint: 'Face mask - prevents contagion, became essential during COVID-19',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_034',
    emoji: '🤮',
    question: '¿Qué haces cuando tienes náuseas?',
    options: ['vomitar', 'devolver', 'arrojar'],
    correctAnswer: 'vomitar',
    hint: 'Vomit - "devolver" also used, náusea is nausea feeling',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_035',
    emoji: '🤕',
    question: '¿Qué tienes cuando te duele?',
    options: ['el dolor', 'la molestia', 'el sufrimiento'],
    correctAnswer: 'el dolor',
    hint: 'Pain - "doler" is to hurt, from Latin "dolere" (to suffer)',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_036',
    emoji: '🩹',
    question: '¿Qué tienes cuando te cortas?',
    options: ['la herida', 'la cortada', 'el raspón'],
    correctAnswer: 'la herida',
    hint: 'Wound - "cortada" is cut, "raspón" is scrape',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_037',
    emoji: '💔',
    question: '¿Qué duele cuando hay infarto?',
    options: ['el corazón', 'el pecho', 'el tórax'],
    correctAnswer: 'el corazón',
    hint: 'Heart - heart attack is "infarto al miocardio", major emergency',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_038',
    emoji: '🧠',
    question: '¿Qué parte duele en dolor de cabeza?',
    options: ['la cabeza', 'el cráneo', 'la testa'],
    correctAnswer: 'la cabeza',
    hint: 'Head - headache is "dolor de cabeza", migraine is "migraña"',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_039',
    emoji: '🦷',
    question: '¿Qué te duele cuando vas al dentista?',
    options: ['el diente', 'la muela', 'el colmillo'],
    correctAnswer: 'el diente',
    hint: 'Tooth - toothache is "dolor de muelas", "muela" is molar',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_040',
    emoji: '👂',
    question: '¿Qué órgano te duele en otitis?',
    options: ['el oído', 'la oreja', 'el oído interno'],
    correctAnswer: 'el oído',
    hint: 'Ear - ear infection is "otitis", "oreja" is outer ear',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_041',
    emoji: '👃',
    question: '¿Por dónde respiras?',
    options: ['la nariz', 'las fosas nasales', 'el tabique nasal'],
    correctAnswer: 'la nariz',
    hint: 'Nose - for breathing and smell, from Latin "nasus"',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_042',
    emoji: '🫁',
    question: '¿Qué órgano te ayuda a respirar?',
    options: ['los pulmones', 'los órganos respiratorios', 'el sistema respiratorio'],
    correctAnswer: 'los pulmones',
    hint: 'Lungs - two organs for breathing oxygen, from Latin "pulmo"',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_043',
    emoji: '🤰',
    question: '¿Qué condición tiene una mujer embarazada?',
    options: ['el embarazo', 'la gestación', 'la preñez'],
    correctAnswer: 'el embarazo',
    hint: 'Pregnancy - carrying baby, from "embarazar" (to encumber)',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_044',
    emoji: '🩸',
    question: '¿Qué líquido sale de una herida?',
    options: ['la sangre', 'el fluido sanguíneo', 'el líquido vital'],
    correctAnswer: 'la sangre',
    hint: 'Blood - vital fluid, from Latin "sanguis", type O+ most common',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_045',
    emoji: '💊',
    question: '¿Qué tomas cuando estás enfermo?',
    options: ['la medicina', 'el medicamento', 'el remedio'],
    correctAnswer: 'la medicina',
    hint: 'Medicine - treatment drug, "pastilla" is pill, "jarabe" is syrup',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_046',
    emoji: '💉',
    question: '¿Qué te ponen con aguja?',
    options: ['la inyección', 'la vacuna', 'el suero'],
    correctAnswer: 'la inyección',
    hint: 'Injection - shot with syringe, delivers medicine into muscle/vein',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_047',
    emoji: '🌡️',
    question: '¿Con qué mides la fiebre?',
    options: ['el termómetro', 'el medidor de temperatura', 'el termómetro digital'],
    correctAnswer: 'el termómetro',
    hint: 'Thermometer - measures body temperature, digital now common',
    points: 5,
    category: 'emergencies',
    difficulty: 'easy',
  },
  {
    id: 'emergencies_048',
    emoji: '🦴',
    question: '¿Qué se rompe en una fractura?',
    options: ['el hueso', 'el esqueleto', 'la estructura ósea'],
    correctAnswer: 'el hueso',
    hint: 'Bone - skeleton part, "fractura" is break, needs cast to heal',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_049',
    emoji: '🩼',
    question: '¿Qué usas con hueso roto?',
    options: ['las muletas', 'los bastones', 'las béquelas'],
    correctAnswer: 'las muletas',
    hint: 'Crutches - support walking with leg injury, "bastones" also used',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
  {
    id: 'emergencies_050',
    emoji: '🚑',
    question: '¿Qué personal te ayuda en emergencia?',
    options: ['el paramédico', 'el técnico de emergencias', 'el EMT'],
    correctAnswer: 'el paramédico',
    hint: 'Paramedic - emergency medical technician, provides pre-hospital care',
    points: 10,
    category: 'emergencies',
    difficulty: 'medium',
  },
];
