/**
 * ENTERTAINMENT Category Questions
 * Category: entertainment
 */

export const entertainmentQuestions = [
{
    id: 'entertainment_001',
    emoji: 'cine.png',
    question: '¿Dónde vas a ver películas?',
    options: ['el cine', 'el teatro', 'el auditorio'],
    correctAnswer: 'el cine',
    hint: 'Movie theater - "cine" from cinema, watch films on big screen',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_002',
    emoji: 'cine al aire libre.png',
    question: '¿Dónde ves películas bajo las estrellas?',
    options: ['el cine al aire libre', 'el autocine', 'el cine exterior'],
    correctAnswer: 'el cine al aire libre',
    hint: 'Outdoor movies - watching films outside under the stars',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_003',
    emoji: '🎸',
    question: '¿Qué instrumento es este?',
    options: ['la guitarra', 'el bajo', 'el ukelele'],
    correctAnswer: 'la guitarra',
    hint: 'Guitar - stringed instrument, "guitarra" from Arabic "qitara", popular worldwide',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_004',
    emoji: '⚽',
    question: '¿Qué deporte es este?',
    options: ['el fútbol', 'el balompié', 'el soccer'],
    correctAnswer: 'el fútbol',
    hint: 'Soccer/football - world\'s most popular sport, "balompié" also used',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_005',
    emoji: 'parque de atracciones.png',
    question: '¿Dónde vas para montar montañas rusas?',
    options: ['el parque de atracciones', 'el parque temático', 'el parque de diversiones'],
    correctAnswer: 'el parque de atracciones',
    hint: 'Amusement park - place with roller coasters and rides for entertainment',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_006',
    emoji: '🎵',
    question: '¿Qué escuchas en tus auriculares?',
    options: ['la música', 'la melodía', 'la canción'],
    correctAnswer: 'la música',
    hint: 'Music - universal language, "música" from Greek "mousike" (art of Muses)',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_007',
    emoji: '📺',
    question: '¿En qué aparato ves tus programas favoritos?',
    options: ['la televisión', 'la tele', 'el televisor'],
    correctAnswer: 'la televisión',
    hint: 'Television - "tele" (far) + "visión" (seeing), broadcast entertainment',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_008',
    emoji: '🎭',
    question: '¿Dónde ves obras con actores en vivo?',
    options: ['el teatro', 'la obra de teatro', 'el drama'],
    correctAnswer: 'el teatro',
    hint: 'Theater - live performances with actors, "teatro" from Greek "theatron"',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_010',
    emoji: '🎨',
    question: '¿Qué actividad es esta?',
    options: ['la pintura', 'el dibujo', 'el arte'],
    correctAnswer: 'la pintura',
    hint: 'Painting - visual art with colors, "pintar" to paint on canvas',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_011',
    emoji: '🎹',
    question: '¿Qué instrumento es este?',
    options: ['el piano', 'el teclado', 'el órgano'],
    correctAnswer: 'el piano',
    hint: 'Piano - keyboard instrument, "piano" means soft in Italian (original name)',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_012',
    emoji: '🎤',
    question: '¿Qué usas para amplificar tu voz?',
    options: ['el micrófono', 'el micro', 'el amplificador'],
    correctAnswer: 'el micrófono',
    hint: 'Microphone - amplifies voice, "micro" (small) + "phone" (sound)',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_013',
    emoji: 'zoológico.png',
    question: '¿Dónde vas para ver animales exóticos?',
    options: ['el zoológico', 'el zoo', 'el parque zoológico'],
    correctAnswer: 'el zoológico',
    hint: 'Zoo - place where exotic animals are kept for public viewing',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_014',
    emoji: '🎯',
    question: '¿Qué juego es este?',
    options: ['los dardos', 'el tiro al blanco', 'la diana'],
    correctAnswer: 'los dardos',
    hint: 'Darts - throwing game aiming at circular board, pub game',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_015',
    emoji: '🎲',
    question: '¿Qué son estos?',
    options: ['los dados', 'los cubos', 'las fichas'],
    correctAnswer: 'los dados',
    hint: 'Dice - cubes with dots 1-6, used in many board games',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_017',
    emoji: '🪩',
    question: '¿Dónde bailas en un resort por la noche?',
    options: ['la discoteca', 'la piscina', 'el restaurante'],
    correctAnswer: 'la discoteca',
    hint: 'Dance club/Disco - nightclub at resort where people dance to music',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_019',
    emoji: 'una celebridad musical.png',
    question: '¿Cómo se llama una persona famosa en la música?',
    options: ['una celebridad musical', 'un músico callejero', 'un estudiante'],
    correctAnswer: 'una celebridad musical',
    hint: 'Musical celebrity - famous person in music, well-known artist or performer',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_020',
    emoji: '🎺',
    question: '¿Qué instrumento es este?',
    options: ['la trompeta', 'el trombón', 'la corneta'],
    correctAnswer: 'la trompeta',
    hint: 'Trumpet - brass instrument, bright sound, jazz and classical music',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },

  // More Musical Instruments (20 questions)
  {
    id: 'entertainment_021',
    emoji: 'guitarra.png',
    question: '¿Qué instrumento de cuerdas se toca con los dedos?',
    options: ['la guitarra', 'el bajo', 'el ukelele'],
    correctAnswer: 'la guitarra',
    hint: 'Has six strings and is very popular',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_022',
    emoji: '🎹',
    question: '¿Qué instrumento tiene teclas blancas y negras?',
    options: ['el piano', 'el teclado', 'el órgano'],
    correctAnswer: 'el piano',
    hint: 'Large instrument with 88 keys',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_023',
    emoji: '🥁',
    question: '¿Qué instrumento golpeas con palillos?',
    options: ['la batería', 'los tambores', 'la percusión'],
    correctAnswer: 'la batería',
    hint: 'Drums - "batería" is drum kit, rhythm foundation in bands',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_024',
    emoji: '🎻',
    question: '¿Qué instrumento se toca con arco?',
    options: ['el violín', 'la viola', 'el violonchelo'],
    correctAnswer: 'el violín',
    hint: 'Violin - bow drawn across strings, classical and folk music',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_025',
    emoji: '🎷',
    question: '¿Qué instrumento de jazz es dorado?',
    options: ['el saxofón', 'el clarinete', 'la flauta'],
    correctAnswer: 'el saxofón',
    hint: 'Saxophone - invented 1840s by Adolphe Sax, essential in jazz',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_026',
    emoji: '🪕',
    question: '¿Qué instrumento de cuerdas es redondo?',
    options: ['el banjo', 'la guitarra', 'el ukelele'],
    correctAnswer: 'el banjo',
    hint: 'Banjo - round body, American folk and bluegrass music instrument',
    points: 15,
    category: 'entertainment',
    difficulty: 'hard',
  },
  {
    id: 'entertainment_027',
    emoji: '🪘',
    question: '¿Qué tambor circular tocas con las manos?',
    options: ['el tambor', 'el bongó', 'la conga'],
    correctAnswer: 'el tambor',
    hint: 'Drum - percussion instrument, "tambor" generic for hand drums',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_028',
    emoji: '🎤',
    question: '¿Qué usas para cantar en público?',
    options: ['el micrófono', 'el micro', 'el amplificador'],
    correctAnswer: 'el micrófono',
    hint: 'Microphone for singing - "micro" common abbreviation in Spanish',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_029',
    emoji: '🎧',
    question: '¿Qué te pones en las orejas para escuchar música?',
    options: ['los audífonos', 'los auriculares', 'los cascos'],
    correctAnswer: 'los audífonos',
    hint: 'Headphones - "auriculares" in Spain, "audífonos" in Latin America',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_030',
    emoji: '🔊',
    question: '¿Qué hace que el sonido sea más fuerte?',
    options: ['el altavoz', 'la bocina', 'el parlante'],
    correctAnswer: 'el altavoz',
    hint: 'Speaker - amplifies sound for everyone, "bocina" also common',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_031',
    emoji: '🎵',
    question: '¿Qué símbolo representa la música?',
    options: ['la nota musical', 'la nota', 'el tono'],
    correctAnswer: 'la nota musical',
    hint: 'Musical note - written symbols for different pitches and durations',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_032',
    emoji: '🎶',
    question: '¿Qué haces cuando escuchas música alegre?',
    options: ['cantar', 'tararear', 'vocalizar'],
    correctAnswer: 'cantar',
    hint: 'To sing - "cantar" from Latin "cantare", expressing music with voice',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_033',
    emoji: '🎼',
    question: '¿Dónde están escritas las notas musicales?',
    options: ['la partitura', 'la música escrita', 'el pentagrama'],
    correctAnswer: 'la partitura',
    hint: 'Sheet music - "partitura" shows notes on staff lines for musicians',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_034',
    emoji: '🎙️',
    question: '¿Qué micrófono usan en radio y podcasts?',
    options: ['el micrófono de estudio', 'el micrófono profesional', 'el micrófono condensador'],
    correctAnswer: 'el micrófono de estudio',
    hint: 'Studio microphone - professional quality for broadcasting and recording',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_035',
    emoji: '🥻',
    question: '¿Qué música latina tiene ritmo rápido?',
    options: ['la salsa', 'el merengue', 'la cumbia'],
    correctAnswer: 'la salsa',
    hint: 'Salsa music - energetic Latin dance music from Caribbean, "spicy" rhythm',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_036',
    emoji: '🪇',
    question: '¿Qué instrumento sacudes para hacer sonido?',
    options: ['las maracas', 'las castañuelas', 'la pandereta'],
    correctAnswer: 'las maracas',
    hint: 'Maracas - Latin percussion, shake rattles filled with seeds or beads',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_037',
    emoji: '🪈',
    question: '¿Qué instrumento de viento es pequeño y sencillo?',
    options: ['la flauta', 'el flautín', 'el píccolo'],
    correctAnswer: 'la flauta',
    hint: 'Flute - oldest instrument, blow across hole, sweet high sound',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_038',
    emoji: '🎺',
    question: '¿Qué instrumento de metal soplas?',
    options: ['la trompeta', 'el trombón', 'la tuba'],
    correctAnswer: 'la trompeta',
    hint: 'Trumpet - brass with three valves, fanfares and jazz solos',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_039',
    emoji: '🎻',
    question: '¿Cuántas cuerdas tiene un violín?',
    options: ['cuatro', 'cinco', 'seis'],
    correctAnswer: 'cuatro',
    hint: 'Four strings - tuned G-D-A-E, same as violin family instruments',
    points: 15,
    category: 'entertainment',
    difficulty: 'hard',
  },
  {
    id: 'entertainment_040',
    emoji: '🎸',
    question: '¿Qué guitarra se conecta a un amplificador?',
    options: ['la guitarra eléctrica', 'el bajo eléctrico', 'la guitarra amplificada'],
    correctAnswer: 'la guitarra eléctrica',
    hint: 'Electric guitar - invented 1930s, rock and blues essential',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },

  // Sports & Activities (30 questions)
  {
    id: 'entertainment_041',
    emoji: 'minigolf.png',
    question: '¿Qué deporte juegas con obstáculos pequeños?',
    options: ['el minigolf', 'el golf en miniatura', 'el golf pequeño'],
    correctAnswer: 'el minigolf',
    hint: 'Miniature golf - fun putting game with creative obstacles and themes',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_042',
    emoji: '🏀',
    question: '¿Qué deporte metes la pelota en un aro?',
    options: ['el baloncesto', 'el básquetbol', 'el basquetbol'],
    correctAnswer: 'el baloncesto',
    hint: 'Basketball - shoot ball through elevated hoop, invented 1891',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_043',
    emoji: '🎾',
    question: '¿Qué deporte se juega con raqueta?',
    options: ['el tenis', 'el bádminton', 'el ping pong'],
    correctAnswer: 'el tenis',
    hint: 'Tennis - hit ball over net with racket, singles or doubles',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_044',
    emoji: '⚾',
    question: '¿Qué deporte usas un bate?',
    options: ['el béisbol', 'el sófbol', 'el cricket'],
    correctAnswer: 'el béisbol',
    hint: 'Baseball - hit ball with bat, run bases, America\'s pastime',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_045',
    emoji: '🏐',
    question: '¿Qué deporte golpeas la pelota sobre una red?',
    options: ['el voleibol', 'el vóleibol', 'el volibol'],
    correctAnswer: 'el voleibol',
    hint: 'Volleyball - spike ball over net, beach or indoor version',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_046',
    emoji: '🏈',
    question: '¿Qué deporte americano es físico?',
    options: ['el fútbol americano', 'el fútbol gridiron', 'el fútbol tackle'],
    correctAnswer: 'el fútbol americano',
    hint: 'American football - tackle sport with helmets and pads, oval ball',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_047',
    emoji: '🏉',
    question: '¿Qué deporte similar al fútbol americano se juega sin protección?',
    options: ['el rugby', 'el rugby union', 'el rugby league'],
    correctAnswer: 'el rugby',
    hint: 'Rugby - like American football but no helmets, originated in England',
    points: 15,
    category: 'entertainment',
    difficulty: 'hard',
  },
  {
    id: 'entertainment_048',
    emoji: '🏏',
    question: '¿Qué deporte británico usa bate plano?',
    options: ['el cricket', 'el críquet', 'el rounders'],
    correctAnswer: 'el cricket',
    hint: 'Cricket - British bat-ball sport, flat bat, popular in Commonwealth',
    points: 15,
    category: 'entertainment',
    difficulty: 'hard',
  },
  {
    id: 'entertainment_049',
    emoji: '🏒',
    question: '¿Qué deporte se juega en hielo?',
    options: ['el hockey', 'el hockey sobre hielo', 'el hockey de campo'],
    correctAnswer: 'el hockey',
    hint: 'Ice hockey - fast skating sport with puck, popular in Canada',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_050',
    emoji: '🏓',
    question: '¿Qué deporte de mesa usa paletas pequeñas?',
    options: ['el ping pong', 'el tenis de mesa', 'el pimpón'],
    correctAnswer: 'el ping pong',
    hint: 'Table tennis - "ping pong" from sound, fast reflexes needed',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_051',
    emoji: '🏸',
    question: '¿Qué deporte golpeas un volante con raqueta?',
    options: ['el bádminton', 'el badminton', 'el volante'],
    correctAnswer: 'el bádminton',
    hint: 'Badminton - hit shuttlecock over net, fastest racket sport',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_052',
    emoji: '🥊',
    question: '¿Qué deporte de combate usa guantes?',
    options: ['el boxeo', 'el pugilismo', 'el box'],
    correctAnswer: 'el boxeo',
    hint: 'Boxing - punch with gloved fists, combat sport with rounds',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_053',
    emoji: '🥋',
    question: '¿Qué arte marcial usa cinturones de colores?',
    options: ['el karate', 'el judo', 'el taekwondo'],
    correctAnswer: 'el karate',
    hint: 'Karate - Japanese martial art, belt colors show skill level',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_054',
    emoji: '🤸',
    question: '¿Qué deporte incluye volteretas y acrobacias?',
    options: ['la gimnasia', 'la gimnasia artística', 'la acrobacia'],
    correctAnswer: 'la gimnasia',
    hint: 'Gymnastics - tumbling, flexibility, balance beam, floor routines',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_056',
    emoji: '🚴',
    question: '¿Qué deporte haces en bicicleta?',
    options: ['el ciclismo', 'la bicicleta', 'el pedaleo'],
    correctAnswer: 'el ciclismo',
    hint: 'Cycling - bike racing, Tour de France famous, road or mountain',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_057',
    emoji: '🏃',
    question: '¿Qué haces en una maratón?',
    options: ['correr', 'trotar', 'esprintar'],
    correctAnswer: 'correr',
    hint: 'Running - marathon is 42.195km, long distance endurance race',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_058',
    emoji: '⛷️',
    question: '¿Qué deporte haces en la nieve?',
    options: ['esquiar', 'el esquí', 'esquí alpino'],
    correctAnswer: 'esquiar',
    hint: 'Skiing - glide on snow with skis, downhill or cross-country',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_059',
    emoji: '🏂',
    question: '¿Qué deporte de nieve usas una tabla?',
    options: ['el snowboard', 'la tabla de nieve', 'el surf de nieve'],
    correctAnswer: 'el snowboard',
    hint: 'Snowboarding - single board for both feet, winter sport since 1960s',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_060',
    emoji: '⛸️',
    question: '¿Qué haces con patines en hielo?',
    options: ['patinar', 'el patinaje', 'deslizarse'],
    correctAnswer: 'patinar',
    hint: 'Ice skating - glide on frozen surface, figure skating or hockey',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_061',
    emoji: '🛹',
    question: '¿Qué tabla usas para hacer trucos en la calle?',
    options: ['la patineta', 'el monopatín', 'el skateboard'],
    correctAnswer: 'la patineta',
    hint: 'Skateboard - wheeled board for tricks, "monopatín" in some regions',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_063',
    emoji: '🤽',
    question: '¿Qué deporte de equipo se juega en piscina?',
    options: ['el waterpolo', 'el polo acuático', 'el water polo'],
    correctAnswer: 'el waterpolo',
    hint: 'Water polo - team handball in pool, treading water while playing',
    points: 15,
    category: 'entertainment',
    difficulty: 'hard',
  },
  {
    id: 'entertainment_064',
    emoji: '🏋️',
    question: '¿Qué deporte levantas pesas?',
    options: ['el levantamiento de pesas', 'el halterofilia', 'las pesas'],
    correctAnswer: 'el levantamiento de pesas',
    hint: 'Weightlifting - Olympic sport, lift barbell overhead, strength training',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_065',
    emoji: '🧘',
    question: '¿Qué ejercicio de meditación es tranquilo?',
    options: ['el yoga', 'la meditación', 'el pilates'],
    correctAnswer: 'el yoga',
    hint: 'Yoga - ancient Indian practice, stretching and meditation, Sanskrit origin',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_066',
    emoji: '🏆',
    question: '¿Qué recibes cuando ganas una competencia?',
    options: ['el trofeo', 'la copa', 'el premio'],
    correctAnswer: 'el trofeo',
    hint: 'Trophy - award for victory, often cup or statue, "copa" for cup',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_067',
    emoji: '🥇',
    question: '¿Qué medalla es para el primer lugar?',
    options: ['el oro', 'la medalla de oro', 'la dorada'],
    correctAnswer: 'el oro',
    hint: 'Gold medal - first place in Olympics and competitions, most valuable',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_068',
    emoji: '🥈',
    question: '¿Qué medalla es para el segundo lugar?',
    options: ['la plata', 'la medalla de plata', 'la plateada'],
    correctAnswer: 'la plata',
    hint: 'Silver medal - second place award, "plata" is also the metal',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_069',
    emoji: '🥉',
    question: '¿Qué medalla es para el tercer lugar?',
    options: ['el bronce', 'la medalla de bronce', 'la bronceada'],
    correctAnswer: 'el bronce',
    hint: 'Bronze medal - third place, "bronce" is copper-tin alloy',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_070',
    emoji: '🏟️',
    question: '¿Dónde se juegan partidos de fútbol grandes?',
    options: ['el estadio', 'el campo', 'la cancha'],
    correctAnswer: 'el estadio',
    hint: 'Stadium - large sports venue, Camp Nou in Barcelona seats 99,000',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },

  // Movies & Cinema (25 questions)
  {
    id: 'entertainment_071',
    emoji: 'castillo inflable.png',
    question: '¿Dónde saltan los niños en fiestas?',
    options: ['el castillo inflable', 'el brincolín', 'la casa inflable'],
    correctAnswer: 'el castillo inflable',
    hint: 'Bouncy castle - inflatable play structure popular at children\'s parties',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_072',
    emoji: 'cámara.png',
    question: '¿Con qué grabas una película?',
    options: ['la cámara', 'la cámara de cine', 'la videocámara'],
    correctAnswer: 'la cámara',
    hint: 'Camera - "cámara" from Latin "camera obscura", records video',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_073',
    emoji: '📽️',
    question: '¿Qué máquina proyecta la película en el cine?',
    options: ['el proyector', 'el proyector de cine', 'la proyección'],
    correctAnswer: 'el proyector',
    hint: 'Projector - throws light/image onto large screen, now digital',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_074',
    emoji: '🎞️',
    question: '¿En qué se grababan las películas antiguas?',
    options: ['la película', 'el filme', 'el rollo'],
    correctAnswer: 'la película',
    hint: 'Film reel - "película" means both film and movie, celluloid strips',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_075',
    emoji: '🎭',
    question: '¿Dónde se presentan obras de teatro?',
    options: ['el teatro', 'el auditorio', 'la sala'],
    correctAnswer: 'el teatro',
    hint: 'Theater - live stage performances, "teatro" from Greek "theatron"',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_076',
    emoji: '🎪',
    question: '¿Qué espectáculo tiene payasos y acróbatas?',
    options: ['el circo', 'el carnaval', 'la feria'],
    correctAnswer: 'el circo',
    hint: 'Circus - traveling show, "circo" from Latin "circus" (ring)',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_077',
    emoji: 'pintar.png',
    question: '¿Qué haces cuando creas imágenes con colores?',
    options: ['pintar', 'dibujar', 'colorear'],
    correctAnswer: 'pintar',
    hint: 'Painting - "pintar" creates art with brush and colors, fine art',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_078',
    emoji: '🖼️',
    question: '¿Dónde ves obras de arte?',
    options: ['el museo', 'la galería', 'la exposición'],
    correctAnswer: 'el museo',
    hint: 'Museum - displays art and history, Prado in Madrid world-famous',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_079',
    emoji: '🎟️',
    question: '¿Qué compras para entrar al cine?',
    options: ['el boleto', 'la entrada', 'el ticket'],
    correctAnswer: 'el boleto',
    hint: 'Ticket - "boleto" in Latin America, "entrada" in Spain for admission',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_081',
    emoji: 'comedia.png',
    question: '¿Qué película te hace reír?',
    options: ['la comedia', 'la película cómica', 'la película graciosa'],
    correctAnswer: 'la comedia',
    hint: 'Comedy - funny genre, from Greek "komodia", makes you laugh',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_082',
    emoji: '😱',
    question: '¿Qué película te da miedo?',
    options: ['el terror', 'el horror', 'la película de miedo'],
    correctAnswer: 'el terror',
    hint: 'Horror - scary movies, "película de terror" frightens audience',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_083',
    emoji: '💕',
    question: '¿Qué película es sobre amor?',
    options: ['el romance', 'la película romántica', 'el amor'],
    correctAnswer: 'el romance',
    hint: 'Romance - love story genre, emotional relationships and passion',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_084',
    emoji: '💥',
    question: '¿Qué película tiene explosiones y peleas?',
    options: ['la acción', 'la película de acción', 'la aventura'],
    correctAnswer: 'la acción',
    hint: 'Action - fast-paced with stunts, chases, explosions, and fights',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_085',
    emoji: '🚀',
    question: '¿Qué película es sobre el futuro o espacio?',
    options: ['la ciencia ficción', 'la ficción científica', 'la sci-fi'],
    correctAnswer: 'la ciencia ficción',
    hint: 'Science fiction - futuristic or space themes, "sci-fi" technology',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_086',
    emoji: 'documental.png',
    question: '¿Qué película cuenta una historia real?',
    options: ['el documental', 'el documento', 'el reportaje'],
    correctAnswer: 'el documental',
    hint: 'Documentary - non-fiction film showing real events and facts',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_087',
    emoji: 'animada.png',
    question: '¿Qué película está dibujada?',
    options: ['la animada', 'la película animada', 'la animación'],
    correctAnswer: 'la animada',
    hint: 'Animated - drawn or computer-generated, Disney and Pixar films',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_088',
    emoji: '🎭',
    question: '¿Qué persona interpreta un personaje en una película?',
    options: ['el actor', 'la actriz', 'el intérprete'],
    correctAnswer: 'el actor',
    hint: 'Actor - performs character roles, "actriz" for female actor',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_089',
    emoji: 'director.png',
    question: '¿Quién dirige una película?',
    options: ['el director', 'el realizador', 'el cineasta'],
    correctAnswer: 'el director',
    hint: 'Director - controls artistic vision, Pedro Almodóvar famous Spanish director',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_090',
    emoji: '📺',
    question: '¿Dónde ves programas y series?',
    options: ['la televisión', 'la tele', 'el televisor'],
    correctAnswer: 'la televisión',
    hint: 'Television - "tele" for short, broadcasts shows and news',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_091',
    emoji: '📻',
    question: '¿Dónde escuchas música y noticias sin pantalla?',
    options: ['la radio', 'la radioemisora', 'el radio'],
    correctAnswer: 'la radio',
    hint: 'Radio - audio-only broadcast, "emisora" is radio station',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_092',
    emoji: '🎮',
    question: '¿Qué dispositivo usas para jugar videojuegos?',
    options: ['la consola', 'la consola de juegos', 'el sistema de juegos'],
    correctAnswer: 'la consola',
    hint: 'Game console - PlayStation, Xbox, Nintendo Switch for gaming',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_093',
    emoji: '🕹️',
    question: '¿Qué usas para controlar videojuegos?',
    options: ['el control', 'el mando', 'el joystick'],
    correctAnswer: 'el control',
    hint: 'Game controller - "mando" in Spain, buttons and joysticks',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_094',
    emoji: '🎰',
    question: '¿Dónde juegan juegos de azar los adultos?',
    options: ['el casino', 'la casa de juegos', 'la sala de apuestas'],
    correctAnswer: 'el casino',
    hint: 'Casino - gambling establishment, slot machines and card games',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_095',
    emoji: '🎲',
    question: '¿Qué cubo lanzas en juegos de mesa?',
    options: ['el dado', 'los dados', 'el cubo'],
    correctAnswer: 'el dado',
    hint: 'Dice - cube with dots 1-6, "dados" is plural for multiple dice',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },

  // Hobbies & Leisure (25 questions)
  {
    id: 'entertainment_096',
    emoji: '📚',
    question: '¿Qué haces con un libro?',
    options: ['leer', 'la lectura', 'leyendo'],
    correctAnswer: 'leer',
    hint: 'Reading - "leer" means to read, essential for learning languages',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_097',
    emoji: '✍️',
    question: '¿Qué haces cuando creas un texto?',
    options: ['escribir', 'la escritura', 'redactar'],
    correctAnswer: 'escribir',
    hint: 'Writing - "escribir" creates text, from Latin "scribere"',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_098',
    emoji: '📖',
    question: '¿Dónde encuentras libros para leer gratis?',
    options: ['la biblioteca', 'la librería', 'la sala de lectura'],
    correctAnswer: 'la biblioteca',
    hint: 'Library - free book lending, from Greek "bibliotheke" (book repository)',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_099',
    emoji: '📰',
    question: '¿Qué lees para saber las noticias del día?',
    options: ['el periódico', 'el diario', 'la prensa'],
    correctAnswer: 'el periódico',
    hint: 'Newspaper - daily news publication, "diario" also means newspaper',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_100',
    emoji: '📕',
    question: '¿Qué libro cuenta una historia larga?',
    options: ['la novela', 'el libro', 'la obra'],
    correctAnswer: 'la novela',
    hint: 'Novel - long fictional story, Don Quixote famous Spanish novel',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_101',
    emoji: 'pincel.png',
    question: '¿Qué usas para pintar?',
    options: ['el pincel', 'la brocha', 'el cepillo'],
    correctAnswer: 'el pincel',
    hint: 'Paintbrush - tool with bristles for applying paint to canvas',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_102',
    emoji: '🖌️',
    question: '¿En qué superficie pintas un cuadro?',
    options: ['el lienzo', 'la tela', 'el canvas'],
    correctAnswer: 'el lienzo',
    hint: 'Canvas - stretched cloth surface for painting, used by artists',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_103',
    emoji: '🖍️',
    question: '¿Con qué dibujan los niños?',
    options: ['el crayón', 'la crayola', 'el color'],
    correctAnswer: 'el crayón',
    hint: 'Crayon - wax sticks in colors, "crayola" brand name commonly used',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_104',
    emoji: '✏️',
    question: '¿Qué usas para escribir y borrar?',
    options: ['el lápiz', 'el lapicero', 'el portaminas'],
    correctAnswer: 'el lápiz',
    hint: 'Pencil - graphite writing tool, erasable unlike pen ("pluma")',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_105',
    emoji: '📷',
    question: '¿Con qué tomas fotos?',
    options: ['la cámara', 'la cámara fotográfica', 'la fotografía'],
    correctAnswer: 'la cámara',
    hint: 'Camera - captures photos, now mostly digital instead of film',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_106',
    emoji: '🎣',
    question: '¿Qué hobby haces con caña en el río?',
    options: ['pescar', 'la pesca', 'ir de pesca'],
    correctAnswer: 'pescar',
    hint: 'Fishing - catching fish with rod and bait, popular leisure activity',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_107',
    emoji: '🏕️',
    question: '¿Qué haces cuando duermes en tienda en la naturaleza?',
    options: ['acampar', 'ir de camping', 'el campamento'],
    correctAnswer: 'acampar',
    hint: 'Camping - outdoor sleeping in tent, "campamento" is campsite',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_108',
    emoji: '🥾',
    question: '¿Qué actividad haces caminando en montañas?',
    options: ['el senderismo', 'el hiking', 'el trekking'],
    correctAnswer: 'el senderismo',
    hint: 'Hiking - walking trails in nature, "sendero" means path or trail',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_109',
    emoji: '🌱',
    question: '¿Qué hobby cultivas plantas?',
    options: ['la jardinería', 'el jardín', 'cultivar'],
    correctAnswer: 'la jardinería',
    hint: 'Gardening - growing plants and flowers, "jardín" is garden',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_110',
    emoji: '🧩',
    question: '¿Qué armas juntando piezas?',
    options: ['el rompecabezas', 'el puzle', 'el puzzle'],
    correctAnswer: 'el rompecabezas',
    hint: 'Puzzle - "rompecabezas" literally means "head breaker", jigsaw pieces',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_111',
    emoji: '🎯',
    question: '¿A qué le lanzas dardos?',
    options: ['la diana', 'el blanco', 'el objetivo'],
    correctAnswer: 'la diana',
    hint: 'Dartboard - circular target, bullseye in center worth most points',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_112',
    emoji: '🎳',
    question: '¿Qué derribas con la bola de bolos?',
    options: ['los pinos', 'las botellas', 'los palitroques'],
    correctAnswer: 'los pinos',
    hint: 'Bowling pins - ten pins arranged in triangle, knock down for strike',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_113',
    emoji: 'hacer malabares.png',
    question: '¿Qué haces cuando practicas malabarismo?',
    options: ['hacer malabares', 'malabarear', 'el malabarismo'],
    correctAnswer: 'hacer malabares',
    hint: 'Juggling - "malabarismo" is art of keeping objects in air',
    points: 15,
    category: 'entertainment',
    difficulty: 'hard',
  },
  {
    id: 'entertainment_114',
    emoji: '🪁',
    question: '¿Qué vuelas con viento usando un hilo?',
    options: ['la cometa', 'el papalote', 'el barrilete'],
    correctAnswer: 'la cometa',
    hint: 'Kite - "cometa" flies on string, "papalote" in Mexico',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_115',
    emoji: '🧶',
    question: '¿Qué haces con agujas e hilo?',
    options: ['tejer', 'el tejido', 'la costura'],
    correctAnswer: 'tejer',
    hint: 'Knitting - "tejer" creates fabric from yarn with needles',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_116',
    emoji: '🎭',
    question: '¿Qué usas para cubrir tu cara en teatro?',
    options: ['la máscara', 'el antifaz', 'la careta'],
    correctAnswer: 'la máscara',
    hint: 'Mask - theatrical face covering, used in ancient Greek drama',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_117',
    emoji: 'comedia.png',
    question: '¿Quién hace reír en el circo?',
    options: ['el payaso', 'el clown', 'el bufón'],
    correctAnswer: 'el payaso',
    hint: 'Clown - funny circus performer with colorful makeup and nose',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_118',
    emoji: '🎩',
    question: '¿Quién hace trucos de magia?',
    options: ['el mago', 'el ilusionista', 'el prestidigitador'],
    correctAnswer: 'el mago',
    hint: 'Magician - performs illusions and tricks, pulls rabbit from hat',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_119',
    emoji: 'acrobacia.png',
    question: '¿Qué hacen las personas que vuelan en trapecio?',
    options: ['la acrobacia', 'las acrobacias', 'el acróbata'],
    correctAnswer: 'la acrobacia',
    hint: 'Acrobatics - aerial stunts and flips, requires strength and balance',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_120',
    emoji: '💃',
    question: '¿Qué haces cuando te mueves con música?',
    options: ['bailar', 'el baile', 'danzar'],
    correctAnswer: 'bailar',
    hint: 'Dancing - "bailar" is to dance, moving body to music rhythm',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },

  // Games & Cards (15 questions)
  {
    id: 'entertainment_121',
    emoji: '🃏',
    question: '¿Con qué juegas póker?',
    options: ['las cartas', 'los naipes', 'la baraja'],
    correctAnswer: 'las cartas',
    hint: 'Playing cards - 52-card deck, "naipes" also means cards',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_122',
    emoji: '♠️',
    question: '¿Cuál es un palo de las cartas?',
    options: ['las espadas', 'las picas', 'los tréboles'],
    correctAnswer: 'las espadas',
    hint: 'Spades - black suit, "picas" in some regions, one of four suits',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_123',
    emoji: '♥️',
    question: '¿Qué palo de cartas es rojo?',
    options: ['los corazones', 'las copas', 'los diamantes'],
    correctAnswer: 'los corazones',
    hint: 'Hearts - red suit shaped like heart symbol, "copas" in Spanish deck',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_124',
    emoji: '🎴',
    question: '¿Qué juego japonés usa cartas especiales?',
    options: ['el hanafuda', 'el karuta', 'el hanuda'],
    correctAnswer: 'el hanafuda',
    hint: 'Hanafuda - traditional Japanese flower cards, 12 suits for months',
    points: 15,
    category: 'entertainment',
    difficulty: 'hard',
  },
  {
    id: 'entertainment_125',
    emoji: '🎰',
    question: '¿Qué máquina de casino tiene rodillos?',
    options: ['la tragamonedas', 'la tragaperras', 'la máquina'],
    correctAnswer: 'la tragamonedas',
    hint: 'Slot machine - "tragamonedas" literally means "coin swallower"',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_126',
    emoji: '♟️',
    question: '¿Qué pieza pequeña usas en ajedrez?',
    options: ['el peón', 'el alfil', 'el caballo'],
    correctAnswer: 'el peón',
    hint: 'Pawn - smallest chess piece, eight per player, moves forward only',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_127',
    emoji: 'ajedrez.png',
    question: '¿Qué juego de estrategia tiene rey y reina?',
    options: ['el ajedrez', 'el chess', 'las piezas'],
    correctAnswer: 'el ajedrez',
    hint: 'Chess - strategic board game, from Persian "shah" (king)',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_128',
    emoji: '🎲',
    question: '¿Qué juego usas fichas blancas y negras?',
    options: ['las damas', 'las damas chinas', 'las damas españolas'],
    correctAnswer: 'las damas',
    hint: 'Checkers - jump opponent pieces to capture them, "draughts" in UK',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_129',
    emoji: '🀄',
    question: '¿Qué juego chino usa fichas con símbolos?',
    options: ['el mahjong', 'el mah-jong', 'el mahjongg'],
    correctAnswer: 'el mahjong',
    hint: 'Mahjong - Chinese tile game, 144 tiles with matching patterns',
    points: 15,
    category: 'entertainment',
    difficulty: 'hard',
  },
  {
    id: 'entertainment_130',
    emoji: '🎯',
    question: '¿Qué juego lanzas flechas a un tablero?',
    options: ['los dardos', 'el tiro al blanco', 'la diana'],
    correctAnswer: 'los dardos',
    hint: 'Darts - throw pointed projectiles at circular board, pub game',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_131',
    emoji: '🎱',
    question: '¿Qué juego golpeas bolas con un taco?',
    options: ['el billar', 'el pool', 'la mesa de billar'],
    correctAnswer: 'el billar',
    hint: 'Pool/billiards - use cue stick to hit balls into pockets',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_132',
    emoji: '🏓',
    question: '¿Qué necesitas para jugar ping pong?',
    options: ['la paleta', 'la pala', 'el remo'],
    correctAnswer: 'la paleta',
    hint: 'Paddle - small table tennis paddle, "pala" also used',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_133',
    emoji: '🪀',
    question: '¿Qué juguete sube y baja con un hilo?',
    options: ['el yoyo', 'el yo-yo', 'el yoyó'],
    correctAnswer: 'el yoyo',
    hint: 'Yo-yo - toy that goes up and down on string, trick toy',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_134',
    emoji: '🧸',
    question: '¿Qué animal de peluche es popular?',
    options: ['el oso de peluche', 'el osito', 'el peluche'],
    correctAnswer: 'el oso de peluche',
    hint: 'Teddy bear - soft stuffed toy, "peluche" means plush',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_135',
    emoji: 'arcade.png',
    question: '¿Dónde juegas videojuegos gratis?',
    options: ['el arcade', 'la máquina', 'la sala de juegos'],
    correctAnswer: 'el arcade',
    hint: 'Arcade - public gaming venue with coin-operated machines',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },

  // Dance & Performance (15 questions)
  {
    id: 'entertainment_136',
    emoji: '💃',
    question: '¿Qué baile latino tiene pasos rápidos?',
    options: ['la salsa', 'el merengue', 'la cumbia'],
    correctAnswer: 'la salsa',
    hint: 'Salsa - fast Latin partner dance, originated in Caribbean',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_137',
    emoji: '🕺',
    question: '¿Qué baile argentino es elegante?',
    options: ['el tango', 'la milonga', 'el vals criollo'],
    correctAnswer: 'el tango',
    hint: 'Tango - passionate Argentine dance, emerged in Buenos Aires',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_138',
    emoji: '🩰',
    question: '¿Qué baile clásico usan zapatillas de punta?',
    options: ['el ballet', 'la danza clásica', 'la danza'],
    correctAnswer: 'el ballet',
    hint: 'Ballet - classical dance on toes, French origin, requires years training',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_139',
    emoji: '💃',
    question: '¿Qué baile español usa castañuelas?',
    options: ['el flamenco', 'la sevillana', 'las bulerías'],
    correctAnswer: 'el flamenco',
    hint: 'Flamenco - passionate Spanish dance with hand clapping, from Andalusia',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_140',
    emoji: '🎭',
    question: '¿Qué arte combina canto, baile y actuación?',
    options: ['el musical', 'la comedia musical', 'el teatro musical'],
    correctAnswer: 'el musical',
    hint: 'Musical theater - combines songs, dance, and dialogue, Broadway famous',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_141',
    emoji: '🎤',
    question: '¿Qué haces cuando cantas en un bar con pistas?',
    options: ['el karaoke', 'el караок', 'cantar karaoke'],
    correctAnswer: 'el karaoke',
    hint: 'Karaoke - singing to recorded music for fun, Japanese origin',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_142',
    emoji: 'concierto.png',
    question: '¿Qué evento tiene músicos en vivo?',
    options: ['el concierto', 'el recital', 'el show'],
    correctAnswer: 'el concierto',
    hint: 'Concert - live music performance by band or artist in venue',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_143',
    emoji: 'festival.png',
    question: '¿Qué festival de música dura varios días?',
    options: ['el festival', 'el festival de música', 'el evento'],
    correctAnswer: 'el festival',
    hint: 'Music festival - multi-day event with many artists, outdoor stages',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_144',
    emoji: '🎭',
    question: '¿Qué arte solo usa movimiento del cuerpo?',
    options: ['el mimo', 'la mímica', 'la pantomima'],
    correctAnswer: 'el mimo',
    hint: 'Mime - silent performance art, Marcel Marceau most famous',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_145',
    emoji: 'equilibrista.png',
    question: '¿Quién camina en cuerda alta?',
    options: ['el equilibrista', 'el funámbulo', 'el acróbata'],
    correctAnswer: 'el equilibrista',
    hint: 'Tightrope walker - balances on high wire, requires perfect balance',
    points: 15,
    category: 'entertainment',
    difficulty: 'hard',
  },
  {
    id: 'entertainment_146',
    emoji: 'bosquejar.png',
    question: '¿Qué haces cuando dibujas rápidamente?',
    options: ['bosquejar', 'esbozar', 'el boceto'],
    correctAnswer: 'bosquejar',
    hint: 'Sketching - quick rough drawing, "boceto" is the sketch itself',
    points: 15,
    category: 'entertainment',
    difficulty: 'hard',
  },
  {
    id: 'entertainment_147',
    emoji: '🗿',
    question: '¿Qué arte crea formas tridimensionales?',
    options: ['la escultura', 'el esculpir', 'el modelado'],
    correctAnswer: 'la escultura',
    hint: 'Sculpture - 3D art in stone, metal, clay, Michelangelo famous sculptor',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_149',
    emoji: 'pintura.png',
    question: '¿Qué mezclas para crear nuevos colores?',
    options: ['la pintura', 'los colores', 'los pigmentos'],
    correctAnswer: 'la pintura',
    hint: 'Paint - mix colors to create new shades, "óleo" is oil paint',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_150',
    emoji: '🎭',
    question: '¿Qué obra de teatro es muy triste?',
    options: ['la tragedia', 'el drama', 'la obra trágica'],
    correctAnswer: 'la tragedia',
    hint: 'Tragedy - serious drama with sad ending, Greek origin like Sophocles',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_151',
    emoji: '🤹',
    question: '¿Cómo se llaman los artistas que actúan en la calle?',
    options: ['los artistas callejeros', 'los músicos callejeros', 'los buskers'],
    correctAnswer: 'los artistas callejeros',
    hint: 'Street performers - buskers perform music, juggling, or acts in public spaces for tips',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_152',
    emoji: '🪄',
    question: '¿Cómo se llama la persona que hace trucos de magia?',
    options: ['el mago', 'el ilusionista', 'el prestidigitador'],
    correctAnswer: 'el mago',
    hint: 'Magician - a performer who entertains audiences with magic tricks and illusions',
    points: 10,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_153',
    emoji: '🤯',
    question: '¿Cómo describes un espectáculo que te sorprende muchísimo?',
    options: ['alucinante', 'aburrido', 'normal'],
    correctAnswer: 'alucinante',
    hint: 'Mind-blowing - "alucinante", incredibly amazing entertainment that blows your mind',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_154',
    emoji: '🧟',
    question: '¿Qué tipo de espectáculo de música y baile se ve en los resorts?',
    options: ['el show de Michael Jackson', 'el tributo a Michael Jackson', 'el espectáculo de MJ'],
    correctAnswer: 'el show de Michael Jackson',
    hint: 'Michael Jackson show - tribute performances popular at resorts, featuring Thriller and iconic dance moves',
    points: 10,
    category: 'entertainment',
    difficulty: 'medium',
  },
  {
    id: 'entertainment_155',
    emoji: '👾',
    question: '¿Qué juegos tienen personajes digitales y niveles?',
    options: ['los videojuegos', 'los juegos electrónicos', 'los juegos digitales'],
    correctAnswer: 'los videojuegos',
    hint: 'Video games - digital entertainment with characters and levels, popular worldwide',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_156',
    emoji: '🎆',
    question: '¿Qué espectáculo tiene explosiones de colores en el cielo?',
    options: ['los fuegos artificiales', 'la pirotecnia', 'el espectáculo pirotécnico'],
    correctAnswer: 'los fuegos artificiales',
    hint: 'Fireworks - colorful explosions in the sky, popular at celebrations and festivals',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
  {
    id: 'entertainment_157',
    emoji: '👹',
    question: '¿Qué usan los actores para cubrir la cara?',
    options: ['la máscara', 'el disfraz', 'el maquillaje'],
    correctAnswer: 'la máscara',
    hint: 'Mask - worn by actors to cover face, used in theater and performances',
    points: 5,
    category: 'entertainment',
    difficulty: 'easy',
  },
];
