/**
 * FOOD Category Questions
 * Category: food
 */

export const foodQuestions = [
// Fruits (20 questions)
  {
    id: 'food_001',
    emoji: '🍉',
    question: '¿Qué fruta roja comes en el verano?',
    translation: 'What red fruit do you eat in summer?',
    options: ['la sandía', 'la fresa', 'la cereza'],
    correctAnswer: 'la sandía',
    hint: 'Summer fruit with green rind and red, juicy flesh; often eaten in slices.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_002',
    emoji: '🍌',
    question: '¿Qué fruta es amarilla y larga?',
    translation: 'What fruit is yellow and long?',
    options: ['el plátano', 'el limón', 'el mango'],
    correctAnswer: 'el plátano',
    hint: 'Long, yellow fruit commonly eaten at breakfast; bends slightly and peels easily.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_003',
    emoji: '🍎',
    question: '¿Qué fruta puede ser roja o verde?',
    translation: 'What fruit can be red or green?',
    options: ['la manzana', 'la pera', 'la uva'],
    correctAnswer: 'la manzana',
    hint: 'Common fruit that comes in red or green varieties; crisp and often eaten raw.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_004',
    emoji: '🍊',
    question: '¿Qué fruta tiene mucha vitamina C?',
    translation: 'What fruit has lots of vitamin C?',
    options: ['la naranja', 'el limón', 'la mandarina'],
    correctAnswer: 'la naranja',
    hint: 'Citrus fruit known for vitamin C; round with a bright peel and segments inside.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_005',
    emoji: '🍇',
    
    question: '¿Con qué fruta se hace el vino?',
    translation: 'What fruit is wine made from?',
    options: ['las uvas', 'las ciruelas', 'las moras'],
    correctAnswer: 'las uvas',
    hint: 'Small round fruits that grow in bunches; pressed to make wine.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_008',
    emoji: 'fideos instantáneos.png',
    question: '¿Qué comida rápida preparas con agua caliente?',
    translation: 'What fast food do you prepare with hot water?',
    options: ['los fideos instantáneos', 'la sopa instantánea', 'el ramen instantáneo'],
    correctAnswer: 'los fideos instantáneos',
    hint: 'Instant noodles - quick meal prepared by adding hot water to dried noodles',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_009',
    emoji: '🍍',
    question: '¿Qué fruta tropical es amarilla por dentro?',
    translation: 'What tropical fruit is yellow inside?',
    options: ['la piña', 'el mango', 'la guayaba'],
    correctAnswer: 'la piña',
    hint: 'Tropical fruit with spiky skin and a sweet, yellow interior; often cut in rings.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_010',
    emoji: '🥝',
    question: '¿Qué fruta es verde por dentro con semillas negras?',
    translation: 'What fruit is green inside with black seeds?',
    options: ['el kiwi', 'la guayaba', 'la papaya'],
    correctAnswer: 'el kiwi',
    hint: 'Small fruit with brown fuzzy skin and bright green flesh dotted with tiny black seeds.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_011',
    emoji: 'sopa.png',
    question: '¿Qué comida líquida y caliente tomas cuando estás enfermo?',
    translation: 'What hot liquid food do you have when you\'re sick?',
    options: ['la sopa', 'el caldo', 'el consomé'],
    correctAnswer: 'la sopa',
    hint: 'Soup - hot liquid food often eaten when sick or for comfort',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_012',
    emoji: '🥭',
    question: '¿Qué fruta tropical es dulce y anaranjada?',
    translation: 'What tropical fruit is sweet and orange?',
    options: ['el mango', 'la papaya', 'el durazno'],
    correctAnswer: 'el mango',
    hint: 'Sweet tropical fruit with a large pit; turns orange when ripe.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_013',
    emoji: '🍐',
    question: '¿Qué fruta tiene forma de campana?',
    translation: 'What fruit is shaped like a bell?',
    options: ['la pera', 'la manzana', 'el higo'],
    correctAnswer: 'la pera',
    hint: 'Fruit with a light-bulb shape; soft texture and juicy flesh.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_014',
    emoji: '🥥',
    question: '¿De qué fruta se obtiene leche vegetal?',
    translation: 'What fruit do you get plant milk from?',
    options: ['el coco', 'la almendra', 'la avena'],
    correctAnswer: 'el coco',
    hint: 'Large tropical fruit with hard shell and white flesh; used to make dairy-free milk.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_015',
    emoji: '🥑',
    question: '¿Qué fruta verde se usa en guacamole?',
    translation: 'What green fruit is used in guacamole?',
    options: ['el aguacate', 'el pepino', 'la lima'],
    correctAnswer: 'el aguacate',
    hint: 'Creamy green fruit used in a popular dip; soft texture when ripe.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_016',
    emoji: '🫐',
    question: '¿Qué fruta pequeña es azul?',
    translation: 'What small fruit is blue?',
    options: ['el arándano', 'la mora', 'la ciruela'],
    correctAnswer: 'el arándano',
    hint: 'Small round blue berries; often used in muffins and breakfast bowls.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_017',
    emoji: '🍈',
    question: '¿Qué fruta es como una sandía pequeña?',
    translation: 'What fruit is like a small watermelon?',
    options: ['el melón', 'la guayaba', 'la granada'],
    correctAnswer: 'el melón',
    hint: 'Refreshing melon; smaller than the striped kind and sweet inside.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_018',
    emoji: '🍅',
    question: '¿Qué fruta roja se usa en ensaladas?',
    translation: 'What red fruit is used in salads?',
    options: ['el tomate', 'el pimiento', 'la remolacha'],
    correctAnswer: 'el tomate',
    hint: 'Red ingredient often added to salads and sauces; technically a fruit.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_019',
    emoji: '🫒',
    
    question: '¿De qué fruta se hace el aceite de oliva?',
    translation: 'What fruit is olive oil made from?',
    options: ['la aceituna', 'la nuez', 'el aguacate'],
    correctAnswer: 'la aceituna',
    hint: 'Olive oil comes from a small, bitter fruit; widely grown around the Mediterranean.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_020',
    emoji: '🍆',
    
    question: '¿Qué verdura es morada y larga?',
    translation: 'What vegetable is purple and long?',
    options: ['la berenjena', 'la remolacha', 'la col morada'],
    correctAnswer: 'la berenjena',
    hint: 'Purple vegetable with glossy skin; often roasted or used in Mediterranean dishes.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },

  // Vegetables (15 questions)
  {
    id: 'food_021',
    emoji: '🥕',
    
    question: '¿Qué verdura naranja comen los conejos?',
    translation: 'What orange vegetable do rabbits eat?',
    options: ['la zanahoria', 'la calabaza', 'el boniato'],
    correctAnswer: 'la zanahoria',
    hint: 'Orange root vegetable, good for eyes',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_022',
    emoji: '🥔',
    
    question: '¿Con qué verdura se hacen las papas fritas?',
    translation: 'What vegetable are french fries made from?',
    options: ['la papa', 'el boniato', 'la yuca'],
    correctAnswer: 'la papa',
    hint: 'Starchy tuber used to make fries; common side dish worldwide.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_023',
    emoji: '🧅',
    
    question: '¿Qué verdura te hace llorar cuando la cortas?',
    translation: 'What vegetable makes you cry when you cut it?',
    options: ['la cebolla', 'el ajo', 'el cebollino'],
    correctAnswer: 'la cebolla',
    hint: 'Makes you cry when you cut it',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_024',
    emoji: '🧄',
    
    question: '¿Qué ingrediente pequeño tiene olor fuerte?',
    translation: 'What small ingredient has a strong smell?',
    options: ['el ajo', 'la cebolla', 'el puerro'],
    correctAnswer: 'el ajo',
  hint: 'Small aromatic ingredient with a strong smell; used to flavor many dishes.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_025',
    emoji: '🌽',
    
    question: '¿Qué verdura amarilla tiene granos?',
    translation: 'What yellow vegetable has kernels?',
    options: ['el maíz', 'el elote', 'el choclo'],
    correctAnswer: 'el maíz',
    hint: 'Yellow kernels, makes popcorn',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_026',
    emoji: '🥒',
    
    question: '¿Qué verdura verde y larga está en las ensaladas?',
    translation: 'What long green vegetable is in salads?',
    options: ['el pepino', 'el calabacín', 'el apio'],
    correctAnswer: 'el pepino',
    hint: 'Crunchy green salad vegetable; high water content and mild taste.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_027',
    emoji: '🥬',
    
    question: '¿Qué verdura verde se come en ensaladas?',
    translation: 'What green vegetable is eaten in salads?',
    options: ['la lechuga', 'la espinaca', 'la acelga'],
    correctAnswer: 'la lechuga',
    hint: 'Green leafy base for salads',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_028',
    emoji: '🥦',
    
    question: '¿Qué verdura verde parece un árbol pequeño?',
    translation: 'What green vegetable looks like a small tree?',
    options: ['el brócoli', 'la coliflor', 'el brócoli rabe'],
    correctAnswer: 'el brócoli',
    hint: 'Green florets that look like tiny trees; rich in fiber and vitamins.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_029',
    emoji: '🫑',
    
    question: '¿Qué verdura puede ser roja, verde o amarilla?',
    translation: 'What vegetable can be red, green, or yellow?',
    options: ['el pimiento', 'el tomate', 'el chile'],
    correctAnswer: 'el pimiento',
    hint: 'Bell-shaped vegetable in red, green, or yellow; sweet, not spicy.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_030',
    emoji: '🌶️',
    
    question: '¿Qué ingrediente es muy picante?',
    translation: 'What ingredient is very spicy?',
    options: ['el chile', 'el pimiento', 'el jalapeño'],
    correctAnswer: 'el chile',
  hint: 'Spicy pepper used to add heat; comes in many varieties.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_031',
    emoji: '🥜',
    
    question: '¿De qué se hace la mantequilla de maní?',
    translation: 'What is peanut butter made from?',
    options: ['el cacahuate', 'la almendra', 'la avellana'],
    correctAnswer: 'el cacahuate',
    hint: 'Made from a legume that grows underground; commonly spread on toast.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_032',
    emoji: '🍄',
    
    question: '¿Qué crece en lugares húmedos?',
    translation: 'What grows in humid places?',
    options: ['el champiñón', 'la seta', 'el hongo'],
    correctAnswer: 'el champiñón',
  hint: 'Common edible mushroom that grows in damp areas; mild flavor.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_033',
    emoji: '🫘',
    
    question: '¿Qué se usa en los frijoles?',
    translation: 'What is used in beans?',
    options: ['los frijoles', 'las habas', 'las lentejas'],
    correctAnswer: 'los frijoles',
  hint: 'Staple legume in many dishes; often cooked and mashed.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_034',
    emoji: '🎃',
    
    question: '¿Qué verdura naranja se usa en Halloween?',
    translation: 'What orange vegetable is used on Halloween?',
    options: ['la calabaza', 'la zanahoria', 'el boniato'],
    correctAnswer: 'la calabaza',
  hint: 'Large orange squash used for decorations and cooking.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_035',
    emoji: '🥗',
    
    question: '¿Qué plato tiene muchas verduras frescas?',
    translation: 'What dish has many fresh vegetables?',
    options: ['la ensalada', 'la sopa', 'el guiso'],
    correctAnswer: 'la ensalada',
  hint: 'Plate of raw vegetables typically served with dressing.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },

  // Main Dishes & Proteins (20 questions)
  {
    id: 'food_036',
    emoji: '🍕',
    
    question: '¿Qué comida italiana es redonda?',
    translation: 'What Italian food is round?',
    options: ['la pizza', 'la focaccia', 'la calzone'],
    correctAnswer: 'la pizza',
    hint: 'Round dough base topped with sauce, cheese, and various toppings.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_037',
    emoji: '🍔',
    
    question: '¿Qué tiene carne entre dos panes?',
    translation: 'What has meat between two breads?',
    options: ['la hamburguesa', 'el sándwich', 'el bocadillo'],
    correctAnswer: 'la hamburguesa',
    hint: 'Ground meat patty in a bun, often with cheese, lettuce, and tomato.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_038',
    emoji: '🌭',
    
    question: '¿Qué comida tiene salchicha en pan largo?',
    translation: 'What food has a sausage in a long bread?',
    options: ['el hot dog', 'el chorizo', 'la salchicha'],
    correctAnswer: 'el hot dog',
    hint: 'Sausage served in a long bun, commonly topped with sauces.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_039',
    emoji: '🌮',
    
    question: '¿Qué comida mexicana usa tortilla doblada?',
    translation: 'What Mexican food uses a folded tortilla?',
    options: ['el taco', 'la quesadilla', 'la enchilada'],
    correctAnswer: 'el taco',
    hint: 'Folded flatbread with fillings such as meat, poultry, or vegetables.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_040',
    emoji: '🌯',
    
    question: '¿Qué comida mexicana está enrollada?',
    translation: 'What Mexican food is rolled up?',
    options: ['el burrito', 'la enchilada', 'el taco'],
    correctAnswer: 'el burrito',
    hint: 'Large rolled flatbread wrapped around a hearty filling.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_041',
    emoji: '🥙',
    
    question: '¿Qué pan árabe está relleno?',
    translation: 'What Arabic bread is stuffed?',
    options: ['la pita', 'el naan', 'la tortilla'],
    correctAnswer: 'la pita',
    hint: 'Flatbread with a pocket for fillings like vegetables or proteins.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_042',
    emoji: '🥪',
    
    question: '¿Qué tiene ingredientes entre dos rebanadas de pan?',
    translation: 'What has ingredients between two slices of bread?',
    options: ['el sándwich', 'el bocadillo', 'el emparedado'],
    correctAnswer: 'el sándwich',
    hint: 'Ingredients layered between two slices of bread; portable meal.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_043',
    emoji: '🍗',
    
    question: '¿Qué carne de ave es muy común?',
    translation: 'What poultry meat is very common?',
    options: ['el pollo', 'el pavo', 'el pato'],
    correctAnswer: 'el pollo',
    hint: 'Common white poultry meat; versatile in many recipes.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_044',
    emoji: '🥩',
    
    question: '¿Qué comes en un asado?',
    translation: 'What do you eat at a barbecue?',
    options: ['la carne', 'el bistec', 'el filete'],
    correctAnswer: 'la carne',
    hint: 'Grilled meat served at cookouts; includes cuts like steak or ribs.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_045',
    emoji: '🥓',
    
    question: '¿Qué carne frita comes en el desayuno?',
    translation: 'What fried meat do you eat for breakfast?',
    options: ['el tocino', 'el jamón', 'la panceta'],
    correctAnswer: 'el tocino',
    hint: 'Crispy smoked strips commonly served at breakfast.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_046',
    emoji: 'costilla.png',
    question: '¿Qué es carne con hueso?',
    translation: 'What is meat with bone?',
    options: ['la costilla', 'la chuleta', 'el filete'],
    correctAnswer: 'la costilla',
    hint: 'Cut of meat with bone attached; popular in barbecues.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_047',
    emoji: '🍤',
    
    question: '¿Qué marisco rosado es pequeño?',
    translation: 'What small pink seafood?',
    options: ['el camarón', 'la gamba', 'la langosta'],
    correctAnswer: 'el camarón',
    hint: 'Small seafood that turns pink when cooked; often fried or grilled.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_048',
    emoji: '🍣',
    
    question: '¿Qué comida japonesa tiene pescado crudo?',
    translation: 'What Japanese food has raw fish?',
    options: ['el sushi', 'el sashimi', 'el ramen'],
    correctAnswer: 'el sushi',
    hint: 'Rice-based dish often paired with raw seafood; sometimes served as rolls.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_049',
    emoji: '🍜',
    
    question: '¿Qué sopa asiática tiene fideos?',
    translation: 'What Asian soup has noodles?',
    options: ['el ramen', 'el pho', 'el udon'],
    correctAnswer: 'el ramen',
    hint: 'Noodle soup with savory broth and toppings like egg or pork.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_050',
    emoji: '🍝',
    
    question: '¿Qué comida italiana tiene fideos?',
    translation: 'What Italian food has noodles?',
    options: ['la pasta', 'los espaguetis', 'los tallarines'],
    correctAnswer: 'la pasta',
    hint: 'Italian noodles in many shapes; served with sauces or cheese.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_051',
    emoji: '🍲',
    
    question: '¿Qué plato caliente tiene muchos ingredientes?',
    translation: 'What hot dish has many ingredients?',
    options: ['el guiso', 'el estofado', 'el cocido'],
    correctAnswer: 'el guiso',
    hint: 'Hearty one-pot dish with mixed ingredients simmered together.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_052',
    emoji: '🥘',
    
    question: '¿Qué plato español tiene arroz y mariscos?',
    translation: 'What Spanish dish has rice and seafood?',
    options: ['la paella', 'el arroz con pollo', 'el risotto'],
    correctAnswer: 'la paella',
    hint: 'Spanish rice dish cooked in a wide pan; often includes seafood or meats.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_054',
    emoji: '🥚',
    
    question: '¿Qué ponen las gallinas?',
    translation: 'What do hens lay?',
    options: ['el huevo', 'el pollito', 'la pluma'],
    correctAnswer: 'el huevo',
    hint: 'Round-shelled food laid by hens; name related to “oval.”',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_055',
    emoji: '🍟',
    
    question: '¿Qué acompaña a la hamburguesa?',
    translation: 'What accompanies the hamburger?',
    options: ['las papas fritas', 'las patatas bravas', 'el arroz'],
    correctAnswer: 'las papas fritas',
    hint: 'Crispy fried strips commonly served alongside burgers.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },

  // Bread & Grains (10 questions)
  {
    id: 'food_056',
    emoji: '🍞',
    
    question: '¿Qué haces con harina en el horno?',
    translation: 'What do you do with flour in the oven?',
    options: ['el pan', 'la galleta', 'el pastel'],
    correctAnswer: 'el pan',
    hint: 'Baked dough made from flour; staple food in many cultures.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_057',
    emoji: '🥖',
    
    question: '¿Qué pan francés es largo?',
    translation: 'What French bread is long?',
    options: ['la baguette', 'el baguette', 'la barra'],
    correctAnswer: 'la baguette',
    hint: 'Long French loaf with a crisp crust and soft interior.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_058',
    emoji: '🥐',
    
    question: '¿Qué pan francés tiene forma de media luna?',
    translation: 'What French bread has a crescent shape?',
    options: ['el croissant', 'la medialuna', 'el brioche'],
    correctAnswer: 'el croissant',
    hint: 'Buttery flaky pastry shaped like a crescent; breakfast favorite.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_059',
    emoji: '🥨',
    
    question: '¿Qué pan tiene forma de nudo?',
    translation: 'What bread has a knot shape?',
    options: ['el pretzel', 'el bretzel', 'el nudo'],
    correctAnswer: 'el pretzel',
    hint: 'Twisted salty bread; often served with mustard in Germany.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_060',
    emoji: '🥯',
    
    question: '¿Qué pan redondo tiene agujero?',
    translation: 'What round bread has a hole?',
    options: ['el bagel', 'la dona', 'el rosquilla'],
    correctAnswer: 'el bagel',
    hint: 'Round bread with a hole; boiled first, then baked.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_061',
    emoji: '🫓',
    
    question: '¿Qué pan delgado y plano se usa en tacos?',
    translation: 'What thin and flat bread is used in tacos?',
    options: ['la tortilla', 'la pita', 'el naan'],
    correctAnswer: 'la tortilla',
    hint: 'Thin flatbread made from corn or wheat; used in many dishes.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_062',
    emoji: '🥞',
    
    question: '¿Qué comes en el desayuno con miel?',
    translation: 'What do you eat for breakfast with honey?',
    options: ['los panqueques', 'las crepes', 'los waffles'],
    correctAnswer: 'los panqueques',
    hint: 'Flat, sweet breakfast cakes often served with syrup or honey.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_063',
    emoji: '🧇',
    
    question: '¿Qué tiene cuadros y se come con miel?',
    translation: 'What has squares and is eaten with honey?',
    options: ['el waffle', 'el panqueque', 'la crepe'],
    correctAnswer: 'el waffle',
    hint: 'Grid-patterned breakfast pastry; crispy pockets hold syrup.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_064',
    emoji: '🍚',
    
    question: '¿Qué grano blanco se come en Asia?',
    translation: 'What white grain is eaten in Asia?',
    options: ['el arroz', 'el trigo', 'la cebada'],
    correctAnswer: 'el arroz',
    hint: 'Small grains eaten worldwide; staple food in many Asian countries.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_065',
    emoji: '🥣',
    
    question: '¿Qué desayuno tiene leche y cereal?',
    translation: 'What breakfast has milk and cereal?',
    options: ['el cereal', 'la avena', 'el muesli'],
    correctAnswer: 'el cereal',
    hint: 'Breakfast bowl with milk and processed grains or flakes.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },

  // Dairy & Cheese (8 questions)
  {
    id: 'food_066',
    emoji: '🥛',
    
    question: '¿Qué bebida blanca dan las vacas?',
    translation: 'What white drink do cows give?',
    options: ['la leche', 'el yogur', 'la crema'],
    correctAnswer: 'la leche',
    hint: 'White dairy drink produced by cows; base for many dairy products.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_067',
    emoji: '🧀',
    
    question: '¿Qué se hace con leche fermentada?',
    translation: 'What is made with fermented milk?',
    options: ['el queso', 'el yogur', 'la crema'],
    correctAnswer: 'el queso',
    hint: 'Dairy product made from curdled milk; many styles and flavors.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_068',
    emoji: '🧈',
    
    question: '¿Qué untas en el pan tostado?',
    translation: 'What do you spread on toast?',
    options: ['la mantequilla', 'la margarina', 'la mermelada'],
    correctAnswer: 'la mantequilla',
    hint: 'Creamy dairy spread used on toast or for cooking.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_069',
    emoji: '🍦',
    question: '¿Qué helado cremoso sale de una máquina?',
    translation: 'What creamy ice cream comes from a machine?',
    options: ['el helado suave', 'el helado soft', 'el helado de máquina'],
    correctAnswer: 'el helado suave',
    hint: 'Soft serve ice cream - creamy frozen dessert dispensed from a machine in a swirl',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_070',
    emoji: '🍨',
    
    question: '¿Qué postre frío se sirve en copa?',
    translation: 'What cold dessert is served in a glass?',
    options: ['el helado', 'el sundae', 'la nieve'],
    correctAnswer: 'el helado',
    hint: 'Ice cream served in a dish with toppings and sauce (sundae style).',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_071',
    emoji: '🧊',
    question: '¿Qué pones en las bebidas para enfriarlas?',
    translation: 'What do you put in drinks to cool them?',
    options: ['el hielo', 'el agua fría', 'la nieve'],
    correctAnswer: 'el hielo',
    hint: 'Frozen water cubes added to drinks to keep them cold.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_073',
    emoji: '🍮',
    
    question: '¿Qué postre dulce tiene caramelo?',
    translation: 'What sweet dessert has caramel?',
    options: ['el flan', 'el pudín', 'la natilla'],
    correctAnswer: 'el flan',
  hint: 'Caramel-topped custard dessert popular in many countries.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },

  // Drinks (12 questions)
  {
    id: 'food_074',
    emoji: '☕',
    question: '¿Qué bebida caliente tomas por la mañana?',
    translation: 'What hot drink do you have in the morning?',
    options: ['el café', 'el té', 'el chocolate caliente'],
    correctAnswer: 'el café',
  hint: 'Hot, caffeinated drink often served as espresso, americano, or latte.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_075',
    emoji: '🍵',
    
    question: '¿Qué bebida caliente tiene hierbas?',
    translation: 'What hot drink has herbs?',
    options: ['el té', 'la infusión', 'la manzanilla'],
    correctAnswer: 'el té',
  hint: 'Hot drink made by steeping leaves; varieties include green, black, and herbal.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_076',
    emoji: '🧃',
    
    question: '¿Qué bebes de frutas?',
    translation: 'What do you drink made from fruits?',
    options: ['el jugo', 'el zumo', 'el néctar'],
    correctAnswer: 'el jugo',
  hint: 'Drink made from pressed fruits; often served at breakfast.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_077',
    emoji: '🥤',
    
    question: '¿Qué bebida gaseosa tomas con popote?',
    translation: 'What fizzy drink do you have with a straw?',
    options: ['el refresco', 'la gaseosa', 'la soda'],
    correctAnswer: 'el refresco',
  hint: 'Sweet carbonated drink often served with a straw.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_078',
    emoji: '🧋',
    
    question: '¿Qué bebida taiwanesa tiene bolitas?',
    translation: 'What Taiwanese drink has little balls?',
    options: ['té de burbujas', 'boba', 'té con leche'],
    correctAnswer: 'té de burbujas',
  hint: 'Tea with chewy tapioca pearls; popular Taiwanese drink.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_079',
    emoji: '🍶',
    
    question: '¿Qué bebida japonesa se hace de arroz?',
    translation: 'What Japanese drink is made from rice?',
    options: ['el sake', 'el shochu', 'el amazake'],
    correctAnswer: 'el sake',
  hint: 'Japanese rice-based drink; served warm or chilled.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_080',
    emoji: '🍺',
    
    question: '¿Qué bebida alcohólica es amarilla?',
    translation: 'What alcoholic drink is yellow?',
    options: ['la cerveza', 'la sidra', 'el vino blanco'],
    correctAnswer: 'la cerveza',
  hint: 'Fermented grain beverage; comes in pale, amber, or dark styles.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_081',
    emoji: '🍷',
    
    question: '¿Qué bebida se hace de uvas?',
    translation: 'What drink is made from grapes?',
    options: ['el vino', 'el mosto', 'el jerez'],
    correctAnswer: 'el vino',
  hint: 'Alcoholic drink made from grapes; red, white, or rosé.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_082',
    emoji: '🥂',
    
    question: '¿Qué bebes para celebrar?',
    translation: 'What do you drink to celebrate?',
    options: ['el champán', 'el cava', 'el prosecco'],
    correctAnswer: 'el champán',
  hint: 'Sparkling wine served for celebrations; bubbly and festive.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_083',
    emoji: '🍹',
    
    question: '¿Qué bebida tropical tiene sombrilla?',
    translation: 'What tropical drink has an umbrella?',
    options: ['el cóctel', 'el trago', 'la bebida'],
    correctAnswer: 'el cóctel',
  hint: 'Mixed tropical drink often decorated with a small umbrella.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_084',
    emoji: '🍸',
    question: '¿Qué bebida se sirve en copa triangular?',
    translation: 'What drink is served in a triangular glass?',
    options: ['el martini', 'el cosmopolitan', 'el manhattan'],
    correctAnswer: 'el martini',
  hint: 'Classic mixed drink served in a V-shaped glass.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_085',
    emoji: '🧉',
    question: '¿Qué bebida tradicional argentina se toma con bombilla?',
    translation: 'What traditional Argentine drink is consumed with a bombilla?',
    options: ['el mate', 'el tereré', 'la yerba'],
    correctAnswer: 'el mate',
  hint: 'Traditional infusion sipped through a metal straw in a shared cup.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },

  // Desserts & Sweets (15 questions)
  {
    id: 'food_086',
    emoji: '🍰',
    question: '¿Qué postre dulce comes en cumpleaños?',
    translation: 'What sweet dessert do you eat on birthdays?',
    options: ['el pastel', 'la tarta', 'el bizcocho'],
    correctAnswer: 'el pastel',
    hint: 'Baked celebration dessert often decorated for birthdays.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_087',
    emoji: '🎂',
    question: '¿Qué tiene velas en tu cumpleaños?',
    translation: 'What has candles on your birthday?',
    options: ['el pastel', 'la tarta', 'el bizcocho'],
    correctAnswer: 'el pastel',
    hint: 'Dessert topped with candles that you blow out to make a wish.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_088',
    emoji: '🧁',
    question: '¿Qué es un pastel pequeño individual?',
    translation: 'What is a small individual cake?',
    options: ['el cupcake', 'la magdalena', 'el muffin'],
    correctAnswer: 'el cupcake',
    hint: 'Individual mini cake with frosting; served in a paper cup.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_089',
    emoji: '🥧',
    
    question: '¿Qué postre tiene frutas en masa?',
    translation: 'What dessert has fruits in dough?',
    options: ['el pay', 'la tarta', 'el pastel de manzana'],
    correctAnswer: 'el pay',
  hint: 'Dessert with a baked crust and a fruit or custard filling.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_090',
    emoji: '🍫',
    
    question: '¿Qué dulce marrón es de cacao?',
    translation: 'What brown candy is made from cocoa?',
    options: ['el chocolate', 'el bombón', 'el cacao'],
    correctAnswer: 'el chocolate',
    hint: 'Sweet treat made from cacao; comes in dark, milk, or white varieties.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_091',
    emoji: '🍬',
    
    question: '¿Qué dulce pequeño chupas?',
    translation: 'What small candy do you suck on?',
    options: ['el caramelo', 'la paleta', 'el chicle'],
    correctAnswer: 'el caramelo',
    hint: 'Small hard candy; also refers to melted sugar sauce in desserts.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_092',
    emoji: '🍭',
    
    question: '¿Qué dulce está en un palito?',
    translation: 'What candy is on a stick?',
    options: ['la paleta', 'el chupete', 'el pirulí'],
    correctAnswer: 'la paleta',
    hint: 'Candy mounted on a stick; also used for frozen treats on sticks.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_093',
    emoji: '🍪',
    
    question: '¿Qué postre crujiente tiene chispas de chocolate?',
    translation: 'What crunchy dessert has chocolate chips?',
    options: ['la galleta', 'la cookie', 'el biscocho'],
    correctAnswer: 'la galleta',
    hint: 'Small baked dessert; often has chocolate chips for crunch.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_094',
    emoji: '🍩',
    
    question: '¿Qué dulce redondo tiene agujero?',
    translation: 'What round candy has a hole?',
    options: ['la dona', 'la rosquilla', 'el buñuelo'],
    correctAnswer: 'la dona',
    hint: 'Round fried dough with a hole; glazed or dusted with sugar.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_095',
    emoji: '🍯',
    
    question: '¿Qué hacen las abejas?',
    translation: 'What do bees make?',
    options: ['la miel', 'la cera', 'el néctar'],
    correctAnswer: 'la miel',
    hint: 'Natural sweetener made by bees from flower nectar.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_096',
    emoji: '🍿',
    
    question: '¿Qué comes en el cine?',
    translation: 'What do you eat at the movies?',
    options: ['las palomitas', 'los nachos', 'las papas fritas'],
    correctAnswer: 'las palomitas',
    hint: 'Puffed corn kernels enjoyed as a crunchy movie snack.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_097',
    emoji: '🥠',
    
    question: '¿Qué galleta china tiene mensaje dentro?',
    translation: 'What Chinese cookie has a message inside?',
    options: ['la galleta de la fortuna', 'el fortune cookie', 'la galleta china'],
    correctAnswer: 'la galleta de la fortuna',
    hint: 'Crispy cookie that contains a small paper message inside.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_098',
    emoji: 'tostada.png',
    question: '¿Qué pan tostado comes en el desayuno?',
    translation: 'What toasted bread do you eat for breakfast?',
    options: ['la tostada', 'el pan tostado', 'el toast'],
    correctAnswer: 'la tostada',
    hint: 'Toast - toasted bread commonly eaten at breakfast with butter or spreads',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_100',
    emoji: '🥮',
    question: '¿Qué pastel chino se come en otoño?',
    translation: 'What Chinese cake is eaten in autumn?',
    options: ['el pastel de luna', 'el mooncake', 'el pastel chino'],
    correctAnswer: 'el pastel de luna',
    hint: 'Dense round pastry eaten during the Mid-Autumn Festival; sweet filling inside.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },

  // More Fruits (10 questions)
  {
    id: 'food_101',
    emoji: '🍑',
    question: '¿Qué fruta de verano tiene piel peluda?',
    translation: 'What summer fruit has fuzzy skin?',
    options: ['el durazno', 'el melocotón', 'el albaricoque'],
    correctAnswer: 'el durazno',
    hint: 'Summer stone fruit with fuzzy skin and sweet, fragrant flesh.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_104',
    emoji: '🍋',
    question: '¿Qué fruta usas para hacer limonada?',
    translation: 'What fruit do you use to make lemonade?',
    options: ['el limón', 'la lima', 'la toronja'],
    correctAnswer: 'el limón',
    hint: 'Citrus fruit used to make a tart, refreshing summer drink.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_105',
    emoji: '🥝',
    question: '¿Qué fruta peluda es verde por dentro?',
    translation: 'What fuzzy fruit is green inside?',
    options: ['el kiwi', 'la guayaba', 'la papaya'],
    correctAnswer: 'el kiwi',
    hint: 'Small fruit with brown fuzzy skin and bright green flesh with tiny seeds.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_106',
    emoji: '🍐',
    question: '¿Qué fruta es dulce y tiene forma de bombilla?',
    translation: 'What fruit is sweet and shaped like a light bulb?',
    options: ['la pera', 'la manzana', 'el higo'],
    correctAnswer: 'la pera',
    hint: 'Sweet fruit with a light-bulb shape; juicy and soft.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_107',
    emoji: '🍓',
    question: '¿Qué fruta roja tiene semillas por fuera?',
    translation: 'What red fruit has seeds on the outside?',
    options: ['la fresa', 'la mora', 'la frambuesa'],
    correctAnswer: 'la fresa',
    hint: 'Red berry with seeds on the outside; aromatic and sweet.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_108',
    emoji: '🍇',
    question: '¿Qué fruta crece en racimos?',
    translation: 'What fruit grows in bunches?',
    options: ['las uvas', 'las moras', 'los arándanos'],
    correctAnswer: 'las uvas',
    hint: 'Small round fruits that grow in clusters; used for wine and raisins.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_109',
    emoji: '🍒',
    question: '¿Qué fruta roja pequeña viene en pares?',
    translation: 'What small red fruit comes in pairs?',
    options: ['la cereza', 'la aceituna', 'la ciruela'],
    correctAnswer: 'la cereza',
    hint: 'Small red stone fruit often seen in pairs; sweet or tart varieties.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_110',
    emoji: '🍈',
    question: '¿Qué fruta verde es dulce por dentro?',
    translation: 'What green fruit is sweet on the inside?',
    options: ['el melón', 'la sandía', 'la guayaba'],
    correctAnswer: 'el melón',
    hint: 'Green-skinned melon with sweet, juicy interior.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },

  // More Proteins & Seafood (15 questions)
  {
    id: 'food_111',
    emoji: '🐟',
    
    question: '¿Qué comes del mar?',
    translation: 'What do you eat from the sea?',
    options: ['el pescado', 'el salmón', 'el atún'],
    correctAnswer: 'el pescado',
    hint: 'Seafood commonly eaten grilled or baked; high in protein.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_112',
    emoji: '🦞',
    
    question: '¿Qué marisco rojo tiene pinzas?',
    translation: 'What red seafood has claws?',
    options: ['la langosta', 'el bogavante', 'el cangrejo'],
    correctAnswer: 'la langosta',
    hint: 'Shellfish with large claws; turns bright red when cooked.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_113',
    emoji: '🦀',
    
    question: '¿Qué marisco camina de lado?',
    translation: 'What seafood walks sideways?',
    options: ['el cangrejo', 'la jaiba', 'el centollo'],
    correctAnswer: 'el cangrejo',
    hint: 'Crustacean that scuttles sideways; hard shell and two claws.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_114',
    emoji: '🦑',
    
    question: '¿Qué marisco tiene tentáculos?',
    translation: 'What seafood has tentacles?',
    options: ['el calamar', 'el pulpo', 'la sepia'],
    correctAnswer: 'el calamar',
    hint: 'Sea creature with long arms; commonly grilled or fried.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_115',
    emoji: '🦐',
    
    question: '¿Qué marisco pequeño se fríe?',
    translation: 'What small seafood is fried?',
    options: ['el camarón', 'la gamba', 'el langostino'],
    correctAnswer: 'el camarón',
    hint: 'Small pink seafood often fried or grilled; turns pink when cooked.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_116',
    emoji: '🦪',
    
    question: '¿En qué marisco encuentras perlas?',
    translation: 'In what seafood do you find pearls?',
    options: ['la ostra', 'la almeja', 'el mejillón'],
    correctAnswer: 'la ostra',
    hint: 'Shellfish sometimes containing pearls; eaten raw or cooked.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_117',
    emoji: '🍖',
    
    question: '¿Qué corte de carne tiene hueso?',
    translation: 'What cut of meat has bone?',
    options: ['la chuleta', 'la costilla', 'el filete'],
    correctAnswer: 'la chuleta',
    hint: 'Meat cut with a bone attached; often grilled or pan-seared.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_118',
    emoji: '🥩',
    
    question: '¿Qué carne se asa a la parrilla?',
    translation: 'What meat is grilled?',
    options: ['el bistec', 'el filete', 'la carne asada'],
    correctAnswer: 'el bistec',
  hint: 'Cut of meat cooked on a grill or pan; served as a hearty main.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_119',
    emoji: '🍗',
    
    question: '¿Qué parte del pollo se fríe?',
    translation: 'What part of the chicken is fried?',
    options: ['el muslo', 'la pechuga', 'el ala'],
    correctAnswer: 'el muslo',
  hint: 'Juicy poultry cut often fried or roasted; flavorful and tender.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_120',
    emoji: '🥓',
    
    question: '¿Qué carne crujiente comes con huevos?',
    translation: 'What crispy meat do you eat with eggs?',
    options: ['el tocino', 'la panceta', 'el jamón'],
    correctAnswer: 'el tocino',
  hint: 'Thin smoked pork slices that crisp when fried; breakfast favorite.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_121',
    emoji: '🍤',
    
    question: '¿Qué marisco empanizado es delicioso?',
    translation: 'What breaded seafood is delicious?',
    options: ['el camarón empanizado', 'el camarón rebozado', 'el pescado empanizado'],
    correctAnswer: 'el camarón empanizado',
  hint: 'Seafood coated in crumbs and fried until crispy on the outside.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_122',
    emoji: 'salchicha.png',
    question: '¿Qué salchicha se come en pan?',
    translation: 'What sausage is eaten in bread?',
    options: ['la salchicha', 'el chorizo', 'la longaniza'],
    correctAnswer: 'la salchicha',
  hint: 'Seasoned meat stuffed into a casing; eaten in a bun or with sides.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_123',
    emoji: 'vino-blanco.png',
    question: '¿Cómo se llama el vino elaborado con uvas amarillas?',
    translation: 'What do you call wine made from yellow grapes?',
    options: ['vino blanco', 'vino tinto', 'vino rosado'],
    correctAnswer: 'vino blanco',
  hint: 'Wine made from green or yellow grapes; often served chilled.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_124',
    emoji: '🫔',
    
    question: '¿Qué comida mexicana está enrollada y bañada?',
    translation: 'What Mexican food is rolled and covered in sauce?',
    options: ['la enchilada', 'el burrito', 'la chimichanga'],
    correctAnswer: 'la enchilada',
  hint: 'Rolled flatbread covered in a spicy sauce; baked or served warm.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_125',
    emoji: '🥟',
    
    question: '¿Qué comida china rellena se cuece al vapor?',
    translation: 'What filled Chinese food is steamed?',
    options: ['el dumpling', 'el wonton', 'el baozi'],
    correctAnswer: 'el dumpling',
  hint: 'Small dough pockets with fillings; steamed, boiled, or fried.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },

  // Condiments & Seasonings (15 questions)
  {
    id: 'food_126',
    emoji: '🧂',
    
    question: '¿Qué condimento blanco usas para sazonar?',
    translation: 'What white condiment do you use to season?',
    options: ['la sal', 'la pimienta', 'el azúcar'],
    correctAnswer: 'la sal',
  hint: 'Essential mineral used to season food; enhances flavor.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_127',
    emoji: '🫙',
    
    question: '¿En qué guardas la mermelada?',
    translation: 'What do you keep jam in?',
    options: ['el frasco', 'el tarro', 'el bote'],
    correctAnswer: 'el frasco',
  hint: 'Glass container with a lid used for jams and preserves.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_128',
    emoji: '🍯',
    
    question: '¿Qué producto dulce hacen las abejas?',
    translation: 'What sweet product do bees make?',
    options: ['la miel', 'el polen', 'la cera'],
    correctAnswer: 'la miel',
  hint: 'Natural sweetener made by bees from flower nectar.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_129',
    emoji: '🥫',
    
    question: '¿En qué recipiente viene la sopa enlatada?',
    translation: 'What container does canned soup come in?',
    options: ['la lata', 'la caja', 'el frasco'],
    correctAnswer: 'la lata',
  hint: 'Metal container; canned foods are sealed and shelf-stable.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_130',
    emoji: '🫗',
    
    question: '¿Qué haces cuando sirves agua?',
    translation: 'What do you do when you serve water?',
    options: ['verter', 'servir', 'echar'],
    correctAnswer: 'verter',
  hint: 'Action of pouring liquid from one container into another.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_131',
    emoji: '🧈',
    
    question: '¿Qué grasa amarilla untas en pan?',
    translation: 'What yellow fat do you spread on bread?',
    options: ['la mantequilla', 'la margarina', 'la manteca'],
    correctAnswer: 'la mantequilla',
  hint: 'Yellow dairy fat used as a spread or for cooking.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_132',
    emoji: '🫚',
    
    question: '¿Qué raíz picante se usa en la cocina asiática?',
    translation: 'What spicy root is used in Asian cooking?',
    options: ['el jengibre', 'la cúrcuma', 'el rábano'],
    correctAnswer: 'el jengibre',
  hint: 'Spicy, aromatic root used fresh or dried in cooking.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_133',
    emoji: '🌶️',
    
    question: '¿Qué ingrediente hace la comida picante?',
    translation: 'What ingredient makes food spicy?',
    options: ['el chile', 'el jalapeño', 'el pimiento'],
    correctAnswer: 'el chile',
  hint: 'Contains capsaicin, which creates a spicy heat sensation.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_134',
    emoji: '🧄',
    
    question: '¿Qué bulbo blanco tiene olor fuerte?',
    translation: 'What white bulb has a strong smell?',
    options: ['el ajo', 'la cebolla', 'el chalote'],
    correctAnswer: 'el ajo',
  hint: 'Pungent white bulb used to flavor many savory dishes.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_135',
    emoji: '🧅',
    
    question: '¿Qué verdura redonda te hace llorar?',
    translation: 'What round vegetable makes you cry?',
    options: ['la cebolla', 'el puerro', 'el cebollino'],
    correctAnswer: 'la cebolla',
  hint: 'Releases compounds when cut that can make your eyes water.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_136',
    emoji: '🥜',
    
    question: '¿De qué nuez se hace la mantequilla de maní?',
    translation: 'What nut is peanut butter made from?',
    options: ['el maní', 'el cacahuate', 'la almendra'],
    correctAnswer: 'el maní',
  hint: 'Technically a legume; ground into a creamy spread.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_137',
    emoji: '🌰',
    
    question: '¿Qué fruto seco comen las ardillas?',
    translation: 'What nuts do squirrels eat?',
    options: ['la castaña', 'la bellota', 'la nuez'],
    correctAnswer: 'la castaña',
  hint: 'Nut often roasted in autumn; popular street snack in many cities.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_138',
    emoji: '🥥',
    
    question: '¿De qué fruta tropical sale leche vegetal?',
    translation: 'What tropical fruit does plant milk come from?',
    options: ['el coco', 'la almendra', 'la avena'],
    correctAnswer: 'el coco',
    hint: 'Hard-shelled tropical fruit with white flesh and liquid; used for plant milk.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_139',
    emoji: '🍄',
    
    question: '¿Qué hongo comestible crece en bosques?',
    translation: 'What edible fungus grows in forests?',
    options: ['la seta', 'el champiñón', 'el portobello'],
    correctAnswer: 'la seta',
  hint: 'Edible wild mushroom; “seta” is a generic term for mushrooms.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_140',
    emoji: '🫘',
    
    question: '¿Qué legumbre se usa en chili?',
    translation: 'What legume is used in chili?',
    options: ['el frijol', 'la alubia', 'el garbanzo'],
    correctAnswer: 'el frijol',
  hint: 'Common bean used in spicy stews; often the red kidney variety.',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },

  // More International Dishes (15 questions)
  // More International Dishes (15 questions)
  {
    id: 'food_142',
    emoji: '🍙',
    
    question: '¿Qué triángulo de arroz japonés tiene alga?',
    translation: 'What Japanese rice triangle has seaweed?',
    options: ['el onigiri', 'el musubi', 'el maki'],
    correctAnswer: 'el onigiri',
    hint: 'Rice triangle wrapped with seaweed; typically has a simple filling.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_143',
    emoji: '🍘',
    question: '¿Qué galleta japonesa de arroz es crujiente?',
    translation: 'What Japanese rice cracker is crunchy?',
    options: ['el senbei', 'el arare', 'el okaki'],
    correctAnswer: 'el senbei',
    hint: 'Crispy Japanese rice cracker; sometimes flavored with soy sauce.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_144',
    emoji: '🍥',
    question: '¿Qué ingrediente blanco y rosado va en ramen?',
    translation: 'What white and pink ingredient goes in ramen?',
    options: ['el narutomaki', 'el kamaboko', 'el surimi'],
    correctAnswer: 'el narutomaki',
    hint: 'White-and-pink fish cake with a spiral; commonly served in ramen.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_147',
    emoji: '🍛',
    question: '¿Qué plato picante indio tiene arroz?',
    translation: 'What spicy Indian dish has rice?',
    options: ['el curry', 'el masala', 'el korma'],
    correctAnswer: 'el curry',
    hint: 'Spiced sauce dish; often served alongside or over rice.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_148',
    emoji: '🍲',
    question: '¿Qué plato caliente cocinas en olla?',
    translation: 'What hot dish do you cook in a pot?',
    options: ['el estofado', 'el cocido', 'el potaje'],
    correctAnswer: 'el estofado',
    hint: 'Slow-cooked pot dish with meat and vegetables in broth.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_149',
    emoji: '🫕',
    question: '¿Qué comida suiza sumerges en queso derretido?',
    translation: 'What Swiss food do you dip in melted cheese?',
    options: ['el fondue', 'la raclette', 'el fondue de queso'],
    correctAnswer: 'el fondue',
    hint: 'Melted cheese served for dipping bread or vegetables; Swiss dish.',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_150',
    emoji: '🥘',
    question: '¿Qué plato español tiene azafrán?',
    translation: 'What Spanish dish has saffron?',
    options: ['la paella', 'el arroz al horno', 'la fideuá'],
    correctAnswer: 'la paella',
    hint: 'Saffron-tinted rice dish cooked in a wide pan; includes seafood or meats.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_151',
    emoji: '🍝',
    question: '¿Qué fideos italianos son largos y delgados?',
    translation: 'What Italian noodles are long and thin?',
    options: ['el espagueti', 'los tallarines', 'los fideos'],
    correctAnswer: 'el espagueti',
    hint: 'Long thin pasta noodles',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_152',
    emoji: '🥗',
    question: '¿Qué ensalada romana tiene crutones?',
    translation: 'What Roman salad has croutons?',
    options: ['la César', 'la ensalada César', 'la ensalada romana'],
    correctAnswer: 'la César',
    hint: 'Classic salad with romaine, croutons, cheese, and a tangy dressing.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_153',
    emoji: 'hummus.png',
    question: '¿Qué comida de Oriente Medio se elabora únicamente con garbanzos?',
    translation: 'What Middle Eastern food is made only from chickpeas?',
    options: ['hummus', 'el baba ganoush','el mutabbal'],
    correctAnswer: 'hummus',
    hint: 'Creamy chickpea spread with sesame paste and olive oil.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_154',
    emoji: '🌮',
    question: '¿Qué comida mexicana tiene tortilla crujiente?',
    translation: 'What Mexican food has a crunchy tortilla?',
    options: ['el taco duro', 'la tostada', 'el taco dorado'],
    correctAnswer: 'el taco duro',
    hint: 'Crunchy fried tortilla shell filled with savory ingredients.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_155',
    emoji: '🧆',
    question: '¿Qué bola frita del Medio Oriente es vegetariana?',
    translation: 'What fried Middle Eastern ball is vegetarian?',
    options: ['el falafel', 'el taameya', 'la kofta'],
    correctAnswer: 'el falafel',
    hint: 'Deep-fried chickpea or fava bean balls; vegetarian.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },

  // Additional Food/Utensil Phrases (3 questions)
  {
    id: 'food_159',
    emoji: 'especias.png',
    question: '¿Qué se añade a la comida para el sabor?',
    translation: 'What is added to food for flavor?',
    options: ['las especias', 'la sal', 'el condimento'],
    correctAnswer: 'las especias',
    hint: 'Spices - powdered or dried seasonings like cumin, paprika, etc.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_160',
    emoji: 'la-salsa-picante.png',
    question: '¿Qué salsa roja picante acompaña muchas comidas?',
    translation: 'What spicy red sauce accompanies many meals?',
    options: ['la salsa picante', 'la salsa de tomate', 'la salsa de chile'],
    correctAnswer: 'la salsa picante',
    hint: 'Hot sauce - spicy condiment made from peppers, adds heat to dishes',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_161',
    emoji: 'ketchup.png',
    question: '¿Qué condimento rojo viene en una botella?',
    translation: 'What red condiment comes in a bottle?',
    options: ['la salsa de tomate', 'la catsup', 'el ketchup'],
    correctAnswer: 'el ketchup',
    hint: 'Ketchup - tomato condiment, popular on fries and burgers, American origin',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_162',
    emoji: '🫛',
    question: '¿Qué verdura verde y pequeña viene en vaina?',
    translation: 'What small green vegetable comes in a pod?',
    options: ['los guisantes', 'los chícharos', 'las arvejas'],
    correctAnswer: 'los guisantes',
    hint: 'Peas - small green legumes in pods, "chícharos" in Mexico, "arvejas" in South America',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_163',
    emoji: '🍼',
    question: '¿Qué toman los bebés?',
    translation: 'What do babies drink?',
    options: ['la fórmula para bebés', 'la leche de fórmula', 'la fórmula infantil'],
    correctAnswer: 'la fórmula para bebés',
    hint: 'Baby formula - infant milk substitute, nutritious for babies',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },

   // Basic Restaurant Phrases (1-15)
  {
    id: 'food_164',
    emoji: '🍽️',
    question: '¿Qué dices al mesero para pedir?',
    translation: 'What do you say to the waiter to order?',
    options: ['quisiera', 'necesito', 'quiero'],
    correctAnswer: 'quisiera',
    hint: 'Polite way to order - "I would like"',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_165',
    emoji: '📋',
    question: '¿Qué necesitas para ver las opciones de comida?',
    translation: 'What do you need to see the food options?',
    options: ['el menú', 'la cuenta', 'el plato'],
    correctAnswer: 'el menú',
    hint: 'Menu - list of food options, also called "la carta"',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_166',
    emoji: '👨‍🍳',
    question: '¿Quién te sirve en un restaurante?',
    translation: 'Who serves you at a restaurant?',
    options: ['el mesero', 'el cocinero', 'el gerente'],
    correctAnswer: 'el mesero',
    hint: 'Waiter/server - also called "camarero" in Spain',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_167',
    emoji: '💰',
    question: '¿Qué pides al final de la comida?',
    translation: 'What do you ask for at the end of the meal?',
    options: ['la cuenta', 'el menú', 'el postre'],
    correctAnswer: 'la cuenta',
    hint: 'The bill/check - "la cuenta, por favor"',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_168',
    emoji: '🪑',
    question: '¿Qué pides cuando llegas al restaurante?',
    translation: 'What do you ask for when you arrive at the restaurant?',
    options: ['una mesa', 'una silla', 'un plato'],
    correctAnswer: 'una mesa',
    hint: 'Table - "una mesa para dos personas"',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_169',
    emoji: '📅',
    question: '¿Qué haces para asegurar una mesa?',
    translation: 'What do you do to secure a table?',
    options: ['hacer una reserva', 'pagar una cuenta', 'leer el menú'],
    correctAnswer: 'hacer una reserva',
    hint: 'Make a reservation - book ahead',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_170',
    emoji: '💵',
    question: '¿Qué dejas para el mesero por buen servicio?',
    translation: 'What do you leave for the waiter for good service?',
    options: ['la propina', 'la cuenta', 'el cambio'],
    correctAnswer: 'la propina',
    hint: 'Tip - gratuity for service',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_171',
    emoji: '🍷',
    question: '¿Qué pides primero para tomar?',
    translation: 'What do you order first to drink?',
    options: ['una bebida', 'un postre', 'la cuenta'],
    correctAnswer: 'una bebida',
    hint: 'Drink/beverage - first thing ordered',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_172',
    emoji: '🥗',
    question: '¿Qué comes antes del plato principal?',
    translation: 'What do you eat before the main course?',
    options: ['el entrante', 'el postre', 'la cuenta'],
    correctAnswer: 'el entrante',
    hint: 'Appetizer/starter - also called "aperitivo"',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_173',
    emoji: '🍰',
    question: '¿Qué comes después del plato principal?',
    translation: 'What do you eat after the main course?',
    options: ['el postre', 'el entrante', 'la sopa'],
    correctAnswer: 'el postre',
    hint: 'Dessert - sweet ending to meal',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_174',
    emoji: '🍴',
    question: '¿Con qué comes?',
    translation: 'What do you eat with?',
    options: ['los cubiertos', 'las servilletas', 'los vasos'],
    correctAnswer: 'los cubiertos',
    hint: 'Cutlery/silverware - fork, knife, spoon',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_175',
    emoji: '🥤',
    question: '¿De qué tomas agua?',
    translation: 'What do you drink water from?',
    options: ['del vaso', 'del plato', 'del tenedor'],
    correctAnswer: 'del vaso',
    hint: 'Glass - drinking vessel',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_176',
    emoji: '🍽️',
    question: '¿Dónde sirven tu comida?',
    translation: 'Where do they serve your food?',
    options: ['en el plato', 'en el vaso', 'en la servilleta'],
    correctAnswer: 'en el plato',
    hint: 'Plate/dish - where food is served',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },

  // Ordering Food (16-30)
  {
    id: 'food_177',
    emoji: '🍔',
    question: '¿Cómo pides una hamburguesa?',
    translation: 'How do you order a hamburger?',
    options: ['quisiera una hamburguesa', 'necesito un plato', 'tomo la cuenta'],
    correctAnswer: 'quisiera una hamburguesa',
    hint: 'Polite ordering phrase',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_178',
    emoji: '🥩',
    question: '¿Cómo te gusta la carne?',
    translation: 'How do you like your meat?',
    options: ['bien cocida', 'cruda', 'quemada'],
    correctAnswer: 'bien cocida',
    hint: 'Well done - level of cooking',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_179',
    emoji: '🍕',
    question: '¿Qué dices cuando quieres pizza?',
    translation: 'What do you say when you want pizza?',
    options: ['una pizza, por favor', 'la cuenta, por favor', 'el menú, por favor'],
    correctAnswer: 'una pizza, por favor',
    hint: 'Polite way to order pizza',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_180',
    emoji: '🔪',
    question: '¿Cómo pides "can I have a knife?"',
    translation: 'How do you ask \'can I have a knife?\'',
    options: ['¿me puede dar un cuchillo?', '¿puedo tener un cuchillo?', '¿me da un cuchillo?'],
    correctAnswer: '¿me puede dar un cuchillo?',
    hint: 'Can I have a knife? - "me puede dar" (can you give me), "cuchillo" (knife), essential utensil',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_181',
    emoji: '🍜',
    question: '¿Qué plato líquido pides cuando hace frío?',
    translation: 'What liquid dish do you order when it\'s cold?',
    options: ['una sopa', 'un helado', 'una ensalada'],
    correctAnswer: 'una sopa',
    hint: 'Soup - hot liquid dish',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_182',
    emoji: '🥗',
    question: '¿Qué pides si quieres comer vegetales?',
    translation: 'What do you order if you want to eat vegetables?',
    options: ['una ensalada', 'un bistec', 'un pescado'],
    correctAnswer: 'una ensalada',
    hint: 'Salad - vegetables and greens',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_183',
    emoji: '🥄',
    question: '¿Con qué comes la sopa?',
    translation: 'What do you eat soup with?',
    options: ['la cuchara', 'la cucharita', 'el cucharón'],
    correctAnswer: 'la cuchara',
    hint: 'Spoon - essential utensil for liquids, from Latin "cochlear"',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_184',
    emoji: '🥄',
    question: '¿Cómo pides "can I have a spoon?"',
    translation: 'How do you ask \'can I have a spoon?\'',
    options: ['¿me puede dar una cuchara?', '¿puedo tener una cuchara?', '¿me da una cuchara?'],
    correctAnswer: '¿me puede dar una cuchara?',
    hint: 'Can I have a spoon? - "me puede dar" (can you give me), "cuchara" (spoon - feminine), for soup/dessert',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_185',
    emoji: '🥖',
    question: '¿Qué te dan gratis en muchos restaurantes?',
    translation: 'What do they give you free at many restaurants?',
    options: ['el pan', 'el postre', 'la bebida'],
    correctAnswer: 'el pan',
    hint: 'Bread - often complimentary',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_186',
    emoji: '🧈',
    question: '¿Qué le pones al pan?',
    translation: 'What do you put on bread?',
    options: ['la mantequilla', 'el agua', 'la sal'],
    correctAnswer: 'la mantequilla',
    hint: 'Butter - spread for bread',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_187',
    emoji: '🍳',
    question: '¿Cómo se preparan los huevos en sartén?',
    translation: 'How are eggs prepared in a pan?',
    options: ['fritos', 'revueltos', 'cocidos'],
    correctAnswer: 'fritos',
    hint: '"Freír" = to fry. "Huevos fritos" are very common in Spain',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_188',
    emoji: '🍴',
    question: '¿Cómo pides "can I have a fork?"',
    translation: 'How do you ask \'can I have a fork?\'',
    options: ['¿me puede dar un tenedor?', '¿puedo tener un tenedor?', '¿me da un tenedor?'],
    correctAnswer: '¿me puede dar un tenedor?',
    hint: 'Can I have a fork? - "me puede dar" (can you give me), "tenedor" (fork), polite restaurant request',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_189',
    emoji: '🥢',
    question: '¿Con qué palitos comes comida asiática?',
    translation: 'What sticks do you eat Asian food with?',
    options: ['los palillos', 'los palillos chinos', 'los hashi'],
    correctAnswer: 'los palillos',
    hint: 'Chopsticks - "palillos" or "palillos chinos", used for Asian food',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_190',
    emoji: '🥡',
    question: '¿En qué caja blanca te dan comida china?',
    translation: 'What white box do they give you Chinese food in?',
    options: ['la caja de comida para llevar', 'el envase para llevar', 'el recipiente desechable'],
    correctAnswer: 'la caja de comida para llevar',
    hint: 'Takeout box - white container for Chinese food, also called "envase para llevar"',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_191',
    emoji: '🍱',
    question: '¿Qué caja japonesa tiene comida variada?',
    translation: 'What Japanese box has varied food?',
    options: ['el bento', 'el obento', 'el ekiben'],
    correctAnswer: 'el bento',
    hint: 'Bento box - Japanese lunch box with varied food compartments, also called "obento"',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },

  // Drinks (31-45)
  {
    id: 'food_192',
    emoji: '💧',
    question: '¿Qué bebida básica pides?',
    translation: 'What basic drink do you order?',
    options: ['agua', 'vino', 'cerveza'],
    correctAnswer: 'agua',
    hint: 'Water - most basic drink',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_193',
    emoji: '🥤',
    question: '¿Qué bebida con gas pides?',
    translation: 'What carbonated drink do you order?',
    options: ['un refresco', 'un café', 'un té'],
    correctAnswer: 'un refresco',
    hint: 'Soft drink/soda - carbonated',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_194',
    emoji: '☕',
    question: '¿Qué bebida caliente pides después de comer?',
    translation: 'What hot drink do you order after eating?',
    options: ['un café', 'un jugo', 'una cerveza'],
    correctAnswer: 'un café',
    hint: 'Coffee - hot beverage',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_195',
    emoji: '🍵',
    question: '¿Qué otra bebida caliente pides?',
    translation: 'What other hot drink do you order?',
    options: ['un té', 'un jugo', 'una leche'],
    correctAnswer: 'un té',
    hint: 'Tea - hot beverage alternative',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_196',
    emoji: '🍷',
    question: '¿Qué bebida alcohólica de uvas pides?',
    translation: 'What alcoholic drink made from grapes do you order?',
    options: ['vino', 'cerveza', 'agua'],
    correctAnswer: 'vino',
    hint: 'Wine - made from grapes',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_197',
    emoji: '🍺',
    question: '¿Qué bebida alcohólica fría pides?',
    translation: 'What cold alcoholic drink do you order?',
    options: ['una cerveza', 'un café', 'un té'],
    correctAnswer: 'una cerveza',
    hint: 'Beer - cold alcoholic drink',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_198',
    emoji: '🧃',
    question: '¿Qué bebida de frutas pides?',
    translation: 'What fruit drink do you order?',
    options: ['un jugo', 'un café', 'una cerveza'],
    correctAnswer: 'un jugo',
    hint: 'Juice - "zumo" in Spain',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_199',
    emoji: '🥛',
    question: '¿Qué bebida blanca pides con cereal?',
    translation: 'What white drink do you order with cereal?',
    options: ['leche', 'agua', 'café'],
    correctAnswer: 'leche',
    hint: 'Milk - dairy drink',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_200',
    emoji: '🧊',
    question: '¿Qué le pides al mesero para enfriar tu bebida?',
    translation: 'What do you ask the waiter for to cool your drink?',
    options: ['hielo', 'sal', 'azúcar'],
    correctAnswer: 'hielo',
    hint: 'Ice - to cool drinks',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_201',
    emoji: '🍋',
    question: '¿Qué le pones al agua para sabor?',
    translation: 'What do you put in water for flavor?',
    options: ['limón', 'sal', 'mantequilla'],
    correctAnswer: 'limón',
    hint: 'Lemon - citrus flavor',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_202',
    emoji: '🍹',
    question: '¿Qué bebida tropical pides en la playa?',
    translation: 'What tropical drink do you order at the beach?',
    options: ['un cóctel', 'un café', 'una sopa'],
    correctAnswer: 'un cóctel',
    hint: 'Cocktail - mixed drink',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_203',
    emoji: '🥃',
    question: '¿Qué licor fuerte pides?',
    translation: 'What strong liquor do you order?',
    options: ['whisky', 'jugo', 'agua'],
    correctAnswer: 'whisky',
    hint: 'Whiskey - strong spirit',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_204',
    emoji: '🍾',
    question: '¿Qué bebida especial pides para celebrar?',
    translation: 'What special drink do you order to celebrate?',
    options: ['champán', 'agua', 'café'],
    correctAnswer: 'champán',
    hint: 'Champagne - celebration drink',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_205',
    emoji: '🧋',
    question: '¿Qué bebida con burbujas es popular en Asia?',
    translation: 'What drink with bubbles is popular in Asia?',
    options: ['té de burbujas', 'café', 'cerveza'],
    correctAnswer: 'té de burbujas',
    hint: 'Bubble tea - boba drink',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_206',
    emoji: '☕',
    question: '¿Cómo pides café con leche?',
    translation: 'How do you order coffee with milk?',
    options: ['un café con leche', 'un café solo', 'un té con limón'],
    correctAnswer: 'un café con leche',
    hint: 'Coffee with milk - popular breakfast drink',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },

  // Desserts (46-55)
  {
    id: 'food_207',
    emoji: '🍰',
    question: '¿Qué postre dulce y esponjoso pides?',
    translation: 'What sweet and fluffy dessert do you order?',
    options: ['el pastel', 'la sopa', 'la ensalada'],
    correctAnswer: 'el pastel',
    hint: 'Cake - sweet dessert',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_208',
    emoji: '🍦',
    question: '¿Qué postre frío pides en verano?',
    translation: 'What cold dessert do you order in summer?',
    options: ['el helado', 'el café', 'la sopa'],
    correctAnswer: 'el helado',
    hint: 'Ice cream - frozen dessert',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_209',
    emoji: '🍮',
    question: '¿Qué postre cremoso español pides?',
    translation: 'What creamy Spanish dessert do you order?',
    options: ['el flan', 'la pizza', 'la sopa'],
    correctAnswer: 'el flan',
    hint: 'Flan - caramel custard',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_210',
    emoji: '🍪',
    question: '¿Qué postre crujiente y dulce pides con café?',
    translation: 'What crunchy and sweet dessert do you order with coffee?',
    options: ['las galletas', 'las papas', 'las verduras'],
    correctAnswer: 'las galletas',
    hint: 'Cookies - sweet baked treats',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_211',
    emoji: '🥧',
    question: '¿Qué postre con frutas pides?',
    translation: 'What dessert with fruit do you order?',
    options: ['el pie', 'el arroz', 'el pescado'],
    correctAnswer: 'el pie',
    hint: 'Pie - "tarta" or "pastel" with fruit',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_212',
    emoji: '🍫',
    question: '¿Qué postre de cacao pides?',
    translation: 'What cocoa dessert do you order?',
    options: ['el chocolate', 'el queso', 'el pan'],
    correctAnswer: 'el chocolate',
    hint: 'Chocolate - cocoa dessert',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_213',
    emoji: '🧁',
    question: '¿Qué postre pequeño individual pides?',
    translation: 'What small individual dessert do you order?',
    options: ['el cupcake', 'la pizza', 'la sopa'],
    correctAnswer: 'el cupcake',
    hint: 'Cupcake - small cake, "magdalena" in Spanish',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_214',
    emoji: '🍩',
    question: '¿Qué postre frito y redondo pides?',
    translation: 'What fried and round dessert do you order?',
    options: ['la dona', 'la ensalada', 'la sopa'],
    correctAnswer: 'la dona',
    hint: 'Donut - "donas" in Latin America',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_215',
    emoji: '🍨',
    question: '¿Qué helado con frutas y crema pides?',
    translation: 'What ice cream with fruit and cream do you order?',
    options: ['el sundae', 'el café', 'la sopa'],
    correctAnswer: 'el sundae',
    hint: 'Sundae - ice cream with toppings',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_216',
    emoji: '🍡',
    question: '¿Qué postre en palitos pides?',
    translation: 'What dessert on sticks do you order?',
    options: ['los dulces', 'las papas', 'los vegetales'],
    correctAnswer: 'los dulces',
    hint: 'Sweets/candy - "golosinas"',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },

  // Restaurant Types & Situations (56-70)
  {
    id: 'food_217',
    emoji: '🍕',
    question: '¿A qué restaurante vas para pizza?',
    translation: 'What restaurant do you go to for pizza?',
    options: ['la pizzería', 'la cafetería', 'la panadería'],
    correctAnswer: 'la pizzería',
    hint: 'Pizzeria - pizza restaurant',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_218',
    emoji: '☕',
    question: '¿Dónde tomas café y pastel?',
    translation: 'Where do you have coffee and cake?',
    options: ['la cafetería', 'la carnicería', 'la pescadería'],
    correctAnswer: 'la cafetería',
    hint: 'Café - coffee shop',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_219',
    emoji: '🍔',
    question: '¿Qué tipo de restaurante sirve comida rápida?',
    translation: 'What type of restaurant serves fast food?',
    options: ['comida rápida', 'comida gourmet', 'comida casera'],
    correctAnswer: 'comida rápida',
    hint: 'Fast food - quick service',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_220',
    emoji: '🍱',
    question: '¿Qué restaurante sirve comida para llevar?',
    translation: 'What restaurant serves food to take away?',
    options: ['comida para llevar', 'comida para aquí', 'comida para mañana'],
    correctAnswer: 'comida para llevar',
    hint: 'Takeout/to-go food',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_221',
    emoji: '🏪',
    question: '¿Dónde comes dentro del restaurante?',
    translation: 'Where do you eat inside the restaurant?',
    options: ['para comer aquí', 'para llevar', 'para mañana'],
    correctAnswer: 'para comer aquí',
    hint: 'Dine in - eat at restaurant',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_222',
    emoji: '🚗',
    question: '¿Dónde pides sin salir del carro?',
    translation: 'Where do you order without getting out of the car?',
    options: ['servicio al auto', 'servicio a casa', 'servicio a pie'],
    correctAnswer: 'servicio al auto',
    hint: 'Drive-through - car service',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_223',
    emoji: '🏠',
    question: '¿Qué servicio trae comida a tu casa?',
    translation: 'What service brings food to your house?',
    options: ['entrega a domicilio', 'comida para llevar', 'reservación'],
    correctAnswer: 'entrega a domicilio',
    hint: 'Delivery - food brought to you',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_224',
    emoji: '🍽️',
    question: '¿Qué tipo de restaurante es elegante?',
    translation: 'What type of restaurant is elegant?',
    options: ['restaurante fino', 'comida rápida', 'cafetería'],
    correctAnswer: 'restaurante fino',
    hint: 'Fine dining - upscale restaurant',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_225',
    emoji: '🎉',
    question: '¿Dónde comes mucha variedad pagando una vez?',
    translation: 'Where do you eat a lot of variety by paying once?',
    options: ['el buffet', 'la pizzería', 'la cafetería'],
    correctAnswer: 'el buffet',
    hint: 'Buffet - all-you-can-eat',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_226',
    emoji: '🍜',
    question: '¿Qué restaurante sirve comida asiática?',
    translation: 'What restaurant serves Asian food?',
    options: ['restaurante asiático', 'restaurante mexicano', 'restaurante italiano'],
    correctAnswer: 'restaurante asiático',
    hint: 'Asian restaurant - serves Asian cuisine',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_227',
    emoji: '🌮',
    question: '¿Qué restaurante sirve tacos y burritos?',
    translation: 'What restaurant serves tacos and burritos?',
    options: ['restaurante mexicano', 'restaurante chino', 'restaurante francés'],
    correctAnswer: 'restaurante mexicano',
    hint: 'Mexican restaurant',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_228',
    emoji: '🍝',
    question: '¿Qué restaurante sirve pasta y pizza?',
    translation: 'What restaurant serves pasta and pizza?',
    options: ['restaurante italiano', 'restaurante mexicano', 'restaurante chino'],
    correctAnswer: 'restaurante italiano',
    hint: 'Italian restaurant',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_229',
    emoji: '🥘',
    question: '¿Qué restaurante sirve paella?',
    translation: 'What restaurant serves paella?',
    options: ['restaurante español', 'restaurante mexicano', 'restaurante chino'],
    correctAnswer: 'restaurante español',
    hint: 'Spanish restaurant',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_230',
    emoji: '🍣',
    question: '¿Qué restaurante sirve sushi?',
    translation: 'What restaurant serves sushi?',
    options: ['restaurante japonés', 'restaurante mexicano', 'restaurante italiano'],
    correctAnswer: 'restaurante japonés',
    hint: 'Japanese restaurant',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_231',
    emoji: '🥖',
    question: '¿Qué restaurante sirve croissants?',
    translation: 'What restaurant serves croissants?',
    options: ['restaurante francés', 'restaurante mexicano', 'restaurante chino'],
    correctAnswer: 'restaurante francés',
    hint: 'French restaurant',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },

  // Dining Preferences & Requests (71-85)
  {
    id: 'food_232',
    emoji: '🌱',
    question: '¿Qué pides si no comes carne?',
    translation: 'What do you order if you don\'t eat meat?',
    options: ['comida vegetariana', 'comida con carne', 'solo carne'],
    correctAnswer: 'comida vegetariana',
    hint: 'Vegetarian food - no meat',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_233',
    emoji: '🥜',
    question: '¿Qué le dices al mesero si tienes alergia?',
    translation: 'What do you tell the waiter if you have an allergy?',
    options: ['soy alérgico a', 'me gusta', 'quisiera más'],
    correctAnswer: 'soy alérgico a',
    hint: 'Allergic to - important health info',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_234',
    emoji: '🌶️',
    question: '¿Qué dices si no quieres comida picante?',
    translation: 'What do you say if you don\'t want spicy food?',
    options: ['sin picante', 'muy picante', 'extra picante'],
    correctAnswer: 'sin picante',
    hint: 'No spicy - mild preference',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_235',
    emoji: '🧂',
    question: '¿Qué dices si no quieres sal?',
    translation: 'What do you say if you don\'t want salt?',
    options: ['sin sal', 'con sal', 'mucha sal'],
    correctAnswer: 'sin sal',
    hint: 'Without salt - dietary preference',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_236',
    emoji: '🔥',
    question: '¿Cómo pides la comida caliente?',
    translation: 'How do you order hot food?',
    options: ['bien caliente', 'frío', 'congelado'],
    correctAnswer: 'bien caliente',
    hint: 'Very hot - temperature request',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_237',
    emoji: '❄️',
    question: '¿Cómo pides la bebida muy fría?',
    translation: 'How do you order a very cold drink?',
    options: ['bien fría', 'caliente', 'sin hielo'],
    correctAnswer: 'bien fría',
    hint: 'Very cold - temperature request',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_238',
    emoji: '🍴',
    question: '¿Qué pides si necesitas tenedor?',
    translation: 'What do you ask for if you need a fork?',
    options: ['un tenedor', 'un vaso', 'un plato'],
    correctAnswer: 'un tenedor',
    hint: 'Fork - eating utensil',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_239',
    emoji: '🥄',
    question: '¿Qué pides para comer sopa?',
    translation: 'What do you ask for to eat soup?',
    options: ['una cuchara', 'un tenedor', 'un cuchillo'],
    correctAnswer: 'una cuchara',
    hint: 'Spoon - for liquid foods',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_240',
    emoji: '🔪',
    question: '¿Qué pides para cortar carne?',
    translation: 'What do you ask for to cut meat?',
    options: ['un cuchillo', 'una cuchara', 'un vaso'],
    correctAnswer: 'un cuchillo',
    hint: 'Knife - for cutting',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_241',
    emoji: '🧻',
    question: '¿Qué usas para limpiarte la boca?',
    translation: 'What do you use to clean your mouth?',
    options: ['la servilleta', 'el menú', 'el plato'],
    correctAnswer: 'la servilleta',
    hint: 'Napkin - for cleaning',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_242',
    emoji: '🥤',
    question: '¿Qué pides para tomar tu refresco?',
    translation: 'What do you ask for to drink your soda?',
    options: ['un popote', 'un plato', 'un tenedor'],
    correctAnswer: 'un popote',
    hint: 'Straw - "pajita" in Spain, "bombilla" in some regions',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_243',
    emoji: '📦',
    question: '¿Qué pides para llevar lo que sobra?',
    translation: 'What do you ask for to take what\'s left over?',
    options: ['una caja para llevar', 'otro plato', 'la cuenta'],
    correctAnswer: 'una caja para llevar',
    hint: 'Takeout box - "doggy bag"',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_244',
    emoji: '🧊',
    question: '¿Qué dices si no quieres hielo?',
    translation: 'What do you say if you don\'t want ice?',
    options: ['sin hielo', 'con hielo', 'mucho hielo'],
    correctAnswer: 'sin hielo',
    hint: 'Without ice - drink preference',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_245',
    emoji: '🍋',
    question: '¿Qué pides para tu té?',
    translation: 'What do you ask for for your tea?',
    options: ['limón', 'carne', 'pescado'],
    correctAnswer: 'limón',
    hint: 'Lemon - for tea',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_246',
    emoji: '🍯',
    question: '¿Qué le pones al té para endulzar?',
    translation: 'What do you put in tea to sweeten it?',
    options: ['miel', 'sal', 'pimienta'],
    correctAnswer: 'miel',
    hint: 'Honey - natural sweetener',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },

  // Final phrases & situations (86-100)
  {
    id: 'food_247',
    emoji: '👍',
    question: '¿Qué dices cuando la comida está deliciosa?',
    translation: 'What do you say when the food is delicious?',
    options: ['está delicioso', 'está horrible', 'está frío'],
    correctAnswer: 'está delicioso',
    hint: 'It\'s delicious - compliment',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_248',
    emoji: '😋',
    question: '¿Qué dices cuando tienes hambre?',
    translation: 'What do you say when you\'re hungry?',
    options: ['tengo hambre', 'tengo sed', 'tengo sueño'],
    correctAnswer: 'tengo hambre',
    hint: 'I\'m hungry - need food',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_249',
    emoji: '🥤',
    question: '¿Qué dices cuando tienes sed?',
    translation: 'What do you say when you\'re thirsty?',
    options: ['tengo sed', 'tengo hambre', 'tengo frío'],
    correctAnswer: 'tengo sed',
    hint: 'I\'m thirsty - need drink',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_250',
    emoji: '😊',
    question: '¿Qué dices al mesero al final?',
    translation: 'What do you say to the waiter at the end?',
    options: ['gracias', 'hola', 'adiós'],
    correctAnswer: 'gracias',
    hint: 'Thank you - show appreciation',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_251',
    emoji: '🙏',
    question: '¿Qué dices para ser cortés al pedir?',
    translation: 'What do you say to be polite when ordering?',
    options: ['por favor', 'ahora', 'nunca'],
    correctAnswer: 'por favor',
    hint: 'Please - polite request',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_252',
    emoji: '⏰',
    question: '¿A qué hora comes en la mañana?',
    translation: 'What time do you eat in the morning?',
    options: ['el desayuno', 'el almuerzo', 'la cena'],
    correctAnswer: 'el desayuno',
    hint: 'Breakfast - morning meal',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_253',
    emoji: '🌞',
    question: '¿A qué hora comes a mediodía?',
    translation: 'What time do you eat at noon?',
    options: ['el almuerzo', 'el desayuno', 'la cena'],
    correctAnswer: 'el almuerzo',
    hint: 'Lunch - midday meal',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_254',
    emoji: '🌙',
    question: '¿A qué hora comes en la noche?',
    translation: 'What time do you eat at night?',
    options: ['la cena', 'el desayuno', 'el almuerzo'],
    correctAnswer: 'la cena',
    hint: 'Dinner - evening meal',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_255',
    emoji: '🔄',
    question: '¿Qué dices para pedir más?',
    translation: 'What do you say to ask for more?',
    options: ['más, por favor', 'menos, por favor', 'nada más'],
    correctAnswer: 'más, por favor',
    hint: 'More, please - want additional',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_256',
    emoji: '✋',
    question: '¿Qué dices cuando no quieres más?',
    translation: 'What do you say when you don\'t want more?',
    options: ['no más, gracias', 'más, por favor', 'todo'],
    correctAnswer: 'no más, gracias',
    hint: 'No more, thanks - satisfied',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_257',
    emoji: '🙋',
    question: '¿Qué dices para llamar al mesero?',
    translation: 'What do you say to call the waiter?',
    options: ['disculpe', 'adiós', 'hola'],
    correctAnswer: 'disculpe',
    hint: 'Excuse me - get attention',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_258',
    emoji: '❓',
    question: '¿Qué preguntas para saber opciones?',
    translation: 'What do you ask to know the options?',
    options: ['¿qué me recomienda?', '¿cuánto cuesta?', '¿dónde está el baño?'],
    correctAnswer: '¿qué me recomienda?',
    hint: 'What do you recommend? - ask for suggestion',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_259',
    emoji: '💵',
    question: '¿Qué preguntas para saber el precio?',
    translation: 'What do you ask to know the price?',
    options: ['¿cuánto cuesta?', '¿qué me recomienda?', '¿dónde está?'],
    correctAnswer: '¿cuánto cuesta?',
    hint: 'How much does it cost? - price question',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_260',
    emoji: '🚻',
    question: '¿Qué preguntas para encontrar el baño?',
    translation: 'What do you ask to find the bathroom?',
    options: ['¿dónde está el baño?', '¿cuánto cuesta?', '¿qué me recomienda?'],
    correctAnswer: '¿dónde está el baño?',
    hint: 'Where is the bathroom? - important question',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_261',
    emoji: '🎊',
    question: '¿Qué dices para disfrutar la comida?',
    translation: 'What do you say to enjoy the meal?',
    options: ['¡buen provecho!', '¡adiós!', '¡hola!'],
    correctAnswer: '¡buen provecho!',
    hint: 'Enjoy your meal! - dining greeting',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_262',
    emoji: '🚬',
    question: '¿Qué está prohibido en muchos restaurantes?',
    translation: 'What is prohibited in many restaurants?',
    options: ['fumar', 'comer', 'beber'],
    correctAnswer: 'fumar',
    hint: 'Smoking - not allowed in most restaurants, "prohibido fumar"',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_263',
    emoji: '🏮',
    question: '¿Qué ilumina y decora un restaurante elegante?',
    translation: 'What illuminates and decorates an elegant restaurant?',
    options: ['las lámparas', 'las mesas', 'los platos'],
    correctAnswer: 'las lámparas',
    hint: 'Lamps/lanterns - decorative lighting creates ambiance in fancy restaurants',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
];
