/**
 * FOOD Category Questions
 * Category: food
 */

export const foodQuestions = [
// Fruits (20 questions)
  {
    id: 'food_001',
    emoji: '🍉',
    question: '¿Qué fruta roja comes en el verano?',
    options: ['la sandía', 'la fresa', 'la cereza'],
    correctAnswer: 'la sandía',
    hint: 'In Spanish, "sandía" comes from Arabic - reflects Spain\'s Moorish history',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_002',
    emoji: '🍌',
    question: '¿Qué fruta es amarilla y larga?',
    options: ['el plátano', 'el limón', 'el mango'],
    correctAnswer: 'el plátano',
    hint: 'Latin America uses "banano" - "plátano" can also mean plantain',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_003',
    emoji: '🍎',
    question: '¿Qué fruta puede ser roja o verde?',
    options: ['la manzana', 'la pera', 'la uva'],
    correctAnswer: 'la manzana',
    hint: 'Remember: "la manzana" (feminine) - fruit names often end in -a',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_004',
    emoji: '🍊',
    question: '¿Qué fruta tiene mucha vitamina C?',
    options: ['la naranja', 'el limón', 'la mandarina'],
    correctAnswer: 'la naranja',
    hint: 'Same word is both the fruit AND the color in Spanish',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_005',
    emoji: '🍇',
    question: '¿Con qué fruta se hace el vino?',
    options: ['las uvas', 'las ciruelas', 'las moras'],
    correctAnswer: 'las uvas',
    hint: 'Spain is the 3rd largest wine producer - "vino de uvas"',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_006',
    emoji: '🍓',
    question: '¿Qué fruta roja pequeña es dulce?',
    options: ['la fresa', 'la cereza', 'la mora'],
    correctAnswer: 'la fresa',
    hint: 'In Latin America, also called "frutilla" in some regions',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_007',
    emoji: '🍒',
    question: '¿Qué fruta pequeña tiene hueso?',
    options: ['la cereza', 'la aceituna', 'la ciruela'],
    correctAnswer: 'la cereza',
    hint: '"Cereza" comes from Latin "ceresia" - related to English "cherry"',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_008',
    emoji: '🍑',
    question: '¿Qué fruta es rosada y peluda?',
    options: ['el melocotón', 'el durazno', 'el albaricoque'],
    correctAnswer: 'el melocotón',
    hint: 'In Latin America, called "durazno" - both words mean peach',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_009',
    emoji: '🍍',
    question: '¿Qué fruta tropical es amarilla por dentro?',
    options: ['la piña', 'el mango', 'la guayaba'],
    correctAnswer: 'la piña',
    hint: 'Tropical fruit with spiky skin',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_010',
    emoji: '🥝',
    question: '¿Qué fruta es verde por dentro con semillas negras?',
    options: ['el kiwi', 'la guayaba', 'la papaya'],
    correctAnswer: 'el kiwi',
    hint: 'Originally from China, named after New Zealand\'s national bird',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_011',
    emoji: '🍋',
    question: '¿Qué fruta ácida es amarilla?',
    options: ['el limón', 'la lima', 'la toronja'],
    correctAnswer: 'el limón',
    hint: 'Sour yellow citrus',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_012',
    emoji: '🥭',
    question: '¿Qué fruta tropical es dulce y anaranjada?',
    options: ['el mango', 'la papaya', 'el durazno'],
    correctAnswer: 'el mango',
    hint: 'Sweet tropical fruit with a large pit',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_013',
    emoji: '🍐',
    question: '¿Qué fruta tiene forma de campana?',
    options: ['la pera', 'la manzana', 'el higo'],
    correctAnswer: 'la pera',
    hint: 'Shaped like a light bulb',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_014',
    emoji: '🥥',
    question: '¿De qué fruta se obtiene leche vegetal?',
    options: ['el coco', 'la almendra', 'la avena'],
    correctAnswer: 'el coco',
    hint: 'Tropical fruit - "agua de coco" (coconut water) is very popular',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_015',
    emoji: '🥑',
    question: '¿Qué fruta verde se usa en guacamole?',
    options: ['el aguacate', 'el pepino', 'la lima'],
    correctAnswer: 'el aguacate',
    hint: 'From Nahuatl "ahuacatl" - essential in Mexican cuisine',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_016',
    emoji: '🫐',
    question: '¿Qué fruta pequeña es azul?',
    options: ['el arándano', 'la mora', 'la ciruela'],
    correctAnswer: 'el arándano',
    hint: 'Blueberry in Spanish - "azul" (blue) + "arándano" (berry)',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_017',
    emoji: '🍈',
    question: '¿Qué fruta es como una sandía pequeña?',
    options: ['el melón', 'la guayaba', 'la granada'],
    correctAnswer: 'el melón',
    hint: 'Cantaloupe or honeydew melon - refreshing summer fruit',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_018',
    emoji: '🍅',
    question: '¿Qué fruta roja se usa en ensaladas?',
    options: ['el tomate', 'el pimiento', 'la remolacha'],
    correctAnswer: 'el tomate',
    hint: 'Red and used in salads and sauces',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_019',
    emoji: '🫒',
    question: '¿De qué fruta se hace el aceite de oliva?',
    options: ['la aceituna', 'la nuez', 'el aguacate'],
    correctAnswer: 'la aceituna',
    hint: 'Spain produces over 40% of world\'s olive oil - "aceite" comes from "aceituna"',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_020',
    emoji: '🍆',
    question: '¿Qué verdura es morada y larga?',
    options: ['la berenjena', 'la remolacha', 'la col morada'],
    correctAnswer: 'la berenjena',
    hint: 'Eggplant - name comes from Arabic "al-bāḏinjān", showing Moorish influence',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },

  // Vegetables (15 questions)
  {
    id: 'food_021',
    emoji: '🥕',
    question: '¿Qué verdura naranja comen los conejos?',
    options: ['la zanahoria', 'la calabaza', 'el boniato'],
    correctAnswer: 'la zanahoria',
    hint: 'Orange root vegetable, good for eyes',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_022',
    emoji: '🥔',
    question: '¿Con qué verdura se hacen las papas fritas?',
    options: ['la papa', 'el boniato', 'la yuca'],
    correctAnswer: 'la papa',
    hint: 'Starchy root vegetable, can be fried',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_023',
    emoji: '🧅',
    question: '¿Qué verdura te hace llorar cuando la cortas?',
    options: ['la cebolla', 'el ajo', 'el cebollino'],
    correctAnswer: 'la cebolla',
    hint: 'Makes you cry when you cut it',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_024',
    emoji: '🧄',
    question: '¿Qué ingrediente pequeño tiene olor fuerte?',
    options: ['el ajo', 'la cebolla', 'el puerro'],
    correctAnswer: 'el ajo',
    hint: 'Essential in Spanish cooking - "un diente de ajo" (a clove of garlic)',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_025',
    emoji: '🌽',
    question: '¿Qué verdura amarilla tiene granos?',
    options: ['el maíz', 'el elote', 'el choclo'],
    correctAnswer: 'el maíz',
    hint: 'Yellow kernels, makes popcorn',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_026',
    emoji: '🥒',
    question: '¿Qué verdura verde y larga está en las ensaladas?',
    options: ['el pepino', 'el calabacín', 'el apio'],
    correctAnswer: 'el pepino',
    hint: 'Green and crunchy, mostly water',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_027',
    emoji: '🥬',
    question: '¿Qué verdura verde se come en ensaladas?',
    options: ['la lechuga', 'la espinaca', 'la acelga'],
    correctAnswer: 'la lechuga',
    hint: 'Green leafy base for salads',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_028',
    emoji: '🥦',
    question: '¿Qué verdura verde parece un árbol pequeño?',
    options: ['el brócoli', 'la coliflor', 'el brócoli rabe'],
    correctAnswer: 'el brócoli',
    hint: 'Green vegetable that looks like a tiny tree',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_029',
    emoji: '🫑',
    question: '¿Qué verdura puede ser roja, verde o amarilla?',
    options: ['el pimiento', 'el tomate', 'el chile'],
    correctAnswer: 'el pimiento',
    hint: 'Bell-shaped vegetable, can be many colors',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_030',
    emoji: '🌶️',
    question: '¿Qué ingrediente es muy picante?',
    options: ['el chile', 'el pimiento', 'el jalapeño'],
    correctAnswer: 'el chile',
    hint: 'From Nahuatl - Mexico has hundreds of varieties of chiles',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_031',
    emoji: '🥜',
    question: '¿De qué se hace la mantequilla de maní?',
    options: ['el cacahuate', 'la almendra', 'la avellana'],
    correctAnswer: 'el cacahuate',
    hint: 'Also called "maní" in many countries - peanut grows underground',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_032',
    emoji: '🍄',
    question: '¿Qué crece en lugares húmedos?',
    options: ['el champiñón', 'la seta', 'el hongo'],
    correctAnswer: 'el champiñón',
    hint: 'From French "champignon" - most common edible mushroom variety',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_033',
    emoji: '🫘',
    question: '¿Qué se usa en los frijoles?',
    options: ['los frijoles', 'las habas', 'las lentejas'],
    correctAnswer: 'los frijoles',
    hint: 'Staple of Mexican cuisine - "frijoles refritos" (refried beans)',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_034',
    emoji: '🎃',
    question: '¿Qué verdura naranja se usa en Halloween?',
    options: ['la calabaza', 'la zanahoria', 'el boniato'],
    correctAnswer: 'la calabaza',
    hint: 'Used for jack-o-lanterns - also makes delicious soup and pie',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_035',
    emoji: '🥗',
    question: '¿Qué plato tiene muchas verduras frescas?',
    options: ['la ensalada', 'la sopa', 'el guiso'],
    correctAnswer: 'la ensalada',
    hint: 'From French "salade" - raw vegetables typically with dressing',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },

  // Main Dishes & Proteins (20 questions)
  {
    id: 'food_036',
    emoji: '🍕',
    question: '¿Qué comida italiana es redonda?',
    options: ['la pizza', 'la focaccia', 'la calzone'],
    correctAnswer: 'la pizza',
    hint: 'Italian dish with cheese and toppings',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_037',
    emoji: '🍔',
    question: '¿Qué tiene carne entre dos panes?',
    options: ['la hamburguesa', 'el sándwich', 'el bocadillo'],
    correctAnswer: 'la hamburguesa',
    hint: 'Meat patty in a bun',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_038',
    emoji: '🌭',
    question: '¿Qué comida tiene salchicha en pan largo?',
    options: ['el hot dog', 'el chorizo', 'la salchicha'],
    correctAnswer: 'el hot dog',
    hint: 'English name used in Spanish - also called "perro caliente" literally',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_039',
    emoji: '🌮',
    question: '¿Qué comida mexicana usa tortilla doblada?',
    options: ['el taco', 'la quesadilla', 'la enchilada'],
    correctAnswer: 'el taco',
    hint: 'Mexican tortilla with fillings',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_040',
    emoji: '🌯',
    question: '¿Qué comida mexicana está enrollada?',
    options: ['el burrito', 'la enchilada', 'el taco'],
    correctAnswer: 'el burrito',
    hint: 'Literally means "little donkey" - large flour tortilla wrapped around filling',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_041',
    emoji: '🥙',
    question: '¿Qué pan árabe está relleno?',
    options: ['la pita', 'el naan', 'la tortilla'],
    correctAnswer: 'la pita',
    hint: 'Middle Eastern flatbread with a pocket - perfect for stuffing with falafel',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_042',
    emoji: '🥪',
    question: '¿Qué tiene ingredientes entre dos rebanadas de pan?',
    options: ['el sándwich', 'el bocadillo', 'el emparedado'],
    correctAnswer: 'el sándwich',
    hint: 'Named after Earl of Sandwich - "emparedado" is the pure Spanish word',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_043',
    emoji: '🍗',
    question: '¿Qué carne de ave es muy común?',
    options: ['el pollo', 'el pavo', 'el pato'],
    correctAnswer: 'el pollo',
    hint: 'White meat that comes from birds',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_044',
    emoji: '🥩',
    question: '¿Qué comes en un asado?',
    options: ['la carne', 'el bistec', 'el filete'],
    correctAnswer: 'la carne',
    hint: 'Red meat from animals',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_045',
    emoji: '🥓',
    question: '¿Qué carne frita comes en el desayuno?',
    options: ['el tocino', 'el jamón', 'la panceta'],
    correctAnswer: 'el tocino',
    hint: 'Crispy bacon strips - in some regions called "panceta" or "beicon"',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_046',
    emoji: '🍖',
    question: '¿Qué es carne con hueso?',
    options: ['la costilla', 'la chuleta', 'el filete'],
    correctAnswer: 'la costilla',
    hint: 'Ribs - popular in BBQ, from "costa" (rib cage)',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_047',
    emoji: '🍤',
    question: '¿Qué marisco rosado es pequeño?',
    options: ['el camarón', 'la gamba', 'la langosta'],
    correctAnswer: 'el camarón',
    hint: 'Shrimp - in Spain called "gamba", essential in paella',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_048',
    emoji: '🍣',
    question: '¿Qué comida japonesa tiene pescado crudo?',
    options: ['el sushi', 'el sashimi', 'el ramen'],
    correctAnswer: 'el sushi',
    hint: 'Japanese rice and fish rolls',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_049',
    emoji: '🍜',
    question: '¿Qué sopa asiática tiene fideos?',
    options: ['el ramen', 'el pho', 'el udon'],
    correctAnswer: 'el ramen',
    hint: 'Japanese noodle soup - very popular worldwide, many varieties',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_050',
    emoji: '🍝',
    question: '¿Qué comida italiana tiene fideos?',
    options: ['la pasta', 'los espaguetis', 'los tallarines'],
    correctAnswer: 'la pasta',
    hint: 'In Spanish, "pasta" is feminine (la pasta) unlike English',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_051',
    emoji: '🍲',
    question: '¿Qué plato caliente tiene muchos ingredientes?',
    options: ['el guiso', 'el estofado', 'el cocido'],
    correctAnswer: 'el guiso',
    hint: 'From "guisar" (to cook/stew) - hearty one-pot meal',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_052',
    emoji: '🥘',
    question: '¿Qué plato español tiene arroz y mariscos?',
    options: ['la paella', 'el arroz con pollo', 'el risotto'],
    correctAnswer: 'la paella',
    hint: 'From Valencia, Spain - named after the pan "paellera"',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_053',
    emoji: '🍳',
    question: '¿Cómo se preparan los huevos en sartén?',
    options: ['fritos', 'revueltos', 'cocidos'],
    correctAnswer: 'fritos',
    hint: '"Freír" = to fry. "Huevos fritos" are very common in Spain',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_054',
    emoji: '🥚',
    question: '¿Qué ponen las gallinas?',
    options: ['el huevo', 'el pollito', 'la pluma'],
    correctAnswer: 'el huevo',
    hint: '"Huevo" comes from Latin "ovum" - related to "oval"',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_055',
    emoji: '🍟',
    question: '¿Qué acompaña a la hamburguesa?',
    options: ['las papas fritas', 'las patatas bravas', 'el arroz'],
    correctAnswer: 'las papas fritas',
    hint: 'French fries - in Spain "patatas fritas", classic side dish',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },

  // Bread & Grains (10 questions)
  {
    id: 'food_056',
    emoji: '🍞',
    question: '¿Qué haces con harina en el horno?',
    options: ['el pan', 'la galleta', 'el pastel'],
    correctAnswer: 'el pan',
    hint: 'Baked from flour, basic food',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_057',
    emoji: '🥖',
    question: '¿Qué pan francés es largo?',
    options: ['la baguette', 'el baguette', 'la barra'],
    correctAnswer: 'la baguette',
    hint: 'French stick bread - crusty outside, soft inside, iconic shape',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_058',
    emoji: '🥐',
    question: '¿Qué pan francés tiene forma de media luna?',
    options: ['el croissant', 'la medialuna', 'el brioche'],
    correctAnswer: 'el croissant',
    hint: 'French crescent pastry - buttery, flaky layers, breakfast favorite',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_059',
    emoji: '🥨',
    question: '¿Qué pan tiene forma de nudo?',
    options: ['el pretzel', 'el bretzel', 'el nudo'],
    correctAnswer: 'el pretzel',
    hint: 'German twisted bread - salty, often eaten with mustard in Germany',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_060',
    emoji: '🥯',
    question: '¿Qué pan redondo tiene agujero?',
    options: ['el bagel', 'la dona', 'el rosquilla'],
    correctAnswer: 'el bagel',
    hint: 'Jewish bread - boiled then baked, popular for breakfast sandwiches',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_061',
    emoji: '🫓',
    question: '¿Qué pan delgado y plano se usa en tacos?',
    options: ['la tortilla', 'la pita', 'el naan'],
    correctAnswer: 'la tortilla',
    hint: 'Flat bread used in Mexican food',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_062',
    emoji: '🥞',
    question: '¿Qué comes en el desayuno con miel?',
    options: ['los panqueques', 'las crepes', 'los waffles'],
    correctAnswer: 'los panqueques',
    hint: 'Flat breakfast cakes - also called "hot cakes" or "tortitas"',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_063',
    emoji: '🧇',
    question: '¿Qué tiene cuadros y se come con miel?',
    options: ['el waffle', 'el panqueque', 'la crepe'],
    correctAnswer: 'el waffle',
    hint: 'Belgian breakfast with grid pattern - crispy pockets hold syrup',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_064',
    emoji: '🍚',
    question: '¿Qué grano blanco se come en Asia?',
    options: ['el arroz', 'el trigo', 'la cebada'],
    correctAnswer: 'el arroz',
    hint: 'White or brown grains, staple in Asia',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_065',
    emoji: '🥣',
    question: '¿Qué desayuno tiene leche y cereal?',
    options: ['el cereal', 'la avena', 'el muesli'],
    correctAnswer: 'el cereal',
    hint: 'Breakfast food eaten with milk',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },

  // Dairy & Cheese (8 questions)
  {
    id: 'food_066',
    emoji: '🥛',
    question: '¿Qué bebida blanca dan las vacas?',
    options: ['la leche', 'el yogur', 'la crema'],
    correctAnswer: 'la leche',
    hint: 'White drink from cows',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_067',
    emoji: '🧀',
    question: '¿Qué se hace con leche fermentada?',
    options: ['el queso', 'el yogur', 'la crema'],
    correctAnswer: 'el queso',
    hint: 'Made from milk, often yellow',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_068',
    emoji: '🧈',
    question: '¿Qué untas en el pan tostado?',
    options: ['la mantequilla', 'la margarina', 'la mermelada'],
    correctAnswer: 'la mantequilla',
    hint: 'Spread made from cream',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_069',
    emoji: '🍦',
    question: '¿Qué postre frío de leche comes en verano?',
    options: ['el helado', 'el sorbete', 'el flan'],
    correctAnswer: 'el helado',
    hint: 'Frozen sweet treat',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_070',
    emoji: '🍨',
    question: '¿Qué postre frío se sirve en copa?',
    options: ['el helado', 'el sundae', 'la nieve'],
    correctAnswer: 'el helado',
    hint: 'Frozen sweet treat',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_071',
    emoji: '🧊',
    question: '¿Qué pones en las bebidas para enfriarlas?',
    options: ['el hielo', 'el agua fría', 'la nieve'],
    correctAnswer: 'el hielo',
    hint: 'Frozen water cubes - "hielo" comes from Latin "gelu" (frost)',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_072',
    emoji: '🥄',
    question: '¿Con qué comes la sopa?',
    options: ['la cuchara', 'la cucharita', 'el cucharón'],
    correctAnswer: 'la cuchara',
    hint: 'Spoon - essential utensil for liquids, from Latin "cochlear"',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_073',
    emoji: '🍮',
    question: '¿Qué postre dulce tiene caramelo?',
    options: ['el flan', 'el pudín', 'la natilla'],
    correctAnswer: 'el flan',
    hint: 'Custard dessert - very popular in Spain and Latin America',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },

  // Drinks (12 questions)
  {
    id: 'food_074',
    emoji: '☕',
    question: '¿Qué bebida caliente tomas por la mañana?',
    options: ['el café', 'el té', 'el chocolate caliente'],
    correctAnswer: 'el café',
    hint: 'Brown drink that wakes you up',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_075',
    emoji: '🍵',
    question: '¿Qué bebida caliente tiene hierbas?',
    options: ['el té', 'la infusión', 'la manzanilla'],
    correctAnswer: 'el té',
    hint: 'Hot drink made from leaves',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_076',
    emoji: '🧃',
    question: '¿Qué bebes de frutas?',
    options: ['el jugo', 'el zumo', 'el néctar'],
    correctAnswer: 'el jugo',
    hint: 'Liquid from squeezed fruits',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_077',
    emoji: '🥤',
    question: '¿Qué bebida gaseosa tomas con popote?',
    options: ['el refresco', 'la gaseosa', 'la soda'],
    correctAnswer: 'el refresco',
    hint: 'Fizzy sweet drink',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_078',
    emoji: '🧋',
    question: '¿Qué bebida taiwanesa tiene bolitas?',
    options: ['el bubble tea', 'el boba', 'el té con leche'],
    correctAnswer: 'el bubble tea',
    hint: 'Taiwanese tea with tapioca pearls - "boba" means bubbles',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_079',
    emoji: '🍶',
    question: '¿Qué bebida japonesa se hace de arroz?',
    options: ['el sake', 'el shochu', 'el amazake'],
    correctAnswer: 'el sake',
    hint: 'Traditional Japanese rice wine - served warm or cold in ceremonies',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_080',
    emoji: '🍺',
    question: '¿Qué bebida alcohólica es amarilla?',
    options: ['la cerveza', 'la sidra', 'el vino blanco'],
    correctAnswer: 'la cerveza',
    hint: 'Beer - Spain\'s popular brands include Mahou, Estrella, and San Miguel',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_081',
    emoji: '🍷',
    question: '¿Qué bebida se hace de uvas?',
    options: ['el vino', 'el mosto', 'el jerez'],
    correctAnswer: 'el vino',
    hint: 'Wine - "vino tinto" (red) and "vino blanco" (white) are most common',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_082',
    emoji: '🥂',
    question: '¿Qué bebes para celebrar?',
    options: ['el champán', 'el cava', 'el prosecco'],
    correctAnswer: 'el champán',
    hint: 'Sparkling wine from Champagne region - "cava" is Spanish version',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_083',
    emoji: '🍹',
    question: '¿Qué bebida tropical tiene sombrilla?',
    options: ['el cóctel', 'el trago', 'la bebida'],
    correctAnswer: 'el cóctel',
    hint: 'Mixed alcoholic drink - piña colada and mojito are famous examples',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_084',
    emoji: '🍸',
    question: '¿Qué bebida se sirve en copa triangular?',
    options: ['el martini', 'el cosmopolitan', 'el manhattan'],
    correctAnswer: 'el martini',
    hint: 'Classic cocktail - gin or vodka with vermouth, iconic V-shaped glass',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_085',
    emoji: '🧉',
    question: '¿Qué bebida tradicional argentina se toma con bombilla?',
    options: ['el mate', 'el tereré', 'la yerba'],
    correctAnswer: 'el mate',
    hint: 'South American herbal tea - social drink shared in a gourd with metal straw',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },

  // Desserts & Sweets (15 questions)
  {
    id: 'food_086',
    emoji: '🍰',
    question: '¿Qué postre dulce comes en cumpleaños?',
    options: ['el pastel', 'la tarta', 'el bizcocho'],
    correctAnswer: 'el pastel',
    hint: 'Sweet baked celebration food',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_087',
    emoji: '🎂',
    question: '¿Qué tiene velas en tu cumpleaños?',
    options: ['el pastel', 'la tarta', 'el bizcocho'],
    correctAnswer: 'el pastel',
    hint: 'Sweet baked celebration food',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_088',
    emoji: '🧁',
    question: '¿Qué es un pastel pequeño individual?',
    options: ['el cupcake', 'la magdalena', 'el muffin'],
    correctAnswer: 'el cupcake',
    hint: 'Individual-sized cake with frosting - "magdalena" in Spanish but "cupcake" widely used',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_089',
    emoji: '🥧',
    question: '¿Qué postre tiene frutas en masa?',
    options: ['el pay', 'la tarta', 'el pastel de manzana'],
    correctAnswer: 'el pay',
    hint: 'Pie - "pay" from English, "tarta" in Spain, filled with fruit or cream',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_090',
    emoji: '🍫',
    question: '¿Qué dulce marrón es de cacao?',
    options: ['el chocolate', 'el bombón', 'el cacao'],
    correctAnswer: 'el chocolate',
    hint: 'Sweet brown candy from cacao',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_091',
    emoji: '🍬',
    question: '¿Qué dulce pequeño chupas?',
    options: ['el caramelo', 'la paleta', 'el chicle'],
    correctAnswer: 'el caramelo',
    hint: 'Hard candy - "caramelo" also means caramel sauce in cooking',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_092',
    emoji: '🍭',
    question: '¿Qué dulce está en un palito?',
    options: ['la paleta', 'el chupete', 'el pirulí'],
    correctAnswer: 'la paleta',
    hint: 'Lollipop - "paleta" means little stick, also used for popsicles',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_093',
    emoji: '🍪',
    question: '¿Qué postre crujiente tiene chispas de chocolate?',
    options: ['la galleta', 'la cookie', 'el biscocho'],
    correctAnswer: 'la galleta',
    hint: 'Small sweet baked snack',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_094',
    emoji: '🍩',
    question: '¿Qué dulce redondo tiene agujero?',
    options: ['la dona', 'la rosquilla', 'el buñuelo'],
    correctAnswer: 'la dona',
    hint: 'Donut - fried dough with hole, "rosquilla" in Spain, "dona" from English',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_095',
    emoji: '🍯',
    question: '¿Qué hacen las abejas?',
    options: ['la miel', 'la cera', 'el néctar'],
    correctAnswer: 'la miel',
    hint: 'Honey - bees collect nectar, "miel" from Latin "mel"',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_096',
    emoji: '🍿',
    question: '¿Qué comes en el cine?',
    options: ['las palomitas', 'los nachos', 'las papas fritas'],
    correctAnswer: 'las palomitas',
    hint: 'Popcorn - "palomitas" means little doves (they look like flying doves when popped)',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_097',
    emoji: '🥠',
    question: '¿Qué galleta china tiene mensaje dentro?',
    options: ['la galleta de la fortuna', 'el fortune cookie', 'la galleta china'],
    correctAnswer: 'la galleta de la fortuna',
    hint: 'Fortune cookie - invented in California, not China, but popular worldwide',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_098',
    emoji: '🧁',
    question: '¿Qué postre pequeño tiene papel rizado?',
    options: ['la magdalena', 'el cupcake', 'el muffin'],
    correctAnswer: 'la magdalena',
    hint: 'Spanish muffin - traditional from Madeleine region, similar to cupcake',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_099',
    emoji: '🍡',
    question: '¿Qué dulce japonés está en palitos?',
    options: ['el dango', 'el mochi', 'el wagashi'],
    correctAnswer: 'el dango',
    hint: 'Japanese rice dumpling on skewers - sweet, chewy, colorful',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_100',
    emoji: '🥮',
    question: '¿Qué pastel chino se come en otoño?',
    options: ['el pastel de luna', 'el mooncake', 'el pastel chino'],
    correctAnswer: 'el pastel de luna',
    hint: 'Mooncake - eaten during Mid-Autumn Festival, dense sweet filling',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },

  // More Fruits (10 questions)
  {
    id: 'food_101',
    emoji: '🍑',
    question: '¿Qué fruta de verano tiene piel peluda?',
    options: ['el durazno', 'el melocotón', 'el albaricoque'],
    correctAnswer: 'el durazno',
    hint: 'Peach - "durazno" in Latin America, "melocotón" in Spain (same fruit)',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_102',
    emoji: '🥭',
    question: '¿Qué fruta tropical tiene un hueso grande?',
    options: ['el mango', 'el aguacate', 'el durazno'],
    correctAnswer: 'el mango',
    hint: 'Sweet tropical fruit with a large pit',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_103',
    emoji: '🍌',
    question: '¿Qué fruta comen los monos?',
    options: ['el plátano', 'el banano', 'la banana'],
    correctAnswer: 'el plátano',
    hint: 'Monkeys love this curved fruit',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_104',
    emoji: '🍋',
    question: '¿Qué fruta usas para hacer limonada?',
    options: ['el limón', 'la lima', 'la toronja'],
    correctAnswer: 'el limón',
    hint: 'Sour yellow citrus',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_105',
    emoji: '🥝',
    question: '¿Qué fruta peluda es verde por dentro?',
    options: ['el kiwi', 'la guayaba', 'la papaya'],
    correctAnswer: 'el kiwi',
    hint: 'Brown fuzzy outside, bright green inside with tiny black seeds',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_106',
    emoji: '🍐',
    question: '¿Qué fruta es dulce y tiene forma de bombilla?',
    options: ['la pera', 'la manzana', 'el higo'],
    correctAnswer: 'la pera',
    hint: 'Shaped like a light bulb',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_107',
    emoji: '🍓',
    question: '¿Qué fruta roja tiene semillas por fuera?',
    options: ['la fresa', 'la mora', 'la frambuesa'],
    correctAnswer: 'la fresa',
    hint: 'Small red berry with seeds on the outside',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_108',
    emoji: '🍇',
    question: '¿Qué fruta crece en racimos?',
    options: ['las uvas', 'las moras', 'los arándanos'],
    correctAnswer: 'las uvas',
    hint: 'Small fruits that grow in bunches',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_109',
    emoji: '🍒',
    question: '¿Qué fruta roja pequeña viene en pares?',
    options: ['la cereza', 'la aceituna', 'la ciruela'],
    correctAnswer: 'la cereza',
    hint: 'Cherries grow in pairs on the tree - sweet or sour varieties',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_110',
    emoji: '🍈',
    question: '¿Qué fruta verde es dulce por dentro?',
    options: ['el melón', 'la sandía', 'la guayaba'],
    correctAnswer: 'el melón',
    hint: 'Green-skinned melon variety - honeydew or cantaloupe, very sweet',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },

  // More Proteins & Seafood (15 questions)
  {
    id: 'food_111',
    emoji: '🐟',
    question: '¿Qué comes del mar?',
    options: ['el pescado', 'el salmón', 'el atún'],
    correctAnswer: 'el pescado',
    hint: 'Protein from the sea',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_112',
    emoji: '🦞',
    question: '¿Qué marisco rojo tiene pinzas?',
    options: ['la langosta', 'el bogavante', 'el cangrejo'],
    correctAnswer: 'la langosta',
    hint: 'Lobster - expensive delicacy, turns red when cooked, large claws',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_113',
    emoji: '🦀',
    question: '¿Qué marisco camina de lado?',
    options: ['el cangrejo', 'la jaiba', 'el centollo'],
    correctAnswer: 'el cangrejo',
    hint: 'Crab - walks sideways, hard shell, two claws, lives in ocean and land',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_114',
    emoji: '🦑',
    question: '¿Qué marisco tiene tentáculos?',
    options: ['el calamar', 'el pulpo', 'la sepia'],
    correctAnswer: 'el calamar',
    hint: 'Squid - has 10 tentacles, "calamares fritos" very popular in Spain',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_115',
    emoji: '🦐',
    question: '¿Qué marisco pequeño se fríe?',
    options: ['el camarón', 'la gamba', 'el langostino'],
    correctAnswer: 'el camarón',
    hint: 'Shrimp turns pink when cooked - "gamba" in Spain, "camarón" in Latin America',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_116',
    emoji: '🦪',
    question: '¿En qué marisco encuentras perlas?',
    options: ['la ostra', 'la almeja', 'el mejillón'],
    correctAnswer: 'la ostra',
    hint: 'Oyster - produces pearls, eaten raw or cooked, aphrodisiac reputation',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_117',
    emoji: '🍖',
    question: '¿Qué corte de carne tiene hueso?',
    options: ['la chuleta', 'la costilla', 'el filete'],
    correctAnswer: 'la chuleta',
    hint: 'Chop or cutlet - meat cut with bone attached, like pork or lamb chop',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_118',
    emoji: '🥩',
    question: '¿Qué carne se asa a la parrilla?',
    options: ['el bistec', 'el filete', 'la carne asada'],
    correctAnswer: 'el bistec',
    hint: 'Steak - "bistec" from English "beefsteak", grilled or pan-fried',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_119',
    emoji: '🍗',
    question: '¿Qué parte del pollo se fríe?',
    options: ['el muslo', 'la pechuga', 'el ala'],
    correctAnswer: 'el muslo',
    hint: 'Chicken thigh/drumstick - juicier and more flavorful than breast',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_120',
    emoji: '🥓',
    question: '¿Qué carne crujiente comes con huevos?',
    options: ['el tocino', 'la panceta', 'el jamón'],
    correctAnswer: 'el tocino',
    hint: 'Bacon - classic breakfast meat, crispy when fried, from pork belly',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_121',
    emoji: '🍤',
    question: '¿Qué marisco empanizado es delicioso?',
    options: ['el camarón empanizado', 'el camarón rebozado', 'el pescado empanizado'],
    correctAnswer: 'el camarón empanizado',
    hint: 'Breaded shrimp - coated in breadcrumbs and deep-fried, crispy outside',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_122',
    emoji: '🌭',
    question: '¿Qué salchicha se come en pan?',
    options: ['la salchicha', 'el chorizo', 'la longaniza'],
    correctAnswer: 'la salchicha',
    hint: 'Sausage - "salchicha" is generic term, many varieties worldwide',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_123',
    emoji: '🥙',
    question: '¿Qué comida mediterránea está en pan de pita?',
    options: ['el falafel', 'el kebab', 'el shawarma'],
    correctAnswer: 'el falafel',
    hint: 'Middle Eastern fried chickpea balls - vegetarian, served in pita bread',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_124',
    emoji: '🫔',
    question: '¿Qué comida mexicana está enrollada y bañada?',
    options: ['la enchilada', 'el burrito', 'la chimichange'],
    correctAnswer: 'la enchilada',
    hint: 'Rolled tortilla covered in chili sauce - "enchilada" from "enchilar" (to season with chili)',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_125',
    emoji: '🥟',
    question: '¿Qué comida china rellena se cuece al vapor?',
    options: ['el dumpling', 'el wonton', 'el baozi'],
    correctAnswer: 'el dumpling',
    hint: 'Chinese filled dough pockets - steamed, boiled, or fried, many fillings',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },

  // Condiments & Seasonings (15 questions)
  {
    id: 'food_126',
    emoji: '🧂',
    question: '¿Qué condimento blanco usas para sazonar?',
    options: ['la sal', 'la pimienta', 'el azúcar'],
    correctAnswer: 'la sal',
    hint: 'Salt - essential mineral, "sal" from Latin, used worldwide for flavor',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_127',
    emoji: '🫙',
    question: '¿En qué guardas la mermelada?',
    options: ['el frasco', 'el tarro', 'el bote'],
    correctAnswer: 'el frasco',
    hint: 'Jar - glass container with lid, "frasco" for preserves and spreads',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_128',
    emoji: '🍯',
    question: '¿Qué producto dulce hacen las abejas?',
    options: ['la miel', 'el polen', 'la cera'],
    correctAnswer: 'la miel',
    hint: 'Honey - natural sweetener, bees make it from flower nectar',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_129',
    emoji: '🥫',
    question: '¿En qué recipiente viene la sopa enlatada?',
    options: ['la lata', 'la caja', 'el frasco'],
    correctAnswer: 'la lata',
    hint: 'Can - metal container, "enlatado" means canned food',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_130',
    emoji: '🫗',
    question: '¿Qué haces cuando sirves agua?',
    options: ['verter', 'servir', 'echar'],
    correctAnswer: 'verter',
    hint: 'To pour - pouring liquid from one container to another',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_131',
    emoji: '🧈',
    question: '¿Qué grasa amarilla untas en pan?',
    options: ['la mantequilla', 'la margarina', 'la manteca'],
    correctAnswer: 'la mantequilla',
    hint: 'Spread made from cream',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_132',
    emoji: '🫚',
    question: '¿Qué raíz picante se usa en la cocina asiática?',
    options: ['el jengibre', 'la cúrcuma', 'el rábano'],
    correctAnswer: 'el jengibre',
    hint: 'Ginger root - spicy, aromatic, used fresh or dried in Asian cooking',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_133',
    emoji: '🌶️',
    question: '¿Qué ingrediente hace la comida picante?',
    options: ['el chile', 'el jalapeño', 'el pimiento'],
    correctAnswer: 'el chile',
    hint: 'Chili pepper - contains capsaicin that creates heat sensation',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_134',
    emoji: '🧄',
    question: '¿Qué bulbo blanco tiene olor fuerte?',
    options: ['el ajo', 'la cebolla', 'el chalote'],
    correctAnswer: 'el ajo',
    hint: 'Garlic - "ajo" used in almost every Spanish dish, good for health',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_135',
    emoji: '🧅',
    question: '¿Qué verdura redonda te hace llorar?',
    options: ['la cebolla', 'el puerro', 'el cebollino'],
    correctAnswer: 'la cebolla',
    hint: 'Makes you cry when you cut it',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_136',
    emoji: '🥜',
    question: '¿De qué nuez se hace la mantequilla de maní?',
    options: ['el maní', 'el cacahuate', 'la almendra'],
    correctAnswer: 'el maní',
    hint: 'Peanut - technically a legume, not a nut, "cacahuate" also used',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_137',
    emoji: '🌰',
    question: '¿Qué fruto seco comen las ardillas?',
    options: ['la castaña', 'la bellota', 'la nuez'],
    correctAnswer: 'la castaña',
    hint: 'Chestnut - roasted in autumn, "castañas asadas" traditional in Spain',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_138',
    emoji: '🥥',
    question: '¿De qué fruta tropical sale leche vegetal?',
    options: ['el coco', 'la almendra', 'la avena'],
    correctAnswer: 'el coco',
    hint: 'Coconut - hard shell outside, white flesh and liquid inside',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_139',
    emoji: '🍄',
    question: '¿Qué hongo comestible crece en bosques?',
    options: ['la seta', 'el champiñón', 'el portobello'],
    correctAnswer: 'la seta',
    hint: 'Wild mushroom - "seta" is generic term, many varieties in forests',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_140',
    emoji: '🫘',
    question: '¿Qué legumbre se usa en chili?',
    options: ['el frijol', 'la alubia', 'el garbanzo'],
    correctAnswer: 'el frijol',
    hint: 'Bean - red kidney beans common in chili con carne',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },

  // More International Dishes (15 questions)
  // More International Dishes (15 questions)
  {
    id: 'food_141',
    emoji: '🍱',
    question: '¿Qué caja japonesa tiene comida variada?',
    options: ['el bento', 'el obento', 'el ekiben'],
    correctAnswer: 'el bento',
    hint: 'Look at the emoji for a clue',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_142',
    emoji: '🍙',
    question: '¿Qué triángulo de arroz japonés tiene alga?',
    options: ['el onigiri', 'el musubi', 'el maki'],
    correctAnswer: 'el onigiri',
    hint: 'Look at the emoji for a clue',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_143',
    emoji: '🍘',
    question: '¿Qué galleta japonesa de arroz es crujiente?',
    options: ['el senbei', 'el arare', 'el okaki'],
    correctAnswer: 'el senbei',
    hint: 'Look at the emoji for a clue',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_144',
    emoji: '🍥',
    question: '¿Qué ingrediente blanco y rosado va en ramen?',
    options: ['el narutomaki', 'el kamaboko', 'el surimi'],
    correctAnswer: 'el narutomaki',
    hint: 'Look at the emoji for a clue',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_145',
    emoji: '🥡',
    question: '¿En qué caja blanca te dan comida china?',
    options: ['la caja de comida para llevar', 'el envase para llevar', 'el recipiente desechable'],
    correctAnswer: 'la caja de comida para llevar',
    hint: 'Look at the emoji for a clue',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_146',
    emoji: '🥢',
    question: '¿Con qué palitos comes comida asiática?',
    options: ['los palillos', 'los palillos chinos', 'los hashi'],
    correctAnswer: 'los palillos',
    hint: 'Look at the emoji for a clue',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_147',
    emoji: '🍛',
    question: '¿Qué plato picante indio tiene arroz?',
    options: ['el curry', 'el masala', 'el korma'],
    correctAnswer: 'el curry',
    hint: 'Look at the emoji for a clue',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_148',
    emoji: '🍲',
    question: '¿Qué plato caliente cocinas en olla?',
    options: ['el estofado', 'el cocido', 'el potaje'],
    correctAnswer: 'el estofado',
    hint: 'Look at the emoji for a clue',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_149',
    emoji: '🫕',
    question: '¿Qué comida suiza sumerges en queso derretido?',
    options: ['el fondue', 'la raclette', 'el fondue de queso'],
    correctAnswer: 'el fondue',
    hint: 'Look at the emoji for a clue',
    points: 15,
    category: 'food',
    difficulty: 'hard',
  },
  {
    id: 'food_150',
    emoji: '🥘',
    question: '¿Qué plato español tiene azafrán?',
    options: ['la paella', 'el arroz al horno', 'la fideuá'],
    correctAnswer: 'la paella',
    hint: 'Look at the emoji for a clue',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_151',
    emoji: '🍝',
    question: '¿Qué fideos italianos son largos y delgados?',
    options: ['el espagueti', 'los tallarines', 'los fideos'],
    correctAnswer: 'el espagueti',
    hint: 'Long thin pasta noodles',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_152',
    emoji: '🥗',
    question: '¿Qué ensalada romana tiene crutones?',
    options: ['la César', 'la ensalada César', 'la ensalada romana'],
    correctAnswer: 'la César',
    hint: 'Look at the emoji for a clue',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_153',
    emoji: '🥙',
    question: '¿Qué comida del Medio Oriente es de garbanzos?',
    options: ['el hummus', 'el falafel', 'el baba ganoush'],
    correctAnswer: 'el hummus',
    hint: 'Look at the emoji for a clue',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_154',
    emoji: '🌮',
    question: '¿Qué comida mexicana tiene tortilla crujiente?',
    options: ['el taco duro', 'la tostada', 'el taco dorado'],
    correctAnswer: 'el taco duro',
    hint: 'Look at the emoji for a clue',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_155',
    emoji: '🧆',
    question: '¿Qué bola frita del Medio Oriente es vegetariana?',
    options: ['el falafel', 'el taameya', 'la kofta'],
    correctAnswer: 'el falafel',
    hint: 'Look at the emoji for a clue',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },

  // Additional Food/Utensil Phrases (3 questions)
  {
    id: 'food_156',
    emoji: '🍴',
    question: '¿Cómo pides "can I have a fork?"',
    options: ['¿me puede dar un tenedor?', '¿puedo tener un tenedor?', '¿me da un tenedor?'],
    correctAnswer: '¿me puede dar un tenedor?',
    hint: 'Can I have a fork? - "me puede dar" (can you give me), "tenedor" (fork), polite restaurant request',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_157',
    emoji: '🔪',
    question: '¿Cómo pides "can I have a knife?"',
    options: ['¿me puede dar un cuchillo?', '¿puedo tener un cuchillo?', '¿me da un cuchillo?'],
    correctAnswer: '¿me puede dar un cuchillo?',
    hint: 'Can I have a knife? - "me puede dar" (can you give me), "cuchillo" (knife), essential utensil',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_158',
    emoji: '🥄',
    question: '¿Cómo pides "can I have a spoon?"',
    options: ['¿me puede dar una cuchara?', '¿puedo tener una cuchara?', '¿me da una cuchara?'],
    correctAnswer: '¿me puede dar una cuchara?',
    hint: 'Can I have a spoon? - "me puede dar" (can you give me), "cuchara" (spoon - feminine), for soup/dessert',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_159',
    emoji: '🧂',
    question: '¿Qué se añade a la comida para el sabor?',
    options: ['las especias', 'la sal', 'el condimento'],
    correctAnswer: 'las especias',
    hint: 'Spices - powdered or dried seasonings like cumin, paprika, etc.',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_160',
    emoji: '🌶️',
    question: '¿Qué salsa roja picante acompaña muchas comidas?',
    options: ['la salsa picante', 'el salsa de tomate', 'la salsa de chile'],
    correctAnswer: 'la salsa picante',
    hint: 'Hot sauce - spicy condiment made from peppers, adds heat to dishes',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_161',
    emoji: '🍅',
    question: '¿Qué condimento rojo viene en una botella?',
    options: ['la salsa de tomate', 'la catsup', 'el ketchup'],
    correctAnswer: 'el ketchup',
    hint: 'Ketchup - tomato condiment, popular on fries and burgers, American origin',
    points: 5,
    category: 'food',
    difficulty: 'easy',
  },
  {
    id: 'food_162',
    emoji: '🫛',
    question: '¿Qué verdura verde y pequeña viene en vaina?',
    options: ['los guisantes', 'los chícharos', 'las arvejas'],
    correctAnswer: 'los guisantes',
    hint: 'Peas - small green legumes in pods, "chícharos" in Mexico, "arvejas" in South America',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
  {
    id: 'food_163',
    emoji: '🍼',
    question: '¿Qué toman los bebés?',
    options: ['la fórmula para bebés', 'la leche de fórmula', 'la fórmula infantil'],
    correctAnswer: 'la fórmula para bebés',
    hint: 'Baby formula - infant milk substitute, nutritious for babies',
    points: 10,
    category: 'food',
    difficulty: 'medium',
  },
];
