/**
 * GRAMMAR Category Questions
 * Category: grammar
 */

export const grammarQuestions = [
// Subject Pronouns (8 questions)
    {
    id: 'grammar_001',
    emoji: '😊',
    question: '¿Cómo se dice "I" (subject pronoun)?',
    options: ['yo', 'yó', 'io'],
    correctAnswer: 'yo',
    hint: 'I - first person singular, from Latin "ego", often omitted since verb shows who (hablo = I speak)',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_002',
    emoji: '😊',
    question: '¿Cómo se dice "you" (informal)?',
    options: ['tú', 'tu', 'usted'],
    correctAnswer: 'tú',
    hint: 'You - informal singular for friends/family, from Latin "tu", has accent to distinguish from "tu" (your)',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_003',
    emoji: '🧑',
    question: '¿Cómo se dice "he"?',
    options: ['él', 'el', 'ella'],
    correctAnswer: 'él',
    hint: 'He - masculine third person, has accent to distinguish from "el" (the), from Latin "ille"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_004',
    emoji: '😊',
    question: '¿Cómo se dice "she"?',
    options: ['ella', 'élla', 'él'],
    correctAnswer: 'ella',
    hint: 'She - feminine third person, no accent needed, from Latin "illa"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_005',
    emoji: '😊',
    question: '¿Cómo se dice "we"?',
    options: ['nosotros', 'nosotras', 'nos'],
    correctAnswer: 'nosotros',
    hint: 'We - first person plural masculine/mixed, "nosotras" all feminine, from "nos" (us) + "otros" (others)',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_006',
    emoji: '👨',
    question: '¿Cómo se dice "they" (masculine)?',
    options: ['ellos', 'ellas', 'elles'],
    correctAnswer: 'ellos',
    hint: 'They - masculine/mixed group, one male makes group masculine, from Latin "illos"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_007',
    emoji: '👩',
    question: '¿Cómo se dice "they" (feminine)?',
    options: ['ellas', 'ellos', 'elles'],
    correctAnswer: 'ellas',
    hint: 'They - all feminine group only, from Latin "illas", rarely used since groups often mixed',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_008',
    emoji: '🎩',
    question: '¿Cómo se dice "you" (formal)?',
    options: ['usted', 'ustéd', 'ustedes'],
    correctAnswer: 'usted',
    hint: 'You - formal singular from "vuestra merced" (your mercy), abbreviated Ud., uses 3rd person verbs',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Verb "SER" (to be) - Present Tense (7 questions)
  {
    id: 'grammar_009',
    emoji: '🎓',
    question: 'Yo ___ estudiante. (to be)',
    options: ['soy', 'estoy', 'so'],
    correctAnswer: 'soy',
    hint: 'I am - SER for identity/profession, irregular "soy" (not "so"), permanent characteristics',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_010',
    emoji: '🧠',
    question: 'Tú ___ inteligente. (to be)',
    options: ['eres', 'estás', 'erés'],
    correctAnswer: 'eres',
    hint: 'You are - SER for characteristics/personality, irregular form, permanent traits',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_011',
    emoji: '⚕️',
    question: 'Él ___ médico. (to be)',
    options: ['es', 'está', 'eres'],
    correctAnswer: 'es',
    hint: 'He is - SER for profession (no article "a/an" in Spanish), permanent occupation',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_012',
    emoji: '👩‍🏫',
    question: 'Ella ___ profesora. (to be)',
    options: ['es', 'está', 'son'],
    correctAnswer: 'es',
    hint: 'She is - same form for él/ella/usted all use "es", SER for occupation',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_013',
    emoji: '🤝',
    question: 'Nosotros ___ amigos. (to be)',
    options: ['somos', 'estamos', 'semos'],
    correctAnswer: 'somos',
    hint: 'We are - SER for relationships, irregular conjugation from Latin "sumus"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_014',
    emoji: '📚',
    question: 'Ellos ___ estudiantes. (to be)',
    options: ['son', 'están', 'es'],
    correctAnswer: 'son',
    hint: 'They are - SER for identity, irregular form, same for ellos/ellas/ustedes',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_015',
    emoji: '😊',
    question: 'Usted ___ muy amable. (to be)',
    options: ['es', 'está', 'eres'],
    correctAnswer: 'es',
    hint: 'You are (formal) - uses 3rd person "es", SER for personality traits (permanent)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Verb "ESTAR" (to be) - Present Tense (7 questions)
  {
    id: 'grammar_016',
    emoji: '🏠',
    question: 'Yo ___ en casa. (to be/location)',
    options: ['estoy', 'soy', 'esto'],
    correctAnswer: 'estoy',
    hint: 'I am - ESTAR for location, irregular "estoy", temporary states and positions',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_017',
    emoji: '😴',
    question: 'Tú ___ cansado. (to be/condition)',
    options: ['estás', 'eres', 'estas'],
    correctAnswer: 'estás',
    hint: 'You are - ESTAR for temporary condition/emotion, "cansado" is temporary state not personality',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_018',
    emoji: '😄',
    question: 'Él ___ contento. (to be/emotion)',
    options: ['está', 'es', 'ésta'],
    correctAnswer: 'está',
    hint: 'He is - ESTAR for emotions (temporary), "contento" is current feeling not permanent trait',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_019',
    emoji: '📍',
    question: 'Nosotros ___ aquí. (to be/location)',
    options: ['estamos', 'somos', 'estemos'],
    correctAnswer: 'estamos',
    hint: 'We are - ESTAR for location/position, "aquí" (here) indicates place',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_020',
    emoji: '💼',
    question: 'Ellos ___ ocupados. (to be/condition)',
    options: ['están', 'son', 'estan'],
    correctAnswer: 'están',
    hint: 'They are - ESTAR for temporary condition, "ocupados" (busy) is current state',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_021',
    emoji: '🏦',
    question: '¿Dónde ___ el banco? (to be/location)',
    options: ['está', 'es', 'ésta'],
    correctAnswer: 'está',
    hint: 'Where is - ESTAR for location even if permanent, "dónde" (where) triggers ESTAR',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_022',
    emoji: '🔥',
    question: 'La comida ___ caliente. (to be/condition)',
    options: ['está', 'es', 'ésta'],
    correctAnswer: 'está',
    hint: 'Food is - ESTAR for temporary condition, "caliente" (hot) is current temperature not permanent',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },

  // Regular -AR Verbs (5 questions)
  {
    id: 'grammar_023',
    emoji: '🗣',
    question: 'Yo ___ español. (hablar - to speak)',
    options: ['hablo', 'hablé', 'hable'],
    correctAnswer: 'hablo',
    hint: 'I speak - -AR verb: remove -ar, add -o for yo, most common verb type in Spanish',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_024',
    emoji: '🎵',
    question: 'Tú ___ música. (escuchar - to listen)',
    options: ['escuchas', 'escucha', 'escuchás'],
    correctAnswer: 'escuchas',
    hint: 'You listen - -AR verb: remove -ar, add -as for tú, regular pattern',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_025',
    emoji: '🧹',
    question: 'Ella ___ la casa. (limpiar - to clean)',
    options: ['limpia', 'limpio', 'limpía'],
    correctAnswer: 'limpia',
    hint: 'She cleans - -AR verb: remove -ar, add -a for él/ella/usted',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_026',
    emoji: '👣',
    question: 'Nosotros ___ en el parque. (caminar - to walk)',
    options: ['caminamos', 'caminemos', 'caminábamos'],
    correctAnswer: 'caminamos',
    hint: 'We walk - -AR verb: remove -ar, add -amos for nosotros, consistent ending',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_027',
    emoji: '⏰',
    question: 'Ellos ___ temprano. (trabajar - to work)',
    options: ['trabajan', 'trabaja', 'trabajen'],
    correctAnswer: 'trabajan',
    hint: 'They work - -AR verb: remove -ar, add -an for ellos/ellas/ustedes',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Regular -ER Verbs (3 questions)
  {
    id: 'grammar_028',
    emoji: '🍽️',
    question: 'Yo ___ mucho. (comer - to eat)',
    options: ['como', 'comó', 'come'],
    correctAnswer: 'como',
    hint: 'I eat - -ER verb: remove -er, add -o for yo, second most common verb type',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_029',
    emoji: '📖',
    question: 'Tú ___ libros. (leer - to read)',
    options: ['lees', 'leés', 'lee'],
    correctAnswer: 'lees',
    hint: 'You read - -ER verb: remove -er, add -es for tú, notice double "e"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_030',
    emoji: '☕',
    question: 'Nosotros ___ café. (beber - to drink)',
    options: ['bebemos', 'bebamos', 'bebíamos'],
    correctAnswer: 'bebemos',
    hint: 'We drink - -ER verb: remove -er, add -emos for nosotros',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Regular -IR Verbs (3 questions)
  {
    id: 'grammar_031',
    emoji: '🏙️',
    question: 'Yo ___ en Madrid. (vivir - to live)',
    options: ['vivo', 'vivó', 'vive'],
    correctAnswer: 'vivo',
    hint: 'I live - -IR verb: remove -ir, add -o for yo, least common but important verb type',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_032',
    emoji: '🚪',
    question: 'Tú ___ la puerta. (abrir - to open)',
    options: ['abres', 'abrís', 'abre'],
    correctAnswer: 'abres',
    hint: 'You open - -IR verb: remove -ir, add -es for tú (same as -ER for tú)',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_033',
    emoji: '✉️',
    question: 'Ellos ___ cartas. (escribir - to write)',
    options: ['escriben', 'escriban', 'escribieron'],
    correctAnswer: 'escriben',
    hint: 'They write - -IR verb: remove -ir, add -en for ellos/ellas/ustedes',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Articles & Gender (6 questions)
  {
    id: 'grammar_034',
    emoji: '📗',
    question: '___ libro (the book - masculine)',
    options: ['el', 'él', 'la'],
    correctAnswer: 'el',
    hint: 'The - masculine singular definite article, most words ending in -o are masculine',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_035',
    emoji: '🏡',
    question: '___ casa (the house - feminine)',
    options: ['la', 'el', 'él'],
    correctAnswer: 'la',
    hint: 'The - feminine singular definite article, most words ending in -a are feminine',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_036',
    emoji: '📚',
    question: '___ libros (the books - masculine plural)',
    options: ['los', 'les', 'las'],
    correctAnswer: 'los',
    hint: 'The - masculine plural definite article, add -s to singular noun ending in vowel',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_037',
    emoji: '🏘️',
    question: '___ casas (the houses - feminine plural)',
    options: ['las', 'los', 'les'],
    correctAnswer: 'las',
    hint: 'The - feminine plural definite article, article must match noun gender and number',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_038',
    emoji: '🍎',
    question: '___ manzana (an apple - indefinite)',
    options: ['una', 'un', 'uno'],
    correctAnswer: 'una',
    hint: 'A/An - feminine indefinite article, "manzana" ends in -a (usually feminine)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_039',
    emoji: '🐕',
    question: '___ perro (a dog - indefinite)',
    options: ['un', 'uno', 'una'],
    correctAnswer: 'un',
    hint: 'A/An - masculine indefinite article, from "uno" (one), drops -o before noun',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Question Words (6 questions)
  {
    id: 'grammar_040',
    emoji: '🤔',
    question: '¿___ te llamas? (What is your name?)',
    options: ['cómo', 'como', 'cómo'],
    correctAnswer: 'cómo',
    hint: 'How/What - literally "how do you call yourself", has accent in questions, from Latin "quomodo"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_041',
    emoji: '📍',
    question: '¿___ estás? (Where are you?)',
    options: ['dónde', 'donde', 'dóndé'],
    correctAnswer: 'dónde',
    hint: 'Where - has accent in questions, from Latin "de unde" (from where)',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_042',
    emoji: '🔢',
    question: '¿___ años tienes? (How many years do you have?)',
    options: ['cuántos', 'cuantos', 'cuántas'],
    correctAnswer: 'cuántos',
    hint: 'How many - masculine plural form, "cuánta/cuántas" for feminine, has accent in questions',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_043',
    emoji: '📅',
    question: '¿___ es tu cumpleaños? (When is your birthday?)',
    options: ['cuándo', 'cuando', 'cuándó'],
    correctAnswer: 'cuándo',
    hint: 'When - asks about time, has accent in questions, from Latin "quando"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_044',
    emoji: '❔',
    question: '¿___ es esto? (What is this?)',
    options: ['qué', 'que', 'quién'],
    correctAnswer: 'qué',
    hint: 'What - asks for definition/identity, has accent in questions, from Latin "quid"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_045',
    emoji: '👤',
    question: '¿___ es él? (Who is he?)',
    options: ['quién', 'quien', 'qué'],
    correctAnswer: 'quién',
    hint: 'Who - asks about people, has accent in questions, "quiénes" for plural',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },

  // Possessive Adjectives (5 questions)
  {
    id: 'grammar_046',
    emoji: '✋',
    question: '___ libro (my book)',
    options: ['mi', 'mí', 'mis'],
    correctAnswer: 'mi',
    hint: 'My - possessive adjective, no accent (unlike "mí" = me), same for masculine/feminine',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_047',
    emoji: '👆',
    question: '___ casa (your house - informal)',
    options: ['tu', 'tú', 'tus'],
    correctAnswer: 'tu',
    hint: 'Your - informal possessive, no accent (unlike "tú" = you), same for masculine/feminine',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_048',
    emoji: '👥',
    question: '___ amigos (our friends)',
    options: ['nuestros', 'nuestro', 'nuestra'],
    correctAnswer: 'nuestros',
    hint: 'Our - masculine plural, changes to "nuestra/nuestras" for feminine, from "nos" (us)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_049',
    emoji: '🐶',
    question: '___ perro (his/her dog)',
    options: ['su', 'sú', 'sus'],
    correctAnswer: 'su',
    hint: 'His/her/their/your(formal) - ambiguous, same for all third person, clarify with "de él/ella"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_050',
    emoji: '📚',
    question: '___ libros (my books - plural)',
    options: ['mis', 'mi', 'mí'],
    correctAnswer: 'mis',
    hint: 'My - plural form, add -s to "mi" for plural nouns, same for masculine/feminine',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // PRETERITE TENSE (Past - Completed Actions) - 10 questions
  {
    id: 'grammar_051',
    emoji: '🍴',
    question: 'Ayer yo ___ en el restaurante. (comer - to eat)',
    options: ['comí', 'como', 'comía'],
    correctAnswer: 'comí',
    hint: 'I ate - Preterite for completed action, -ER verb: remove -er, add -í for yo',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_052',
    emoji: '🗣️',
    question: 'Tú ___ con María anoche. (hablar - to speak)',
    options: ['hablaste', 'hablas', 'hablabas'],
    correctAnswer: 'hablaste',
    hint: 'You spoke - Preterite completed action, -AR verb: add -aste for tú, "anoche" = last night',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_053',
    emoji: '✈️',
    question: 'Ella ___ a España el año pasado. (viajar - to travel)',
    options: ['viajó', 'viaja', 'viajaba'],
    correctAnswer: 'viajó',
    hint: 'She traveled - Preterite completed action, -AR verb: add -ó for él/ella, accent on last syllable',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_054',
    emoji: '👀',
    question: 'Nosotros ___ la película. (ver - to see/watch)',
    options: ['vimos', 'vemos', 'veíamos'],
    correctAnswer: 'vimos',
    hint: 'We saw - Preterite completed, -ER verb: add -imos for nosotros, irregular stem "v-"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_055',
    emoji: '🚶‍♂️',
    question: 'Ellos ___ temprano esta mañana. (salir - to leave)',
    options: ['salieron', 'salen', 'salían'],
    correctAnswer: 'salieron',
    hint: 'They left - Preterite completed, -IR verb: add -ieron for ellos, "esta mañana" = this morning',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_056',
    emoji: '🚶',
    question: 'Ayer yo ___ al médico. (ir - to go)',
    options: ['fui', 'voy', 'iba'],
    correctAnswer: 'fui',
    hint: 'I went - Irregular preterite! "ir" and "ser" share same forms, context shows meaning',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_057',
    emoji: '🏁',
    question: 'Tú ___ tarde a la reunión. (llegar - to arrive)',
    options: ['llegaste', 'llegas', 'llegabas'],
    correctAnswer: 'llegaste',
    hint: 'You arrived - Preterite completed action, regular -AR pattern for tú',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_058',
    emoji: '📦',
    question: 'Él ___ un regalo. (traer - to bring)',
    options: ['trajo', 'trae', 'traía'],
    correctAnswer: 'trajo',
    hint: 'He brought - Irregular preterite stem "traj-", add -o for él (not -ó!), no accent',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_059',
    emoji: '📍',
    question: 'Nosotros ___ en ese hotel. (estar - to be)',
    options: ['estuvimos', 'estamos', 'estábamos'],
    correctAnswer: 'estuvimos',
    hint: 'We were - Irregular preterite "estuv-" stem, completed stay/visit',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_060',
    emoji: '💬',
    question: 'Ellos no ___ la verdad. (decir - to say/tell)',
    options: ['dijeron', 'dicen', 'decían'],
    correctAnswer: 'dijeron',
    hint: 'They didn\'t say - Irregular "dij-" stem, add -eron (not -ieron!), spelling change',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },

  // IMPERFECT TENSE (Past - Ongoing/Habitual) - 10 questions
  {
    id: 'grammar_061',
    emoji: '⚽',
    question: 'Cuando era niño, yo ___ mucho. (jugar - to play)',
    options: ['jugaba', 'jugué', 'juego'],
    correctAnswer: 'jugaba',
    hint: 'I used to play - Imperfect for habitual past, -AR verb: add -aba for yo, "cuando era niño" = when I was a child',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_062',
    emoji: '🍷',
    question: 'Tú siempre ___ café por la mañana. (beber - to drink)',
    options: ['bebías', 'bebiste', 'bebes'],
    correctAnswer: 'bebías',
    hint: 'You used to drink - Imperfect habitual, -ER verb: add -ías for tú, "siempre" = always (habitual)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_063',
    emoji: '🏡',
    question: 'Ella ___ en Madrid antes. (vivir - to live)',
    options: ['vivía', 'vivió', 'vive'],
    correctAnswer: 'vivía',
    hint: 'She used to live - Imperfect ongoing state, -IR verb: add -ía for ella, "antes" = before',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_064',
    emoji: '🚶‍♀️',
    question: 'Nosotros ___ al parque cada domingo. (ir - to go)',
    options: ['íbamos', 'fuimos', 'vamos'],
    correctAnswer: 'íbamos',
    hint: 'We used to go - Irregular imperfect of "ir", "cada domingo" = every Sunday (habitual)',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_065',
    emoji: '👴',
    question: 'Ellos ___ muy felices juntos. (ser - to be)',
    options: ['eran', 'fueron', 'son'],
    correctAnswer: 'eran',
    hint: 'They were - Irregular imperfect of "ser", describes ongoing state in past',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_066',
    emoji: '🍳',
    question: 'Mientras yo ___, sonó el teléfono. (cocinar - to cook)',
    options: ['cocinaba', 'cociné', 'cocino'],
    correctAnswer: 'cocinaba',
    hint: 'I was cooking - Imperfect for ongoing action interrupted, "mientras" = while',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_067',
    emoji: '📺',
    question: 'Tú ___ la televisión cuando llegué. (ver - to watch)',
    options: ['veías', 'viste', 'ves'],
    correctAnswer: 'veías',
    hint: 'You were watching - Imperfect ongoing action, background action when something happened',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_068',
    emoji: '🎂',
    question: '¿Qué hora ___ cuando saliste? (ser - to be)',
    options: ['era', 'fue', 'es'],
    correctAnswer: 'era',
    hint: 'What time was it - Imperfect for telling time in past, always use "ser" imperfect',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_069',
    emoji: '💃',
    question: 'Nosotros ___ mucho cuando éramos jóvenes. (bailar - to dance)',
    options: ['bailábamos', 'bailamos', 'bailamos'],
    correctAnswer: 'bailábamos',
    hint: 'We used to dance - Imperfect habitual, "cuando éramos jóvenes" = when we were young',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_070',
    emoji: '😢',
    question: 'El niño ___ cuando lo encontraron. (llorar - to cry)',
    options: ['lloraba', 'lloró', 'llora'],
    correctAnswer: 'lloraba',
    hint: 'The child was crying - Imperfect ongoing action as background to "encontraron" (found)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // FUTURE TENSE - 10 questions
  {
    id: 'grammar_071',
    emoji: '🔮',
    question: 'Mañana yo ___ con mi familia. (comer - to eat)',
    options: ['comeré', 'como', 'comí'],
    correctAnswer: 'comeré',
    hint: 'I will eat - Future: keep infinitive + -é for yo, "mañana" = tomorrow',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_072',
    emoji: '🗨️',
    question: 'Tú ___ español muy bien. (hablar - to speak)',
    options: ['hablarás', 'hablas', 'hablaste'],
    correctAnswer: 'hablarás',
    hint: 'You will speak - Future: infinitive + -ás for tú, accent on last syllable',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_073',
    emoji: '🏘️',
    question: 'Ella ___ en París el próximo año. (vivir - to live)',
    options: ['vivirá', 'vive', 'vivió'],
    correctAnswer: 'vivirá',
    hint: 'She will live - Future: infinitive + -á for ella, "el próximo año" = next year',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_074',
    emoji: '🚪',
    question: 'Nosotros ___ mañana. (salir - to leave)',
    options: ['saldremos', 'salimos', 'salíamos'],
    correctAnswer: 'saldremos',
    hint: 'We will leave - Irregular future stem "saldr-" + -emos, drops "i" from infinitive',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_075',
    emoji: '💭',
    question: 'Ellos ___ la verdad. (decir - to say/tell)',
    options: ['dirán', 'dicen', 'dijeron'],
    correctAnswer: 'dirán',
    hint: 'They will say - Irregular future stem "dir-" (not "decir-") + -án for ellos',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_076',
    emoji: '🛠️',
    question: '¿Qué ___ tú este fin de semana? (hacer - to do)',
    options: ['harás', 'haces', 'hiciste'],
    correctAnswer: 'harás',
    hint: 'What will you do - Irregular future stem "har-" (not "hacer-"), "fin de semana" = weekend',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_077',
    emoji: '🎁',
    question: 'Yo ___ dinero para el viaje. (tener - to have)',
    options: ['tendré', 'tengo', 'tuve'],
    correctAnswer: 'tendré',
    hint: 'I will have - Irregular future stem "tendr-" (not "tener-") + -é',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_078',
    emoji: '🏁',
    question: 'Nosotros ___ a tiempo. (llegar - to arrive)',
    options: ['llegaremos', 'llegamos', 'llegábamos'],
    correctAnswer: 'llegaremos',
    hint: 'We will arrive - Regular future: infinitive + -emos for nosotros',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_079',
    emoji: '🚶‍♂️',
    question: '¿Cuándo ___ ellos? (venir - to come)',
    options: ['vendrán', 'vienen', 'vinieron'],
    correctAnswer: 'vendrán',
    hint: 'When will they come - Irregular future stem "vendr-" (not "venir-") + -án',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_080',
    emoji: '💪',
    question: 'Ella no ___ ir a la fiesta. (poder - to be able)',
    options: ['podrá', 'puede', 'pudo'],
    correctAnswer: 'podrá',
    hint: 'She won\'t be able - Irregular future stem "podr-" (not "poder-") + -á',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },

  // PRESENT PROGRESSIVE (estar + gerund) - 8 questions
  {
    id: 'grammar_081',
    emoji: '📖',
    question: 'Yo ___ un libro ahora. (leer - to read)',
    options: ['estoy leyendo', 'leo', 'leí'],
    correctAnswer: 'estoy leyendo',
    hint: 'I am reading - Present progressive: estar + gerund, -ER/-IR verbs end in -yendo',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_082',
    emoji: '🎓',
    question: 'Tú ___ español muy rápido. (aprender - to learn)',
    options: ['estás aprendiendo', 'aprendes', 'aprendiste'],
    correctAnswer: 'estás aprendiendo',
    hint: 'You are learning - estar + gerund (-iendo for -ER verbs), happening right now',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_083',
    emoji: '👨‍🍳',
    question: 'Ella ___ la cena en este momento. (cocinar - to cook)',
    options: ['está cocinando', 'cocina', 'cocinó'],
    correctAnswer: 'está cocinando',
    hint: 'She is cooking - estar + gerund (-ando for -AR verbs), "en este momento" = right now',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_084',
    emoji: '👁️',
    question: 'Nosotros ___ una película. (ver - to watch)',
    options: ['estamos viendo', 'vemos', 'vimos'],
    correctAnswer: 'estamos viendo',
    hint: 'We are watching - estar + gerund, ongoing action happening now',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_085',
    emoji: '🔨',
    question: '¿Qué ___ ellos? (hacer - to do)',
    options: ['están haciendo', 'hacen', 'hicieron'],
    correctAnswer: 'están haciendo',
    hint: 'What are they doing - estar + gerund of irregular "hacer" = "haciendo"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_086',
    emoji: '📝',
    question: 'Yo ___ para el examen. (estudiar - to study)',
    options: ['estoy estudiando', 'estudio', 'estudié'],
    correctAnswer: 'estoy estudiando',
    hint: 'I am studying - Present progressive for action in progress, -AR gerund = -ando',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_087',
    emoji: '🎮',
    question: 'Ellos ___ al fútbol. (jugar - to play)',
    options: ['están jugando', 'juegan', 'jugaron'],
    correctAnswer: 'están jugando',
    hint: 'They are playing - estar + gerund, action happening right now',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_088',
    emoji: '😭',
    question: '¿Por qué ___ tú? (llorar - to cry)',
    options: ['estás llorando', 'lloras', 'lloraste'],
    correctAnswer: 'estás llorando',
    hint: 'Why are you crying - Present progressive for current action, -AR = -ando',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // CONDITIONAL TENSE (would) - 8 questions
  {
    id: 'grammar_089',
    emoji: '🤷',
    question: 'Yo ___ a España si tuviera dinero. (ir - to go)',
    options: ['iría', 'voy', 'fui'],
    correctAnswer: 'iría',
    hint: 'I would go - Conditional: infinitive + -ía for yo, used with "si" (if) clauses',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_090',
    emoji: '💭',
    question: 'Tú ___ feliz allí. (ser - to be)',
    options: ['serías', 'eres', 'fuiste'],
    correctAnswer: 'serías',
    hint: 'You would be - Conditional for hypothetical, infinitive + -ías for tú',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_091',
    emoji: '🚶',
    question: 'Ella ___ más temprano. (salir - to leave)',
    options: ['saldría', 'sale', 'salió'],
    correctAnswer: 'saldría',
    hint: 'She would leave - Irregular conditional stem "saldr-" (same as future) + -ía',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_092',
    emoji: '💼',
    question: 'Nosotros ___ más si pudiéramos. (trabajar - to work)',
    options: ['trabajaríamos', 'trabajamos', 'trabajábamos'],
    correctAnswer: 'trabajaríamos',
    hint: 'We would work - Conditional: infinitive + -íamos for nosotros, hypothetical',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_093',
    emoji: '🛠️',
    question: '¿Qué ___ tú en mi lugar? (hacer - to do)',
    options: ['harías', 'haces', 'hiciste'],
    correctAnswer: 'harías',
    hint: 'What would you do - Irregular stem "har-" (same as future) + -ías, "en mi lugar" = in my place',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_094',
    emoji: '🤔',
    question: 'Ellos ___ ayudarnos. (poder - to be able)',
    options: ['podrían', 'pueden', 'pudieron'],
    correctAnswer: 'podrían',
    hint: 'They could/would be able - Irregular stem "podr-" + -ían, polite suggestion',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_095',
    emoji: '🎁',
    question: 'Yo ___ más cuidado. (tener - to have)',
    options: ['tendría', 'tengo', 'tuve'],
    correctAnswer: 'tendría',
    hint: 'I would have/take - Irregular stem "tendr-" + -ía, "tener cuidado" = be careful',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_096',
    emoji: '🙏',
    question: '¿___ usted ayudarme? (poder - could you)',
    options: ['Podría', 'Puede', 'Pudo'],
    correctAnswer: 'Podría',
    hint: 'Could you - Conditional for polite request, more polite than "puede"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },

  // SUBJUNCTIVE BASICS (Present) - 14 questions
  {
    id: 'grammar_097',
    emoji: '🎭',
    question: 'Espero que tú ___ bien. (estar - to be)',
    options: ['estés', 'estás', 'estas'],
    correctAnswer: 'estés',
    hint: 'I hope you are - Subjunctive after "espero que" (hope that), doubt/wish, tú form = -es',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_098',
    emoji: '🗣️',
    question: 'Es importante que nosotros ___ español. (hablar - to speak)',
    options: ['hablemos', 'hablamos', 'hablaremos'],
    correctAnswer: 'hablemos',
    hint: 'It\'s important that we speak - Subjunctive after "es importante que", -AR = -emos',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_099',
    emoji: '💬',
    question: 'Quiero que ella ___ la verdad. (decir - to say)',
    options: ['diga', 'dice', 'dirá'],
    correctAnswer: 'diga',
    hint: 'I want her to say - Subjunctive after "quiero que" (want that), irregular "decir" = "diga"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_100',
    emoji: '🏁',
    question: 'Dudo que ellos ___ a tiempo. (llegar - to arrive)',
    options: ['lleguen', 'llegan', 'llegarán'],
    correctAnswer: 'lleguen',
    hint: 'I doubt they arrive - Subjunctive after "dudo que" (doubt), uncertainty, -AR = -en',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_101',
    emoji: '📚',
    question: 'Es necesario que yo ___ más. (estudiar - to study)',
    options: ['estudie', 'estudio', 'estudiaré'],
    correctAnswer: 'estudie',
    hint: 'It\'s necessary that I study - Subjunctive after impersonal expression, -AR yo = -e',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_102',
    emoji: '🎯',
    question: 'No creo que él ___ razón. (tener - to have)',
    options: ['tenga', 'tiene', 'tendrá'],
    correctAnswer: 'tenga',
    hint: 'I don\'t think he\'s right - Subjunctive after "no creo que" (negative belief), irregular "tener"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_103',
    emoji: '✅',
    question: 'Ojalá que ___ buen tiempo mañana. (hacer - to make/do)',
    options: ['haga', 'hace', 'hará'],
    correctAnswer: 'haga',
    hint: 'I hope the weather is good - "Ojalá que" (hopefully) always uses subjunctive, irregular "hacer"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_104',
    emoji: '🥤',
    question: 'Te recomiendo que ___ agua. (beber - to drink)',
    options: ['bebas', 'bebes', 'beberás'],
    correctAnswer: 'bebas',
    hint: 'I recommend you drink - Subjunctive after recommendation, -ER tú = -as',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_105',
    emoji: '🚶‍♀️',
    question: 'Es posible que nosotros ___ tarde. (salir - to leave)',
    options: ['salgamos', 'salimos', 'saldremos'],
    correctAnswer: 'salgamos',
    hint: 'It\'s possible we leave late - Subjunctive for possibility, irregular "salir" = "salg-"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_106',
    emoji: '🏡',
    question: 'Prefiero que tú ___ aquí. (quedarse - to stay)',
    options: ['te quedes', 'te quedas', 'te quedarás'],
    correctAnswer: 'te quedes',
    hint: 'I prefer you stay - Subjunctive after preference, reflexive verb with subjunctive',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_107',
    emoji: '💤',
    question: 'Aunque ___ cansado, voy a trabajar. (estar - to be)',
    options: ['esté', 'estoy', 'estaré'],
    correctAnswer: 'esté',
    hint: 'Even though I am tired - Subjunctive after "aunque" when uncertain, irregular "estar"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_108',
    emoji: '🧠',
    question: 'No hay nadie que ___ la respuesta. (saber - to know)',
    options: ['sepa', 'sabe', 'sabrá'],
    correctAnswer: 'sepa',
    hint: 'There\'s no one who knows - Subjunctive after negative + "que", irregular "saber"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_109',
    emoji: '➡️',
    question: 'Cuando ___ a España, te llamaré. (ir - to go)',
    options: ['vaya', 'voy', 'iré'],
    correctAnswer: 'vaya',
    hint: 'When I go to Spain - Subjunctive after "cuando" for future events, irregular "ir"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_110',
    emoji: '🏨',
    question: 'Busco un hotel que ___ económico. (ser - to be)',
    options: ['sea', 'es', 'será'],
    correctAnswer: 'sea',
    hint: 'I\'m looking for a hotel that is cheap - Subjunctive for uncertain/nonexistent, irregular "ser"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },

  // Direct and Indirect Object Pronouns (10 questions)
  {
    id: 'grammar_111',
    emoji: '📚',
    question: 'Te ___ el libro mañana. (dar - I will give you)',
    options: ['daré', 'doy', 'daba'],
    correctAnswer: 'daré',
    hint: 'I will give you the book - "te" is indirect object pronoun, future tense of "dar"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_112',
    emoji: '🎁',
    question: 'María ___ compró un regalo. (me - to me)',
    options: ['me', 'te', 'le'],
    correctAnswer: 'me',
    hint: 'María bought me a gift - indirect object pronoun "me" (to me) goes before verb',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_113',
    emoji: '👀',
    question: '___ veo todos los días. (te - you)',
    options: ['Te', 'Le', 'Lo'],
    correctAnswer: 'Te',
    hint: 'I see you every day - direct object pronoun "te" (you) for informal singular',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_114',
    emoji: '🌸',
    question: 'Voy a dar___ las flores. (to them)',
    options: ['les', 'los', 'las'],
    correctAnswer: 'les',
    hint: 'I\'m going to give them the flowers - "les" is indirect object (to them), can attach to infinitive',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_115',
    emoji: '📞',
    question: 'Ella ___ llamó ayer. (nos - us)',
    options: ['nos', 'les', 'los'],
    correctAnswer: 'nos',
    hint: 'She called us yesterday - "nos" is direct/indirect object pronoun (us/to us)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_116',
    emoji: '🆘',
    question: '¿___ puedes ayudar? (me - can you help me)',
    options: ['Me', 'Te', 'Le'],
    correctAnswer: 'Me',
    hint: 'Can you help me? - "me" is object pronoun, goes before conjugated verb',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_117',
    emoji: '💬',
    question: 'Se ___ dije ayer. (lo - it)',
    options: ['lo', 'la', 'le'],
    correctAnswer: 'lo',
    hint: 'I told it to him/her yesterday - "lo" is direct object (it/masculine), "se" replaces "le"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_118',
    emoji: '🚗',
    question: 'Quiero comprar___ un coche. (me - for myself)',
    options: ['me', 'te', 'se'],
    correctAnswer: 'me',
    hint: 'I want to buy myself a car - reflexive/indirect pronoun attached to infinitive',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_119',
    emoji: '👁️',
    question: '___ están mirando. (nos - they are looking at us)',
    options: ['Nos', 'Les', 'Los'],
    correctAnswer: 'Nos',
    hint: 'They are looking at us - "nos" direct object with progressive form',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_120',
    emoji: '📮',
    question: 'Se ___ enviamos por correo. (las - them/feminine)',
    options: ['las', 'los', 'les'],
    correctAnswer: 'las',
    hint: 'We sent them (feminine) by mail - "las" direct object, "se" replaces "les"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },

  // Reflexive Verbs (10 questions)
  {
    id: 'grammar_121',
    emoji: '🛁',
    question: 'Me ___ todos los días. (bañar - I bathe)',
    options: ['baño', 'bañas', 'baña'],
    correctAnswer: 'baño',
    hint: 'I bathe every day - reflexive verb "bañarse", first person present',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_122',
    emoji: '⏰',
    question: '¿Te ___ temprano? (levantar - do you get up)',
    options: ['levantas', 'levanto', 'levanta'],
    correctAnswer: 'levantas',
    hint: 'Do you get up early? - reflexive "levantarse" (to get up), second person',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_123',
    emoji: '🛏️',
    question: 'Se ___ a las ocho. (acostar - he goes to bed)',
    options: ['acuesta', 'acuesto', 'acuestas'],
    correctAnswer: 'acuesta',
    hint: 'He goes to bed at eight - reflexive "acostarse", stem change o→ue, third person',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_124',
    emoji: '🎉',
    question: 'Nos ___ mucho. (divertir - we have fun)',
    options: ['divertimos', 'divertís', 'divierten'],
    correctAnswer: 'divertimos',
    hint: 'We have fun a lot - reflexive "divertirse", stem change e→ie, first person plural',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_125',
    emoji: '🪞',
    question: 'Se ___ en el espejo. (mirar - they look at themselves)',
    options: ['miran', 'miro', 'miras'],
    correctAnswer: 'miran',
    hint: 'They look at themselves in the mirror - reflexive "mirarse", third person plural',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_126',
    emoji: '🏷️',
    question: 'Me ___ Juan. (llamar - my name is)',
    options: ['llamo', 'llamas', 'llama'],
    correctAnswer: 'llamo',
    hint: 'My name is Juan - literally "I call myself", reflexive "llamarse"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_127',
    emoji: '🤒',
    question: '¿Te ___ bien? (sentir - do you feel)',
    options: ['sientes', 'siento', 'siente'],
    correctAnswer: 'sientes',
    hint: 'Do you feel well? - reflexive "sentirse", stem change e→ie, second person',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_128',
    emoji: '🧼',
    question: 'Nos ___ las manos. (lavar - we wash)',
    options: ['lavamos', 'laváis', 'lavan'],
    correctAnswer: 'lavamos',
    hint: 'We wash our hands - reflexive "lavarse", first person plural',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_129',
    emoji: '👔',
    question: 'Se ___ rápido. (vestir - she gets dressed)',
    options: ['viste', 'visto', 'vistes'],
    correctAnswer: 'viste',
    hint: 'She gets dressed quickly - reflexive "vestirse", stem change e→i, third person',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_130',
    emoji: '🧥',
    question: 'Me ___ el abrigo. (poner - I put on)',
    options: ['pongo', 'pones', 'pone'],
    correctAnswer: 'pongo',
    hint: 'I put on my coat - reflexive "ponerse", irregular first person "pongo"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Comparatives and Superlatives (10 questions)
  {
    id: 'grammar_131',
    emoji: '📏',
    question: 'María es ___ alta que Juan. (more)',
    options: ['más', 'menos', 'tan'],
    correctAnswer: 'más',
    hint: 'María is taller than Juan - "más... que" (more... than) for comparisons',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_132',
    emoji: '⚖️',
    question: 'Este libro es ___ interesante como ese. (as)',
    options: ['tan', 'más', 'menos'],
    correctAnswer: 'tan',
    hint: 'This book is as interesting as that one - "tan... como" (as... as) for equality',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_133',
    emoji: '💰',
    question: 'Tengo ___ dinero que tú. (less)',
    options: ['menos', 'más', 'tan'],
    correctAnswer: 'menos',
    hint: 'I have less money than you - "menos... que" (less... than)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_134',
    emoji: '🏆',
    question: 'Es el ___ grande de todos. (most)',
    options: ['más', 'muy', 'tan'],
    correctAnswer: 'más',
    hint: 'It\'s the biggest of all - superlative: "el más... de" (the most... of)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_135',
    emoji: '👦👨',
    question: 'Mi hermano es ___ que yo. (older/better)',
    options: ['mayor', 'más viejo', 'grande'],
    correctAnswer: 'mayor',
    hint: 'My brother is older than me - "mayor" irregular comparative (older/better)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_136',
    emoji: '🏡',
    question: 'Esta casa es la ___ bonita. (most)',
    options: ['más', 'muy', 'mucho'],
    correctAnswer: 'más',
    hint: 'This house is the prettiest - superlative with adjective',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_137',
    emoji: '🥶',
    question: 'Hoy hace ___ frío que ayer. (more)',
    options: ['más', 'mucho', 'muy'],
    correctAnswer: 'más',
    hint: 'Today it\'s colder than yesterday - "hace más frío que"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_138',
    emoji: '📝',
    question: 'Este examen es ___ difícil que el otro. (less)',
    options: ['menos', 'más', 'tan'],
    correctAnswer: 'menos',
    hint: 'This test is less difficult than the other - "menos... que"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_139',
    emoji: '👧',
    question: 'Ella es ___ de la clase. (the youngest)',
    options: ['la menor', 'la más joven', 'la pequeña'],
    correctAnswer: 'la menor',
    hint: 'She\'s the youngest in the class - "menor" irregular superlative',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_140',
    emoji: '📚',
    question: 'Tengo ___ libros como tú. (as many)',
    options: ['tantos', 'tan', 'tanto'],
    correctAnswer: 'tantos',
    hint: 'I have as many books as you - "tantos... como" for countable nouns (plural)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Por vs Para (10 questions)
  {
    id: 'grammar_141',
    emoji: '🛒',
    question: 'Voy al mercado ___ comprar frutas. (in order to)',
    options: ['para', 'por', 'a'],
    correctAnswer: 'para',
    hint: 'I\'m going to the market to buy fruits - "para" for purpose/goal',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_142',
    emoji: '🙏',
    question: 'Gracias ___ tu ayuda. (for - reason)',
    options: ['por', 'para', 'de'],
    correctAnswer: 'por',
    hint: 'Thanks for your help - "por" for reason/motive',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_143',
    emoji: '🎁',
    question: 'Este regalo es ___ ti. (for you - recipient)',
    options: ['para', 'por', 'a'],
    correctAnswer: 'para',
    hint: 'This gift is for you - "para" for recipient/destination',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_144',
    emoji: '🌳',
    question: 'Caminamos ___ el parque. (through)',
    options: ['por', 'para', 'en'],
    correctAnswer: 'por',
    hint: 'We walk through the park - "por" for movement through/along',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_145',
    emoji: '👨‍⚕️',
    question: 'Estudio ___ ser médico. (in order to be)',
    options: ['para', 'por', 'a'],
    correctAnswer: 'para',
    hint: 'I study to be a doctor - "para" for purpose/goal',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_146',
    emoji: '💝',
    question: 'Lo hice ___ ella. (because of her)',
    options: ['por', 'para', 'de'],
    correctAnswer: 'por',
    hint: 'I did it because of her - "por" for reason/on behalf of',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_147',
    emoji: '🏢',
    question: 'Trabajo ___ una empresa grande. (for - employer)',
    options: ['para', 'por', 'en'],
    correctAnswer: 'para',
    hint: 'I work for a big company - "para" for employer/recipient',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_148',
    emoji: '✈️',
    question: 'Viajamos ___ avión. (by - means)',
    options: ['por', 'para', 'en'],
    correctAnswer: 'por',
    hint: 'We travel by plane - "por" for means of transportation',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_149',
    emoji: '📋',
    question: 'Necesito el informe ___ mañana. (by/for - deadline)',
    options: ['para', 'por', 'en'],
    correctAnswer: 'para',
    hint: 'I need the report by tomorrow - "para" for deadlines',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_150',
    emoji: '💶',
    question: 'Pagué veinte euros ___ el libro. (for - price)',
    options: ['por', 'para', 'de'],
    correctAnswer: 'por',
    hint: 'I paid twenty euros for the book - "por" for price/exchange',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Commands (Imperative) (10 questions)
  {
    id: 'grammar_151',
    emoji: '👉',
    question: '¡___ aquí! (come - tú command)',
    options: ['Ven', 'Venga', 'Venir'],
    correctAnswer: 'Ven',
    hint: 'Come here! - irregular affirmative tú command of "venir"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_152',
    emoji: '🚫',
    question: '¡No ___ eso! (do - negative tú command)',
    options: ['hagas', 'haces', 'haz'],
    correctAnswer: 'hagas',
    hint: 'Don\'t do that! - negative tú command uses subjunctive form',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_153',
    emoji: '📝',
    question: '¡___ la tarea! (do - tú command)',
    options: ['Haz', 'Hace', 'Hacer'],
    correctAnswer: 'Haz',
    hint: 'Do the homework! - irregular affirmative tú command of "hacer"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_154',
    emoji: '🗣️',
    question: '¡___ la verdad! (tell - usted command)',
    options: ['Diga', 'Di', 'Dice'],
    correctAnswer: 'Diga',
    hint: 'Tell the truth! - formal command uses subjunctive form of "decir"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_155',
    emoji: '🚗',
    question: '¡___ con cuidado! (drive - tú command)',
    options: ['Conduce', 'Conduces', 'Conducir'],
    correctAnswer: 'Conduce',
    hint: 'Drive carefully! - regular affirmative tú command, drop the "s"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_156',
    emoji: '⏰',
    question: '¡No ___ tarde! (arrive - tú command)',
    options: ['llegues', 'llegas', 'llega'],
    correctAnswer: 'llegues',
    hint: 'Don\'t arrive late! - negative tú command uses subjunctive',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_157',
    emoji: '🧘',
    question: '¡___ pacientes! (be - ustedes command)',
    options: ['Sean', 'Son', 'Ser'],
    correctAnswer: 'Sean',
    hint: 'Be patient! - formal plural command of "ser" uses subjunctive',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_158',
    emoji: '✅',
    question: '¡___ responsable! (be - tú command)',
    options: ['Sé', 'Eres', 'Ser'],
    correctAnswer: 'Sé',
    hint: 'Be responsible! - irregular affirmative tú command of "ser"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_159',
    emoji: '🚪',
    question: '¡___! (leave/go out - tú command)',
    options: ['Sal', 'Sale', 'Salir'],
    correctAnswer: 'Sal',
    hint: 'Leave!/Go out! - irregular affirmative tú command of "salir"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_160',
    emoji: '👋',
    question: '¡___ con nosotros! (come - usted command)',
    options: ['Venga', 'Ven', 'Viene'],
    correctAnswer: 'Venga',
    hint: 'Come with us! - formal command of "venir" uses subjunctive form',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Prepositions (10 questions)
  {
    id: 'grammar_161',
    emoji: '🏫',
    question: 'Voy ___ la escuela. (to)',
    options: ['a', 'en', 'de'],
    correctAnswer: 'a',
    hint: 'I\'m going to school - "a" for direction/destination',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_162',
    emoji: '📕',
    question: 'El libro está ___ la mesa. (on)',
    options: ['en', 'sobre', 'a'],
    correctAnswer: 'en',
    hint: 'The book is on the table - "en" for location (on/in)',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_163',
    emoji: '🇪🇸',
    question: 'Vengo ___ España. (from)',
    options: ['de', 'desde', 'a'],
    correctAnswer: 'de',
    hint: 'I come from Spain - "de" for origin',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_164',
    emoji: '🐱',
    question: 'El gato está ___ la cama. (under)',
    options: ['debajo de', 'encima de', 'sobre'],
    correctAnswer: 'debajo de',
    hint: 'The cat is under the bed - "debajo de" (under/below)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_165',
    emoji: '👨‍👩‍👧',
    question: 'Vivo ___ mis padres. (with)',
    options: ['con', 'en', 'a'],
    correctAnswer: 'con',
    hint: 'I live with my parents - "con" (with)',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_166',
    emoji: '🖼️',
    question: 'El cuadro está ___ la pared. (on - attached)',
    options: ['en', 'sobre', 'a'],
    correctAnswer: 'en',
    hint: 'The picture is on the wall - "en" for attached to surface',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_167',
    emoji: '🕐',
    question: 'Estudio ___ las ocho. (until)',
    options: ['hasta', 'desde', 'a'],
    correctAnswer: 'hasta',
    hint: 'I study until eight - "hasta" (until)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_168',
    emoji: '🏪',
    question: 'La tienda está ___ el banco. (next to)',
    options: ['al lado de', 'cerca de', 'lejos de'],
    correctAnswer: 'al lado de',
    hint: 'The store is next to the bank - "al lado de" (next to)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_169',
    emoji: '🕘',
    question: 'Trabajo ___ las nueve. (from - starting point)',
    options: ['desde', 'de', 'a'],
    correctAnswer: 'desde',
    hint: 'I work from nine - "desde" (from/since) for time starting point',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_170',
    emoji: '➡️',
    question: 'Camino ___ el parque. (toward)',
    options: ['hacia', 'a', 'para'],
    correctAnswer: 'hacia',
    hint: 'I walk toward the park - "hacia" (toward/in the direction of)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Perfect Tenses (10 questions)
  {
    id: 'grammar_171',
    emoji: '✔️',
    question: 'Yo ___ comido ya. (have)',
    options: ['he', 'ha', 'has'],
    correctAnswer: 'he',
    hint: 'I have already eaten - present perfect with "haber" + past participle',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_172',
    emoji: '🗼',
    question: 'Ella ___ visitado París. (has)',
    options: ['ha', 'he', 'han'],
    correctAnswer: 'ha',
    hint: 'She has visited Paris - third person present perfect',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_173',
    emoji: '🎬',
    question: '¿___ visto la película? (have you - tú)',
    options: ['Has', 'He', 'Ha'],
    correctAnswer: 'Has',
    hint: 'Have you seen the movie? - second person present perfect',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_174',
    emoji: '✅',
    question: 'Nosotros ___ terminado el trabajo. (have)',
    options: ['hemos', 'habemos', 'han'],
    correctAnswer: 'hemos',
    hint: 'We have finished the work - first person plural present perfect',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_175',
    emoji: '⏱️',
    question: 'Ellos ___ llegado tarde. (have)',
    options: ['han', 'ha', 'hemos'],
    correctAnswer: 'han',
    hint: 'They have arrived late - third person plural present perfect',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_176',
    emoji: '💔',
    question: 'Él ___ roto el vaso. (has broken)',
    options: ['ha roto', 'ha rompido', 'rompió'],
    correctAnswer: 'ha roto',
    hint: 'He has broken the glass - irregular past participle "roto" from "romper"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_177',
    emoji: '✍️',
    question: '¿___ escrito la carta? (have you - tú)',
    options: ['Has escrito', 'Has escribido', 'Escribiste'],
    correctAnswer: 'Has escrito',
    hint: 'Have you written the letter? - irregular past participle "escrito"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_178',
    emoji: '💯',
    question: 'Yo ___ dicho la verdad. (have said)',
    options: ['he dicho', 'he decido', 'dije'],
    correctAnswer: 'he dicho',
    hint: 'I have told the truth - irregular past participle "dicho" from "decir"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_179',
    emoji: '🌊',
    question: 'Ella nunca ___ visto el mar. (has)',
    options: ['ha', 'he', 'han'],
    correctAnswer: 'ha',
    hint: 'She has never seen the ocean - present perfect with "nunca" (never)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_180',
    emoji: '🚪',
    question: 'Nosotros ___ abierto la puerta. (have opened)',
    options: ['hemos abierto', 'hemos abrido', 'abrimos'],
    correctAnswer: 'hemos abierto',
    hint: 'We have opened the door - irregular past participle "abierto" from "abrir"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },

  // Advanced Grammar Concepts (10 questions)
  {
    id: 'grammar_181',
    emoji: '🌤️',
    question: 'Ojalá que ___ buen tiempo mañana. (hacer - I hope)',
    options: ['haga', 'hace', 'hará'],
    correctAnswer: 'haga',
    hint: 'I hope the weather is good tomorrow - "ojalá que" requires subjunctive',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_182',
    emoji: '💭',
    question: 'Si ___ dinero, compraría una casa. (tener - if I had)',
    options: ['tuviera', 'tengo', 'tendría'],
    correctAnswer: 'tuviera',
    hint: 'If I had money, I would buy a house - imperfect subjunctive in "si" clause',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_183',
    emoji: '⏰',
    question: 'Es importante que tú ___ a tiempo. (llegar)',
    options: ['llegues', 'llegas', 'llegarás'],
    correctAnswer: 'llegues',
    hint: 'It\'s important that you arrive on time - subjunctive after impersonal expression',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_184',
    emoji: '☕',
    question: 'Me gusta ___ café por la mañana. (drink)',
    options: ['tomar', 'tomando', 'que tomo'],
    correctAnswer: 'tomar',
    hint: 'I like to drink coffee in the morning - infinitive after "gustar"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_185',
    emoji: '🚿',
    question: 'Antes de ___, me ducho. (to leave)',
    options: ['salir', 'salgo', 'saliendo'],
    correctAnswer: 'salir',
    hint: 'Before leaving, I shower - infinitive after "antes de"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_186',
    emoji: '🏠',
    question: 'Al ___ a casa, vi a María. (to arrive)',
    options: ['llegar', 'llego', 'llegando'],
    correctAnswer: 'llegar',
    hint: 'Upon arriving home, I saw María - infinitive after "al"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_187',
    emoji: '📖',
    question: 'Acabo de ___ un libro. (read - just finished)',
    options: ['leer', 'leo', 'leyendo'],
    correctAnswer: 'leer',
    hint: 'I just read a book - "acabar de" + infinitive (to have just done)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_188',
    emoji: '📅',
    question: 'Llevo tres años ___ español. (studying)',
    options: ['estudiando', 'estudiar', 'estudio'],
    correctAnswer: 'estudiando',
    hint: 'I\'ve been studying Spanish for three years - "llevar" + gerund for duration',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_189',
    emoji: '🇪🇸',
    question: 'Se ___ español en España. (one speaks/is spoken)',
    options: ['habla', 'hable', 'hablan'],
    correctAnswer: 'habla',
    hint: 'Spanish is spoken in Spain - impersonal "se" with third person singular',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_190',
    emoji: '🎵',
    question: 'Me encanta ___ música. (to listen to)',
    options: ['escuchar', 'escuchando', 'que escucho'],
    correctAnswer: 'escuchar',
    hint: 'I love listening to music - infinitive after "encantar"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Mixed Review (10 questions)
  {
    id: 'grammar_191',
    emoji: '🇲🇽',
    question: 'El año pasado ___ a México. (I went)',
    options: ['fui', 'iba', 'iré'],
    correctAnswer: 'fui',
    hint: 'Last year I went to Mexico - preterite for completed past action',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_192',
    emoji: '👶',
    question: 'Cuando era niño, ___ mucho. (I used to play)',
    options: ['jugaba', 'jugué', 'juego'],
    correctAnswer: 'jugaba',
    hint: 'When I was a child, I used to play a lot - imperfect for habitual past',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_193',
    emoji: '🎓',
    question: '¿___ estudiantes hay en la clase? (How many)',
    options: ['Cuántos', 'Cuánto', 'Cuántas'],
    correctAnswer: 'Cuántos',
    hint: 'How many students are in the class? - "cuántos" for masculine plural count',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_194',
    emoji: '🤕',
    question: 'Me duele ___ cabeza. (the - feminine)',
    options: ['la', 'el', 'las'],
    correctAnswer: 'la',
    hint: 'My head hurts - "la cabeza" is feminine, body parts use definite article',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_195',
    emoji: '🚂',
    question: '¿A qué hora ___ el tren? (leaves - salir)',
    options: ['sale', 'salga', 'salió'],
    correctAnswer: 'sale',
    hint: 'What time does the train leave? - present tense for schedules',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_196',
    emoji: '👬',
    question: 'Mis hermanos ___ altos. (are)',
    options: ['son', 'están', 'es'],
    correctAnswer: 'son',
    hint: 'My brothers are tall - "ser" for permanent characteristics, plural',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_197',
    emoji: '📱',
    question: '¿___ es tu número de teléfono? (What)',
    options: ['Cuál', 'Qué', 'Quién'],
    correctAnswer: 'Cuál',
    hint: 'What is your phone number? - "cuál" for selection/which one',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_198',
    emoji: '🤷‍♀️',
    question: 'No tengo ___ idea. (any/no)',
    options: ['ninguna', 'alguna', 'una'],
    correctAnswer: 'ninguna',
    hint: 'I have no idea - "ninguna" (no/not any) feminine singular',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_199',
    emoji: '🌧️',
    question: 'Ayer ___ todo el día. (it rained)',
    options: ['llovió', 'llovía', 'llueve'],
    correctAnswer: 'llovió',
    hint: 'Yesterday it rained all day - preterite for completed action (even if duration)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_200',
    emoji: '🏖️',
    question: 'Voy a ___ en la playa este verano. (relax)',
    options: ['relajarme', 'relajo', 'relajando'],
    correctAnswer: 'relajarme',
    hint: 'I\'m going to relax on the beach this summer - reflexive infinitive after "ir a"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
 
];
