/**
 * GREETINGS & CONVERSATIONS Category Questions
 * Category: greetings
 */

export const greetingsQuestions = [
// Basic Greetings (10 questions)
  {
    id: 'greetings_001',
    emoji: '👋',
    question: '¿Cómo saludas a alguien por la mañana?',
    options: ['buenos días', 'buen día', 'buen día tengas'],
    correctAnswer: 'buenos días',
    hint: 'Good morning - literally "good days" (plural), from Latin "bonus dies", use until 2pm',
    usageExample: '¡Buenos días! ¿Cómo amaneciste hoy?',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'greetings_002',
    emoji: '🌅',
    question: '¿Qué dices por la tarde?',
    options: ['buenas tardes', 'buena tarde', 'tardes buenas'],
    correctAnswer: 'buenas tardes',
    hint: 'Good afternoon - "tardes" feminine plural, use 2pm-sunset, timing varies by region',
    usageExample: 'Buenas tardes, ¿cómo le va?',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_003',
    emoji: '🌙',
    question: '¿Qué dices cuando es de noche?',
    options: ['buenas noches', 'buena noche', 'noches buenas'],
    correctAnswer: 'buenas noches',
    hint: 'Good night - works as greeting after sunset AND farewell before sleep',
    usageExample: '¡Buenas noches! Que descanses bien.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'greetings_004',
    emoji: '👋',
    question: '¿Cómo dices "hello" informalmente?',
    options: ['hola', 'ola', 'holaa'],
    correctAnswer: 'hola',
    hint: 'Hello - universal informal greeting anytime, no gender/formality changes, from Arabic "wa-llāh"',
    usageExample: '¡Hola! ¿Qué tal estás?',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'greetings_005',
    emoji: '👋',
    question: '¿Cómo dices "goodbye"?',
    options: ['adiós', 'a dios', 'adios'],
    correctAnswer: 'adiós',
    hint: 'Goodbye - literally "to God" (a + Dios), permanent farewell, "chau" more casual',
    usageExample: 'Adiós, fue un placer conocerte.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'sad',
  },
  {
    id: 'greetings_006',
    emoji: '🌅',
    question: '¿Qué es otra forma de decir "adiós"?',
    options: ['hasta luego', 'hasta la vista', 'hasta pronto'],
    correctAnswer: 'hasta luego',
    hint: 'See you later - "hasta" (until) + "luego" (later), implies you\'ll meet again soon',
    usageExample: 'Hasta luego, nos vemos en la tarde.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_007',
    emoji: '💤',
    question: '¿Qué dices antes de dormir?',
    options: ['buenas noches', 'buena noche', 'dulces sueños'],
    correctAnswer: 'buenas noches',
    hint: 'Good night - before sleep, same phrase as evening greeting but context differs',
    usageExample: '¡Buenas noches! Que descanses bien.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'greetings_008',
    emoji: '🌄',
    question: '¿Qué significa "hasta mañana"?',
    options: ['see you tomorrow', 'until tomorrow', 'see you later'],
    correctAnswer: 'see you tomorrow',
    hint: 'See you tomorrow - "hasta" (until) + "mañana" (tomorrow/morning), confirms next-day meeting',
    usageExample: 'Hasta mañana, te veo en la escuela.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_009',
    emoji: '👋',
    question: '¿Cómo preguntas "how are you?"',
    options: ['¿cómo estás?', '¿cómo está?', '¿cómo estáis?'],
    correctAnswer: '¿cómo estás?',
    hint: 'How are you? - informal tú form, "¿cómo está?" for usted formal, from "estar" (to be)',
    usageExample: 'Hola María, ¿cómo estás? Te ves muy feliz.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'greetings_010',
    emoji: '👍',
    question: '¿Cómo respondes "I am fine"?',
    options: ['estoy bien', 'muy bien', 'todo bien'],
    correctAnswer: 'estoy bien',
    hint: 'I\'m fine - "estoy" (I am) + "bien" (well/good), "muy bien" for very well, "regular" for so-so',
    usageExample: 'Gracias por preguntar, estoy bien.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'happy',
  },

  // Politeness & Courtesy (10 questions)
  {
    id: 'greetings_011',
    emoji: '🙏',
    question: '¿Cómo dices "please"?',
    options: ['por favor', 'de favor', 'con favor'],
    correctAnswer: 'por favor',
    hint: 'Please - literally "for favor", from Latin "pro favore", essential politeness in Spanish culture',
    usageExample: '¿Me pasas el agua, por favor?',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'greetings_012',
    emoji: '😊',
    question: '¿Cómo dices "thank you"?',
    options: ['gracias', 'muchas gracias', 'mil gracias'],
    correctAnswer: 'gracias',
    hint: 'Thank you - from Latin "gratias" (thanks), "muchas gracias" for many thanks',
    usageExample: 'Gracias por tu ayuda, eres muy amable.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_013',
    emoji: '👍',
    question: '¿Cómo respondes a "gracias"?',
    options: ['de nada', 'no hay de qué', 'con gusto'],
    correctAnswer: 'de nada',
    hint: 'You\'re welcome - literally "of nothing", also "no hay de qué" (there\'s nothing to thank)',
    usageExample: '— Gracias. — De nada, para eso están los amigos.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_014',
    emoji: '🙇',
    question: '¿Cómo dices "excuse me"?',
    options: ['perdón', 'disculpa', 'perdone'],
    correctAnswer: 'perdón',
    hint: 'Excuse me/Sorry - from "perdonar" (to forgive), "disculpe" more formal, "con permiso" to pass by',
    usageExample: 'Perdón, ¿dónde está el baño?',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'greetings_015',
    emoji: '😔',
    question: '¿Cómo dices "I am sorry"?',
    options: ['lo siento', 'lo lamento', 'siento mucho'],
    correctAnswer: 'lo siento',
    hint: 'I\'m sorry - literally "I feel it", expresses empathy/regret, deeper than "perdón"',
    usageExample: 'Lo siento mucho, no fue mi intención.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'sad',
  },
  {
    id: 'greetings_016',
    emoji: '🤝',
    question: '¿Cómo dices "nice to meet you"?',
    options: ['mucho gusto', 'encantado', 'un placer'],
    correctAnswer: 'mucho gusto',
    hint: 'Nice to meet you - literally "much pleasure", response is "igualmente" (likewise) or "el gusto es mío"',
    usageExample: 'Mucho gusto en conocerte, Ana.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'greetings_017',
    emoji: '🙏',
    question: '¿Qué es otra forma de decir "gracias"?',
    options: ['muchas gracias', 'muchísimas gracias', 'mil gracias'],
    correctAnswer: 'muchas gracias',
    hint: 'Thank you very much - "muchas" (many, feminine plural), "muchísimas gracias" even stronger',
    usageExample: 'Muchas gracias por el regalo, me encanta.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_018',
    emoji: '👋',
    question: '¿Cómo respondes a "mucho gusto"?',
    options: ['igualmente', 'el gusto es mío', 'encantado'],
    correctAnswer: 'igualmente',
    hint: 'Likewise - from "igual" (equal), also "el gusto es mío" (pleasure is mine)',
    usageExample: '— Mucho gusto. — Igualmente, encantado.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'greetings_019',
    emoji: '🙏',
    question: '¿Cómo pides permiso para pasar?',
    options: ['con permiso', 'permiso', 'disculpe'],
    correctAnswer: 'con permiso',
    hint: 'With permission - polite phrase to pass by someone or leave room, shows respect',
    usageExample: 'Con permiso, necesito pasar.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'greetings_020',
    emoji: '😇',
    question: '¿Cómo deseas buena suerte?',
    options: ['buena suerte', 'mucha suerte', 'que tengas suerte'],
    correctAnswer: 'buena suerte',
    hint: 'Good luck - "suerte" (luck) from Latin "sors" (fate/lot), "¡que tengas suerte!" also common',
    usageExample: '¡Buena suerte en tu examen!',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'determined',
  },

  // Common Questions (10 questions)
  {
    id: 'greetings_021',
    emoji: '❓',
    question: '¿Cómo preguntas "what is your name?"',
    options: ['¿cómo te llamas?', '¿cómo se llama?', '¿cuál es tu nombre?'],
    correctAnswer: '¿cómo te llamas?',
    hint: 'What\'s your name? - literally "how do you call yourself?", "¿cómo se llama?" formal usted',
    usageExample: 'Hola, ¿cómo te llamas? Yo soy Pedro.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'greetings_022',
    emoji: '🗣️',
    question: '¿Cómo dices "my name is..."?',
    options: ['me llamo', 'mi nombre es', 'yo soy'],
    correctAnswer: 'me llamo',
    hint: 'My name is... - literally "I call myself", from "llamar" (to call), "mi nombre es" also used',
    usageExample: 'Me llamo Carlos, mucho gusto.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_023',
    emoji: '🌍',
    question: '¿Cómo preguntas "where are you from?"',
    options: ['¿de dónde eres?', '¿de dónde es?', '¿de dónde vienes?'],
    correctAnswer: '¿de dónde eres?',
    hint: 'Where are you from? - "de dónde" (from where), "¿de dónde es?" formal usted form',
    usageExample: '¿De dónde eres? Tu acento es muy interesante.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'greetings_024',
    emoji: '🏠',
    question: '¿Cómo respondes "I am from..."?',
    options: ['soy de', 'vengo de', 'provengo de'],
    correctAnswer: 'soy de',
    hint: 'I\'m from... - "soy" (I am) + "de" (from), uses "ser" for origin/nationality',
    usageExample: 'Soy de México, de la ciudad de Guadalajara.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_025',
    emoji: '🗨️',
    question: '¿Cómo preguntas "what\'s up?"',
    options: ['¿qué tal?', '¿qué pasa?', '¿qué onda?'],
    correctAnswer: '¿qué tal?',
    hint: 'What\'s up? - casual greeting, literally "what such?", Spain also uses "¿qué pasa?"',
    usageExample: '¡Hola! ¿Qué tal? ¿Todo bien?',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'greetings_026',
    emoji: '🎂',
    question: '¿Cuántos años tienes? means what?',
    options: ['how old are you?', 'how many years do you have?', 'what is your age?'],
    correctAnswer: 'how old are you?',
    hint: 'How old are you? - literally "how many years do you have?", Spanish uses "tener" (have) for age',
    usageExample: '¿Cuántos años tienes? Pareces muy joven.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'greetings_027',
    emoji: '🔢',
    question: '¿Cómo respondes "I am 25 years old"?',
    options: ['tengo 25 años', 'tengo veinticinco años', 'cumplo 25 años'],
    correctAnswer: 'tengo 25 años',
    hint: 'I\'m 25 years old - uses "tengo" (I have), not "soy", "años" always plural after 1',
    usageExample: 'Tengo 25 años y estudio en la universidad.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'greetings_028',
    emoji: '🗣️',
    question: '¿Cómo preguntas "do you speak Spanish?"',
    options: ['¿hablas español?', '¿habla español?', '¿sabes español?'],
    correctAnswer: '¿hablas español?',
    hint: 'Do you speak Spanish? - "hablas" from "hablar" (to speak), "¿habla español?" formal usted',
    usageExample: '¿Hablas español? Me gustaría practicar contigo.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'greetings_029',
    emoji: '🇬🇧',
    question: '¿Cómo preguntas "do you speak English?"',
    options: ['¿hablas inglés?', '¿habla inglés?', '¿sabes inglés?'],
    correctAnswer: '¿hablas inglés?',
    hint: 'Do you speak English? - "inglés" (English language), essential tourist question',
    usageExample: 'Disculpe, ¿hablas inglés? No entiendo muy bien español.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'greetings_030',
    emoji: '❌',
    question: '¿Cómo dices "I don\'t understand"?',
    options: ['no entiendo', 'no comprendo', 'no capto'],
    correctAnswer: 'no entiendo',
    hint: 'I don\'t understand - "entiendo" from "entender", "no comprendo" also used, essential phrase',
    usageExample: 'Lo siento, no entiendo. ¿Puedes hablar más despacio?',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'confused',
  },

  // Conversation Basics (10 questions)
  {
    id: 'greetings_031',
    emoji: '✅',
    question: '¿Cómo dices "yes"?',
    options: ['sí', 'síí', 'siii'],
    correctAnswer: 'sí',
    hint: 'Yes - affirmative, has accent (sí) to distinguish from "si" (if), from Latin "sic"',
    usageExample: '— ¿Quieres café? — Sí, por favor.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_032',
    emoji: '❌',
    question: '¿Cómo dices "no"?',
    options: ['no', 'noo', 'nooo'],
    correctAnswer: 'no',
    hint: 'No - negative answer, same as English, from Latin "non", double negatives common in Spanish',
    usageExample: '— ¿Tienes hambre? — No, gracias, ya comí.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'greetings_033',
    emoji: '🤷',
    question: '¿Cómo dices "maybe"?',
    options: ['tal vez', 'quizás', 'a lo mejor'],
    correctAnswer: 'tal vez',
    hint: 'Maybe - literally "such time", "quizás" and "a lo mejor" also used for uncertainty',
    usageExample: 'Tal vez vaya al cine mañana, no estoy seguro.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'greetings_034',
    emoji: '👍',
    question: '¿Cómo dices "okay" o "fine"?',
    options: ['vale', 'está bien', 'ok'],
    correctAnswer: 'vale',
    hint: 'Okay/Fine - very common in Spain, Latin America uses "está bien" or "OK", from "valer" (to be worth)',
    usageExample: '— ¿Nos vemos a las 5? — Vale, perfecto.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'greetings_035',
    emoji: '👌',
    question: '¿Cómo dices "of course"?',
    options: ['claro', 'por supuesto', 'desde luego'],
    correctAnswer: 'claro',
    hint: 'Of course - literally "clear", "por supuesto" more formal, shows strong agreement',
    usageExample: '— ¿Puedo usar tu teléfono? — Claro, adelante.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'greetings_036',
    emoji: '⏰',
    question: '¿Cómo preguntas "what time is it?"',
    options: ['¿qué hora es?', '¿qué horas son?', '¿cuál es la hora?'],
    correctAnswer: '¿qué hora es?',
    hint: 'What time is it? - "hora" (hour) singular, answer uses "es la" (singular) or "son las" (plural)',
    usageExample: 'Perdón, ¿qué hora es? Olvidé mi reloj.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'greetings_037',
    emoji: '📅',
    question: '¿Cómo preguntas "what day is today?"',
    options: ['¿qué día es hoy?', '¿qué día es?', '¿cuál día es hoy?'],
    correctAnswer: '¿qué día es hoy?',
    hint: 'What day is today? - "día" (day) + "hoy" (today), answer: "hoy es lunes" (today is Monday)',
    usageExample: '¿Qué día es hoy? Creo que es miércoles.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'greetings_038',
    emoji: '🔍',
    question: '¿Cómo dices "I don\'t know"?',
    options: ['no sé', 'no lo sé', 'ni idea'],
    correctAnswer: 'no sé',
    hint: 'I don\'t know - "sé" from "saber" (to know facts), different from "conocer" (to know people/places)',
    usageExample: '— ¿Dónde está Juan? — No sé, no lo he visto.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'confused',
  },
  {
    id: 'greetings_039',
    emoji: '🙋',
    question: '¿Cómo dices "help" o "help me"?',
    options: ['ayuda', 'ayúdame', 'socorro'],
    correctAnswer: 'ayuda',
    hint: 'Help - command form of "ayudar", "ayúdame" (help me), "¡socorro!" for emergencies',
    usageExample: '¡Ayuda! No puedo abrir la puerta.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'afraid',
  },
  {
    id: 'greetings_040',
    emoji: '⏸️',
    question: '¿Cómo dices "wait"?',
    options: ['espera', 'espérate', 'un momento'],
    correctAnswer: 'espera',
    hint: 'Wait - command from "esperar" (to wait/hope), "espere" formal, "un momento" (one moment) polite',
    usageExample: '¡Espera! Olvidaste tu mochila.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'anxious',
  },

  // Special Occasions (10 questions)
  {
    id: 'greetings_041',
    emoji: '🎉',
    question: '¿Cómo felicitas a alguien?',
    options: ['felicidades', 'felicitaciones', 'enhorabuena'],
    correctAnswer: 'felicidades',
    hint: 'Congratulations - from "feliz" (happy), "felicitaciones" also used, for any celebration or achievement',
    usageExample: '¡Felicidades por tu nuevo trabajo!',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'greetings_042',
    emoji: '🎂',
    question: '¿Cómo dices "happy birthday"?',
    options: ['feliz cumpleaños', 'feliz cumple', 'que cumplas muchos más'],
    correctAnswer: 'feliz cumpleaños',
    hint: 'Happy birthday - "cumpleaños" from "cumplir años" (to complete years), song: "cumpleaños feliz"',
    usageExample: '¡Feliz cumpleaños! Que tengas un día maravilloso.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'greetings_043',
    emoji: '🎄',
    question: '¿Cómo dices "merry Christmas"?',
    options: ['feliz navidad', 'felices navidades', 'feliz pascua'],
    correctAnswer: 'feliz navidad',
    hint: 'Merry Christmas - "navidad" from Latin "nativitas" (birth), December 25, major holiday',
    usageExample: '¡Feliz Navidad y próspero Año Nuevo!',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'greetings_044',
    emoji: '🎊',
    question: '¿Cómo dices "happy new year"?',
    options: ['feliz año nuevo', 'próspero año nuevo', 'felices fiestas'],
    correctAnswer: 'feliz año nuevo',
    hint: 'Happy new year - celebrate midnight January 1, eat 12 grapes tradition in Spain',
    usageExample: '¡Feliz año nuevo! Que este año traiga mucha felicidad.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'greetings_045',
    emoji: '🛫',
    question: '¿Cómo deseas "have a good trip"?',
    options: ['buen viaje', 'que tengas buen viaje', 'feliz viaje'],
    correctAnswer: 'buen viaje',
    hint: 'Have a good trip - "viaje" (trip/journey), "que tengas buen viaje" longer form',
    usageExample: '¡Buen viaje! Espero que lo pases muy bien.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'greetings_046',
    emoji: '🍽️',
    question: '¿Qué dices antes de comer?',
    options: ['buen provecho', 'que aproveche', 'provecho'],
    correctAnswer: 'buen provecho',
    hint: 'Enjoy your meal - literally "good benefit", French "bon appétit" equivalent, very important culturally',
    usageExample: 'Buen provecho, que disfrutes la comida.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'greetings_047',
    emoji: '🌟',
    question: '¿Cómo deseas "good luck"?',
    options: ['buena suerte', 'mucha suerte', 'que tengas suerte'],
    correctAnswer: 'buena suerte',
    hint: 'Good luck - same as greetings_20, "mucha suerte" stronger, "¡suerte!" casual',
    usageExample: '¡Buena suerte en la entrevista!',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'greetings_048',
    emoji: '🏥',
    question: '¿Cómo dices "get well soon"?',
    options: ['que te mejores', 'que se mejore', 'mejórate pronto'],
    correctAnswer: 'que te mejores',
    hint: 'Get well soon - from "mejorar" (to improve/get better), "que se mejore" formal usted',
    usageExample: 'Que te mejores pronto, cuídate mucho.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'hurt',
  },
  {
    id: 'greetings_049',
    emoji: '💑',
    question: '¿Cómo dices "I love you"?',
    options: ['te quiero', 'te amo', 'te adoro'],
    correctAnswer: 'te quiero',
    hint: 'I love you - "te quiero" common for family/friends/partners, "te amo" deeper romantic love',
    usageExample: 'Te quiero mucho, mamá. Gracias por todo.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'greetings_050',
    emoji: '😘',
    question: '¿Cómo dices "I miss you"?',
    options: ['te extraño', 'te echo de menos', 'me haces falta'],
    correctAnswer: 'te extraño',
    hint: 'I miss you - "extrañar" in Latin America, Spain uses "te echo de menos" (I throw you from less)',
    usageExample: 'Te extraño mucho, ¿cuándo volverás?',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'sad',
  },

  // Additional Conversation Phrases (4 questions)
  {
    id: 'greetings_051',
    emoji: '❓',
    question: '¿Cómo dices "I have a question for you"?',
    options: ['tengo una pregunta para ti', 'tengo una pregunta por ti', 'tengo pregunta para ti'],
    correctAnswer: 'tengo una pregunta para ti',
    hint: 'I have a question for you - "tengo" (I have), "pregunta" (question), "para ti" (for you informal)',
    usageExample: 'Disculpa, tengo una pregunta para ti sobre la tarea.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'greetings_052',
    emoji: '🛑',
    question: '¿Cómo dices "that is enough"?',
    options: ['eso es suficiente', 'es suficiente', 'basta'],
    correctAnswer: 'eso es suficiente',
    hint: 'That is enough - "eso" (that), "suficiente" (enough/sufficient), "basta" is stronger "enough!"',
    usageExample: 'Eso es suficiente, gracias. No necesito más.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'greetings_053',
    emoji: '🏨',
    question: '¿Cómo dices "we are staying here for two weeks"?',
    options: ['nos quedamos aquí por dos semanas', 'estamos quedando aquí por dos semanas', 'quedamos aquí dos semanas'],
    correctAnswer: 'nos quedamos aquí por dos semanas',
    hint: 'We are staying here for two weeks - "quedarse" (to stay), "por dos semanas" (for two weeks), useful for hotels',
    usageExample: 'Nos quedamos aquí por dos semanas, hasta el 15 de julio.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'greetings_054',
    emoji: '💡',
    question: '¿Cómo dices "the answer is..." (___)?',
    options: ['la respuesta es', 'la respuesta está', 'el respuesto es'],
    correctAnswer: 'la respuesta es',
    hint: 'The answer is - "respuesta" is feminine (la), use "ser" (es) not "estar", "el" would be wrong gender',
    usageExample: 'La respuesta es muy simple: cuarenta y dos.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  // Extended Greetings & Conversational Phrases (46 additional questions)
  {
    id: 'greetings_055',
    emoji: '🎉',
    question: '¿Cómo dices "welcome"?',
    options: ['bienvenido', 'bien venido', 'bienvenida'],
    correctAnswer: 'bienvenido',
    hint: 'Welcome - "bien" (well) + "venido" (come), masculine form, use "bienvenida" for females',
    usageExample: '¡Bienvenido a nuestra casa! Ponte cómodo.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'greetings_056',
    emoji: '👍',
    question: '¿Cómo dices "you\'re welcome" (de nada)?',
    options: ['de nada', 'por nada', 'sin nada'],
    correctAnswer: 'de nada',
    hint: 'You\'re welcome - literally "of nothing", standard polite response to "gracias"',
    usageExample: '— Muchas gracias. — De nada, fue un placer ayudarte.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_057',
    emoji: '🙏',
    question: '¿Cómo dices "blessing" o "bless you" (después de estornudar)?',
    options: ['salud', 'bendición', 'jesús'],
    correctAnswer: 'salud',
    hint: 'Bless you - literally "health", said after someone sneezes, more common than "jesús" in modern usage',
    usageExample: '— ¡Achú! — ¡Salud! ¿Estás bien?',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'greetings_058',
    emoji: '🤔',
    question: '¿Cómo preguntas "what\'s new?"?',
    options: ['¿qué hay de nuevo?', '¿qué es nuevo?', '¿qué tiene nuevo?'],
    correctAnswer: '¿qué hay de nuevo?',
    hint: 'What\'s new? - "¿qué hay?" (what is there?) + "de nuevo" (of new), casual conversation starter',
    usageExample: '¡Hola! ¿Qué hay de nuevo en tu vida?',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'greetings_059',
    emoji: '😊',
    question: '¿Cómo dices "it was nice seeing you"?',
    options: ['fue un placer verte', 'fue placer verte', 'fue agradable verte'],
    correctAnswer: 'fue un placer verte',
    hint: 'It was nice seeing you - "fue" (it was), "un placer" (a pleasure), "verte" (to see you)',
    usageExample: 'Fue un placer verte de nuevo después de tanto tiempo.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'greetings_060',
    emoji: '🚪',
    question: '¿Cómo dices "come in"?',
    options: ['pasa', 'entra', 'adelante'],
    correctAnswer: 'pasa',
    hint: 'Come in - "pasa" (pass/come in) informal command, "adelante" also common meaning "go ahead"',
    usageExample: 'Pasa, pasa! La puerta está abierta.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'greetings_061',
    emoji: '💺',
    question: '¿Cómo invitas a alguien a sentarse?',
    options: ['siéntate', 'sienta', 'sentarse'],
    correctAnswer: 'siéntate',
    hint: 'Sit down - informal command from "sentarse", use "siéntese" for formal',
    usageExample: 'Siéntate aquí, voy a traer café.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'greetings_062',
    emoji: '😴',
    question: '¿Cómo dices "I\'m sleepy"?',
    options: ['tengo sueño', 'estoy sueño', 'soy sueño'],
    correctAnswer: 'tengo sueño',
    hint: 'I\'m sleepy - "tener sueño" (to have sleep), use "tener" not "estar" or "ser"',
    usageExample: 'Tengo mucho sueño, me voy a dormir temprano.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'greetings_063',
    emoji: '🥱',
    question: '¿Cómo dices "I\'m tired"?',
    options: ['estoy cansado', 'soy cansado', 'tengo cansado'],
    correctAnswer: 'estoy cansado',
    hint: 'I\'m tired - "estar cansado" (temporary state), use "estar" not "ser", add "a" for female',
    usageExample: 'Estoy cansado después de trabajar todo el día.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'greetings_064',
    emoji: '🍽️',
    question: '¿Cómo dices "I\'m hungry"?',
    options: ['tengo hambre', 'estoy hambre', 'soy hambre'],
    correctAnswer: 'tengo hambre',
    hint: 'I\'m hungry - "tener hambre" (to have hunger), use "tener" not "estar" or "ser"',
    usageExample: 'Tengo hambre, ¿vamos a comer algo?',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'greetings_065',
    emoji: '💧',
    question: '¿Cómo dices "I\'m thirsty"?',
    options: ['tengo sed', 'estoy sed', 'soy sed'],
    correctAnswer: 'tengo sed',
    hint: 'I\'m thirsty - "tener sed" (to have thirst), use "tener" not "estar" or "ser"',
    usageExample: 'Tengo sed, ¿me das un vaso de agua?',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'greetings_066',
    emoji: '🥶',
    question: '¿Cómo dices "I\'m cold"?',
    options: ['tengo frío', 'estoy frío', 'soy frío'],
    correctAnswer: 'tengo frío',
    hint: 'I\'m cold - "tener frío" (to have cold/coldness), use "tener" not "estar", "estar frío" means object is cold',
    usageExample: 'Tengo frío, ¿puedes cerrar la ventana?',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'greetings_067',
    emoji: '🥵',
    question: '¿Cómo dices "I\'m hot" (feeling heat)?',
    options: ['tengo calor', 'estoy calor', 'soy calor'],
    correctAnswer: 'tengo calor',
    hint: 'I\'m hot - "tener calor" (to have heat), use "tener" not "estar", "estar caliente" has sexual connotation',
    usageExample: 'Tengo mucho calor, voy a abrir la ventana.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'greetings_068',
    emoji: '😰',
    question: '¿Cómo dices "I\'m afraid"?',
    options: ['tengo miedo', 'estoy miedo', 'soy miedo'],
    correctAnswer: 'tengo miedo',
    hint: 'I\'m afraid - "tener miedo" (to have fear), use "tener" not "estar" or "ser"',
    usageExample: 'Tengo miedo de las arañas grandes.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'afraid',
  },
  {
    id: 'greetings_069',
    emoji: '😡',
    question: '¿Cómo dices "I\'m angry"?',
    options: ['estoy enojado', 'soy enojado', 'tengo enojo'],
    correctAnswer: 'estoy enojado',
    hint: 'I\'m angry - "estar enojado" (temporary state), use "estar" not "ser", add "a" for female',
    usageExample: 'Estoy enojado porque perdí mis llaves.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'angry',
  },
  {
    id: 'greetings_070',
    emoji: '😔',
    question: '¿Cómo dices "I\'m sad"?',
    options: ['estoy triste', 'soy triste', 'tengo tristeza'],
    correctAnswer: 'estoy triste',
    hint: 'I\'m sad - "estar triste" (temporary emotion), use "estar" not "ser", same form for both genders',
    usageExample: 'Estoy triste porque mi perro está enfermo.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'sad',
  },
  {
    id: 'greetings_071',
    emoji: '😁',
    question: '¿Cómo dices "I\'m happy"?',
    options: ['estoy feliz', 'soy feliz', 'tengo felicidad'],
    correctAnswer: 'estoy feliz',
    hint: 'I\'m happy - "estar feliz" (temporary emotion), use "estar" not "ser", same form for both genders',
    usageExample: 'Estoy feliz porque mañana es mi cumpleaños.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'greetings_072',
    emoji: '😲',
    question: '¿Cómo dices "I\'m surprised"?',
    options: ['estoy sorprendido', 'soy sorprendido', 'tengo sorpresa'],
    correctAnswer: 'estoy sorprendido',
    hint: 'I\'m surprised - "estar sorprendido" (temporary state), use "estar" not "ser", add "a" for female',
    usageExample: 'Estoy sorprendido de verte aquí.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'surprised',
  },
  {
    id: 'greetings_073',
    emoji: '😖',
    question: '¿Cómo dices "I\'m worried"?',
    options: ['estoy preocupado', 'soy preocupado', 'tengo preocupación'],
    correctAnswer: 'estoy preocupado',
    hint: 'I\'m worried - "estar preocupado" (temporary state), use "estar" not "ser", add "a" for female',
    usageExample: 'Estoy preocupado por el examen de mañana.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'greetings_074',
    emoji: '😕',
    question: '¿Cómo dices "I\'m confused"?',
    options: ['estoy confundido', 'soy confundido', 'tengo confusión'],
    correctAnswer: 'estoy confundido',
    hint: 'I\'m confused - "estar confundido" (temporary state), use "estar" not "ser", add "a" for female',
    usageExample: 'Estoy confundido, no entiendo las instrucciones.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'greetings_075',
    emoji: '🤢',
    question: '¿Cómo dices "I feel sick"?',
    options: ['me siento mal', 'estoy enfermo', 'tengo enfermedad'],
    correctAnswer: 'me siento mal',
    hint: 'I feel sick - "sentirse mal" (to feel bad), "estar enfermo" also works but means specifically ill',
    usageExample: 'Me siento mal, creo que tengo fiebre.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'hurt',
  },
  {
    id: 'greetings_076',
    emoji: '😌',
    question: '¿Cómo dices "I feel better"?',
    options: ['me siento mejor', 'estoy mejor', 'soy mejor'],
    correctAnswer: 'me siento mejor',
    hint: 'I feel better - "sentirse mejor" (to feel better), "estar mejor" also works',
    usageExample: 'Gracias por preguntar, ya me siento mejor.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'greetings_077',
    emoji: '💪',
    question: '¿Cómo dices "I feel strong"?',
    options: ['me siento fuerte', 'estoy fuerte', 'soy fuerte'],
    correctAnswer: 'me siento fuerte',
    hint: 'I feel strong - "sentirse fuerte" (to feel strong), temporary feeling, "ser fuerte" is permanent characteristic',
    usageExample: 'Me siento fuerte después de entrenar.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'greetings_078',
    emoji: '🎊',
    question: '¿Cómo dices "I\'m excited"?',
    options: ['estoy emocionado', 'soy emocionado', 'tengo emoción'],
    correctAnswer: 'estoy emocionado',
    hint: 'I\'m excited - "estar emocionado" (temporary emotion), use "estar" not "ser", add "a" for female',
    usageExample: 'Estoy emocionado por el viaje a la playa.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'greetings_079',
    emoji: '🙂',
    question: '¿Cómo preguntas "how are you feeling?"?',
    options: ['¿cómo te sientes?', '¿cómo estás sintiendo?', '¿qué sientes?'],
    correctAnswer: '¿cómo te sientes?',
    hint: 'How are you feeling? - "sentirse" (to feel oneself), use reflexive verb',
    usageExample: '¿Cómo te sientes hoy? ¿Ya estás mejor?',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'greetings_080',
    emoji: '🤝',
    question: '¿Cómo dices "nice to meet you" (formal)?',
    options: ['mucho gusto', 'muy gusto', 'mucha gusto'],
    correctAnswer: 'mucho gusto',
    hint: 'Nice to meet you - "mucho gusto" (much pleasure), "mucho" is adverb so doesn\'t change gender',
    usageExample: 'Mucho gusto, señor Rodríguez. Es un honor conocerlo.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_081',
    emoji: '👋',
    question: '¿Cómo respondes a "mucho gusto"?',
    options: ['igualmente', 'igual', 'lo mismo'],
    correctAnswer: 'igualmente',
    hint: 'Likewise - "igualmente" (equally/likewise), standard polite response to "mucho gusto"',
    usageExample: '— Mucho gusto. — Igualmente, el placer es mío.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_082',
    emoji: '🎂',
    question: '¿Cómo felicitas a alguien en su cumpleaños?',
    options: ['feliz cumpleaños', 'felicidades', 'cumpleaños feliz'],
    correctAnswer: 'feliz cumpleaños',
    hint: 'Happy birthday - "feliz cumpleaños" (happy birthday), "felicidades" also used',
    usageExample: '¡Feliz cumpleaños! Que todos tus deseos se hagan realidad.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'greetings_083',
    emoji: '🎄',
    question: '¿Cómo dices "Merry Christmas"?',
    options: ['feliz Navidad', 'felices Navidades', 'Navidad feliz'],
    correctAnswer: 'feliz Navidad',
    hint: 'Merry Christmas - "feliz Navidad" (happy Christmas), "felices Navidades" plural also used',
    usageExample: '¡Feliz Navidad y próspero Año Nuevo!',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'greetings_084',
    emoji: '🎆',
    question: '¿Cómo dices "Happy New Year"?',
    options: ['feliz Año Nuevo', 'feliz año nuevo', 'Año Nuevo feliz'],
    correctAnswer: 'feliz Año Nuevo',
    hint: 'Happy New Year - "feliz Año Nuevo", capitalize both "Año" and "Nuevo"',
    usageExample: '¡Feliz Año Nuevo! Que este año traiga salud y alegría.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'greetings_085',
    emoji: '🍀',
    question: '¿Cómo deseas buena suerte?',
    options: ['buena suerte', 'suerte buena', 'buenas suertes'],
    correctAnswer: 'buena suerte',
    hint: 'Good luck - "buena suerte" (good luck), "suerte" is feminine singular',
    usageExample: '¡Buena suerte en tu entrevista de trabajo!',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'greetings_086',
    emoji: '🍽️',
    question: '¿Qué dices antes de comer (enjoy your meal)?',
    options: ['buen provecho', 'bueno provecho', 'buen apetito'],
    correctAnswer: 'buen provecho',
    hint: 'Enjoy your meal - "buen provecho" (good benefit/profit), said before or during meal',
    usageExample: 'Buen provecho, que disfrutes la comida.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'greetings_087',
    emoji: '🤧',
    question: '¿Cómo dices "get well soon"?',
    options: ['que te mejores', 'mejórate pronto', 'que mejores'],
    correctAnswer: 'que te mejores',
    hint: 'Get well soon - "que te mejores" (that you get better), subjunctive form expressing wish',
    usageExample: 'Que te mejores pronto, descansa mucho.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'greetings_088',
    emoji: '😴',
    question: '¿Cómo deseas dulces sueños?',
    options: ['dulces sueños', 'sueños dulces', 'que sueñes dulce'],
    correctAnswer: 'dulces sueños',
    hint: 'Sweet dreams - "dulces sueños" (sweet dreams), "sueño" is masculine plural',
    usageExample: '¡Buenas noches! Que descanses bien.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'greetings_089',
    emoji: '✈️',
    question: '¿Cómo deseas buen viaje?',
    options: ['buen viaje', 'viaje bueno', 'bueno viaje'],
    correctAnswer: 'buen viaje',
    hint: 'Have a good trip - "buen viaje" (good trip), "viaje" is masculine',
    usageExample: '¡Buen viaje! Que tengas un vuelo seguro.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'greetings_090',
    emoji: '🏁',
    question: '¿Cómo dices "see you soon"?',
    options: ['hasta pronto', 'hasta luego', 'nos vemos pronto'],
    correctAnswer: 'hasta pronto',
    hint: 'See you soon - "hasta pronto" (until soon), implies meeting again very soon',
    usageExample: 'Hasta pronto, te veo mañana en la mañana.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'greetings_091',
    emoji: '📅',
    question: '¿Cómo dices "see you tomorrow"?',
    options: ['hasta mañana', 'vemos mañana', 'nos vemos mañana'],
    correctAnswer: 'hasta mañana',
    hint: 'See you tomorrow - "hasta mañana" (until tomorrow), common evening farewell',
    usageExample: 'Hasta mañana, que descanses bien.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'greetings_092',
    emoji: '👀',
    question: '¿Cómo dices "see you later"?',
    options: ['nos vemos', 'vemos después', 'te veo luego'],
    correctAnswer: 'nos vemos',
    hint: 'See you later - "nos vemos" (we see each other), very casual common farewell',
    usageExample: 'Nos vemos después, tengo que irme.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'greetings_093',
    emoji: '🙋',
    question: '¿Cómo llamas la atención de alguien educadamente?',
    options: ['disculpa', 'disculpe', 'perdón'],
    correctAnswer: 'disculpa',
    hint: 'Excuse me - "disculpa" (informal), "disculpe" (formal), used to get attention politely',
    usageExample: 'Disculpa, ¿me puedes decir la hora?',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'greetings_094',
    emoji: '🤷',
    question: '¿Cómo dices "I don\'t know"?',
    options: ['no sé', 'no conozco', 'no sabo'],
    correctAnswer: 'no sé',
    hint: 'I don\'t know - "no sé" from "saber" (to know facts), not "conocer" (to know people/places)',
    usageExample: 'No sé dónde está mi teléfono.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'confused',
  },
  {
    id: 'greetings_095',
    emoji: '🤔',
    question: '¿Cómo preguntas "what do you mean?"?',
    options: ['¿qué quieres decir?', '¿qué significa?', '¿qué dices?'],
    correctAnswer: '¿qué quieres decir?',
    hint: 'What do you mean? - "¿qué quieres decir?" (what do you want to say?), asking for clarification',
    usageExample: '¿Qué quieres decir con eso? No entiendo.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'greetings_096',
    emoji: '👂',
    question: '¿Cómo pides que repitan algo?',
    options: ['¿cómo?', '¿qué?', '¿perdón?'],
    correctAnswer: '¿cómo?',
    hint: 'What? (asking to repeat) - "¿cómo?" (how?) is more polite than "¿qué?" in this context',
    usageExample: '¿Cómo? No te escuché bien, ¿puedes repetir?',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'confused',
  },
  {
    id: 'greetings_097',
    emoji: '🗣️',
    question: '¿Cómo pides que hablen más despacio?',
    options: ['habla más despacio', 'hablas más lento', 'hable despacio'],
    correctAnswer: 'habla más despacio',
    hint: 'Speak more slowly - informal command "habla" + "más despacio" (more slowly)',
    usageExample: 'Por favor, habla más despacio. Estoy aprendiendo español.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'greetings_098',
    emoji: '📝',
    question: '¿Cómo preguntas "can you write it down?"?',
    options: ['¿puedes escribirlo?', '¿puede escribirlo?', '¿escribes esto?'],
    correctAnswer: '¿puedes escribirlo?',
    hint: 'Can you write it down? - informal "puedes" + infinitive "escribir" + object pronoun "lo"',
    usageExample: '¿Puedes escribirlo? No entiendo cuando hablas.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'greetings_099',
    emoji: '🙌',
    question: '¿Cómo dices "that\'s great!"?',
    options: ['¡qué bien!', '¡es genial!', '¡muy bueno!'],
    correctAnswer: '¡qué bien!',
    hint: 'That\'s great! - "¡qué bien!" (how good!), exclamation showing enthusiasm',
    usageExample: '— Conseguí el trabajo. — ¡Qué bien! Felicidades.',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'greetings_100',
    emoji: '😤',
    question: '¿Cómo dices "I\'m fed up" o "I\'m sick of it"?',
    options: ['estoy harto', 'soy harto', 'tengo hartazgo'],
    correctAnswer: 'estoy harto',
    hint: 'I\'m fed up - "estar harto" (to be fed up), temporary state, add "a" for female',
    usageExample: 'Estoy harto de esperar, me voy.',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
    emotion: 'disgusted',
  },

];
