/**
 * GREETINGS & CONVERSATIONS Category Questions
 * Category: greetings
 */

export const greetingsQuestions = [
// Basic Greetings (10 questions)
  {
    id: 'greetings_001',
    emoji: '👋',
    question: '¿Cómo saludas a alguien por la mañana?',
    options: ['buenos días', 'buen día', 'buen día tengas'],
    correctAnswer: 'buenos días',
    hint: 'Good morning - literally "good days" (plural), from Latin "bonus dies", use until 2pm',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_002',
    emoji: '🌅',
    question: '¿Qué dices por la tarde?',
    options: ['buenas tardes', 'buena tarde', 'tardes buenas'],
    correctAnswer: 'buenas tardes',
    hint: 'Good afternoon - "tardes" feminine plural, use 2pm-sunset, timing varies by region',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_003',
    emoji: '🌙',
    question: '¿Qué dices cuando es de noche?',
    options: ['buenas noches', 'buena noche', 'noches buenas'],
    correctAnswer: 'buenas noches',
    hint: 'Good night - works as greeting after sunset AND farewell before sleep',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_004',
    emoji: '👋',
    question: '¿Cómo dices "hello" informalmente?',
    options: ['hola', 'ola', 'holaa'],
    correctAnswer: 'hola',
    hint: 'Hello - universal informal greeting anytime, no gender/formality changes, from Arabic "wa-llāh"',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_005',
    emoji: '👋',
    question: '¿Cómo dices "goodbye"?',
    options: ['adiós', 'a dios', 'adios'],
    correctAnswer: 'adiós',
    hint: 'Goodbye - literally "to God" (a + Dios), permanent farewell, "chau" more casual',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_006',
    emoji: '🌅',
    question: '¿Qué es otra forma de decir "adiós"?',
    options: ['hasta luego', 'hasta la vista', 'hasta pronto'],
    correctAnswer: 'hasta luego',
    hint: 'See you later - "hasta" (until) + "luego" (later), implies you\'ll meet again soon',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_007',
    emoji: '💤',
    question: '¿Qué dices antes de dormir?',
    options: ['buenas noches', 'buena noche', 'dulces sueños'],
    correctAnswer: 'buenas noches',
    hint: 'Good night - before sleep, same phrase as evening greeting but context differs',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_008',
    emoji: '🌄',
    question: '¿Qué significa "hasta mañana"?',
    options: ['see you tomorrow', 'until tomorrow', 'see you later'],
    correctAnswer: 'see you tomorrow',
    hint: 'See you tomorrow - "hasta" (until) + "mañana" (tomorrow/morning), confirms next-day meeting',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_009',
    emoji: '👋',
    question: '¿Cómo preguntas "how are you?"',
    options: ['¿cómo estás?', '¿cómo está?', '¿cómo estáis?'],
    correctAnswer: '¿cómo estás?',
    hint: 'How are you? - informal tú form, "¿cómo está?" for usted formal, from "estar" (to be)',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_010',
    emoji: '👍',
    question: '¿Cómo respondes "I am fine"?',
    options: ['estoy bien', 'muy bien', 'todo bien'],
    correctAnswer: 'estoy bien',
    hint: 'I\'m fine - "estoy" (I am) + "bien" (well/good), "muy bien" for very well, "regular" for so-so',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },

  // Politeness & Courtesy (10 questions)
  {
    id: 'greetings_011',
    emoji: '🙏',
    question: '¿Cómo dices "please"?',
    options: ['por favor', 'de favor', 'con favor'],
    correctAnswer: 'por favor',
    hint: 'Please - literally "for favor", from Latin "pro favore", essential politeness in Spanish culture',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_012',
    emoji: '😊',
    question: '¿Cómo dices "thank you"?',
    options: ['gracias', 'muchas gracias', 'mil gracias'],
    correctAnswer: 'gracias',
    hint: 'Thank you - from Latin "gratias" (thanks), "muchas gracias" for many thanks',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_013',
    emoji: '👍',
    question: '¿Cómo respondes a "gracias"?',
    options: ['de nada', 'no hay de qué', 'con gusto'],
    correctAnswer: 'de nada',
    hint: 'You\'re welcome - literally "of nothing", also "no hay de qué" (there\'s nothing to thank)',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_014',
    emoji: '🙇',
    question: '¿Cómo dices "excuse me"?',
    options: ['perdón', 'disculpa', 'perdone'],
    correctAnswer: 'perdón',
    hint: 'Excuse me/Sorry - from "perdonar" (to forgive), "disculpe" more formal, "con permiso" to pass by',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_015',
    emoji: '😔',
    question: '¿Cómo dices "I am sorry"?',
    options: ['lo siento', 'lo lamento', 'siento mucho'],
    correctAnswer: 'lo siento',
    hint: 'I\'m sorry - literally "I feel it", expresses empathy/regret, deeper than "perdón"',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_016',
    emoji: '🤝',
    question: '¿Cómo dices "nice to meet you"?',
    options: ['mucho gusto', 'encantado', 'un placer'],
    correctAnswer: 'mucho gusto',
    hint: 'Nice to meet you - literally "much pleasure", response is "igualmente" (likewise) or "el gusto es mío"',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_017',
    emoji: '🙏',
    question: '¿Qué es otra forma de decir "gracias"?',
    options: ['muchas gracias', 'muchísimas gracias', 'mil gracias'],
    correctAnswer: 'muchas gracias',
    hint: 'Thank you very much - "muchas" (many, feminine plural), "muchísimas gracias" even stronger',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_018',
    emoji: '👋',
    question: '¿Cómo respondes a "mucho gusto"?',
    options: ['igualmente', 'el gusto es mío', 'encantado'],
    correctAnswer: 'igualmente',
    hint: 'Likewise - from "igual" (equal), also "el gusto es mío" (pleasure is mine)',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_019',
    emoji: '🙏',
    question: '¿Cómo pides permiso para pasar?',
    options: ['con permiso', 'permiso', 'disculpe'],
    correctAnswer: 'con permiso',
    hint: 'With permission - polite phrase to pass by someone or leave room, shows respect',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_020',
    emoji: '😇',
    question: '¿Cómo deseas buena suerte?',
    options: ['buena suerte', 'mucha suerte', 'que tengas suerte'],
    correctAnswer: 'buena suerte',
    hint: 'Good luck - "suerte" (luck) from Latin "sors" (fate/lot), "¡que tengas suerte!" also common',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },

  // Common Questions (10 questions)
  {
    id: 'greetings_021',
    emoji: '❓',
    question: '¿Cómo preguntas "what is your name?"',
    options: ['¿cómo te llamas?', '¿cómo se llama?', '¿cuál es tu nombre?'],
    correctAnswer: '¿cómo te llamas?',
    hint: 'What\'s your name? - literally "how do you call yourself?", "¿cómo se llama?" formal usted',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_022',
    emoji: '🗣️',
    question: '¿Cómo dices "my name is..."?',
    options: ['me llamo', 'mi nombre es', 'yo soy'],
    correctAnswer: 'me llamo',
    hint: 'My name is... - literally "I call myself", from "llamar" (to call), "mi nombre es" also used',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_023',
    emoji: '🌍',
    question: '¿Cómo preguntas "where are you from?"',
    options: ['¿de dónde eres?', '¿de dónde es?', '¿de dónde vienes?'],
    correctAnswer: '¿de dónde eres?',
    hint: 'Where are you from? - "de dónde" (from where), "¿de dónde es?" formal usted form',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_024',
    emoji: '🏠',
    question: '¿Cómo respondes "I am from..."?',
    options: ['soy de', 'vengo de', 'provengo de'],
    correctAnswer: 'soy de',
    hint: 'I\'m from... - "soy" (I am) + "de" (from), uses "ser" for origin/nationality',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_025',
    emoji: '🗨️',
    question: '¿Cómo preguntas "what\'s up?"',
    options: ['¿qué tal?', '¿qué pasa?', '¿qué onda?'],
    correctAnswer: '¿qué tal?',
    hint: 'What\'s up? - casual greeting, literally "what such?", Spain also uses "¿qué pasa?"',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_026',
    emoji: '🎂',
    question: '¿Cuántos años tienes? means what?',
    options: ['how old are you?', 'how many years do you have?', 'what is your age?'],
    correctAnswer: 'how old are you?',
    hint: 'How old are you? - literally "how many years do you have?", Spanish uses "tener" (have) for age',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_027',
    emoji: '🔢',
    question: '¿Cómo respondes "I am 25 years old"?',
    options: ['tengo 25 años', 'tengo veinticinco años', 'cumplo 25 años'],
    correctAnswer: 'tengo 25 años',
    hint: 'I\'m 25 years old - uses "tengo" (I have), not "soy", "años" always plural after 1',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_028',
    emoji: '🗣️',
    question: '¿Cómo preguntas "do you speak Spanish?"',
    options: ['¿hablas español?', '¿habla español?', '¿sabes español?'],
    correctAnswer: '¿hablas español?',
    hint: 'Do you speak Spanish? - "hablas" from "hablar" (to speak), "¿habla español?" formal usted',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_029',
    emoji: '🇬🇧',
    question: '¿Cómo preguntas "do you speak English?"',
    options: ['¿hablas inglés?', '¿habla inglés?', '¿sabes inglés?'],
    correctAnswer: '¿hablas inglés?',
    hint: 'Do you speak English? - "inglés" (English language), essential tourist question',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_030',
    emoji: '❌',
    question: '¿Cómo dices "I don\'t understand"?',
    options: ['no entiendo', 'no comprendo', 'no capto'],
    correctAnswer: 'no entiendo',
    hint: 'I don\'t understand - "entiendo" from "entender", "no comprendo" also used, essential phrase',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },

  // Conversation Basics (10 questions)
  {
    id: 'greetings_031',
    emoji: '✅',
    question: '¿Cómo dices "yes"?',
    options: ['sí', 'síí', 'siii'],
    correctAnswer: 'sí',
    hint: 'Yes - affirmative, has accent (sí) to distinguish from "si" (if), from Latin "sic"',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_032',
    emoji: '❌',
    question: '¿Cómo dices "no"?',
    options: ['no', 'noo', 'nooo'],
    correctAnswer: 'no',
    hint: 'No - negative answer, same as English, from Latin "non", double negatives common in Spanish',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_033',
    emoji: '🤷',
    question: '¿Cómo dices "maybe"?',
    options: ['tal vez', 'quizás', 'a lo mejor'],
    correctAnswer: 'tal vez',
    hint: 'Maybe - literally "such time", "quizás" and "a lo mejor" also used for uncertainty',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_034',
    emoji: '👍',
    question: '¿Cómo dices "okay" o "fine"?',
    options: ['vale', 'está bien', 'ok'],
    correctAnswer: 'vale',
    hint: 'Okay/Fine - very common in Spain, Latin America uses "está bien" or "OK", from "valer" (to be worth)',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_035',
    emoji: '👌',
    question: '¿Cómo dices "of course"?',
    options: ['claro', 'por supuesto', 'desde luego'],
    correctAnswer: 'claro',
    hint: 'Of course - literally "clear", "por supuesto" more formal, shows strong agreement',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_036',
    emoji: '⏰',
    question: '¿Cómo preguntas "what time is it?"',
    options: ['¿qué hora es?', '¿qué horas son?', '¿cuál es la hora?'],
    correctAnswer: '¿qué hora es?',
    hint: 'What time is it? - "hora" (hour) singular, answer uses "es la" (singular) or "son las" (plural)',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_037',
    emoji: '📅',
    question: '¿Cómo preguntas "what day is today?"',
    options: ['¿qué día es hoy?', '¿qué día es?', '¿cuál día es hoy?'],
    correctAnswer: '¿qué día es hoy?',
    hint: 'What day is today? - "día" (day) + "hoy" (today), answer: "hoy es lunes" (today is Monday)',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_038',
    emoji: '🔍',
    question: '¿Cómo dices "I don\'t know"?',
    options: ['no sé', 'no lo sé', 'ni idea'],
    correctAnswer: 'no sé',
    hint: 'I don\'t know - "sé" from "saber" (to know facts), different from "conocer" (to know people/places)',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_039',
    emoji: '🙋',
    question: '¿Cómo dices "help" o "help me"?',
    options: ['ayuda', 'ayúdame', 'socorro'],
    correctAnswer: 'ayuda',
    hint: 'Help - command form of "ayudar", "ayúdame" (help me), "¡socorro!" for emergencies',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_040',
    emoji: '⏸️',
    question: '¿Cómo dices "wait"?',
    options: ['espera', 'espérate', 'un momento'],
    correctAnswer: 'espera',
    hint: 'Wait - command from "esperar" (to wait/hope), "espere" formal, "un momento" (one moment) polite',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },

  // Special Occasions (10 questions)
  {
    id: 'greetings_041',
    emoji: '🎉',
    question: '¿Cómo felicitas a alguien?',
    options: ['felicidades', 'felicitaciones', 'enhorabuena'],
    correctAnswer: 'felicidades',
    hint: 'Congratulations - from "feliz" (happy), "felicitaciones" also used, for any celebration or achievement',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_042',
    emoji: '🎂',
    question: '¿Cómo dices "happy birthday"?',
    options: ['feliz cumpleaños', 'feliz cumple', 'que cumplas muchos más'],
    correctAnswer: 'feliz cumpleaños',
    hint: 'Happy birthday - "cumpleaños" from "cumplir años" (to complete years), song: "cumpleaños feliz"',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_043',
    emoji: '🎄',
    question: '¿Cómo dices "merry Christmas"?',
    options: ['feliz navidad', 'felices navidades', 'feliz pascua'],
    correctAnswer: 'feliz navidad',
    hint: 'Merry Christmas - "navidad" from Latin "nativitas" (birth), December 25, major holiday',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_044',
    emoji: '🎊',
    question: '¿Cómo dices "happy new year"?',
    options: ['feliz año nuevo', 'próspero año nuevo', 'felices fiestas'],
    correctAnswer: 'feliz año nuevo',
    hint: 'Happy new year - celebrate midnight January 1, eat 12 grapes tradition in Spain',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_045',
    emoji: '🛫',
    question: '¿Cómo deseas "have a good trip"?',
    options: ['buen viaje', 'que tengas buen viaje', 'feliz viaje'],
    correctAnswer: 'buen viaje',
    hint: 'Have a good trip - "viaje" (trip/journey), "que tengas buen viaje" longer form',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_046',
    emoji: '🍽️',
    question: '¿Qué dices antes de comer?',
    options: ['buen provecho', 'que aproveche', 'provecho'],
    correctAnswer: 'buen provecho',
    hint: 'Enjoy your meal - literally "good benefit", French "bon appétit" equivalent, very important culturally',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_047',
    emoji: '🌟',
    question: '¿Cómo deseas "good luck"?',
    options: ['buena suerte', 'mucha suerte', 'que tengas suerte'],
    correctAnswer: 'buena suerte',
    hint: 'Good luck - same as greetings_20, "mucha suerte" stronger, "¡suerte!" casual',
    points: 5,
    category: 'greetings',
    difficulty: 'easy',
  },
  {
    id: 'greetings_048',
    emoji: '🏥',
    question: '¿Cómo dices "get well soon"?',
    options: ['que te mejores', 'que se mejore', 'mejórate pronto'],
    correctAnswer: 'que te mejores',
    hint: 'Get well soon - from "mejorar" (to improve/get better), "que se mejore" formal usted',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_049',
    emoji: '💑',
    question: '¿Cómo dices "I love you"?',
    options: ['te quiero', 'te amo', 'te adoro'],
    correctAnswer: 'te quiero',
    hint: 'I love you - "te quiero" common for family/friends/partners, "te amo" deeper romantic love',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_050',
    emoji: '😘',
    question: '¿Cómo dices "I miss you"?',
    options: ['te extraño', 'te echo de menos', 'me haces falta'],
    correctAnswer: 'te extraño',
    hint: 'I miss you - "extrañar" in Latin America, Spain uses "te echo de menos" (I throw you from less)',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },

  // Additional Conversation Phrases (4 questions)
  {
    id: 'greetings_051',
    emoji: '❓',
    question: '¿Cómo dices "I have a question for you"?',
    options: ['tengo una pregunta para ti', 'tengo una pregunta por ti', 'tengo pregunta para ti'],
    correctAnswer: 'tengo una pregunta para ti',
    hint: 'I have a question for you - "tengo" (I have), "pregunta" (question), "para ti" (for you informal)',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_052',
    emoji: '🛑',
    question: '¿Cómo dices "that is enough"?',
    options: ['eso es suficiente', 'es suficiente', 'basta'],
    correctAnswer: 'eso es suficiente',
    hint: 'That is enough - "eso" (that), "suficiente" (enough/sufficient), "basta" is stronger "enough!"',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_053',
    emoji: '🏨',
    question: '¿Cómo dices "we are staying here for two weeks"?',
    options: ['nos quedamos aquí por dos semanas', 'estamos quedando aquí por dos semanas', 'quedamos aquí dos semanas'],
    correctAnswer: 'nos quedamos aquí por dos semanas',
    hint: 'We are staying here for two weeks - "quedarse" (to stay), "por dos semanas" (for two weeks), useful for hotels',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },
  {
    id: 'greetings_054',
    emoji: '💡',
    question: '¿Cómo dices "the answer is..." (___)?',
    options: ['la respuesta es', 'la respuesta está', 'el respuesto es'],
    correctAnswer: 'la respuesta es',
    hint: 'The answer is - "respuesta" is feminine (la), use "ser" (es) not "estar", "el" would be wrong gender',
    points: 10,
    category: 'greetings',
    difficulty: 'medium',
  },

  // NUMBERS, DATES & TIME CATEGORY - 60 questions
  // Basic Numbers 0-10 (10 questions)
  {
    id: 'numbers_1',
    emoji: '0️⃣',
    question: '¿Cómo se dice "zero"?',
    options: ['cero', 'nada', 'ninguno'],
    correctAnswer: 'cero',
    hint: 'Zero - from Arabic "sifr" (empty), like English "cipher", temperature 0°C is "cero grados"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_2',
    emoji: '1️⃣',
    question: '¿Cómo se dice "one"?',
    options: ['uno', 'un', 'una'],
    correctAnswer: 'uno',
    hint: 'One - becomes "un" before masculine nouns, "una" before feminine, from Latin "unus"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_3',
    emoji: '2️⃣',
    question: '¿Cómo se dice "two"?',
    options: ['dos', 'doce', 'veinte'],
    correctAnswer: 'dos',
    hint: 'Two - from Latin "duos", same root as "duo", "dual", "double", never changes form',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_4',
    emoji: '3️⃣',
    question: '¿Cómo se dice "three"?',
    options: ['tres', 'trece', 'treinta'],
    correctAnswer: 'tres',
    hint: 'Three - from Latin "tres", like "trio", "triple", "trinity", never changes form',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_5',
    emoji: '4️⃣',
    question: '¿Cómo se dice "four"?',
    options: ['cuatro', 'catorce', 'cuarenta'],
    correctAnswer: 'cuatro',
    hint: 'Four - from Latin "quattuor", think "quartet", "quadrant", never changes form',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_6',
    emoji: '5️⃣',
    question: '¿Cómo se dice "five"?',
    options: ['cinco', 'quince', 'cincuenta'],
    correctAnswer: 'cinco',
    hint: 'Five - from Latin "quinque", like "quintet", "quintuplets", never changes form',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_7',
    emoji: '6️⃣',
    question: '¿Cómo se dice "six"?',
    options: ['seis', 'dieciséis', 'sesenta'],
    correctAnswer: 'seis',
    hint: 'Six - from Latin "sex", like "sextet", "sextuple", never changes form',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_8',
    emoji: '7️⃣',
    question: '¿Cómo se dice "seven"?',
    options: ['siete', 'diecisiete', 'setenta'],
    correctAnswer: 'siete',
    hint: 'Seven - from Latin "septem", like "September" (7th month in Roman calendar), lucky number',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_9',
    emoji: '8️⃣',
    question: '¿Cómo se dice "eight"?',
    options: ['ocho', 'dieciocho', 'ochenta'],
    correctAnswer: 'ocho',
    hint: 'Eight - from Latin "octo", like "octopus" (8 legs), "October" (8th month in Roman calendar)',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_10',
    emoji: '9️⃣',
    question: '¿Cómo se dice "nine"?',
    options: ['nueve', 'diecinueve', 'noventa'],
    correctAnswer: 'nueve',
    hint: 'Nine - from Latin "novem", like "November" (9th month in Roman calendar), "novena" (9-day prayer)',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },

  // Numbers 10-20 (10 questions)
  {
    id: 'numbers_11',
    emoji: '🔟',
    question: '¿Cómo se dice "ten"?',
    options: ['diez', 'dieci', 'dies'],
    correctAnswer: 'diez',
    hint: 'Ten - from Latin "decem", like "decade", "decimal", "December" (10th Roman month)',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_12',
    emoji: '🔢',
    question: '¿Cómo se dice "eleven"?',
    options: ['once', 'uno', 'diez y uno'],
    correctAnswer: 'once',
    hint: 'Eleven - from Latin "undecim" (one + ten), starts teen pattern until 15',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_13',
    emoji: '🔢',
    question: '¿Cómo se dice "twelve"?',
    options: ['doce', 'dos', 'diez y dos'],
    correctAnswer: 'doce',
    hint: 'Twelve - from Latin "duodecim" (two + ten), "una docena" is a dozen',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_14',
    emoji: '🔢',
    question: '¿Cómo se dice "thirteen"?',
    options: ['trece', 'tres', 'diez y tres'],
    correctAnswer: 'trece',
    hint: 'Thirteen - from "tres" + "diez", unlucky number in some cultures',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_15',
    emoji: '🔢',
    question: '¿Cómo se dice "fourteen"?',
    options: ['catorce', 'cuatro', 'diez y cuatro'],
    correctAnswer: 'catorce',
    hint: 'Fourteen - from "cuatro" + "diez", last unique teen form',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_16',
    emoji: '🔢',
    question: '¿Cómo se dice "fifteen"?',
    options: ['quince', 'cinco', 'diez y cinco'],
    correctAnswer: 'quince',
    hint: 'Fifteen - from "cinco" + "diez", quinceañera celebrates girl\'s 15th birthday',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_17',
    emoji: '🔢',
    question: '¿Cómo se dice "sixteen"?',
    options: ['dieciséis', 'diez y seis', 'dieciseis'],
    correctAnswer: 'dieciséis',
    hint: 'Sixteen - "diez y seis" combined, pattern continues 16-19 with "dieci-"',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_18',
    emoji: '🔢',
    question: '¿Cómo se dice "seventeen"?',
    options: ['diecisiete', 'diez y siete', 'dieciseis'],
    correctAnswer: 'diecisiete',
    hint: 'Seventeen - literally "ten and seven", combined form of "diez y siete"',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_19',
    emoji: '🔢',
    question: '¿Cómo se dice "eighteen"?',
    options: ['dieciocho', 'diez y ocho', 'diecisiete'],
    correctAnswer: 'dieciocho',
    hint: 'Eighteen - adult age in most countries, "diez y ocho" combined',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_20',
    emoji: '🔢',
    question: '¿Cómo se dice "nineteen"?',
    options: ['diecinueve', 'diez y nueve', 'diecinuebe'],
    correctAnswer: 'diecinueve',
    hint: 'Nineteen - last teen number, "diez y nueve" combined, legal drinking age some places',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },

  // Larger Numbers (10 questions)
  {
    id: 'numbers_21',
    emoji: '🔢',
    question: '¿Cómo se dice "twenty"?',
    options: ['veinte', 'vente', 'beinte'],
    correctAnswer: 'veinte',
    hint: 'Twenty - from Latin "viginti", 21-29 combine as "veinti-" (veintiuno, veintidós)',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_22',
    emoji: '🔢',
    question: '¿Cómo se dice "thirty"?',
    options: ['treinta', 'trenta', 'treynta'],
    correctAnswer: 'treinta',
    hint: 'Thirty - from "tres" + "-inta" suffix, pattern for 30-90 (treinta y uno, treinta y dos)',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_23',
    emoji: '🔢',
    question: '¿Cómo se dice "forty"?',
    options: ['cuarenta', 'quarenta', 'cuatrenta'],
    correctAnswer: 'cuarenta',
    hint: 'Forty - from "cuatro" + "-enta", notice spelling change from cuatro',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_24',
    emoji: '🔢',
    question: '¿Cómo se dice "fifty"?',
    options: ['cincuenta', 'cinquenta', 'cincenta'],
    correctAnswer: 'cincuenta',
    hint: 'Fifty - from "cinco" + "-enta", half of 100 is "media centena"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_25',
    emoji: '🔢',
    question: '¿Cómo se dice "sixty"?',
    options: ['sesenta', 'seisenta', 'secenta'],
    correctAnswer: 'sesenta',
    hint: 'Sixty - from "seis" + "-enta", 60 minutes in hour, 60 seconds in minute',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_26',
    emoji: '🔢',
    question: '¿Cómo se dice "seventy"?',
    options: ['setenta', 'sietenta', 'septenta'],
    correctAnswer: 'setenta',
    hint: 'Seventy - from "siete" + "-enta", notice spelling change from siete',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_27',
    emoji: '🔢',
    question: '¿Cómo se dice "eighty"?',
    options: ['ochenta', 'ochocenta', 'ochoenta'],
    correctAnswer: 'ochenta',
    hint: 'Eighty - from "ocho" + "-enta", follows decade pattern',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_28',
    emoji: '🔢',
    question: '¿Cómo se dice "ninety"?',
    options: ['noventa', 'nueventa', 'noventay'],
    correctAnswer: 'noventa',
    hint: 'Ninety - from "nueve" + "-enta", last decade before 100',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_29',
    emoji: '💯',
    question: '¿Cómo se dice "one hundred"?',
    options: ['cien', 'ciento', 'cientos'],
    correctAnswer: 'cien',
    hint: 'One hundred - "cien" alone, "ciento" before other numbers (ciento uno), from Latin "centum"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_30',
    emoji: '🔢',
    question: '¿Cómo se dice "one thousand"?',
    options: ['mil', 'miles', 'mille'],
    correctAnswer: 'mil',
    hint: 'One thousand - from Latin "mille", millennium is 1000 years, never changes (dos mil, tres mil)',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },

  // Days of the Week (7 questions)
  {
    id: 'numbers_31',
    emoji: '📅',
    question: '¿Cómo se dice "Monday"?',
    options: ['lunes', 'el lunes', 'los lunes'],
    correctAnswer: 'lunes',
    hint: 'Monday - from Latin "dies Lunae" (day of Moon), always lowercase, masculine singular',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_32',
    emoji: '📅',
    question: '¿Cómo se dice "Tuesday"?',
    options: ['martes', 'el martes', 'los martes'],
    correctAnswer: 'martes',
    hint: 'Tuesday - from Mars (Roman god of war), "día de Marte", always lowercase',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_33',
    emoji: '📅',
    question: '¿Cómo se dice "Wednesday"?',
    options: ['miércoles', 'el miércoles', 'los miércoles'],
    correctAnswer: 'miércoles',
    hint: 'Wednesday - from Mercury (Roman god), middle of work week, "hump day"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_34',
    emoji: '📅',
    question: '¿Cómo se dice "Thursday"?',
    options: ['jueves', 'el jueves', 'los jueves'],
    correctAnswer: 'jueves',
    hint: 'Thursday - from Jove/Jupiter (Roman king of gods), fourth work day',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_35',
    emoji: '📅',
    question: '¿Cómo se dice "Friday"?',
    options: ['viernes', 'el viernes', 'los viernes'],
    correctAnswer: 'viernes',
    hint: 'Friday - from Venus (Roman goddess of love), TGIF! Last work day, "Viernes Santo" is Good Friday',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_36',
    emoji: '📅',
    question: '¿Cómo se dice "Saturday"?',
    options: ['sábado', 'el sábado', 'los sábados'],
    correctAnswer: 'sábado',
    hint: 'Saturday - from Latin "Sabbatum" (Sabbath), weekend day, party night',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_37',
    emoji: '📅',
    question: '¿Cómo se dice "Sunday"?',
    options: ['domingo', 'el domingo', 'los domingos'],
    correctAnswer: 'domingo',
    hint: 'Sunday - from Latin "dies Dominicus" (Lord\'s day), rest day, family day in Spanish culture',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },

  // Months of the Year (12 questions)
  {
    id: 'numbers_38',
    emoji: '📆',
    question: '¿Cómo se dice "January"?',
    options: ['enero', 'el enero', 'januario'],
    correctAnswer: 'enero',
    hint: 'January - from Janus (Roman god of beginnings), New Year month, always lowercase in Spanish',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_39',
    emoji: '📆',
    question: '¿Cómo se dice "February"?',
    options: ['febrero', 'el febrero', 'februario'],
    correctAnswer: 'febrero',
    hint: 'February - shortest month (28/29 days), from Roman purification festival "Februa"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_40',
    emoji: '📆',
    question: '¿Cómo se dice "March"?',
    options: ['marzo', 'el marzo', 'marcho'],
    correctAnswer: 'marzo',
    hint: 'March - from Mars (god of war), spring begins, "Martes y trece" (Tuesday 13th) unlucky in Spanish',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_41',
    emoji: '📆',
    question: '¿Cómo se dice "April"?',
    options: ['abril', 'el abril', 'abrel'],
    correctAnswer: 'abril',
    hint: 'April - possibly from Latin "aperire" (to open) for spring flowers, "Día de los Inocentes" April 1st',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_42',
    emoji: '📆',
    question: '¿Cómo se dice "May"?',
    options: ['mayo', 'el mayo', 'mai'],
    correctAnswer: 'mayo',
    hint: 'May - from Maia (Roman goddess), "Cinco de Mayo" celebrated, spring/summer month',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_43',
    emoji: '📆',
    question: '¿Cómo se dice "June"?',
    options: ['junio', 'el junio', 'junho'],
    correctAnswer: 'junio',
    hint: 'June - from Juno (Roman goddess, protector of marriage), popular wedding month',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_44',
    emoji: '📆',
    question: '¿Cómo se dice "July"?',
    options: ['julio', 'el julio', 'jullio'],
    correctAnswer: 'julio',
    hint: 'July - named after Julius Caesar, summer month, vacation season in Spain',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_45',
    emoji: '📆',
    question: '¿Cómo se dice "August"?',
    options: ['agosto', 'el agosto', 'augusto'],
    correctAnswer: 'agosto',
    hint: 'August - named after Emperor Augustus, peak summer, "agosto" also means harvest time',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_46',
    emoji: '📆',
    question: '¿Cómo se dice "September"?',
    options: ['septiembre', 'setiembre', 'el septiembre'],
    correctAnswer: 'septiembre',
    hint: 'September - from Latin "septem" (seven, 7th in Roman calendar), back to school month',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_47',
    emoji: '📆',
    question: '¿Cómo se dice "October"?',
    options: ['octubre', 'otubre', 'el octubre'],
    correctAnswer: 'octubre',
    hint: 'October - from Latin "octo" (eight, 8th Roman month), "Día de la Raza" October 12',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_48',
    emoji: '📆',
    question: '¿Cómo se dice "November"?',
    options: ['noviembre', 'nobiembre', 'el noviembre'],
    correctAnswer: 'noviembre',
    hint: 'November - from Latin "novem" (nine, 9th Roman month), "Día de Muertos" November 1-2',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_49',
    emoji: '📆',
    question: '¿Cómo se dice "December"?',
    options: ['diciembre', 'disiembre', 'el diciembre'],
    correctAnswer: 'diciembre',
    hint: 'December - from Latin "decem" (ten, 10th Roman month), Christmas "Navidad" December 25',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },

  // Time Expressions (11 questions)
  {
    id: 'numbers_50',
    emoji: '⏰',
    question: '¿Cómo se dice "hour"?',
    options: ['hora', 'la hora', 'horas'],
    correctAnswer: 'hora',
    hint: 'Hour - 60 minutes, from Latin "hora", "¿qué hora es?" asks the time',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_51',
    emoji: '⏱️',
    question: '¿Cómo se dice "minute"?',
    options: ['minuto', 'el minuto', 'minutos'],
    correctAnswer: 'minuto',
    hint: 'Minute - 60 seconds, from Latin "minutus" (small), "un minuto" is wait a minute',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_52',
    emoji: '⏱️',
    question: '¿Cómo se dice "second"?',
    options: ['segundo', 'el segundo', 'segundos'],
    correctAnswer: 'segundo',
    hint: 'Second - smallest time unit, also means "second" (2nd), dual meaning in Spanish',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_53',
    emoji: '🌅',
    question: '¿Cómo se dice "morning"?',
    options: ['mañana', 'la mañana', 'mañanita'],
    correctAnswer: 'mañana',
    hint: 'Morning - before noon, also means "tomorrow", "de la mañana" for AM time',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_54',
    emoji: '☀️',
    question: '¿Cómo se dice "afternoon"?',
    options: ['tarde', 'la tarde', 'tardecita'],
    correctAnswer: 'tarde',
    hint: 'Afternoon - after noon until sunset, also means "late", "de la tarde" for PM time',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_55',
    emoji: '🌙',
    question: '¿Cómo se dice "night"?',
    options: ['noche', 'la noche', 'nochecita'],
    correctAnswer: 'noche',
    hint: 'Night - after sunset, from Latin "nox", "de la noche" for evening time, "medianoche" is midnight',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_56',
    emoji: '📅',
    question: '¿Cómo se dice "today"?',
    options: ['hoy', 'hoY', 'oy'],
    correctAnswer: 'hoy',
    hint: 'Today - this day, from Latin "hodie", "hoy en día" means nowadays',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_57',
    emoji: '📅',
    question: '¿Cómo se dice "yesterday"?',
    options: ['ayer', 'anteayer', 'ayér'],
    correctAnswer: 'ayer',
    hint: 'Yesterday - day before today, "anteayer" is day before yesterday (two days ago)',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_58',
    emoji: '📅',
    question: '¿Cómo se dice "tomorrow"?',
    options: ['mañana', 'la mañana', 'mañanita'],
    correctAnswer: 'mañana',
    hint: 'Tomorrow - day after today, also means "morning", context determines meaning',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_59',
    emoji: '📅',
    question: '¿Cómo se dice "week"?',
    options: ['semana', 'la semana', 'semanita'],
    correctAnswer: 'semana',
    hint: 'Week - seven days, from Latin "septimana" (seven), "fin de semana" is weekend',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_60',
    emoji: '📆',
    question: '¿Cómo se dice "year"?',
    options: ['año', 'el año', 'añito'],
    correctAnswer: 'año',
    hint: 'Year - twelve months, 365 days, from Latin "annus", "Año Nuevo" is New Year',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },

  // Colors (15 questions)
  {
    id: 'numbers_61',
    emoji: '🔴',
    question: '¿Cómo se dice "red"?',
    options: ['rojo', 'roja', 'rojos'],
    correctAnswer: 'rojo',
    hint: 'Red - changes to "roja" for feminine nouns, from Latin "russus", color of passion and danger',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_62',
    emoji: '🔵',
    question: '¿Cómo se dice "blue"?',
    options: ['azul', 'azules', 'azulado'],
    correctAnswer: 'azul',
    hint: 'Blue - from Arabic "lazaward" (lapis lazuli stone), no gender change, sky and ocean color',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_63',
    emoji: '🟢',
    question: '¿Cómo se dice "green"?',
    options: ['verde', 'verdes', 'verdoso'],
    correctAnswer: 'verde',
    hint: 'Green - no gender change, also means "unripe" (fruta verde), nature and plant color',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_64',
    emoji: '🟡',
    question: '¿Cómo se dice "yellow"?',
    options: ['amarillo', 'amarilla', 'amarillos'],
    correctAnswer: 'amarillo',
    hint: 'Yellow - changes to "amarilla" for feminine, from Arabic "al-mariyya", sun color',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_65',
    emoji: '🟠',
    question: '¿Cómo se dice "orange"?',
    options: ['naranja', 'anaranjado', 'naranjas'],
    correctAnswer: 'naranja',
    hint: 'Orange - same word as fruit, no gender change (invariable), from Sanskrit through Arabic',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_66',
    emoji: '🟣',
    question: '¿Cómo se dice "purple"?',
    options: ['morado', 'púrpura', 'violeta'],
    correctAnswer: 'morado',
    hint: 'Purple - changes to "morada", also "púrpura" or "violeta", royal color historically',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_67',
    emoji: '🩷',
    question: '¿Cómo se dice "pink"?',
    options: ['rosa', 'rosado', 'rosada'],
    correctAnswer: 'rosa',
    hint: 'Pink - same word as "rose" flower, no gender change, light red color',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_68',
    emoji: '⚫',
    question: '¿Cómo se dice "black"?',
    options: ['negro', 'negra', 'negros'],
    correctAnswer: 'negro',
    hint: 'Black - changes to "negra" for feminine, from Latin "niger", absence of light',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_69',
    emoji: '⚪',
    question: '¿Cómo se dice "white"?',
    options: ['blanco', 'blanca', 'blancos'],
    correctAnswer: 'blanco',
    hint: 'White - changes to "blanca", from Germanic "blank", all colors combined, purity symbol',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_70',
    emoji: '🩶',
    question: '¿Cómo se dice "gray"?',
    options: ['gris', 'grises', 'grisáceo'],
    correctAnswer: 'gris',
    hint: 'Gray - from French "gris", no gender change, mixture of black and white',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_71',
    emoji: '🟤',
    question: '¿Cómo se dice "brown"?',
    options: ['marrón', 'café', 'pardo'],
    correctAnswer: 'marrón',
    hint: 'Brown - from French "marron" (chestnut), Latin America often uses "café", earth color',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_72',
    emoji: '🎨',
    question: '¿Cómo se dice "color"?',
    options: ['color', 'el color', 'los colores'],
    correctAnswer: 'color',
    hint: 'Color - masculine noun, same spelling as English, from Latin "color"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_73',
    emoji: '🌈',
    question: '¿Cómo se dice "rainbow"?',
    options: ['arcoíris', 'arco iris', 'el arcoíris'],
    correctAnswer: 'arcoíris',
    hint: 'Rainbow - literally "arc of iris", seven colors spectrum, appears after rain',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_74',
    emoji: '💡',
    question: '¿Cómo se dice "light" (color)?',
    options: ['claro', 'oscuro', 'brillante'],
    correctAnswer: 'claro',
    hint: 'Light - pale color shade, "azul claro" (light blue), also means "clear" or "of course"',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_75',
    emoji: '🌑',
    question: '¿Cómo se dice "dark" (color)?',
    options: ['oscuro', 'claro', 'negro'],
    correctAnswer: 'oscuro',
    hint: 'Dark - deep color shade, "verde oscuro" (dark green), opposite of claro, from Latin "obscurus"',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
];
