/**
 * MEDICAL Category Questions
 * Category: medical
 */

export const medicalQuestions = [
{
    id: 'medical_001',
    emoji: '🚑',
    question: '¿Qué vehículo lleva a los enfermos al hospital?',
    translation: 'What vehicle takes the sick to the hospital?',
    options: ['la ambulancia', 'el vehículo de emergencia', 'el coche de urgencias'],
    correctAnswer: 'la ambulancia',
    hint: 'Ambulance - emergency medical vehicle, from Latin "ambulare" (to walk)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_002',
    emoji: '🚨',
    question: '¿Qué situación requiere ayuda inmediata?',
    translation: 'What situation requires immediate help?',
    options: ['la emergencia', 'la urgencia', 'la crisis'],
    correctAnswer: 'la emergencia',
    hint: 'Emergency - urgent situation requiring immediate action, dial 112 (Europe) or 911 (Americas)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_003',
    emoji: '👮',
    question: '¿Quién es?',
    translation: 'Who is it?',
    options: ['el policía', 'el agente', 'el oficial'],
    correctAnswer: 'el policía',
    hint: 'Police officer - "la policía" is the force, maintains order and safety',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_004',
    emoji: '🚒',
    question: '¿Qué vehículo apaga incendios?',
    translation: 'What vehicle puts out fires?',
    options: ['el camión de bomberos', 'el carro de bomberos', 'la autobomba'],
    correctAnswer: 'el camión de bomberos',
    hint: 'Fire truck - carries water and equipment, "bomberos" from "bomba" (pump)',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_005',
    emoji: '🏥',
    question: '¿Dónde vas en una emergencia?',
    translation: 'Where do you go in an emergency?',
    options: ['el hospital', 'el centro médico', 'el centro de salud'],
    correctAnswer: 'el hospital',
    hint: 'Hospital - emergency medical facility, "sala de urgencias" is ER',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_006',
    emoji: '👨‍⚕️',
    question: '¿Quién es?',
    translation: 'Who is it?',
    options: ['el doctor', 'el médico', 'el facultativo'],
    correctAnswer: 'el doctor',
    hint: 'Doctor - medical physician, "médico" also used, from Latin "docere" (to teach)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_007',
    emoji: '💊',
    question: '¿Qué tomas cuando estás enfermo?',
    translation: 'What do you take when you\'re sick?',
    options: ['la medicina', 'el medicamento', 'el remedio'],
    correctAnswer: 'la medicina',
    hint: 'Medicine - drug for treatment, "medicamento" more formal, "remedio" for remedy',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_008',
    emoji: '🤒',
    question: '¿Cómo está la persona?',
    translation: 'How is the person?',
    options: ['enferma', 'mala', 'indispuesta'],
    correctAnswer: 'enferma',
    hint: 'Sick - ill with disease, "enfermo/a" from Latin "infirmus" (not firm/weak)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_009',
    emoji: '🤕',
    question: '¿Qué tiene la persona?',
    translation: 'What does the person have?',
    options: ['la herida', 'la lesión', 'el traumatismo'],
    correctAnswer: 'la herida',
    hint: 'Wound - injury breaking skin, from Latin "ferire" (to strike)',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_010',
    emoji: '🩹',
    question: '¿Con qué cubres una herida?',
    translation: 'What do you cover a wound with?',
    options: ['el vendaje', 'la venda', 'el apósito'],
    correctAnswer: 'el vendaje',
    hint: 'Bandage - wraps wound, "venda" is the strip material itself',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_011',
    emoji: '💉',
    question: '¿Qué te ponen con una aguja?',
    translation: 'What do they give you with a needle?',
    options: ['la inyección', 'la vacuna', 'la jeringa'],
    correctAnswer: 'la inyección',
    hint: 'Injection - shot with needle, "vacuna" is vaccine type',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_012',
    emoji: '🌡️',
    question: '¿Con qué mides la fiebre?',
    translation: 'What do you measure fever with?',
    options: ['el termómetro', 'el medidor de temperatura', 'el termómetro clínico'],
    correctAnswer: 'el termómetro',
    hint: 'Thermometer - measures temperature, from Greek "therme" (heat) + "metron" (measure)',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_013',
    emoji: '😷',
    question: '¿Qué usa la persona?',
    translation: 'What does the person use?',
    options: ['la mascarilla', 'el cubrebocas', 'el tapabocas'],
    correctAnswer: 'la mascarilla',
    hint: 'Face mask - prevents disease spread, "cubrebocas" or "tapabocas" in Latin America',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_014',
    emoji: '🩺',
    question: '¿Con qué escucha el doctor tu corazón?',
    translation: 'What does the doctor listen to your heart with?',
    options: ['el estetoscopio', 'el fonendoscopio', 'el estetoscope'],
    correctAnswer: 'el estetoscopio',
    hint: 'Stethoscope - listens to heart/lungs, from Greek "stethos" (chest) + "skopein" (examine)',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_015',
    emoji: '🧴',
    question: '¿Qué usas para matar gérmenes?',
    translation: 'What do you use to kill germs?',
    options: ['el desinfectante', 'el antiséptico', 'el sanitizante'],
    correctAnswer: 'el desinfectante',
    hint: 'Disinfectant - kills germs, alcohol gel common type',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },

  // Emergency Situations & Responses (15 questions)
  {
    id: 'medical_016',
    emoji: '📞',
    question: '¿Qué número llamas en emergencia?',
    translation: 'What number do you call in an emergency?',
    options: ['el número de emergencia', 'el 112', 'el 911'],
    correctAnswer: 'el número de emergencia',
    hint: 'Emergency number - 112 in Spain/Europe, 911 in Mexico/Americas, always free',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_017',
    emoji: '🚨',
    question: '¿Qué llamas si hay un crimen?',
    translation: 'What do you call if there is a crime?',
    options: ['la policía', 'la poli', 'las autoridades'],
    correctAnswer: 'la policía',
    hint: 'Police - for crime and public safety, "la poli" colloquial',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_018',
    emoji: '🔥',
    question: '¿Qué llamas si hay fuego?',
    translation: 'What do you call if there is a fire?',
    options: ['los bomberos', 'el cuerpo de bomberos', 'los firefighters'],
    correctAnswer: 'los bomberos',
    hint: 'Firefighters - fight fires and rescue, "cuerpo de bomberos" is fire department',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_019',
    emoji: '🤕',
    question: '¿Qué llamas si alguien está herido?',
    translation: 'What do you call if someone is hurt?',
    options: ['la ambulancia', 'el servicio médico', 'la emergencia médica'],
    correctAnswer: 'la ambulancia',
    hint: 'Ambulance - for medical emergencies, paramedics provide first aid',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_020',
    emoji: '🏥',
    question: '¿A dónde te llevan en ambulancia?',
    translation: 'Where do they take you in an ambulance?',
    options: ['el hospital', 'urgencias', 'emergencias'],
    correctAnswer: 'el hospital',
    hint: 'Hospital - trauma center, "urgencias" or "emergencias" is emergency department',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_021',
    emoji: '🆘',
    question: '¿Qué gritas cuando necesitas ayuda?',
    translation: 'What do you shout when you need help?',
    options: ['ayuda', 'socorro', 'auxilio'],
    correctAnswer: 'ayuda',
    hint: 'Help - "¡socorro!" also means help, from Latin "adjutare" (to assist)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_022',
    emoji: '🚪',
    question: '¿Por dónde sales rápido?',
    translation: 'Where do you exit quickly?',
    options: ['la salida de emergencia', 'la salida de urgencia', 'la salida de seguridad'],
    correctAnswer: 'la salida de emergencia',
    hint: 'Emergency exit - marked with green signs, always keep clear',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_023',
    emoji: '🧯',
    question: '¿Qué usas para apagar fuego?',
    translation: 'What do you use to put out fire?',
    options: ['el extintor', 'el extinguidor', 'el matafuegos'],
    correctAnswer: 'el extintor',
    hint: 'Fire extinguisher - red cylinder, "extinguidor" also used in Latin America',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_024',
    emoji: '🚨',
    question: '¿Qué suena cuando hay peligro?',
    translation: 'What sounds when there is danger?',
    options: ['la alarma', 'la sirena', 'el aviso'],
    correctAnswer: 'la alarma',
    hint: 'Alarm - warning sound, from Italian "allarme" (to arms!)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_025',
    emoji: '⚠️',
    question: '¿Qué símbolo indica riesgo?',
    translation: 'What symbol indicates risk?',
    options: ['el peligro', 'el riesgo', 'la advertencia'],
    correctAnswer: 'el peligro',
    hint: 'Danger - warning sign, "riesgo" is risk, triangle symbol universal',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_026',
    emoji: '🆘',
    question: '¿Qué necesitas urgentemente?',
    translation: 'What do you need urgently?',
    options: ['la ayuda urgente', 'el socorro', 'la asistencia inmediata'],
    correctAnswer: 'la ayuda urgente',
    hint: 'Urgent help - "socorro" for distress call, SOS international signal',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_027',
    emoji: '🩹',
    question: '¿Qué haces con una herida?',
    translation: 'What do you do with a wound?',
    options: ['curar', 'tratar', 'atender'],
    correctAnswer: 'curar',
    hint: 'Treat/heal - "curar" also means cure, apply first aid to wounds',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_028',
    emoji: '🚑',
    question: '¿Dónde va el paciente en ambulancia?',
    translation: 'Where does the patient go in an ambulance?',
    options: ['la sala de emergencias', 'urgencias', 'el departamento de emergencias'],
    correctAnswer: 'la sala de emergencias',
    hint: 'Emergency room - ER/ED, "urgencias" in Spain, critical care department',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_029',
    emoji: '🧑‍⚕️',
    question: '¿Quién te atiende en emergencia?',
    translation: 'Who attends to you in an emergency?',
    options: ['el médico de urgencias', 'el doctor de emergencias', 'el médico de emergencias'],
    correctAnswer: 'el médico de urgencias',
    hint: 'Emergency doctor - ER physician, specialized in urgent care',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_030',
    emoji: '🚨',
    question: '¿Qué situación requiere acción inmediata?',
    translation: 'What situation requires immediate action?',
    options: ['la emergencia', 'la urgencia', 'la crisis'],
    correctAnswer: 'la emergencia',
    hint: 'Emergency - urgent crisis, from Latin "emergere" (to arise suddenly)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },

  // Medical Symptoms & Conditions (20 questions)
  {
    id: 'medical_031',
    emoji: '🤒',
    question: '¿Qué tienes cuando hay fiebre?',
    translation: 'What do you have when there is fever?',
    options: ['la temperatura alta', 'la fiebre', 'la calentura'],
    correctAnswer: 'la temperatura alta',
    hint: 'High temperature - fever over 38°C/100.4°F, "calentura" colloquial',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_032',
    emoji: '🤧',
    question: '¿Qué haces cuando estás resfriado?',
    translation: 'What do you do when you have a cold?',
    options: ['estornudar', 'toser', 'sonarse la nariz'],
    correctAnswer: 'estornudar',
    hint: 'Sneeze - from cold or allergies, "catarro" is head cold',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_033',
    emoji: '😷',
    question: '¿Qué usas para no contagiar?',
    translation: 'What do you use to not infect others?',
    options: ['la mascarilla', 'el cubrebocas', 'el tapabocas'],
    correctAnswer: 'la mascarilla',
    hint: 'Face mask - prevents contagion, became essential during COVID-19',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_034',
    emoji: '🤮',
    question: '¿Qué haces cuando tienes náuseas?',
    translation: 'What do you do when you have nausea?',
    options: ['vomitar', 'devolver', 'arrojar'],
    correctAnswer: 'vomitar',
    hint: 'Vomit - "devolver" also used, náusea is nausea feeling',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_035',
    emoji: '🤕',
    question: '¿Qué tienes cuando te duele?',
    translation: 'What do you have when it hurts?',
    options: ['el dolor', 'la molestia', 'el sufrimiento'],
    correctAnswer: 'el dolor',
    hint: 'Pain - "doler" is to hurt, from Latin "dolere" (to suffer)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_036',
    emoji: '🩹',
    question: '¿Qué tienes cuando te cortas?',
    translation: 'What do you have when you cut yourself?',
    options: ['la herida', 'la cortada', 'el raspón'],
    correctAnswer: 'la herida',
    hint: 'Wound - "cortada" is cut, "raspón" is scrape',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_037',
    emoji: '💔',
    question: '¿Qué duele cuando hay infarto?',
    translation: 'What hurts when there is a heart attack?',
    options: ['el corazón', 'el pecho', 'el tórax'],
    correctAnswer: 'el corazón',
    hint: 'Heart - heart attack is "infarto al miocardio", major emergency',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_038',
    emoji: '🧠',
    question: '¿Qué parte duele en dolor de cabeza?',
    translation: 'What part hurts in a headache?',
    options: ['la cabeza', 'el cráneo', 'la testa'],
    correctAnswer: 'la cabeza',
    hint: 'Head - headache is "dolor de cabeza", migraine is "migraña"',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_039',
    emoji: '🦷',
    question: '¿Qué te duele cuando vas al dentista?',
    translation: 'What hurts when you go to the dentist?',
    options: ['el diente', 'la muela', 'el colmillo'],
    correctAnswer: 'el diente',
    hint: 'Tooth - toothache is "dolor de muelas", "muela" is molar',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_040',
    emoji: '👂',
    question: '¿Qué órgano te duele en otitis?',
    translation: 'What organ hurts in otitis?',
    options: ['el oído', 'la oreja', 'el oído interno'],
    correctAnswer: 'el oído',
    hint: 'Ear - ear infection is "otitis", "oreja" is outer ear',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_041',
    emoji: '👃',
    question: '¿Por dónde respiras?',
    translation: 'Where do you breathe through?',
    options: ['la nariz', 'las fosas nasales', 'el tabique nasal'],
    correctAnswer: 'la nariz',
    hint: 'Nose - for breathing and smell, from Latin "nasus"',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_042',
    emoji: '🫁',
    question: '¿Qué órgano te ayuda a respirar?',
    translation: 'What organ helps you breathe?',
    options: ['los pulmones', 'los órganos respiratorios', 'el sistema respiratorio'],
    correctAnswer: 'los pulmones',
    hint: 'Lungs - two organs for breathing oxygen, from Latin "pulmo"',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_043',
    emoji: '🤰',
    question: '¿Qué condición tiene una mujer embarazada?',
    translation: 'What condition does a pregnant woman have?',
    options: ['el embarazo', 'la gestación', 'la preñez'],
    correctAnswer: 'el embarazo',
    hint: 'Pregnancy - carrying baby, from "embarazar" (to encumber)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_044',
    emoji: '🩸',
    question: '¿Qué líquido sale de una herida?',
    translation: 'What liquid comes out of a wound?',
    options: ['la sangre', 'el fluido sanguíneo', 'el líquido vital'],
    correctAnswer: 'la sangre',
    hint: 'Blood - vital fluid, from Latin "sanguis", type O+ most common',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_045',
    emoji: '💊',
    question: '¿Qué tomas cuando estás enfermo?',
    translation: 'What do you take when you\'re sick?',
    options: ['la medicina', 'el medicamento', 'el remedio'],
    correctAnswer: 'la medicina',
    hint: 'Medicine - treatment drug, "pastilla" is pill, "jarabe" is syrup',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_046',
    emoji: '💉',
    question: '¿Qué te ponen con aguja?',
    translation: 'What do they give you with a needle?',
    options: ['la inyección', 'la vacuna', 'el suero'],
    correctAnswer: 'la inyección',
    hint: 'Injection - shot with syringe, delivers medicine into muscle/vein',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_047',
    emoji: '🌡️',
    question: '¿Con qué mides la fiebre?',
    translation: 'What do you measure fever with?',
    options: ['el termómetro', 'el medidor de temperatura', 'el termómetro digital'],
    correctAnswer: 'el termómetro',
    hint: 'Thermometer - measures body temperature, digital now common',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_048',
    emoji: '🦴',
    question: '¿Qué se rompe en una fractura?',
    translation: 'What breaks in a fracture?',
    options: ['el hueso', 'el esqueleto', 'la estructura ósea'],
    correctAnswer: 'el hueso',
    hint: 'Bone - skeleton part, "fractura" is break, needs cast to heal',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_049',
    emoji: '🩼',
    question: '¿Qué usas con hueso roto?',
    translation: 'What do you use with a broken bone?',
    options: ['las muletas', 'los bastones', 'las béquelas'],
    correctAnswer: 'las muletas',
    hint: 'Crutches - support walking with leg injury, "bastones" also used',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_050',
    emoji: '🚑',
    question: '¿Qué personal te ayuda en emergencia?',
    translation: 'What personnel helps you in an emergency?',
    options: ['el paramédico', 'el técnico de emergencias', 'el EMT'],
    correctAnswer: 'el paramédico',
    hint: 'Paramedic - emergency medical technician, provides pre-hospital care',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_051',
    emoji: '🦠',
    question: '¿Qué causa enfermedades contagiosas?',
    translation: 'What causes contagious diseases?',
    options: ['la infección', 'el contagio', 'la bacteria'],
    correctAnswer: 'la infección',
    hint: 'Infection - caused by bacteria, viruses, or other pathogens entering the body',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_052',
    emoji: '🧪',
    question: '¿Qué te hacen para diagnosticar enfermedades?',
    translation: 'What do they do to diagnose diseases?',
    options: ['el análisis', 'el examen médico', 'la prueba'],
    correctAnswer: 'el análisis',
    hint: 'Medical test/analysis - blood test is "análisis de sangre", urine test is "análisis de orina"',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_053',
    emoji: '🧫',
    question: '¿Qué prueba de laboratorio identifica bacterias?',
    translation: 'What laboratory test identifies bacteria?',
    options: ['el cultivo', 'el análisis bacteriano', 'la muestra'],
    correctAnswer: 'el cultivo',
    hint: 'Culture - laboratory test to grow and identify bacteria, "cultivo bacteriano" or "cultivo de bacterias"',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_054',
    emoji: '🧬',
    question: '¿Qué prueba estudia tu ADN?',
    translation: 'What test studies your DNA?',
    options: ['la prueba genética', 'el análisis de ADN', 'el examen genético'],
    correctAnswer: 'la prueba genética',
    hint: 'Genetic test - analyzes DNA for hereditary diseases, "prueba de ADN" also used',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_055',
    emoji: 'x-ray.png',
    question: '¿Qué imagen médica te toman para ver los huesos?',
    translation: 'What medical image do they take to see bones?',
    options: ['la radiografía', 'los rayos X', 'la placa'],
    correctAnswer: 'la radiografía',
    hint: 'X-ray - medical imaging to see bones, "rayos X" is X-rays, "placa" colloquial',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  }
];
