/**
 * MEDICAL Category Questions
 * Category: medical
 */

export const medicalQuestions = [
{
    id: 'medical_001',
    emoji: 'ambulance.png',
    question: '¿Qué vehículo lleva a los enfermos al hospital?',
    translation: 'What vehicle takes the sick to the hospital?',
    options: ['la ambulancia', 'el vehículo de emergencia', 'el coche de urgencias'],
    correctAnswer: 'la ambulancia',
    hint: 'Ambulance - emergency medical vehicle, from Latin "ambulare" (to walk)',
  usageExample: 'La ambulancia llegó en menos de cinco minutos.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'medical_003',
    emoji: 'police-car.png',
    question: '¿Qué vehículo usan los policías?',
    translation: 'What vehicle do police use?',
    options: ['el carro de policía', 'el patrullero', 'la patrulla'],
    correctAnswer: 'el carro de policía',
    hint: 'Police car - patrol vehicle, "patrullero" or "patrulla" also used',
    usageExample: 'El carro de policía patrulló el barrio toda la noche.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_004',
    emoji: 'heart-monitor.png',
    question: '¿Con qué dispositivo mides los latidos del corazón?',
    translation: 'What device do you measure heartbeats with?',
    options: ['el monitor de frecuencia cardíaca', 'el pulsómetro', 'el monitor cardíaco'],
    correctAnswer: 'el monitor de frecuencia cardíaca',
    hint: 'Heart rate monitor - measures heart beats per minute, used in fitness and medical settings',
    usageExample: 'Uso el monitor de frecuencia cardíaca durante mi ejercicio.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_005',
    emoji: 'hospital.png',
    question: '¿Dónde vas en una emergencia?',
    translation: 'Where do you go in an emergency?',
    options: ['el hospital', 'el centro médico', 'el centro de salud'],
    correctAnswer: 'el hospital',
    hint: 'Hospital - emergency medical facility, "sala de urgencias" is ER',
    usageExample: 'En caso de accidente me llevan al hospital.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'medical_006',
    emoji: 'doctor.png',
    question: '¿Quién es?',
    translation: 'Who is it?',
    options: ['el doctor', 'el médico', 'el facultativo'],
    correctAnswer: 'el doctor',
    hint: 'Doctor - medical physician, "médico" also used, from Latin "docere" (to teach)',
    usageExample: 'El doctor revisó mis síntomas y me recetó descanso.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'medical_007',
    emoji: '💊',
    question: '¿Qué tomas cuando estás enfermo?',
    translation: 'What do you take when you\'re sick?',
    options: ['la medicina', 'el medicamento', 'el remedio'],
    correctAnswer: 'la medicina',
    hint: 'Medicine - drug for treatment, "medicamento" more formal, "remedio" for remedy',
    usageExample: 'Tomé la medicina según las indicaciones del médico.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'medical_008',
    emoji: '🤒',
    question: '¿Cómo está la persona?',
    translation: 'How is the person?',
    options: ['enferma', 'mala', 'indispuesta'],
    correctAnswer: 'enferma',
    hint: 'Sick - ill with disease, "enfermo/a" from Latin "infirmus" (not firm/weak)',
    usageExample: 'Después de la gripe, ella sigue enferma y cansada.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_009',
    emoji: '🤕',
    question: '¿Qué tiene la persona?',
    translation: 'What does the person have?',
    options: ['la herida', 'la lesión', 'el traumatismo'],
    correctAnswer: 'la herida',
    hint: 'Wound - injury breaking skin, from Latin "ferire" (to strike)',
    usageExample: 'La herida necesita puntos para cerrar correctamente.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'hurt',
  },
  {
    id: 'medical_010',
    emoji: 'band-aid.png',
    question: '¿Con qué cubres una herida pequeña?',
    translation: 'What do you cover a small wound with?',
    options: ['la curita', 'la tirita', 'el apósito adhesivo'],
    correctAnswer: 'la curita',
    hint: 'Band-aid - adhesive bandage for small cuts, "tirita" in Spain, "curita" in Latin America',
    usageExample: 'Puse una curita en el corte de mi dedo.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'medical_011',
    emoji: 'syringe.png',
    question: '¿Qué instrumento se usa para inyectar?',
    translation: 'What instrument is used to inject?',
    options: ['la jeringa', 'la jeringuilla', 'la aguja hipodérmica'],
    correctAnswer: 'la jeringa',
    hint: 'Syringe - medical device with needle for injections, "jeringuilla" in Spain',
    usageExample: 'La enfermera preparó la jeringa para la vacuna.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'medical_012',
    emoji: '🌡️',
    question: '¿Con qué mides la fiebre?',
    translation: 'What do you measure fever with?',
    options: ['el termómetro', 'el medidor de temperatura', 'el termómetro clínico'],
    correctAnswer: 'el termómetro',
    hint: 'Thermometer - measures temperature, from Greek "therme" (heat) + "metron" (measure)',
    usageExample: 'Comprobé la fiebre con el termómetro esta mañana.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_013',
    emoji: 'medical-mask.png',
    question: '¿Qué usa la persona?',
    translation: 'What does the person use?',
    options: ['la mascarilla', 'el cubrebocas', 'el tapabocas'],
    correctAnswer: 'la mascarilla',
    hint: 'Face mask - prevents disease spread, "cubrebocas" or "tapabocas" in Latin America',
    usageExample: 'Ella siempre lleva la mascarilla en el transporte público.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'medical_014',
    emoji: '🩺',
    question: '¿Con qué escucha el doctor tu corazón?',
    translation: 'What does the doctor listen to your heart with?',
    options: ['el estetoscopio', 'el fonendoscopio', 'el estetoscope'],
    correctAnswer: 'el estetoscopio',
    hint: 'Stethoscope - listens to heart/lungs, from Greek "stethos" (chest) + "skopein" (examine)',
    usageExample: 'El doctor usó el estetoscopio para escuchar mis pulmones.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_015',
    emoji: '🧴',
    question: '¿Qué usas para matar gérmenes?',
    translation: 'What do you use to kill germs?',
    options: ['el desinfectante', 'el antiséptico', 'el sanitizante'],
    correctAnswer: 'el desinfectante',
    hint: 'Disinfectant - kills germs, alcohol gel common type',
    usageExample: 'Usa el desinfectante antes de tocar la herida.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  // Emergency Situations & Responses (15 questions)
  {
    id: 'medical_016',
    emoji: '📞',
    question: '¿Qué número llamas en emergencia?',
    translation: 'What number do you call in an emergency?',
    options: ['el número de emergencia', 'el 112', 'el 911'],
    correctAnswer: 'el número de emergencia',
    hint: 'Emergency number - 112 in Spain/Europe, 911 in Mexico/Americas, always free',
    usageExample: 'En la calle llamé al número de emergencia para pedir ayuda.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'medical_017',
    emoji: 'infrared-forehead-scanner.png',
    question: '¿Con qué aparato mides la temperatura sin contacto?',
    translation: 'What device do you measure temperature with without contact?',
    options: ['el termómetro infrarrojo', 'el escáner de frente', 'el termómetro sin contacto'],
    correctAnswer: 'el termómetro infrarrojo',
    hint: 'Infrared forehead scanner - non-contact thermometer measures temperature from forehead, became common during COVID-19',
    usageExample: 'En la entrada verificaron mi temperatura con el termómetro infrarrojo.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_018',
    emoji: '🔥',
    question: '¿Qué llamas si hay fuego?',
    translation: 'What do you call if there is a fire?',
    options: ['los bomberos', 'el cuerpo de bomberos', 'los firefighters'],
    correctAnswer: 'los bomberos',
    hint: 'Firefighters - fight fires and rescue, "cuerpo de bomberos" is fire department',
    usageExample: 'Llamamos a los bomberos cuando vio humo en la cocina.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'medical_020',
    emoji: '🏥',
    question: '¿A dónde te llevan en ambulancia?',
    translation: 'Where do they take you in an ambulance?',
    options: ['el hospital', 'urgencias', 'emergencias'],
    correctAnswer: 'el hospital',
    hint: 'Hospital - trauma center, "urgencias" or "emergencias" is emergency department',
    usageExample: 'Tras el choque, me llevaron al hospital más cercano.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'medical_021',
    emoji: '🆘',
    question: '¿Qué gritas cuando necesitas ayuda?',
    translation: 'What do you shout when you need help?',
    options: ['ayuda', 'socorro', 'auxilio'],
    correctAnswer: 'ayuda',
    hint: 'Help - "¡socorro!" also means help, from Latin "adjutare" (to assist)',
    usageExample: 'Grité "¡ayuda!" cuando me quedé atrapado.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'afraid',
  },
  {
    id: 'medical_022',
    emoji: '🚪',
    question: '¿Por dónde sales rápido?',
    translation: 'Where do you exit quickly?',
    options: ['la salida de emergencia', 'la salida de urgencia', 'la salida de seguridad'],
    correctAnswer: 'la salida de emergencia',
    hint: 'Emergency exit - marked with green signs, always keep clear',
    usageExample: 'La sala tiene una clara señal hacia la salida de emergencia.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'medical_023',
    emoji: '🧯',
    question: '¿Qué usas para apagar fuego?',
    translation: 'What do you use to put out fire?',
    options: ['el extintor', 'el extinguidor', 'el matafuegos'],
    correctAnswer: 'el extintor',
    hint: 'Fire extinguisher - red cylinder, "extinguidor" also used in Latin America',
    usageExample: 'Aprendimos a usar el extintor en la capacitación de seguridad.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'medical_024',
    emoji: '🚨',
    question: '¿Qué suena cuando hay peligro?',
    translation: 'What sounds when there is danger?',
    options: ['la alarma', 'la sirena', 'el aviso'],
    correctAnswer: 'la alarma',
    hint: 'Alarm - warning sound, from Italian "allarme" (to arms!)',
    usageExample: 'La alarma sonó y evacuamos el edificio enseguida.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'medical_025',
    emoji: '⚠️',
    question: '¿Qué símbolo indica riesgo?',
    translation: 'What symbol indicates risk?',
    options: ['el peligro', 'el riesgo', 'la advertencia'],
    correctAnswer: 'el peligro',
    hint: 'Danger - warning sign, "riesgo" is risk, triangle symbol universal',
    usageExample: 'Vimos el letrero que indica el peligro en la zona.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'medical_026',
    emoji: '🆘',
    question: '¿Qué necesitas urgentemente?',
    translation: 'What do you need urgently?',
    options: ['la ayuda urgente', 'el socorro', 'la asistencia inmediata'],
    correctAnswer: 'la ayuda urgente',
    hint: 'Urgent help - "socorro" for distress call, SOS international signal',
    usageExample: 'Se pidió la ayuda urgente tras el derrumbe.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'medical_027',
    emoji: '🩹',
    question: '¿Qué haces con una herida?',
    translation: 'What do you do with a wound?',
    options: ['curar', 'tratar', 'atender'],
    correctAnswer: 'curar',
    hint: 'Treat/heal - "curar" also means cure, apply first aid to wounds',
    usageExample: 'Primero hay que limpiar la herida para poder curar la zona.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'medical_028',
    emoji: '🚑',
    question: '¿Dónde va el paciente en ambulancia?',
    translation: 'Where does the patient go in an ambulance?',
    options: ['la sala de emergencias', 'urgencias', 'el departamento de emergencias'],
    correctAnswer: 'la sala de emergencias',
    hint: 'Emergency room - ER/ED, "urgencias" in Spain, critical care department',
    usageExample: 'Nos dirigieron a la sala de emergencias tras la evaluación.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'medical_029',
    emoji: '🧑‍⚕️',
    question: '¿Quién te atiende en emergencia?',
    translation: 'Who attends to you in an emergency?',
    options: ['el médico de urgencias', 'el doctor de emergencias', 'el médico de emergencias'],
    correctAnswer: 'el médico de urgencias',
    hint: 'Emergency doctor - ER physician, specialized in urgent care',
    usageExample: 'El médico de urgencias me explicó el procedimiento a seguir.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'medical_030',
    emoji: '🚨',
    question: '¿Qué situación requiere acción inmediata?',
    translation: 'What situation requires immediate action?',
    options: ['la emergencia', 'la urgencia', 'la crisis'],
    correctAnswer: 'la emergencia',
    hint: 'Emergency - urgent crisis, from Latin "emergere" (to arise suddenly)',
    usageExample: 'El incendio en el taller fue una emergencia real.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'anxious',
  },

  // Medical Symptoms & Conditions (20 questions)
  {
    id: 'medical_031',
    emoji: '🤒',
    question: '¿Qué tienes cuando hay fiebre?',
    translation: 'What do you have when there is fever?',
    options: ['la temperatura alta', 'la fiebre', 'la calentura'],
    correctAnswer: 'la temperatura alta',
    hint: 'High temperature - fever over 38°C/100.4°F, "calentura" colloquial',
    usageExample: 'La temperatura alta indicó que tenía fiebre.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_032',
    emoji: '🤧',
    question: '¿Qué haces cuando estás resfriado?',
    translation: 'What do you do when you have a cold?',
    options: ['estornudar', 'toser', 'sonarse la nariz'],
    correctAnswer: 'estornudar',
    hint: 'Sneeze - from cold or allergies, "catarro" is head cold',
    usageExample: 'No pude evitar estornudar cuando me dio el polen.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_033',
    emoji: '😷',
    question: '¿Qué usas para no contagiar?',
    translation: 'What do you use to not infect others?',
    options: ['la mascarilla', 'el cubrebocas', 'el tapabocas'],
    correctAnswer: 'la mascarilla',
    hint: 'Face mask - prevents contagion, became essential during COVID-19',
    usageExample: 'Me puse la mascarilla antes de entrar al hospital.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'medical_034',
    emoji: '🤮',
    question: '¿Qué haces cuando tienes náuseas?',
    translation: 'What do you do when you have nausea?',
    options: ['vomitar', 'devolver', 'arrojar'],
    correctAnswer: 'vomitar',
    hint: 'Vomit - "devolver" also used, náusea is nausea feeling',
    usageExample: 'Tuve que detener el viaje porque sentí ganas de vomitar.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'medical_035',
    emoji: '🤕',
    question: '¿Qué tienes cuando te duele?',
    translation: 'What do you have when it hurts?',
    options: ['el dolor', 'la molestia', 'el sufrimiento'],
    correctAnswer: 'el dolor',
    hint: 'Pain - "doler" is to hurt, from Latin "dolere" (to suffer)',
  usageExample: 'Sufro dolor en la espalda después de correr.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_036',
    emoji: '🩹',
    question: '¿Qué tienes cuando te cortas?',
    translation: 'What do you have when you cut yourself?',
    options: ['la herida', 'la cortada', 'el raspón'],
    correctAnswer: 'la herida',
    hint: 'Wound - "cortada" is cut, "raspón" is scrape',
  usageExample: 'Limpié y curé la herida en la rodilla.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_037',
    emoji: 'heart.png',
    question: '¿Qué órgano bombea la sangre?',
    translation: 'What organ pumps blood?',
    options: ['el corazón', 'el órgano cardíaco', 'el músculo cardíaco'],
    correctAnswer: 'el corazón',
    hint: 'Heart - pumps blood through body, heart attack is "infarto al miocardio"',
    usageExample: 'Sentí que el corazón latía muy fuerte después de correr.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_038',
    emoji: 'brain.png',
    question: '¿Qué órgano controla el cuerpo?',
    translation: 'What organ controls the body?',
    options: ['el cerebro', 'el encéfalo', 'la mente'],
    correctAnswer: 'el cerebro',
    hint: 'Brain - controls all body functions, from Latin "cerebrum"',
    usageExample: 'El cerebro procesa la información que recibimos cada segundo.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_039',
    emoji: 'toothache.png',
    question: '¿Qué tienes cuando te duele un diente?',
    translation: 'What do you have when your tooth hurts?',
    options: ['el dolor de muelas', 'el dolor dental', 'la caries'],
    correctAnswer: 'el dolor de muelas',
    hint: 'Toothache - pain in tooth, often caused by cavity ("caries")',
    usageExample: 'Fui al dentista por el dolor de muelas que no paraba.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_040',
    emoji: '👂',
    question: '¿Qué órgano te duele en otitis?',
    translation: 'What organ hurts in otitis?',
    options: ['el oído', 'la oreja', 'el oído interno'],
    correctAnswer: 'el oído',
    hint: 'Ear - ear infection is "otitis", "oreja" is outer ear',
    usageExample: 'El oído le dolía tanto que tuvo que ir al médico.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'hurt',
  },
  {
    id: 'medical_041',
    emoji: 'nose.png',
    question: '¿Por dónde respiras?',
    translation: 'Where do you breathe through?',
    options: ['la nariz', 'las fosas nasales', 'el tabique nasal'],
    correctAnswer: 'la nariz',
    hint: 'Nose - for breathing and smell, from Latin "nasus"',
    usageExample: 'Respiro por la nariz para poder oler el perfume.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_042',
    emoji: 'lungs.png',
    question: '¿Qué órgano te ayuda a respirar?',
    translation: 'What organ helps you breathe?',
    options: ['los pulmones', 'los órganos respiratorios', 'el sistema respiratorio'],
    correctAnswer: 'los pulmones',
    hint: 'Lungs - two organs for breathing oxygen, from Latin "pulmo"',
    usageExample: 'Mis pulmones se expandieron profundamente al tomar aire fresco.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_043',
    emoji: '🤰',
    question: '¿Qué condición tiene una mujer embarazada?',
    translation: 'What condition does a pregnant woman have?',
    options: ['el embarazo', 'la gestación', 'la preñez'],
    correctAnswer: 'el embarazo',
    hint: 'Pregnancy - carrying baby, from "embarazar" (to encumber)',
    usageExample: 'Durante el embarazo visitó al médico mensualmente.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'medical_044',
    emoji: '🩸',
    question: '¿Qué líquido sale de una herida?',
    translation: 'What liquid comes out of a wound?',
    options: ['la sangre', 'el fluido sanguíneo', 'el líquido vital'],
    correctAnswer: 'la sangre',
    hint: 'Blood - vital fluid, from Latin "sanguis", type O+ most common',
    usageExample: 'La herida sangraba y perdió mucha sangre.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'medical_045',
    emoji: '💊',
    question: '¿Qué tomas cuando estás enfermo?',
    translation: 'What do you take when you\'re sick?',
    options: ['la medicina', 'el medicamento', 'el remedio'],
    correctAnswer: 'la medicina',
    hint: 'Medicine - treatment drug, "pastilla" is pill, "jarabe" is syrup',
    usageExample: 'Siempre guardo la medicina en el botiquín.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'medical_046',
    emoji: '💉',
    question: '¿Qué te ponen con aguja?',
    translation: 'What do they give you with a needle?',
    options: ['la inyección', 'la vacuna', 'el suero'],
    correctAnswer: 'la inyección',
    hint: 'Injection - shot with syringe, delivers medicine into muscle/vein',
    usageExample: 'Me dieron la inyección para prevenir la infección.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'medical_047',
    emoji: '🌡️',
    question: '¿Con qué mides la fiebre?',
    translation: 'What do you measure fever with?',
    options: ['el termómetro', 'el medidor de temperatura', 'el termómetro digital'],
    correctAnswer: 'el termómetro',
    hint: 'Thermometer - measures body temperature, digital now common',
    usageExample: 'Puso el termómetro bajo la lengua para medir la fiebre.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_048',
    emoji: '🦴',
    question: '¿Qué se rompe en una fractura?',
    translation: 'What breaks in a fracture?',
    options: ['el hueso', 'el esqueleto', 'la estructura ósea'],
    correctAnswer: 'el hueso',
    hint: 'Bone - skeleton part, "fractura" is break, needs cast to heal',
    usageExample: 'El hueso se fracturó y le pusieron un yeso.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'hurt',
  },
  {
    id: 'medical_049',
    emoji: '🩼',
    question: '¿Qué usas con hueso roto?',
    translation: 'What do you use with a broken bone?',
    options: ['las muletas', 'los bastones', 'las béquelas'],
    correctAnswer: 'las muletas',
    hint: 'Crutches - support walking with leg injury, "bastones" also used',
    usageExample: 'Caminó con las muletas durante seis semanas.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'hurt',
  },
  {
    id: 'medical_051',
    emoji: '🦠',
    question: '¿Qué causa enfermedades contagiosas?',
    translation: 'What causes contagious diseases?',
    options: ['la infección', 'el contagio', 'la bacteria'],
    correctAnswer: 'la infección',
    hint: 'Infection - caused by bacteria, viruses, or other pathogens entering the body',
    usageExample: 'La infección se extendió por falta de higiene.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'medical_052',
    emoji: '🧪',
    question: '¿Qué te hacen para diagnosticar enfermedades?',
    translation: 'What do they do to diagnose diseases?',
    options: ['el análisis', 'el examen médico', 'la prueba'],
    correctAnswer: 'el análisis',
    hint: 'Medical test/analysis - blood test is "análisis de sangre", urine test is "análisis de orina"',
    usageExample: 'Me hicieron un análisis de sangre esta mañana.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_053',
    emoji: '🧫',
    question: '¿Qué prueba de laboratorio identifica bacterias?',
    translation: 'What laboratory test identifies bacteria?',
    options: ['el cultivo', 'el análisis bacteriano', 'la muestra'],
    correctAnswer: 'el cultivo',
    hint: 'Culture - laboratory test to grow and identify bacteria, "cultivo bacteriano" or "cultivo de bacterias"',
    usageExample: 'El laboratorio inició el cultivo para identificar la bacteria.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_054',
    emoji: '🧬',
    question: '¿Qué prueba estudia tu ADN?',
    translation: 'What test studies your DNA?',
    options: ['la prueba genética', 'el análisis de ADN', 'el examen genético'],
    correctAnswer: 'la prueba genética',
    hint: 'Genetic test - analyzes DNA for hereditary diseases, "prueba de ADN" also used',
    usageExample: 'Hicimos la prueba genética para descartar enfermedades hereditarias.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_055',
    emoji: 'x-ray.png',
    question: '¿Qué imagen médica te toman para ver los huesos?',
    translation: 'What medical image do they take to see bones?',
    options: ['la radiografía', 'los rayos X', 'la placa'],
    correctAnswer: 'la radiografía',
    hint: 'X-ray - medical imaging to see bones, "rayos X" is X-rays, "placa" colloquial',
    usageExample: 'Me hicieron una radiografía para ver si había fractura.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_056',
    emoji: 'nurse.png',
    question: '¿Quién asiste al doctor en el hospital?',
    translation: 'Who assists the doctor in the hospital?',
    options: ['la enfermera', 'la auxiliar de enfermería', 'el personal de enfermería'],
    correctAnswer: 'la enfermera',
    hint: 'Nurse - provides patient care, "enfermero" for male nurse',
    usageExample: 'La enfermera tomó mis signos vitales al llegar.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'medical_057',
    emoji: 'patient.png',
    question: '¿Cómo se llama la persona que recibe tratamiento médico?',
    translation: 'What do you call the person who receives medical treatment?',
    options: ['el paciente', 'el enfermo', 'el usuario'],
    correctAnswer: 'el paciente',
    hint: 'Patient - person receiving medical care, from Latin "patiens" (suffering)',
    usageExample: 'El paciente llegó con dolor agudo en el abdomen.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_058',
    emoji: 'surgeon.png',
    question: '¿Qué doctor hace operaciones?',
    translation: 'What doctor performs operations?',
    options: ['el cirujano', 'el médico cirujano', 'el operador'],
    correctAnswer: 'el cirujano',
    hint: 'Surgeon - performs surgical operations, from Greek "kheirourgia" (handwork)',
    usageExample: 'El cirujano explicó los riesgos antes de la operación.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'medical_059',
    emoji: 'dentist.png',
    question: '¿Qué doctor cuida tus dientes?',
    translation: 'What doctor takes care of your teeth?',
    options: ['el dentista', 'el odontólogo', 'el doctor dental'],
    correctAnswer: 'el dentista',
    hint: 'Dentist - treats teeth and gums, "odontólogo" more formal term',
    usageExample: 'Tengo cita con el dentista para una limpieza.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_060',
    emoji: 'pharmacist.png',
    question: '¿Quién trabaja en la farmacia?',
    translation: 'Who works in the pharmacy?',
    options: ['el farmacéutico', 'el boticario', 'el químico farmacéutico'],
    correctAnswer: 'el farmacéutico',
    hint: 'Pharmacist - dispenses medications, "boticario" older term',
    usageExample: 'El farmacéutico me explicó cómo tomar el nuevo medicamento.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_061',
    emoji: 'anesthesiologist.png',
    question: '¿Qué doctor te duerme para una operación?',
    translation: 'What doctor puts you to sleep for an operation?',
    options: ['el anestesiólogo', 'el anestesista', 'el médico anestesista'],
    correctAnswer: 'el anestesiólogo',
    hint: 'Anesthesiologist - administers anesthesia for surgery',
    usageExample: 'El anestesiólogo verificó mis constantes antes de dormirme.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'anxious',
  },
  {
    id: 'medical_062',
    emoji: 'optometrist.png',
    question: '¿Qué profesional examina tu vista?',
    translation: 'What professional examines your eyesight?',
    options: ['el optometrista', 'el oculista', 'el oftalmólogo'],
    correctAnswer: 'el optometrista',
    hint: 'Optometrist - tests vision and prescribes glasses, "oftalmólogo" is eye surgeon',
    usageExample: 'Fui al optometrista para revisar mi vista anual.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_063',
    emoji: 'caregiver.png',
    question: '¿Quién cuida a personas enfermas o ancianas?',
    translation: 'Who cares for sick or elderly people?',
    options: ['el cuidador', 'el asistente de cuidado', 'el auxiliar de cuidado'],
    correctAnswer: 'el cuidador',
    hint: 'Caregiver - provides care for sick or elderly, "cuidadora" for female',
    usageExample: 'El cuidador ayudó a su abuelo con las tareas diarias.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'medical_064',
    emoji: 'phlebotomist.png',
    question: '¿Quién saca sangre para análisis?',
    translation: 'Who draws blood for testing?',
    options: ['el flebotomista', 'el técnico de laboratorio', 'el extraccionista'],
    correctAnswer: 'el flebotomista',
    hint: 'Phlebotomist - specialist in drawing blood, from Greek "phleps" (vein)',
    usageExample: 'El flebotomista extrajo la muestra de sangre rápidamente.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'anxious',
  },
  {
    id: 'medical_065',
    emoji: 'toxicologist.png',
    question: '¿Qué especialista estudia venenos?',
    translation: 'What specialist studies poisons?',
    options: ['el toxicólogo', 'el especialista en toxinas', 'el venereólogo'],
    correctAnswer: 'el toxicólogo',
    hint: 'Toxicologist - studies poisons and toxins, from Greek "toxikon" (poison)',
    usageExample: 'Consultamos al toxicólogo tras la ingestión accidental.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_066',
    emoji: 'skeleton.png',
    question: '¿Cómo se llama el conjunto de huesos del cuerpo?',
    translation: 'What do you call the set of bones in the body?',
    options: ['el esqueleto', 'la osamenta', 'el sistema óseo'],
    correctAnswer: 'el esqueleto',
    hint: 'Skeleton - framework of bones, adult has 206 bones',
    usageExample: 'En la clase vimos el esqueleto humano completo.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_067',
    emoji: 'skull.png',
    question: '¿Qué hueso protege el cerebro?',
    translation: 'What bone protects the brain?',
    options: ['el cráneo', 'la calavera', 'el hueso craneal'],
    correctAnswer: 'el cráneo',
    hint: 'Skull - bones of the head, "calavera" is colloquial',
    usageExample: 'El cráneo protege el cerebro de golpes fuertes.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_068',
    emoji: 'eyeball.png',
    question: '¿Qué órgano te permite ver?',
    translation: 'What organ allows you to see?',
    options: ['el ojo', 'el globo ocular', 'el órgano visual'],
    correctAnswer: 'el ojo',
    hint: 'Eye - organ of sight, "globo ocular" is eyeball',
    usageExample: 'Cerré un ojo para mirar mejor de cerca.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_069',
    emoji: 'jaw.png',
    question: '¿Qué hueso mueves cuando masticas?',
    translation: 'What bone do you move when you chew?',
    options: ['la mandíbula', 'la quijada', 'el maxilar'],
    correctAnswer: 'la mandíbula',
    hint: 'Jaw - lower jawbone, only movable skull bone',
    usageExample: 'Sentí tensión en la mandíbula al masticar rápido.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_070',
    emoji: 'stomach.png',
    question: '¿Qué órgano digiere la comida?',
    translation: 'What organ digests food?',
    options: ['el estómago', 'el vientre', 'el aparato digestivo'],
    correctAnswer: 'el estómago',
    hint: 'Stomach - digestive organ, holds food for 2-4 hours',
    usageExample: 'Después de comer mucho, el estómago me dolía.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_071',
    emoji: 'liver.png',
    question: '¿Qué órgano filtra toxinas?',
    translation: 'What organ filters toxins?',
    options: ['el hígado', 'el órgano hepático', 'el filtrador'],
    correctAnswer: 'el hígado',
    hint: 'Liver - largest internal organ, filters blood and produces bile',
    usageExample: 'El hígado procesa las toxinas cuando tomas alcohol.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_072',
    emoji: 'kidney.png',
    question: '¿Qué órgano filtra la sangre y produce orina?',
    translation: 'What organ filters blood and produces urine?',
    options: ['el riñón', 'el órgano renal', 'el filtro renal'],
    correctAnswer: 'el riñón',
    hint: 'Kidney - filters blood, we have two kidneys',
    usageExample: 'El riñón elimina los desechos del cuerpo a través de la orina.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_073',
    emoji: 'digestive-system.png',
    question: '¿Qué sistema procesa la comida?',
    translation: 'What system processes food?',
    options: ['el sistema digestivo', 'el aparato digestivo', 'el tracto gastrointestinal'],
    correctAnswer: 'el sistema digestivo',
    hint: 'Digestive system - processes food from mouth to anus',
    usageExample: 'El sistema digestivo transforma los alimentos en energía.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_074',
    emoji: 'pelvis.png',
    question: '¿Qué estructura ósea sostiene los órganos reproductivos?',
    translation: 'What bone structure supports the reproductive organs?',
    options: ['la pelvis', 'la cadera', 'el hueso pélvico'],
    correctAnswer: 'la pelvis',
    hint: 'Pelvis - basin-shaped bone structure, "cadera" is hip',
    usageExample: 'La pelvis soporta el peso de la parte inferior del cuerpo.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_075',
    emoji: 'knee-joint.png',
    question: '¿Qué articulación dobla la pierna?',
    translation: 'What joint bends the leg?',
    options: ['la rodilla', 'la articulación de la rodilla', 'el menisco'],
    correctAnswer: 'la rodilla',
    hint: 'Knee - largest joint in body, "menisco" is knee cartilage',
    usageExample: 'Me lastimé la rodilla jugando fútbol el fin de semana.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_076',
    emoji: 'inhaler.png',
    question: '¿Qué dispositivo usan los asmáticos para respirar?',
    translation: 'What device do asthmatics use to breathe?',
    options: ['el inhalador', 'el aerosol', 'el broncodilatador'],
    correctAnswer: 'el inhalador',
    hint: 'Inhaler - delivers asthma medication to lungs, "puff" in English',
    usageExample: 'Llevó el inhalador por si tenía una crisis asmática.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'medical_077',
    emoji: 'oxygen-canister.png',
    question: '¿Qué contenedor lleva oxígeno médico?',
    translation: 'What container carries medical oxygen?',
    options: ['el tanque de oxígeno', 'el cilindro de oxígeno', 'la bombona de oxígeno'],
    correctAnswer: 'el tanque de oxígeno',
    hint: 'Oxygen tank - portable oxygen supply for respiratory patients',
    usageExample: 'El paciente necesitó el tanque de oxígeno durante la noche.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_078',
    emoji: 'blood-pressure-meter.png',
    question: '¿Con qué mides la presión arterial?',
    translation: 'What do you measure blood pressure with?',
    options: ['el tensiómetro', 'el esfigmomanómetro', 'el medidor de presión'],
    correctAnswer: 'el tensiómetro',
    hint: 'Blood pressure meter - measures arterial pressure, "esfigmomanómetro" formal term',
    usageExample: 'El enfermero midió la presión con el tensiómetro.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_079',
    emoji: 'oximeter.png',
    question: '¿Con qué mides el oxígeno en la sangre?',
    translation: 'What do you measure oxygen in blood with?',
    options: ['el oxímetro', 'el pulsioxímetro', 'el medidor de oxígeno'],
    correctAnswer: 'el oxímetro',
    hint: 'Oximeter - measures blood oxygen saturation, clips on finger',
    usageExample: 'Colocaron el oxímetro en mi dedo para medir la saturación.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_080',
    emoji: 'glucometer.png',
    question: '¿Con qué miden los diabéticos su azúcar?',
    translation: 'What do diabetics measure their sugar with?',
    options: ['el glucómetro', 'el medidor de glucosa', 'el monitor de azúcar'],
    correctAnswer: 'el glucómetro',
    hint: 'Glucometer - measures blood sugar levels for diabetics',
    usageExample: 'Revisé mi nivel con el glucómetro antes de comer.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_081',
    emoji: 'glucose-monitor.png',
    question: '¿Qué dispositivo monitorea el azúcar continuamente?',
    translation: 'What device monitors sugar continuously?',
    options: ['el monitor de glucosa continuo', 'el CGM', 'el sensor de glucosa'],
    correctAnswer: 'el monitor de glucosa continuo',
    hint: 'Continuous glucose monitor - wearable device for diabetics, CGM in English',
    usageExample: 'El monitor de glucosa continuo avisó una bajada de azúcar.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'pleased',
  },
  {
    id: 'medical_082',
    emoji: 'otoscope.png',
    question: '¿Con qué examina el doctor tus oídos?',
    translation: 'What does the doctor examine your ears with?',
    options: ['el otoscopio', 'el auriscopo', 'el espéculo auricular'],
    correctAnswer: 'el otoscopio',
    hint: 'Otoscope - instrument to look inside ears, from Greek "ous" (ear)',
    usageExample: 'El doctor utilizó el otoscopio para revisar mi oído.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_083',
    emoji: 'hearing-aid.png',
    question: '¿Qué dispositivo ayuda a oír mejor?',
    translation: 'What device helps you hear better?',
    options: ['el audífono', 'el aparato auditivo', 'la prótesis auditiva'],
    correctAnswer: 'el audífono',
    hint: 'Hearing aid - amplifies sound for hearing impaired',
    usageExample: 'Mi abuelo usa el audífono para escuchar la televisión.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'medical_084',
    emoji: 'mri-machine.png',
    question: '¿Qué máquina toma imágenes detalladas del cuerpo?',
    translation: 'What machine takes detailed images of the body?',
    options: ['la resonancia magnética', 'el MRI', 'el escáner de resonancia'],
    correctAnswer: 'la resonancia magnética',
    hint: 'MRI machine - magnetic resonance imaging, very detailed body scan',
    usageExample: 'Me hicieron una resonancia magnética para revisar la lesión.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_085',
    emoji: 'plaster-cast.png',
    question: '¿Qué ponen en un hueso roto?',
    translation: 'What do they put on a broken bone?',
    options: ['el yeso', 'la escayola', 'el vendaje de yeso'],
    correctAnswer: 'el yeso',
    hint: 'Plaster cast - immobilizes broken bone, "escayola" in Spain',
    usageExample: 'Le pusieron el yeso para inmovilizar la pierna rota.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'hurt',
  },
  {
    id: 'medical_086',
    emoji: 'intravenous-therapy.png',
    question: '¿Cómo se llama el tratamiento por vena?',
    translation: 'What is the treatment through vein called?',
    options: ['la terapia intravenosa', 'el suero', 'la vía intravenosa'],
    correctAnswer: 'la terapia intravenosa',
    hint: 'Intravenous therapy - IV delivers fluids and medicine through vein',
    usageExample: 'Recibió la terapia intravenosa con antibióticos en el hospital.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_087',
    emoji: 'booster-shot.png',
    question: '¿Qué vacuna adicional refuerza la protección?',
    translation: 'What additional vaccine reinforces protection?',
    options: ['la vacuna de refuerzo', 'la dosis de refuerzo', 'el booster'],
    correctAnswer: 'la vacuna de refuerzo',
    hint: 'Booster shot - additional vaccine dose to boost immunity',
    usageExample: 'Me puse la vacuna de refuerzo antes del viaje.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'medical_088',
    emoji: 'sterile-swab.png',
    question: '¿Con qué toman muestras para análisis?',
    translation: 'What do they take samples with for testing?',
    options: ['el hisopo', 'el bastoncillo', 'el aplicador estéril'],
    correctAnswer: 'el hisopo',
    hint: 'Sterile swab - cotton-tipped stick for collecting samples, "bastoncillo" also used',
    usageExample: 'El técnico tomó la muestra con un hisopo estéril.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_089',
    emoji: 'urine-sample.png',
    question: '¿Qué análisis usa orina?',
    translation: 'What test uses urine?',
    options: ['el análisis de orina', 'el examen de orina', 'el urinocultivo'],
    correctAnswer: 'el análisis de orina',
    hint: 'Urine sample - tests urine for diseases and conditions',
    usageExample: 'El doctor pidió un análisis de orina para revisar la infección.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_090',
    emoji: 'tweezers.png',
    question: '¿Con qué quitan astillas o suturas?',
    translation: 'What do they remove splinters or stitches with?',
    options: ['las pinzas', 'las tenazas', 'el fórceps'],
    correctAnswer: 'las pinzas',
    hint: 'Tweezers - small gripping tool for removing splinters and stitches',
    usageExample: 'El doctor usó las pinzas para sacar la astilla.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_091',
    emoji: 'throat-spray.png',
    question: '¿Qué usas para el dolor de garganta?',
    translation: 'What do you use for sore throat?',
    options: ['el spray para la garganta', 'el aerosol bucal', 'el medicamento para garganta'],
    correctAnswer: 'el spray para la garganta',
    hint: 'Throat spray - liquid medicine sprayed on sore throat',
    usageExample: 'Rocié el spray para la garganta para aliviar el dolor.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'medical_092',
    emoji: 'thermal-blanket.png',
    question: '¿Qué manta de emergencia retiene calor?',
    translation: 'What emergency blanket retains heat?',
    options: ['la manta térmica', 'la manta de emergencia', 'la manta isotérmica'],
    correctAnswer: 'la manta térmica',
    hint: 'Thermal blanket - reflective emergency blanket prevents hypothermia',
    usageExample: 'Cubriron al herido con la manta térmica para conservar calor.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'calm',
  },
  {
    id: 'medical_093',
    emoji: 'muscle-strain.png',
    question: '¿Qué lesión ocurre cuando estiras demasiado un músculo?',
    translation: 'What injury occurs when you stretch a muscle too much?',
    options: ['la distensión muscular', 'el tirón muscular', 'el desgarro'],
    correctAnswer: 'la distensión muscular',
    hint: 'Muscle strain - pulled muscle from overstretching, "tirón" colloquial',
    usageExample: 'Sufrió una distensión muscular al levantar peso excesivo.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'hurt',
  },
  {
    id: 'medical_094',
    emoji: 'cold-sore.png',
    question: '¿Qué llaga aparece en los labios?',
    translation: 'What sore appears on the lips?',
    options: ['el herpes labial', 'la calentura', 'la ampolla febril'],
    correctAnswer: 'el herpes labial',
    hint: 'Cold sore - viral blister on lips, "calentura" colloquial',
    usageExample: 'El herpes labial apareció tras un resfriado fuerte.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'hurt',
  },
  {
    id: 'medical_095',
    emoji: 'blood-donation.png',
    question: '¿Qué acto voluntario salva vidas?',
    translation: 'What voluntary act saves lives?',
    options: ['la donación de sangre', 'la donación sanguínea', 'donar sangre'],
    correctAnswer: 'la donación de sangre',
    hint: 'Blood donation - voluntary giving of blood to help patients, can donate every 8-12 weeks',
    usageExample: 'Participé en la campaña de la donación de sangre del hospital.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'medical_096',
    emoji: 'crutches.png',
    question: '¿Qué usas para caminar con una pierna lesionada?',
    translation: 'What do you use to walk with an injured leg?',
    options: ['las muletas', 'los bastones', 'las béquelas'],
    correctAnswer: 'las muletas',
    hint: 'Crutches - support walking with leg injury, help transfer weight from legs to upper body',
    usageExample: 'Después de la operación, usó las muletas durante meses.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'hurt',
  },
  {
    id: 'medical_097',
    emoji: 'ultrasound.png',
    question: '¿Qué prueba usa ondas sonoras para ver dentro del cuerpo?',
    translation: 'What test uses sound waves to see inside the body?',
    options: ['el ultrasonido', 'la ecografía', 'el sonograma'],
    correctAnswer: 'el ultrasonido',
    hint: 'Ultrasound - imaging using sound waves, commonly used during pregnancy, "ecografía" also used',
    usageExample: 'La ecografía es un tipo de ultrasonido usado en embarazos.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'happy',
  },
  {
    id: 'medical_098',
    emoji: 'nasal-spray.png',
    question: '¿Qué usas para la congestión nasal?',
    translation: 'What do you use for nasal congestion?',
    options: ['el spray nasal', 'el aerosol nasal', 'el descongestionante nasal'],
    correctAnswer: 'el spray nasal',
    hint: 'Nasal spray - liquid medicine sprayed into nose, relieves congestion and allergies',
    usageExample: 'Compré un spray nasal para la congestión de la alergia.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'medical_099',
    emoji: 'headache.png',
    question: '¿Qué dolor sientes en la cabeza?',
    translation: 'What pain do you feel in your head?',
    options: ['el dolor de cabeza', 'la cefalea', 'la jaqueca'],
    correctAnswer: 'el dolor de cabeza',
    hint: 'Headache - pain in the head, "cefalea" is medical term, "jaqueca" is migraine',
    usageExample: 'Tomé un analgésico por el dolor de cabeza intenso.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_100',
    emoji: 'contact-lenses.png',
    question: '¿Qué usas en los ojos en lugar de gafas?',
    translation: 'What do you use in your eyes instead of glasses?',
    options: ['los lentes de contacto', 'las lentillas', 'los pupilentes'],
    correctAnswer: 'los lentes de contacto',
    hint: 'Contact lenses - worn directly on eye, "lentillas" in Spain, "pupilentes" in Latin America',
    usageExample: 'Prefiero los lentes de contacto cuando hago deporte.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'pleased',
  },


    {
    id: 'medical_101',
    emoji: '👁️',
    question: '¿Qué palabra usas para "eyes"?',
    translation: 'What word do you use for \'eyes\'?',
    options: ['los ojos', 'las orejas', 'las cejas'],
    correctAnswer: 'los ojos',
    hint: 'Eyes - organs of sight, "ojo" is singular',
      usageExample: 'Los ojos me ardieron por el humo.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_103',
    emoji: '👄',
    question: '¿Cuál es la palabra para "mouth"?',
    translation: 'What is the word for \'mouth\'?',
    options: ['la boca', 'la nariz', 'el labio'],
    correctAnswer: 'la boca',
    hint: 'Mouth - for eating and speaking, feminine',
    usageExample: 'Abre la boca para que te revise el dentista.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_104',
    emoji: '👂',
    question: 'En español, ¿qué es "ear"?',
    translation: 'In Spanish, what is \'ear\'?',
    options: ['la oreja', 'el ojo', 'la nariz'],
    correctAnswer: 'la oreja',
    hint: 'Ear - organ of hearing, "oído" is inner ear',
    usageExample: 'Se lavó la oreja con cuidado después de nadar.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_105',
    emoji: '✋',
    question: '¿Cómo dirías "hand"?',
    translation: 'How would you say \'hand\'?',
    options: ['la mano', 'el brazo', 'el dedo'],
    correctAnswer: 'la mano',
    hint: 'Hand - at end of arm, feminine despite ending in -o',
    usageExample: 'Lávate la mano antes de comer.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_106',
    emoji: '🦵',
    question: 'La palabra española para "leg" es...',
    translation: 'The Spanish word for \'leg\' is...',
    options: ['la pierna', 'el brazo', 'el pie'],
    correctAnswer: 'la pierna',
    hint: 'Leg - from hip to foot, feminine noun',
    usageExample: 'Se rompió la pierna en la caída.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_107',
    emoji: '🦶',
    question: '¿Qué palabra usas para "foot"?',
    translation: 'What word do you use for \'foot\'?',
    options: ['el pie', 'la pierna', 'la mano'],
    correctAnswer: 'el pie',
    hint: 'Foot - at end of leg, masculine noun',
    usageExample: 'Me lastimé el pie al tropezar con la piedra.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  // New questions added from work/medical-words.csv
  {
    id: 'medical_108',
    emoji: 'allergy-test-kit.png',
    question: '¿Qué dispositivo se usa para probar alergias?',
    translation: 'What device is used to test allergies?',
    options: ['el kit de prueba de alergia', 'la prueba de alergia', 'el kit para alergias'],
    correctAnswer: 'el kit de prueba de alergia',
    hint: 'Allergy test kits are used to identify substances that trigger allergic reactions',
    usageExample: 'El alergólogo usó el kit de prueba de alergia para identificar el alérgeno.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_109',
    emoji: 'crash-cart.png',
    question: '¿Cómo se llama el carro con equipo de emergencia para reanimación?',
    translation: 'What is the cart called that holds emergency resuscitation equipment?',
    options: ['el carro de paro', 'la camilla móvil', 'el carrito de medicinas'],
    correctAnswer: 'el carro de paro',
    hint: 'Crash cart contains defibrillator, drugs and supplies for resuscitation',
    usageExample: 'El personal llevó el carro de paro a la sala inmediatamente.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'medical_110',
    emoji: 'disposable-shoe-covers.png',
    question: '¿Qué cubre tus zapatos para mantener áreas estériles?',
    translation: 'What covers your shoes to keep areas sterile?',
    options: ['los cubrezapatos desechables', 'las botas protectoras', 'las fundas reutilizables para zapatos'],
    correctAnswer: 'los cubrezapatos desechables',
    hint: 'Disposable shoe covers protect sterile environments from outside contamination',
    usageExample: 'Los médicos se pusieron los cubrezapatos desechables antes de entrar.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_111',
    emoji: 'glove-dispenser.png',
    question: '¿Qué máquina contiene guantes para uso médico?',
    translation: 'What machine holds gloves for medical use?',
    options: ['el dispensador de guantes', 'el estante de guantes', 'la caja de guantes'],
    correctAnswer: 'el dispensador de guantes',
    hint: 'Glove dispensers are mounted on walls in clinical areas for easy access',
    usageExample: 'Saqué un par del dispensador de guantes antes de atender al paciente.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_112',
    emoji: 'heating-pad.png',
    question: '¿Qué usas para aliviar el dolor con calor?',
    translation: 'What do you use to relieve pain with heat?',
    options: ['la almohadilla térmica', 'la bolsa de hielo', 'el masajeador'],
    correctAnswer: 'la almohadilla térmica',
    hint: 'Heating pads provide localized heat to relax muscles and reduce pain',
    usageExample: 'Puse la almohadilla térmica en la zona adolorida.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'medical_113',
    emoji: 'laboratory.png',
    question: '¿Cómo se llama el lugar donde se hacen análisis médicos?',
    translation: 'What is the place called where medical tests are performed?',
    options: ['el laboratorio', 'la clínica', 'el consultorio'],
    correctAnswer: 'el laboratorio',
    hint: 'Laboratory - where samples are analyzed, cultures grown and tests performed',
    usageExample: 'Enviaron la muestra al laboratorio para su análisis.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_114',
    emoji: 'masseuse.png',
    question: '¿Cómo se llama la persona que da masajes terapéuticos?',
    translation: 'What is the person called who gives therapeutic massages?',
    options: ['la masajista', 'la fisioterapeuta', 'la enfermera'],
    correctAnswer: 'la masajista',
    hint: 'Masseuse / massage therapist provides muscle relaxation and pain relief',
    usageExample: 'La masajista alivió la tensión en mis hombros.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'medical_115',
    emoji: 'medical-id-bracelet.png',
    question: '¿Qué pulsera contiene información médica importante?',
    translation: 'What bracelet contains important medical information?',
    options: ['la pulsera de identificación médica', 'la pulsera de moda', 'la pulsera de contacto'],
    correctAnswer: 'la pulsera de identificación médica',
    hint: 'Medical ID bracelets list allergies, conditions or emergency contacts',
    usageExample: 'Lleva la pulsera de identificación médica por su alergia severa.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_116',
    emoji: 'oxygen-concentrator.png',
    question: '¿Qué aparato proporciona oxígeno concentrado al paciente?',
    translation: 'What device provides concentrated oxygen to the patient?',
    options: ['el concentrador de oxígeno', 'la botella de oxígeno', 'la mascarilla de oxígeno'],
    correctAnswer: 'el concentrador de oxígeno',
    hint: 'Oxygen concentrators extract oxygen from room air for patients needing supplemental oxygen',
    usageExample: 'El concentrador de oxígeno permitió que respirara mejor en casa.',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'medical_117',
    emoji: 'paramedic.png',
    question: '¿Cómo se llama el profesional que atiende emergencias fuera del hospital?',
    translation: 'What is the professional called who attends emergencies outside the hospital?',
    options: ['el paramédico', 'el médico de guardia', 'el bombero'],
    correctAnswer: 'el paramédico',
    hint: 'Paramedic provides pre-hospital emergency care and transport',
    usageExample: 'El paramédico estabilizó al paciente en la ambulancia.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'medical_118',
    emoji: 'pediatrician.png',
    question: '¿Cómo se llama el doctor que atiende a los niños?',
    translation: 'What is the doctor called who treats children?',
    options: ['el pediatra', 'el médico de familia', 'el neonatólogo'],
    correctAnswer: 'el pediatra',
    hint: 'Pediatrician - medical specialist for infants, children and adolescents',
    usageExample: 'El pediatra vacunó a mi hijo esta mañana.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'medical_119',
    emoji: 'prosthetic.png',
    question: '¿Cómo se llama un reemplazo artificial para una parte del cuerpo?',
    translation: 'What is an artificial replacement for a body part called?',
    options: ['la prótesis', 'el implante', 'la ortesis'],
    correctAnswer: 'la prótesis',
    hint: 'Prosthetic - artificial device replacing missing body parts',
    usageExample: 'Después del accidente le colocaron la prótesis de pierna.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'medical_120',
    emoji: 'psychologist.png',
    question: '¿Cómo se llama el profesional que ayuda con la salud mental?',
    translation: 'What is the professional called who helps with mental health?',
    options: ['el psicólogo', 'el psiquiatra', 'el terapeuta'],
    correctAnswer: 'el psicólogo',
    hint: 'Psychologist - studies behavior and provides therapy; psychiatrist is a medical doctor',
    usageExample: 'El psicólogo recomendó técnicas para manejar la ansiedad.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'medical_121',
    emoji: 'scientist.png',
    question: '¿Cómo se llama la persona que realiza investigaciones científicas?',
    translation: 'What is the person called who conducts scientific research?',
    options: ['el científico', 'el investigador', 'el profesor'],
    correctAnswer: 'el científico',
    hint: 'Scientist - conducts experiments and research in a laboratory or field',
    usageExample: 'El científico presentó los resultados del estudio clínico.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'determined',
  },

  {
    id: 'medical_122',
    emoji: 'forceps.png',
    question: '¿Con qué instrumento quirúrgico sujetan o extraen tejidos?',
    translation: 'With what surgical instrument do they hold or extract tissues?',
    options: ['las pinzas', 'el fórceps', 'las tijeras quirúrgicas'],
    correctAnswer: 'el fórceps',
    hint: 'Forceps are tong-like instruments used to grasp, hold, or extract tissue during procedures',
    usageExample: 'El cirujano utilizó el fórceps para extraer el tejido con cuidado.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  // Added from work/medical-words.csv
  {
    id: 'medical_123',
    emoji: 'chest.png',
    question: '¿Qué palabra usas para "chest"?',
    translation: 'What word do you use for "chest"?',
    options: ['el pecho', 'el tórax', 'la caja torácica'],
    correctAnswer: 'el pecho',
    hint: 'Chest - upper front part of the torso',
    usageExample: 'Me dolía el pecho después de subir las escaleras.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_124',
    emoji: 'finger.png',
    question: '¿Qué palabra usas para "finger"?',
    translation: 'What word do you use for "finger"?',
    options: ['el dedo', 'la falange', 'la uña'],
    correctAnswer: 'el dedo',
    hint: 'Finger - digit of the hand',
    usageExample: 'Me corté el dedo con el papel.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_125',
    emoji: 'lips.png',
    question: '¿Qué palabra usas para "lips"?',
    translation: 'What word do you use for "lips"?',
    options: ['los labios', 'las comisuras', 'la boca'],
    correctAnswer: 'los labios',
    hint: 'Lips - fleshy structures around the mouth',
    usageExample: 'Se pintó los labios antes de salir.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'medical_126',
    emoji: 'neck.png',
    question: '¿Qué palabra usas para "neck"?',
    translation: 'What word do you use for "neck"?',
    options: ['el cuello', 'la garganta', 'la nuca'],
    correctAnswer: 'el cuello',
    hint: 'Neck - connects head to torso',
    usageExample: 'Siento rigidez en el cuello por dormir mal.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_127',
    emoji: 'palm.png',
    question: '¿Qué palabra usas para "palm"?',
    translation: 'What word do you use for "palm"?',
    options: ['la palma', 'la planta', 'el dorso'],
    correctAnswer: 'la palma',
    hint: 'Palm - inner surface of the hand',
    usageExample: 'Me quemé la palma al tocar la olla caliente.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_128',
    emoji: 'teeth.png',
    question: '¿Qué palabra usas para "teeth"?',
    translation: 'What word do you use for "teeth"?',
    options: ['los dientes', 'la dentadura', 'las muelas'],
    correctAnswer: 'los dientes',
    hint: 'Teeth - for chewing and speaking',
    usageExample: 'Me duelen los dientes cuando como helado.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_129',
    emoji: 'thumb.png',
    question: '¿Qué palabra usas para "thumb"?',
    translation: 'What word do you use for "thumb"?',
    options: ['el pulgar', 'el dedo gordo', 'la uña del dedo'],
    correctAnswer: 'el pulgar',
    hint: 'Thumb - the short, thick first digit of the hand',
    usageExample: 'Usa el pulgar para presionar el botón.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'medical_130',
    emoji: 'toe.png',
    question: '¿Qué palabra usas para "toe"?',
    translation: 'What word do you use for "toe"?',
    options: ['el dedo del pie', 'la uña', 'la planta del pie'],
    correctAnswer: 'el dedo del pie',
    hint: 'Toe - digit of the foot',
    usageExample: 'Me lastimé el dedo del pie con la puerta.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'medical_131',
    emoji: 'tongue.png',
    question: '¿Qué palabra usas para "tongue"?',
    translation: 'What word do you use for "tongue"?',
    options: ['la lengua', 'el paladar', 'el sabor'],
    correctAnswer: 'la lengua',
    hint: 'Tongue - organ for taste and speech',
    usageExample: 'La lengua me ardía por comer algo muy picante.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'medical_132',
    emoji: 'wheelchair.png',
    question: '¿Qué palabra usas para "wheelchair"?',
    translation: 'What word do you use for "wheelchair"?',
    options: ['la silla de ruedas', 'el carrito de ruedas', 'la butaca'],
    correctAnswer: 'la silla de ruedas',
    hint: 'Wheelchair - mobility device for people with difficulty walking',
    usageExample: 'Tras la operación, usó la silla de ruedas temporalmente.',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'medical_133',
    emoji: 'wrist.png',
    question: '¿Qué palabra usas para "wrist"?',
    translation: 'What word do you use for "wrist"?',
    options: ['la muñeca', 'la muñeca de reloj', 'el antebrazo'],
    correctAnswer: 'la muñeca',
    hint: 'Wrist - joint between hand and forearm',
    usageExample: 'Se torció la muñeca jugando baloncesto.',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'hurt',
  },

  // Added: first-aid-kit question
  {
    id: 'medical_134',
    emoji: 'first-aid-kit.png',
    question: '¿Qué palabra usas para "first-aid kit"?',
    translation: 'What word do you use for "first-aid kit"?',
    options: ['el botiquín de primeros auxilios', 'la caja de primeros auxilios', 'el kit de primeros auxilios'],
    correctAnswer: 'el botiquín de primeros auxilios',
    hint: 'First-aid kit - a set of tools and supplies for treating minor injuries',
    usageExample: 'Guardamos el botiquín de primeros auxilios en un lugar accesible.',
    points: 10,
    category: 'medical',
    difficulty: 'easy',
    emotion: 'calm',
  },

];
