/**
 * MEDICAL Category Questions
 * Category: medical
 */

export const medicalQuestions = [
{
    id: 'medical_001',
    emoji: 'ambulance.png',
    question: '¿Qué vehículo lleva a los enfermos al hospital?',
    translation: 'What vehicle takes the sick to the hospital?',
    options: ['la ambulancia', 'el vehículo de emergencia', 'el coche de urgencias'],
    correctAnswer: 'la ambulancia',
    hint: 'Ambulance - emergency medical vehicle, from Latin "ambulare" (to walk)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_002',
    emoji: '🚨',
    question: '¿Qué situación requiere ayuda inmediata?',
    translation: 'What situation requires immediate help?',
    options: ['la emergencia', 'la urgencia', 'la crisis'],
    correctAnswer: 'la emergencia',
    hint: 'Emergency - urgent situation requiring immediate action, dial 112 (Europe) or 911 (Americas)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_003',
    emoji: 'police-car.png',
    question: '¿Qué vehículo usan los policías?',
    translation: 'What vehicle do police use?',
    options: ['el carro de policía', 'el patrullero', 'la patrulla'],
    correctAnswer: 'el carro de policía',
    hint: 'Police car - patrol vehicle, "patrullero" or "patrulla" also used',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_004',
    emoji: 'heart-rate-monitor.png',
    question: '¿Con qué dispositivo mides los latidos del corazón?',
    translation: 'What device do you measure heartbeats with?',
    options: ['el monitor de frecuencia cardíaca', 'el pulsómetro', 'el monitor cardíaco'],
    correctAnswer: 'el monitor de frecuencia cardíaca',
    hint: 'Heart rate monitor - measures heart beats per minute, used in fitness and medical settings',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_005',
    emoji: 'hospital.png',
    question: '¿Dónde vas en una emergencia?',
    translation: 'Where do you go in an emergency?',
    options: ['el hospital', 'el centro médico', 'el centro de salud'],
    correctAnswer: 'el hospital',
    hint: 'Hospital - emergency medical facility, "sala de urgencias" is ER',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_006',
    emoji: 'doctor.png',
    question: '¿Quién es?',
    translation: 'Who is it?',
    options: ['el doctor', 'el médico', 'el facultativo'],
    correctAnswer: 'el doctor',
    hint: 'Doctor - medical physician, "médico" also used, from Latin "docere" (to teach)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_007',
    emoji: '💊',
    question: '¿Qué tomas cuando estás enfermo?',
    translation: 'What do you take when you\'re sick?',
    options: ['la medicina', 'el medicamento', 'el remedio'],
    correctAnswer: 'la medicina',
    hint: 'Medicine - drug for treatment, "medicamento" more formal, "remedio" for remedy',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_008',
    emoji: '🤒',
    question: '¿Cómo está la persona?',
    translation: 'How is the person?',
    options: ['enferma', 'mala', 'indispuesta'],
    correctAnswer: 'enferma',
    hint: 'Sick - ill with disease, "enfermo/a" from Latin "infirmus" (not firm/weak)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_009',
    emoji: '🤕',
    question: '¿Qué tiene la persona?',
    translation: 'What does the person have?',
    options: ['la herida', 'la lesión', 'el traumatismo'],
    correctAnswer: 'la herida',
    hint: 'Wound - injury breaking skin, from Latin "ferire" (to strike)',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_010',
    emoji: 'band-aid.png',
    question: '¿Con qué cubres una herida pequeña?',
    translation: 'What do you cover a small wound with?',
    options: ['la curita', 'la tirita', 'el apósito adhesivo'],
    correctAnswer: 'la curita',
    hint: 'Band-aid - adhesive bandage for small cuts, "tirita" in Spain, "curita" in Latin America',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_011',
    emoji: 'syringe.png',
    question: '¿Qué instrumento se usa para inyectar?',
    translation: 'What instrument is used to inject?',
    options: ['la jeringa', 'la jeringuilla', 'la aguja hipodérmica'],
    correctAnswer: 'la jeringa',
    hint: 'Syringe - medical device with needle for injections, "jeringuilla" in Spain',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_012',
    emoji: '🌡️',
    question: '¿Con qué mides la fiebre?',
    translation: 'What do you measure fever with?',
    options: ['el termómetro', 'el medidor de temperatura', 'el termómetro clínico'],
    correctAnswer: 'el termómetro',
    hint: 'Thermometer - measures temperature, from Greek "therme" (heat) + "metron" (measure)',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_013',
    emoji: 'medical-mask.png',
    question: '¿Qué usa la persona?',
    translation: 'What does the person use?',
    options: ['la mascarilla', 'el cubrebocas', 'el tapabocas'],
    correctAnswer: 'la mascarilla',
    hint: 'Face mask - prevents disease spread, "cubrebocas" or "tapabocas" in Latin America',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_014',
    emoji: '🩺',
    question: '¿Con qué escucha el doctor tu corazón?',
    translation: 'What does the doctor listen to your heart with?',
    options: ['el estetoscopio', 'el fonendoscopio', 'el estetoscope'],
    correctAnswer: 'el estetoscopio',
    hint: 'Stethoscope - listens to heart/lungs, from Greek "stethos" (chest) + "skopein" (examine)',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_015',
    emoji: '🧴',
    question: '¿Qué usas para matar gérmenes?',
    translation: 'What do you use to kill germs?',
    options: ['el desinfectante', 'el antiséptico', 'el sanitizante'],
    correctAnswer: 'el desinfectante',
    hint: 'Disinfectant - kills germs, alcohol gel common type',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },

  // Emergency Situations & Responses (15 questions)
  {
    id: 'medical_016',
    emoji: '📞',
    question: '¿Qué número llamas en emergencia?',
    translation: 'What number do you call in an emergency?',
    options: ['el número de emergencia', 'el 112', 'el 911'],
    correctAnswer: 'el número de emergencia',
    hint: 'Emergency number - 112 in Spain/Europe, 911 in Mexico/Americas, always free',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_017',
    emoji: 'infrared-forehead-scanner.png',
    question: '¿Con qué aparato mides la temperatura sin contacto?',
    translation: 'What device do you measure temperature with without contact?',
    options: ['el termómetro infrarrojo', 'el escáner de frente', 'el termómetro sin contacto'],
    correctAnswer: 'el termómetro infrarrojo',
    hint: 'Infrared forehead scanner - non-contact thermometer measures temperature from forehead, became common during COVID-19',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_018',
    emoji: '🔥',
    question: '¿Qué llamas si hay fuego?',
    translation: 'What do you call if there is a fire?',
    options: ['los bomberos', 'el cuerpo de bomberos', 'los firefighters'],
    correctAnswer: 'los bomberos',
    hint: 'Firefighters - fight fires and rescue, "cuerpo de bomberos" is fire department',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_019',
    emoji: '🤕',
    question: '¿Qué llamas si alguien está herido?',
    translation: 'What do you call if someone is hurt?',
    options: ['la ambulancia', 'el servicio médico', 'la emergencia médica'],
    correctAnswer: 'la ambulancia',
    hint: 'Ambulance - for medical emergencies, paramedics provide first aid',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_020',
    emoji: '🏥',
    question: '¿A dónde te llevan en ambulancia?',
    translation: 'Where do they take you in an ambulance?',
    options: ['el hospital', 'urgencias', 'emergencias'],
    correctAnswer: 'el hospital',
    hint: 'Hospital - trauma center, "urgencias" or "emergencias" is emergency department',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_021',
    emoji: '🆘',
    question: '¿Qué gritas cuando necesitas ayuda?',
    translation: 'What do you shout when you need help?',
    options: ['ayuda', 'socorro', 'auxilio'],
    correctAnswer: 'ayuda',
    hint: 'Help - "¡socorro!" also means help, from Latin "adjutare" (to assist)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_022',
    emoji: '🚪',
    question: '¿Por dónde sales rápido?',
    translation: 'Where do you exit quickly?',
    options: ['la salida de emergencia', 'la salida de urgencia', 'la salida de seguridad'],
    correctAnswer: 'la salida de emergencia',
    hint: 'Emergency exit - marked with green signs, always keep clear',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_023',
    emoji: '🧯',
    question: '¿Qué usas para apagar fuego?',
    translation: 'What do you use to put out fire?',
    options: ['el extintor', 'el extinguidor', 'el matafuegos'],
    correctAnswer: 'el extintor',
    hint: 'Fire extinguisher - red cylinder, "extinguidor" also used in Latin America',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_024',
    emoji: '🚨',
    question: '¿Qué suena cuando hay peligro?',
    translation: 'What sounds when there is danger?',
    options: ['la alarma', 'la sirena', 'el aviso'],
    correctAnswer: 'la alarma',
    hint: 'Alarm - warning sound, from Italian "allarme" (to arms!)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_025',
    emoji: '⚠️',
    question: '¿Qué símbolo indica riesgo?',
    translation: 'What symbol indicates risk?',
    options: ['el peligro', 'el riesgo', 'la advertencia'],
    correctAnswer: 'el peligro',
    hint: 'Danger - warning sign, "riesgo" is risk, triangle symbol universal',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_026',
    emoji: '🆘',
    question: '¿Qué necesitas urgentemente?',
    translation: 'What do you need urgently?',
    options: ['la ayuda urgente', 'el socorro', 'la asistencia inmediata'],
    correctAnswer: 'la ayuda urgente',
    hint: 'Urgent help - "socorro" for distress call, SOS international signal',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_027',
    emoji: '🩹',
    question: '¿Qué haces con una herida?',
    translation: 'What do you do with a wound?',
    options: ['curar', 'tratar', 'atender'],
    correctAnswer: 'curar',
    hint: 'Treat/heal - "curar" also means cure, apply first aid to wounds',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_028',
    emoji: '🚑',
    question: '¿Dónde va el paciente en ambulancia?',
    translation: 'Where does the patient go in an ambulance?',
    options: ['la sala de emergencias', 'urgencias', 'el departamento de emergencias'],
    correctAnswer: 'la sala de emergencias',
    hint: 'Emergency room - ER/ED, "urgencias" in Spain, critical care department',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_029',
    emoji: '🧑‍⚕️',
    question: '¿Quién te atiende en emergencia?',
    translation: 'Who attends to you in an emergency?',
    options: ['el médico de urgencias', 'el doctor de emergencias', 'el médico de emergencias'],
    correctAnswer: 'el médico de urgencias',
    hint: 'Emergency doctor - ER physician, specialized in urgent care',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_030',
    emoji: '🚨',
    question: '¿Qué situación requiere acción inmediata?',
    translation: 'What situation requires immediate action?',
    options: ['la emergencia', 'la urgencia', 'la crisis'],
    correctAnswer: 'la emergencia',
    hint: 'Emergency - urgent crisis, from Latin "emergere" (to arise suddenly)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },

  // Medical Symptoms & Conditions (20 questions)
  {
    id: 'medical_031',
    emoji: '🤒',
    question: '¿Qué tienes cuando hay fiebre?',
    translation: 'What do you have when there is fever?',
    options: ['la temperatura alta', 'la fiebre', 'la calentura'],
    correctAnswer: 'la temperatura alta',
    hint: 'High temperature - fever over 38°C/100.4°F, "calentura" colloquial',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_032',
    emoji: '🤧',
    question: '¿Qué haces cuando estás resfriado?',
    translation: 'What do you do when you have a cold?',
    options: ['estornudar', 'toser', 'sonarse la nariz'],
    correctAnswer: 'estornudar',
    hint: 'Sneeze - from cold or allergies, "catarro" is head cold',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_033',
    emoji: '😷',
    question: '¿Qué usas para no contagiar?',
    translation: 'What do you use to not infect others?',
    options: ['la mascarilla', 'el cubrebocas', 'el tapabocas'],
    correctAnswer: 'la mascarilla',
    hint: 'Face mask - prevents contagion, became essential during COVID-19',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_034',
    emoji: '🤮',
    question: '¿Qué haces cuando tienes náuseas?',
    translation: 'What do you do when you have nausea?',
    options: ['vomitar', 'devolver', 'arrojar'],
    correctAnswer: 'vomitar',
    hint: 'Vomit - "devolver" also used, náusea is nausea feeling',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_035',
    emoji: '🤕',
    question: '¿Qué tienes cuando te duele?',
    translation: 'What do you have when it hurts?',
    options: ['el dolor', 'la molestia', 'el sufrimiento'],
    correctAnswer: 'el dolor',
    hint: 'Pain - "doler" is to hurt, from Latin "dolere" (to suffer)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_036',
    emoji: '🩹',
    question: '¿Qué tienes cuando te cortas?',
    translation: 'What do you have when you cut yourself?',
    options: ['la herida', 'la cortada', 'el raspón'],
    correctAnswer: 'la herida',
    hint: 'Wound - "cortada" is cut, "raspón" is scrape',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_037',
    emoji: 'heart.png',
    question: '¿Qué órgano bombea la sangre?',
    translation: 'What organ pumps blood?',
    options: ['el corazón', 'el órgano cardíaco', 'el músculo cardíaco'],
    correctAnswer: 'el corazón',
    hint: 'Heart - pumps blood through body, heart attack is "infarto al miocardio"',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_038',
    emoji: 'brain.png',
    question: '¿Qué órgano controla el cuerpo?',
    translation: 'What organ controls the body?',
    options: ['el cerebro', 'el encéfalo', 'la mente'],
    correctAnswer: 'el cerebro',
    hint: 'Brain - controls all body functions, from Latin "cerebrum"',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_039',
    emoji: 'toothache.png',
    question: '¿Qué tienes cuando te duele un diente?',
    translation: 'What do you have when your tooth hurts?',
    options: ['el dolor de muelas', 'el dolor dental', 'la caries'],
    correctAnswer: 'el dolor de muelas',
    hint: 'Toothache - pain in tooth, often caused by cavity ("caries")',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_040',
    emoji: '👂',
    question: '¿Qué órgano te duele en otitis?',
    translation: 'What organ hurts in otitis?',
    options: ['el oído', 'la oreja', 'el oído interno'],
    correctAnswer: 'el oído',
    hint: 'Ear - ear infection is "otitis", "oreja" is outer ear',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_041',
    emoji: 'nose.png',
    question: '¿Por dónde respiras?',
    translation: 'Where do you breathe through?',
    options: ['la nariz', 'las fosas nasales', 'el tabique nasal'],
    correctAnswer: 'la nariz',
    hint: 'Nose - for breathing and smell, from Latin "nasus"',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_042',
    emoji: 'lungs.png',
    question: '¿Qué órgano te ayuda a respirar?',
    translation: 'What organ helps you breathe?',
    options: ['los pulmones', 'los órganos respiratorios', 'el sistema respiratorio'],
    correctAnswer: 'los pulmones',
    hint: 'Lungs - two organs for breathing oxygen, from Latin "pulmo"',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_043',
    emoji: '🤰',
    question: '¿Qué condición tiene una mujer embarazada?',
    translation: 'What condition does a pregnant woman have?',
    options: ['el embarazo', 'la gestación', 'la preñez'],
    correctAnswer: 'el embarazo',
    hint: 'Pregnancy - carrying baby, from "embarazar" (to encumber)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_044',
    emoji: '🩸',
    question: '¿Qué líquido sale de una herida?',
    translation: 'What liquid comes out of a wound?',
    options: ['la sangre', 'el fluido sanguíneo', 'el líquido vital'],
    correctAnswer: 'la sangre',
    hint: 'Blood - vital fluid, from Latin "sanguis", type O+ most common',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_045',
    emoji: '💊',
    question: '¿Qué tomas cuando estás enfermo?',
    translation: 'What do you take when you\'re sick?',
    options: ['la medicina', 'el medicamento', 'el remedio'],
    correctAnswer: 'la medicina',
    hint: 'Medicine - treatment drug, "pastilla" is pill, "jarabe" is syrup',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_046',
    emoji: '💉',
    question: '¿Qué te ponen con aguja?',
    translation: 'What do they give you with a needle?',
    options: ['la inyección', 'la vacuna', 'el suero'],
    correctAnswer: 'la inyección',
    hint: 'Injection - shot with syringe, delivers medicine into muscle/vein',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_047',
    emoji: '🌡️',
    question: '¿Con qué mides la fiebre?',
    translation: 'What do you measure fever with?',
    options: ['el termómetro', 'el medidor de temperatura', 'el termómetro digital'],
    correctAnswer: 'el termómetro',
    hint: 'Thermometer - measures body temperature, digital now common',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_048',
    emoji: '🦴',
    question: '¿Qué se rompe en una fractura?',
    translation: 'What breaks in a fracture?',
    options: ['el hueso', 'el esqueleto', 'la estructura ósea'],
    correctAnswer: 'el hueso',
    hint: 'Bone - skeleton part, "fractura" is break, needs cast to heal',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_049',
    emoji: '🩼',
    question: '¿Qué usas con hueso roto?',
    translation: 'What do you use with a broken bone?',
    options: ['las muletas', 'los bastones', 'las béquelas'],
    correctAnswer: 'las muletas',
    hint: 'Crutches - support walking with leg injury, "bastones" also used',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_050',
    emoji: '🚑',
    question: '¿Qué personal te ayuda en emergencia?',
    translation: 'What personnel helps you in an emergency?',
    options: ['el paramédico', 'el técnico de emergencias', 'el EMT'],
    correctAnswer: 'el paramédico',
    hint: 'Paramedic - emergency medical technician, provides pre-hospital care',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_051',
    emoji: '🦠',
    question: '¿Qué causa enfermedades contagiosas?',
    translation: 'What causes contagious diseases?',
    options: ['la infección', 'el contagio', 'la bacteria'],
    correctAnswer: 'la infección',
    hint: 'Infection - caused by bacteria, viruses, or other pathogens entering the body',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_052',
    emoji: '🧪',
    question: '¿Qué te hacen para diagnosticar enfermedades?',
    translation: 'What do they do to diagnose diseases?',
    options: ['el análisis', 'el examen médico', 'la prueba'],
    correctAnswer: 'el análisis',
    hint: 'Medical test/analysis - blood test is "análisis de sangre", urine test is "análisis de orina"',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_053',
    emoji: '🧫',
    question: '¿Qué prueba de laboratorio identifica bacterias?',
    translation: 'What laboratory test identifies bacteria?',
    options: ['el cultivo', 'el análisis bacteriano', 'la muestra'],
    correctAnswer: 'el cultivo',
    hint: 'Culture - laboratory test to grow and identify bacteria, "cultivo bacteriano" or "cultivo de bacterias"',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_054',
    emoji: '🧬',
    question: '¿Qué prueba estudia tu ADN?',
    translation: 'What test studies your DNA?',
    options: ['la prueba genética', 'el análisis de ADN', 'el examen genético'],
    correctAnswer: 'la prueba genética',
    hint: 'Genetic test - analyzes DNA for hereditary diseases, "prueba de ADN" also used',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_055',
    emoji: 'x-ray.png',
    question: '¿Qué imagen médica te toman para ver los huesos?',
    translation: 'What medical image do they take to see bones?',
    options: ['la radiografía', 'los rayos X', 'la placa'],
    correctAnswer: 'la radiografía',
    hint: 'X-ray - medical imaging to see bones, "rayos X" is X-rays, "placa" colloquial',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_056',
    emoji: 'nurse.png',
    question: '¿Quién asiste al doctor en el hospital?',
    translation: 'Who assists the doctor in the hospital?',
    options: ['la enfermera', 'la auxiliar de enfermería', 'el personal de enfermería'],
    correctAnswer: 'la enfermera',
    hint: 'Nurse - provides patient care, "enfermero" for male nurse',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_057',
    emoji: 'patient.png',
    question: '¿Cómo se llama la persona que recibe tratamiento médico?',
    translation: 'What do you call the person who receives medical treatment?',
    options: ['el paciente', 'el enfermo', 'el usuario'],
    correctAnswer: 'el paciente',
    hint: 'Patient - person receiving medical care, from Latin "patiens" (suffering)',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_058',
    emoji: 'surgeon.png',
    question: '¿Qué doctor hace operaciones?',
    translation: 'What doctor performs operations?',
    options: ['el cirujano', 'el médico cirujano', 'el operador'],
    correctAnswer: 'el cirujano',
    hint: 'Surgeon - performs surgical operations, from Greek "kheirourgia" (handwork)',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_059',
    emoji: 'dentist.png',
    question: '¿Qué doctor cuida tus dientes?',
    translation: 'What doctor takes care of your teeth?',
    options: ['el dentista', 'el odontólogo', 'el doctor dental'],
    correctAnswer: 'el dentista',
    hint: 'Dentist - treats teeth and gums, "odontólogo" more formal term',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_060',
    emoji: 'pharmacist.png',
    question: '¿Quién trabaja en la farmacia?',
    translation: 'Who works in the pharmacy?',
    options: ['el farmacéutico', 'el boticario', 'el químico farmacéutico'],
    correctAnswer: 'el farmacéutico',
    hint: 'Pharmacist - dispenses medications, "boticario" older term',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_061',
    emoji: 'anesthesiologist.png',
    question: '¿Qué doctor te duerme para una operación?',
    translation: 'What doctor puts you to sleep for an operation?',
    options: ['el anestesiólogo', 'el anestesista', 'el médico anestesista'],
    correctAnswer: 'el anestesiólogo',
    hint: 'Anesthesiologist - administers anesthesia for surgery',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_062',
    emoji: 'optometrist.png',
    question: '¿Qué profesional examina tu vista?',
    translation: 'What professional examines your eyesight?',
    options: ['el optometrista', 'el oculista', 'el oftalmólogo'],
    correctAnswer: 'el optometrista',
    hint: 'Optometrist - tests vision and prescribes glasses, "oftalmólogo" is eye surgeon',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_063',
    emoji: 'caregiver.png',
    question: '¿Quién cuida a personas enfermas o ancianas?',
    translation: 'Who cares for sick or elderly people?',
    options: ['el cuidador', 'el asistente de cuidado', 'el auxiliar de cuidado'],
    correctAnswer: 'el cuidador',
    hint: 'Caregiver - provides care for sick or elderly, "cuidadora" for female',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_064',
    emoji: 'phlebotomist.png',
    question: '¿Quién saca sangre para análisis?',
    translation: 'Who draws blood for testing?',
    options: ['el flebotomista', 'el técnico de laboratorio', 'el extraccionista'],
    correctAnswer: 'el flebotomista',
    hint: 'Phlebotomist - specialist in drawing blood, from Greek "phleps" (vein)',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_065',
    emoji: 'toxicologist.png',
    question: '¿Qué especialista estudia venenos?',
    translation: 'What specialist studies poisons?',
    options: ['el toxicólogo', 'el especialista en toxinas', 'el venereólogo'],
    correctAnswer: 'el toxicólogo',
    hint: 'Toxicologist - studies poisons and toxins, from Greek "toxikon" (poison)',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_066',
    emoji: 'skeleton.png',
    question: '¿Cómo se llama el conjunto de huesos del cuerpo?',
    translation: 'What do you call the set of bones in the body?',
    options: ['el esqueleto', 'la osamenta', 'el sistema óseo'],
    correctAnswer: 'el esqueleto',
    hint: 'Skeleton - framework of bones, adult has 206 bones',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_067',
    emoji: 'skull.png',
    question: '¿Qué hueso protege el cerebro?',
    translation: 'What bone protects the brain?',
    options: ['el cráneo', 'la calavera', 'el hueso craneal'],
    correctAnswer: 'el cráneo',
    hint: 'Skull - bones of the head, "calavera" is colloquial',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_068',
    emoji: 'eyeball.png',
    question: '¿Qué órgano te permite ver?',
    translation: 'What organ allows you to see?',
    options: ['el ojo', 'el globo ocular', 'el órgano visual'],
    correctAnswer: 'el ojo',
    hint: 'Eye - organ of sight, "globo ocular" is eyeball',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_069',
    emoji: 'jaw.png',
    question: '¿Qué hueso mueves cuando masticas?',
    translation: 'What bone do you move when you chew?',
    options: ['la mandíbula', 'la quijada', 'el maxilar'],
    correctAnswer: 'la mandíbula',
    hint: 'Jaw - lower jawbone, only movable skull bone',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_070',
    emoji: 'stomach.png',
    question: '¿Qué órgano digiere la comida?',
    translation: 'What organ digests food?',
    options: ['el estómago', 'el vientre', 'el aparato digestivo'],
    correctAnswer: 'el estómago',
    hint: 'Stomach - digestive organ, holds food for 2-4 hours',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_071',
    emoji: 'liver.png',
    question: '¿Qué órgano filtra toxinas?',
    translation: 'What organ filters toxins?',
    options: ['el hígado', 'el órgano hepático', 'el filtrador'],
    correctAnswer: 'el hígado',
    hint: 'Liver - largest internal organ, filters blood and produces bile',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_072',
    emoji: 'kidney.png',
    question: '¿Qué órgano filtra la sangre y produce orina?',
    translation: 'What organ filters blood and produces urine?',
    options: ['el riñón', 'el órgano renal', 'el filtro renal'],
    correctAnswer: 'el riñón',
    hint: 'Kidney - filters blood, we have two kidneys',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_073',
    emoji: 'digestive-system.png',
    question: '¿Qué sistema procesa la comida?',
    translation: 'What system processes food?',
    options: ['el sistema digestivo', 'el aparato digestivo', 'el tracto gastrointestinal'],
    correctAnswer: 'el sistema digestivo',
    hint: 'Digestive system - processes food from mouth to anus',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_074',
    emoji: 'pelvis.png',
    question: '¿Qué estructura ósea sostiene los órganos reproductivos?',
    translation: 'What bone structure supports the reproductive organs?',
    options: ['la pelvis', 'la cadera', 'el hueso pélvico'],
    correctAnswer: 'la pelvis',
    hint: 'Pelvis - basin-shaped bone structure, "cadera" is hip',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_075',
    emoji: 'knee-joint.png',
    question: '¿Qué articulación dobla la pierna?',
    translation: 'What joint bends the leg?',
    options: ['la rodilla', 'la articulación de la rodilla', 'el menisco'],
    correctAnswer: 'la rodilla',
    hint: 'Knee - largest joint in body, "menisco" is knee cartilage',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_076',
    emoji: 'inhaler.png',
    question: '¿Qué dispositivo usan los asmáticos para respirar?',
    translation: 'What device do asthmatics use to breathe?',
    options: ['el inhalador', 'el aerosol', 'el broncodilatador'],
    correctAnswer: 'el inhalador',
    hint: 'Inhaler - delivers asthma medication to lungs, "puff" in English',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_077',
    emoji: 'oxygen-canister.png',
    question: '¿Qué contenedor lleva oxígeno médico?',
    translation: 'What container carries medical oxygen?',
    options: ['el tanque de oxígeno', 'el cilindro de oxígeno', 'la bombona de oxígeno'],
    correctAnswer: 'el tanque de oxígeno',
    hint: 'Oxygen tank - portable oxygen supply for respiratory patients',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_078',
    emoji: 'blood-pressure-meter.png',
    question: '¿Con qué mides la presión arterial?',
    translation: 'What do you measure blood pressure with?',
    options: ['el tensiómetro', 'el esfigmomanómetro', 'el medidor de presión'],
    correctAnswer: 'el tensiómetro',
    hint: 'Blood pressure meter - measures arterial pressure, "esfigmomanómetro" formal term',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_079',
    emoji: 'oximeter.png',
    question: '¿Con qué mides el oxígeno en la sangre?',
    translation: 'What do you measure oxygen in blood with?',
    options: ['el oxímetro', 'el pulsioxímetro', 'el medidor de oxígeno'],
    correctAnswer: 'el oxímetro',
    hint: 'Oximeter - measures blood oxygen saturation, clips on finger',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_080',
    emoji: 'glucometer.png',
    question: '¿Con qué miden los diabéticos su azúcar?',
    translation: 'What do diabetics measure their sugar with?',
    options: ['el glucómetro', 'el medidor de glucosa', 'el monitor de azúcar'],
    correctAnswer: 'el glucómetro',
    hint: 'Glucometer - measures blood sugar levels for diabetics',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_081',
    emoji: 'glucose-monitor.png',
    question: '¿Qué dispositivo monitorea el azúcar continuamente?',
    translation: 'What device monitors sugar continuously?',
    options: ['el monitor de glucosa continuo', 'el CGM', 'el sensor de glucosa'],
    correctAnswer: 'el monitor de glucosa continuo',
    hint: 'Continuous glucose monitor - wearable device for diabetics, CGM in English',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_082',
    emoji: 'otoscope.png',
    question: '¿Con qué examina el doctor tus oídos?',
    translation: 'What does the doctor examine your ears with?',
    options: ['el otoscopio', 'el auriscopo', 'el espéculo auricular'],
    correctAnswer: 'el otoscopio',
    hint: 'Otoscope - instrument to look inside ears, from Greek "ous" (ear)',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_083',
    emoji: 'hearing-aid.png',
    question: '¿Qué dispositivo ayuda a oír mejor?',
    translation: 'What device helps you hear better?',
    options: ['el audífono', 'el aparato auditivo', 'la prótesis auditiva'],
    correctAnswer: 'el audífono',
    hint: 'Hearing aid - amplifies sound for hearing impaired',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_084',
    emoji: 'mri-machine.png',
    question: '¿Qué máquina toma imágenes detalladas del cuerpo?',
    translation: 'What machine takes detailed images of the body?',
    options: ['la resonancia magnética', 'el MRI', 'el escáner de resonancia'],
    correctAnswer: 'la resonancia magnética',
    hint: 'MRI machine - magnetic resonance imaging, very detailed body scan',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_085',
    emoji: 'plaster-cast.png',
    question: '¿Qué ponen en un hueso roto?',
    translation: 'What do they put on a broken bone?',
    options: ['el yeso', 'la escayola', 'el vendaje de yeso'],
    correctAnswer: 'el yeso',
    hint: 'Plaster cast - immobilizes broken bone, "escayola" in Spain',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_086',
    emoji: 'intravenous-therapy.png',
    question: '¿Cómo se llama el tratamiento por vena?',
    translation: 'What is the treatment through vein called?',
    options: ['la terapia intravenosa', 'el suero', 'la vía intravenosa'],
    correctAnswer: 'la terapia intravenosa',
    hint: 'Intravenous therapy - IV delivers fluids and medicine through vein',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_087',
    emoji: 'booster-shot.png',
    question: '¿Qué vacuna adicional refuerza la protección?',
    translation: 'What additional vaccine reinforces protection?',
    options: ['la vacuna de refuerzo', 'la dosis de refuerzo', 'el booster'],
    correctAnswer: 'la vacuna de refuerzo',
    hint: 'Booster shot - additional vaccine dose to boost immunity',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_088',
    emoji: 'sterile-swab.png',
    question: '¿Con qué toman muestras para análisis?',
    translation: 'What do they take samples with for testing?',
    options: ['el hisopo', 'el bastoncillo', 'el aplicador estéril'],
    correctAnswer: 'el hisopo',
    hint: 'Sterile swab - cotton-tipped stick for collecting samples, "bastoncillo" also used',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_089',
    emoji: 'urine-sample.png',
    question: '¿Qué análisis usa orina?',
    translation: 'What test uses urine?',
    options: ['el análisis de orina', 'el examen de orina', 'el urinocultivo'],
    correctAnswer: 'el análisis de orina',
    hint: 'Urine sample - tests urine for diseases and conditions',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_090',
    emoji: 'tweezers.png',
    question: '¿Con qué quitan astillas o suturas?',
    translation: 'What do they remove splinters or stitches with?',
    options: ['las pinzas', 'las tenazas', 'el fórceps'],
    correctAnswer: 'las pinzas',
    hint: 'Tweezers - small gripping tool for removing splinters and stitches',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_091',
    emoji: 'throat-spray.png',
    question: '¿Qué usas para el dolor de garganta?',
    translation: 'What do you use for sore throat?',
    options: ['el spray para la garganta', 'el aerosol bucal', 'el medicamento para garganta'],
    correctAnswer: 'el spray para la garganta',
    hint: 'Throat spray - liquid medicine sprayed on sore throat',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_092',
    emoji: 'thermal-blanket.png',
    question: '¿Qué manta de emergencia retiene calor?',
    translation: 'What emergency blanket retains heat?',
    options: ['la manta térmica', 'la manta de emergencia', 'la manta isotérmica'],
    correctAnswer: 'la manta térmica',
    hint: 'Thermal blanket - reflective emergency blanket prevents hypothermia',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_093',
    emoji: 'muscle-strain.png',
    question: '¿Qué lesión ocurre cuando estiras demasiado un músculo?',
    translation: 'What injury occurs when you stretch a muscle too much?',
    options: ['la distensión muscular', 'el tirón muscular', 'el desgarro'],
    correctAnswer: 'la distensión muscular',
    hint: 'Muscle strain - pulled muscle from overstretching, "tirón" colloquial',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_094',
    emoji: 'cold-sore.png',
    question: '¿Qué llaga aparece en los labios?',
    translation: 'What sore appears on the lips?',
    options: ['el herpes labial', 'la calentura', 'la ampolla febril'],
    correctAnswer: 'el herpes labial',
    hint: 'Cold sore - viral blister on lips, "calentura" colloquial',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_095',
    emoji: 'blood-donation.png',
    question: '¿Qué acto voluntario salva vidas?',
    translation: 'What voluntary act saves lives?',
    options: ['la donación de sangre', 'la donación sanguínea', 'donar sangre'],
    correctAnswer: 'la donación de sangre',
    hint: 'Blood donation - voluntary giving of blood to help patients, can donate every 8-12 weeks',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_096',
    emoji: 'crutches.png',
    question: '¿Qué usas para caminar con una pierna lesionada?',
    translation: 'What do you use to walk with an injured leg?',
    options: ['las muletas', 'los bastones', 'las béquelas'],
    correctAnswer: 'las muletas',
    hint: 'Crutches - support walking with leg injury, help transfer weight from legs to upper body',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_097',
    emoji: 'ultrasound.png',
    question: '¿Qué prueba usa ondas sonoras para ver dentro del cuerpo?',
    translation: 'What test uses sound waves to see inside the body?',
    options: ['el ultrasonido', 'la ecografía', 'el sonograma'],
    correctAnswer: 'el ultrasonido',
    hint: 'Ultrasound - imaging using sound waves, commonly used during pregnancy, "ecografía" also used',
    points: 15,
    category: 'medical',
    difficulty: 'hard',
  },
  {
    id: 'medical_098',
    emoji: 'nasal-spray.png',
    question: '¿Qué usas para la congestión nasal?',
    translation: 'What do you use for nasal congestion?',
    options: ['el spray nasal', 'el aerosol nasal', 'el descongestionante nasal'],
    correctAnswer: 'el spray nasal',
    hint: 'Nasal spray - liquid medicine sprayed into nose, relieves congestion and allergies',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  },
  {
    id: 'medical_099',
    emoji: 'headache.png',
    question: '¿Qué dolor sientes en la cabeza?',
    translation: 'What pain do you feel in your head?',
    options: ['el dolor de cabeza', 'la cefalea', 'la jaqueca'],
    correctAnswer: 'el dolor de cabeza',
    hint: 'Headache - pain in the head, "cefalea" is medical term, "jaqueca" is migraine',
    points: 5,
    category: 'medical',
    difficulty: 'easy',
  },
  {
    id: 'medical_100',
    emoji: 'contact-lenses.png',
    question: '¿Qué usas en los ojos en lugar de gafas?',
    translation: 'What do you use in your eyes instead of glasses?',
    options: ['los lentes de contacto', 'las lentillas', 'los pupilentes'],
    correctAnswer: 'los lentes de contacto',
    hint: 'Contact lenses - worn directly on eye, "lentillas" in Spain, "pupilentes" in Latin America',
    points: 10,
    category: 'medical',
    difficulty: 'medium',
  }
];
