/**
 * Numbers, Colors & Time Category Questions
 * Category: numbers
 */

export const numbersQuestions = [
{
    id: 'numbers_001',
    emoji: '0️⃣',
    question: '¿Cómo se dice "zero"?',
    options: ['cero', 'nada', 'ninguno'],
    correctAnswer: 'cero',
    hint: 'Zero - from Arabic "sifr" (empty), like English "cipher", temperature 0°C is "cero grados"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_002',
    emoji: '1️⃣',
    question: '¿Cómo se dice "one"?',
    options: ['uno', 'un', 'una'],
    correctAnswer: 'uno',
    hint: 'One - becomes "un" before masculine nouns, "una" before feminine, from Latin "unus"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_003',
    emoji: '2️⃣',
    question: '¿Cómo se dice "two"?',
    options: ['dos', 'doce', 'veinte'],
    correctAnswer: 'dos',
    hint: 'Two - from Latin "duos", same root as "duo", "dual", "double", never changes form',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_004',
    emoji: '3️⃣',
    question: '¿Cómo se dice "three"?',
    options: ['tres', 'trece', 'treinta'],
    correctAnswer: 'tres',
    hint: 'Three - from Latin "tres", like "trio", "triple", "trinity", never changes form',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_005',
    emoji: '4️⃣',
    question: '¿Cómo se dice "four"?',
    options: ['cuatro', 'catorce', 'cuarenta'],
    correctAnswer: 'cuatro',
    hint: 'Four - from Latin "quattuor", think "quartet", "quadrant", never changes form',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_006',
    emoji: '5️⃣',
    question: '¿Cómo se dice "five"?',
    options: ['cinco', 'quince', 'cincuenta'],
    correctAnswer: 'cinco',
    hint: 'Five - from Latin "quinque", like "quintet", "quintuplets", never changes form',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_007',
    emoji: '6️⃣',
    question: '¿Cómo se dice "six"?',
    options: ['seis', 'dieciséis', 'sesenta'],
    correctAnswer: 'seis',
    hint: 'Six - from Latin "sex", like "sextet", "sextuple", never changes form',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_008',
    emoji: '7️⃣',
    question: '¿Cómo se dice "seven"?',
    options: ['siete', 'diecisiete', 'setenta'],
    correctAnswer: 'siete',
    hint: 'Seven - from Latin "septem", like "September" (7th month in Roman calendar), lucky number',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_009',
    emoji: '8️⃣',
    question: '¿Cómo se dice "eight"?',
    options: ['ocho', 'dieciocho', 'ochenta'],
    correctAnswer: 'ocho',
    hint: 'Eight - from Latin "octo", like "octopus" (8 legs), "October" (8th month in Roman calendar)',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_010',
    emoji: '9️⃣',
    question: '¿Cómo se dice "nine"?',
    options: ['nueve', 'diecinueve', 'noventa'],
    correctAnswer: 'nueve',
    hint: 'Nine - from Latin "novem", like "November" (9th month in Roman calendar), "novena" (9-day prayer)',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },

  // Numbers 10-20 (10 questions)
  {
    id: 'numbers_011',
    emoji: '🔟',
    question: '¿Cómo se dice "ten"?',
    options: ['diez', 'dieci', 'dies'],
    correctAnswer: 'diez',
    hint: 'Ten - from Latin "decem", like "decade", "decimal", "December" (10th Roman month)',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_012',
    emoji: '🔢',
    question: '¿Cómo se dice "eleven"?',
    options: ['once', 'uno', 'diez y uno'],
    correctAnswer: 'once',
    hint: 'Eleven - from Latin "undecim" (one + ten), starts teen pattern until 15',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_013',
    emoji: '🔢',
    question: '¿Cómo se dice "twelve"?',
    options: ['doce', 'dos', 'diez y dos'],
    correctAnswer: 'doce',
    hint: 'Twelve - from Latin "duodecim" (two + ten), "una docena" is a dozen',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_014',
    emoji: '🔢',
    question: '¿Cómo se dice "thirteen"?',
    options: ['trece', 'tres', 'diez y tres'],
    correctAnswer: 'trece',
    hint: 'Thirteen - from "tres" + "diez", unlucky number in some cultures',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_015',
    emoji: '🔢',
    question: '¿Cómo se dice "fourteen"?',
    options: ['catorce', 'cuatro', 'diez y cuatro'],
    correctAnswer: 'catorce',
    hint: 'Fourteen - from "cuatro" + "diez", last unique teen form',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_016',
    emoji: '🔢',
    question: '¿Cómo se dice "fifteen"?',
    options: ['quince', 'cinco', 'diez y cinco'],
    correctAnswer: 'quince',
    hint: 'Fifteen - from "cinco" + "diez", quinceañera celebrates girl\'s 15th birthday',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_017',
    emoji: '🔢',
    question: '¿Cómo se dice "sixteen"?',
    options: ['dieciséis', 'diez y seis', 'dieciseis'],
    correctAnswer: 'dieciséis',
    hint: 'Sixteen - "diez y seis" combined, pattern continues 16-19 with "dieci-"',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_018',
    emoji: '🔢',
    question: '¿Cómo se dice "seventeen"?',
    options: ['diecisiete', 'diez y siete', 'dieciseis'],
    correctAnswer: 'diecisiete',
    hint: 'Seventeen - literally "ten and seven", combined form of "diez y siete"',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_019',
    emoji: '🔢',
    question: '¿Cómo se dice "eighteen"?',
    options: ['dieciocho', 'diez y ocho', 'diecisiete'],
    correctAnswer: 'dieciocho',
    hint: 'Eighteen - adult age in most countries, "diez y ocho" combined',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_020',
    emoji: '🔢',
    question: '¿Cómo se dice "nineteen"?',
    options: ['diecinueve', 'diez y nueve', 'diecinuebe'],
    correctAnswer: 'diecinueve',
    hint: 'Nineteen - last teen number, "diez y nueve" combined, legal drinking age some places',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },

  // Larger Numbers (10 questions)
  {
    id: 'numbers_021',
    emoji: '🔢',
    question: '¿Cómo se dice "twenty"?',
    options: ['veinte', 'vente', 'beinte'],
    correctAnswer: 'veinte',
    hint: 'Twenty - from Latin "viginti", 21-29 combine as "veinti-" (veintiuno, veintidós)',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_022',
    emoji: '🔢',
    question: '¿Cómo se dice "thirty"?',
    options: ['treinta', 'trenta', 'treynta'],
    correctAnswer: 'treinta',
    hint: 'Thirty - from "tres" + "-inta" suffix, pattern for 30-90 (treinta y uno, treinta y dos)',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_023',
    emoji: '🔢',
    question: '¿Cómo se dice "forty"?',
    options: ['cuarenta', 'quarenta', 'cuatrenta'],
    correctAnswer: 'cuarenta',
    hint: 'Forty - from "cuatro" + "-enta", notice spelling change from cuatro',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_024',
    emoji: '🔢',
    question: '¿Cómo se dice "fifty"?',
    options: ['cincuenta', 'cinquenta', 'cincenta'],
    correctAnswer: 'cincuenta',
    hint: 'Fifty - from "cinco" + "-enta", half of 100 is "media centena"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_025',
    emoji: '🔢',
    question: '¿Cómo se dice "sixty"?',
    options: ['sesenta', 'seisenta', 'secenta'],
    correctAnswer: 'sesenta',
    hint: 'Sixty - from "seis" + "-enta", 60 minutes in hour, 60 seconds in minute',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_026',
    emoji: '🔢',
    question: '¿Cómo se dice "seventy"?',
    options: ['setenta', 'sietenta', 'septenta'],
    correctAnswer: 'setenta',
    hint: 'Seventy - from "siete" + "-enta", notice spelling change from siete',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_027',
    emoji: '🔢',
    question: '¿Cómo se dice "eighty"?',
    options: ['ochenta', 'ochocenta', 'ochoenta'],
    correctAnswer: 'ochenta',
    hint: 'Eighty - from "ocho" + "-enta", follows decade pattern',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_028',
    emoji: '🔢',
    question: '¿Cómo se dice "ninety"?',
    options: ['noventa', 'nueventa', 'noventay'],
    correctAnswer: 'noventa',
    hint: 'Ninety - from "nueve" + "-enta", last decade before 100',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_029',
    emoji: '💯',
    question: '¿Cómo se dice "one hundred"?',
    options: ['cien', 'ciento', 'cientos'],
    correctAnswer: 'cien',
    hint: 'One hundred - "cien" alone, "ciento" before other numbers (ciento uno), from Latin "centum"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_030',
    emoji: '🔢',
    question: '¿Cómo se dice "one thousand"?',
    options: ['mil', 'miles', 'mille'],
    correctAnswer: 'mil',
    hint: 'One thousand - from Latin "mille", millennium is 1000 years, never changes (dos mil, tres mil)',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },

  // Days of the Week (7 questions)
  {
    id: 'numbers_031',
    emoji: '📅',
    question: '¿Cómo se dice "Monday"?',
    options: ['lunes', 'el lunes', 'los lunes'],
    correctAnswer: 'lunes',
    hint: 'Monday - from Latin "dies Lunae" (day of Moon), always lowercase, masculine singular',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_032',
    emoji: '📅',
    question: '¿Cómo se dice "Tuesday"?',
    options: ['martes', 'el martes', 'los martes'],
    correctAnswer: 'martes',
    hint: 'Tuesday - from Mars (Roman god of war), "día de Marte", always lowercase',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_033',
    emoji: '📅',
    question: '¿Cómo se dice "Wednesday"?',
    options: ['miércoles', 'el miércoles', 'los miércoles'],
    correctAnswer: 'miércoles',
    hint: 'Wednesday - from Mercury (Roman god), middle of work week, "hump day"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_034',
    emoji: '📅',
    question: '¿Cómo se dice "Thursday"?',
    options: ['jueves', 'el jueves', 'los jueves'],
    correctAnswer: 'jueves',
    hint: 'Thursday - from Jove/Jupiter (Roman king of gods), fourth work day',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_035',
    emoji: '📅',
    question: '¿Cómo se dice "Friday"?',
    options: ['viernes', 'el viernes', 'los viernes'],
    correctAnswer: 'viernes',
    hint: 'Friday - from Venus (Roman goddess of love), TGIF! Last work day, "Viernes Santo" is Good Friday',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_036',
    emoji: '📅',
    question: '¿Cómo se dice "Saturday"?',
    options: ['sábado', 'el sábado', 'los sábados'],
    correctAnswer: 'sábado',
    hint: 'Saturday - from Latin "Sabbatum" (Sabbath), weekend day, party night',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_037',
    emoji: '📅',
    question: '¿Cómo se dice "Sunday"?',
    options: ['domingo', 'el domingo', 'los domingos'],
    correctAnswer: 'domingo',
    hint: 'Sunday - from Latin "dies Dominicus" (Lord\'s day), rest day, family day in Spanish culture',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },

  // Months of the Year (12 questions)
  {
    id: 'numbers_038',
    emoji: '📆',
    question: '¿Cómo se dice "January"?',
    options: ['enero', 'el enero', 'januario'],
    correctAnswer: 'enero',
    hint: 'January - from Janus (Roman god of beginnings), New Year month, always lowercase in Spanish',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_039',
    emoji: '📆',
    question: '¿Cómo se dice "February"?',
    options: ['febrero', 'el febrero', 'februario'],
    correctAnswer: 'febrero',
    hint: 'February - shortest month (28/29 days), from Roman purification festival "Februa"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_040',
    emoji: '📆',
    question: '¿Cómo se dice "March"?',
    options: ['marzo', 'el marzo', 'marcho'],
    correctAnswer: 'marzo',
    hint: 'March - from Mars (god of war), spring begins, "Martes y trece" (Tuesday 13th) unlucky in Spanish',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_041',
    emoji: '📆',
    question: '¿Cómo se dice "April"?',
    options: ['abril', 'el abril', 'abrel'],
    correctAnswer: 'abril',
    hint: 'April - possibly from Latin "aperire" (to open) for spring flowers, "Día de los Inocentes" April 1st',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_042',
    emoji: '📆',
    question: '¿Cómo se dice "May"?',
    options: ['mayo', 'el mayo', 'mai'],
    correctAnswer: 'mayo',
    hint: 'May - from Maia (Roman goddess), "Cinco de Mayo" celebrated, spring/summer month',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_043',
    emoji: '📆',
    question: '¿Cómo se dice "June"?',
    options: ['junio', 'el junio', 'junho'],
    correctAnswer: 'junio',
    hint: 'June - from Juno (Roman goddess, protector of marriage), popular wedding month',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_044',
    emoji: '📆',
    question: '¿Cómo se dice "July"?',
    options: ['julio', 'el julio', 'jullio'],
    correctAnswer: 'julio',
    hint: 'July - named after Julius Caesar, summer month, vacation season in Spain',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_045',
    emoji: '📆',
    question: '¿Cómo se dice "August"?',
    options: ['agosto', 'el agosto', 'augusto'],
    correctAnswer: 'agosto',
    hint: 'August - named after Emperor Augustus, peak summer, "agosto" also means harvest time',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_046',
    emoji: '📆',
    question: '¿Cómo se dice "September"?',
    options: ['septiembre', 'setiembre', 'el septiembre'],
    correctAnswer: 'septiembre',
    hint: 'September - from Latin "septem" (seven, 7th in Roman calendar), back to school month',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_047',
    emoji: '📆',
    question: '¿Cómo se dice "October"?',
    options: ['octubre', 'otubre', 'el octubre'],
    correctAnswer: 'octubre',
    hint: 'October - from Latin "octo" (eight, 8th Roman month), "Día de la Raza" October 12',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_048',
    emoji: '📆',
    question: '¿Cómo se dice "November"?',
    options: ['noviembre', 'nobiembre', 'el noviembre'],
    correctAnswer: 'noviembre',
    hint: 'November - from Latin "novem" (nine, 9th Roman month), "Día de Muertos" November 1-2',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_049',
    emoji: '📆',
    question: '¿Cómo se dice "December"?',
    options: ['diciembre', 'disiembre', 'el diciembre'],
    correctAnswer: 'diciembre',
    hint: 'December - from Latin "decem" (ten, 10th Roman month), Christmas "Navidad" December 25',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },

  // Time Expressions (11 questions)
  {
    id: 'numbers_050',
    emoji: '⏰',
    question: '¿Cómo se dice "hour"?',
    options: ['hora', 'la hora', 'horas'],
    correctAnswer: 'hora',
    hint: 'Hour - 60 minutes, from Latin "hora", "¿qué hora es?" asks the time',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_051',
    emoji: '⏱️',
    question: '¿Cómo se dice "minute"?',
    options: ['minuto', 'el minuto', 'minutos'],
    correctAnswer: 'minuto',
    hint: 'Minute - 60 seconds, from Latin "minutus" (small), "un minuto" is wait a minute',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_052',
    emoji: '⏱️',
    question: '¿Cómo se dice "second"?',
    options: ['segundo', 'el segundo', 'segundos'],
    correctAnswer: 'segundo',
    hint: 'Second - smallest time unit, also means "second" (2nd), dual meaning in Spanish',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_053',
    emoji: '🌅',
    question: '¿Cómo se dice "morning"?',
    options: ['mañana', 'la mañana', 'mañanita'],
    correctAnswer: 'mañana',
    hint: 'Morning - before noon, also means "tomorrow", "de la mañana" for AM time',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_054',
    emoji: '☀️',
    question: '¿Cómo se dice "afternoon"?',
    options: ['tarde', 'la tarde', 'tardecita'],
    correctAnswer: 'tarde',
    hint: 'Afternoon - after noon until sunset, also means "late", "de la tarde" for PM time',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_055',
    emoji: '🌙',
    question: '¿Cómo se dice "night"?',
    options: ['noche', 'la noche', 'nochecita'],
    correctAnswer: 'noche',
    hint: 'Night - after sunset, from Latin "nox", "de la noche" for evening time, "medianoche" is midnight',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_056',
    emoji: '📅',
    question: '¿Cómo se dice "today"?',
    options: ['hoy', 'hoY', 'oy'],
    correctAnswer: 'hoy',
    hint: 'Today - this day, from Latin "hodie", "hoy en día" means nowadays',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_057',
    emoji: '📅',
    question: '¿Cómo se dice "yesterday"?',
    options: ['ayer', 'anteayer', 'ayér'],
    correctAnswer: 'ayer',
    hint: 'Yesterday - day before today, "anteayer" is day before yesterday (two days ago)',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_058',
    emoji: '📅',
    question: '¿Cómo se dice "tomorrow"?',
    options: ['mañana', 'la mañana', 'mañanita'],
    correctAnswer: 'mañana',
    hint: 'Tomorrow - day after today, also means "morning", context determines meaning',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_059',
    emoji: '📅',
    question: '¿Cómo se dice "week"?',
    options: ['semana', 'la semana', 'semanita'],
    correctAnswer: 'semana',
    hint: 'Week - seven days, from Latin "septimana" (seven), "fin de semana" is weekend',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_060',
    emoji: '📆',
    question: '¿Cómo se dice "year"?',
    options: ['año', 'el año', 'añito'],
    correctAnswer: 'año',
    hint: 'Year - twelve months, 365 days, from Latin "annus", "Año Nuevo" is New Year',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },

  // Colors (15 questions)
  {
    id: 'numbers_061',
    emoji: '🔴',
    question: '¿Cómo se dice "red"?',
    options: ['rojo', 'roja', 'rojos'],
    correctAnswer: 'rojo',
    hint: 'Red - changes to "roja" for feminine nouns, from Latin "russus", color of passion and danger',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_062',
    emoji: '🔵',
    question: '¿Cómo se dice "blue"?',
    options: ['azul', 'azules', 'azulado'],
    correctAnswer: 'azul',
    hint: 'Blue - from Arabic "lazaward" (lapis lazuli stone), no gender change, sky and ocean color',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_063',
    emoji: '🟢',
    question: '¿Cómo se dice "green"?',
    options: ['verde', 'verdes', 'verdoso'],
    correctAnswer: 'verde',
    hint: 'Green - no gender change, also means "unripe" (fruta verde), nature and plant color',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_064',
    emoji: '🟡',
    question: '¿Cómo se dice "yellow"?',
    options: ['amarillo', 'amarilla', 'amarillos'],
    correctAnswer: 'amarillo',
    hint: 'Yellow - changes to "amarilla" for feminine, from Arabic "al-mariyya", sun color',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_065',
    emoji: '🟠',
    question: '¿Cómo se dice "orange"?',
    options: ['naranja', 'anaranjado', 'naranjas'],
    correctAnswer: 'naranja',
    hint: 'Orange - same word as fruit, no gender change (invariable), from Sanskrit through Arabic',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_066',
    emoji: '🟣',
    question: '¿Cómo se dice "purple"?',
    options: ['morado', 'púrpura', 'violeta'],
    correctAnswer: 'morado',
    hint: 'Purple - changes to "morada", also "púrpura" or "violeta", royal color historically',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_067',
    emoji: '🩷',
    question: '¿Cómo se dice "pink"?',
    options: ['rosa', 'rosado', 'rosada'],
    correctAnswer: 'rosa',
    hint: 'Pink - same word as "rose" flower, no gender change, light red color',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_068',
    emoji: '⚫',
    question: '¿Cómo se dice "black"?',
    options: ['negro', 'negra', 'negros'],
    correctAnswer: 'negro',
    hint: 'Black - changes to "negra" for feminine, from Latin "niger", absence of light',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_069',
    emoji: '⚪',
    question: '¿Cómo se dice "white"?',
    options: ['blanco', 'blanca', 'blancos'],
    correctAnswer: 'blanco',
    hint: 'White - changes to "blanca", from Germanic "blank", all colors combined, purity symbol',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_070',
    emoji: '🩶',
    question: '¿Cómo se dice "gray"?',
    options: ['gris', 'grises', 'grisáceo'],
    correctAnswer: 'gris',
    hint: 'Gray - from French "gris", no gender change, mixture of black and white',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_071',
    emoji: '🟤',
    question: '¿Cómo se dice "brown"?',
    options: ['marrón', 'café', 'pardo'],
    correctAnswer: 'marrón',
    hint: 'Brown - from French "marron" (chestnut), Latin America often uses "café", earth color',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_072',
    emoji: '🎨',
    question: '¿Cómo se dice "color"?',
    options: ['color', 'el color', 'los colores'],
    correctAnswer: 'color',
    hint: 'Color - masculine noun, same spelling as English, from Latin "color"',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'numbers_073',
    emoji: '🌈',
    question: '¿Cómo se dice "rainbow"?',
    options: ['arcoíris', 'arco iris', 'el arcoíris'],
    correctAnswer: 'arcoíris',
    hint: 'Rainbow - literally "arc of iris", seven colors spectrum, appears after rain',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_074',
    emoji: '💡',
    question: '¿Cómo se dice "light" (color)?',
    options: ['claro', 'oscuro', 'brillante'],
    correctAnswer: 'claro',
    hint: 'Light - pale color shade, "azul claro" (light blue), also means "clear" or "of course"',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_075',
    emoji: '🌑',
    question: '¿Cómo se dice "dark" (color)?',
    options: ['oscuro', 'claro', 'negro'],
    correctAnswer: 'oscuro',
    hint: 'Dark - deep color shade, "verde oscuro" (dark green), opposite of claro, from Latin "obscurus"',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_076',
    emoji: '🕘',
    question: '¿Qué hora es?',
    options: ['las nueve', 'son las nueve', 'nueve en punto'],
    correctAnswer: 'las nueve',
    hint: '9 o\'clock - "las nueve" or "son las nueve" (it\'s nine), "en punto" means sharp/exactly',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_077',
    emoji: '🕛',
    question: '¿Qué hora es?',
    options: ['las doce', 'son las doce', 'mediodía'],
    correctAnswer: 'las doce',
    hint: '12 o\'clock - "las doce" or "son las doce" (it\'s twelve), "mediodía" is noon, "medianoche" is midnight',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_078',
    emoji: '🕒',
    question: '¿Qué hora es?',
    options: ['las tres', 'son las tres', 'tres en punto'],
    correctAnswer: 'las tres',
    hint: '3 o\'clock - "las tres" or "son las tres" (it\'s three), afternoon time in most contexts',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'numbers_079',
    emoji: '🕕',
    question: '¿Qué hora es?',
    options: ['las seis', 'son las seis', 'seis en punto'],
    correctAnswer: 'las seis',
    hint: '6 o\'clock - "las seis" or "son las seis" (it\'s six), can be morning or evening depending on context',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
  },

  // GRAMMAR CATEGORY - 50 questions
  // Subject Pronouns (8 questions)
  {
    id: 'grammar_1',
    emoji: '📝',
    question: '¿Cómo se dice "I" (subject pronoun)?',
    options: ['yo', 'yó', 'io'],
    correctAnswer: 'yo',
    hint: 'I - first person singular, from Latin "ego", often omitted since verb shows who (hablo = I speak)',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_2',
    emoji: '📝',
    question: '¿Cómo se dice "you" (informal)?',
    options: ['tú', 'tu', 'usted'],
    correctAnswer: 'tú',
    hint: 'You - informal singular for friends/family, from Latin "tu", has accent to distinguish from "tu" (your)',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_3',
    emoji: '📝',
    question: '¿Cómo se dice "he"?',
    options: ['él', 'el', 'ella'],
    correctAnswer: 'él',
    hint: 'He - masculine third person, has accent to distinguish from "el" (the), from Latin "ille"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_4',
    emoji: '📝',
    question: '¿Cómo se dice "she"?',
    options: ['ella', 'élla', 'él'],
    correctAnswer: 'ella',
    hint: 'She - feminine third person, no accent needed, from Latin "illa"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_5',
    emoji: '📝',
    question: '¿Cómo se dice "we"?',
    options: ['nosotros', 'nosotras', 'nos'],
    correctAnswer: 'nosotros',
    hint: 'We - first person plural masculine/mixed, "nosotras" all feminine, from "nos" (us) + "otros" (others)',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_6',
    emoji: '📝',
    question: '¿Cómo se dice "they" (masculine)?',
    options: ['ellos', 'ellas', 'elles'],
    correctAnswer: 'ellos',
    hint: 'They - masculine/mixed group, one male makes group masculine, from Latin "illos"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_7',
    emoji: '📝',
    question: '¿Cómo se dice "they" (feminine)?',
    options: ['ellas', 'ellos', 'elles'],
    correctAnswer: 'ellas',
    hint: 'They - all feminine group only, from Latin "illas", rarely used since groups often mixed',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_8',
    emoji: '📝',
    question: '¿Cómo se dice "you" (formal)?',
    options: ['usted', 'ustéd', 'ustedes'],
    correctAnswer: 'usted',
    hint: 'You - formal singular from "vuestra merced" (your mercy), abbreviated Ud., uses 3rd person verbs',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Verb "SER" (to be) - Present Tense (7 questions)
  {
    id: 'grammar_9',
    emoji: '✍️',
    question: 'Yo ___ estudiante. (to be)',
    options: ['soy', 'estoy', 'so'],
    correctAnswer: 'soy',
    hint: 'I am - SER for identity/profession, irregular "soy" (not "so"), permanent characteristics',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_10',
    emoji: '✍️',
    question: 'Tú ___ inteligente. (to be)',
    options: ['eres', 'estás', 'erés'],
    correctAnswer: 'eres',
    hint: 'You are - SER for characteristics/personality, irregular form, permanent traits',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_11',
    emoji: '✍️',
    question: 'Él ___ médico. (to be)',
    options: ['es', 'está', 'eres'],
    correctAnswer: 'es',
    hint: 'He is - SER for profession (no article "a/an" in Spanish), permanent occupation',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_12',
    emoji: '✍️',
    question: 'Ella ___ profesora. (to be)',
    options: ['es', 'está', 'son'],
    correctAnswer: 'es',
    hint: 'She is - same form for él/ella/usted all use "es", SER for occupation',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_13',
    emoji: '✍️',
    question: 'Nosotros ___ amigos. (to be)',
    options: ['somos', 'estamos', 'semos'],
    correctAnswer: 'somos',
    hint: 'We are - SER for relationships, irregular conjugation from Latin "sumus"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_14',
    emoji: '✍️',
    question: 'Ellos ___ estudiantes. (to be)',
    options: ['son', 'están', 'es'],
    correctAnswer: 'son',
    hint: 'They are - SER for identity, irregular form, same for ellos/ellas/ustedes',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_15',
    emoji: '✍️',
    question: 'Usted ___ muy amable. (to be)',
    options: ['es', 'está', 'eres'],
    correctAnswer: 'es',
    hint: 'You are (formal) - uses 3rd person "es", SER for personality traits (permanent)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Verb "ESTAR" (to be) - Present Tense (7 questions)
  {
    id: 'grammar_16',
    emoji: '✍️',
    question: 'Yo ___ en casa. (to be/location)',
    options: ['estoy', 'soy', 'esto'],
    correctAnswer: 'estoy',
    hint: 'I am - ESTAR for location, irregular "estoy", temporary states and positions',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_17',
    emoji: '✍️',
    question: 'Tú ___ cansado. (to be/condition)',
    options: ['estás', 'eres', 'estas'],
    correctAnswer: 'estás',
    hint: 'You are - ESTAR for temporary condition/emotion, "cansado" is temporary state not personality',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_18',
    emoji: '✍️',
    question: 'Él ___ contento. (to be/emotion)',
    options: ['está', 'es', 'ésta'],
    correctAnswer: 'está',
    hint: 'He is - ESTAR for emotions (temporary), "contento" is current feeling not permanent trait',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_19',
    emoji: '✍️',
    question: 'Nosotros ___ aquí. (to be/location)',
    options: ['estamos', 'somos', 'estemos'],
    correctAnswer: 'estamos',
    hint: 'We are - ESTAR for location/position, "aquí" (here) indicates place',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_20',
    emoji: '✍️',
    question: 'Ellos ___ ocupados. (to be/condition)',
    options: ['están', 'son', 'estan'],
    correctAnswer: 'están',
    hint: 'They are - ESTAR for temporary condition, "ocupados" (busy) is current state',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_21',
    emoji: '✍️',
    question: '¿Dónde ___ el banco? (to be/location)',
    options: ['está', 'es', 'ésta'],
    correctAnswer: 'está',
    hint: 'Where is - ESTAR for location even if permanent, "dónde" (where) triggers ESTAR',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_22',
    emoji: '✍️',
    question: 'La comida ___ caliente. (to be/condition)',
    options: ['está', 'es', 'ésta'],
    correctAnswer: 'está',
    hint: 'Food is - ESTAR for temporary condition, "caliente" (hot) is current temperature not permanent',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },

  // Regular -AR Verbs (5 questions)
  {
    id: 'grammar_23',
    emoji: '📖',
    question: 'Yo ___ español. (hablar - to speak)',
    options: ['hablo', 'hablé', 'hable'],
    correctAnswer: 'hablo',
    hint: 'I speak - -AR verb: remove -ar, add -o for yo, most common verb type in Spanish',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_24',
    emoji: '📖',
    question: 'Tú ___ música. (escuchar - to listen)',
    options: ['escuchas', 'escucha', 'escuchás'],
    correctAnswer: 'escuchas',
    hint: 'You listen - -AR verb: remove -ar, add -as for tú, regular pattern',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_25',
    emoji: '📖',
    question: 'Ella ___ la casa. (limpiar - to clean)',
    options: ['limpia', 'limpio', 'limpía'],
    correctAnswer: 'limpia',
    hint: 'She cleans - -AR verb: remove -ar, add -a for él/ella/usted',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_26',
    emoji: '📖',
    question: 'Nosotros ___ en el parque. (caminar - to walk)',
    options: ['caminamos', 'caminemos', 'caminábamos'],
    correctAnswer: 'caminamos',
    hint: 'We walk - -AR verb: remove -ar, add -amos for nosotros, consistent ending',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_27',
    emoji: '📖',
    question: 'Ellos ___ temprano. (trabajar - to work)',
    options: ['trabajan', 'trabaja', 'trabajen'],
    correctAnswer: 'trabajan',
    hint: 'They work - -AR verb: remove -ar, add -an for ellos/ellas/ustedes',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Regular -ER Verbs (3 questions)
  {
    id: 'grammar_28',
    emoji: '📖',
    question: 'Yo ___ mucho. (comer - to eat)',
    options: ['como', 'comó', 'come'],
    correctAnswer: 'como',
    hint: 'I eat - -ER verb: remove -er, add -o for yo, second most common verb type',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_29',
    emoji: '📖',
    question: 'Tú ___ libros. (leer - to read)',
    options: ['lees', 'leés', 'lee'],
    correctAnswer: 'lees',
    hint: 'You read - -ER verb: remove -er, add -es for tú, notice double "e"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_30',
    emoji: '📖',
    question: 'Nosotros ___ café. (beber - to drink)',
    options: ['bebemos', 'bebamos', 'bebíamos'],
    correctAnswer: 'bebemos',
    hint: 'We drink - -ER verb: remove -er, add -emos for nosotros',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Regular -IR Verbs (3 questions)
  {
    id: 'grammar_31',
    emoji: '📖',
    question: 'Yo ___ en Madrid. (vivir - to live)',
    options: ['vivo', 'vivó', 'vive'],
    correctAnswer: 'vivo',
    hint: 'I live - -IR verb: remove -ir, add -o for yo, least common but important verb type',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_32',
    emoji: '📖',
    question: 'Tú ___ la puerta. (abrir - to open)',
    options: ['abres', 'abrís', 'abre'],
    correctAnswer: 'abres',
    hint: 'You open - -IR verb: remove -ir, add -es for tú (same as -ER for tú)',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_33',
    emoji: '📖',
    question: 'Ellos ___ cartas. (escribir - to write)',
    options: ['escriben', 'escriban', 'escribieron'],
    correctAnswer: 'escriben',
    hint: 'They write - -IR verb: remove -ir, add -en for ellos/ellas/ustedes',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Articles & Gender (6 questions)
  {
    id: 'grammar_34',
    emoji: '🔤',
    question: '___ libro (the book - masculine)',
    options: ['el', 'él', 'la'],
    correctAnswer: 'el',
    hint: 'The - masculine singular definite article, most words ending in -o are masculine',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_35',
    emoji: '🔤',
    question: '___ casa (the house - feminine)',
    options: ['la', 'el', 'él'],
    correctAnswer: 'la',
    hint: 'The - feminine singular definite article, most words ending in -a are feminine',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_36',
    emoji: '🔤',
    question: '___ libros (the books - masculine plural)',
    options: ['los', 'les', 'las'],
    correctAnswer: 'los',
    hint: 'The - masculine plural definite article, add -s to singular noun ending in vowel',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_37',
    emoji: '🔤',
    question: '___ casas (the houses - feminine plural)',
    options: ['las', 'los', 'les'],
    correctAnswer: 'las',
    hint: 'The - feminine plural definite article, article must match noun gender and number',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_38',
    emoji: '🔤',
    question: '___ manzana (an apple - indefinite)',
    options: ['una', 'un', 'uno'],
    correctAnswer: 'una',
    hint: 'A/An - feminine indefinite article, "manzana" ends in -a (usually feminine)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_39',
    emoji: '🔤',
    question: '___ perro (a dog - indefinite)',
    options: ['un', 'uno', 'una'],
    correctAnswer: 'un',
    hint: 'A/An - masculine indefinite article, from "uno" (one), drops -o before noun',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // Question Words (6 questions)
  {
    id: 'grammar_40',
    emoji: '❓',
    question: '¿___ te llamas? (What is your name?)',
    options: ['cómo', 'como', 'cómo'],
    correctAnswer: 'cómo',
    hint: 'How/What - literally "how do you call yourself", has accent in questions, from Latin "quomodo"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_41',
    emoji: '❓',
    question: '¿___ estás? (Where are you?)',
    options: ['dónde', 'donde', 'dóndé'],
    correctAnswer: 'dónde',
    hint: 'Where - has accent in questions, from Latin "de unde" (from where)',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_42',
    emoji: '❓',
    question: '¿___ años tienes? (How many years do you have?)',
    options: ['cuántos', 'cuantos', 'cuántas'],
    correctAnswer: 'cuántos',
    hint: 'How many - masculine plural form, "cuánta/cuántas" for feminine, has accent in questions',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_43',
    emoji: '❓',
    question: '¿___ es tu cumpleaños? (When is your birthday?)',
    options: ['cuándo', 'cuando', 'cuándó'],
    correctAnswer: 'cuándo',
    hint: 'When - asks about time, has accent in questions, from Latin "quando"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_44',
    emoji: '❓',
    question: '¿___ es esto? (What is this?)',
    options: ['qué', 'que', 'quién'],
    correctAnswer: 'qué',
    hint: 'What - asks for definition/identity, has accent in questions, from Latin "quid"',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_45',
    emoji: '❓',
    question: '¿___ es él? (Who is he?)',
    options: ['quién', 'quien', 'qué'],
    correctAnswer: 'quién',
    hint: 'Who - asks about people, has accent in questions, "quiénes" for plural',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },

  // Possessive Adjectives (5 questions)
  {
    id: 'grammar_46',
    emoji: '✋',
    question: '___ libro (my book)',
    options: ['mi', 'mí', 'mis'],
    correctAnswer: 'mi',
    hint: 'My - possessive adjective, no accent (unlike "mí" = me), same for masculine/feminine',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_47',
    emoji: '✋',
    question: '___ casa (your house - informal)',
    options: ['tu', 'tú', 'tus'],
    correctAnswer: 'tu',
    hint: 'Your - informal possessive, no accent (unlike "tú" = you), same for masculine/feminine',
    points: 5,
    category: 'grammar',
    difficulty: 'easy',
  },
  {
    id: 'grammar_48',
    emoji: '✋',
    question: '___ amigos (our friends)',
    options: ['nuestros', 'nuestro', 'nuestra'],
    correctAnswer: 'nuestros',
    hint: 'Our - masculine plural, changes to "nuestra/nuestras" for feminine, from "nos" (us)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_49',
    emoji: '✋',
    question: '___ perro (his/her dog)',
    options: ['su', 'sú', 'sus'],
    correctAnswer: 'su',
    hint: 'His/her/their/your(formal) - ambiguous, same for all third person, clarify with "de él/ella"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_50',
    emoji: '✋',
    question: '___ libros (my books - plural)',
    options: ['mis', 'mi', 'mí'],
    correctAnswer: 'mis',
    hint: 'My - plural form, add -s to "mi" for plural nouns, same for masculine/feminine',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // PRETERITE TENSE (Past - Completed Actions) - 10 questions
  {
    id: 'grammar_51',
    emoji: '⏪',
    question: 'Ayer yo ___ en el restaurante. (comer - to eat)',
    options: ['comí', 'como', 'comía'],
    correctAnswer: 'comí',
    hint: 'I ate - Preterite for completed action, -ER verb: remove -er, add -í for yo',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_52',
    emoji: '⏪',
    question: 'Tú ___ con María anoche. (hablar - to speak)',
    options: ['hablaste', 'hablas', 'hablabas'],
    correctAnswer: 'hablaste',
    hint: 'You spoke - Preterite completed action, -AR verb: add -aste for tú, "anoche" = last night',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_53',
    emoji: '⏪',
    question: 'Ella ___ a España el año pasado. (viajar - to travel)',
    options: ['viajó', 'viaja', 'viajaba'],
    correctAnswer: 'viajó',
    hint: 'She traveled - Preterite completed action, -AR verb: add -ó for él/ella, accent on last syllable',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_54',
    emoji: '⏪',
    question: 'Nosotros ___ la película. (ver - to see/watch)',
    options: ['vimos', 'vemos', 'veíamos'],
    correctAnswer: 'vimos',
    hint: 'We saw - Preterite completed, -ER verb: add -imos for nosotros, irregular stem "v-"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_55',
    emoji: '⏪',
    question: 'Ellos ___ temprano esta mañana. (salir - to leave)',
    options: ['salieron', 'salen', 'salían'],
    correctAnswer: 'salieron',
    hint: 'They left - Preterite completed, -IR verb: add -ieron for ellos, "esta mañana" = this morning',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_56',
    emoji: '⏪',
    question: 'Ayer yo ___ al médico. (ir - to go)',
    options: ['fui', 'voy', 'iba'],
    correctAnswer: 'fui',
    hint: 'I went - Irregular preterite! "ir" and "ser" share same forms, context shows meaning',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_57',
    emoji: '⏪',
    question: 'Tú ___ tarde a la reunión. (llegar - to arrive)',
    options: ['llegaste', 'llegas', 'llegabas'],
    correctAnswer: 'llegaste',
    hint: 'You arrived - Preterite completed action, regular -AR pattern for tú',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_58',
    emoji: '⏪',
    question: 'Él ___ un regalo. (traer - to bring)',
    options: ['trajo', 'trae', 'traía'],
    correctAnswer: 'trajo',
    hint: 'He brought - Irregular preterite stem "traj-", add -o for él (not -ó!), no accent',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_59',
    emoji: '⏪',
    question: 'Nosotros ___ en ese hotel. (estar - to be)',
    options: ['estuvimos', 'estamos', 'estábamos'],
    correctAnswer: 'estuvimos',
    hint: 'We were - Irregular preterite "estuv-" stem, completed stay/visit',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_60',
    emoji: '⏪',
    question: 'Ellos no ___ la verdad. (decir - to say/tell)',
    options: ['dijeron', 'dicen', 'decían'],
    correctAnswer: 'dijeron',
    hint: 'They didn\'t say - Irregular "dij-" stem, add -eron (not -ieron!), spelling change',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },

  // IMPERFECT TENSE (Past - Ongoing/Habitual) - 10 questions
  {
    id: 'grammar_61',
    emoji: '🔄',
    question: 'Cuando era niño, yo ___ mucho. (jugar - to play)',
    options: ['jugaba', 'jugué', 'juego'],
    correctAnswer: 'jugaba',
    hint: 'I used to play - Imperfect for habitual past, -AR verb: add -aba for yo, "cuando era niño" = when I was a child',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_62',
    emoji: '🔄',
    question: 'Tú siempre ___ café por la mañana. (beber - to drink)',
    options: ['bebías', 'bebiste', 'bebes'],
    correctAnswer: 'bebías',
    hint: 'You used to drink - Imperfect habitual, -ER verb: add -ías for tú, "siempre" = always (habitual)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_63',
    emoji: '🔄',
    question: 'Ella ___ en Madrid antes. (vivir - to live)',
    options: ['vivía', 'vivió', 'vive'],
    correctAnswer: 'vivía',
    hint: 'She used to live - Imperfect ongoing state, -IR verb: add -ía for ella, "antes" = before',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_64',
    emoji: '🔄',
    question: 'Nosotros ___ al parque cada domingo. (ir - to go)',
    options: ['íbamos', 'fuimos', 'vamos'],
    correctAnswer: 'íbamos',
    hint: 'We used to go - Irregular imperfect of "ir", "cada domingo" = every Sunday (habitual)',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_65',
    emoji: '🔄',
    question: 'Ellos ___ muy felices juntos. (ser - to be)',
    options: ['eran', 'fueron', 'son'],
    correctAnswer: 'eran',
    hint: 'They were - Irregular imperfect of "ser", describes ongoing state in past',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_66',
    emoji: '🔄',
    question: 'Mientras yo ___, sonó el teléfono. (cocinar - to cook)',
    options: ['cocinaba', 'cociné', 'cocino'],
    correctAnswer: 'cocinaba',
    hint: 'I was cooking - Imperfect for ongoing action interrupted, "mientras" = while',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_67',
    emoji: '🔄',
    question: 'Tú ___ la televisión cuando llegué. (ver - to watch)',
    options: ['veías', 'viste', 'ves'],
    correctAnswer: 'veías',
    hint: 'You were watching - Imperfect ongoing action, background action when something happened',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_68',
    emoji: '🔄',
    question: '¿Qué hora ___ cuando saliste? (ser - to be)',
    options: ['era', 'fue', 'es'],
    correctAnswer: 'era',
    hint: 'What time was it - Imperfect for telling time in past, always use "ser" imperfect',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_69',
    emoji: '🔄',
    question: 'Nosotros ___ mucho cuando éramos jóvenes. (bailar - to dance)',
    options: ['bailábamos', 'bailamos', 'bailamos'],
    correctAnswer: 'bailábamos',
    hint: 'We used to dance - Imperfect habitual, "cuando éramos jóvenes" = when we were young',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_70',
    emoji: '🔄',
    question: 'El niño ___ cuando lo encontraron. (llorar - to cry)',
    options: ['lloraba', 'lloró', 'llora'],
    correctAnswer: 'lloraba',
    hint: 'The child was crying - Imperfect ongoing action as background to "encontraron" (found)',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // FUTURE TENSE - 10 questions
  {
    id: 'grammar_71',
    emoji: '⏩',
    question: 'Mañana yo ___ con mi familia. (comer - to eat)',
    options: ['comeré', 'como', 'comí'],
    correctAnswer: 'comeré',
    hint: 'I will eat - Future: keep infinitive + -é for yo, "mañana" = tomorrow',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_72',
    emoji: '⏩',
    question: 'Tú ___ español muy bien. (hablar - to speak)',
    options: ['hablarás', 'hablas', 'hablaste'],
    correctAnswer: 'hablarás',
    hint: 'You will speak - Future: infinitive + -ás for tú, accent on last syllable',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_73',
    emoji: '⏩',
    question: 'Ella ___ en París el próximo año. (vivir - to live)',
    options: ['vivirá', 'vive', 'vivió'],
    correctAnswer: 'vivirá',
    hint: 'She will live - Future: infinitive + -á for ella, "el próximo año" = next year',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_74',
    emoji: '⏩',
    question: 'Nosotros ___ mañana. (salir - to leave)',
    options: ['saldremos', 'salimos', 'salíamos'],
    correctAnswer: 'saldremos',
    hint: 'We will leave - Irregular future stem "saldr-" + -emos, drops "i" from infinitive',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_75',
    emoji: '⏩',
    question: 'Ellos ___ la verdad. (decir - to say/tell)',
    options: ['dirán', 'dicen', 'dijeron'],
    correctAnswer: 'dirán',
    hint: 'They will say - Irregular future stem "dir-" (not "decir-") + -án for ellos',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_76',
    emoji: '⏩',
    question: '¿Qué ___ tú este fin de semana? (hacer - to do)',
    options: ['harás', 'haces', 'hiciste'],
    correctAnswer: 'harás',
    hint: 'What will you do - Irregular future stem "har-" (not "hacer-"), "fin de semana" = weekend',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_77',
    emoji: '⏩',
    question: 'Yo ___ dinero para el viaje. (tener - to have)',
    options: ['tendré', 'tengo', 'tuve'],
    correctAnswer: 'tendré',
    hint: 'I will have - Irregular future stem "tendr-" (not "tener-") + -é',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_78',
    emoji: '⏩',
    question: 'Nosotros ___ a tiempo. (llegar - to arrive)',
    options: ['llegaremos', 'llegamos', 'llegábamos'],
    correctAnswer: 'llegaremos',
    hint: 'We will arrive - Regular future: infinitive + -emos for nosotros',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_79',
    emoji: '⏩',
    question: '¿Cuándo ___ ellos? (venir - to come)',
    options: ['vendrán', 'vienen', 'vinieron'],
    correctAnswer: 'vendrán',
    hint: 'When will they come - Irregular future stem "vendr-" (not "venir-") + -án',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_80',
    emoji: '⏩',
    question: 'Ella no ___ ir a la fiesta. (poder - to be able)',
    options: ['podrá', 'puede', 'pudo'],
    correctAnswer: 'podrá',
    hint: 'She won\'t be able - Irregular future stem "podr-" (not "poder-") + -á',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },

  // PRESENT PROGRESSIVE (estar + gerund) - 8 questions
  {
    id: 'grammar_81',
    emoji: '▶️',
    question: 'Yo ___ un libro ahora. (leer - to read)',
    options: ['estoy leyendo', 'leo', 'leí'],
    correctAnswer: 'estoy leyendo',
    hint: 'I am reading - Present progressive: estar + gerund, -ER/-IR verbs end in -yendo',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_82',
    emoji: '▶️',
    question: 'Tú ___ español muy rápido. (aprender - to learn)',
    options: ['estás aprendiendo', 'aprendes', 'aprendiste'],
    correctAnswer: 'estás aprendiendo',
    hint: 'You are learning - estar + gerund (-iendo for -ER verbs), happening right now',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_83',
    emoji: '▶️',
    question: 'Ella ___ la cena en este momento. (cocinar - to cook)',
    options: ['está cocinando', 'cocina', 'cocinó'],
    correctAnswer: 'está cocinando',
    hint: 'She is cooking - estar + gerund (-ando for -AR verbs), "en este momento" = right now',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_84',
    emoji: '▶️',
    question: 'Nosotros ___ una película. (ver - to watch)',
    options: ['estamos viendo', 'vemos', 'vimos'],
    correctAnswer: 'estamos viendo',
    hint: 'We are watching - estar + gerund, ongoing action happening now',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_85',
    emoji: '▶️',
    question: '¿Qué ___ ellos? (hacer - to do)',
    options: ['están haciendo', 'hacen', 'hicieron'],
    correctAnswer: 'están haciendo',
    hint: 'What are they doing - estar + gerund of irregular "hacer" = "haciendo"',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_86',
    emoji: '▶️',
    question: 'Yo ___ para el examen. (estudiar - to study)',
    options: ['estoy estudiando', 'estudio', 'estudié'],
    correctAnswer: 'estoy estudiando',
    hint: 'I am studying - Present progressive for action in progress, -AR gerund = -ando',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_87',
    emoji: '▶️',
    question: 'Ellos ___ al fútbol. (jugar - to play)',
    options: ['están jugando', 'juegan', 'jugaron'],
    correctAnswer: 'están jugando',
    hint: 'They are playing - estar + gerund, action happening right now',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },
  {
    id: 'grammar_88',
    emoji: '▶️',
    question: '¿Por qué ___ tú? (llorar - to cry)',
    options: ['estás llorando', 'lloras', 'lloraste'],
    correctAnswer: 'estás llorando',
    hint: 'Why are you crying - Present progressive for current action, -AR = -ando',
    points: 10,
    category: 'grammar',
    difficulty: 'medium',
  },

  // CONDITIONAL TENSE (would) - 8 questions
  {
    id: 'grammar_89',
    emoji: '🤔',
    question: 'Yo ___ a España si tuviera dinero. (ir - to go)',
    options: ['iría', 'voy', 'fui'],
    correctAnswer: 'iría',
    hint: 'I would go - Conditional: infinitive + -ía for yo, used with "si" (if) clauses',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_90',
    emoji: '🤔',
    question: 'Tú ___ feliz allí. (ser - to be)',
    options: ['serías', 'eres', 'fuiste'],
    correctAnswer: 'serías',
    hint: 'You would be - Conditional for hypothetical, infinitive + -ías for tú',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_91',
    emoji: '🤔',
    question: 'Ella ___ más temprano. (salir - to leave)',
    options: ['saldría', 'sale', 'salió'],
    correctAnswer: 'saldría',
    hint: 'She would leave - Irregular conditional stem "saldr-" (same as future) + -ía',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_92',
    emoji: '🤔',
    question: 'Nosotros ___ más si pudiéramos. (trabajar - to work)',
    options: ['trabajaríamos', 'trabajamos', 'trabajábamos'],
    correctAnswer: 'trabajaríamos',
    hint: 'We would work - Conditional: infinitive + -íamos for nosotros, hypothetical',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_93',
    emoji: '🤔',
    question: '¿Qué ___ tú en mi lugar? (hacer - to do)',
    options: ['harías', 'haces', 'hiciste'],
    correctAnswer: 'harías',
    hint: 'What would you do - Irregular stem "har-" (same as future) + -ías, "en mi lugar" = in my place',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_94',
    emoji: '🤔',
    question: 'Ellos ___ ayudarnos. (poder - to be able)',
    options: ['podrían', 'pueden', 'pudieron'],
    correctAnswer: 'podrían',
    hint: 'They could/would be able - Irregular stem "podr-" + -ían, polite suggestion',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_95',
    emoji: '🤔',
    question: 'Yo ___ más cuidado. (tener - to have)',
    options: ['tendría', 'tengo', 'tuve'],
    correctAnswer: 'tendría',
    hint: 'I would have/take - Irregular stem "tendr-" + -ía, "tener cuidado" = be careful',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_96',
    emoji: '🤔',
    question: '¿___ usted ayudarme? (poder - could you)',
    options: ['Podría', 'Puede', 'Pudo'],
    correctAnswer: 'Podría',
    hint: 'Could you - Conditional for polite request, more polite than "puede"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },

  // SUBJUNCTIVE BASICS (Present) - 14 questions
  {
    id: 'grammar_97',
    emoji: '💭',
    question: 'Espero que tú ___ bien. (estar - to be)',
    options: ['estés', 'estás', 'estas'],
    correctAnswer: 'estés',
    hint: 'I hope you are - Subjunctive after "espero que" (hope that), doubt/wish, tú form = -es',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_98',
    emoji: '💭',
    question: 'Es importante que nosotros ___ español. (hablar - to speak)',
    options: ['hablemos', 'hablamos', 'hablaremos'],
    correctAnswer: 'hablemos',
    hint: 'It\'s important that we speak - Subjunctive after "es importante que", -AR = -emos',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_99',
    emoji: '💭',
    question: 'Quiero que ella ___ la verdad. (decir - to say)',
    options: ['diga', 'dice', 'dirá'],
    correctAnswer: 'diga',
    hint: 'I want her to say - Subjunctive after "quiero que" (want that), irregular "decir" = "diga"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_100',
    emoji: '💭',
    question: 'Dudo que ellos ___ a tiempo. (llegar - to arrive)',
    options: ['lleguen', 'llegan', 'llegarán'],
    correctAnswer: 'lleguen',
    hint: 'I doubt they arrive - Subjunctive after "dudo que" (doubt), uncertainty, -AR = -en',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_101',
    emoji: '💭',
    question: 'Es necesario que yo ___ más. (estudiar - to study)',
    options: ['estudie', 'estudio', 'estudiaré'],
    correctAnswer: 'estudie',
    hint: 'It\'s necessary that I study - Subjunctive after impersonal expression, -AR yo = -e',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_102',
    emoji: '💭',
    question: 'No creo que él ___ razón. (tener - to have)',
    options: ['tenga', 'tiene', 'tendrá'],
    correctAnswer: 'tenga',
    hint: 'I don\'t think he\'s right - Subjunctive after "no creo que" (negative belief), irregular "tener"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_103',
    emoji: '💭',
    question: 'Ojalá que ___ buen tiempo mañana. (hacer - to make/do)',
    options: ['haga', 'hace', 'hará'],
    correctAnswer: 'haga',
    hint: 'I hope the weather is good - "Ojalá que" (hopefully) always uses subjunctive, irregular "hacer"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_104',
    emoji: '💭',
    question: 'Te recomiendo que ___ agua. (beber - to drink)',
    options: ['bebas', 'bebes', 'beberás'],
    correctAnswer: 'bebas',
    hint: 'I recommend you drink - Subjunctive after recommendation, -ER tú = -as',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_105',
    emoji: '💭',
    question: 'Es posible que nosotros ___ tarde. (salir - to leave)',
    options: ['salgamos', 'salimos', 'saldremos'],
    correctAnswer: 'salgamos',
    hint: 'It\'s possible we leave late - Subjunctive for possibility, irregular "salir" = "salg-"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_106',
    emoji: '💭',
    question: 'Prefiero que tú ___ aquí. (quedarse - to stay)',
    options: ['te quedes', 'te quedas', 'te quedarás'],
    correctAnswer: 'te quedes',
    hint: 'I prefer you stay - Subjunctive after preference, reflexive verb with subjunctive',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_107',
    emoji: '💭',
    question: 'Aunque ___ cansado, voy a trabajar. (estar - to be)',
    options: ['esté', 'estoy', 'estaré'],
    correctAnswer: 'esté',
    hint: 'Even though I am tired - Subjunctive after "aunque" when uncertain, irregular "estar"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_108',
    emoji: '💭',
    question: 'No hay nadie que ___ la respuesta. (saber - to know)',
    options: ['sepa', 'sabe', 'sabrá'],
    correctAnswer: 'sepa',
    hint: 'There\'s no one who knows - Subjunctive after negative + "que", irregular "saber"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_109',
    emoji: '💭',
    question: 'Cuando ___ a España, te llamaré. (ir - to go)',
    options: ['vaya', 'voy', 'iré'],
    correctAnswer: 'vaya',
    hint: 'When I go to Spain - Subjunctive after "cuando" for future events, irregular "ir"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
  {
    id: 'grammar_110',
    emoji: '💭',
    question: 'Busco un hotel que ___ económico. (ser - to be)',
    options: ['sea', 'es', 'será'],
    correctAnswer: 'sea',
    hint: 'I\'m looking for a hotel that is cheap - Subjunctive for uncertain/nonexistent, irregular "ser"',
    points: 15,
    category: 'grammar',
    difficulty: 'hard',
  },
];
