/**
 * Numbers, Colors & Time Category Questions
 * Category: numbers
 */

export const numbersQuestions = [
{
    id: 'numbers_001',
    emoji: '0️⃣',
    question: '¿Qué número representa la temperatura de congelación del agua en grados Celsius?',
    translation: 'What number represents the freezing temperature of water in degrees Celsius?',
    options: ['cero', 'nada', 'ninguno'],
    correctAnswer: 'cero',
    hint: 'Zero - from Arabic "sifr" (empty), like English "cipher", temperature 0°C is "cero grados"',
    usageExample: 'La temperatura hoy es de cero grados.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_002',
    emoji: '1️⃣',
    question: '¿Cuál es el primer número después de cero?',
    translation: 'What is the first number after zero?',
    options: ['uno', 'un', 'una'],
    correctAnswer: 'uno',
    hint: 'One - becomes "un" before masculine nouns, "una" before feminine, from Latin "unus"',
    usageExample: 'Necesito comprar uno de cada color.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_003',
    emoji: '2️⃣',
    question: '¿Cuántos ojos tiene una persona?',
    translation: 'How many eyes does a person have?',
    options: ['dos', 'doce', 'veinte'],
    correctAnswer: 'dos',
    hint: 'Two - from Latin "duos", same root as "duo", "dual", "double", never changes form',
    usageExample: 'Tengo dos hermanos mayores.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_004',
    emoji: '3️⃣',
    question: '¿Cuántos lados tiene un triángulo?',
    translation: 'How many sides does a triangle have?',
    options: ['tres', 'trece', 'treinta'],
    correctAnswer: 'tres',
    hint: 'Three - from Latin "tres", like "trio", "triple", "trinity", never changes form',
    usageExample: 'La reunión es a las tres de la tarde.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_005',
    emoji: '4️⃣',
    question: '¿Cuántas estaciones tiene el año?',
    translation: 'How many seasons does the year have?',
    options: ['cuatro', 'catorce', 'cuarenta'],
    correctAnswer: 'cuatro',
    hint: 'Four - from Latin "quattuor", think "quartet", "quadrant", never changes form',
    usageExample: 'Mi familia tiene cuatro mascotas.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_006',
    emoji: '5️⃣',
    question: '¿Cuántos dedos tiene una mano?',
    translation: 'How many fingers does a hand have?',
    options: ['cinco', 'quince', 'cincuenta'],
    correctAnswer: 'cinco',
    hint: 'Five - from Latin "quinque", like "quintet", "quintuplets", never changes form',
    usageExample: 'La tienda abre a las cinco de la mañana.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_007',
    emoji: '6️⃣',
    question: '¿Cuántas patas tiene un insecto?',
    translation: 'How many legs does an insect have?',
    options: ['seis', 'dieciséis', 'sesenta'],
    correctAnswer: 'seis',
    hint: 'Six - from Latin "sex", like "sextet", "sextuple", never changes form',
    usageExample: 'Hay seis manzanas en la canasta.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_008',
    emoji: '7️⃣',
    question: '¿Cuántos días tiene una semana?',
    translation: 'How many days does a week have?',
    options: ['siete', 'diecisiete', 'setenta'],
    correctAnswer: 'siete',
    hint: 'Seven - from Latin "septem", like "September" (7th month in Roman calendar), lucky number',
    usageExample: 'Ella vive en el piso siete del edificio.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_009',
    emoji: '8️⃣',
    question: '¿Cuántos tentáculos tiene un pulpo?',
    translation: 'How many tentacles does an octopus have?',
    options: ['ocho', 'dieciocho', 'ochenta'],
    correctAnswer: 'ocho',
    hint: 'Eight - from Latin "octo", like "octopus" (8 legs), "October" (8th month in Roman calendar)',
    usageExample: 'El autobús sale a las ocho en punto.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_010',
    emoji: '9️⃣',
    question: '¿Cuántos jugadores tiene un equipo de béisbol en el campo?',
    translation: 'How many players does a baseball team have on the field?',
    options: ['nueve', 'diecinueve', 'noventa'],
    correctAnswer: 'nueve',
    hint: 'Nine - from Latin "novem", like "November" (9th month in Roman calendar), "novena" (9-day prayer)',
    usageExample: 'Mi hermano tiene nueve años de edad.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },

  // Numbers 10-20 (10 questions)
  {
    id: 'numbers_011',
    emoji: '🔟',
    question: '¿Cuántos mandamientos hay en la tradición judeocristiana?',
    translation: 'How many commandments are there in the Judeo-Christian tradition?',
    options: ['diez', 'dieci', 'dies'],
    correctAnswer: 'diez',
    hint: 'Ten - from Latin "decem", like "decade", "decimal", "December" (10th Roman month)',
    usageExample: 'Son las diez de la noche y tengo sueño.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_012',
    emoji: '🔢',
    question: '¿Cuántos jugadores tiene un equipo de fútbol en el campo?',
    translation: 'How many players does a soccer team have on the field?',
    options: ['once', 'uno', 'diez y uno'],
    correctAnswer: 'once',
    hint: 'Eleven - from Latin "undecim" (one + ten), starts teen pattern until 15',
    usageExample: 'La clase comienza a las once de la mañana.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_013',
    emoji: '🔢',
    question: '¿Cuántos meses tiene un año?',
    translation: 'How many months does a year have?',
    options: ['doce', 'dos', 'diez y dos'],
    correctAnswer: 'doce',
    hint: 'Twelve - from Latin "duodecim" (two + ten), "una docena" is a dozen',
    usageExample: 'Compré doce huevos en el supermercado.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_014',
    emoji: '🔢',
    question: '¿Qué número se considera de mala suerte en algunas culturas?',
    translation: 'What number is considered unlucky in some cultures?',
    options: ['trece', 'tres', 'diez y tres'],
    correctAnswer: 'trece',
    hint: 'Thirteen - from "tres" + "diez", unlucky number in some cultures',
    usageExample: 'Mi hija cumple trece años mañana.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_015',
    emoji: '🔢',
    question: '¿Cuántos días tiene un par de semanas?',
    translation: 'How many days are in two weeks?',
    options: ['catorce', 'cuatro', 'diez y cuatro'],
    correctAnswer: 'catorce',
    hint: 'Fourteen - from "cuatro" + "diez", last unique teen form',
    usageExample: 'Hay catorce estudiantes en el salón de clase.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_016',
    emoji: '🔢',
    question: '¿A qué edad celebran las chicas su quinceañera?',
    translation: 'At what age do girls celebrate their quinceañera?',
    options: ['quince', 'cinco', 'diez y cinco'],
    correctAnswer: 'quince',
    hint: 'Fifteen - from "cinco" + "diez", quinceañera celebrates girl\'s 15th birthday',
    usageExample: 'Mi prima celebró su quince años el mes pasado.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_017',
    emoji: '🔢',
    question: '¿A qué edad pueden conducir los jóvenes en muchos países?',
    translation: 'At what age can young people drive in many countries?',
    options: ['dieciséis', 'diez y seis', 'dieciseis'],
    correctAnswer: 'dieciséis',
    hint: 'Sixteen - "diez y seis" combined, pattern continues 16-19 with "dieci-"',
    usageExample: 'El edificio tiene dieciséis pisos de altura.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_018',
    emoji: '🔢',
    question: '¿Qué número viene después de dieciséis y antes de dieciocho?',
    translation: 'What number comes after sixteen and before eighteen?',
    options: ['diecisiete', 'diez y siete', 'dieciseis'],
    correctAnswer: 'diecisiete',
    hint: 'Seventeen - literally "ten and seven", combined form of "diez y siete"',
    usageExample: 'El partido de fútbol comienza a las diecisiete horas.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_019',
    emoji: '🔢',
    question: '¿A qué edad se considera adulto en la mayoría de los países?',
    translation: 'At what age is someone considered an adult in most countries?',
    options: ['dieciocho', 'diez y ocho', 'diecisiete'],
    correctAnswer: 'dieciocho',
    hint: 'Eighteen - adult age in most countries, "diez y ocho" combined',
    usageExample: 'Tengo dieciocho años y puedo votar ahora.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_020',
    emoji: '🔢',
    question: '¿Qué número viene justo antes de veinte?',
    translation: 'What number comes right before twenty?',
    options: ['diecinueve', 'diez y nueve', 'diecinuebe'],
    correctAnswer: 'diecinueve',
    hint: 'Nineteen - last teen number, "diez y nueve" combined, legal drinking age some places',
    usageExample: 'Ella tiene diecinueve años y estudia medicina.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  // Larger Numbers (10 questions)
  {
    id: 'numbers_021',
    emoji: '🔢',
    question: '¿Cuántos dedos tiene una persona en total?',
    translation: 'How many fingers does a person have in total?',
    options: ['veinte', 'vente', 'beinte'],
    correctAnswer: 'veinte',
    hint: 'Twenty - from Latin "viginti", 21-29 combine as "veinti-" (veintiuno, veintidós)',
    usageExample: 'El libro cuesta veinte dólares en la librería.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_022',
    emoji: '🔢',
    question: '¿Cuántos días tienen los meses de abril, junio, septiembre y noviembre?',
    translation: 'How many days do the months of April, June, September and November have?',
    options: ['treinta', 'trenta', 'treynta'],
    correctAnswer: 'treinta',
    hint: 'Thirty - from "tres" + "-inta" suffix, pattern for 30-90 (treinta y uno, treinta y dos)',
    usageExample: 'Mi madre tiene treinta y cinco años.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_023',
    emoji: '🔢',
    question: '¿Cuántos días y noches llovío en la historia del arca de Noé?',
    translation: 'How many days and nights did it rain in the story of Noah\'s ark?',
    options: ['cuarenta', 'quarenta', 'cuatrenta'],
    correctAnswer: 'cuarenta',
    hint: 'Forty - from "cuatro" + "-enta", notice spelling change from cuatro',
    usageExample: 'El viaje en tren dura cuarenta minutos.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_024',
    emoji: '🔢',
    question: '¿Cuál es la mitad de cien?',
    translation: 'What is half of one hundred?',
    options: ['cincuenta', 'cinquenta', 'cincenta'],
    correctAnswer: 'cincuenta',
    hint: 'Fifty - from "cinco" + "-enta", half of 100 is "media centena"',
    usageExample: 'Hay cincuenta estados en los Estados Unidos.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_025',
    emoji: '🔢',
    question: '¿Cuántos minutos tiene una hora?',
    translation: 'How many minutes does an hour have?',
    options: ['sesenta', 'seisenta', 'secenta'],
    correctAnswer: 'sesenta',
    hint: 'Sixty - from "seis" + "-enta", 60 minutes in hour, 60 seconds in minute',
    usageExample: 'Mi abuelo tiene sesenta y dos años.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_026',
    emoji: '🔢',
    question: '¿Qué número viene después de sesenta y nueve?',
    translation: 'What number comes after sixty-nine?',
    options: ['setenta', 'sietenta', 'septenta'],
    correctAnswer: 'setenta',
    hint: 'Seventy - from "siete" + "-enta", notice spelling change from siete',
    usageExample: 'La abuela de Pedro tiene setenta años.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_027',
    emoji: '🔢',
    question: '¿Qué número está entre setenta y noventa?',
    translation: 'What number is between seventy and ninety?',
    options: ['ochenta', 'ochocenta', 'ochoenta'],
    correctAnswer: 'ochenta',
    hint: 'Eighty - from "ocho" + "-enta", follows decade pattern',
    usageExample: 'El límite de velocidad es ochenta kilómetros por hora.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_028',
    emoji: '🔢',
    question: '¿Qué número viene antes de cien?',
    translation: 'What number comes before one hundred?',
    options: ['noventa', 'nueventa', 'noventay'],
    correctAnswer: 'noventa',
    hint: 'Ninety - from "nueve" + "-enta", last decade before 100',
    usageExample: 'El año mil novecientos noventa fue hace mucho tiempo.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_029',
    emoji: '💯',
    question: '¿Cuántos centavos hay en un dólar?',
    translation: 'How many cents are in a dollar?',
    options: ['cien', 'ciento', 'cientos'],
    correctAnswer: 'cien',
    hint: 'One hundred - "cien" alone, "ciento" before other numbers (ciento uno), from Latin "centum"',
    usageExample: 'La camisa cuesta cien pesos en la tienda.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_030',
    emoji: '🔢',
    question: '¿Cuántos años hay en un milenio?',
    translation: 'How many years are in a millennium?',
    options: ['mil', 'miles', 'mille'],
    correctAnswer: 'mil',
    hint: 'One thousand - from Latin "mille", millennium is 1000 years, never changes (dos mil, tres mil)',
    usageExample: 'El vuelo a España cuesta mil dólares.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  // Days of the Week (7 questions)
  {
    id: 'numbers_031',
    emoji: '📅',
    question: '¿Qué día de la semana viene después del domingo?',
    translation: 'What day of the week comes after Sunday?',
    options: ['lunes', 'el lunes', 'los lunes'],
    correctAnswer: 'lunes',
    hint: 'Monday - from Latin "dies Lunae" (day of Moon), always lowercase, masculine singular',
    usageExample: 'El lunes tengo una reunión importante en la oficina.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_032',
    emoji: '📅',
    question: '¿Qué día viene después del lunes?',
    translation: 'What day comes after Monday?',
    options: ['martes', 'el martes', 'los martes'],
    correctAnswer: 'martes',
    hint: 'Tuesday - from Mars (Roman god of war), "día de Marte", always lowercase',
    usageExample: 'Los martes voy al gimnasio después del trabajo.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_033',
    emoji: '📅',
    question: '¿Qué día está en el medio de la semana laboral?',
    translation: 'What day is in the middle of the work week?',
    options: ['miércoles', 'el miércoles', 'los miércoles'],
    correctAnswer: 'miércoles',
    hint: 'Wednesday - from Mercury (Roman god), middle of work week, "hump day"',
    usageExample: 'El examen de matemáticas es el miércoles próximo.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_034',
    emoji: '📅',
    question: '¿Qué día viene antes del viernes?',
    translation: 'What day comes before Friday?',
    options: ['jueves', 'el jueves', 'los jueves'],
    correctAnswer: 'jueves',
    hint: 'Thursday - from Jove/Jupiter (Roman king of gods), fourth work day',
    usageExample: 'Todos los jueves tenemos clase de español.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_035',
    emoji: '📅',
    question: '¿Qué día es el último día laboral de la semana?',
    translation: 'What day is the last work day of the week?',
    options: ['viernes', 'el viernes', 'los viernes'],
    correctAnswer: 'viernes',
    hint: 'Friday - from Venus (Roman goddess of love), TGIF! Last work day, "Viernes Santo" is Good Friday',
    usageExample: 'El viernes por la noche vamos al cine.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_036',
    emoji: '📅',
    question: '¿Qué día es el primer día del fin de semana?',
    translation: 'What day is the first day of the weekend?',
    options: ['sábado', 'el sábado', 'los sábados'],
    correctAnswer: 'sábado',
    hint: 'Saturday - from Latin "Sabbatum" (Sabbath), weekend day, party night',
    usageExample: 'El sábado vamos a la playa con amigos.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_037',
    emoji: '📅',
    question: '¿Qué día es el último día de la semana?',
    translation: 'What day is the last day of the week?',
    options: ['domingo', 'el domingo', 'los domingos'],
    correctAnswer: 'domingo',
    hint: 'Sunday - from Latin "dies Dominicus" (Lord\'s day), rest day, family day in Spanish culture',
    usageExample: 'Los domingos comemos con la familia.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },

  // Months of the Year (12 questions)
  {
    id: 'numbers_038',
    emoji: '📆',
    question: '¿En qué mes celebramos el Año Nuevo?',
    translation: 'In what month do we celebrate the New Year?',
    options: ['enero', 'el enero', 'januario'],
    correctAnswer: 'enero',
    hint: 'January - from Janus (Roman god of beginnings), New Year month, always lowercase in Spanish',
    usageExample: 'Mi cumpleaños es el quince de enero.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_039',
    emoji: '📆',
    question: '¿Cuál es el mes más corto del año?',
    translation: 'What is the shortest month of the year?',
    options: ['febrero', 'el febrero', 'februario'],
    correctAnswer: 'febrero',
    hint: 'February - shortest month (28/29 days), from Roman purification festival "Februa"',
    usageExample: 'El día de San Valentín es en febrero.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_040',
    emoji: '📆',
    question: '¿En qué mes comienza la primavera en el hemisferio norte?',
    translation: 'In what month does spring begin in the northern hemisphere?',
    options: ['marzo', 'el marzo', 'marcho'],
    correctAnswer: 'marzo',
    hint: 'March - from Mars (god of war), spring begins, "Martes y trece" (Tuesday 13th) unlucky in Spanish',
    usageExample: 'La primavera comienza en marzo.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_041',
    emoji: '📆',
    question: '¿En qué mes celebramos el Día de los Inocentes (April Fools)?',
    translation: 'In what month do we celebrate April Fools\' Day?',
    options: ['abril', 'el abril', 'abrel'],
    correctAnswer: 'abril',
    hint: 'April - possibly from Latin "aperire" (to open) for spring flowers, "Día de los Inocentes" April 1st',
    usageExample: 'Las flores florecen en abril.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_042',
    emoji: '📆',
    question: '¿En qué mes se celebra el Cinco de Mayo?',
    translation: 'In what month is Cinco de Mayo celebrated?',
    options: ['mayo', 'el mayo', 'mai'],
    correctAnswer: 'mayo',
    hint: 'May - from Maia (Roman goddess), "Cinco de Mayo" celebrated, spring/summer month',
    usageExample: 'El cinco de mayo es una celebración importante.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_043',
    emoji: '📆',
    question: '¿En qué mes comienza el verano en el hemisferio norte?',
    translation: 'In what month does summer begin in the northern hemisphere?',
    options: ['junio', 'el junio', 'junho'],
    correctAnswer: 'junio',
    hint: 'June - from Juno (Roman goddess, protector of marriage), popular wedding month',
    usageExample: 'Nos vamos de vacaciones en junio.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_044',
    emoji: '📆',
    question: '¿En qué mes celebran los estadounidenses su independencia?',
    translation: 'In what month do Americans celebrate their independence?',
    options: ['julio', 'el julio', 'jullio'],
    correctAnswer: 'julio',
    hint: 'July - named after Julius Caesar, summer month, vacation season in Spain',
    usageExample: 'Hace mucho calor en julio.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_045',
    emoji: '📆',
    question: '¿Cuál es el último mes del verano en el hemisferio norte?',
    translation: 'What is the last month of summer in the northern hemisphere?',
    options: ['agosto', 'el agosto', 'augusto'],
    correctAnswer: 'agosto',
    hint: 'August - named after Emperor Augustus, peak summer, "agosto" also means harvest time',
    usageExample: 'En agosto vamos a visitar a mis abuelos.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_046',
    emoji: '📆',
    question: '¿En qué mes comienza el año escolar en la mayoría de los países?',
    translation: 'In what month does the school year start in most countries?',
    options: ['septiembre', 'setiembre', 'el septiembre'],
    correctAnswer: 'septiembre',
    hint: 'September - from Latin "septem" (seven, 7th in Roman calendar), back to school month',
    usageExample: 'Las clases empiezan en septiembre.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_047',
    emoji: '📆',
    question: '¿En qué mes se celebra Halloween?',
    translation: 'In what month is Halloween celebrated?',
    options: ['octubre', 'otubre', 'el octubre'],
    correctAnswer: 'octubre',
    hint: 'October - from Latin "octo" (eight, 8th Roman month), "Día de la Raza" October 12',
    usageExample: 'Halloween se celebra en octubre.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_048',
    emoji: '📆',
    question: '¿En qué mes se celebra el Día de los Muertos?',
    translation: 'In what month is Day of the Dead celebrated?',
    options: ['noviembre', 'nobiembre', 'el noviembre'],
    correctAnswer: 'noviembre',
    hint: 'November - from Latin "novem" (nine, 9th Roman month), "Día de Muertos" November 1-2',
    usageExample: 'El día de los muertos es en noviembre.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_049',
    emoji: '📆',
    question: '¿En qué mes celebramos la Navidad?',
    translation: 'In what month do we celebrate Christmas?',
    options: ['diciembre', 'disiembre', 'el diciembre'],
    correctAnswer: 'diciembre',
    hint: 'December - from Latin "decem" (ten, 10th Roman month), Christmas "Navidad" December 25',
    usageExample: 'La Navidad es en diciembre.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },

  // Time Expressions (11 questions)
  {
    id: 'numbers_050',
    emoji: '⏰',
    question: '¿Cuánto tiempo tiene sesenta minutos?',
    translation: 'What period of time has sixty minutes?',
    options: ['hora', 'la hora', 'horas'],
    correctAnswer: 'hora',
    hint: 'Hour - 60 minutes, from Latin "hora", "¿qué hora es?" asks the time',
    usageExample: '¿Qué hora es? Son las dos de la tarde.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_051',
    emoji: '⏱️',
    question: '¿Cuánto tiempo tiene sesenta segundos?',
    translation: 'What period of time has sixty seconds?',
    options: ['minuto', 'el minuto', 'minutos'],
    correctAnswer: 'minuto',
    hint: 'Minute - 60 seconds, from Latin "minutus" (small), "un minuto" is wait a minute',
    usageExample: 'Espera un minuto, ya casi termino.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_052',
    emoji: '⏱️',
    question: '¿Cuál es la unidad de tiempo más pequeña?',
    translation: 'What is the smallest unit of time?',
    options: ['segundo', 'el segundo', 'segundos'],
    correctAnswer: 'segundo',
    hint: 'Second - smallest time unit, also means "second" (2nd), dual meaning in Spanish',
    usageExample: 'La carrera duró solo treinta segundos.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_053',
    emoji: '🌅',
    question: '¿Qué parte del día es antes del mediodía?',
    translation: 'What part of the day is before noon?',
    options: ['mañana', 'la mañana', 'mañanita'],
    correctAnswer: 'mañana',
    hint: 'Morning - before noon, also means "tomorrow", "de la mañana" for AM time',
    usageExample: 'Me gusta caminar por la mañana.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_054',
    emoji: '☀️',
    question: '¿Qué parte del día es después del mediodía y antes de la noche?',
    translation: 'What part of the day is after noon and before night?',
    options: ['tarde', 'la tarde', 'tardecita'],
    correctAnswer: 'tarde',
    hint: 'Afternoon - after noon until sunset, also means "late", "de la tarde" for PM time',
    usageExample: 'Vamos a la piscina esta tarde.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_055',
    emoji: '🌙',
    question: '¿Qué parte del día es cuando sale la luna y las estrellas?',
    translation: 'What part of the day is when the moon and stars come out?',
    options: ['noche', 'la noche', 'nochecita'],
    correctAnswer: 'noche',
    hint: 'Night - after sunset, from Latin "nox", "de la noche" for evening time, "medianoche" is midnight',
    usageExample: 'Buenas noches, que duermas bien.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_056',
    emoji: '📅',
    question: '¿Qué día es ahora, este día?',
    translation: 'What day is now, this day?',
    options: ['hoy', 'hoY', 'oy'],
    correctAnswer: 'hoy',
    hint: 'Today - this day, from Latin "hodie", "hoy en día" means nowadays',
    usageExample: 'Hoy es un día muy especial.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_057',
    emoji: '📅',
    question: '¿Qué día fue antes de hoy?',
    translation: 'What day was before today?',
    options: ['ayer', 'anteayer', 'ayér'],
    correctAnswer: 'ayer',
    hint: 'Yesterday - day before today, "anteayer" is day before yesterday (two days ago)',
    usageExample: 'Ayer fui al parque con mis amigos.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_058',
    emoji: '📅',
    question: '¿Qué día viene después de hoy?',
    translation: 'What day comes after today?',
    options: ['mañana', 'la mañana', 'mañanita'],
    correctAnswer: 'mañana',
    hint: 'Tomorrow - day after today, also means "morning", context determines meaning',
    usageExample: 'Mañana tengo un examen importante.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_059',
    emoji: '📅',
    question: '¿Cuánto tiempo tiene siete días?',
    translation: 'What period of time has seven days?',
    options: ['semana', 'la semana', 'semanita'],
    correctAnswer: 'semana',
    hint: 'Week - seven days, from Latin "septimana" (seven), "fin de semana" is weekend',
    usageExample: 'Este fin de semana vamos a la montaña.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_060',
    emoji: '📆',
    question: '¿Cuánto tiempo tiene doce meses?',
    translation: 'What period of time has twelve months?',
    options: ['año', 'el año', 'añito'],
    correctAnswer: 'año',
    hint: 'Year - twelve months, 365 days, from Latin "annus", "Año Nuevo" is New Year',
    usageExample: '¡Feliz año nuevo! Que tengas un gran año.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },

  // Colors (15 questions)
  {
    id: 'numbers_061',
    emoji: '🔴',
    question: '¿De qué color es una rosa tradicional de amor?',
    translation: 'What color is a traditional rose of love?',
    options: ['rojo', 'roja', 'rojos'],
    correctAnswer: 'rojo',
    hint: 'Red - changes to "roja" for feminine nouns, from Latin "russus", color of passion and danger',
    usageExample: 'Mi coche nuevo es rojo brillante.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_062',
    emoji: '🔵',
    question: '¿De qué color es el cielo en un día despejado?',
    translation: 'What color is the sky on a clear day?',
    options: ['azul', 'azules', 'azulado'],
    correctAnswer: 'azul',
    hint: 'Blue - from Arabic "lazaward" (lapis lazuli stone), no gender change, sky and ocean color',
    usageExample: 'El cielo está azul y despejado hoy.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_063',
    emoji: '🟢',
    question: '¿De qué color son las hojas de los árboles en primavera?',
    translation: 'What color are the leaves of trees in spring?',
    options: ['verde', 'verdes', 'verdoso'],
    correctAnswer: 'verde',
    hint: 'Green - no gender change, also means "unripe" (fruta verde), nature and plant color',
    usageExample: 'Me encanta el color verde de los árboles.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_064',
    emoji: '🟡',
    question: '¿De qué color es el sol?',
    translation: 'What color is the sun?',
    options: ['amarillo', 'amarilla', 'amarillos'],
    correctAnswer: 'amarillo',
    hint: 'Yellow - changes to "amarilla" for feminine, from Arabic "al-mariyya", sun color',
    usageExample: 'Las flores amarillas son muy bonitas.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_065',
    emoji: '🟠',
    question: '¿De qué color es una calabaza de Halloween?',
    translation: 'What color is a Halloween pumpkin?',
    options: ['naranja', 'anaranjado', 'naranjas'],
    correctAnswer: 'naranja',
    hint: 'Orange - same word as fruit, no gender change (invariable), from Sanskrit through Arabic',
    usageExample: 'Tiene una camisa naranja muy llamativa.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_066',
    emoji: '🟣',
    question: '¿De qué color son las uvas usadas para hacer vino tinto?',
    translation: 'What color are grapes used to make red wine?',
    options: ['morado', 'púrpura', 'violeta'],
    correctAnswer: 'morado',
    hint: 'Purple - changes to "morada", also "púrpura" or "violeta", royal color historically',
    usageExample: 'Mi color favorito es el morado.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_067',
    emoji: '🩷',
    question: '¿De qué color son los flamencos?',
    translation: 'What color are flamingos?',
    options: ['rosa', 'rosado', 'rosada'],
    correctAnswer: 'rosa',
    hint: 'Pink - same word as "rose" flower, no gender change, light red color',
    usageExample: 'La niña lleva un vestido rosa precioso.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_068',
    emoji: '⚫',
    question: '¿De qué color es la noche sin luna?',
    translation: 'What color is the night without a moon?',
    options: ['negro', 'negra', 'negros'],
    correctAnswer: 'negro',
    hint: 'Black - changes to "negra" for feminine, from Latin "niger", absence of light',
    usageExample: 'Mi gato es negro con ojos verdes.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_069',
    emoji: '⚪',
    question: '¿De qué color es la nieve?',
    translation: 'What color is snow?',
    options: ['blanco', 'blanca', 'blancos'],
    correctAnswer: 'blanco',
    hint: 'White - changes to "blanca", from Germanic "blank", all colors combined, purity symbol',
    usageExample: 'La nieve es blanca y fría.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_070',
    emoji: '🩶',
    question: '¿De qué color es un elefante?',
    translation: 'What color is an elephant?',
    options: ['gris', 'grises', 'grisáceo'],
    correctAnswer: 'gris',
    hint: 'Gray - from French "gris", no gender change, mixture of black and white',
    usageExample: 'El elefante es de color gris.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_071',
    emoji: '🟤',
    question: '¿De qué color son la mayoría de los osos?',
    translation: 'What color are most bears?',
    options: ['marrón', 'café', 'pardo'],
    correctAnswer: 'marrón',
    hint: 'Brown - from French "marron" (chestnut), Latin America often uses "café", earth color',
    usageExample: 'Los osos son de color marrón.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_072',
    emoji: '🎨',
    question: '¿Qué palabra usamos para describir si algo es rojo, azul o verde?',
    translation: 'What word do we use to describe if something is red, blue or green?',
    options: ['color', 'el color', 'los colores'],
    correctAnswer: 'color',
    hint: 'Color - masculine noun, same spelling as English, from Latin "color"',
    usageExample: '¿Cuál es tu color favorito?',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_073',
    emoji: '🌈',
    question: '¿Qué aparece en el cielo después de la lluvia con siete colores?',
    translation: 'What appears in the sky after rain with seven colors?',
    options: ['arcoíris', 'arco iris', 'el arcoíris'],
    correctAnswer: 'arcoíris',
    hint: 'Rainbow - literally "arc of iris", seven colors spectrum, appears after rain',
    usageExample: 'Después de la lluvia apareció un arcoíris hermoso.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_074',
    emoji: '💡',
    question: '¿Qué palabra describe un color pálido como azul pálido?',
    translation: 'What word describes a pale color like light blue?',
    options: ['claro', 'oscuro', 'brillante'],
    correctAnswer: 'claro',
    hint: 'Light - pale color shade, "azul claro" (light blue), also means "clear" or "of course"',
    usageExample: 'Me gusta el azul claro para las paredes.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_075',
    emoji: '🌑',
    question: '¿Qué palabra describe un color intenso como verde intenso?',
    translation: 'What word describes a deep color like dark green?',
    options: ['oscuro', 'claro', 'negro'],
    correctAnswer: 'oscuro',
    hint: 'Dark - deep color shade, "verde oscuro" (dark green), opposite of claro, from Latin "obscurus"',
    usageExample: 'Prefiero el verde oscuro para mi cuarto.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_076',
    emoji: '🕘',
    question: '¿Qué hora es?',
    translation: 'What time is it?',
    options: ['las nueve', 'son las nueve', 'nueve en punto'],
    correctAnswer: 'las nueve',
    hint: '9 o\'clock - "las nueve" or "son las nueve" (it\'s nine), "en punto" means sharp/exactly',
    usageExample: 'Son las nueve de la mañana, hora de trabajar.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'numbers_077',
    emoji: '🕛',
    question: '¿Qué hora es?',
    translation: 'What time is it?',
    options: ['las doce', 'son las doce', 'mediodía'],
    correctAnswer: 'las doce',
    hint: '12 o\'clock - "las doce" or "son las doce" (it\'s twelve), "mediodía" is noon, "medianoche" is midnight',
    usageExample: 'Son las doce del mediodía, vamos a almorzar.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'numbers_078',
    emoji: '🕒',
    question: '¿Qué hora es?',
    translation: 'What time is it?',
    options: ['las tres', 'son las tres', 'tres en punto'],
    correctAnswer: 'las tres',
    hint: '3 o\'clock - "las tres" or "son las tres" (it\'s three), afternoon time in most contexts',
    usageExample: 'La reunión es a las tres de la tarde.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'numbers_079',
    emoji: '🕕',
    question: '¿Qué hora es?',
    translation: 'What time is it?',
    options: ['las seis', 'son las seis', 'seis en punto'],
    correctAnswer: 'las seis',
    hint: '6 o\'clock - "las seis" or "son las seis" (it\'s six), can be morning or evening depending on context',
    usageExample: 'Cenamos siempre a las seis de la tarde.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  // Ordinal Numbers & More (21 questions)
  {
    id: 'numbers_080',
    emoji: '🥇',
    question: '¿Qué posición tiene el ganador de oro en una competencia?',
    translation: 'What position does the gold winner have in a competition?',
    options: ['primero', 'uno', 'primer'],
    correctAnswer: 'primero',
    hint: 'First - ordinal number, shortens to "primer" before masculine nouns (primer día = first day)',
    usageExample: 'Este es mi primer día de trabajo.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'numbers_081',
    emoji: '🥈',
    question: '¿Qué posición tiene el ganador de plata en una competencia?',
    translation: 'What position does the silver winner have in a competition?',
    options: ['segundo', 'dos', 'segunda'],
    correctAnswer: 'segundo',
    hint: 'Second - ordinal number, also means "second" (time unit), changes to "segunda" for feminine',
    usageExample: 'Mi hijo nació el segundo día del mes.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'numbers_082',
    emoji: '🥉',
    question: '¿Qué posición tiene el ganador de bronce en una competencia?',
    translation: 'What position does the bronze winner have in a competition?',
    options: ['tercero', 'tres', 'tercer'],
    correctAnswer: 'tercero',
    hint: 'Third - ordinal number, shortens to "tercer" before masculine nouns (tercer piso = third floor)',
    usageExample: 'Vivo en el tercer piso del edificio.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'numbers_083',
    emoji: '🔢',
    question: '¿Qué posición viene después de tercero?',
    translation: 'What position comes after third?',
    options: ['cuarto', 'cuatro', 'cuarta'],
    correctAnswer: 'cuarto',
    hint: 'Fourth - ordinal number, also means "room" or "quarter" (un cuarto de hora = quarter hour)',
    usageExample: 'Es la cuarta vez que te lo digo.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'numbers_084',
    emoji: '🔢',
    question: '¿Qué posición viene después de cuarto?',
    translation: 'What position comes after fourth?',
    options: ['quinto', 'cinco', 'quinta'],
    correctAnswer: 'quinto',
    hint: 'Fifth - ordinal number, from Latin "quintus", like "quintet"',
    usageExample: 'Quedé en quinto lugar en la carrera.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'numbers_085',
    emoji: '🔢',
    question: '¿Qué número es el objetivo del juego de cartas blackjack?',
    translation: 'What number is the goal of the card game blackjack?',
    options: ['veintiuno', 'veinte y uno', 'veinteyuno'],
    correctAnswer: 'veintiuno',
    hint: 'Twenty-one - combines "veinte" + "uno" into one word, used in blackjack game',
    usageExample: 'Mi hermano cumple veintiún años mañana.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_086',
    emoji: '🔢',
    question: '¿Cuántos días tiene el mes de enero?',
    translation: 'How many days does the month of January have?',
    options: ['treinta y uno', 'treinta uno', 'treintayuno'],
    correctAnswer: 'treinta y uno',
    hint: 'Thirty-one - written as three words with "y" (and) connecting them, days in some months',
    usageExample: 'El mes de enero tiene treinta y un días.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_087',
    emoji: '🔢',
    question: '¿Qué número está exactamente entre cuarenta y cincuenta?',
    translation: 'What number is exactly between forty and fifty?',
    options: ['cuarenta y cinco', 'cuarenta cinco', 'cuarentaycinco'],
    correctAnswer: 'cuarenta y cinco',
    hint: 'Forty-five - three words, 45 minutes is "y cuarenta y cinco" when telling time',
    usageExample: 'El autobús llega en cuarenta y cinco minutos.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_088',
    emoji: '🔢',
    question: '¿Qué número viene justo antes de cien?',
    translation: 'What number comes right before one hundred?',
    options: ['noventa y nueve', 'noventa nueve', 'noventaynueve'],
    correctAnswer: 'noventa y nueve',
    hint: 'Ninety-nine - highest two-digit number, "99 Luftballons" song reference',
    usageExample: 'El libro tiene noventa y nueve páginas.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_089',
    emoji: '💯',
    question: '¿Cuánto es cien más cien?',
    translation: 'How much is one hundred plus one hundred?',
    options: ['doscientos', 'dos cientos', 'doscientas'],
    correctAnswer: 'doscientos',
    hint: 'Two hundred - plural form, changes to "doscientas" for feminine nouns',
    usageExample: 'El vestido cuesta doscientos dólares.',
    points: 15,
    category: 'numbers',
    difficulty: 'hard',
    emotion: 'confused',
  },
  {
    id: 'numbers_090',
    emoji: '🔢',
    question: '¿Cuánto es la mitad de mil?',
    translation: 'How much is half of one thousand?',
    options: ['quinientos', 'cinco cientos', 'quinientas'],
    correctAnswer: 'quinientos',
    hint: 'Five hundred - notice spelling change from "cinco", changes to "quinientas" for feminine',
    usageExample: 'Hay quinientos estudiantes en la escuela.',
    points: 15,
    category: 'numbers',
    difficulty: 'hard',
    emotion: 'confused',
  },
  {
    id: 'numbers_091',
    emoji: '🔢',
    question: '¿Cuánto es mil multiplicado por mil?',
    translation: 'How much is one thousand multiplied by one thousand?',
    options: ['un millón', 'millón', 'uno millón'],
    correctAnswer: 'un millón',
    hint: 'One million - masculine noun, uses "un" before it, requires "de" before another noun',
    usageExample: 'La ciudad tiene más de un millón de habitantes.',
    points: 15,
    category: 'numbers',
    difficulty: 'hard',
    emotion: 'confused',
  },
  {
    id: 'numbers_092',
    emoji: '🕐',
    question: '¿Cuánto tiempo son treinta minutos?',
    translation: 'How much time is thirty minutes?',
    options: ['media hora', 'mitad hora', 'media de hora'],
    correctAnswer: 'media hora',
    hint: 'Half an hour - "media" (feminine) + "hora" (hour), 30 minutes',
    usageExample: 'Llego en media hora, espérame.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_093',
    emoji: '🕐',
    question: '¿Cuánto tiempo son quince minutos?',
    translation: 'How much time is fifteen minutes?',
    options: ['un cuarto de hora', 'un cuarto hora', 'cuarto de hora'],
    correctAnswer: 'un cuarto de hora',
    hint: 'Quarter hour - "cuarto" means "quarter" or "fourth", 15 minutes',
    usageExample: 'La tienda abre en un cuarto de hora.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_094',
    emoji: '📅',
    question: '¿Cómo se llama el período de sábado y domingo?',
    translation: 'What is the period of Saturday and Sunday called?',
    options: ['fin de semana', 'final de semana', 'final semana'],
    correctAnswer: 'fin de semana',
    hint: 'Weekend - literally "end of week", Saturday and Sunday',
    usageExample: 'Voy a la playa este fin de semana.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_095',
    emoji: '📅',
    question: '¿Qué período de tiempo tiene aproximadamente treinta días?',
    translation: 'What period of time has approximately thirty days?',
    options: ['mes', 'mez', 'mese'],
    correctAnswer: 'mes',
    hint: 'Month - from Latin "mensis", 12 months in a year',
    usageExample: 'Este mes viajo a España de vacaciones.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_096',
    emoji: '📅',
    question: '¿Qué período de tiempo tiene veinticuatro horas?',
    translation: 'What period of time has twenty-four hours?',
    options: ['día', 'dias', 'dia'],
    correctAnswer: 'día',
    hint: 'Day - masculine noun despite ending in "a", 24 hours, "Buenos días" = Good morning',
    usageExample: 'Hoy es un día perfecto para pasear.',
    points: 5,
    category: 'numbers',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'numbers_097',
    emoji: '⏰',
    question: '¿Qué hora es a las doce de la noche?',
    translation: 'What time is it at twelve at night?',
    options: ['medianoche', 'media noche', 'noche media'],
    correctAnswer: 'medianoche',
    hint: 'Midnight - "media" (middle) + "noche" (night), 12:00 AM, one word',
    usageExample: 'Nos vemos a medianoche en la plaza.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_098',
    emoji: '☀️',
    question: '¿Qué hora es a las doce del día?',
    translation: 'What time is it at twelve during the day?',
    options: ['mediodía', 'medio día', 'día medio'],
    correctAnswer: 'mediodía',
    hint: 'Noon/Midday - "medio" (middle) + "día" (day), 12:00 PM, one word',
    usageExample: 'Almorzamos todos los días al mediodía.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_099',
    emoji: '🔢',
    question: '¿Cuántas veces es hacer algo solamente una ocasión?',
    translation: 'How many times is doing something only one occasion?',
    options: ['una vez', 'un vez', 'una tiempo'],
    correctAnswer: 'una vez',
    hint: 'Once/one time - "vez" is feminine, "dos veces" = twice, "tres veces" = three times',
    usageExample: 'Sólo te lo diré una vez más.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'numbers_100',
    emoji: '🔢',
    question: '¿Cuántas veces es hacer algo en dos ocasiones?',
    translation: 'How many times is doing something on two occasions?',
    options: ['dos veces', 'dos vez', 'doble'],
    correctAnswer: 'dos veces',
    hint: 'Twice/two times - "veces" is plural of "vez", "doble" means "double" (different usage)',
    usageExample: 'Voy al gimnasio dos veces por semana.',
    points: 10,
    category: 'numbers',
    difficulty: 'medium',
    emotion: 'pleased',
  },

];
