/**
 * People & Relationships Category Questions
 * Category: people
 */

export const peopleQuestions = [
  // Family Members (20 questions)
  {
    id: 'people_001',
    emoji: '👨',
    question: '¿Cómo se dice "father" en español?',
    translation: 'How do you say \'father\' in Spanish?',
    options: ['el padre', 'el tío', 'el abuelo'],
    correctAnswer: 'el padre',
    hint: 'Father - "papá" is informal, masculine',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_002',
    emoji: '👩',
    question: '¿Cómo se dice "mother" en español?',
    translation: 'How do you say \'mother\' in Spanish?',
    options: ['la madre', 'la tía', 'la abuela'],
    correctAnswer: 'la madre',
    hint: 'Mother - "mamá" is informal, feminine',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'people_003',
    emoji: '👦',
    question: '¿Cómo se llama un hijo varón?',
    translation: 'What is a male child called?',
    options: ['el hijo', 'el hermano', 'el primo'],
    correctAnswer: 'el hijo',
    hint: 'Son - male child, "hija" is daughter',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_004',
    emoji: '👧',
    question: '¿Cómo se llama una hija?',
    translation: 'What is a daughter called?',
    options: ['la hija', 'la hermana', 'la prima'],
    correctAnswer: 'la hija',
    hint: 'Daughter - female child, "hijo" is son',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_005',
    emoji: '👴',
    question: '¿Cómo se dice "grandfather" en español?',
    translation: 'How do you say \'grandfather\' in Spanish?',
    options: ['el abuelo', 'el padre', 'el tío'],
    correctAnswer: 'el abuelo',
    hint: 'Grandfather - "abuelito" is affectionate diminutive',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'people_006',
    emoji: '👵',
    question: '¿Cómo se dice "grandmother" en español?',
    translation: 'How do you say \'grandmother\' in Spanish?',
    options: ['la abuela', 'la madre', 'la tía'],
    correctAnswer: 'la abuela',
    hint: 'Grandmother - "abuelita" is affectionate diminutive',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'people_007',
    emoji: '👨‍👦',
    question: '¿Cómo se dice "brother" en español?',
    translation: 'How do you say \'brother\' in Spanish?',
    options: ['el hermano', 'el primo', 'el hijo'],
    correctAnswer: 'el hermano',
    hint: 'Brother - "hermana" is sister, same family',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_008',
    emoji: '👩‍👧',
    question: '¿Cómo se dice "sister" en español?',
    translation: 'How do you say \'sister\' in Spanish?',
    options: ['la hermana', 'la prima', 'la hija'],
    correctAnswer: 'la hermana',
    hint: 'Sister - "hermano" is brother, same family',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_009',
    emoji: '👨‍👦‍👦',
    question: '¿Cómo se dice "uncle" en español?',
    translation: 'How do you say \'uncle\' in Spanish?',
    options: ['el tío', 'el padre', 'el abuelo'],
    correctAnswer: 'el tío',
    hint: 'Uncle - parent\'s brother, "tía" is aunt',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_010',
    emoji: '👩‍👧‍👧',
    question: '¿Cómo se dice "aunt" en español?',
    translation: 'How do you say \'aunt\' in Spanish?',
    options: ['la tía', 'la madre', 'la abuela'],
    correctAnswer: 'la tía',
    hint: 'Aunt - parent\'s sister, "tío" is uncle',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_011',
    emoji: '👦👧',
    question: '¿Cómo se dice "cousin" (masculino)?',
    translation: 'How do you say \'cousin\' (masculine)?',
    options: ['el primo', 'el hermano', 'el sobrino'],
    correctAnswer: 'el primo',
    hint: 'Male cousin - child of uncle/aunt, "prima" is female',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_012',
    emoji: '👫',
    question: '¿Cómo se dice "cousin" (femenino)?',
    translation: 'How do you say \'cousin\' (feminine)?',
    options: ['la prima', 'la hermana', 'la sobrina'],
    correctAnswer: 'la prima',
    hint: 'Female cousin - child of uncle/aunt, "primo" is male',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_013',
    emoji: '👶',
    question: '¿Cómo se dice "baby" en español?',
    translation: 'How do you say \'baby\' in Spanish?',
    options: ['el bebé', 'el niño', 'el hijo'],
    correctAnswer: 'el bebé',
    hint: 'Baby - very young child, "bebé" works for both genders',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'people_014',
    emoji: '👨‍👩‍👧',
    question: '¿Cómo se dice "nephew" en español?',
    translation: 'How do you say \'nephew\' in Spanish?',
    options: ['el sobrino', 'el primo', 'el hijo'],
    correctAnswer: 'el sobrino',
    hint: 'Nephew - brother/sister\'s son, "sobrina" is niece',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_015',
    emoji: '👨‍👩‍👧‍👦',
    question: '¿Cómo se dice "niece" en español?',
    translation: 'How do you say \'niece\' in Spanish?',
    options: ['la sobrina', 'la prima', 'la hija'],
    correctAnswer: 'la sobrina',
    hint: 'Niece - brother/sister\'s daughter, "sobrino" is nephew',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_016',
    emoji: '💑',
    question: '¿Cómo se dice "husband" en español?',
    translation: 'How do you say \'husband\' in Spanish?',
    options: ['el esposo', 'el novio', 'el padre'],
    correctAnswer: 'el esposo',
    hint: 'Husband - married man, "marido" is also correct',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'people_017',
    emoji: '👰',
    question: '¿Cómo se dice "wife" en español?',
    translation: 'How do you say \'wife\' in Spanish?',
    options: ['la esposa', 'la novia', 'la madre'],
    correctAnswer: 'la esposa',
    hint: 'Wife - married woman, "mujer" is also used',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'people_018',
    emoji: '💏',
    question: '¿Cómo se dice "boyfriend" en español?',
    translation: 'How do you say \'boyfriend\' in Spanish?',
    options: ['el novio', 'el esposo', 'el amigo'],
    correctAnswer: 'el novio',
    hint: 'Boyfriend - romantic partner, not married yet',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'people_019',
    emoji: '💑',
    question: '¿Cómo se dice "girlfriend" en español?',
    translation: 'How do you say \'girlfriend\' in Spanish?',
    options: ['la novia', 'la esposa', 'la amiga'],
    correctAnswer: 'la novia',
    hint: 'Girlfriend - romantic partner, not married yet',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'people_020',
    emoji: '👨‍👩‍👧‍👦',
    question: '¿Cómo se dice "family" en español?',
    translation: 'How do you say \'family\' in Spanish?',
    options: ['la familia', 'los padres', 'los hermanos'],
    correctAnswer: 'la familia',
    hint: 'Family - all relatives together, feminine noun',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'happy',
  },

  // Professions (30 questions)
  {
    id: 'people_021',
    emoji: '👨‍⚕️',
    question: '¿Cómo se dice "doctor" (masculino)?',
    translation: 'How do you say \'doctor\' (masculine)?',
    options: ['el médico', 'el enfermero', 'el dentista'],
    correctAnswer: 'el médico',
    hint: 'Male doctor - medical professional, "doctor" also works',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'people_022',
    emoji: '👩‍⚕️',
    question: '¿Cómo se dice "doctor" (femenino)?',
    translation: 'How do you say \'doctor\' (feminine)?',
    options: ['la médica', 'la enfermera', 'la dentista'],
    correctAnswer: 'la médica',
    hint: 'Female doctor - medical professional, "doctora" also works',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'people_023',
    emoji: '👨‍🏫',
    question: '¿Cómo se dice "teacher" (masculino)?',
    translation: 'How do you say \'teacher\' (masculine)?',
    options: ['el maestro', 'el estudiante', 'el director'],
    correctAnswer: 'el maestro',
    hint: 'Male teacher - "profesor" for higher education',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_024',
    emoji: '👩‍🏫',
    question: '¿Cómo se dice "teacher" (femenino)?',
    translation: 'How do you say \'teacher\' (feminine)?',
    options: ['la maestra', 'la estudiante', 'la directora'],
    correctAnswer: 'la maestra',
    hint: 'Female teacher - "profesora" for higher education',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_025',
    emoji: '👨‍🎓',
    question: '¿Cómo se dice "student" (masculino)?',
    translation: 'How do you say \'student\' (masculine)?',
    options: ['el estudiante', 'el maestro', 'el alumno'],
    correctAnswer: 'el estudiante',
    hint: 'Male student - "alumno" is also common',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'people_026',
    emoji: '👩‍🎓',
    question: '¿Cómo se dice "student" (femenino)?',
    translation: 'How do you say \'student\' (feminine)?',
    options: ['la estudiante', 'la maestra', 'la alumna'],
    correctAnswer: 'la estudiante',
    hint: 'Female student - "alumna" is also common',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'people_027',
    emoji: '👨‍💼',
    question: '¿Cómo se dice "businessman"?',
    translation: 'How do you say \'businessman\'?',
    options: ['el hombre de negocios', 'el vendedor', 'el jefe'],
    correctAnswer: 'el hombre de negocios',
    hint: 'Businessman - "empresario" is entrepreneur',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_028',
    emoji: '👩‍💼',
    question: '¿Cómo se dice "businesswoman"?',
    translation: 'How do you say \'businesswoman\'?',
    options: ['la mujer de negocios', 'la vendedora', 'la jefa'],
    correctAnswer: 'la mujer de negocios',
    hint: 'Businesswoman - "empresaria" is entrepreneur',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_029',
    emoji: '👨‍🍳',
    question: '¿Cómo se dice "chef" o "cook"?',
    translation: 'How do you say \'chef\' or \'cook\'?',
    options: ['el cocinero', 'el camarero', 'el panadero'],
    correctAnswer: 'el cocinero',
    hint: 'Male cook - "chef" is also used, from French',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_030',
    emoji: '👩‍🍳',
    question: '¿Cómo se dice "chef" o "cook" (femenino)?',
    translation: 'How do you say \'chef\' or \'cook\' (feminine)?',
    options: ['la cocinera', 'la camarera', 'la panadera'],
    correctAnswer: 'la cocinera',
    hint: 'Female cook - "chef" is also used, from French',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_031',
    emoji: '👮‍♂️',
    question: '¿Cómo se dice "police officer" (masculino)?',
    translation: 'How do you say \'police officer\' (masculine)?',
    options: ['el policía', 'el bombero', 'el soldado'],
    correctAnswer: 'el policía',
    hint: 'Male police officer - keeps order and safety',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'people_032',
    emoji: '👮‍♀️',
    question: '¿Cómo se dice "police officer" (femenino)?',
    translation: 'How do you say \'police officer\' (feminine)?',
    options: ['la policía', 'la bombera', 'la soldado'],
    correctAnswer: 'la policía',
    hint: 'Female police officer - keeps order and safety',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'people_033',
    emoji: '👨‍🚒',
    question: '¿Cómo se dice "firefighter"?',
    translation: 'How do you say \'firefighter\'?',
    options: ['el bombero', 'el policía', 'el paramédico'],
    correctAnswer: 'el bombero',
    hint: 'Firefighter - fights fires, "bomba" means pump',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'people_034',
    emoji: '👨‍⚖️',
    question: '¿Cómo se dice "lawyer"?',
    translation: 'How do you say \'lawyer\'?',
    options: ['el abogado', 'el juez', 'el fiscal'],
    correctAnswer: 'el abogado',
    hint: 'Male lawyer - represents clients in court',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_035',
    emoji: '👩‍⚖️',
    question: '¿Cómo se dice "lawyer" (femenino)?',
    translation: 'How do you say \'lawyer\' (feminine)?',
    options: ['la abogada', 'la jueza', 'la fiscal'],
    correctAnswer: 'la abogada',
    hint: 'Female lawyer - represents clients in court',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_036',
    emoji: '👨‍🔧',
    question: '¿Cómo se dice "mechanic"?',
    translation: 'How do you say \'mechanic\'?',
    options: ['el mecánico', 'el plomero', 'el electricista'],
    correctAnswer: 'el mecánico',
    hint: 'Mechanic - fixes cars and machines',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_037',
    emoji: '👨‍🌾',
    question: '¿Cómo se dice "farmer"?',
    translation: 'How do you say \'farmer\'?',
    options: ['el granjero', 'el jardinero', 'el pescador'],
    correctAnswer: 'el granjero',
    hint: 'Farmer - works on farm, "agricultor" is also used',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_038',
    emoji: '👨‍✈️',
    question: '¿Cómo se dice "pilot"?',
    translation: 'How do you say \'pilot\'?',
    options: ['el piloto', 'el capitán', 'el navegante'],
    correctAnswer: 'el piloto',
    hint: 'Pilot - flies airplanes, same word for male/female',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_039',
    emoji: '👨‍🎨',
    question: '¿Cómo se dice "artist"?',
    translation: 'How do you say \'artist\'?',
    options: ['el artista', 'el pintor', 'el músico'],
    correctAnswer: 'el artista',
    hint: 'Artist - creates art, same word for male/female',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_040',
    emoji: '👨‍🎤',
    question: '¿Cómo se dice "singer"?',
    translation: 'How do you say \'singer\'?',
    options: ['el cantante', 'el músico', 'el bailarín'],
    correctAnswer: 'el cantante',
    hint: 'Singer - sings songs, "cantar" means to sing',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'people_041',
    emoji: '👨‍💻',
    question: '¿Cómo se dice "programmer"?',
    translation: 'How do you say \'programmer\'?',
    options: ['el programador', 'el ingeniero', 'el técnico'],
    correctAnswer: 'el programador',
    hint: 'Programmer - writes code, "programar" means to program',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_042',
    emoji: '👨‍🔬',
    question: '¿Cómo se dice "scientist"?',
    translation: 'How do you say \'scientist\'?',
    options: ['el científico', 'el investigador', 'el profesor'],
    correctAnswer: 'el científico',
    hint: 'Scientist - studies science, from "ciencia"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_043',
    emoji: '👨‍🏭',
    question: '¿Cómo se dice "worker"?',
    translation: 'How do you say \'worker\'?',
    options: ['el trabajador', 'el obrero', 'el empleado'],
    correctAnswer: 'el trabajador',
    hint: 'Worker - anyone who works, from "trabajar"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'people_044',
    emoji: '👩‍💼',
    question: '¿Cómo se dice "secretary"?',
    translation: 'How do you say \'secretary\'?',
    options: ['la secretaria', 'la asistente', 'la gerente'],
    correctAnswer: 'la secretaria',
    hint: 'Secretary - assists in office, manages documents',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_045',
    emoji: '👨‍🍳',
    question: '¿Cómo se dice "waiter"?',
    translation: 'How do you say \'waiter\'?',
    options: ['el camarero', 'el cocinero', 'el chef'],
    correctAnswer: 'el camarero',
    hint: 'Waiter - serves in restaurant, "mesero" in Latin America',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_046',
    emoji: '👩‍🍳',
    question: '¿Cómo se dice "waitress"?',
    translation: 'How do you say \'waitress\'?',
    options: ['la camarera', 'la cocinera', 'la chef'],
    correctAnswer: 'la camarera',
    hint: 'Waitress - serves in restaurant, "mesera" in Latin America',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_047',
    emoji: '🧑‍🎨',
    question: '¿Cómo se dice "painter"?',
    translation: 'How do you say \'painter\'?',
    options: ['el pintor', 'el artista', 'el dibujante'],
    correctAnswer: 'el pintor',
    hint: 'Painter - paints pictures, from "pintar"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_048',
    emoji: '👨‍🔧',
    question: '¿Cómo se dice "plumber"?',
    translation: 'How do you say \'plumber\'?',
    options: ['el plomero', 'el mecánico', 'el electricista'],
    correctAnswer: 'el plomero',
    hint: 'Plumber - fixes pipes and water systems',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_049',
    emoji: '⚡',
    question: '¿Cómo se dice "electrician"?',
    translation: 'How do you say \'electrician\'?',
    options: ['el electricista', 'el mecánico', 'el plomero'],
    correctAnswer: 'el electricista',
    hint: 'Electrician - works with electricity and wiring',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_050',
    emoji: '👨‍💼',
    question: '¿Cómo se dice "boss" o "manager"?',
    translation: 'How do you say \'boss\' or \'manager\'?',
    options: ['el jefe', 'el gerente', 'el director'],
    correctAnswer: 'el jefe',
    hint: 'Boss - person in charge, "gerente" is manager',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'determined',
  },

  // Physical Descriptions (25 questions)
  {
    id: 'people_051',
    emoji: 'young.png',
    question: '¿Cómo se dice "young"?',
    translation: 'How do you say \'young\'?',
    options: ['joven', 'viejo', 'nuevo'],
    correctAnswer: 'joven',
    hint: 'Young - not old, "juventud" is youth',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'people_052',
    emoji: '👴',
    question: '¿Cómo se dice "old" (person)?',
    translation: 'How do you say \'old\' (person)?',
    options: ['viejo', 'anciano', 'mayor'],
    correctAnswer: 'viejo',
    hint: 'Old - not young, "anciano" is elderly',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'calm',
  },

  {
    id: 'people_055',
    emoji: '💪',
    question: '¿Cómo se dice "strong"?',
    translation: 'How do you say \'strong\'?',
    options: ['fuerte', 'débil', 'musculoso'],
    correctAnswer: 'fuerte',
    hint: 'Strong - powerful, opposite of "débil"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'people_056',
    emoji: '😌',
    question: '¿Cómo se dice "weak"?',
    translation: 'How do you say \'weak\'?',
    options: ['débil', 'fuerte', 'cansado'],
    correctAnswer: 'débil',
    hint: 'Weak - not strong, opposite of "fuerte"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'hurt',
  },
  {
    id: 'people_057',
    emoji: 'pretty.png',
    question: '¿Cómo se dice "pretty" o "beautiful"?',
    translation: 'How do you say \'pretty\' or \'beautiful\'?',
    options: ['bonito', 'feo', 'hermoso'],
    correctAnswer: 'bonito',
    hint: 'Pretty - attractive, "hermoso" is also correct',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_058',
    emoji: '😞',
    question: '¿Cómo se dice "ugly"?',
    translation: 'How do you say \'ugly\'?',
    options: ['feo', 'bonito', 'malo'],
    correctAnswer: 'feo',
    hint: 'Ugly - not attractive, opposite of "bonito"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'sad',
  },
  {
    id: 'people_059',
    emoji: '😃',
    question: '¿Cómo se dice "happy"?',
    translation: 'How do you say \'happy\'?',
    options: ['feliz', 'triste', 'alegre'],
    correctAnswer: 'feliz',
    hint: 'Happy - joyful, "alegre" is also correct',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'people_060',
    emoji: '😢',
    question: '¿Cómo se dice "sad"?',
    translation: 'How do you say \'sad\'?',
    options: ['triste', 'feliz', 'enojado'],
    correctAnswer: 'triste',
    hint: 'Sad - unhappy, opposite of "feliz"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'sad',
  },
  {
    id: 'people_061',
    emoji: '😠',
    question: '¿Cómo se dice "angry"?',
    translation: 'How do you say \'angry\'?',
    options: ['enojado', 'feliz', 'cansado'],
    correctAnswer: 'enojado',
    hint: 'Angry - mad, "enfadado" is also used',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'angry',
  },
  {
    id: 'people_062',
    emoji: '😴',
    question: '¿Cómo se dice "tired"?',
    translation: 'How do you say \'tired\'?',
    options: ['cansado', 'despierto', 'dormido'],
    correctAnswer: 'cansado',
    hint: 'Tired - exhausted, from "cansar"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'hurt',
  },
  {
    id: 'people_063',
    emoji: '🤓',
    question: '¿Cómo se dice "intelligent"?',
    translation: 'How do you say \'intelligent\'?',
    options: ['inteligente', 'tonto', 'listo'],
    correctAnswer: 'inteligente',
    hint: 'Intelligent - smart, "listo" means clever',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_064',
    emoji: '😇',
    question: '¿Cómo se dice "nice" o "kind"?',
    translation: 'How do you say \'nice\' or \'kind\'?',
    options: ['amable', 'malo', 'simpático'],
    correctAnswer: 'amable',
    hint: 'Nice - kind person, "simpático" is friendly',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_065',
    emoji: '😈',
    question: '¿Cómo se dice "mean" o "bad"?',
    translation: 'How do you say \'mean\' or \'bad\'?',
    options: ['malo', 'bueno', 'cruel'],
    correctAnswer: 'malo',
    hint: 'Bad - not good, opposite of "bueno"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'angry',
  },
  {
    id: 'people_066',
    emoji: '💇',
    question: '¿Cómo se dice con pelo rubio?',
    translation: 'How do you say with blond hair?',
    options: ['rubio', 'moreno', 'pelirrojo'],
    correctAnswer: 'rubio',
    hint: 'Blond - light hair color, "rubia" for feminine',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_067',
    emoji: '💇‍♂️',
    question: '¿Cómo se dice con pelo castaño/moreno?',
    translation: 'How do you say with brown/dark hair?',
    options: ['moreno', 'rubio', 'pelirrojo'],
    correctAnswer: 'moreno',
    hint: 'Dark-haired - brunette, "castaño" is brown',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_069',
    emoji: '👁️',
    question: '¿Cómo se dice "eyes" en español?',
    translation: 'How do you say \'eyes\' in Spanish?',
    options: ['los ojos', 'las orejas', 'las cejas'],
    correctAnswer: 'los ojos',
    hint: 'Eyes - organs of sight, "ojo" is singular',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_070',
    emoji: '👃',
    question: '¿Cómo se dice "nose" en español?',
    translation: 'How do you say \'nose\' in Spanish?',
    options: ['la nariz', 'la boca', 'la oreja'],
    correctAnswer: 'la nariz',
    hint: 'Nose - organ of smell, feminine noun',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_071',
    emoji: '👄',
    question: '¿Cómo se dice "mouth" en español?',
    translation: 'How do you say \'mouth\' in Spanish?',
    options: ['la boca', 'la nariz', 'el labio'],
    correctAnswer: 'la boca',
    hint: 'Mouth - for eating and speaking, feminine',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_072',
    emoji: '👂',
    question: '¿Cómo se dice "ear" en español?',
    translation: 'How do you say \'ear\' in Spanish?',
    options: ['la oreja', 'el ojo', 'la nariz'],
    correctAnswer: 'la oreja',
    hint: 'Ear - organ of hearing, "oído" is inner ear',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_073',
    emoji: '✋',
    question: '¿Cómo se dice "hand" en español?',
    translation: 'How do you say \'hand\' in Spanish?',
    options: ['la mano', 'el brazo', 'el dedo'],
    correctAnswer: 'la mano',
    hint: 'Hand - at end of arm, feminine despite ending in -o',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_074',
    emoji: '🦵',
    question: '¿Cómo se dice "leg" en español?',
    translation: 'How do you say \'leg\' in Spanish?',
    options: ['la pierna', 'el brazo', 'el pie'],
    correctAnswer: 'la pierna',
    hint: 'Leg - from hip to foot, feminine noun',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_075',
    emoji: '🦶',
    question: '¿Cómo se dice "foot" en español?',
    translation: 'How do you say \'foot\' in Spanish?',
    options: ['el pie', 'la pierna', 'la mano'],
    correctAnswer: 'el pie',
    hint: 'Foot - at end of leg, masculine noun',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },

  // Personality & Character Traits (15 questions)
  {
    id: 'people_076',
    emoji: '🤗',
    question: '¿Cómo se dice "friendly"?',
    translation: 'How do you say \'friendly\'?',
    options: ['amistoso', 'antipático', 'tímido'],
    correctAnswer: 'amistoso',
    hint: 'Friendly - sociable, "simpático" also means friendly',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'people_077',
    emoji: '😏',
    question: '¿Cómo se dice "funny"?',
    translation: 'How do you say \'funny\'?',
    options: ['gracioso', 'serio', 'aburrido'],
    correctAnswer: 'gracioso',
    hint: 'Funny - makes people laugh, "chistoso" is also used',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'people_078',
    emoji: '🤐',
    question: '¿Cómo se dice "shy"?',
    translation: 'How do you say \'shy\'?',
    options: ['tímido', 'atrevido', 'sociable'],
    correctAnswer: 'tímido',
    hint: 'Shy - quiet, reserved, opposite of outgoing',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'people_079',
    emoji: '😎',
    question: '¿Cómo se dice "brave"?',
    translation: 'How do you say \'brave\'?',
    options: ['valiente', 'cobarde', 'tímido'],
    correctAnswer: 'valiente',
    hint: 'Brave - courageous, opposite of "cobarde"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_080',
    emoji: '🤥',
    question: '¿Cómo se dice "honest"?',
    translation: 'How do you say \'honest\'?',
    options: ['honesto', 'mentiroso', 'sincero'],
    correctAnswer: 'honesto',
    hint: 'Honest - truthful, "sincero" is sincere',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_081',
    emoji: '😤',
    question: '¿Cómo se dice "patient"?',
    translation: 'How do you say \'patient\'?',
    options: ['paciente', 'impaciente', 'tranquilo'],
    correctAnswer: 'paciente',
    hint: 'Patient - can wait calmly, opposite of impatient',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'people_082',
    emoji: '🤓',
    question: '¿Cómo se dice "studious" o "hardworking"?',
    translation: 'How do you say \'studious\' or \'hardworking\'?',
    options: ['trabajador', 'perezoso', 'estudioso'],
    correctAnswer: 'trabajador',
    hint: 'Hardworking - diligent, "estudioso" is studious',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_083',
    emoji: '😴',
    question: '¿Cómo se dice "lazy"?',
    translation: 'How do you say \'lazy\'?',
    options: ['perezoso', 'trabajador', 'activo'],
    correctAnswer: 'perezoso',
    hint: 'Lazy - doesn\'t like to work, opposite of hardworking',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_084',
    emoji: '💰',
    question: '¿Cómo se dice "generous"?',
    translation: 'How do you say \'generous\'?',
    options: ['generoso', 'tacaño', 'egoísta'],
    correctAnswer: 'generoso',
    hint: 'Generous - gives freely, opposite of "tacaño" (stingy)',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_085',
    emoji: '😌',
    question: '¿Cómo se dice "calm" o "quiet"?',
    translation: 'How do you say \'calm\' or \'quiet\'?',
    options: ['tranquilo', 'nervioso', 'ruidoso'],
    correctAnswer: 'tranquilo',
    hint: 'Calm - peaceful, "quieto" means still',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'people_086',
    emoji: '😰',
    question: '¿Cómo se dice "nervous"?',
    translation: 'How do you say \'nervous\'?',
    options: ['nervioso', 'tranquilo', 'calmado'],
    correctAnswer: 'nervioso',
    hint: 'Nervous - anxious, opposite of "tranquilo"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'people_087',
    emoji: '🎯',
    question: '¿Cómo se dice "responsible"?',
    translation: 'How do you say \'responsible\'?',
    options: ['responsable', 'irresponsable', 'serio'],
    correctAnswer: 'responsable',
    hint: 'Responsible - reliable, can be trusted',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_088',
    emoji: '😌',
    question: '¿Cómo se dice "polite"?',
    translation: 'How do you say \'polite\'?',
    options: ['educado', 'grosero', 'cortés'],
    correctAnswer: 'educado',
    hint: 'Polite - well-mannered, "cortés" is courteous',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_089',
    emoji: '😠',
    question: '¿Cómo se dice "rude"?',
    translation: 'How do you say \'rude\'?',
    options: ['grosero', 'educado', 'cortés'],
    correctAnswer: 'grosero',
    hint: 'Rude - impolite, opposite of "educado"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'angry',
  },
  {
    id: 'people_090',
    emoji: '🤝',
    question: '¿Cómo se dice "helpful"?',
    translation: 'How do you say \'helpful\'?',
    options: ['servicial', 'egoísta', 'útil'],
    correctAnswer: 'servicial',
    hint: 'Helpful - likes to help others, "útil" means useful',
    points: 5,
    category: 'people',
    difficulty: 'hard',
    emotion: 'pleased',
  },

  // Age & Life Stages (10 questions)
  {
    id: 'people_091',
    emoji: '👶',
    question: '¿Cómo se dice "child" o "kid"?',
    translation: 'How do you say \'child\' or \'kid\'?',
    options: ['el niño', 'el bebé', 'el adolescente'],
    correctAnswer: 'el niño',
    hint: 'Child - young person, "niña" is girl',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_092',
    emoji: '🧒',
    question: '¿Cómo se dice "boy"?',
    translation: 'How do you say \'boy\'?',
    options: ['el niño', 'el chico', 'el hombre'],
    correctAnswer: 'el niño',
    hint: 'Boy - young male, "chico" is also used',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_093',
    emoji: '👧',
    question: '¿Cómo se dice "girl"?',
    translation: 'How do you say \'girl\'?',
    options: ['la niña', 'la chica', 'la mujer'],
    correctAnswer: 'la niña',
    hint: 'Girl - young female, "chica" is also used',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_094',
    emoji: '🧑',
    question: '¿Cómo se dice "man"?',
    translation: 'How do you say \'man\'?',
    options: ['el hombre', 'el niño', 'el chico'],
    correctAnswer: 'el hombre',
    hint: 'Man - adult male, "hombres" is plural',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_095',
    emoji: '👩',
    question: '¿Cómo se dice "woman"?',
    translation: 'How do you say \'woman\'?',
    options: ['la mujer', 'la niña', 'la chica'],
    correctAnswer: 'la mujer',
    hint: 'Woman - adult female, "mujeres" is plural',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_096',
    emoji: '🧒',
    question: '¿Cómo se dice "teenager"?',
    translation: 'How do you say \'teenager\'?',
    options: ['el adolescente', 'el niño', 'el adulto'],
    correctAnswer: 'el adolescente',
    hint: 'Teenager - between child and adult, 13-19 years',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'people_097',
    emoji: '🧑',
    question: '¿Cómo se dice "adult"?',
    translation: 'How do you say \'adult\'?',
    options: ['el adulto', 'el niño', 'el joven'],
    correctAnswer: 'el adulto',
    hint: 'Adult - fully grown person, mature',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_098',
    emoji: '👵',
    question: '¿Cómo se dice "elderly person"?',
    translation: 'How do you say \'elderly person\'?',
    options: ['el anciano', 'el viejo', 'el mayor'],
    correctAnswer: 'el anciano',
    hint: 'Elderly - very old person, "anciana" is feminine',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'people_099',
    emoji: '👤',
    question: '¿Cómo se dice "person"?',
    translation: 'How do you say \'person\'?',
    options: ['la persona', 'el hombre', 'la gente'],
    correctAnswer: 'la persona',
    hint: 'Person - individual, always feminine even for males',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_100',
    emoji: '👥',
    question: '¿Cómo se dice "people" (colectivo)?',
    translation: 'How do you say \'people\' (collective)?',
    options: ['la gente', 'las personas', 'los hombres'],
    correctAnswer: 'la gente',
    hint: 'People - group of persons, singular feminine noun',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },

  {
    id: 'people_102',
    emoji: '🔞',
    question: '¿Qué significa "solo para mayores de 18 años"?',
    translation: 'What does \'only for over 18 years old\' mean?',
    options: ['restricción de edad', 'permiso especial', 'entrada gratis'],
    correctAnswer: 'restricción de edad',
    hint: 'Age restriction - "restricción de edad", content or places limited to adults',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_103',
    emoji: '👨‍🍼',
    question: '¿Qué haces cuando un bebé tiene hambre?',
    translation: 'What do you do when a baby is hungry?',
    options: ['le doy de comer', 'lo ignoro', 'lo baño'],
    correctAnswer: 'le doy de comer',
    hint: 'Feed the baby - "dar de comer", caring for an infant by feeding',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_104',
    emoji: '🥸',
    question: '¿Cómo se llama alguien que finge ser otra persona?',
    translation: 'What do you call someone who pretends to be another person?',
    options: ['el impostor', 'el mentiroso', 'el actor'],
    correctAnswer: 'el impostor',
    hint: 'Imposter - "impostor", someone who pretends to be someone else to deceive',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'people_105',
    emoji: '🥹',
    question: '¿Cómo se llama el estado emocional de tristeza profunda?',
    translation: 'What is the emotional state of deep sadness called?',
    options: ['la depresión', 'la alegría', 'la ansiedad'],
    correctAnswer: 'la depresión',
    hint: 'Depression - "depresión", deep emotional sadness, a mental health condition',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'sad',
  },
  {
    id: 'people_107',
    emoji: '⚖️',
    question: '¿Por qué las personas buscan la justicia?',
    translation: 'Why do people seek justice?',
    options: ['para que se haga lo correcto', 'para vengarse', 'para ganar dinero'],
    correctAnswer: 'para que se haga lo correcto',
    hint: 'Why people seek justice - "para que se haga lo correcto", to ensure fairness and what is right',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_108',
    emoji: '🪦',
    question: '¿Qué haces cuando visitas a un familiar fallecido?',
    translation: 'What do you do when you visit a deceased family member?',
    options: ['visito su tumba', 'voy al hospital', 'llamo por teléfono'],
    correctAnswer: 'visito su tumba',
    hint: 'Visit their grave - "visitar la tumba", honoring deceased family members at the cemetery',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'sad',
  },
  {
    id: 'people_109',
    emoji: '🤬',
    question: '¿Qué hace alguien cuando dice palabras groseras?',
    translation: 'What does someone do when they say rude words?',
    options: ['maldice', 'felicita', 'saluda'],
    correctAnswer: 'maldice',
    hint: 'Swear/curse - "maldecir", using offensive or vulgar language when angry',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'angry',
  },
  {
    id: 'people_110',
    emoji: '👩🏿‍⚖️',
    question: '¿Quién decide el veredicto en un tribunal?',
    translation: 'Who decides the verdict in a court?',
    options: ['el juez', 'el abogado', 'el testigo'],
    correctAnswer: 'el juez',
    hint: 'Judge - presides over court proceedings and makes legal decisions',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_111',
    emoji: '👨🏻‍🎓',
    question: '¿Quién estudia en la universidad?',
    translation: 'Who studies at the university?',
    options: ['el estudiante', 'el profesor', 'el director'],
    correctAnswer: 'el estudiante',
    hint: 'Student - person who studies at school or university',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_112',
    emoji: 'vote.png',
    question: '¿Qué haces cuando participas en las elecciones?',
    translation: 'What do you do when you participate in elections?',
    options: ['voto', 'trabajo', 'estudio'],
    correctAnswer: 'voto',
    hint: 'Vote - participate in elections by casting your vote for candidates',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  // Emotions and Emotional Relationships (38 questions)
  {
    id: 'people_113',
    emoji: 'love.png',
    question: '¿Cómo se dice "love" en español?',
    translation: 'How do you say \'love\' in Spanish?',
    options: ['el amor', 'el odio', 'la tristeza'],
    correctAnswer: 'el amor',
    hint: 'Love - strong affection, "amar" is the verb to love',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'people_114',
    emoji: 'heartbreak.png',
    question: '¿Qué emoción sientes cuando alguien rompe tu corazón?',
    translation: 'What emotion do you feel when someone breaks your heart?',
    options: ['el desamor', 'la alegría', 'la envidia'],
    correctAnswer: 'el desamor',
    hint: 'Heartbreak - feeling of deep sadness when love ends',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'sad',
  },
  {
    id: 'people_115',
    emoji: 'joy.png',
    question: '¿Cómo te sientes cuando estás contento?',
    translation: 'How do you feel when you are content?',
    options: ['la alegría', 'la tristeza', 'el miedo'],
    correctAnswer: 'la alegría',
    hint: 'Joy - feeling of great happiness and pleasure',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'people_116',
    emoji: 'sadness.png',
    question: '¿Qué emoción causa llanto?',
    translation: 'What emotion causes crying?',
    options: ['la tristeza', 'la alegría', 'la sorpresa'],
    correctAnswer: 'la tristeza',
    hint: 'Sadness - feeling of sorrow or unhappiness',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'sad',
  },
  {
    id: 'people_117',
    emoji: 'fear.png',
    question: '¿Qué sientes cuando estás asustado?',
    translation: 'What do you feel when you are scared?',
    options: ['el miedo', 'la felicidad', 'el amor'],
    correctAnswer: 'el miedo',
    hint: 'Fear - unpleasant emotion caused by threat or danger',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'afraid',
  },
  {
    id: 'people_118',
    emoji: 'anger.png',
    question: '¿Cómo se dice "anger" en español?',
    translation: 'How do you say \'anger\' in Spanish?',
    options: ['la ira', 'la paz', 'la calma'],
    correctAnswer: 'la ira',
    hint: 'Anger - strong feeling of displeasure or hostility',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'angry',
  },
  {
    id: 'people_119',
    emoji: 'annoyance.png',
    question: '¿Qué sientes cuando alguien te hace enojar?',
    translation: 'What do you feel when someone makes you angry?',
    options: ['el enojo', 'la felicidad', 'el amor'],
    correctAnswer: 'el enojo',
    hint: 'Annoyance/anger - feeling of irritation or displeasure',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'angry',
  },
  {
    id: 'people_120',
    emoji: 'disgust.png',
    question: '¿Qué emoción sientes hacia algo repugnante?',
    translation: 'What emotion do you feel toward something disgusting?',
    options: ['el asco', 'la admiración', 'la alegría'],
    correctAnswer: 'el asco',
    hint: 'Disgust - strong feeling of revulsion or aversion',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'disgusted',
  },
  {
    id: 'people_122',
    emoji: 'affection.png',
    question: '¿Qué sientes hacia una persona querida?',
    translation: 'What do you feel toward a loved one?',
    options: ['el cariño', 'el odio', 'la indiferencia'],
    correctAnswer: 'el cariño',
    hint: 'Affection - tender feeling of fondness or love',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_123',
    emoji: 'indifference.png',
    question: '¿Qué sientes cuando algo no te importa?',
    translation: 'What do you feel when something doesn\'t matter to you?',
    options: ['la indiferencia', 'la pasión', 'el entusiasmo'],
    correctAnswer: 'la indiferencia',
    hint: 'Indifference - lack of interest, concern, or sympathy',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_124',
    emoji: 'friendship.png',
    question: '¿Cómo se llama la relación de apoyo mutuo?',
    translation: 'What is a relationship of mutual support called?',
    options: ['la amistad', 'la enemistad', 'la rivalidad'],
    correctAnswer: 'la amistad',
    hint: 'Friendship - relationship of mutual affection between people',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'people_125',
    emoji: 'hatred.png',
    question: '¿Cómo se dice "hatred" en español?',
    translation: 'How do you say \'hatred\' in Spanish?',
    options: ['el odio', 'el amor', 'la simpatía'],
    correctAnswer: 'el odio',
    hint: 'Hatred - intense dislike or ill will toward someone',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'angry',
  },
  {
    id: 'people_126',
    emoji: 'enmity.png',
    question: '¿Qué tipo de relación tiene hostilidad?',
    translation: 'What type of relationship has hostility?',
    options: ['la enemistad', 'la amistad', 'el amor'],
    correctAnswer: 'la enemistad',
    hint: 'Enmity - state or feeling of being actively opposed or hostile',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'angry',
  },
  {
    id: 'people_127',
    emoji: 'envy.png',
    question: '¿Qué sientes cuando quieres lo que otro tiene?',
    translation: 'What do you feel when you want what another has?',
    options: ['la envidia', 'la generosidad', 'la alegría'],
    correctAnswer: 'la envidia',
    hint: 'Envy - feeling of discontent at another\'s advantages or possessions',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'sad',
  },
  {
    id: 'people_128',
    emoji: 'jealousy.png',
    question: '¿Cómo se dice "jealousy" en español?',
    translation: 'How do you say \'jealousy\' in Spanish?',
    options: ['los celos', 'la confianza', 'la lealtad'],
    correctAnswer: 'los celos',
    hint: 'Jealousy - fear of losing someone\'s affection to a rival',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'people_129',
    emoji: 'infactuation.png',
    question: '¿Qué sientes cuando te enamoras?',
    translation: 'What do you feel when you fall in love?',
    options: ['el enamoramiento', 'el aburrimiento', 'la apatía'],
    correctAnswer: 'el enamoramiento',
    hint: 'Infatuation/falling in love - intense but short-lived passion',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'people_130',
    emoji: 'romance.png',
    question: '¿Cómo se llama el amor romántico?',
    translation: 'What is romantic love called?',
    options: ['el romance', 'la amistad', 'la enemistad'],
    correctAnswer: 'el romance',
    hint: 'Romance - feeling of excitement associated with love',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'people_131',
    emoji: 'passion.png',
    question: '¿Qué emoción sientes hacia alguien especial?',
    translation: 'What emotion do you feel toward someone special?',
    options: ['la pasión', 'la indiferencia', 'el desprecio'],
    correctAnswer: 'la pasión',
    hint: 'Passion - strong and barely controllable emotion',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'people_132',
    emoji: 'disappointment.png',
    question: '¿Cómo se dice "disappointment" en español?',
    translation: 'How do you say \'disappointment\' in Spanish?',
    options: ['la decepción', 'la satisfacción', 'la alegría'],
    correctAnswer: 'la decepción',
    hint: 'Disappointment - sadness from unfulfilled hopes or expectations',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'sad',
  },
  {
    id: 'people_133',
    emoji: 'despair.png',
    question: '¿Qué sientes cuando pierdes la esperanza?',
    translation: 'What do you feel when you lose hope?',
    options: ['la desesperación', 'el optimismo', 'la alegría'],
    correctAnswer: 'la desesperación',
    hint: 'Despair - complete loss or absence of hope',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'sad',
  },
  {
    id: 'people_134',
    emoji: 'compassion.png',
    question: '¿Cómo se dice "compassion" en español?',
    translation: 'How do you say \'compassion\' in Spanish?',
    options: ['la compasión', 'la crueldad', 'la indiferencia'],
    correctAnswer: 'la compasión',
    hint: 'Compassion - sympathetic concern for the sufferings of others',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_135',
    emoji: 'pity.png',
    question: '¿Qué sientes por alguien que sufre?',
    translation: 'What do you feel for someone who suffers?',
    options: ['la lástima', 'la alegría', 'la envidia'],
    correctAnswer: 'la lástima',
    hint: 'Pity - feeling of sorrow and compassion for another\'s misfortune',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'sad',
  },
  {
    id: 'people_136',
    emoji: 'resentment.png',
    question: '¿Cómo se dice "resentment" en español?',
    translation: 'How do you say \'resentment\' in Spanish?',
    options: ['el rencor', 'el perdón', 'la gratitud'],
    correctAnswer: 'el rencor',
    hint: 'Resentment - bitter indignation at having been treated unfairly',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'angry',
  },
  {
    id: 'people_137',
    emoji: 'shame.png',
    question: '¿Qué sientes cuando algo te avergüenza?',
    translation: 'What do you feel when something embarrasses you?',
    options: ['la vergüenza', 'el orgullo', 'la satisfacción'],
    correctAnswer: 'la vergüenza',
    hint: 'Shame - painful feeling from consciousness of guilt or dishonor',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'people_138',
    emoji: 'gratitude.png',
    question: '¿Cómo se dice "gratitude" en español?',
    translation: 'How do you say \'gratitude\' in Spanish?',
    options: ['la gratitud', 'la ingratitud', 'el rencor'],
    correctAnswer: 'la gratitud',
    hint: 'Gratitude - quality of being thankful and appreciative',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_139',
    emoji: 'animosity.png',
    question: '¿Qué relación tiene sentimientos negativos?',
    translation: 'What relationship has negative feelings?',
    options: ['la animosidad', 'el cariño', 'la amistad'],
    correctAnswer: 'la animosidad',
    hint: 'Animosity - strong hostility or ill feeling toward someone',
    points: 15,
    category: 'people',
    difficulty: 'hard',
    emotion: 'angry',
  },
  {
    id: 'people_140',
    emoji: 'appreciation.png',
    question: '¿Qué sientes cuando estás agradecido?',
    translation: 'What do you feel when you are grateful?',
    options: ['el agradecimiento', 'el resentimiento', 'la ira'],
    correctAnswer: 'el agradecimiento',
    hint: 'Appreciation - recognition and enjoyment of good qualities',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_141',
    emoji: 'admiration.png',
    question: '¿Cómo se dice "admiration" en español?',
    translation: 'How do you say \'admiration\' in Spanish?',
    options: ['la admiración', 'el desprecio', 'la envidia'],
    correctAnswer: 'la admiración',
    hint: 'Admiration - respect and warm approval for someone or something',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_142',
    emoji: 'contempt.png',
    question: '¿Qué sientes hacia algo que desprecias?',
    translation: 'What do you feel toward something you despise?',
    options: ['el desprecio', 'la admiración', 'el respeto'],
    correctAnswer: 'el desprecio',
    hint: 'Contempt - feeling that someone or something is worthless',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'angry',
  },
  {
    id: 'people_143',
    emoji: 'regret.png',
    question: '¿Cómo se dice "remorse" en español?',
    translation: 'How do you say \'remorse\' in Spanish?',
    options: ['el remordimiento', 'la alegría', 'la satisfacción'],
    correctAnswer: 'el remordimiento',
    hint: 'Remorse - deep regret or guilt for a wrong committed',
    points: 15,
    category: 'people',
    difficulty: 'hard',
    emotion: 'sad',
  },
  {
    id: 'people_144',
    emoji: 'forgiving.png',
    question: '¿Qué sientes cuando perdonas?',
    translation: 'What do you feel when you forgive?',
    options: ['el perdón', 'la venganza', 'el odio'],
    correctAnswer: 'el perdón',
    hint: 'Forgiveness - act of ceasing to feel resentment against someone',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_145',
    emoji: 'confidence.png',
    question: '¿Cómo se dice "confidence" en español?',
    translation: 'How do you say \'confidence\' in Spanish?',
    options: ['la confianza', 'la duda', 'el miedo'],
    correctAnswer: 'la confianza',
    hint: 'Confidence - feeling of self-assurance arising from trust',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_146',
    emoji: 'anxious.png',
    question: '¿Qué sientes cuando tienes preocupación?',
    translation: 'What do you feel when you have worry?',
    options: ['la ansiedad', 'la tranquilidad', 'la alegría'],
    correctAnswer: 'la ansiedad',
    hint: 'Anxiety - feeling of worry, nervousness, or unease',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'people_147',
    emoji: 'laughing.png',
    question: '¿Qué emoción causa la risa?',
    translation: 'What emotion causes laughter?',
    options: ['la diversión', 'la tristeza', 'el miedo'],
    correctAnswer: 'la diversión',
    hint: 'Amusement - feeling of being entertained or finding something funny',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'people_148',
    emoji: 'pleased.png',
    question: '¿Cómo se dice "surprise" en español?',
    translation: 'How do you say \'surprise\' in Spanish?',
    options: ['la sorpresa', 'la expectativa', 'la rutina'],
    correctAnswer: 'la sorpresa',
    hint: 'Surprise - feeling caused by something unexpected',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'people_149',
    emoji: 'irritated.png',
    question: '¿Qué sientes cuando algo te fastidia?',
    translation: 'What do you feel when something annoys you?',
    options: ['la irritación', 'la felicidad', 'el amor'],
    correctAnswer: 'la irritación',
    hint: 'Irritation - feeling of annoyance or slight anger',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'angry',
  },
  {
    id: 'people_150',
    emoji: 'boredom.png',
    question: '¿Cómo se dice "boredom" en español?',
    translation: 'How do you say \'boredom\' in Spanish?',
    options: ['el aburrimiento', 'la emoción', 'el entusiasmo'],
    correctAnswer: 'el aburrimiento',
    hint: 'Boredom - state of feeling weary from lack of interest',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_151',
    emoji: 'phone-scammer.png',
    question: '¿Quién te llama para engañarte y robarte dinero?',
    translation: 'Who calls you to deceive you and steal your money?',
    options: ['el estafador telefónico', 'el operador', 'el vendedor'],
    correctAnswer: 'el estafador telefónico',
    hint: 'Phone scammer - "estafador" means scammer, fraudulent caller who tries to steal money',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'afraid',
  },

  // Extended Family Relationships (60 questions)
  {
    id: 'people_152',
    emoji: '👨',
    question: '¿Cómo se dice "dad" en español (informal)?',
    translation: 'How do you say \'dad\' in Spanish (informal)?',
    options: ['papá', 'padre', 'tío'],
    correctAnswer: 'papá',
    hint: 'Dad - informal, must have accent on second "a"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_153',
    emoji: '👩',
    question: '¿Cómo se dice "mom" en español (informal)?',
    translation: 'How do you say \'mom\' in Spanish (informal)?',
    options: ['mamá', 'madre', 'tía'],
    correctAnswer: 'mamá',
    hint: 'Mom - informal, must have accent on second "a"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'people_154',
    emoji: '👨‍👩‍👦',
    question: '¿Cómo se dice "parents" en español?',
    translation: 'How do you say \'parents\' in Spanish?',
    options: ['los padres', 'los parientes', 'los hermanos'],
    correctAnswer: 'los padres',
    hint: 'Parents - both mother and father together, plural of "padre"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_155',
    emoji: '👦👧',
    question: '¿Cómo se dice "siblings" en español?',
    translation: 'How do you say \'siblings\' in Spanish?',
    options: ['los hermanos', 'los primos', 'los padres'],
    correctAnswer: 'los hermanos',
    hint: 'Siblings - brothers and sisters, can be mixed gender',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_156',
    emoji: '💑',
    question: '¿Cómo se dice "husband" (alternativa)?',
    translation: 'How do you say \'husband\' (alternative)?',
    options: ['el marido', 'el esposo', 'el novio'],
    correctAnswer: 'el marido',
    hint: 'Husband - alternative to "esposo", commonly used',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'people_157',
    emoji: '👰',
    question: '¿Cómo se puede decir "wife" (alternativa)?',
    translation: 'How can you say \'wife\' (alternative)?',
    options: ['la mujer', 'la esposa', 'la novia'],
    correctAnswer: 'la mujer',
    hint: 'Wife - "mujer" can mean both "woman" and "wife" depending on context',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'people_158',
    emoji: '👴👵',
    question: '¿Cómo se dice "grandparents" en español?',
    translation: 'How do you say \'grandparents\' in Spanish?',
    options: ['los abuelos', 'los padres', 'los ancianos'],
    correctAnswer: 'los abuelos',
    hint: 'Grandparents - both grandmother and grandfather together',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'people_159',
    emoji: '👴',
    question: '¿Cómo se dice "great-grandfather"?',
    translation: 'How do you say \'great-grandfather\'?',
    options: ['el bisabuelo', 'el abuelo', 'el tatarabuelo'],
    correctAnswer: 'el bisabuelo',
    hint: 'Great-grandfather - grandfather\'s father, "bis" prefix means twice',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'people_160',
    emoji: '👵',
    question: '¿Cómo se dice "great-grandmother"?',
    translation: 'How do you say \'great-grandmother\'?',
    options: ['la bisabuela', 'la abuela', 'la tatarabuela'],
    correctAnswer: 'la bisabuela',
    hint: 'Great-grandmother - grandmother\'s mother, "bis" prefix',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'people_161',
    emoji: '👴',
    question: '¿Cómo se dice "great-great-grandfather"?',
    translation: 'How do you say \'great-great-grandfather\'?',
    options: ['el tatarabuelo', 'el bisabuelo', 'el abuelo'],
    correctAnswer: 'el tatarabuelo',
    hint: 'Great-great-grandfather - great-grandfather\'s father',
    points: 15,
    category: 'people',
    difficulty: 'hard',
    emotion: 'calm',
  },
  {
    id: 'people_162',
    emoji: '👵',
    question: '¿Cómo se dice "great-great-grandmother"?',
    translation: 'How do you say \'great-great-grandmother\'?',
    options: ['la tatarabuela', 'la bisabuela', 'la abuela'],
    correctAnswer: 'la tatarabuela',
    hint: 'Great-great-grandmother - great-grandmother\'s mother',
    points: 15,
    category: 'people',
    difficulty: 'hard',
    emotion: 'calm',
  },
  {
    id: 'people_163',
    emoji: '👦',
    question: '¿Cómo se dice "grandson" en español?',
    translation: 'How do you say \'grandson\' in Spanish?',
    options: ['el nieto', 'el hijo', 'el sobrino'],
    correctAnswer: 'el nieto',
    hint: 'Grandson - son of your child, "nieta" is granddaughter',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_164',
    emoji: '👧',
    question: '¿Cómo se dice "granddaughter" en español?',
    translation: 'How do you say \'granddaughter\' in Spanish?',
    options: ['la nieta', 'la hija', 'la sobrina'],
    correctAnswer: 'la nieta',
    hint: 'Granddaughter - daughter of your child, "nieto" is grandson',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_165',
    emoji: '👦👧',
    question: '¿Cómo se dice "grandchildren" en español?',
    translation: 'How do you say \'grandchildren\' in Spanish?',
    options: ['los nietos', 'los hijos', 'los sobrinos'],
    correctAnswer: 'los nietos',
    hint: 'Grandchildren - children of your children, plural',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_166',
    emoji: '👦',
    question: '¿Cómo se dice "great-grandson"?',
    translation: 'How do you say \'great-grandson\'?',
    options: ['el bisnieto', 'el nieto', 'el tataranieto'],
    correctAnswer: 'el bisnieto',
    hint: 'Great-grandson - grandson of your child, "bis" prefix',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_167',
    emoji: '👧',
    question: '¿Cómo se dice "great-granddaughter"?',
    translation: 'How do you say \'great-granddaughter\'?',
    options: ['la bisnieta', 'la nieta', 'la tataranieta'],
    correctAnswer: 'la bisnieta',
    hint: 'Great-granddaughter - granddaughter of your child, "bis" prefix',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_168',
    emoji: '👦',
    question: '¿Cómo se dice "great-great-grandson"?',
    translation: 'How do you say \'great-great-grandson\'?',
    options: ['el tataranieto', 'el bisnieto', 'el nieto'],
    correctAnswer: 'el tataranieto',
    hint: 'Great-great-grandson - great-grandson of your child',
    points: 15,
    category: 'people',
    difficulty: 'hard',
    emotion: 'pleased',
  },
  {
    id: 'people_169',
    emoji: '👧',
    question: '¿Cómo se dice "great-great-granddaughter"?',
    translation: 'How do you say \'great-great-granddaughter\'?',
    options: ['la tataranieta', 'la bisnieta', 'la nieta'],
    correctAnswer: 'la tataranieta',
    hint: 'Great-great-granddaughter - great-granddaughter of your child',
    points: 15,
    category: 'people',
    difficulty: 'hard',
    emotion: 'pleased',
  },
  {
    id: 'people_170',
    emoji: '👨‍👩‍👧',
    question: '¿Cómo se dice "uncles" o "aunts and uncles"?',
    translation: 'How do you say \'uncles\' or \'aunts and uncles\'?',
    options: ['los tíos', 'los padres', 'los abuelos'],
    correctAnswer: 'los tíos',
    hint: 'Uncles - plural, can mean just uncles or uncles and aunts together',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_171',
    emoji: '👦👧',
    question: '¿Cómo se dice "cousins" en español?',
    translation: 'How do you say \'cousins\' in Spanish?',
    options: ['los primos', 'los hermanos', 'los sobrinos'],
    correctAnswer: 'los primos',
    hint: 'Cousins - children of your aunts and uncles, plural',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'people_172',
    emoji: '👨‍👩‍👦',
    question: '¿Cómo se dice "nephews" o "nieces and nephews"?',
    translation: 'How do you say \'nephews\' or \'nieces and nephews\'?',
    options: ['los sobrinos', 'los primos', 'los hijos'],
    correctAnswer: 'los sobrinos',
    hint: 'Nephews - children of your siblings, can be mixed gender',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_173',
    emoji: '👨‍👦',
    question: '¿Cómo se dice "godfather" en español?',
    translation: 'How do you say \'godfather\' in Spanish?',
    options: ['el padrino', 'el padre', 'el tío'],
    correctAnswer: 'el padrino',
    hint: 'Godfather - spiritual father in baptism, "madrina" is godmother',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_174',
    emoji: '👩‍👧',
    question: '¿Cómo se dice "godmother" en español?',
    translation: 'How do you say \'godmother\' in Spanish?',
    options: ['la madrina', 'la madre', 'la tía'],
    correctAnswer: 'la madrina',
    hint: 'Godmother - spiritual mother in baptism, "padrino" is godfather',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_175',
    emoji: '👦',
    question: '¿Cómo se dice "godson" en español?',
    translation: 'How do you say \'godson\' in Spanish?',
    options: ['el ahijado', 'el hijo', 'el nieto'],
    correctAnswer: 'el ahijado',
    hint: 'Godson - male child with godparents, "ahijada" is goddaughter',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_176',
    emoji: '👧',
    question: '¿Cómo se dice "goddaughter" en español?',
    translation: 'How do you say \'goddaughter\' in Spanish?',
    options: ['la ahijada', 'la hija', 'la nieta'],
    correctAnswer: 'la ahijada',
    hint: 'Goddaughter - female child with godparents, "ahijado" is godson',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_177',
    emoji: '👴',
    question: '¿Cómo se dice "father-in-law" en español?',
    translation: 'How do you say \'father-in-law\' in Spanish?',
    options: ['el suegro', 'el padre', 'el tío'],
    correctAnswer: 'el suegro',
    hint: 'Father-in-law - father of your spouse, "suegra" is mother-in-law',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_178',
    emoji: '👵',
    question: '¿Cómo se dice "mother-in-law" en español?',
    translation: 'How do you say \'mother-in-law\' in Spanish?',
    options: ['la suegra', 'la madre', 'la tía'],
    correctAnswer: 'la suegra',
    hint: 'Mother-in-law - mother of your spouse, "suegro" is father-in-law',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_179',
    emoji: '👴👵',
    question: '¿Cómo se dice "in-laws" en español?',
    translation: 'How do you say \'in-laws\' in Spanish?',
    options: ['los suegros', 'los padres', 'los tíos'],
    correctAnswer: 'los suegros',
    hint: 'In-laws - parents of your spouse, plural',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_180',
    emoji: '👨',
    question: '¿Cómo se dice "son-in-law" en español?',
    translation: 'How do you say \'son-in-law\' in Spanish?',
    options: ['el yerno', 'el hijo', 'el sobrino'],
    correctAnswer: 'el yerno',
    hint: 'Son-in-law - husband of your daughter, "nuera" is daughter-in-law',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_181',
    emoji: '👩',
    question: '¿Cómo se dice "daughter-in-law" en español?',
    translation: 'How do you say \'daughter-in-law\' in Spanish?',
    options: ['la nuera', 'la hija', 'la sobrina'],
    correctAnswer: 'la nuera',
    hint: 'Daughter-in-law - wife of your son, "yerno" is son-in-law',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_182',
    emoji: '👨',
    question: '¿Cómo se dice "brother-in-law" en español?',
    translation: 'How do you say \'brother-in-law\' in Spanish?',
    options: ['el cuñado', 'el hermano', 'el primo'],
    correctAnswer: 'el cuñado',
    hint: 'Brother-in-law - brother of your spouse or husband of your sibling',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_183',
    emoji: '👩',
    question: '¿Cómo se dice "sister-in-law" en español?',
    translation: 'How do you say \'sister-in-law\' in Spanish?',
    options: ['la cuñada', 'la hermana', 'la prima'],
    correctAnswer: 'la cuñada',
    hint: 'Sister-in-law - sister of your spouse or wife of your sibling',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_184',
    emoji: '👨',
    question: '¿Cómo se dice el esposo de tu cuñada?',
    translation: 'How do you say your sister-in-law\'s husband?',
    options: ['el concuñado', 'el cuñado', 'el hermano'],
    correctAnswer: 'el concuñado',
    hint: 'Co-brother-in-law - spouse of your sibling-in-law, rare term',
    points: 15,
    category: 'people',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'people_185',
    emoji: '👩',
    question: '¿Cómo se dice la esposa de tu cuñado?',
    translation: 'How do you say your brother-in-law\'s wife?',
    options: ['la concuñada', 'la cuñada', 'la hermana'],
    correctAnswer: 'la concuñada',
    hint: 'Co-sister-in-law - spouse of your sibling-in-law, rare term',
    points: 15,
    category: 'people',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'people_186',
    emoji: '👴',
    question: '¿Cómo se dice el padre del esposo de tu hijo/a?',
    translation: 'How do you say the father of your child\'s spouse?',
    options: ['el consuegro', 'el suegro', 'el yerno'],
    correctAnswer: 'el consuegro',
    hint: 'Co-father-in-law - parent of your child\'s spouse',
    points: 15,
    category: 'people',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'people_187',
    emoji: '👵',
    question: '¿Cómo se dice la madre del esposo de tu hijo/a?',
    translation: 'How do you say the mother of your child\'s spouse?',
    options: ['la consuegra', 'la suegra', 'la nuera'],
    correctAnswer: 'la consuegra',
    hint: 'Co-mother-in-law - parent of your child\'s spouse',
    points: 15,
    category: 'people',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'people_188',
    emoji: '👨‍👩‍👧‍👦',
    question: '¿Cómo se dice "in-laws" como grupo?',
    translation: 'How do you say \'in-laws\' as a group?',
    options: ['la familia política', 'la familia', 'los parientes'],
    correctAnswer: 'la familia política',
    hint: 'In-laws - family related by marriage, "política" means political or by marriage',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_189',
    emoji: '👨',
    question: '¿Cómo se dice "uncle by marriage"?',
    translation: 'How do you say \'uncle by marriage\'?',
    options: ['el tío político', 'el tío', 'el suegro'],
    correctAnswer: 'el tío político',
    hint: 'Uncle by marriage - married to your aunt, not blood related',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_190',
    emoji: '👩',
    question: '¿Cómo se dice "aunt by marriage"?',
    translation: 'How do you say \'aunt by marriage\'?',
    options: ['la tía política', 'la tía', 'la suegra'],
    correctAnswer: 'la tía política',
    hint: 'Aunt by marriage - married to your uncle, not blood related',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_191',
    emoji: '👨',
    question: '¿Cómo se dice "stepfather" en español?',
    translation: 'How do you say \'stepfather\' in Spanish?',
    options: ['el padrastro', 'el padre', 'el tío'],
    correctAnswer: 'el padrastro',
    hint: 'Stepfather - mother\'s new husband, not biological father',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_192',
    emoji: '👩',
    question: '¿Cómo se dice "stepmother" en español?',
    translation: 'How do you say \'stepmother\' in Spanish?',
    options: ['la madrastra', 'la madre', 'la tía'],
    correctAnswer: 'la madrastra',
    hint: 'Stepmother - father\'s new wife, not biological mother',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_193',
    emoji: '👦',
    question: '¿Cómo se dice "stepson" en español?',
    translation: 'How do you say \'stepson\' in Spanish?',
    options: ['el hijastro', 'el hijo', 'el sobrino'],
    correctAnswer: 'el hijastro',
    hint: 'Stepson - spouse\'s son from previous relationship',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_194',
    emoji: '👧',
    question: '¿Cómo se dice "stepdaughter" en español?',
    translation: 'How do you say \'stepdaughter\' in Spanish?',
    options: ['la hijastra', 'la hija', 'la sobrina'],
    correctAnswer: 'la hijastra',
    hint: 'Stepdaughter - spouse\'s daughter from previous relationship',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_195',
    emoji: '👦',
    question: '¿Cómo se dice "stepbrother" en español?',
    translation: 'How do you say \'stepbrother\' in Spanish?',
    options: ['el hermanastro', 'el hermano', 'el primo'],
    correctAnswer: 'el hermanastro',
    hint: 'Stepbrother - parent\'s new spouse\'s son, not blood related',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_196',
    emoji: '👧',
    question: '¿Cómo se dice "stepsister" en español?',
    translation: 'How do you say \'stepsister\' in Spanish?',
    options: ['la hermanastra', 'la hermana', 'la prima'],
    correctAnswer: 'la hermanastra',
    hint: 'Stepsister - parent\'s new spouse\'s daughter, not blood related',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_197',
    emoji: '👦',
    question: '¿Cómo se dice "half-brother" en español?',
    translation: 'How do you say \'half-brother\' in Spanish?',
    options: ['el medio hermano', 'el hermano', 'el hermanastro'],
    correctAnswer: 'el medio hermano',
    hint: 'Half-brother - shares one parent with you, blood related',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_198',
    emoji: '👧',
    question: '¿Cómo se dice "half-sister" en español?',
    translation: 'How do you say \'half-sister\' in Spanish?',
    options: ['la media hermana', 'la hermana', 'la hermanastra'],
    correctAnswer: 'la media hermana',
    hint: 'Half-sister - shares one parent with you, blood related',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_199',
    emoji: '👨‍👩‍👧‍👦',
    question: '¿Cómo se dice "adopted family"?',
    translation: 'How do you say \'adopted family\'?',
    options: ['la familia adoptiva', 'la familia', 'la familia política'],
    correctAnswer: 'la familia adoptiva',
    hint: 'Adopted family - family that legally adopted you',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_200',
    emoji: '💑',
    question: '¿Cómo se dice "partner" o "couple"?',
    translation: 'How do you say \'partner\' or \'couple\'?',
    options: ['la pareja', 'el novio', 'el esposo'],
    correctAnswer: 'la pareja',
    hint: 'Partner - always feminine, inclusive for any couple',
    points: 5,
    category: 'people',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'people_201',
    emoji: '💍',
    question: '¿Cómo se dice "fiancé" (masculino)?',
    translation: 'How do you say \'fiancé\' (masculine)?',
    options: ['el prometido', 'el novio', 'el esposo'],
    correctAnswer: 'el prometido',
    hint: 'Fiancé - man engaged to be married, from "prometer"',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'people_202',
    emoji: '💍',
    question: '¿Cómo se dice "fiancée" (femenino)?',
    translation: 'How do you say \'fiancée\' (feminine)?',
    options: ['la prometida', 'la novia', 'la esposa'],
    correctAnswer: 'la prometida',
    hint: 'Fiancée - woman engaged to be married, from "prometer"',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'people_203',
    emoji: '👨',
    question: '¿Cómo se dice "male partner" o "companion"?',
    translation: 'How do you say \'male partner\' or \'companion\'?',
    options: ['el compañero', 'el amigo', 'el novio'],
    correctAnswer: 'el compañero',
    hint: 'Partner - can mean partner, companion, or colleague',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_204',
    emoji: '👩',
    question: '¿Cómo se dice "female partner" o "companion"?',
    translation: 'How do you say \'female partner\' or \'companion\'?',
    options: ['la compañera', 'la amiga', 'la novia'],
    correctAnswer: 'la compañera',
    hint: 'Partner - can mean partner, companion, or colleague',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'people_205',
    emoji: '👨‍👩‍👧‍👦',
    question: '¿Cómo se dice "relatives" en español?',
    translation: 'How do you say \'relatives\' in Spanish?',
    options: ['los parientes', 'los padres', 'los amigos'],
    correctAnswer: 'los parientes',
    hint: 'Relatives - extended family members, from "pariente"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_206',
    emoji: '👨‍👩‍👧‍👦',
    question: '¿Cómo se dice "family members"?',
    translation: 'How do you say \'family members\'?',
    options: ['los familiares', 'la familia', 'los parientes'],
    correctAnswer: 'los familiares',
    hint: 'Family members - people in your family, synonymous with relatives',
    points: 5,
    category: 'people',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'people_207',
    emoji: '👩‍👧',
    question: '¿Cómo se dice "single mother"?',
    translation: 'How do you say \'single mother\'?',
    options: ['la madre soltera', 'la madre', 'la mujer'],
    correctAnswer: 'la madre soltera',
    hint: 'Single mother - mother raising child alone, "soltera" means single',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_208',
    emoji: '👨‍👦',
    question: '¿Cómo se dice "single father"?',
    translation: 'How do you say \'single father\'?',
    options: ['el padre soltero', 'el padre', 'el hombre'],
    correctAnswer: 'el padre soltero',
    hint: 'Single father - father raising child alone, "soltero" means single',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'people_209',
    emoji: '👦',
    question: '¿Cómo se dice "only child" (masculino)?',
    translation: 'How do you say \'only child\' (masculine)?',
    options: ['el hijo único', 'el hijo', 'el niño'],
    correctAnswer: 'el hijo único',
    hint: 'Only child - child with no siblings, "único" means only/unique',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_210',
    emoji: '👧',
    question: '¿Cómo se dice "only child" (femenino)?',
    translation: 'How do you say \'only child\' (feminine)?',
    options: ['la hija única', 'la hija', 'la niña'],
    correctAnswer: 'la hija única',
    hint: 'Only child - child with no siblings, "única" means only/unique',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'people_211',
    emoji: '👴',
    question: '¿Cómo se dice "widower" en español?',
    translation: 'How do you say \'widower\' in Spanish?',
    options: ['el viudo', 'el soltero', 'el divorciado'],
    correctAnswer: 'el viudo',
    hint: 'Widower - man whose wife has died, "viuda" is widow',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'sad',
  },
  {
    id: 'people_212',
    emoji: '👵',
    question: '¿Cómo se dice "widow" en español?',
    translation: 'How do you say \'widow\' in Spanish?',
    options: ['la viuda', 'la soltera', 'la divorciada'],
    correctAnswer: 'la viuda',
    hint: 'Widow - woman whose husband has died, "viudo" is widower',
    points: 10,
    category: 'people',
    difficulty: 'medium',
    emotion: 'sad',
  },
  {
    id: 'people_213',
    emoji: '👥',
    question: '¿Cómo se dice "chosen family"?',
    translation: 'How do you say \'chosen family\'?',
    options: ['la familia elegida', 'la familia', 'los amigos'],
    correctAnswer: 'la familia elegida',
    hint: 'Chosen family - close friends considered as family, "elegida" means chosen',
    points: 15,
    category: 'people',
    difficulty: 'hard',
    emotion: 'happy',
  },
];
