/**
 * People & Relationships Category Questions
 * Category: people
 */

export const peopleQuestions = [
  // Family Members (20 questions)
  {
    id: 'people_001',
    emoji: '👨',
    question: '¿Cómo se dice "father" en español?',
    options: ['el padre', 'el tío', 'el abuelo'],
    correctAnswer: 'el padre',
    hint: 'Father - "papá" is informal, masculine',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_002',
    emoji: '👩',
    question: '¿Cómo se dice "mother" en español?',
    options: ['la madre', 'la tía', 'la abuela'],
    correctAnswer: 'la madre',
    hint: 'Mother - "mamá" is informal, feminine',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_003',
    emoji: '👦',
    question: '¿Cómo se llama un hijo varón?',
    options: ['el hijo', 'el hermano', 'el primo'],
    correctAnswer: 'el hijo',
    hint: 'Son - male child, "hija" is daughter',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_004',
    emoji: '👧',
    question: '¿Cómo se llama una hija?',
    options: ['la hija', 'la hermana', 'la prima'],
    correctAnswer: 'la hija',
    hint: 'Daughter - female child, "hijo" is son',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_005',
    emoji: '👴',
    question: '¿Cómo se dice "grandfather" en español?',
    options: ['el abuelo', 'el padre', 'el tío'],
    correctAnswer: 'el abuelo',
    hint: 'Grandfather - "abuelito" is affectionate diminutive',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_006',
    emoji: '👵',
    question: '¿Cómo se dice "grandmother" en español?',
    options: ['la abuela', 'la madre', 'la tía'],
    correctAnswer: 'la abuela',
    hint: 'Grandmother - "abuelita" is affectionate diminutive',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_007',
    emoji: '👨‍👦',
    question: '¿Cómo se dice "brother" en español?',
    options: ['el hermano', 'el primo', 'el hijo'],
    correctAnswer: 'el hermano',
    hint: 'Brother - "hermana" is sister, same family',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_008',
    emoji: '👩‍👧',
    question: '¿Cómo se dice "sister" en español?',
    options: ['la hermana', 'la prima', 'la hija'],
    correctAnswer: 'la hermana',
    hint: 'Sister - "hermano" is brother, same family',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_009',
    emoji: '👨‍👦‍👦',
    question: '¿Cómo se dice "uncle" en español?',
    options: ['el tío', 'el padre', 'el abuelo'],
    correctAnswer: 'el tío',
    hint: 'Uncle - parent\'s brother, "tía" is aunt',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_010',
    emoji: '👩‍👧‍👧',
    question: '¿Cómo se dice "aunt" en español?',
    options: ['la tía', 'la madre', 'la abuela'],
    correctAnswer: 'la tía',
    hint: 'Aunt - parent\'s sister, "tío" is uncle',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_011',
    emoji: '👦👧',
    question: '¿Cómo se dice "cousin" (masculino)?',
    options: ['el primo', 'el hermano', 'el sobrino'],
    correctAnswer: 'el primo',
    hint: 'Male cousin - child of uncle/aunt, "prima" is female',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_012',
    emoji: '👫',
    question: '¿Cómo se dice "cousin" (femenino)?',
    options: ['la prima', 'la hermana', 'la sobrina'],
    correctAnswer: 'la prima',
    hint: 'Female cousin - child of uncle/aunt, "primo" is male',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_013',
    emoji: '👶',
    question: '¿Cómo se dice "baby" en español?',
    options: ['el bebé', 'el niño', 'el hijo'],
    correctAnswer: 'el bebé',
    hint: 'Baby - very young child, "bebé" works for both genders',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_014',
    emoji: '👨‍👩‍👧',
    question: '¿Cómo se dice "nephew" en español?',
    options: ['el sobrino', 'el primo', 'el hijo'],
    correctAnswer: 'el sobrino',
    hint: 'Nephew - brother/sister\'s son, "sobrina" is niece',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_015',
    emoji: '👨‍👩‍👧‍👦',
    question: '¿Cómo se dice "niece" en español?',
    options: ['la sobrina', 'la prima', 'la hija'],
    correctAnswer: 'la sobrina',
    hint: 'Niece - brother/sister\'s daughter, "sobrino" is nephew',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_016',
    emoji: '💑',
    question: '¿Cómo se dice "husband" en español?',
    options: ['el esposo', 'el novio', 'el padre'],
    correctAnswer: 'el esposo',
    hint: 'Husband - married man, "marido" is also correct',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_017',
    emoji: '👰',
    question: '¿Cómo se dice "wife" en español?',
    options: ['la esposa', 'la novia', 'la madre'],
    correctAnswer: 'la esposa',
    hint: 'Wife - married woman, "mujer" is also used',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_018',
    emoji: '💏',
    question: '¿Cómo se dice "boyfriend" en español?',
    options: ['el novio', 'el esposo', 'el amigo'],
    correctAnswer: 'el novio',
    hint: 'Boyfriend - romantic partner, not married yet',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_019',
    emoji: '💑',
    question: '¿Cómo se dice "girlfriend" en español?',
    options: ['la novia', 'la esposa', 'la amiga'],
    correctAnswer: 'la novia',
    hint: 'Girlfriend - romantic partner, not married yet',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_020',
    emoji: '👨‍👩‍👧‍👦',
    question: '¿Cómo se dice "family" en español?',
    options: ['la familia', 'los padres', 'los hermanos'],
    correctAnswer: 'la familia',
    hint: 'Family - all relatives together, feminine noun',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },

  // Professions (30 questions)
  {
    id: 'people_021',
    emoji: '👨‍⚕️',
    question: '¿Cómo se dice "doctor" (masculino)?',
    options: ['el médico', 'el enfermero', 'el dentista'],
    correctAnswer: 'el médico',
    hint: 'Male doctor - medical professional, "doctor" also works',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_022',
    emoji: '👩‍⚕️',
    question: '¿Cómo se dice "doctor" (femenino)?',
    options: ['la médica', 'la enfermera', 'la dentista'],
    correctAnswer: 'la médica',
    hint: 'Female doctor - medical professional, "doctora" also works',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_023',
    emoji: '👨‍🏫',
    question: '¿Cómo se dice "teacher" (masculino)?',
    options: ['el maestro', 'el estudiante', 'el director'],
    correctAnswer: 'el maestro',
    hint: 'Male teacher - "profesor" for higher education',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_024',
    emoji: '👩‍🏫',
    question: '¿Cómo se dice "teacher" (femenino)?',
    options: ['la maestra', 'la estudiante', 'la directora'],
    correctAnswer: 'la maestra',
    hint: 'Female teacher - "profesora" for higher education',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_025',
    emoji: '👨‍🎓',
    question: '¿Cómo se dice "student" (masculino)?',
    options: ['el estudiante', 'el maestro', 'el alumno'],
    correctAnswer: 'el estudiante',
    hint: 'Male student - "alumno" is also common',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_026',
    emoji: '👩‍🎓',
    question: '¿Cómo se dice "student" (femenino)?',
    options: ['la estudiante', 'la maestra', 'la alumna'],
    correctAnswer: 'la estudiante',
    hint: 'Female student - "alumna" is also common',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_027',
    emoji: '👨‍💼',
    question: '¿Cómo se dice "businessman"?',
    options: ['el hombre de negocios', 'el vendedor', 'el jefe'],
    correctAnswer: 'el hombre de negocios',
    hint: 'Businessman - "empresario" is entrepreneur',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_028',
    emoji: '👩‍💼',
    question: '¿Cómo se dice "businesswoman"?',
    options: ['la mujer de negocios', 'la vendedora', 'la jefa'],
    correctAnswer: 'la mujer de negocios',
    hint: 'Businesswoman - "empresaria" is entrepreneur',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_029',
    emoji: '👨‍🍳',
    question: '¿Cómo se dice "chef" o "cook"?',
    options: ['el cocinero', 'el camarero', 'el panadero'],
    correctAnswer: 'el cocinero',
    hint: 'Male cook - "chef" is also used, from French',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_030',
    emoji: '👩‍🍳',
    question: '¿Cómo se dice "chef" o "cook" (femenino)?',
    options: ['la cocinera', 'la camarera', 'la panadera'],
    correctAnswer: 'la cocinera',
    hint: 'Female cook - "chef" is also used, from French',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_031',
    emoji: '👮‍♂️',
    question: '¿Cómo se dice "police officer" (masculino)?',
    options: ['el policía', 'el bombero', 'el soldado'],
    correctAnswer: 'el policía',
    hint: 'Male police officer - keeps order and safety',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_032',
    emoji: '👮‍♀️',
    question: '¿Cómo se dice "police officer" (femenino)?',
    options: ['la policía', 'la bombera', 'la soldado'],
    correctAnswer: 'la policía',
    hint: 'Female police officer - keeps order and safety',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_033',
    emoji: '👨‍🚒',
    question: '¿Cómo se dice "firefighter"?',
    options: ['el bombero', 'el policía', 'el paramédico'],
    correctAnswer: 'el bombero',
    hint: 'Firefighter - fights fires, "bomba" means pump',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_034',
    emoji: '👨‍⚖️',
    question: '¿Cómo se dice "lawyer"?',
    options: ['el abogado', 'el juez', 'el fiscal'],
    correctAnswer: 'el abogado',
    hint: 'Male lawyer - represents clients in court',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_035',
    emoji: '👩‍⚖️',
    question: '¿Cómo se dice "lawyer" (femenino)?',
    options: ['la abogada', 'la jueza', 'la fiscal'],
    correctAnswer: 'la abogada',
    hint: 'Female lawyer - represents clients in court',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_036',
    emoji: '👨‍🔧',
    question: '¿Cómo se dice "mechanic"?',
    options: ['el mecánico', 'el plomero', 'el electricista'],
    correctAnswer: 'el mecánico',
    hint: 'Mechanic - fixes cars and machines',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_037',
    emoji: '👨‍🌾',
    question: '¿Cómo se dice "farmer"?',
    options: ['el granjero', 'el jardinero', 'el pescador'],
    correctAnswer: 'el granjero',
    hint: 'Farmer - works on farm, "agricultor" is also used',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_038',
    emoji: '👨‍✈️',
    question: '¿Cómo se dice "pilot"?',
    options: ['el piloto', 'el capitán', 'el navegante'],
    correctAnswer: 'el piloto',
    hint: 'Pilot - flies airplanes, same word for male/female',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_039',
    emoji: '👨‍🎨',
    question: '¿Cómo se dice "artist"?',
    options: ['el artista', 'el pintor', 'el músico'],
    correctAnswer: 'el artista',
    hint: 'Artist - creates art, same word for male/female',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_040',
    emoji: '👨‍🎤',
    question: '¿Cómo se dice "singer"?',
    options: ['el cantante', 'el músico', 'el bailarín'],
    correctAnswer: 'el cantante',
    hint: 'Singer - sings songs, "cantar" means to sing',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_041',
    emoji: '👨‍💻',
    question: '¿Cómo se dice "programmer"?',
    options: ['el programador', 'el ingeniero', 'el técnico'],
    correctAnswer: 'el programador',
    hint: 'Programmer - writes code, "programar" means to program',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_042',
    emoji: '👨‍🔬',
    question: '¿Cómo se dice "scientist"?',
    options: ['el científico', 'el investigador', 'el profesor'],
    correctAnswer: 'el científico',
    hint: 'Scientist - studies science, from "ciencia"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_043',
    emoji: '👨‍🏭',
    question: '¿Cómo se dice "worker"?',
    options: ['el trabajador', 'el obrero', 'el empleado'],
    correctAnswer: 'el trabajador',
    hint: 'Worker - anyone who works, from "trabajar"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_044',
    emoji: '👩‍💼',
    question: '¿Cómo se dice "secretary"?',
    options: ['la secretaria', 'la asistente', 'la gerente'],
    correctAnswer: 'la secretaria',
    hint: 'Secretary - assists in office, manages documents',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_045',
    emoji: '👨‍🍳',
    question: '¿Cómo se dice "waiter"?',
    options: ['el camarero', 'el cocinero', 'el chef'],
    correctAnswer: 'el camarero',
    hint: 'Waiter - serves in restaurant, "mesero" in Latin America',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_046',
    emoji: '👩‍🍳',
    question: '¿Cómo se dice "waitress"?',
    options: ['la camarera', 'la cocinera', 'la chef'],
    correctAnswer: 'la camarera',
    hint: 'Waitress - serves in restaurant, "mesera" in Latin America',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_047',
    emoji: '🧑‍🎨',
    question: '¿Cómo se dice "painter"?',
    options: ['el pintor', 'el artista', 'el dibujante'],
    correctAnswer: 'el pintor',
    hint: 'Painter - paints pictures, from "pintar"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_048',
    emoji: '👨‍🔧',
    question: '¿Cómo se dice "plumber"?',
    options: ['el plomero', 'el mecánico', 'el electricista'],
    correctAnswer: 'el plomero',
    hint: 'Plumber - fixes pipes and water systems',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_049',
    emoji: '⚡',
    question: '¿Cómo se dice "electrician"?',
    options: ['el electricista', 'el mecánico', 'el plomero'],
    correctAnswer: 'el electricista',
    hint: 'Electrician - works with electricity and wiring',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_050',
    emoji: '👨‍💼',
    question: '¿Cómo se dice "boss" o "manager"?',
    options: ['el jefe', 'el gerente', 'el director'],
    correctAnswer: 'el jefe',
    hint: 'Boss - person in charge, "gerente" is manager',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },

  // Physical Descriptions (25 questions)
  {
    id: 'people_051',
    emoji: '🧒',
    question: '¿Cómo se dice "young"?',
    options: ['joven', 'viejo', 'nuevo'],
    correctAnswer: 'joven',
    hint: 'Young - not old, "juventud" is youth',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_052',
    emoji: '👴',
    question: '¿Cómo se dice "old" (person)?',
    options: ['viejo', 'anciano', 'mayor'],
    correctAnswer: 'viejo',
    hint: 'Old - not young, "anciano" is elderly',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_053',
    emoji: '📏',
    question: '¿Cómo se dice "tall"?',
    options: ['alto', 'bajo', 'grande'],
    correctAnswer: 'alto',
    hint: 'Tall - high stature, opposite of "bajo"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_054',
    emoji: '📐',
    question: '¿Cómo se dice "short" (height)?',
    options: ['bajo', 'alto', 'pequeño'],
    correctAnswer: 'bajo',
    hint: 'Short - low height, opposite of "alto"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_055',
    emoji: '💪',
    question: '¿Cómo se dice "strong"?',
    options: ['fuerte', 'débil', 'musculoso'],
    correctAnswer: 'fuerte',
    hint: 'Strong - powerful, opposite of "débil"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_056',
    emoji: '😌',
    question: '¿Cómo se dice "weak"?',
    options: ['débil', 'fuerte', 'cansado'],
    correctAnswer: 'débil',
    hint: 'Weak - not strong, opposite of "fuerte"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_057',
    emoji: '😊',
    question: '¿Cómo se dice "pretty" o "beautiful"?',
    options: ['bonito', 'feo', 'hermoso'],
    correctAnswer: 'bonito',
    hint: 'Pretty - attractive, "hermoso" is also correct',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_058',
    emoji: '😞',
    question: '¿Cómo se dice "ugly"?',
    options: ['feo', 'bonito', 'malo'],
    correctAnswer: 'feo',
    hint: 'Ugly - not attractive, opposite of "bonito"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_059',
    emoji: '😃',
    question: '¿Cómo se dice "happy"?',
    options: ['feliz', 'triste', 'alegre'],
    correctAnswer: 'feliz',
    hint: 'Happy - joyful, "alegre" is also correct',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_060',
    emoji: '😢',
    question: '¿Cómo se dice "sad"?',
    options: ['triste', 'feliz', 'enojado'],
    correctAnswer: 'triste',
    hint: 'Sad - unhappy, opposite of "feliz"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_061',
    emoji: '😠',
    question: '¿Cómo se dice "angry"?',
    options: ['enojado', 'feliz', 'cansado'],
    correctAnswer: 'enojado',
    hint: 'Angry - mad, "enfadado" is also used',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_062',
    emoji: '😴',
    question: '¿Cómo se dice "tired"?',
    options: ['cansado', 'despierto', 'dormido'],
    correctAnswer: 'cansado',
    hint: 'Tired - exhausted, from "cansar"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_063',
    emoji: '🤓',
    question: '¿Cómo se dice "intelligent"?',
    options: ['inteligente', 'tonto', 'listo'],
    correctAnswer: 'inteligente',
    hint: 'Intelligent - smart, "listo" means clever',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_064',
    emoji: '😇',
    question: '¿Cómo se dice "nice" o "kind"?',
    options: ['amable', 'malo', 'simpático'],
    correctAnswer: 'amable',
    hint: 'Nice - kind person, "simpático" is friendly',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_065',
    emoji: '😈',
    question: '¿Cómo se dice "mean" o "bad"?',
    options: ['malo', 'bueno', 'cruel'],
    correctAnswer: 'malo',
    hint: 'Bad - not good, opposite of "bueno"',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_066',
    emoji: '💇',
    question: '¿Cómo se dice con pelo rubio?',
    options: ['rubio', 'moreno', 'pelirrojo'],
    correctAnswer: 'rubio',
    hint: 'Blond - light hair color, "rubia" for feminine',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_067',
    emoji: '💇‍♂️',
    question: '¿Cómo se dice con pelo castaño/moreno?',
    options: ['moreno', 'rubio', 'pelirrojo'],
    correctAnswer: 'moreno',
    hint: 'Dark-haired - brunette, "castaño" is brown',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_068',
    emoji: '🦰',
    question: '¿Cómo se dice con pelo rojo?',
    options: ['pelirrojo', 'rubio', 'moreno'],
    correctAnswer: 'pelirrojo',
    hint: 'Redhead - red hair, compound of "pelo" + "rojo"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_069',
    emoji: '👁️',
    question: '¿Cómo se dice "eyes" en español?',
    options: ['los ojos', 'las orejas', 'las cejas'],
    correctAnswer: 'los ojos',
    hint: 'Eyes - organs of sight, "ojo" is singular',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_070',
    emoji: '👃',
    question: '¿Cómo se dice "nose" en español?',
    options: ['la nariz', 'la boca', 'la oreja'],
    correctAnswer: 'la nariz',
    hint: 'Nose - organ of smell, feminine noun',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_071',
    emoji: '👄',
    question: '¿Cómo se dice "mouth" en español?',
    options: ['la boca', 'la nariz', 'el labio'],
    correctAnswer: 'la boca',
    hint: 'Mouth - for eating and speaking, feminine',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_072',
    emoji: '👂',
    question: '¿Cómo se dice "ear" en español?',
    options: ['la oreja', 'el ojo', 'la nariz'],
    correctAnswer: 'la oreja',
    hint: 'Ear - organ of hearing, "oído" is inner ear',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_073',
    emoji: '✋',
    question: '¿Cómo se dice "hand" en español?',
    options: ['la mano', 'el brazo', 'el dedo'],
    correctAnswer: 'la mano',
    hint: 'Hand - at end of arm, feminine despite ending in -o',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_074',
    emoji: '🦵',
    question: '¿Cómo se dice "leg" en español?',
    options: ['la pierna', 'el brazo', 'el pie'],
    correctAnswer: 'la pierna',
    hint: 'Leg - from hip to foot, feminine noun',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_075',
    emoji: '🦶',
    question: '¿Cómo se dice "foot" en español?',
    options: ['el pie', 'la pierna', 'la mano'],
    correctAnswer: 'el pie',
    hint: 'Foot - at end of leg, masculine noun',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },

  // Personality & Character Traits (15 questions)
  {
    id: 'people_076',
    emoji: '🤗',
    question: '¿Cómo se dice "friendly"?',
    options: ['amistoso', 'antipático', 'tímido'],
    correctAnswer: 'amistoso',
    hint: 'Friendly - sociable, "simpático" also means friendly',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_077',
    emoji: '😏',
    question: '¿Cómo se dice "funny"?',
    options: ['gracioso', 'serio', 'aburrido'],
    correctAnswer: 'gracioso',
    hint: 'Funny - makes people laugh, "chistoso" is also used',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_078',
    emoji: '🤐',
    question: '¿Cómo se dice "shy"?',
    options: ['tímido', 'atrevido', 'sociable'],
    correctAnswer: 'tímido',
    hint: 'Shy - quiet, reserved, opposite of outgoing',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_079',
    emoji: '😎',
    question: '¿Cómo se dice "brave"?',
    options: ['valiente', 'cobarde', 'tímido'],
    correctAnswer: 'valiente',
    hint: 'Brave - courageous, opposite of "cobarde"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_080',
    emoji: '🤥',
    question: '¿Cómo se dice "honest"?',
    options: ['honesto', 'mentiroso', 'sincero'],
    correctAnswer: 'honesto',
    hint: 'Honest - truthful, "sincero" is sincere',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_081',
    emoji: '😤',
    question: '¿Cómo se dice "patient"?',
    options: ['paciente', 'impaciente', 'tranquilo'],
    correctAnswer: 'paciente',
    hint: 'Patient - can wait calmly, opposite of impatient',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_082',
    emoji: '🤓',
    question: '¿Cómo se dice "studious" o "hardworking"?',
    options: ['trabajador', 'perezoso', 'estudioso'],
    correctAnswer: 'trabajador',
    hint: 'Hardworking - diligent, "estudioso" is studious',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_083',
    emoji: '😴',
    question: '¿Cómo se dice "lazy"?',
    options: ['perezoso', 'trabajador', 'activo'],
    correctAnswer: 'perezoso',
    hint: 'Lazy - doesn\'t like to work, opposite of hardworking',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_084',
    emoji: '💰',
    question: '¿Cómo se dice "generous"?',
    options: ['generoso', 'tacaño', 'egoísta'],
    correctAnswer: 'generoso',
    hint: 'Generous - gives freely, opposite of "tacaño" (stingy)',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_085',
    emoji: '😌',
    question: '¿Cómo se dice "calm" o "quiet"?',
    options: ['tranquilo', 'nervioso', 'ruidoso'],
    correctAnswer: 'tranquilo',
    hint: 'Calm - peaceful, "quieto" means still',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_086',
    emoji: '😰',
    question: '¿Cómo se dice "nervous"?',
    options: ['nervioso', 'tranquilo', 'calmado'],
    correctAnswer: 'nervioso',
    hint: 'Nervous - anxious, opposite of "tranquilo"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_087',
    emoji: '🎯',
    question: '¿Cómo se dice "responsible"?',
    options: ['responsable', 'irresponsable', 'serio'],
    correctAnswer: 'responsable',
    hint: 'Responsible - reliable, can be trusted',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_088',
    emoji: '😌',
    question: '¿Cómo se dice "polite"?',
    options: ['educado', 'grosero', 'cortés'],
    correctAnswer: 'educado',
    hint: 'Polite - well-mannered, "cortés" is courteous',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_089',
    emoji: '😠',
    question: '¿Cómo se dice "rude"?',
    options: ['grosero', 'educado', 'cortés'],
    correctAnswer: 'grosero',
    hint: 'Rude - impolite, opposite of "educado"',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_090',
    emoji: '🤝',
    question: '¿Cómo se dice "helpful"?',
    options: ['servicial', 'egoísta', 'útil'],
    correctAnswer: 'servicial',
    hint: 'Helpful - likes to help others, "útil" means useful',
    points: 5,
    category: 'people',
    difficulty: 'hard',
  },

  // Age & Life Stages (10 questions)
  {
    id: 'people_091',
    emoji: '👶',
    question: '¿Cómo se dice "child" o "kid"?',
    options: ['el niño', 'el bebé', 'el adolescente'],
    correctAnswer: 'el niño',
    hint: 'Child - young person, "niña" is girl',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_092',
    emoji: '🧒',
    question: '¿Cómo se dice "boy"?',
    options: ['el niño', 'el chico', 'el hombre'],
    correctAnswer: 'el niño',
    hint: 'Boy - young male, "chico" is also used',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_093',
    emoji: '👧',
    question: '¿Cómo se dice "girl"?',
    options: ['la niña', 'la chica', 'la mujer'],
    correctAnswer: 'la niña',
    hint: 'Girl - young female, "chica" is also used',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_094',
    emoji: '🧑',
    question: '¿Cómo se dice "man"?',
    options: ['el hombre', 'el niño', 'el chico'],
    correctAnswer: 'el hombre',
    hint: 'Man - adult male, "hombres" is plural',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_095',
    emoji: '👩',
    question: '¿Cómo se dice "woman"?',
    options: ['la mujer', 'la niña', 'la chica'],
    correctAnswer: 'la mujer',
    hint: 'Woman - adult female, "mujeres" is plural',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_096',
    emoji: '🧒',
    question: '¿Cómo se dice "teenager"?',
    options: ['el adolescente', 'el niño', 'el adulto'],
    correctAnswer: 'el adolescente',
    hint: 'Teenager - between child and adult, 13-19 years',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_097',
    emoji: '🧑',
    question: '¿Cómo se dice "adult"?',
    options: ['el adulto', 'el niño', 'el joven'],
    correctAnswer: 'el adulto',
    hint: 'Adult - fully grown person, mature',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_098',
    emoji: '👵',
    question: '¿Cómo se dice "elderly person"?',
    options: ['el anciano', 'el viejo', 'el mayor'],
    correctAnswer: 'el anciano',
    hint: 'Elderly - very old person, "anciana" is feminine',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
  {
    id: 'people_099',
    emoji: '👤',
    question: '¿Cómo se dice "person"?',
    options: ['la persona', 'el hombre', 'la gente'],
    correctAnswer: 'la persona',
    hint: 'Person - individual, always feminine even for males',
    points: 5,
    category: 'people',
    difficulty: 'easy',
  },
  {
    id: 'people_100',
    emoji: '👥',
    question: '¿Cómo se dice "people" (colectivo)?',
    options: ['la gente', 'las personas', 'los hombres'],
    correctAnswer: 'la gente',
    hint: 'People - group of persons, singular feminine noun',
    points: 5,
    category: 'people',
    difficulty: 'medium',
  },
];
