/**
 * Animals Category Questions
 * Category: animals
 */

export const plantsAnimalsQuestions = [
{
    id: 'plants_animals_001',
    emoji: '🐕',
    question: '¿Cuál es un animal doméstico común?',
    translation: 'What is a common domestic animal?',
    options: ['el perro', 'el lobo', 'el zorro'],
    correctAnswer: 'el perro',
    hint: 'Dog - man\'s best friend, "canis" in Latin',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_002',
    emoji: '🐈',
    question: '¿Qué animal dice "miau"?',
    translation: 'What animal says \'meow\'?',
    options: ['el gato', 'el ratón', 'el loro'],
    correctAnswer: 'el gato',
    hint: 'Cat - independent pet, "felino" in scientific terms',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_003',
    emoji: '🐭',
    question: '¿Qué animal pequeño vive en las casas?',
    translation: 'What small animal lives in houses?',
    options: ['el ratón', 'la hormiga', 'la cucaracha'],
    correctAnswer: 'el ratón',
    hint: 'Mouse - small rodent, "ratoncillo" is diminutive',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'afraid',
  },
  {
    id: 'plants_animals_004',
    emoji: '🐀',
    question: '¿Qué roedor es más grande que el ratón?',
    translation: 'What rodent is bigger than a mouse?',
    options: ['la rata', 'el hamster', 'el conejillo de indias'],
    correctAnswer: 'la rata',
    hint: 'Rat - larger rodent, intelligent, often kept as pets',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_005',
    emoji: '🐹',
    question: '¿Qué roedor pequeño tiene bolsas en las mejillas?',
    translation: 'What small rodent has pouches in its cheeks?',
    options: ['el hamster', 'el ratón', 'el gerbil'],
    correctAnswer: 'el hamster',
    hint: 'Hamster - small rodent, cheek pouches, stores food, popular pet',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_006',
    emoji: '🐿️',
    question: '¿Qué animal come frutos secos en el árbol?',
    translation: 'What animal has orange stripes?',
    options: ['la ardilla', 'el pájaro', 'la catarita'],
    correctAnswer: 'la ardilla',
    hint: 'Squirrel - bushy tail, climbs trees, collects nuts',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_007',
    emoji: '🐇',
    question: '¿Qué animal tiene orejas largas?',
    translation: 'What animal has a trunk?',
    options: ['el conejo', 'el venado', 'la cabra'],
    correctAnswer: 'el conejo',
    hint: 'Rabbit - hops around, "conej�🐇illo de indias" is guinea pig',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_008',
    emoji: '🦁',
    question: '¿Cuál es el rey de la selva?',
    translation: 'What small rodent has pouches in its cheeks?',
    options: ['el león', 'el tigre', 'el elefante'],
    correctAnswer: 'el león',
    hint: 'Lion - has a mane, roars loudly, symbol of courage',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_009',
    emoji: '🐯',
    question: '¿Qué animal tiene rayas naranjas?',
    translation: 'What animal has orange stripes?',
    options: ['el tigre', 'el leopardo', 'el gato montés'],
    correctAnswer: 'el tigre',
    hint: 'Tiger - striped big cat, endangered species',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_010',
    emoji: '🐘',
    question: '¿Qué animal tiene una trompa?',
    translation: 'What animal has a trunk?',
    options: ['el elefante', 'la jirafa', 'el cocodrilo'],
    correctAnswer: 'el elefante',
    hint: 'Elephant - largest land animal, has tusks',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_011',
    emoji: '🦒',
    question: '¿Qué animal tiene el cuello más largo?',
    translation: 'What animal has the longest neck?',
    options: ['la jirafa', 'el avestruz', 'la llama'],
    correctAnswer: 'la jirafa',
    hint: 'Giraffe - tallest land animal, African herbivore',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_012',
    emoji: '🦓',
    question: '¿Qué animal tiene rayas blancas y negras?',
    translation: 'What animal has white and black stripes?',
    options: ['la cebra', 'el caballo', 'el burro'],
    correctAnswer: 'la cebra',
    hint: 'Zebra - related to horses, African animal, striped',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'plants_animals_013',
    emoji: '🦏',
    question: '¿Qué animal tiene un cuerno en la nariz?',
    translation: 'What animal has a horn on its nose?',
    options: ['el rinoceronte', 'el alce', 'el búfalo'],
    correctAnswer: 'el rinoceronte',
    hint: 'Rhinoceros - large African animal, endangered',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_014',
    emoji: '🐻',
    question: '¿Qué animal grande vive en el bosque?',
    translation: 'What big animal lives in the forest?',
    options: ['el oso', 'el ciervo', 'el puma'],
    correctAnswer: 'el oso',
    hint: 'Bear - large mammal, hibernates in winter',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_015',
    emoji: '🦊',
    question: '¿Qué animal es parecido al perro pero salvaje?',
    translation: 'What animal is similar to a dog but wild?',
    options: ['el zorro', 'el lobo', 'el chacal'],
    correctAnswer: 'el zorro',
    hint: 'Fox - cunning animal, reddish fur, similar to dog',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_016',
    emoji: '🐺',
    question: '¿Qué animal aúlla a la luna?',
    translation: 'What animal howls at the moon?',
    options: ['el lobo', 'el perro', 'el coyote'],
    correctAnswer: 'el lobo',
    hint: 'Wolf - wild canine, hunts in packs, endangered in many places',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_017',
    emoji: '🐄',
    question: '¿Qué animal produce leche?',
    translation: 'What animal produces milk?',
    options: ['la vaca', 'la oveja', 'la cabra'],
    correctAnswer: 'la vaca',
    hint: 'Cow - dairy animal, bovine, "ternera" for calf',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'plants_animals_018',
    emoji: '🐷',
    question: '¿Qué animal tiene cola rizada?',
    translation: 'What animal has a curly tail?',
    options: ['el cerdo', 'el cordero', 'el caballo'],
    correctAnswer: 'el cerdo',
    hint: 'Pig - farm animal, curly tail, "cochinillo" for piglet',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_019',
    emoji: '🐑',
    question: '¿Qué animal produce lana?',
    translation: 'What animal produces wool?',
    options: ['la oveja', 'la cabra', 'el cerdo'],
    correctAnswer: 'la oveja',
    hint: 'Sheep - woolly farm animal, "carnero" for ram',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_020',
    emoji: '🐐',
    question: '¿Qué animal trepa bien en las montañas?',
    translation: 'What animal climbs well in the mountains?',
    options: ['la cabra', 'el cordero', 'la oveja'],
    correctAnswer: 'la cabra',
    hint: 'Goat - climbs steep terrain, agile, produces milk',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_021',
    emoji: '🐴',
    question: '¿Qué animal montas para viajar?',
    translation: 'What animal do you ride to travel?',
    options: ['el caballo', 'el burro', 'el camello'],
    correctAnswer: 'el caballo',
    hint: 'Horse - large hoofed animal, rides quickly, "yegua" for mare',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_022',
    emoji: '🦘',
    question: '¿Qué animal salta y viene de Australia?',
    translation: 'What animal jumps and comes from Australia?',
    options: ['el canguro', 'el koala', 'el wombat'],
    correctAnswer: 'el canguro',
    hint: 'Kangaroo - jumps on hind legs, Australian, carries baby in pouch',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_023',
    emoji: '🐨',
    question: '¿Qué animal come eucalipto?',
    translation: 'What animal eats eucalyptus?',
    options: ['el koala', 'el canguro', 'el oso panda'],
    correctAnswer: 'el koala',
    hint: 'Koala - looks like bear, eats eucalyptus leaves, Australian marsupial',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'plants_animals_024',
    emoji: '🐼',
    question: '¿Qué animal gigante es blanco y negro?',
    translation: 'What giant animal is black and white?',
    options: ['el oso panda', 'el oso polar', 'el tejón'],
    correctAnswer: 'el oso panda',
    hint: 'Panda - endangered, eats bamboo, from China',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_025',
    emoji: '🐍',
    question: '¿Qué animal doméstico es una mascotas en casas?',
    translation: 'What domestic animal is a pet in houses?',
    options: ['la serpiente', 'el cocodrilo', 'el iguana'],
    correctAnswer: 'la serpiente',
    hint: 'Snake - can be kept as exotic pet, some docile species',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_026',
    emoji: '🦁',
    question: '¿Cuál es el felino salvaje más grande de América?',
    translation: 'What is the largest wild cat in America?',
    options: ['el puma', 'el jaguár', 'el ocelote'],
    correctAnswer: 'el jaguár',
    hint: 'Jaguar - spotted big cat, largest cat in Americas, endangered',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_027',
    emoji: '🐒',
    question: '¿Qué animal es parecido a los humanos?',
    translation: 'What animal is similar to humans?',
    options: ['el mono', 'el simio', 'el chimpancé'],
    correctAnswer: 'el mono',
    hint: 'Monkey - primate with tail, swings in trees, intelligent',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'plants_animals_028',
    emoji: '🦍',
    question: '¿Qué primate grande tiene brazos muy largos?',
    translation: 'What big primate has very long arms?',
    options: ['el gorila', 'el orangután', 'el chimpancé'],
    correctAnswer: 'el gorila',
    hint: 'Gorilla - largest primate, endangered, knuckle-walks, very strong',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_029',
    emoji: '🦅',
    question: '¿Qué pájaro grande vuela muy alto?',
    translation: 'What big bird flies very high?',
    options: ['el águila', 'el halcón', 'el cóndor'],
    correctAnswer: 'el águila',
    hint: 'Eagle - large bird of prey, symbol of strength and freedom',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_030',
    emoji: '🦉',
    question: '¿Qué pájaro ve bien de noche?',
    translation: 'What bird sees well at night?',
    options: ['el búho', 'la lechuza', 'el cuervo'],
    correctAnswer: 'el búho',
    hint: 'Owl - nocturnal bird of prey, large eyes, rotates head',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_031',
    emoji: '🦜',
    question: '¿Qué pájaro colorido puede hablar?',
    translation: 'What colorful bird can talk?',
    options: ['el loro', 'el papagayo', 'el periquito'],
    correctAnswer: 'el loro',
    hint: 'Parrot - intelligent, colorful, mimics sounds and words',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_032',
    emoji: '🦆',
    question: '¿Qué pájaro acuático tiene pico plano?',
    translation: 'What water bird has a flat beak?',
    options: ['el pato', 'la gaviota', 'el cisne'],
    correctAnswer: 'el pato',
    hint: 'Duck - waterfowl, quacks, waddles on land',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_033',
    emoji: '🦢',
    question: '¿Qué pájaro blanco es elegante?',
    translation: 'What white bird is elegant?',
    options: ['el cisne', 'el pato', 'la gaviota'],
    correctAnswer: 'el cisne',
    hint: 'Swan - large water bird, elegant, white or black species',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_034',
    emoji: '🦚',
    question: '¿Qué pájaro tiene plumas de muchos colores?',
    translation: 'What bird has feathers of many colors?',
    options: ['el pavo real', 'el loro', 'el faisán'],
    correctAnswer: 'el pavo real',
    hint: 'Peacock - displays colorful feathers, Indian bird, very beautiful',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_035',
    emoji: '🐢',
    question: '¿Qué animal tiene caparazón?',
    translation: 'What animal has a shell?',
    options: ['la tortuga', 'el cangrejo', 'el caracol'],
    correctAnswer: 'la tortuga',
    hint: 'Turtle - reptile with hard shell, can live long time',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'afraid',
  },
  {
    id: 'plants_animals_036',
    emoji: '🦎',
    question: '¿Qué animal pequeño tiene cola larga?',
    translation: 'What small animal has a long tail?',
    options: ['la lagartija', 'el camaleón', 'la iguana'],
    correctAnswer: 'la lagartija',
    hint: 'Lizard - small reptile, can detach tail, sunbathes',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_037',
    emoji: '🐊',
    question: '¿Qué animal verde vive en el río?',
    translation: 'What green animal lives in the river?',
    options: ['el cocodrilo', 'la serpiente', 'la tortuga'],
    correctAnswer: 'el cocodrilo',
    hint: 'Crocodile - large reptile, sharp teeth, ancient predator',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_038',
    emoji: '🐙',
    question: '¿Qué animal marino tiene ocho brazos?',
    translation: 'What sea animal has eight arms?',
    options: ['el pulpo', 'la medusa', 'el calamar'],
    correctAnswer: 'el pulpo',
    hint: 'Octopus - eight tentacles, intelligent, changes color',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_039',
    emoji: '🦑',
    question: '¿Qué animal marino parece el pulpo?',
    translation: 'What sea animal looks like an octopus?',
    options: ['el calamar', 'la medusa', 'el caracol'],
    correctAnswer: 'el calamar',
    hint: 'Squid - similar to octopus, ten tentacles, emits ink',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_040',
    emoji: '🐠',
    question: '¿Qué animal vive en el agua?',
    translation: 'What animal lives in water?',
    options: ['el pez', 'el pescado', 'la aleta'],
    correctAnswer: 'el pez',
    hint: 'Fish - aquatic animal, has gills and fins, "pescado" means cooked fish',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_041',
    emoji: '🦈',
    question: '¿Qué pez es peligroso?',
    translation: 'What fish is dangerous?',
    options: ['el tiburón', 'la sardina', 'la trucha'],
    correctAnswer: 'el tiburón',
    hint: 'Shark - dangerous predator, sharp teeth, appears in all oceans',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'afraid',
  },
  {
    id: 'plants_animals_042',
    emoji: '🐋',
    question: '¿Qué animal marino es el más grande?',
    translation: 'What sea animal is the biggest?',
    options: ['la ballena', 'el tiburón', 'el delfín'],
    correctAnswer: 'la ballena',
    hint: 'Whale - largest animal on Earth, marine mammal, endangered species',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_043',
    emoji: '🐬',
    question: '¿Qué animal marino es inteligente y amigable?',
    translation: 'What sea animal is intelligent and friendly?',
    options: ['el delfín', 'la ballena', 'el tiburón'],
    correctAnswer: 'el delfín',
    hint: 'Dolphin - intelligent marine mammal, friendly to humans, playful',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_044',
    emoji: '🦭',
    question: '¿Qué animal tiene bigotes y vive en el hielo?',
    translation: 'What animal has whiskers and lives in ice?',
    options: ['la foca', 'la morsa', 'el oso polar'],
    correctAnswer: 'la foca',
    hint: 'Seal - marine mammal, whiskers, lives in cold waters',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_045',
    emoji: '🦀',
    question: '¿Qué animal tiene diez patas?',
    translation: 'What animal has ten legs?',
    options: ['el cangrejo', 'el camarón', 'la langosta'],
    correctAnswer: 'el cangrejo',
    hint: 'Crab - crustacean with claws, walks sideways, edible',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_046',
    emoji: '🦞',
    question: '¿Qué animal parece un cangrejo grande?',
    translation: 'What animal looks like a big crab?',
    options: ['la langosta', 'el camarón', 'la ostra'],
    correctAnswer: 'la langosta',
    hint: 'Lobster - large crustacean, delicacy, expensive',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_047',
    emoji: '🦗',
    question: '¿Qué insecto hace ruido por la noche?',
    translation: 'What insect makes noise at night?',
    options: ['el grillo', 'la cigarra', 'el saltamontes'],
    correctAnswer: 'el grillo',
    hint: 'Cricket - insect, chirps at night, jumps, used in sports',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_048',
    emoji: '🦋',
    question: '¿Qué insecto tiene alas coloridas?',
    translation: 'What insect has colorful wings?',
    options: ['la mariposa', 'la polilla', 'la libélula'],
    correctAnswer: 'la mariposa',
    hint: 'Butterfly - colorful insect, goes through metamorphosis',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_049',
    emoji: '🐝',
    question: '¿Qué insecto produce miel?',
    translation: 'What insect produces honey?',
    options: ['la abeja', 'la avispa', 'el abejorro'],
    correctAnswer: 'la abeja',
    hint: 'Bee - produces honey, pollinates flowers, lives in colonies',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_050',
    emoji: '🐜',
    question: '¿Qué insecto pequeño trabaja en equipo?',
    translation: 'What small insect works as a team?',
    options: ['la hormiga', 'la termita', 'el escarabajo'],
    correctAnswer: 'la hormiga',
    hint: 'Ant - social insect, works in colonies, carries leaves',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_051',
    emoji: '🦗',
    question: '¿Qué insecto salta alto?',
    translation: 'What insect jumps high?',
    options: ['el saltamontes', 'la cucaracha', 'el escarabajo'],
    correctAnswer: 'el saltamontes',
    hint: 'Grasshopper - jumps far, green color, eats plants',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_052',
    emoji: '🐛',
    question: '¿Cuál es la larva de la mariposa?',
    translation: 'What is the larva of a butterfly?',
    options: ['la oruga', 'la pupa', 'el gusano'],
    correctAnswer: 'la oruga',
    hint: 'Caterpillar - larva stage of butterfly, eats leaves, colorful',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_053',
    emoji: '🦇',
    question: '¿Qué animal vuela de noche?',
    translation: 'What animal flies at night?',
    options: ['el murciélago', 'el búho', 'la lechuza'],
    correctAnswer: 'el murciélago',
    hint: 'Bat - only mammal that flies, uses echolocation, nocturnal',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_054',
    emoji: '🦢',
    question: '¿Qué pájaro blanco es elegante?',
    translation: 'What white bird is elegant?',
    options: ['el cisne', 'el pato', 'la gaviota'],
    correctAnswer: 'el cisne',
    hint: 'Swan - large water bird, elegant, white or black species',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_055',
    emoji: '🦚',
    question: '¿Qué pájaro tiene plumas de muchos colores?',
    translation: 'What bird has feathers of many colors?',
    options: ['el pavo real', 'el loro', 'el faisán'],
    correctAnswer: 'el pavo real',
    hint: 'Peacock - displays colorful feathers, Indian bird, very beautiful',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_056',
    emoji: '🐢',
    question: '¿Qué animal tiene caparazón?',
    translation: 'What animal has a shell?',
    options: ['la tortuga', 'el cangrejo', 'el caracol'],
    correctAnswer: 'la tortuga',
    hint: 'Turtle - reptile with hard shell, can live long time',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_057',
    emoji: '🦃',
    question: '¿Qué ave grande se come tradicionalmente en Acción de Gracias?',
    translation: 'What large bird is traditionally eaten at Thanksgiving?',
    options: ['el pavo', 'el pollo', 'el ganso'],
    correctAnswer: 'el pavo',
    hint: 'Turkey - large bird traditionally eaten at Thanksgiving and Christmas',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_058',
    emoji: '🐂',
    question: '¿Cómo se llama la vaca macho?',
    translation: 'What is a male cow called?',
    options: ['el toro', 'el buey', 'el carnero'],
    correctAnswer: 'el toro',
    hint: 'Bull - male cow, strong and powerful animal',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_059',
    emoji: '🐓',
    question: '¿Cómo se llama el pollo macho que canta por la mañana?',
    translation: 'What is the male chicken that crows in the morning called?',
    options: ['el gallo', 'el pollo', 'el pavo'],
    correctAnswer: 'el gallo',
    hint: 'Rooster - male chicken, crows at dawn, has colorful feathers',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_060',
    emoji: '🐔',
    question: '¿Qué ave de granja pone huevos?',
    translation: 'What farm bird lays eggs?',
    options: ['la gallina', 'el gallo', 'el pato'],
    correctAnswer: 'la gallina',
    hint: 'Chicken/Hen - farm bird, lays eggs, female of rooster',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_061',
    emoji: '🐣',
    question: '¿Cómo se llama el bebé que sale del huevo?',
    translation: 'What is the baby that comes out of the egg called?',
    options: ['el pollito', 'el patito', 'el pajarito'],
    correctAnswer: 'el pollito',
    hint: 'Chick - baby bird that hatches from egg, young chicken',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'plants_animals_062',
    emoji: '🦨',
    question: '¿Qué animal tiene rayas blancas y negras y produce mal olor?',
    translation: 'What animal has black and white stripes and produces a bad smell?',
    options: ['el zorrillo', 'la mofeta', 'el tejón'],
    correctAnswer: 'el zorrillo',
    hint: 'Skunk - black and white striped animal, sprays bad smell for defense',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'afraid',
  },
  {
    id: 'plants_animals_063',
    emoji: '🐧',
    question: '¿Qué ave nada pero no vuela?',
    translation: 'What bird swims but doesn\'t fly?',
    options: ['el pingüino', 'el pato', 'el cisne'],
    correctAnswer: 'el pingüino',
    hint: 'Penguin - flightless bird, swims in cold waters, lives in Antarctica',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'plants_animals_064',
    emoji: '🦦',
    question: '¿Qué animal juguetón nada en los ríos?',
    translation: 'What playful animal swims in rivers?',
    options: ['la nutria', 'el castor', 'la foca'],
    correctAnswer: 'la nutria',
    hint: 'Otter - playful aquatic mammal, swims in rivers and oceans, holds hands while sleeping',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_065',
    emoji: '🐦‍⬛',
    question: '¿Qué pájaro pequeño es común en las ciudades?',
    translation: 'What small bird is common in cities?',
    options: ['el gorrión', 'el canario', 'el jilguero'],
    correctAnswer: 'el gorrión',
    hint: 'Sparrow - small brown bird, common in cities and towns, chirps frequently',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_066',
    emoji: '🪿',
    question: '¿Qué ave tiene cuello largo y hace "honk"?',
    translation: 'What bird has a long neck and goes \'honk\'?',
    options: ['el ganso', 'el pato', 'el cisne'],
    correctAnswer: 'el ganso',
    hint: 'Goose - waterfowl with long neck, honks loudly, can be aggressive',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'plants_animals_067',
    emoji: '🪰',
    question: '¿Qué insecto molesto vuela en la casa?',
    translation: 'What annoying insect flies around the house?',
    options: ['la mosca', 'el mosquito', 'la avispa'],
    correctAnswer: 'la mosca',
    hint: 'Fly - common household insect, buzzes around, attracted to food',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_068',
    emoji: '🐸',
    question: '¿Qué animal anfibio salta y dice "croac"?',
    translation: 'What amphibian animal jumps and says \'croak\'?',
    options: ['la rana', 'el sapo', 'la salamandra'],
    correctAnswer: 'la rana',
    hint: 'Frog - amphibian that jumps, lives near water, croaks loudly',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_069',
    emoji: '🪲',
    question: '¿Qué insecto tiene un caparazón duro?',
    translation: 'What insect has a hard shell?',
    options: ['el escarabajo', 'la mariquita', 'la cucaracha'],
    correctAnswer: 'el escarabajo',
    hint: 'Beetle - insect with hard shell, many species, some can fly',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'plants_animals_070',
    emoji: '🦖',
    question: '¿Qué animal prehistórico gigante está extinto?',
    translation: 'What giant prehistoric animal is extinct?',
    options: ['el dinosaurio', 'el mamut', 'el tigre dientes de sable'],
    correctAnswer: 'el dinosaurio',
    hint: 'Dinosaur - prehistoric reptile, extinct millions of years ago, many species',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'afraid',
  },
  {
    id: 'plants_animals_071',
    emoji: '🪸',
    question: '¿Qué organismo marino forma arrecifes?',
    translation: 'What marine organism forms reefs?',
    options: ['el coral', 'la esponja', 'la anémona'],
    correctAnswer: 'el coral',
    hint: 'Coral - marine organism, forms reefs, provides habitat for fish',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_072',
    emoji: '🦧',
    question: '¿Qué primate tiene pelo naranja y vive en los árboles?',
    translation: 'What primate has orange fur and lives in trees?',
    options: ['el orangután', 'el mono', 'el gorila'],
    correctAnswer: 'el orangután',
    hint: 'Orangutan - great ape with orange fur, lives in trees, found in Southeast Asia',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_073',
    emoji: '🫎',
    question: '¿Qué animal grande tiene astas y vive en el bosque frío?',
    translation: 'What large animal has antlers and lives in cold forests?',
    options: ['el alce', 'el ciervo', 'el reno'],
    correctAnswer: 'el alce',
    hint: 'Moose - largest deer species, has big antlers, lives in cold forests',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'plants_animals_074',
    emoji: '🦌',
    question: '¿Qué animal tiene cuernos y vive en el bosque?',
    translation: 'What animal has antlers and lives in the forest?',
    options: ['el ciervo', 'el alce', 'la cabra'],
    correctAnswer: 'el ciervo',
    hint: 'Deer - graceful animal with antlers, lives in forests and meadows',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_075',
    emoji: '🦮',
    question: '¿Qué perro ayuda a las personas con discapacidades?',
    translation: 'What dog helps people with disabilities?',
    options: ['el perro guía', 'el perro policía', 'el perro pastor'],
    correctAnswer: 'el perro guía',
    hint: 'Guide dog - service dog trained to help people with disabilities, especially the blind',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_076',
    emoji: '🦩',
    question: '¿Qué ave rosada tiene patas largas?',
    translation: 'What pink bird has long legs?',
    options: ['el flamenco', 'la garza', 'el cisne'],
    correctAnswer: 'el flamenco',
    hint: 'Flamingo - pink bird with long legs, stands on one leg, lives near water',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_077',
    emoji: '🦫',
    question: '¿Qué animal construye presas en los ríos?',
    translation: 'What animal builds dams in rivers?',
    options: ['el castor', 'la nutria', 'el tejón'],
    correctAnswer: 'el castor',
    hint: 'Beaver - builds dams in rivers, has flat tail, strong teeth, gnaws trees',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'plants_animals_078',
    emoji: '🪺',
    question: '¿Dónde ponen los pájaros sus huevos?',
    translation: 'Where do birds lay their eggs?',
    options: ['el nido', 'la cueva', 'el árbol'],
    correctAnswer: 'el nido',
    hint: 'Nest - birds build it with twigs and grass, used for laying eggs and raising chicks',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_079',
    emoji: '🐻‍❄️',
    question: '¿Qué oso blanco vive en el Ártico?',
    translation: 'What white bear lives in the Arctic?',
    options: ['el oso polar', 'el oso pardo', 'el oso negro'],
    correctAnswer: 'el oso polar',
    hint: 'Polar bear - white bear, lives in Arctic, excellent swimmer, hunts seals',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_080',
    emoji: '🐆',
    question: '¿Qué felino manchado corre muy rápido?',
    translation: 'What spotted feline runs very fast?',
    options: ['el guepardo', 'el leopardo', 'el tigre'],
    correctAnswer: 'el guepardo',
    hint: 'Cheetah - fastest land animal, spotted coat, slender build',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'plants_animals_081',
    emoji: '🦓',
    question: '¿Qué animal parece un caballo con rayas?',
    translation: 'What animal looks like a horse with stripes?',
    options: ['la cebra', 'el burro', 'la mula'],
    correctAnswer: 'la cebra',
    hint: 'Zebra - black and white stripes, lives in Africa, related to horses',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_082',
    emoji: '🦒',
    question: '¿Qué animal tiene el cuello más largo del mundo?',
    translation: 'What animal has the longest neck in the world?',
    options: ['la jirafa', 'el avestruz', 'el camello'],
    correctAnswer: 'la jirafa',
    hint: 'Giraffe - tallest animal, long neck to reach high leaves, lives in Africa',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_083',
    emoji: '🦏',
    question: '¿Qué animal grande tiene un cuerno en la nariz?',
    translation: 'What large animal has a horn on its nose?',
    options: ['el rinoceronte', 'el hipopótamo', 'el búfalo'],
    correctAnswer: 'el rinoceronte',
    hint: 'Rhinoceros - large animal with horn on nose, thick skin, herbivore',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_084',
    emoji: '🦛',
    question: '¿Qué animal grande vive en ríos africanos?',
    translation: 'What large animal lives in African rivers?',
    options: ['el hipopótamo', 'el cocodrilo', 'el rinoceronte'],
    correctAnswer: 'el hipopótamo',
    hint: 'Hippopotamus - large river animal, semi-aquatic, powerful jaws, lives in Africa',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'plants_animals_085',
    emoji: '🐪',
    question: '¿Qué animal tiene una joroba y vive en el desierto?',
    translation: 'What animal has a hump and lives in the desert?',
    options: ['el camello', 'el dromedario', 'la llama'],
    correctAnswer: 'el camello',
    hint: 'Camel - has humps for storing fat, survives in desert, can go without water for days',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_086',
    emoji: '🐫',
    question: '¿Qué animal tiene dos jorobas?',
    translation: 'What animal has two humps?',
    options: ['el camello bactriano', 'el dromedario', 'la llama'],
    correctAnswer: 'el camello bactriano',
    hint: 'Bactrian camel - has two humps, from Central Asia, adapted to cold deserts',
    points: 5,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_087',
    emoji: '🦙',
    question: '¿Qué animal andino se parece al camello?',
    translation: 'What Andean animal looks like a camel?',
    options: ['la llama', 'la alpaca', 'la vicuña'],
    correctAnswer: 'la llama',
    hint: 'Llama - South American camelid, used as pack animal, lives in Andes mountains',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_088',
    emoji: '🦘',
    question: '¿Qué animal salta y tiene una bolsa?',
    translation: 'What animal hops and has a pouch?',
    options: ['el canguro', 'el koala', 'el wombat'],
    correctAnswer: 'el canguro',
    hint: 'Kangaroo - hops on powerful hind legs, has pouch for babies, from Australia',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'plants_animals_089',
    emoji: '🐨',
    question: '¿Qué animal duerme mucho en los árboles?',
    translation: 'What animal sleeps a lot in trees?',
    options: ['el koala', 'el perezoso', 'el mapache'],
    correctAnswer: 'el koala',
    hint: 'Koala - sleeps up to 20 hours, eats eucalyptus, lives in Australia',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'surprised',
  },
  {
    id: 'plants_animals_090',
    emoji: '🦥',
    question: '¿Qué animal se mueve muy lentamente?',
    translation: 'What animal moves very slowly?',
    options: ['el perezoso', 'el koala', 'la tortuga'],
    correctAnswer: 'el perezoso',
    hint: 'Sloth - extremely slow movement, hangs from trees, lives in rainforests',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_091',
    emoji: '🦦',
    question: '¿Qué animal juguetón nada en los ríos?',
    translation: 'What playful animal swims in rivers?',
    options: ['la nutria', 'el castor', 'la foca'],
    correctAnswer: 'la nutria',
    hint: 'Otter - playful aquatic mammal, uses rocks to open shells, lives near water',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_092',
    emoji: '🦨',
    question: '¿Qué animal produce un olor muy fuerte para defenderse?',
    translation: 'What animal produces a very strong smell to defend itself?',
    options: ['el zorrillo', 'la mofeta', 'el tejón'],
    correctAnswer: 'el zorrillo',
    hint: 'Skunk - sprays strong-smelling liquid as defense, black with white stripes',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_093',
    emoji: '🦡',
    question: '¿Qué animal nocturno tiene rayas en la cara?',
    translation: 'What nocturnal animal has stripes on its face?',
    options: ['el tejón', 'el mapache', 'el zorrillo'],
    correctAnswer: 'el tejón',
    hint: 'Badger - nocturnal, lives in burrows called setts, distinctive facial stripes',
    points: 5,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'plants_animals_094',
    emoji: '🦝',
    question: '¿Qué animal tiene máscara negra y cola con anillos?',
    translation: 'What animal has a black mask and ringed tail?',
    options: ['el mapache', 'el tejón', 'el panda rojo'],
    correctAnswer: 'el mapache',
    hint: 'Raccoon - masked face, ringed tail, intelligent, washes food before eating',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_095',
    emoji: '🐊',
    question: '¿Qué reptil grande vive en pantanos?',
    translation: 'What large reptile lives in swamps?',
    options: ['el caimán', 'el cocodrilo', 'el lagarto'],
    correctAnswer: 'el caimán',
    hint: 'Alligator - large reptile, lives in swamps, powerful jaws, from Americas',
    points: 5,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_096',
    emoji: '🐢',
    question: '¿Qué animal lleva su casa en el caparazón?',
    translation: 'What animal carries its house in its shell?',
    options: ['la tortuga', 'el caracol', 'el cangrejo ermitaño'],
    correctAnswer: 'la tortuga',
    hint: 'Turtle - reptile with protective shell, can be aquatic or terrestrial, long-lived',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_097',
    emoji: '🦎',
    question: '¿Qué reptil pequeño puede cambiar de color?',
    translation: 'What small reptile can change color?',
    options: ['el camaleón', 'la lagartija', 'la iguana'],
    correctAnswer: 'el camaleón',
    hint: 'Chameleon - changes color for camouflage and communication, long tongue, swivel eyes',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'plants_animals_098',
    emoji: '🦈',
    question: '¿Qué pez grande tiene muchos dientes?',
    translation: 'What large fish has many teeth?',
    options: ['el tiburón', 'la ballena', 'el delfín'],
    correctAnswer: 'el tiburón',
    hint: 'Shark - large predatory fish, multiple rows of teeth, cartilage skeleton',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_099',
    emoji: '🐳',
    question: '¿Qué animal marino es el más grande del mundo?',
    translation: 'What marine animal is the largest in the world?',
    options: ['la ballena azul', 'el tiburón ballena', 'la orca'],
    correctAnswer: 'la ballena azul',
    hint: 'Blue whale - largest animal ever, can weigh up to 200 tons, eats krill',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_100',
    emoji: '🦇',
    question: '¿Qué mamífero vuela de noche?',
    translation: 'What mammal flies at night?',
    options: ['el murciélago', 'la lechuza', 'el búho'],
    correctAnswer: 'el murciélago',
    hint: 'Bat - only flying mammal, uses echolocation, often nocturnal, eats insects or fruit',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_101',
    emoji: 'alpaca.png',
    question: '¿Qué animal andino produce lana suave?',
    translation: 'What Andean animal produces soft wool?',
    options: ['la alpaca', 'la llama', 'la vicuña'],
    correctAnswer: 'la alpaca',
    hint: 'Alpaca - South American camelid, produces soft wool, smaller than llama',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_102',
    emoji: 'baboon.png',
    question: '¿Qué primate tiene cara colorida?',
    translation: 'What primate has a colorful face?',
    options: ['el mandril', 'el mono', 'el chimpancé'],
    correctAnswer: 'el mandril',
    hint: 'Baboon/Mandrill - colorful-faced primate, lives in troops, found in Africa',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_103',
    emoji: 'bald-eagle.png',
    question: '¿Qué ave es el símbolo de Estados Unidos?',
    translation: 'What bird is the symbol of the United States?',
    options: ['el águila calva', 'el halcón', 'el cóndor'],
    correctAnswer: 'el águila calva',
    hint: 'Bald eagle - national bird of USA, white head, powerful hunter',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_104',
    emoji: 'dragonfly.png',
    question: '¿Qué insecto tiene cuatro alas transparentes?',
    translation: 'What insect has four transparent wings?',
    options: ['la libélula', 'la mariposa', 'la polilla'],
    correctAnswer: 'la libélula',
    hint: 'Dragonfly - four transparent wings, excellent flyer, lives near water',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'plants_animals_105',
    emoji: 'fly.png',
    question: '¿Qué insecto molesto zumba en la casa?',
    translation: 'What annoying insect buzzes in the house?',
    options: ['la mosca', 'el mosquito', 'la avispa'],
    correctAnswer: 'la mosca',
    hint: 'Fly - common household pest, buzzes around, attracted to food',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_106',
    emoji: 'fruit-bat.png',
    question: '¿Qué murciélago come frutas?',
    translation: 'What bat eats fruits?',
    options: ['el murciélago frugívoro', 'el murciélago vampiro', 'el murciélago insectívoro'],
    correctAnswer: 'el murciélago frugívoro',
    hint: 'Fruit bat - eats fruits and nectar, also called flying fox, important pollinator',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_107',
    emoji: 'hippopotamus.png',
    question: '¿Qué animal grande pasa el día en el agua?',
    translation: 'What large animal spends the day in water?',
    options: ['el hipopótamo', 'el cocodrilo', 'el elefante'],
    correctAnswer: 'el hipopótamo',
    hint: 'Hippopotamus - large semi-aquatic mammal, spends days in water, very dangerous',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_108',
    emoji: 'iguana.png',
    question: '¿Qué lagarto grande es verde?',
    translation: 'What large lizard is green?',
    options: ['la iguana', 'el camaleón', 'la lagartija'],
    correctAnswer: 'la iguana',
    hint: 'Iguana - large green lizard, herbivore, has dewlap under chin',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_109',
    emoji: 'jellyfish.png',
    question: '¿Qué animal marino tiene tentáculos y pica?',
    translation: 'What marine animal has tentacles and stings?',
    options: ['la medusa', 'el pulpo', 'la anémona'],
    correctAnswer: 'la medusa',
    hint: 'Jellyfish - translucent marine animal, stinging tentacles, drifts with currents',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_110',
    emoji: 'kiwi-bird.png',
    question: '¿Qué ave pequeña no vuela y es de Nueva Zelanda?',
    translation: 'What small flightless bird is from New Zealand?',
    options: ['el kiwi', 'el pingüino', 'el avestruz'],
    correctAnswer: 'el kiwi',
    hint: 'Kiwi bird - flightless nocturnal bird from New Zealand, national symbol',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_111',
    emoji: 'largemouth-bass.png',
    question: '¿Qué pez de agua dulce es popular entre pescadores?',
    translation: 'What freshwater fish is popular among anglers?',
    options: ['la lobina negra', 'la trucha', 'el lucio'],
    correctAnswer: 'la lobina negra',
    hint: 'Largemouth bass - popular game fish, large mouth, lives in lakes and rivers',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_112',
    emoji: 'lioness.png',
    question: '¿Cómo se llama la leona que caza?',
    translation: 'What is the female lion that hunts called?',
    options: ['la leona', 'la tigresa', 'la pantera'],
    correctAnswer: 'la leona',
    hint: 'Lioness - female lion, does most of the hunting, no mane',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_113',
    emoji: 'manatee.png',
    question: '¿Qué mamífero marino grande es herbívoro?',
    translation: 'What large marine mammal is herbivorous?',
    options: ['el manatí', 'la foca', 'la morsa'],
    correctAnswer: 'el manatí',
    hint: 'Manatee - gentle marine mammal, eats seagrass, also called sea cow',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_114',
    emoji: 'mole.png',
    question: '¿Qué animal cava túneles bajo tierra?',
    translation: 'What animal digs tunnels underground?',
    options: ['el topo', 'el tejón', 'la ardilla'],
    correctAnswer: 'el topo',
    hint: 'Mole - small mammal, lives underground, digs tunnels, nearly blind',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_115',
    emoji: 'moth.png',
    question: '¿Qué insecto parece una mariposa pero vuela de noche?',
    translation: 'What insect looks like a butterfly but flies at night?',
    options: ['la polilla', 'la mariposa nocturna', 'la libélula'],
    correctAnswer: 'la polilla',
    hint: 'Moth - nocturnal insect, similar to butterfly, attracted to light',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_116',
    emoji: 'northern-pike.png',
    question: '¿Qué pez depredador tiene dientes afilados?',
    translation: 'What predatory fish has sharp teeth?',
    options: ['el lucio', 'la trucha', 'el salmón'],
    correctAnswer: 'el lucio',
    hint: 'Pike - aggressive freshwater predator, sharp teeth, ambush hunter',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_117',
    emoji: 'ostrich.png',
    question: '¿Qué ave es la más grande del mundo?',
    translation: 'What bird is the largest in the world?',
    options: ['el avestruz', 'el emú', 'el cóndor'],
    correctAnswer: 'el avestruz',
    hint: 'Ostrich - largest bird, cannot fly, fastest running bird, lays huge eggs',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_118',
    emoji: 'pelican.png',
    question: '¿Qué ave tiene una bolsa grande en el pico?',
    translation: 'What bird has a large pouch on its beak?',
    options: ['el pelícano', 'la gaviota', 'el cormorán'],
    correctAnswer: 'el pelícano',
    hint: 'Pelican - large water bird, expandable throat pouch for catching fish',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_119',
    emoji: 'penguin.png',
    question: '¿Qué ave no vuela pero nada muy bien?',
    translation: 'What bird doesn\'t fly but swims very well?',
    options: ['el pingüino', 'el pato', 'el cormorán'],
    correctAnswer: 'el pingüino',
    hint: 'Penguin - flightless bird, expert swimmer, lives in cold climates',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_120',
    emoji: 'scorpion.png',
    question: '¿Qué arácnido tiene cola venenosa?',
    translation: 'What arachnid has a venomous tail?',
    options: ['el escorpión', 'la araña', 'el ciempiés'],
    correctAnswer: 'el escorpión',
    hint: 'Scorpion - arachnid with pincers and venomous stinger on tail',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_121',
    emoji: 'siamese-cat.png',
    question: '¿Qué gato tiene puntas oscuras en las orejas y cola?',
    translation: 'What cat has dark points on ears and tail?',
    options: ['el gato siamés', 'el gato persa', 'el gato angora'],
    correctAnswer: 'el gato siamés',
    hint: 'Siamese cat - distinctive color points, blue eyes, vocal breed',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_122',
    emoji: 'snail.png',
    question: '¿Qué animal lleva su casa en espiral?',
    translation: 'What animal carries its spiral house?',
    options: ['el caracol', 'la tortuga', 'el cangrejo ermitaño'],
    correctAnswer: 'el caracol',
    hint: 'Snail - moves slowly, carries spiral shell, leaves slime trail',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_123',
    emoji: 'trout.png',
    question: '¿Qué pez de agua dulce vive en ríos fríos?',
    translation: 'What freshwater fish lives in cold rivers?',
    options: ['la trucha', 'el salmón', 'el lucio'],
    correctAnswer: 'la trucha',
    hint: 'Trout - freshwater fish, lives in cold clean water, popular for fishing',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_124',
    emoji: 'vulture.png',
    question: '¿Qué ave come animales muertos?',
    translation: 'What bird eats dead animals?',
    options: ['el buitre', 'el águila', 'el halcón'],
    correctAnswer: 'el buitre',
    hint: 'Vulture - scavenger bird, bald head, important for ecosystem cleanup',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_125',
    emoji: 'walleye.png',
    question: '¿Qué pez tiene ojos grandes y brillantes?',
    translation: 'What fish has large, shiny eyes?',
    options: ['el lucioperca', 'la trucha', 'el bass'],
    correctAnswer: 'el lucioperca',
    hint: 'Walleye - freshwater fish, reflective eyes, popular game fish',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_126',
    emoji: 'apple-tree.png',
    question: '¿Qué árbol produce manzanas?',
    translation: 'What tree produces apples?',
    options: ['el manzano', 'el peral', 'el cerezo'],
    correctAnswer: 'el manzano',
    hint: 'Apple tree - fruit tree, produces apples, blooms in spring',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_127',
    emoji: 'bamboo.png',
    question: '¿Qué planta alta comen los pandas?',
    translation: 'What tall plant do pandas eat?',
    options: ['el bambú', 'el eucalipto', 'la caña'],
    correctAnswer: 'el bambú',
    hint: 'Bamboo - fast-growing grass, favorite food of pandas, hollow stems',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_128',
    emoji: 'bellflower.png',
    question: '¿Qué flor tiene forma de campana?',
    translation: 'What flower has a bell shape?',
    options: ['la campanilla', 'la rosa', 'el tulipán'],
    correctAnswer: 'la campanilla',
    hint: 'Bellflower - bell-shaped flowers, often blue or purple, delicate',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_129',
    emoji: 'birch-tree.png',
    question: '¿Qué árbol tiene corteza blanca?',
    translation: 'What tree has white bark?',
    options: ['el abedul', 'el pino', 'el roble'],
    correctAnswer: 'el abedul',
    hint: 'Birch tree - distinctive white bark that peels, grows in cold climates',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_130',
    emoji: 'cactus.png',
    question: '¿Qué planta con espinas vive en el desierto?',
    translation: 'What spiny plant lives in the desert?',
    options: ['el cactus', 'el agave', 'la yuca'],
    correctAnswer: 'el cactus',
    hint: 'Cactus - succulent plant, stores water, has spines instead of leaves',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_131',
    emoji: 'cattail.png',
    question: '¿Qué planta parece un cigarro y crece en pantanos?',
    translation: 'What plant looks like a cigar and grows in swamps?',
    options: ['la espadaña', 'el junco', 'el carrizo'],
    correctAnswer: 'la espadaña',
    hint: 'Cattail - wetland plant, brown cylindrical flower head, edible parts',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_132',
    emoji: 'cherry-blossom-tree.png',
    question: '¿Qué árbol tiene flores rosadas hermosas?',
    translation: 'What tree has beautiful pink flowers?',
    options: ['el cerezo', 'el manzano', 'el duraznero'],
    correctAnswer: 'el cerezo',
    hint: 'Cherry blossom tree - famous in Japan, pink spring flowers, produces cherries',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_133',
    emoji: 'daffodil.png',
    question: '¿Qué flor amarilla anuncia la primavera?',
    translation: 'What yellow flower announces spring?',
    options: ['el narciso', 'el girasol', 'el tulipán'],
    correctAnswer: 'el narciso',
    hint: 'Daffodil - bright yellow spring flower, trumpet-shaped center, symbol of renewal',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_134',
    emoji: 'fern.png',
    question: '¿Qué planta verde tiene hojas en forma de pluma?',
    translation: 'What green plant has feather-shaped leaves?',
    options: ['el helecho', 'la palmera', 'el bambú'],
    correctAnswer: 'el helecho',
    hint: 'Fern - ancient plant, feathery fronds, reproduces by spores, grows in shade',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_135',
    emoji: 'lavender.png',
    question: '¿Qué planta morada huele muy bien?',
    translation: 'What purple plant smells very good?',
    options: ['la lavanda', 'el romero', 'la menta'],
    correctAnswer: 'la lavanda',
    hint: 'Lavender - purple fragrant flowers, used in perfumes and aromatherapy',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_136',
    emoji: 'lemon-tree.png',
    question: '¿Qué árbol produce limones?',
    translation: 'What tree produces lemons?',
    options: ['el limonero', 'el naranjo', 'el limero'],
    correctAnswer: 'el limonero',
    hint: 'Lemon tree - citrus tree, produces yellow sour fruit, fragrant flowers',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_137',
    emoji: 'lily.png',
    question: '¿Qué flor elegante crece en el agua?',
    translation: 'What elegant flower grows in water?',
    options: ['el lirio', 'la rosa', 'el tulipán'],
    correctAnswer: 'el lirio',
    hint: 'Lily - elegant flower, often white, sweet fragrance, symbol of purity',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_138',
    emoji: 'oak-tree.png',
    question: '¿Qué árbol fuerte produce bellotas?',
    translation: 'What strong tree produces acorns?',
    options: ['el roble', 'el pino', 'el abedul'],
    correctAnswer: 'el roble',
    hint: 'Oak tree - strong hardwood tree, produces acorns, symbol of strength',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_139',
    emoji: 'palm-tree.png',
    question: '¿Qué árbol tropical tiene cocos?',
    translation: 'What tropical tree has coconuts?',
    options: ['la palmera', 'el plátano', 'el mango'],
    correctAnswer: 'la palmera',
    hint: 'Palm tree - tropical tree, produces coconuts, tall trunk with fronds on top',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_140',
    emoji: 'pine-forest.png',
    question: '¿Qué bosque tiene árboles con agujas?',
    translation: 'What forest has trees with needles?',
    options: ['el bosque de pinos', 'el bosque tropical', 'el bosque de robles'],
    correctAnswer: 'el bosque de pinos',
    hint: 'Pine forest - coniferous forest, evergreen trees with needles and cones',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'plants_animals_141',
    emoji: 'poppy-flower.png',
    question: '¿Qué flor roja es símbolo de recuerdo?',
    translation: 'What red flower is a symbol of remembrance?',
    options: ['la amapola', 'la rosa', 'el clavel'],
    correctAnswer: 'la amapola',
    hint: 'Poppy - red flower, symbol of remembrance, delicate petals',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_142',
    emoji: 'rhododendron.png',
    question: '¿Qué arbusto tiene flores grandes y coloridas?',
    translation: 'What shrub has large colorful flowers?',
    options: ['el rododendro', 'la azalea', 'la hortensia'],
    correctAnswer: 'el rododendro',
    hint: 'Rhododendron - large flowering shrub, clusters of showy flowers, evergreen',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_143',
    emoji: 'venus-flytrap.png',
    question: '¿Qué planta carnívora atrapa insectos?',
    translation: 'What carnivorous plant traps insects?',
    options: ['la venus atrapamoscas', 'la planta jarra', 'la drosera'],
    correctAnswer: 'la venus atrapamoscas',
    hint: 'Venus flytrap - carnivorous plant, snap-trap leaves, catches insects',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_144',
    emoji: 'violet.png',
    question: '¿Qué flor pequeña es morada o azul?',
    translation: 'What small flower is purple or blue?',
    options: ['la violeta', 'la lila', 'la lavanda'],
    correctAnswer: 'la violeta',
    hint: 'Violet - small delicate flower, purple or blue, heart-shaped leaves',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_145',
    emoji: 'water-lilly.png',
    question: '¿Qué flor flota en el agua?',
    translation: 'What flower floats on water?',
    options: ['el nenúfar', 'el lirio', 'el loto'],
    correctAnswer: 'el nenúfar',
    hint: 'Water lily - aquatic plant, floating leaves and flowers, grows in ponds',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_146',
    emoji: 'white-lily.png',
    question: '¿Qué lirio blanco simboliza pureza?',
    translation: 'What white lily symbolizes purity?',
    options: ['el lirio blanco', 'la rosa blanca', 'la azucena'],
    correctAnswer: 'el lirio blanco',
    hint: 'White lily - pure white flower, sweet fragrance, symbol of innocence',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_147',
    emoji: 'wildflowers.png',
    question: '¿Qué flores crecen naturalmente en los campos?',
    translation: 'What flowers grow naturally in fields?',
    options: ['las flores silvestres', 'las rosas', 'los tulipanes'],
    correctAnswer: 'las flores silvestres',
    hint: 'Wildflowers - naturally growing flowers, colorful meadows, diverse species',
    points: 5,
    category: 'plants_animals',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_148',
    emoji: 'willow-tree.png',
    question: '¿Qué árbol tiene ramas que cuelgan?',
    translation: 'What tree has hanging branches?',
    options: ['el sauce', 'el álamo', 'el fresno'],
    correctAnswer: 'el sauce',
    hint: 'Willow tree - graceful tree with drooping branches, grows near water',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'plants_animals_149',
    emoji: 'ant-colony.png',
    question: '¿Cómo se llama el grupo de hormigas que trabajan juntas?',
    translation: 'What is the group of ants that work together called?',
    options: ['la colonia de hormigas', 'el enjambre', 'la manada'],
    correctAnswer: 'la colonia de hormigas',
    hint: 'Ant colony - organized community of ants, with queen, workers, and soldiers',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'plants_animals_150',
    emoji: 'wasp-nest.png',
    question: '¿Dónde viven las avispas?',
    translation: 'Where do wasps live?',
    options: ['el nido de avispas', 'la colmena', 'el hormiguero'],
    correctAnswer: 'el nido de avispas',
    hint: 'Wasp nest - paper-like structure made by wasps, can be aggressive defenders',
    points: 10,
    category: 'plants_animals',
    difficulty: 'medium',
    emotion: 'pleased',
  },
];
