/**
 * Animals Category Questions
 * Category: animals
 */

export const plantsAnimalsQuestions = [
{
    id: 'animals_001',
    emoji: '🐕',
    question: '¿Cuál es un animal doméstico común?',
    translation: 'What is a common domestic animal?',
    options: ['el perro', 'el lobo', 'el zorro'],
    correctAnswer: 'el perro',
    hint: 'Dog - man\'s best friend, "canis" in Latin',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_002',
    emoji: '🐈',
    question: '¿Qué animal dice "miau"?',
    translation: 'What animal says \'meow\'?',
    options: ['el gato', 'el ratón', 'el loro'],
    correctAnswer: 'el gato',
    hint: 'Cat - independent pet, "felino" in scientific terms',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_003',
    emoji: '🐭',
    question: '¿Qué animal pequeño vive en las casas?',
    translation: 'What small animal lives in houses?',
    options: ['el ratón', 'la hormiga', 'la cucaracha'],
    correctAnswer: 'el ratón',
    hint: 'Mouse - small rodent, "ratoncillo" is diminutive',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_004',
    emoji: '🐀',
    question: '¿Qué roedor es más grande que el ratón?',
    translation: 'What rodent is bigger than a mouse?',
    options: ['la rata', 'el hamster', 'el conejillo de indias'],
    correctAnswer: 'la rata',
    hint: 'Rat - larger rodent, intelligent, often kept as pets',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_005',
    emoji: '🐹',
    question: '¿Qué roedor pequeño tiene bolsas en las mejillas?',
    translation: 'What small rodent has pouches in its cheeks?',
    options: ['el hamster', 'el ratón', 'el gerbil'],
    correctAnswer: 'el hamster',
    hint: 'Hamster - small rodent, cheek pouches, stores food, popular pet',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_006',
    emoji: '🐿️',
    question: '¿Qué animal come frutos secos en el árbol?',
    translation: 'What animal has orange stripes?',
    options: ['la ardilla', 'el pájaro', 'la catarita'],
    correctAnswer: 'la ardilla',
    hint: 'Squirrel - bushy tail, climbs trees, collects nuts',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_007',
    emoji: '🐇',
    question: '¿Qué animal tiene orejas largas?',
    translation: 'What animal has a trunk?',
    options: ['el conejo', 'el venado', 'la cabra'],
    correctAnswer: 'el conejo',
    hint: 'Rabbit - hops around, "conej�🐇illo de indias" is guinea pig',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_005',
    emoji: '🦁',
    question: '¿Cuál es el rey de la selva?',
    translation: 'What small rodent has pouches in its cheeks?',
    options: ['el león', 'el tigre', 'el elefante'],
    correctAnswer: 'el león',
    hint: 'Lion - has a mane, roars loudly, symbol of courage',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_006',
    emoji: '🐯',
    question: '¿Qué animal tiene rayas naranjas?',
    translation: 'What animal has orange stripes?',
    options: ['el tigre', 'el leopardo', 'el gato montés'],
    correctAnswer: 'el tigre',
    hint: 'Tiger - striped big cat, endangered species',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_007',
    emoji: '🐘',
    question: '¿Qué animal tiene una trompa?',
    translation: 'What animal has a trunk?',
    options: ['el elefante', 'la jirafa', 'el cocodrilo'],
    correctAnswer: 'el elefante',
    hint: 'Elephant - largest land animal, has tusks',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_008',
    emoji: '🦒',
    question: '¿Qué animal tiene el cuello más largo?',
    translation: 'What animal has the longest neck?',
    options: ['la jirafa', 'el avestruz', 'la llama'],
    correctAnswer: 'la jirafa',
    hint: 'Giraffe - tallest land animal, African herbivore',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_009',
    emoji: '🦓',
    question: '¿Qué animal tiene rayas blancas y negras?',
    translation: 'What animal has white and black stripes?',
    options: ['la cebra', 'el caballo', 'el burro'],
    correctAnswer: 'la cebra',
    hint: 'Zebra - related to horses, African animal, striped',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_010',
    emoji: '🦏',
    question: '¿Qué animal tiene un cuerno en la nariz?',
    translation: 'What animal has a horn on its nose?',
    options: ['el rinoceronte', 'el alce', 'el búfalo'],
    correctAnswer: 'el rinoceronte',
    hint: 'Rhinoceros - large African animal, endangered',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_011',
    emoji: '🐻',
    question: '¿Qué animal grande vive en el bosque?',
    translation: 'What big animal lives in the forest?',
    options: ['el oso', 'el ciervo', 'el puma'],
    correctAnswer: 'el oso',
    hint: 'Bear - large mammal, hibernates in winter',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_012',
    emoji: '🦊',
    question: '¿Qué animal es parecido al perro pero salvaje?',
    translation: 'What animal is similar to a dog but wild?',
    options: ['el zorro', 'el lobo', 'el chacal'],
    correctAnswer: 'el zorro',
    hint: 'Fox - cunning animal, reddish fur, similar to dog',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_013',
    emoji: '🐺',
    question: '¿Qué animal aúlla a la luna?',
    translation: 'What animal howls at the moon?',
    options: ['el lobo', 'el perro', 'el coyote'],
    correctAnswer: 'el lobo',
    hint: 'Wolf - wild canine, hunts in packs, endangered in many places',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_014',
    emoji: '🐄',
    question: '¿Qué animal produce leche?',
    translation: 'What animal produces milk?',
    options: ['la vaca', 'la oveja', 'la cabra'],
    correctAnswer: 'la vaca',
    hint: 'Cow - dairy animal, bovine, "ternera" for calf',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_015',
    emoji: '🐷',
    question: '¿Qué animal tiene cola rizada?',
    translation: 'What animal has a curly tail?',
    options: ['el cerdo', 'el cordero', 'el caballo'],
    correctAnswer: 'el cerdo',
    hint: 'Pig - farm animal, curly tail, "cochinillo" for piglet',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_016',
    emoji: '🐑',
    question: '¿Qué animal produce lana?',
    translation: 'What animal produces wool?',
    options: ['la oveja', 'la cabra', 'el cerdo'],
    correctAnswer: 'la oveja',
    hint: 'Sheep - woolly farm animal, "carnero" for ram',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_017',
    emoji: '🐐',
    question: '¿Qué animal trepa bien en las montañas?',
    translation: 'What animal climbs well in the mountains?',
    options: ['la cabra', 'el cordero', 'la oveja'],
    correctAnswer: 'la cabra',
    hint: 'Goat - climbs steep terrain, agile, produces milk',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_018',
    emoji: '🐴',
    question: '¿Qué animal montas para viajar?',
    translation: 'What animal do you ride to travel?',
    options: ['el caballo', 'el burro', 'el camello'],
    correctAnswer: 'el caballo',
    hint: 'Horse - large hoofed animal, rides quickly, "yegua" for mare',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_019',
    emoji: '🦘',
    question: '¿Qué animal salta y viene de Australia?',
    translation: 'What animal jumps and comes from Australia?',
    options: ['el canguro', 'el koala', 'el wombat'],
    correctAnswer: 'el canguro',
    hint: 'Kangaroo - jumps on hind legs, Australian, carries baby in pouch',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_020',
    emoji: '🐨',
    question: '¿Qué animal come eucalipto?',
    translation: 'What animal eats eucalyptus?',
    options: ['el koala', 'el canguro', 'el oso panda'],
    correctAnswer: 'el koala',
    hint: 'Koala - looks like bear, eats eucalyptus leaves, Australian marsupial',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_021',
    emoji: '🐼',
    question: '¿Qué animal gigante es blanco y negro?',
    translation: 'What giant animal is black and white?',
    options: ['el oso panda', 'el oso polar', 'el tejón'],
    correctAnswer: 'el oso panda',
    hint: 'Panda - endangered, eats bamboo, from China',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_022',
    emoji: '🐍',
    question: '¿Qué animal doméstico es una mascotas en casas?',
    translation: 'What domestic animal is a pet in houses?',
    options: ['la serpiente', 'el cocodrilo', 'el iguana'],
    correctAnswer: 'la serpiente',
    hint: 'Snake - can be kept as exotic pet, some docile species',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_023',
    emoji: '🦁',
    question: '¿Cuál es el felino salvaje más grande de América?',
    translation: 'What is the largest wild cat in America?',
    options: ['el puma', 'el jaguár', 'el ocelote'],
    correctAnswer: 'el jaguár',
    hint: 'Jaguar - spotted big cat, largest cat in Americas, endangered',
    points: 10,
    category: 'fauna_animals',
    difficulty: 'medium',
  },
  {
    id: 'animals_024',
    emoji: '🐒',
    question: '¿Qué animal es parecido a los humanos?',
    translation: 'What animal is similar to humans?',
    options: ['el mono', 'el simio', 'el chimpancé'],
    correctAnswer: 'el mono',
    hint: 'Monkey - primate with tail, swings in trees, intelligent',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_025',
    emoji: '🦍',
    question: '¿Qué primate grande tiene brazos muy largos?',
    translation: 'What big primate has very long arms?',
    options: ['el gorila', 'el orangután', 'el chimpancé'],
    correctAnswer: 'el gorila',
    hint: 'Gorilla - largest primate, endangered, knuckle-walks, very strong',
    points: 10,
    category: 'fauna_animals',
    difficulty: 'medium',
  },
  {
    id: 'animals_026',
    emoji: '🦅',
    question: '¿Qué pájaro grande vuela muy alto?',
    translation: 'What big bird flies very high?',
    options: ['el águila', 'el halcón', 'el cóndor'],
    correctAnswer: 'el águila',
    hint: 'Eagle - large bird of prey, symbol of strength and freedom',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_027',
    emoji: '🦉',
    question: '¿Qué pájaro ve bien de noche?',
    translation: 'What bird sees well at night?',
    options: ['el búho', 'la lechuza', 'el cuervo'],
    correctAnswer: 'el búho',
    hint: 'Owl - nocturnal bird of prey, large eyes, rotates head',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_028',
    emoji: '🦜',
    question: '¿Qué pájaro colorido puede hablar?',
    translation: 'What colorful bird can talk?',
    options: ['el loro', 'el papagayo', 'el periquito'],
    correctAnswer: 'el loro',
    hint: 'Parrot - intelligent, colorful, mimics sounds and words',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_029',
    emoji: '🦆',
    question: '¿Qué pájaro acuático tiene pico plano?',
    translation: 'What water bird has a flat beak?',
    options: ['el pato', 'la gaviota', 'el cisne'],
    correctAnswer: 'el pato',
    hint: 'Duck - waterfowl, quacks, waddles on land',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_030',
    emoji: '🦢',
    question: '¿Qué pájaro blanco es elegante?',
    translation: 'What white bird is elegant?',
    options: ['el cisne', 'el pato', 'la gaviota'],
    correctAnswer: 'el cisne',
    hint: 'Swan - large water bird, elegant, white or black species',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_031',
    emoji: '🦚',
    question: '¿Qué pájaro tiene plumas de muchos colores?',
    translation: 'What bird has feathers of many colors?',
    options: ['el pavo real', 'el loro', 'el faisán'],
    correctAnswer: 'el pavo real',
    hint: 'Peacock - displays colorful feathers, Indian bird, very beautiful',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_032',
    emoji: '🐢',
    question: '¿Qué animal tiene caparazón?',
    translation: 'What animal has a shell?',
    options: ['la tortuga', 'el cangrejo', 'el caracol'],
    correctAnswer: 'la tortuga',
    hint: 'Turtle - reptile with hard shell, can live long time',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_033',
    emoji: '🦎',
    question: '¿Qué animal pequeño tiene cola larga?',
    translation: 'What small animal has a long tail?',
    options: ['la lagartija', 'el camaleón', 'la iguana'],
    correctAnswer: 'la lagartija',
    hint: 'Lizard - small reptile, can detach tail, sunbathes',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_034',
    emoji: '🐊',
    question: '¿Qué animal verde vive en el río?',
    translation: 'What green animal lives in the river?',
    options: ['el cocodrilo', 'la serpiente', 'la tortuga'],
    correctAnswer: 'el cocodrilo',
    hint: 'Crocodile - large reptile, sharp teeth, ancient predator',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_035',
    emoji: '🐙',
    question: '¿Qué animal marino tiene ocho brazos?',
    translation: 'What sea animal has eight arms?',
    options: ['el pulpo', 'la medusa', 'el calamar'],
    correctAnswer: 'el pulpo',
    hint: 'Octopus - eight tentacles, intelligent, changes color',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_036',
    emoji: '🦑',
    question: '¿Qué animal marino parece el pulpo?',
    translation: 'What sea animal looks like an octopus?',
    options: ['el calamar', 'la medusa', 'el caracol'],
    correctAnswer: 'el calamar',
    hint: 'Squid - similar to octopus, ten tentacles, emits ink',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_037',
    emoji: '🐠',
    question: '¿Qué animal vive en el agua?',
    translation: 'What animal lives in water?',
    options: ['el pez', 'el pescado', 'la aleta'],
    correctAnswer: 'el pez',
    hint: 'Fish - aquatic animal, has gills and fins, "pescado" means cooked fish',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_038',
    emoji: '🦈',
    question: '¿Qué pez es peligroso?',
    translation: 'What fish is dangerous?',
    options: ['el tiburón', 'la sardina', 'la trucha'],
    correctAnswer: 'el tiburón',
    hint: 'Shark - dangerous predator, sharp teeth, appears in all oceans',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_039',
    emoji: '🐋',
    question: '¿Qué animal marino es el más grande?',
    translation: 'What sea animal is the biggest?',
    options: ['la ballena', 'el tiburón', 'el delfín'],
    correctAnswer: 'la ballena',
    hint: 'Whale - largest animal on Earth, marine mammal, endangered species',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_040',
    emoji: '🐬',
    question: '¿Qué animal marino es inteligente y amigable?',
    translation: 'What sea animal is intelligent and friendly?',
    options: ['el delfín', 'la ballena', 'el tiburón'],
    correctAnswer: 'el delfín',
    hint: 'Dolphin - intelligent marine mammal, friendly to humans, playful',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_041',
    emoji: '🦭',
    question: '¿Qué animal tiene bigotes y vive en el hielo?',
    translation: 'What animal has whiskers and lives in ice?',
    options: ['la foca', 'la morsa', 'el oso polar'],
    correctAnswer: 'la foca',
    hint: 'Seal - marine mammal, whiskers, lives in cold waters',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_042',
    emoji: '🦀',
    question: '¿Qué animal tiene diez patas?',
    translation: 'What animal has ten legs?',
    options: ['el cangrejo', 'el camarón', 'la langosta'],
    correctAnswer: 'el cangrejo',
    hint: 'Crab - crustacean with claws, walks sideways, edible',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_043',
    emoji: '🦞',
    question: '¿Qué animal parece un cangrejo grande?',
    translation: 'What animal looks like a big crab?',
    options: ['la langosta', 'el camarón', 'la ostra'],
    correctAnswer: 'la langosta',
    hint: 'Lobster - large crustacean, delicacy, expensive',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_044',
    emoji: '🦗',
    question: '¿Qué insecto hace ruido por la noche?',
    translation: 'What insect makes noise at night?',
    options: ['el grillo', 'la cigarra', 'el saltamontes'],
    correctAnswer: 'el grillo',
    hint: 'Cricket - insect, chirps at night, jumps, used in sports',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_045',
    emoji: '🦋',
    question: '¿Qué insecto tiene alas coloridas?',
    translation: 'What insect has colorful wings?',
    options: ['la mariposa', 'la polilla', 'la libélula'],
    correctAnswer: 'la mariposa',
    hint: 'Butterfly - colorful insect, goes through metamorphosis',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_046',
    emoji: '🐝',
    question: '¿Qué insecto produce miel?',
    translation: 'What insect produces honey?',
    options: ['la abeja', 'la avispa', 'el abejorro'],
    correctAnswer: 'la abeja',
    hint: 'Bee - produces honey, pollinates flowers, lives in colonies',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_047',
    emoji: '🐜',
    question: '¿Qué insecto pequeño trabaja en equipo?',
    translation: 'What small insect works as a team?',
    options: ['la hormiga', 'la termita', 'el escarabajo'],
    correctAnswer: 'la hormiga',
    hint: 'Ant - social insect, works in colonies, carries leaves',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_048',
    emoji: '🦗',
    question: '¿Qué insecto salta alto?',
    translation: 'What insect jumps high?',
    options: ['el saltamontes', 'la cucaracha', 'el escarabajo'],
    correctAnswer: 'el saltamontes',
    hint: 'Grasshopper - jumps far, green color, eats plants',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_049',
    emoji: '🐛',
    question: '¿Cuál es la larva de la mariposa?',
    translation: 'What is the larva of a butterfly?',
    options: ['la oruga', 'la pupa', 'el gusano'],
    correctAnswer: 'la oruga',
    hint: 'Caterpillar - larva stage of butterfly, eats leaves, colorful',
    points: 10,
    category: 'fauna_animals',
    difficulty: 'medium',
  },
  {
    id: 'animals_050',
    emoji: '🦇',
    question: '¿Qué animal vuela de noche?',
    translation: 'What animal flies at night?',
    options: ['el murciélago', 'el búho', 'la lechuza'],
    correctAnswer: 'el murciélago',
    hint: 'Bat - only mammal that flies, uses echolocation, nocturnal',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_058',
    emoji: '🦢',
    question: '¿Qué pájaro blanco es elegante?',
    translation: 'What white bird is elegant?',
    options: ['el cisne', 'el pato', 'la gaviota'],
    correctAnswer: 'el cisne',
    hint: 'Swan - large water bird, elegant, white or black species',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_059',
    emoji: '🦚',
    question: '¿Qué pájaro tiene plumas de muchos colores?',
    translation: 'What bird has feathers of many colors?',
    options: ['el pavo real', 'el loro', 'el faisán'],
    correctAnswer: 'el pavo real',
    hint: 'Peacock - displays colorful feathers, Indian bird, very beautiful',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_060',
    emoji: '🐢',
    question: '¿Qué animal tiene caparazón?',
    translation: 'What animal has a shell?',
    options: ['la tortuga', 'el cangrejo', 'el caracol'],
    correctAnswer: 'la tortuga',
    hint: 'Turtle - reptile with hard shell, can live long time',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_061',
    emoji: '🦃',
    question: '¿Qué ave grande se come tradicionalmente en Acción de Gracias?',
    translation: 'What large bird is traditionally eaten at Thanksgiving?',
    options: ['el pavo', 'el pollo', 'el ganso'],
    correctAnswer: 'el pavo',
    hint: 'Turkey - large bird traditionally eaten at Thanksgiving and Christmas',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_062',
    emoji: '🐂',
    question: '¿Cómo se llama la vaca macho?',
    translation: 'What is a male cow called?',
    options: ['el toro', 'el buey', 'el carnero'],
    correctAnswer: 'el toro',
    hint: 'Bull - male cow, strong and powerful animal',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_063',
    emoji: '🐓',
    question: '¿Cómo se llama el pollo macho que canta por la mañana?',
    translation: 'What is the male chicken that crows in the morning called?',
    options: ['el gallo', 'el pollo', 'el pavo'],
    correctAnswer: 'el gallo',
    hint: 'Rooster - male chicken, crows at dawn, has colorful feathers',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_064',
    emoji: '🐔',
    question: '¿Qué ave de granja pone huevos?',
    translation: 'What farm bird lays eggs?',
    options: ['la gallina', 'el gallo', 'el pato'],
    correctAnswer: 'la gallina',
    hint: 'Chicken/Hen - farm bird, lays eggs, female of rooster',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_065',
    emoji: '🐣',
    question: '¿Cómo se llama el bebé que sale del huevo?',
    translation: 'What is the baby that comes out of the egg called?',
    options: ['el pollito', 'el patito', 'el pajarito'],
    correctAnswer: 'el pollito',
    hint: 'Chick - baby bird that hatches from egg, young chicken',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_066',
    emoji: '🦨',
    question: '¿Qué animal tiene rayas blancas y negras y produce mal olor?',
    translation: 'What animal has black and white stripes and produces a bad smell?',
    options: ['el zorrillo', 'la mofeta', 'el tejón'],
    correctAnswer: 'el zorrillo',
    hint: 'Skunk - black and white striped animal, sprays bad smell for defense',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_067',
    emoji: '🐧',
    question: '¿Qué ave nada pero no vuela?',
    translation: 'What bird swims but doesn\'t fly?',
    options: ['el pingüino', 'el pato', 'el cisne'],
    correctAnswer: 'el pingüino',
    hint: 'Penguin - flightless bird, swims in cold waters, lives in Antarctica',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_068',
    emoji: '🦦',
    question: '¿Qué animal juguetón nada en los ríos?',
    translation: 'What playful animal swims in rivers?',
    options: ['la nutria', 'el castor', 'la foca'],
    correctAnswer: 'la nutria',
    hint: 'Otter - playful aquatic mammal, swims in rivers and oceans, holds hands while sleeping',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_069',
    emoji: '🐦‍⬛',
    question: '¿Qué pájaro pequeño es común en las ciudades?',
    translation: 'What small bird is common in cities?',
    options: ['el gorrión', 'el canario', 'el jilguero'],
    correctAnswer: 'el gorrión',
    hint: 'Sparrow - small brown bird, common in cities and towns, chirps frequently',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_070',
    emoji: '🪿',
    question: '¿Qué ave tiene cuello largo y hace "honk"?',
    translation: 'What bird has a long neck and goes \'honk\'?',
    options: ['el ganso', 'el pato', 'el cisne'],
    correctAnswer: 'el ganso',
    hint: 'Goose - waterfowl with long neck, honks loudly, can be aggressive',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_071',
    emoji: '🪰',
    question: '¿Qué insecto molesto vuela en la casa?',
    translation: 'What annoying insect flies around the house?',
    options: ['la mosca', 'el mosquito', 'la avispa'],
    correctAnswer: 'la mosca',
    hint: 'Fly - common household insect, buzzes around, attracted to food',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_072',
    emoji: '🐸',
    question: '¿Qué animal anfibio salta y dice "croac"?',
    translation: 'What amphibian animal jumps and says \'croak\'?',
    options: ['la rana', 'el sapo', 'la salamandra'],
    correctAnswer: 'la rana',
    hint: 'Frog - amphibian that jumps, lives near water, croaks loudly',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_073',
    emoji: '🪲',
    question: '¿Qué insecto tiene un caparazón duro?',
    translation: 'What insect has a hard shell?',
    options: ['el escarabajo', 'la mariquita', 'la cucaracha'],
    correctAnswer: 'el escarabajo',
    hint: 'Beetle - insect with hard shell, many species, some can fly',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_074',
    emoji: '🦖',
    question: '¿Qué animal prehistórico gigante está extinto?',
    translation: 'What giant prehistoric animal is extinct?',
    options: ['el dinosaurio', 'el mamut', 'el tigre dientes de sable'],
    correctAnswer: 'el dinosaurio',
    hint: 'Dinosaur - prehistoric reptile, extinct millions of years ago, many species',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_075',
    emoji: '🪸',
    question: '¿Qué organismo marino forma arrecifes?',
    translation: 'What marine organism forms reefs?',
    options: ['el coral', 'la esponja', 'la anémona'],
    correctAnswer: 'el coral',
    hint: 'Coral - marine organism, forms reefs, provides habitat for fish',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_076',
    emoji: '🦧',
    question: '¿Qué primate tiene pelo naranja y vive en los árboles?',
    translation: 'What primate has orange fur and lives in trees?',
    options: ['el orangután', 'el mono', 'el gorila'],
    correctAnswer: 'el orangután',
    hint: 'Orangutan - great ape with orange fur, lives in trees, found in Southeast Asia',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_077',
    emoji: '🫎',
    question: '¿Qué animal grande tiene astas y vive en el bosque frío?',
    translation: 'What large animal has antlers and lives in cold forests?',
    options: ['el alce', 'el ciervo', 'el reno'],
    correctAnswer: 'el alce',
    hint: 'Moose - largest deer species, has big antlers, lives in cold forests',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_078',
    emoji: '🦌',
    question: '¿Qué animal tiene cuernos y vive en el bosque?',
    translation: 'What animal has antlers and lives in the forest?',
    options: ['el ciervo', 'el alce', 'la cabra'],
    correctAnswer: 'el ciervo',
    hint: 'Deer - graceful animal with antlers, lives in forests and meadows',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_079',
    emoji: '🦮',
    question: '¿Qué perro ayuda a las personas con discapacidades?',
    translation: 'What dog helps people with disabilities?',
    options: ['el perro guía', 'el perro policía', 'el perro pastor'],
    correctAnswer: 'el perro guía',
    hint: 'Guide dog - service dog trained to help people with disabilities, especially the blind',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_080',
    emoji: '🦩',
    question: '¿Qué ave rosada tiene patas largas?',
    translation: 'What pink bird has long legs?',
    options: ['el flamenco', 'la garza', 'el cisne'],
    correctAnswer: 'el flamenco',
    hint: 'Flamingo - pink bird with long legs, stands on one leg, lives near water',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_081',
    emoji: '🦫',
    question: '¿Qué animal construye presas en los ríos?',
    translation: 'What animal builds dams in rivers?',
    options: ['el castor', 'la nutria', 'el tejón'],
    correctAnswer: 'el castor',
    hint: 'Beaver - builds dams in rivers, has flat tail, strong teeth, gnaws trees',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_082',
    emoji: '🪺',
    question: '¿Dónde ponen los pájaros sus huevos?',
    translation: 'Where do birds lay their eggs?',
    options: ['el nido', 'la cueva', 'el árbol'],
    correctAnswer: 'el nido',
    hint: 'Nest - birds build it with twigs and grass, used for laying eggs and raising chicks',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_083',
    emoji: '🐻‍❄️',
    question: '¿Qué oso blanco vive en el Ártico?',
    translation: 'What white bear lives in the Arctic?',
    options: ['el oso polar', 'el oso pardo', 'el oso negro'],
    correctAnswer: 'el oso polar',
    hint: 'Polar bear - white bear, lives in Arctic, excellent swimmer, hunts seals',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_084',
    emoji: '🐆',
    question: '¿Qué felino manchado corre muy rápido?',
    translation: 'What spotted feline runs very fast?',
    options: ['el guepardo', 'el leopardo', 'el tigre'],
    correctAnswer: 'el guepardo',
    hint: 'Cheetah - fastest land animal, spotted coat, slender build',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_085',
    emoji: '🦓',
    question: '¿Qué animal parece un caballo con rayas?',
    translation: 'What animal looks like a horse with stripes?',
    options: ['la cebra', 'el burro', 'la mula'],
    correctAnswer: 'la cebra',
    hint: 'Zebra - black and white stripes, lives in Africa, related to horses',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_086',
    emoji: '🦒',
    question: '¿Qué animal tiene el cuello más largo del mundo?',
    translation: 'What animal has the longest neck in the world?',
    options: ['la jirafa', 'el avestruz', 'el camello'],
    correctAnswer: 'la jirafa',
    hint: 'Giraffe - tallest animal, long neck to reach high leaves, lives in Africa',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_087',
    emoji: '🦏',
    question: '¿Qué animal grande tiene un cuerno en la nariz?',
    translation: 'What large animal has a horn on its nose?',
    options: ['el rinoceronte', 'el hipopótamo', 'el búfalo'],
    correctAnswer: 'el rinoceronte',
    hint: 'Rhinoceros - large animal with horn on nose, thick skin, herbivore',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_088',
    emoji: '🦛',
    question: '¿Qué animal grande vive en ríos africanos?',
    translation: 'What large animal lives in African rivers?',
    options: ['el hipopótamo', 'el cocodrilo', 'el rinoceronte'],
    correctAnswer: 'el hipopótamo',
    hint: 'Hippopotamus - large river animal, semi-aquatic, powerful jaws, lives in Africa',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_089',
    emoji: '🐪',
    question: '¿Qué animal tiene una joroba y vive en el desierto?',
    translation: 'What animal has a hump and lives in the desert?',
    options: ['el camello', 'el dromedario', 'la llama'],
    correctAnswer: 'el camello',
    hint: 'Camel - has humps for storing fat, survives in desert, can go without water for days',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_090',
    emoji: '🐫',
    question: '¿Qué animal tiene dos jorobas?',
    translation: 'What animal has two humps?',
    options: ['el camello bactriano', 'el dromedario', 'la llama'],
    correctAnswer: 'el camello bactriano',
    hint: 'Bactrian camel - has two humps, from Central Asia, adapted to cold deserts',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'medium',
  },
  {
    id: 'animals_091',
    emoji: '🦙',
    question: '¿Qué animal andino se parece al camello?',
    translation: 'What Andean animal looks like a camel?',
    options: ['la llama', 'la alpaca', 'la vicuña'],
    correctAnswer: 'la llama',
    hint: 'Llama - South American camelid, used as pack animal, lives in Andes mountains',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_092',
    emoji: '🦘',
    question: '¿Qué animal salta y tiene una bolsa?',
    translation: 'What animal hops and has a pouch?',
    options: ['el canguro', 'el koala', 'el wombat'],
    correctAnswer: 'el canguro',
    hint: 'Kangaroo - hops on powerful hind legs, has pouch for babies, from Australia',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_093',
    emoji: '🐨',
    question: '¿Qué animal duerme mucho en los árboles?',
    translation: 'What animal sleeps a lot in trees?',
    options: ['el koala', 'el perezoso', 'el mapache'],
    correctAnswer: 'el koala',
    hint: 'Koala - sleeps up to 20 hours, eats eucalyptus, lives in Australia',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_094',
    emoji: '🦥',
    question: '¿Qué animal se mueve muy lentamente?',
    translation: 'What animal moves very slowly?',
    options: ['el perezoso', 'el koala', 'la tortuga'],
    correctAnswer: 'el perezoso',
    hint: 'Sloth - extremely slow movement, hangs from trees, lives in rainforests',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_095',
    emoji: '🦦',
    question: '¿Qué animal juguetón nada en los ríos?',
    translation: 'What playful animal swims in rivers?',
    options: ['la nutria', 'el castor', 'la foca'],
    correctAnswer: 'la nutria',
    hint: 'Otter - playful aquatic mammal, uses rocks to open shells, lives near water',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_096',
    emoji: '🦨',
    question: '¿Qué animal produce un olor muy fuerte para defenderse?',
    translation: 'What animal produces a very strong smell to defend itself?',
    options: ['el zorrillo', 'la mofeta', 'el tejón'],
    correctAnswer: 'el zorrillo',
    hint: 'Skunk - sprays strong-smelling liquid as defense, black with white stripes',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_097',
    emoji: '🦡',
    question: '¿Qué animal nocturno tiene rayas en la cara?',
    translation: 'What nocturnal animal has stripes on its face?',
    options: ['el tejón', 'el mapache', 'el zorrillo'],
    correctAnswer: 'el tejón',
    hint: 'Badger - nocturnal, lives in burrows called setts, distinctive facial stripes',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'medium',
  },
  {
    id: 'animals_098',
    emoji: '🦝',
    question: '¿Qué animal tiene máscara negra y cola con anillos?',
    translation: 'What animal has a black mask and ringed tail?',
    options: ['el mapache', 'el tejón', 'el panda rojo'],
    correctAnswer: 'el mapache',
    hint: 'Raccoon - masked face, ringed tail, intelligent, washes food before eating',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_099',
    emoji: '🐊',
    question: '¿Qué reptil grande vive en pantanos?',
    translation: 'What large reptile lives in swamps?',
    options: ['el caimán', 'el cocodrilo', 'el lagarto'],
    correctAnswer: 'el caimán',
    hint: 'Alligator - large reptile, lives in swamps, powerful jaws, from Americas',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'medium',
  },
  {
    id: 'animals_100',
    emoji: '🐢',
    question: '¿Qué animal lleva su casa en el caparazón?',
    translation: 'What animal carries its house in its shell?',
    options: ['la tortuga', 'el caracol', 'el cangrejo ermitaño'],
    correctAnswer: 'la tortuga',
    hint: 'Turtle - reptile with protective shell, can be aquatic or terrestrial, long-lived',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_101',
    emoji: '🦎',
    question: '¿Qué reptil pequeño puede cambiar de color?',
    translation: 'What small reptile can change color?',
    options: ['el camaleón', 'la lagartija', 'la iguana'],
    correctAnswer: 'el camaleón',
    hint: 'Chameleon - changes color for camouflage and communication, long tongue, swivel eyes',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_102',
    emoji: '🦈',
    question: '¿Qué pez grande tiene muchos dientes?',
    translation: 'What large fish has many teeth?',
    options: ['el tiburón', 'la ballena', 'el delfín'],
    correctAnswer: 'el tiburón',
    hint: 'Shark - large predatory fish, multiple rows of teeth, cartilage skeleton',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_103',
    emoji: '🐳',
    question: '¿Qué animal marino es el más grande del mundo?',
    translation: 'What marine animal is the largest in the world?',
    options: ['la ballena azul', 'el tiburón ballena', 'la orca'],
    correctAnswer: 'la ballena azul',
    hint: 'Blue whale - largest animal ever, can weigh up to 200 tons, eats krill',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
  {
    id: 'animals_104',
    emoji: '🦇',
    question: '¿Qué mamífero vuela de noche?',
    translation: 'What mammal flies at night?',
    options: ['el murciélago', 'la lechuza', 'el búho'],
    correctAnswer: 'el murciélago',
    hint: 'Bat - only flying mammal, uses echolocation, often nocturnal, eats insects or fruit',
    points: 5,
    category: 'fauna_animals',
    difficulty: 'easy',
  },
];
