/**
 * RECREATION Category Questions
 * Category: recreation
 */

export const recreationQuestions = [
{
    id: 'recreation_001',
    emoji: 'billiards-table.png',
    question: '¿En qué mesa juegas con tacos y bolas?',
    translation: 'On what table do you play with cues and balls?',
    options: ['la mesa de billar', 'la mesa de ping pong', 'la mesa de juegos'],
    correctAnswer: 'la mesa de billar',
    hint: 'Billiards table - pool table with pockets, played with cue stick and balls',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_002',
    emoji: '🏊',
    question: '¿Qué actividad es?',
    translation: 'What activity is it?',
    options: ['nadar', 'la natación', 'ir a nadar'],
    correctAnswer: 'nadar',
    hint: 'Swim - water movement, from Latin "natare", essential beach activity',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_003',
    emoji: '🏄',
    question: '¿Qué actividad es?',
    translation: 'What activity is it?',
    options: ['surf', 'hacer surf', 'el surf'],
    correctAnswer: 'surf',
    hint: 'Surfing - ride waves on board, popular in Spain and Mexico',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_004',
    emoji: '🤿',
    question: '¿Qué actividad es?',
    translation: 'What activity is it?',
    options: ['bucear', 'el buceo', 'hacer snorkel'],
    correctAnswer: 'bucear',
    hint: 'Dive - explore underwater with mask and snorkel, Caribbean excellent',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_005',
    emoji: '☀️',
    question: '¿Qué brilla en el cielo y da calor?',
    translation: 'What shines in the sky and gives heat?',
    options: ['el sol', 'el astro rey', 'el sol ardiente'],
    correctAnswer: 'el sol',
    hint: 'Sun - provides light and heat, "tomar el sol" means sunbathe',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_006',
    emoji: '🌊',
    question: '¿Qué forma el mar cuando se mueve?',
    translation: 'What does the sea form when it moves?',
    options: ['la ola', 'la onda', 'el oleaje'],
    correctAnswer: 'la ola',
    hint: 'Wave - moving water, surfers love big waves, from Latin "unda"',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_007',
    emoji: '🏝️',
    question: '¿Qué lugar es?',
    translation: 'What place is it?',
    options: ['la isla', 'el islote', 'el atolón'],
    correctAnswer: 'la isla',
    hint: 'Island - land surrounded by water, Canary Islands famous in Spain',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_008',
    emoji: '⛱️',
    question: '¿Qué usas para dar sombra en la playa?',
    translation: 'What do you use to give shade at the beach?',
    options: ['la sombrilla', 'el parasol', 'la sombrilla de playa'],
    correctAnswer: 'la sombrilla',
    hint: 'Beach umbrella - provides shade, "paraguas" for rain',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_009',
    emoji: '🩱',
    question: '¿Qué ropa es?',
    translation: 'What clothing is it?',
    options: ['el traje de baño', 'el bañador', 'el swimsuit'],
    correctAnswer: 'el traje de baño',
    hint: 'Swimsuit - "bañador" also used, essential for swimming',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_010',
    emoji: '🕶️',
    question: '¿Qué proteges tus ojos del sol con esto?',
    translation: 'What do you protect your eyes from the sun with?',
    options: ['las gafas de sol', 'los lentes de sol', 'los anteojos de sol'],
    correctAnswer: 'las gafas de sol',
    hint: 'Sunglasses - protect eyes from UV rays, "lentes de sol" in Latin America',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_011',
    emoji: '🧴',
    question: '¿Qué necesitas en la playa?',
    translation: 'What do you need at the beach?',
    options: ['el protector solar', 'el bloqueador solar', 'la crema solar'],
    correctAnswer: 'el protector solar',
    hint: 'Sunscreen - prevents sunburn, SPF 30+ recommended, "bloqueador solar" also used',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'recreation_012',
    emoji: '🏐',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['el voleibol', 'el vóley', 'el vóleibol'],
    correctAnswer: 'el voleibol',
    hint: 'Volleyball - beach sport with net, "vóley playa" is beach volleyball',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_013',
    emoji: '🐚',
    question: '¿Qué coleccionas en la arena?',
    translation: 'What do you collect in the sand?',
    options: ['la concha', 'la concha marina', 'el caracol marino'],
    correctAnswer: 'la concha',
    hint: 'Seashell - former mollusk home, beautiful to collect on beach',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_014',
    emoji: '🌴',
    question: '¿Qué árbol es?',
    translation: 'What tree is it?',
    options: ['la palmera', 'la palma', 'el cocotero'],
    correctAnswer: 'la palmera',
    hint: 'Palm tree - tropical tree, provides coconuts and shade at beach',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_015',
    emoji: '🥥',
    question: '¿Qué fruta es?',
    translation: 'What fruit is it?',
    options: ['el coco', 'el coco verde', 'la nuez de coco'],
    correctAnswer: 'el coco',
    hint: 'Coconut - tropical fruit from palm tree, agua de coco refreshing',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  
  // Water Activities (20 questions)
  {
    id: 'recreation_016',
    emoji: '🏊',
    question: '¿Qué estás haciendo?',
    translation: 'What are you doing?',
    options: ['nadar', 'la natación', 'bañarse'],
    correctAnswer: 'nadar',
    hint: 'Swimming - propelling through water, good exercise and fun',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_017',
    emoji: '🏄',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['surf', 'hacer surf', 'el surf'],
    correctAnswer: 'surf',
    hint: 'Surfing - riding waves on board, originated in Polynesia, popular worldwide',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_018',
    emoji: '🤿',
    question: '¿Qué actividad es?',
    translation: 'What activity is it?',
    options: ['bucear', 'el buceo', 'hacer snorkel'],
    correctAnswer: 'bucear',
    hint: 'Diving - underwater exploration with mask, snorkel, or scuba gear',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'recreation_019',
    emoji: '⛵',
    question: '¿Qué barco usa el viento para moverse?',
    translation: 'What boat uses the wind to move?',
    options: ['el velero', 'el bote de vela', 'la embarcación de vela'],
    correctAnswer: 'el velero',
    hint: 'Sailboat - wind-powered vessel, "vela" is sail, eco-friendly navigation',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_020',
    emoji: '🚤',
    question: '¿Qué tipo de barco es?',
    translation: 'What type of boat is it?',
    options: ['la lancha', 'la lancha motora', 'la lancha rápida'],
    correctAnswer: 'la lancha',
    hint: 'Motorboat - fast speedboat, "lancha rápida" for speed, popular for water sports',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_021',
    emoji: '🛶',
    question: '¿Qué embarcación es?',
    translation: 'What vessel is it?',
    options: ['la canoa', 'la piragua', 'el kayak'],
    correctAnswer: 'la canoa',
    hint: 'Canoe - small paddle boat, indigenous origin, "piragua" also used',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_022',
    emoji: '🎣',
    question: '¿Qué actividad es?',
    translation: 'What activity is it?',
    options: ['pescar', 'la pesca', 'ir de pesca'],
    correctAnswer: 'pescar',
    hint: 'Fishing - catching fish with rod and bait, relaxing beach activity',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'recreation_023',
    emoji: '🐟',
    question: '¿Qué animal es?',
    translation: 'What animal is it?',
    options: ['el pez', 'el pescado', 'el pececillo'],
    correctAnswer: 'el pez',
    hint: 'Fish - aquatic animal with gills, "pescado" when caught for food',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_024',
    emoji: '🐠',
    question: '¿Qué pez colorido vive en aguas cálidas?',
    translation: 'What colorful fish lives in warm waters?',
    options: ['el pez tropical', 'el pez de colores', 'el pez exótico'],
    correctAnswer: 'el pez tropical',
    hint: 'Tropical fish - colorful warm-water fish, beautiful in coral reefs',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_025',
    emoji: '🦈',
    question: '¿Qué animal marino es?',
    translation: 'What marine animal is it?',
    options: ['el tiburón', 'el escualo', 'el jaquetón'],
    correctAnswer: 'el tiburón',
    hint: 'Shark - apex predator, from "tiburón" (ancient Taíno word)',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_026',
    emoji: '🐬',
    question: '¿Qué animal marino es?',
    translation: 'What marine animal is it?',
    options: ['el delfín', 'el delfín nariz de botella', 'el cetáceo'],
    correctAnswer: 'el delfín',
    hint: 'Dolphin - intelligent mammal, friendly and playful, from Greek "delphis"',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_027',
    emoji: '🐳',
    question: '¿Qué animal es?',
    translation: 'What animal is it?',
    options: ['la ballena', 'el cetáceo', 'la ballena azul'],
    correctAnswer: 'la ballena',
    hint: 'Whale - largest animal on Earth, blue whale can reach 30m long',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_028',
    emoji: '🦀',
    question: '¿Qué criatura es?',
    translation: 'What creature is it?',
    options: ['el cangrejo', 'el crustáceo', 'la jaiba'],
    correctAnswer: 'el cangrejo',
    hint: 'Crab - walks sideways, has claws, hides in sand on beach',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_029',
    emoji: '🦞',
    question: '¿Qué marisco es?',
    translation: 'What seafood is it?',
    options: ['la langosta', 'el bogavante', 'la langosta de mar'],
    correctAnswer: 'la langosta',
    hint: 'Lobster - expensive seafood delicacy, red when cooked',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_030',
    emoji: '🦑',
    question: '¿Qué criatura marina es?',
    translation: 'What marine creature is it?',
    options: ['el calamar', 'la jibia', 'el chipirón'],
    correctAnswer: 'el calamar',
    hint: 'Squid - has tentacles and shoots ink for defense, calamari dish',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_031',
    emoji: '🐙',
    question: '¿Qué animal marino es?',
    translation: 'What marine animal is it?',
    options: ['el pulpo', 'el pulpo común', 'el cefalópodo'],
    correctAnswer: 'el pulpo',
    hint: 'Octopus - eight arms, highly intelligent, can change color',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_032',
    emoji: '🪼',
    question: '¿Qué animal marino puede picar?',
    translation: 'What marine animal can sting?',
    options: ['la medusa', 'la aguamala', 'la aguaviva'],
    correctAnswer: 'la medusa',
    hint: 'Jellyfish - can sting, gelatinous body, "aguamala" in some regions',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'recreation_033',
    emoji: '⭐',
    question: '¿Qué es esto del mar?',
    translation: 'What is this from the sea?',
    options: ['la estrella de mar', 'el asteroidea', 'la estrella marina'],
    correctAnswer: 'la estrella de mar',
    hint: 'Starfish - five-pointed sea creature, can regenerate lost arms',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_034',
    emoji: '🐚',
    question: '¿Qué encuentras en la playa?',
    translation: 'What do you find at the beach?',
    options: ['la concha', 'la concha marina', 'el caracol'],
    correctAnswer: 'la concha',
    hint: 'Seashell - mollusk\'s former home, makes ocean sound when held to ear',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_035',
    emoji: '🌊',
    question: '¿Qué montan los surfistas?',
    translation: 'What do surfers ride?',
    options: ['la ola', 'la onda', 'el oleaje'],
    correctAnswer: 'la ola',
    hint: 'Wave - moving water ridge, surfers ride them, "oleaje" is surf',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'happy',
  },
  
  // Beach Equipment & Items (20 questions)
  {
    id: 'recreation_036',
    emoji: '🏖️',
    question: '¿Qué pones en la arena para dar sombra?',
    translation: 'What do you put in the sand to give shade?',
    options: ['la sombrilla de playa', 'el parasol', 'la sombrilla playera'],
    correctAnswer: 'la sombrilla de playa',
    hint: 'Provides shade at the beach',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_037',
    emoji: '🩱',
    question: '¿Qué ropa es?',
    translation: 'What clothing is it?',
    options: ['el traje de baño', 'el bañador', 'el swimsuit'],
    correctAnswer: 'el traje de baño',
    hint: 'What you wear swimming',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_038',
    emoji: '🩳',
    question: '¿Qué son estos?',
    translation: 'What are these?',
    options: ['el bañador', 'el traje de baño', 'el short de baño'],
    correctAnswer: 'el bañador',
    hint: 'Men\'s swimming attire',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_039',
    emoji: '🕶️',
    question: '¿Qué son estos?',
    translation: 'What are these?',
    options: ['las gafas de sol', 'los lentes de sol', 'los anteojos de sol'],
    correctAnswer: 'las gafas de sol',
    hint: 'Protect your eyes from the sun',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_040',
    emoji: '🧴',
    question: '¿Qué esencial de playa es esto?',
    translation: 'What beach essential is this?',
    options: ['el protector solar', 'el bloqueador solar', 'la crema solar'],
    correctAnswer: 'el protector solar',
    hint: 'Sunscreen - protects skin from UV damage, reapply every 2 hours',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'recreation_041',
    emoji: '🩴',
    question: '¿Qué calzado es?',
    translation: 'What footwear is it?',
    options: ['las chanclas', 'las chancletas', 'las sandalias de playa'],
    correctAnswer: 'las chanclas',
    hint: 'Flip-flops - beach sandals, easy on/off, "sandalias" also used',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_042',
    emoji: '🧊',
    question: '¿Qué usas en una hielera?',
    translation: 'What do you use in a cooler?',
    options: ['el hielo', 'el hielo picado', 'los cubitos de hielo'],
    correctAnswer: 'el hielo',
    hint: 'Ice - frozen water, keeps food/drinks cold, melts slowly',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_043',
    emoji: '🧺',
    question: '¿Qué llevas a la playa?',
    translation: 'What do you take to the beach?',
    options: ['la cesta de playa', 'la canasta', 'el bolso de playa'],
    correctAnswer: 'la cesta de playa',
    hint: 'Beach basket - woven carrier for towels and supplies',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_044',
    emoji: '🪣',
    question: '¿Qué usan los niños para hacer castillos de arena?',
    translation: 'What do children use to make sand castles?',
    options: ['el cubo', 'la cubeta', 'el balde'],
    correctAnswer: 'el cubo',
    hint: 'Bucket - container for carrying sand and water, shapes sand',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_045',
    emoji: '🏰',
    question: '¿Qué construyes con arena?',
    translation: 'What do you build with sand?',
    options: ['el castillo de arena', 'la fortaleza de arena', 'la construcción de arena'],
    correctAnswer: 'el castillo de arena',
    hint: 'Sandcastle - classic beach building activity, use wet sand',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'recreation_046',
    emoji: '🎭',
    question: '¿Qué usas en el agua?',
    translation: 'What do you use in the water?',
    options: ['la máscara de buceo', 'las gafas de buceo', 'la máscara submarina'],
    correctAnswer: 'la máscara de buceo',
    hint: 'Diving mask - waterproof eyewear, "gafas de buceo" also used',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_047',
    emoji: '🏊‍♂️',
    question: '¿Qué usas para nadar más rápido?',
    translation: 'What do you use to swim faster?',
    options: ['las aletas', 'las patas de rana', 'los flippers'],
    correctAnswer: 'las aletas',
    hint: 'Flippers - swim fins for propulsion, "patas de rana" (frog feet)',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_048',
    emoji: '🛟',
    question: '¿Qué dispositivo de seguridad es?',
    translation: 'What safety device is it?',
    options: ['el salvavidas', 'el flotador', 'el aro salvavidas'],
    correctAnswer: 'el salvavidas',
    hint: 'Life preserver - ring buoy for rescue, also means lifeguard person',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_049',
    emoji: '🎈',
    question: '¿Qué es esto inflable?',
    translation: 'What is this inflatable?',
    options: ['el globo', 'el globo inflable', 'el balón'],
    correctAnswer: 'el globo',
    hint: 'Balloon - inflatable with air or helium, floats and pops',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_050',
    emoji: '🏐',
    question: '¿Qué deporte de playa usa esta pelota?',
    translation: 'What beach sport uses this ball?',
    options: ['el voleibol de playa', 'el vóley playa', 'el beach volleyball'],
    correctAnswer: 'el voleibol de playa',
    hint: 'Beach volleyball - played on sand over net, Olympic sport',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'recreation_051',
    emoji: '🥏',
    question: '¿Qué juguete es?',
    translation: 'What toy is it?',
    options: ['el frisbee', 'el disco volador', 'el disco'],
    correctAnswer: 'el frisbee',
    hint: 'Frisbee - flying disc you throw and catch, "disco volador" in Spanish',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_052',
    emoji: '🪁',
    question: '¿Qué vuelas en una playa ventosa?',
    translation: 'What do you fly on a windy beach?',
    options: ['la cometa', 'el papalote', 'el volantín'],
    correctAnswer: 'la cometa',
    hint: 'Kite - flies on string in wind, "papalote" in Mexico',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_053',
    emoji: '📸',
    question: '¿Qué usas para tomar fotos?',
    translation: 'What do you use to take photos?',
    options: ['la cámara', 'la cámara fotográfica', 'la cámara digital'],
    correctAnswer: 'la cámara',
    hint: 'Camera - captures memories, smartphone cameras now common',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_054',
    emoji: '🎒',
    question: '¿En qué llevas tus cosas?',
    translation: 'What do you carry your things in?',
    options: ['la mochila', 'la bolsa', 'el morral'],
    correctAnswer: 'la mochila',
    hint: 'Backpack - carries beach gear on shoulders, hands-free',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_055',
    emoji: '💧',
    question: '¿Qué bebes cuando tienes sed?',
    translation: 'What do you drink when you\'re thirsty?',
    options: ['el agua', 'el agua potable', 'el agua fresca'],
    correctAnswer: 'el agua',
    hint: 'Water - essential hydration, especially important in sun',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  
  // Nature & Environment (20 questions)
  {
    id: 'recreation_056',
    emoji: '☀️',
    question: '¿Qué brilla en el cielo?',
    translation: 'What shines in the sky?',
    options: ['el sol', 'el astro rey', 'el sol radiante'],
    correctAnswer: 'el sol',
    hint: 'Sun - star providing daylight, "tomar el sol" means sunbathe',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'recreation_057',
    emoji: '🌙',
    question: '¿Qué brilla de noche?',
    translation: 'What shines at night?',
    options: ['la luna', 'la luna llena', 'el satélite natural'],
    correctAnswer: 'la luna',
    hint: 'Moon - reflects sunlight at night, phases change monthly',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_058',
    emoji: '⭐',
    question: '¿Qué ves en el cielo nocturno?',
    translation: 'What do you see in the night sky?',
    options: ['la estrella', 'el astro', 'la estrella brillante'],
    correctAnswer: 'la estrella',
    hint: 'Star - distant sun, twinkles in night sky, from Latin "stella"',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_059',
    emoji: '☁️',
    question: '¿Qué está en el cielo?',
    translation: 'What is in the sky?',
    options: ['la nube', 'la nubosidad', 'el nubarrón'],
    correctAnswer: 'la nube',
    hint: 'Cloud - water vapor condensed, brings shade and rain',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_060',
    emoji: '🌤️',
    question: '¿Qué clima es?',
    translation: 'What climate is it?',
    options: ['parcialmente nublado', 'medio nublado', 'nuboso parcial'],
    correctAnswer: 'parcialmente nublado',
    hint: 'Partly cloudy - sun and clouds together, mixed weather',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'recreation_061',
    emoji: '⛅',
    question: '¿Qué clima es?',
    translation: 'What climate is it?',
    options: ['nublado', 'nuboso', 'cubierto de nubes'],
    correctAnswer: 'nublado',
    hint: 'Cloudy - sky covered with clouds, less sun',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'recreation_062',
    emoji: '🌧️',
    question: '¿Qué clima es?',
    translation: 'What climate is it?',
    options: ['la lluvia', 'la precipitación', 'el aguacero'],
    correctAnswer: 'la lluvia',
    hint: 'Rain - water falling from clouds, "llover" means to rain',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_063',
    emoji: '⛈️',
    question: '¿Qué tiempo hace?',
    translation: 'What\'s the weather like?',
    options: ['la tormenta', 'la tempestad', 'el temporal'],
    correctAnswer: 'la tormenta',
    hint: 'Storm - severe weather with thunder, lightning, "tempestad" also used',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_064',
    emoji: '🌈',
    question: '¿Qué aparece después de la lluvia?',
    translation: 'What appears after the rain?',
    options: ['el arcoíris', 'el arco iris', 'el arcoiris'],
    correctAnswer: 'el arcoíris',
    hint: 'Rainbow - colorful arc of light, seven colors spectrum',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'recreation_066',
    emoji: '🏝️',
    question: '¿Qué tierra está rodeada de agua?',
    translation: 'What land is surrounded by water?',
    options: ['la isla', 'el islote', 'el atolón'],
    correctAnswer: 'la isla',
    hint: 'Island - land completely surrounded by water, tropical paradises',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_067',
    emoji: '⛱️',
    question: '¿Dónde estás?',
    translation: 'Where are you?',
    options: ['en la playa', 'en la costa', 'en la orilla'],
    correctAnswer: 'en la playa',
    hint: 'At the beach - sandy shore by ocean, perfect for relaxing',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'recreation_068',
    emoji: '🏔️',
    question: '¿Qué elevación es muy alta?',
    translation: 'What elevation is very high?',
    options: ['la montaña', 'el monte', 'la sierra'],
    correctAnswer: 'la montaña',
    hint: 'Mountain - very tall landform, from Latin "montanea" (mountainous)',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_069',
    emoji: '🌋',
    question: '¿Qué montaña arroja lava?',
    translation: 'What mountain throws lava?',
    options: ['el volcán', 'el volcán activo', 'el cráter'],
    correctAnswer: 'el volcán',
    hint: 'Volcano - mountain that can erupt with lava, from Vulcan (fire god)',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_070',
    emoji: '🏞️',
    question: '¿Dónde protege una nación la naturaleza?',
    translation: 'Where does a nation protect nature?',
    options: ['el parque nacional', 'una reserva de parque nacional', 'el área protegida'],
    correctAnswer: 'una reserva de parque nacional',
    hint: 'National park - protected nature reserve, preserves wildlife',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'calm',
  },
  
  // Outdoor Activities & Sports (25 questions)
  {
    id: 'recreation_076',
    emoji: '🚶',
    question: '¿Qué estás haciendo?',
    translation: 'What are you doing?',
    options: ['caminar', 'andar', 'pasear'],
    correctAnswer: 'caminar',
    hint: 'Walking - moving on foot at normal pace, good exercise',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_077',
    emoji: '🏃',
    question: '¿Qué estás haciendo?',
    translation: 'What are you doing?',
    options: ['correr', 'trotar', 'el jogging'],
    correctAnswer: 'correr',
    hint: 'Running - moving faster than walking, cardio exercise',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_078',
    emoji: '🚴',
    question: '¿Qué actividad es?',
    translation: 'What activity is it?',
    options: ['andar en bicicleta', 'montar en bici', 'el ciclismo'],
    correctAnswer: 'andar en bicicleta',
    hint: 'Biking - riding bicycle, "montar en bici" also used',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_079',
    emoji: '🏇',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['montar a caballo', 'la equitación', 'cabalgar'],
    correctAnswer: 'montar a caballo',
    hint: 'Horseback riding - equestrian sport, "equitación" formal term',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'recreation_080',
    emoji: '⛷️',
    question: '¿Qué deporte de invierno es?',
    translation: 'What winter sport is it?',
    options: ['esquiar', 'el esquí', 'el esquí alpino'],
    correctAnswer: 'esquiar',
    hint: 'Skiing - sliding on snow with skis, popular in Pyrenees and Andes',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_081',
    emoji: '🏂',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['el snowboard', 'la tabla de nieve', 'el snowboarding'],
    correctAnswer: 'el snowboard',
    hint: 'Snowboarding - boarding on snow slopes, like surfing on snow',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_082',
    emoji: '🧗',
    question: '¿Qué estás haciendo?',
    translation: 'What are you doing?',
    options: ['escalar', 'el alpinismo', 'la escalada'],
    correctAnswer: 'escalar',
    hint: 'Climbing - ascending mountains or walls, requires strength',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'recreation_083',
    emoji: '🏌️',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['el golf', 'el minigolf', 'jugar al golf'],
    correctAnswer: 'el golf',
    hint: 'Golf - hit ball into 18 holes with clubs, precision sport',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_084',
    emoji: '🎾',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['el tenis', 'el tenis de mesa', 'el pádel'],
    correctAnswer: 'el tenis',
    hint: 'Tennis - racket sport with yellow ball, Wimbledon famous',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_085',
    emoji: '🏀',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['el básquetbol', 'el baloncesto', 'el basquetbol'],
    correctAnswer: 'el básquetbol',
    hint: 'Basketball - shoot ball through hoop, "baloncesto" in Spain',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'recreation_086',
    emoji: '⚽',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['el fútbol', 'el balompié', 'el soccer'],
    correctAnswer: 'el fútbol',
    hint: 'Soccer - world\'s most popular sport, "el deporte rey" (king sport)',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_087',
    emoji: '🏈',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['el fútbol americano', 'el football americano', 'el fútbol gringo'],
    correctAnswer: 'el fútbol americano',
    hint: 'American football - popular in USA, NFL Super Bowl famous',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_088',
    emoji: '⚾',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['el béisbol', 'el beisbol', 'el baseball'],
    correctAnswer: 'el béisbol',
    hint: 'Baseball - America\'s pastime, bat and ball sport, 9 innings',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'recreation_089',
    emoji: '🥎',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['el softball', 'el sófbol', 'el softbol'],
    correctAnswer: 'el softball',
    hint: 'Softball - like baseball with larger ball, underhand pitching',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_090',
    emoji: '🎱',
    question: '¿Qué juego es?',
    translation: 'What game is it?',
    options: ['el billar', 'el pool', 'la mesa de billar'],
    correctAnswer: 'el billar',
    hint: 'Billiards - pool table game, hit balls with cue stick',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_091',
    emoji: '🎳',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['los bolos', 'el boliche', 'el bowling'],
    correctAnswer: 'los bolos',
    hint: 'Bowling - knock down pins with ball, "boliche" in Latin America',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_092',
    emoji: '🎯',
    question: '¿Qué lanzas al tablero circular?',
    translation: 'What do you throw at the circular board?',
    options: ['los dardos', 'el juego de dardos', 'la diana'],
    correctAnswer: 'los dardos',
    hint: 'Darts - throw pointed missiles at circular board target',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'recreation_093',
    emoji: '🏹',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['el tiro con arco', 'la arquería', 'el arco y flecha'],
    correctAnswer: 'el tiro con arco',
    hint: 'Archery - shoot arrows with bow, "arquería" also used, Olympic sport',
    points: 15,
    category: 'recreation',
    difficulty: 'hard',
    emotion: 'excited',
  },
  {
    id: 'recreation_094',
    emoji: '🥊',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['el boxeo', 'el pugilismo', 'el boxear'],
    correctAnswer: 'el boxeo',
    hint: 'Boxing - fighting with gloves in ring, "púgil" is boxer',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'recreation_095',
    emoji: '🤺',
    question: '¿Qué deporte es?',
    translation: 'What sport is it?',
    options: ['la esgrima', 'el esgrimir', 'la esgrima deportiva'],
    correctAnswer: 'la esgrima',
    hint: 'Fencing - sword fighting sport with foil, épée, or sabre',
    points: 15,
    category: 'recreation',
    difficulty: 'hard',
    emotion: 'pleased',
  },
  {
    id: 'recreation_096',
    emoji: '🥋',
    question: '¿Qué arte marcial es?',
    translation: 'What martial art is it?',
    options: ['el karate', 'el kárate', 'el karate-do'],
    correctAnswer: 'el karate',
    hint: 'Karate - Japanese martial art, "empty hand" striking techniques',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_097',
    emoji: '🏋️',
    question: '¿Qué haces en el gimnasio?',
    translation: 'What do you do at the gym?',
    options: ['levantar pesas', 'el levantamiento de pesas', 'pesas'],
    correctAnswer: 'levantar pesas',
    hint: 'Weightlifting - lifting weights builds muscle, "pesas" are weights',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'recreation_098',
    emoji: '🤸',
    question: '¿Qué actividad es?',
    translation: 'What activity is it?',
    options: ['la gimnasia', 'la gimnasia artística', 'la gimnasia deportiva'],
    correctAnswer: 'la gimnasia',
    hint: 'Gymnastics - acrobatic exercises, balance and flexibility sport',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_099',
    emoji: '🧘',
    question: '¿Qué práctica es?',
    translation: 'What practice is it?',
    options: ['el yoga', 'la yoga', 'el hatha yoga'],
    correctAnswer: 'el yoga',
    hint: 'Yoga - mind-body practice from India, breathing and poses',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'recreation_100',
    emoji: '🎪',
    question: '¿Qué entretenimiento es?',
    translation: 'What entertainment is it?',
    options: ['el circo', 'el circo ambulante', 'la carpa'],
    correctAnswer: 'el circo',
    hint: 'Circus - acrobats, clowns, animals perform, from Latin "circus" (ring)',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_101',
    emoji: '🌵',
    question: '¿Qué planta tiene espinas y crece en el desierto?',
    translation: 'What plant has spines and grows in the desert?',
    options: ['el cactus', 'la palmera', 'el aloe'],
    correctAnswer: 'el cactus',
    hint: 'Cactus - desert plant with spines, stores water, survives in hot dry climates',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'recreation_102',
    emoji: '🤳',
    question: '¿Qué estás haciendo?',
    translation: 'What are you doing?',
    options: ['tomar una selfie', 'hacer una selfie', 'sacar una selfie'],
    correctAnswer: 'tomar una selfie',
    hint: 'Taking a selfie - photo of yourself with phone, popular at beach',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_103',
    emoji: '🥵',
    question: '¿Qué haces en un día muy caluroso?',
    translation: 'What do you do on a very hot day?',
    options: ['sudar', 'transpirar', 'estar sudando'],
    correctAnswer: 'sudar',
    hint: 'Sweating - body cools itself on hot day, "transpirar" also used',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_104',
    emoji: '🪂',
    question: '¿Qué actividad de agua es?',
    translation: 'What water activity is it?',
    options: ['el parasailing', 'hacer parasailing', 'el paravelismo'],
    correctAnswer: 'el parasailing',
    hint: 'Parasailing - parachute towed behind boat at beach resorts, thrilling water sport',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'recreation_105',
    emoji: '🛖',
    question: '¿Qué estructura encuentras en la playa de un resort?',
    translation: 'What structure do you find on the beach at a resort?',
    options: ['la cabaña', 'la palapa', 'el chiringuito'],
    correctAnswer: 'la cabaña',
    hint: 'Beach hut - small structure at resorts, "palapa" is thatched-roof hut, provides shade',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_106',
    emoji: '🏌🏻',
    question: '¿Qué deporte juegas con un palo y una pelota pequeña?',
    translation: 'What sport do you play with a club and a small ball?',
    options: ['el golf', 'el hockey', 'el béisbol'],
    correctAnswer: 'el golf',
    hint: 'Golf - sport played on courses with clubs and small ball, aims for holes',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_107',
    emoji: '⛳️',
    question: '¿Dónde se juega al golf?',
    translation: 'Where do you play golf?',
    options: ['el campo de golf', 'la cancha de golf', 'el estadio'],
    correctAnswer: 'el campo de golf',
    hint: 'Golf course - large outdoor area with grass, holes, and flags where golf is played',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'recreation_108',
    emoji: '📜',
    question: '¿Qué haces cuando visitas lugares históricos?',
    translation: 'What do you do when you visit historical places?',
    options: ['visitar monumentos', 'ir de compras', 'nadar'],
    correctAnswer: 'visitar monumentos',
    hint: 'Visit monuments - explore historical sites, learn about culture and history',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_109',
    emoji: '🚯',
    question: '¿Qué está prohibido hacer en la playa?',
    translation: 'What is prohibited to do at the beach?',
    options: ['tirar basura', 'tirar desperdicios', 'ensuciar'],
    correctAnswer: 'tirar basura',
    hint: 'Littering - throwing trash, prohibited on beaches, "no tirar basura" means no littering',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_113',
    emoji: '🤾‍♂️',
    question: '¿Qué deporte de equipo juegas en la arena?',
    translation: 'What team sport do you play on the sand?',
    options: ['el voleibol de playa', 'el fútbol playa', 'el balonmano'],
    correctAnswer: 'el voleibol de playa',
    hint: 'Beach volleyball - team sport played on sand, popular beach activity worldwide',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_114',
    emoji: '🧖🏾‍♀️',
    question: '¿Qué pides en el resort para secarte después de nadar?',
    translation: 'What do you ask for at the resort to dry off after swimming?',
    options: ['las toallas', 'las sábanas', 'las mantas'],
    correctAnswer: 'las toallas',
    hint: 'Towels - provided at beach resorts for drying after swimming, often available at towel station',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_115',
    emoji: '🚷',
    question: '¿Qué está prohibido hacer cerca de la piscina del hotel?',
    translation: 'What is prohibited to do near the hotel pool?',
    options: ['correr', 'nadar', 'caminar'],
    correctAnswer: 'correr',
    hint: 'No running - pool safety rule at hotels/resorts, prevents slipping on wet surfaces',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'recreation_116',
    emoji: '🔭',
    question: '¿Qué actividad nocturna haces para ver las estrellas?',
    translation: 'What nighttime activity do you do to see the stars?',
    options: ['observar las estrellas', 'mirar el cielo', 'ver las constelaciones'],
    correctAnswer: 'observar las estrellas',
    hint: 'Star gazing - nighttime activity to observe stars and constellations, popular at beach resorts',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_117',
    emoji: '🏊',
    question: '¿Qué deporte es este?',
    translation: 'What sport is this?',
    options: ['la natación', 'el nado', 'la piscina'],
    correctAnswer: 'la natación',
    hint: 'Swimming - "natación" from "nadar" (to swim), Olympic sport',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_118',
    emoji: '🏃',
    question: '¿Qué actividad es esta?',
    translation: 'What activity is this?',
    options: ['correr', 'trotar', 'esprintar'],
    correctAnswer: 'correr',
    hint: 'Running - "correr" for jogging or racing, popular exercise',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'recreation_119',
    emoji: '🏄',
    question: '¿Qué deporte haces sobre las olas?',
    translation: 'What sport do you do on the waves?',
    options: ['el surf', 'el surfing', 'la tabla'],
    correctAnswer: 'el surf',
    hint: 'Surfing - ride ocean waves standing on board, Hawaii origins',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_120',
    emoji: '🏊',
    question: '¿Qué deporte haces en la piscina?',
    translation: 'What sport do you do in the pool?',
    options: ['la natación', 'el nado', 'la alberca'],
    correctAnswer: 'la natación',
    hint: 'Swimming - propel yourself through water, Olympic sport with styles',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_121',
    emoji: 'air-hockey.png',
    question: '¿Qué juego de mesa se juega en una superficie con aire?',
    translation: 'What table game is played on a surface with air?',
    options: ['el hockey de aire', 'el air hockey', 'el hockey sobre hielo'],
    correctAnswer: 'el hockey de aire',
    hint: 'Air hockey - table game with puck floating on air cushion, fast-paced arcade game',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'recreation_122',
    emoji: 'canoe.png',
    question: '¿Qué embarcación pequeña usas con remos?',
    translation: 'What small boat do you use with paddles?',
    options: ['la canoa', 'el kayak', 'el bote'],
    correctAnswer: 'la canoa',
    hint: 'Canoe - small narrow boat propelled by paddles, great for rivers and lakes',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_123',
    emoji: 'climbing-harness.png',
    question: '¿Qué equipo de seguridad usas para escalar?',
    translation: 'What safety equipment do you use for climbing?',
    options: ['el arnés de escalada', 'la cuerda', 'el casco'],
    correctAnswer: 'el arnés de escalada',
    hint: 'Climbing harness - safety equipment that attaches climber to rope, essential for rock climbing',
    points: 15,
    category: 'recreation',
    difficulty: 'hard',
    emotion: 'calm',
  },
  {
    id: 'recreation_124',
    emoji: 'cross-trainer.png',
    question: '¿Qué máquina de gimnasio es esta?',
    translation: 'What gym machine is this?',
    options: ['la elíptica', 'el cross-trainer', 'la caminadora'],
    correctAnswer: 'la elíptica',
    hint: 'Elliptical machine - low-impact cardio equipment, works arms and legs simultaneously',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_125',
    emoji: 'dock.png',
    question: '¿Dónde amarras los barcos?',
    translation: 'Where do you dock boats?',
    options: ['el muelle', 'el embarcadero', 'la marina'],
    correctAnswer: 'el muelle',
    hint: 'Dock - platform where boats are moored, "embarcadero" also used',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'recreation_126',
    emoji: 'fishing-gear.png',
    question: '¿Qué necesitas para ir a pescar?',
    translation: 'What do you need to go fishing?',
    options: ['el equipo de pesca', 'la caña de pescar', 'el anzuelo'],
    correctAnswer: 'el equipo de pesca',
    hint: 'Fishing gear - all equipment needed for fishing including rod, tackle, and bait',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_127',
    emoji: 'fishing-rod.png',
    question: '¿Qué usas para pescar?',
    translation: 'What do you use to fish?',
    options: ['la caña de pescar', 'la red', 'el anzuelo'],
    correctAnswer: 'la caña de pescar',
    hint: 'Fishing rod - long pole with line and hook for catching fish',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'recreation_128',
    emoji: 'gym-weight.png',
    question: '¿Qué levantas en el gimnasio?',
    translation: 'What do you lift at the gym?',
    options: ['las pesas', 'las mancuernas', 'la barra'],
    correctAnswer: 'las pesas',
    hint: 'Gym weights - dumbbells or weights for strength training and muscle building',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_129',
    emoji: 'hiking-trail.png',
    question: '¿Por dónde caminas en la montaña?',
    translation: 'Where do you walk in the mountain?',
    options: ['el sendero', 'el camino', 'la ruta'],
    correctAnswer: 'el sendero',
    hint: 'Hiking trail - marked path through nature for walking and hiking',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'recreation_130',
    emoji: 'kayak-paddle.png',
    question: '¿Qué usas para mover un kayak?',
    translation: 'What do you use to move a kayak?',
    options: ['el remo de kayak', 'la pala', 'el remo doble'],
    correctAnswer: 'el remo de kayak',
    hint: 'Kayak paddle - double-bladed paddle used to propel kayak through water',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_131',
    emoji: 'kayak.png',
    question: '¿Qué embarcación pequeña usas sentado?',
    translation: 'What small boat do you use while sitting?',
    options: ['el kayak', 'la canoa', 'el bote'],
    correctAnswer: 'el kayak',
    hint: 'Kayak - narrow watercraft propelled by double-bladed paddle, popular for rivers and sea',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'recreation_132',
    emoji: 'kickboard.png',
    question: '¿Qué usas para practicar natación?',
    translation: 'What do you use to practice swimming?',
    options: ['la tabla de natación', 'el flotador', 'las aletas'],
    correctAnswer: 'la tabla de natación',
    hint: 'Kickboard - flotation device for swimming practice, helps focus on leg kicks',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_133',
    emoji: 'metal-detector.png',
    question: '¿Qué usas para buscar objetos metálicos en la playa?',
    translation: 'What do you use to search for metal objects on the beach?',
    options: ['el detector de metales', 'el buscador', 'el escáner'],
    correctAnswer: 'el detector de metales',
    hint: 'Metal detector - electronic device that finds buried metal objects, popular beach hobby',
    points: 15,
    category: 'recreation',
    difficulty: 'hard',
    emotion: 'calm',
  },
  {
    id: 'recreation_134',
    emoji: 'paddleboat.png',
    question: '¿Qué bote mueves con pedales?',
    translation: 'What boat do you move with pedals?',
    options: ['el hidropedal', 'el bote a pedales', 'el pedaló'],
    correctAnswer: 'el hidropedal',
    hint: 'Paddleboat - pedal-powered boat, fun family activity at lakes and beaches',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_135',
    emoji: 'pebble-beach.png',
    question: '¿Qué tipo de playa tiene piedras pequeñas?',
    translation: 'What type of beach has small stones?',
    options: ['la playa de guijarros', 'la playa de piedras', 'la playa rocosa'],
    correctAnswer: 'la playa de guijarros',
    hint: 'Pebble beach - beach covered with smooth stones instead of sand, common in Mediterranean',
    points: 15,
    category: 'recreation',
    difficulty: 'hard',
    emotion: 'happy',
  },
  {
    id: 'recreation_136',
    emoji: 'punch-bag.png',
    question: '¿Qué usas para practicar boxeo?',
    translation: 'What do you use to practice boxing?',
    options: ['el saco de boxeo', 'la bolsa de boxeo', 'el costal'],
    correctAnswer: 'el saco de boxeo',
    hint: 'Punching bag - heavy bag for boxing practice, develops strength and technique',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_137',
    emoji: 'recreational-vehicle.png',
    question: '¿Qué vehículo usas para acampar?',
    translation: 'What vehicle do you use for camping?',
    options: ['la casa rodante', 'el RV', 'la caravana'],
    correctAnswer: 'la casa rodante',
    hint: 'RV - recreational vehicle with living quarters, "autocaravana" in Spain',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'recreation_138',
    emoji: 'rock-climbing-kit.png',
    question: '¿Qué necesitas para escalar rocas?',
    translation: 'What do you need for rock climbing?',
    options: ['el equipo de escalada', 'el arnés', 'la cuerda'],
    correctAnswer: 'el equipo de escalada',
    hint: 'Rock climbing kit - complete set of gear including harness, rope, carabiners, and helmet',
    points: 15,
    category: 'recreation',
    difficulty: 'hard',
    emotion: 'pleased',
  },
  {
    id: 'recreation_139',
    emoji: 'rowing-boat.png',
    question: '¿Qué bote mueves con remos?',
    translation: 'What boat do you move with oars?',
    options: ['el bote de remos', 'la lancha', 'el kayak'],
    correctAnswer: 'el bote de remos',
    hint: 'Rowing boat - small boat propelled by oars, peaceful water activity',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'recreation_140',
    emoji: 'rowing-machine.png',
    question: '¿Qué máquina simula remar en el gimnasio?',
    translation: 'What machine simulates rowing at the gym?',
    options: ['la máquina de remo', 'el remo ergométrico', 'el simulador de remo'],
    correctAnswer: 'la máquina de remo',
    hint: 'Rowing machine - cardio equipment that simulates rowing motion, great full-body workout',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'recreation_141',
    emoji: 'sandcastle.png',
    question: '¿Qué construyes en la playa con arena?',
    translation: 'What do you build on the beach with sand?',
    options: ['el castillo de arena', 'la escultura de arena', 'la torre de arena'],
    correctAnswer: 'el castillo de arena',
    hint: 'Sandcastle - sand structure built on beach, classic children\'s activity',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_142',
    emoji: 'scuba-tank.png',
    question: '¿Qué necesitas para bucear bajo el agua?',
    translation: 'What do you need to dive underwater?',
    options: ['el tanque de buceo', 'el cilindro de oxígeno', 'la botella de aire'],
    correctAnswer: 'el tanque de buceo',
    hint: 'Scuba tank - compressed air cylinder for underwater breathing, essential for scuba diving',
    points: 15,
    category: 'recreation',
    difficulty: 'hard',
    emotion: 'calm',
  },
  {
    id: 'recreation_143',
    emoji: 'soccer-net.png',
    question: '¿Dónde entra el balón en el fútbol?',
    translation: 'Where does the ball go in soccer?',
    options: ['la portería', 'la red', 'el arco'],
    correctAnswer: 'la portería',
    hint: 'Soccer net - goal where ball must enter to score, "arco" used in Latin America',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_144',
    emoji: 'spin-bike.png',
    question: '¿Qué bicicleta usas en el gimnasio?',
    translation: 'What bike do you use at the gym?',
    options: ['la bicicleta de spinning', 'la bici estática', 'la bicicleta fija'],
    correctAnswer: 'la bicicleta de spinning',
    hint: 'Spin bike - stationary bike for intense cardio workouts, popular fitness class',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'recreation_145',
    emoji: 'tennis-court.png',
    question: '¿Dónde juegas al tenis?',
    translation: 'Where do you play tennis?',
    options: ['la cancha de tenis', 'la pista de tenis', 'el campo de tenis'],
    correctAnswer: 'la cancha de tenis',
    hint: 'Tennis court - playing surface for tennis, can be clay, grass, or hard court',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'recreation_146',
    emoji: 'tennis.png',
    question: '¿Qué deporte juegas con raqueta?',
    translation: 'What sport do you play with a racket?',
    options: ['el tenis', 'el bádminton', 'el ping-pong'],
    correctAnswer: 'el tenis',
    hint: 'Tennis - racket sport played on court, Wimbledon is famous championship',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_147',
    emoji: 'trail-map.png',
    question: '¿Qué usas para no perderte en la montaña?',
    translation: 'What do you use to not get lost in the mountain?',
    options: ['el mapa de senderos', 'la brújula', 'el GPS'],
    correctAnswer: 'el mapa de senderos',
    hint: 'Trail map - shows hiking paths and terrain, essential for mountain navigation',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'recreation_148',
    emoji: 'trail-sign.png',
    question: '¿Qué te indica el camino en el sendero?',
    translation: 'What indicates the path on the trail?',
    options: ['la señal de sendero', 'el marcador', 'el cartel'],
    correctAnswer: 'la señal de sendero',
    hint: 'Trail sign - marker showing direction and distance on hiking paths',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'calm',
  },
  {
    id: 'recreation_149',
    emoji: 'walking-stick.png',
    question: '¿Qué usas para caminar en la montaña?',
    translation: 'What do you use to walk in the mountains?',
    options: ['el bastón de senderismo', 'el bastón de trekking', 'el palo de caminar'],
    correctAnswer: 'el bastón de senderismo',
    hint: 'Walking stick - hiking pole for stability and support on trails, reduces knee strain',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_150',
    emoji: 'water-bottle.png',
    question: '¿Qué llevas para mantenerte hidratado?',
    translation: 'What do you carry to stay hydrated?',
    options: ['la botella de agua', 'el termo', 'la cantimplora'],
    correctAnswer: 'la botella de agua',
    hint: 'Water bottle - container for carrying water during activities, essential for hydration',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'recreation_151',
    emoji: '🎯',
    question: '¿Qué juego es este?',
    translation: 'What game is this?',
    options: ['los dardos', 'el tiro al blanco', 'la diana'],
    correctAnswer: 'los dardos',
    hint: 'Darts - throwing game aiming at circular board, pub game',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_152',
    emoji: '🏐',
    question: '¿Qué deporte golpeas la pelota sobre una red?',
    translation: 'What sport do you hit the ball over a net?',
    options: ['el voleibol', 'el vóleibol', 'el volibol'],
    correctAnswer: 'el voleibol',
    hint: 'Volleyball - spike ball over net, beach or indoor version',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_153',
    emoji: '🤸',
    question: '¿Qué deporte incluye volteretas y acrobacias?',
    translation: 'What sport includes flips and acrobatics?',
    options: ['la gimnasia', 'la gimnasia artística', 'la acrobacia'],
    correctAnswer: 'la gimnasia',
    hint: 'Gymnastics - tumbling, flexibility, balance beam, floor routines',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_154',
    emoji: '🚴',
    question: '¿Qué deporte haces en bicicleta?',
    translation: 'What sport do you do on a bicycle?',
    options: ['el ciclismo', 'la bicicleta', 'el pedaleo'],
    correctAnswer: 'el ciclismo',
    hint: 'Cycling - bike racing, Tour de France famous, road or mountain',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_155',
    emoji: '🏃',
    question: '¿Qué haces en una maratón?',
    translation: 'What do you do in a marathon?',
    options: ['correr', 'trotar', 'esprintar'],
    correctAnswer: 'correr',
    hint: 'Running - marathon is 42.195km, long distance endurance race',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'recreation_156',
    emoji: '🏂',
    question: '¿Qué deporte de nieve usas una tabla?',
    translation: 'What snow sport do you use a board?',
    options: ['el snowboard', 'la tabla de nieve', 'el surf de nieve'],
    correctAnswer: 'el snowboard',
    hint: 'Snowboarding - single board for both feet, winter sport since 1960s',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_157',
    emoji: '🛹',
    question: '¿Qué tabla usas para hacer trucos en la calle?',
    translation: 'What board do you use to do tricks on the street?',
    options: ['la patineta', 'el monopatín', 'el skateboard'],
    correctAnswer: 'la patineta',
    hint: 'Skateboard - wheeled board for tricks, "monopatín" in some regions',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_158',
    emoji: '🏋️',
    question: '¿Qué deporte levantas pesas?',
    translation: 'What sport do you lift weights?',
    options: ['el levantamiento de pesas', 'el halterofilia', 'las pesas'],
    correctAnswer: 'el levantamiento de pesas',
    hint: 'Weightlifting - Olympic sport, lift barbell overhead, strength training',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'recreation_159',
    emoji: '🧘',
    question: '¿Qué ejercicio de meditación es tranquilo?',
    translation: 'What meditation exercise is calm?',
    options: ['el yoga', 'la meditación', 'el pilates'],
    correctAnswer: 'el yoga',
    hint: 'Yoga - ancient Indian practice, stretching and meditation, Sanskrit origin',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'recreation_160',
    emoji: 'camera.png',
    question: '¿Con qué grabas una película?',
    translation: 'What do you record a movie with?',
    options: ['la cámara', 'la cámara de cine', 'la videocámara'],
    correctAnswer: 'la cámara',
    hint: 'Camera - "cámara" from Latin "camera obscura", records video',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'recreation_161',
    emoji: 'pintar.png',
    question: '¿Qué haces cuando creas imágenes con colores?',
    translation: 'What do you do when you create images with colors?',
    options: ['pintar', 'dibujar', 'colorear'],
    correctAnswer: 'pintar',
    hint: 'Painting - "pintar" creates art with brush and colors, fine art',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_162',
    emoji: 'pincel.png',
    question: '¿Qué usas para pintar?',
    translation: 'What do you use to paint?',
    options: ['el pincel', 'la brocha', 'el cepillo'],
    correctAnswer: 'el pincel',
    hint: 'Paintbrush - tool with bristles for applying paint to canvas',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_163',
    emoji: '🖌️',
    question: '¿En qué superficie pintas un cuadro?',
    translation: 'On what surface do you paint a picture?',
    options: ['el lienzo', 'la tela', 'el canvas'],
    correctAnswer: 'el lienzo',
    hint: 'Canvas - stretched cloth surface for painting, used by artists',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_164',
    emoji: '🎣',
    question: '¿Qué hobby haces con caña en el río?',
    translation: 'What hobby do you do with a rod in the river?',
    options: ['pescar', 'la pesca', 'ir de pesca'],
    correctAnswer: 'pescar',
    hint: 'Fishing - catching fish with rod and bait, popular leisure activity',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'recreation_165',
    emoji: '🏕️',
    question: '¿Qué haces cuando duermes en tienda en la naturaleza?',
    translation: 'What do you do when you sleep in a tent in nature?',
    options: ['acampar', 'ir de camping', 'el campamento'],
    correctAnswer: 'acampar',
    hint: 'Camping - outdoor sleeping in tent, "campamento" is campsite',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_166',
    emoji: '🥾',
    question: '¿Qué actividad haces caminando en montañas?',
    translation: 'What activity do you do walking in mountains?',
    options: ['el senderismo', 'el hiking', 'el trekking'],
    correctAnswer: 'el senderismo',
    hint: 'Hiking - walking trails in nature, "sendero" means path or trail',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_167',
    emoji: '🧩',
    question: '¿Qué armas juntando piezas?',
    translation: 'What do you assemble putting pieces together?',
    options: ['el rompecabezas', 'el puzle', 'el puzzle'],
    correctAnswer: 'el rompecabezas',
    hint: 'Puzzle - "rompecabezas" literally means "head breaker", jigsaw pieces',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_168',
    emoji: '🎳',
    question: '¿Qué derribas con la bola de bolos?',
    translation: 'What do you knock down with a bowling ball?',
    options: ['los pinos', 'las botellas', 'los palitroques'],
    correctAnswer: 'los pinos',
    hint: 'Bowling pins - ten pins arranged in triangle, knock down for strike',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_169',
    emoji: '🪁',
    question: '¿Qué vuelas con viento usando un hilo?',
    translation: 'What do you fly with wind using a string?',
    options: ['la cometa', 'el papalote', 'el barrilete'],
    correctAnswer: 'la cometa',
    hint: 'Kite - "cometa" flies on string, "papalote" in Mexico',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_170',
    emoji: '🧶',
    question: '¿Qué haces con agujas e hilo?',
    translation: 'What do you do with needles and thread?',
    options: ['tejer', 'el tejido', 'la costura'],
    correctAnswer: 'tejer',
    hint: 'Knitting - "tejer" creates fabric from yarn with needles',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_171',
    emoji: '♟️',
    question: '¿Qué pieza pequeña usas en ajedrez?',
    translation: 'What small piece do you use in chess?',
    options: ['el peón', 'el alfil', 'el caballo'],
    correctAnswer: 'el peón',
    hint: 'Pawn - smallest chess piece, eight per player, moves forward only',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_172',
    emoji: '🀄',
    question: '¿Qué juego chino usa fichas con símbolos?',
    translation: 'What Chinese game uses tiles with symbols?',
    options: ['el mahjong', 'el mah-jong', 'el mahjongg'],
    correctAnswer: 'el mahjong',
    hint: 'Mahjong - Chinese tile game, 144 tiles with matching patterns',
    points: 15,
    category: 'recreation',
    difficulty: 'hard',
    emotion: 'pleased',
  },
  {
    id: 'recreation_173',
    emoji: '🎱',
    question: '¿Qué juego golpeas bolas con un taco?',
    translation: 'What game do you hit balls with a cue?',
    options: ['el billar', 'el pool', 'la mesa de billar'],
    correctAnswer: 'el billar',
    hint: 'Pool/billiards - use cue stick to hit balls into pockets',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_174',
    emoji: 'minigolf.png',
    question: '¿Qué deporte juegas con obstáculos pequeños?',
    translation: 'What sport do you play with small obstacles?',
    options: ['el minigolf', 'el golf en miniatura', 'el golf pequeño'],
    correctAnswer: 'el minigolf',
    hint: 'Miniature golf - fun putting game with creative obstacles and themes',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_175',
    emoji: '🏀',
    question: '¿Qué deporte metes la pelota en un aro?',
    translation: 'What sport do you put the ball in a hoop?',
    options: ['el baloncesto', 'el básquetbol', 'el basquetbol'],
    correctAnswer: 'el baloncesto',
    hint: 'Basketball - shoot ball through elevated hoop, invented 1891',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_176',
    emoji: '🎾',
    question: '¿Qué deporte se juega con raqueta?',
    translation: 'What sport is played with a racket?',
    options: ['el tenis', 'el bádminton', 'el ping pong'],
    correctAnswer: 'el tenis',
    hint: 'Tennis - hit ball over net with racket, singles or doubles',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_177',
    emoji: '⚾',
    question: '¿Qué deporte usas un bate?',
    translation: 'What sport do you use a bat?',
    options: ['el béisbol', 'el sófbol', 'el cricket'],
    correctAnswer: 'el béisbol',
    hint: 'Baseball - hit ball with bat, run bases, America\'s pastime',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_178',
    emoji: '🏈',
    question: '¿Qué deporte americano es físico?',
    translation: 'What American sport is physical?',
    options: ['el fútbol americano', 'el fútbol gridiron', 'el fútbol tackle'],
    correctAnswer: 'el fútbol americano',
    hint: 'American football - tackle sport with helmets and pads, oval ball',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_179',
    emoji: '🏉',
    question: '¿Qué deporte similar al fútbol americano se juega sin protección?',
    translation: 'What sport similar to American football is played without protection?',
    options: ['el rugby', 'el rugby union', 'el rugby league'],
    correctAnswer: 'el rugby',
    hint: 'Rugby - like American football but no helmets, originated in England',
    points: 15,
    category: 'recreation',
    difficulty: 'hard',
    emotion: 'excited',
  },
  {
    id: 'recreation_180',
    emoji: '🏏',
    question: '¿Qué deporte británico usa bate plano?',
    translation: 'What British sport uses a flat bat?',
    options: ['el cricket', 'el críquet', 'el rounders'],
    correctAnswer: 'el cricket',
    hint: 'Cricket - British bat-ball sport, flat bat, popular in Commonwealth',
    points: 15,
    category: 'recreation',
    difficulty: 'hard',
    emotion: 'pleased',
  },
  {
    id: 'recreation_181',
    emoji: '🏒',
    question: '¿Qué deporte se juega en hielo?',
    translation: 'What sport is played on ice?',
    options: ['el hockey', 'el hockey sobre hielo', 'el hockey de campo'],
    correctAnswer: 'el hockey',
    hint: 'Ice hockey - fast skating sport with puck, popular in Canada',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_182',
    emoji: '🏸',
    question: '¿Qué deporte golpeas un volante con raqueta?',
    translation: 'What sport do you hit a shuttlecock with a racket?',
    options: ['el bádminton', 'el badminton', 'el volante'],
    correctAnswer: 'el bádminton',
    hint: 'Badminton - hit shuttlecock over net, fastest racket sport',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_183',
    emoji: '🥊',
    question: '¿Qué deporte de combate usa guantes?',
    translation: 'What combat sport uses gloves?',
    options: ['el boxeo', 'el pugilismo', 'el box'],
    correctAnswer: 'el boxeo',
    hint: 'Boxing - punch with gloved fists, combat sport with rounds',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_184',
    emoji: '🥋',
    question: '¿Qué arte marcial usa cinturones de colores?',
    translation: 'What martial art uses colored belts?',
    options: ['el karate', 'el judo', 'el taekwondo'],
    correctAnswer: 'el karate',
    hint: 'Karate - Japanese martial art, belt colors show skill level',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'recreation_185',
    emoji: '⛷️',
    question: '¿Qué deporte haces en la nieve?',
    translation: 'What sport do you do in the snow?',
    options: ['esquiar', 'el esquí', 'esquí alpino'],
    correctAnswer: 'esquiar',
    hint: 'Skiing - glide on snow with skis, downhill or cross-country',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'recreation_186',
    emoji: '⛸️',
    question: '¿Qué haces con patines en hielo?',
    translation: 'What do you do with ice skates?',
    options: ['patinar', 'el patinaje', 'deslizarse'],
    correctAnswer: 'patinar',
    hint: 'Ice skating - glide on frozen surface, figure skating or hockey',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'recreation_187',
    emoji: '🤽',
    question: '¿Qué deporte de equipo se juega en piscina?',
    translation: 'What team sport is played in a pool?',
    options: ['el waterpolo', 'el polo acuático', 'el water polo'],
    correctAnswer: 'el waterpolo',
    hint: 'Water polo - team handball in pool, treading water while playing',
    points: 15,
    category: 'recreation',
    difficulty: 'hard',
    emotion: 'excited',
  },
  {
    id: 'recreation_188',
    emoji: '🏋️',
    question: '¿Qué deporte levantas pesas?',
    translation: 'What sport do you lift weights?',
    options: ['el levantamiento de pesas', 'el halterofilia', 'las pesas'],
    correctAnswer: 'el levantamiento de pesas',
    hint: 'Weightlifting - Olympic sport, lift barball overhead, strength training',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'recreation_189',
    emoji: '⚽',
    question: '¿Qué deporte es este?',
    translation: 'What sport is this?',
    options: ['el fútbol', 'el balompié', 'el soccer'],
    correctAnswer: 'el fútbol',
    hint: 'Soccer/football - world\'s most popular sport, "balompié" also used',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'recreation_190',
    emoji: '🎨',
    question: '¿Qué actividad es esta?',
    translation: 'What activity is this?',
    options: ['la pintura', 'el dibujo', 'el arte'],
    correctAnswer: 'la pintura',
    hint: 'Painting - visual art with colors, "pintar" to paint on canvas',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'recreation_191',
    emoji: 'zoológico.png',
    question: '¿Dónde vas para ver animales exóticos?',
    translation: 'Where do you go to see exotic animals?',
    options: ['el zoológico', 'el zoo', 'el parque zoológico'],
    correctAnswer: 'el zoológico',
    hint: 'Zoo - place where exotic animals are kept for public viewing',
    points: 10,
    category: 'recreation',
    difficulty: 'medium',
    emotion: 'excited',
  },

    {
    id: 'recreation_192',
    emoji: '🏕️',
    question: '¿Qué haces cuando duermes en tienda en la naturaleza?',
    translation: 'What do you do when you sleep in a tent in nature?',
    options: ['acampar', 'ir de camping', 'el campamento'],
    correctAnswer: 'acampar',
    hint: 'Camping - outdoor sleeping in tent, "campamento" is campsite',
    points: 5,
    category: 'recreation',
    difficulty: 'easy',
    emotion: 'excited',
  },

];
