/**
 * RESTAURANT & DINING Category Questions
 * Category: restaurant
 */

export const restaurantQuestions = [
  // Basic Restaurant Phrases (1-15)
  {
    id: 'restaurant_001',
    emoji: '🍽️',
    question: '¿Qué dices al mesero para pedir?',
    options: ['quisiera', 'necesito', 'quiero'],
    correctAnswer: 'quisiera',
    hint: 'Polite way to order - "I would like"',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_002',
    emoji: '📋',
    question: '¿Qué necesitas para ver las opciones de comida?',
    options: ['el menú', 'la cuenta', 'el plato'],
    correctAnswer: 'el menú',
    hint: 'Menu - list of food options, also called "la carta"',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_003',
    emoji: '👨‍🍳',
    question: '¿Quién te sirve en un restaurante?',
    options: ['el mesero', 'el cocinero', 'el gerente'],
    correctAnswer: 'el mesero',
    hint: 'Waiter/server - also called "camarero" in Spain',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_004',
    emoji: '💰',
    question: '¿Qué pides al final de la comida?',
    options: ['la cuenta', 'el menú', 'el postre'],
    correctAnswer: 'la cuenta',
    hint: 'The bill/check - "la cuenta, por favor"',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_005',
    emoji: '🪑',
    question: '¿Qué pides cuando llegas al restaurante?',
    options: ['una mesa', 'una silla', 'un plato'],
    correctAnswer: 'una mesa',
    hint: 'Table - "una mesa para dos personas"',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_006',
    emoji: '📅',
    question: '¿Qué haces para asegurar una mesa?',
    options: ['hacer una reserva', 'pagar una cuenta', 'leer el menú'],
    correctAnswer: 'hacer una reserva',
    hint: 'Make a reservation - book ahead',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_007',
    emoji: '💵',
    question: '¿Qué dejas para el mesero por buen servicio?',
    options: ['la propina', 'la cuenta', 'el cambio'],
    correctAnswer: 'la propina',
    hint: 'Tip - gratuity for service',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_008',
    emoji: '🍷',
    question: '¿Qué pides primero para tomar?',
    options: ['una bebida', 'un postre', 'la cuenta'],
    correctAnswer: 'una bebida',
    hint: 'Drink/beverage - first thing ordered',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_009',
    emoji: '🥗',
    question: '¿Qué comes antes del plato principal?',
    options: ['el entrante', 'el postre', 'la cuenta'],
    correctAnswer: 'el entrante',
    hint: 'Appetizer/starter - also called "aperitivo"',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_010',
    emoji: '🍰',
    question: '¿Qué comes después del plato principal?',
    options: ['el postre', 'el entrante', 'la sopa'],
    correctAnswer: 'el postre',
    hint: 'Dessert - sweet ending to meal',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_011',
    emoji: '🍴',
    question: '¿Con qué comes?',
    options: ['los cubiertos', 'las servilletas', 'los vasos'],
    correctAnswer: 'los cubiertos',
    hint: 'Cutlery/silverware - fork, knife, spoon',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_014',
    emoji: '🥤',
    question: '¿De qué tomas agua?',
    options: ['del vaso', 'del plato', 'del tenedor'],
    correctAnswer: 'del vaso',
    hint: 'Glass - drinking vessel',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_015',
    emoji: '🍽️',
    question: '¿Dónde sirven tu comida?',
    options: ['en el plato', 'en el vaso', 'en la servilleta'],
    correctAnswer: 'en el plato',
    hint: 'Plate/dish - where food is served',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },

  // Ordering Food (16-30)
  {
    id: 'restaurant_016',
    emoji: '🍔',
    question: '¿Cómo pides una hamburguesa?',
    options: ['quisiera una hamburguesa', 'necesito un plato', 'tomo la cuenta'],
    correctAnswer: 'quisiera una hamburguesa',
    hint: 'Polite ordering phrase',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_017',
    emoji: '🥩',
    question: '¿Cómo te gusta la carne?',
    options: ['bien cocida', 'cruda', 'quemada'],
    correctAnswer: 'bien cocida',
    hint: 'Well done - level of cooking',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_018',
    emoji: '🍕',
    question: '¿Qué dices cuando quieres pizza?',
    options: ['una pizza, por favor', 'la cuenta, por favor', 'el menú, por favor'],
    correctAnswer: 'una pizza, por favor',
    hint: 'Polite way to order pizza',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_019',
    emoji: '🥙',
    question: '¿Qué comida mexicana pides?',
    options: ['un taco', 'una paella', 'un sushi'],
    correctAnswer: 'un taco',
    hint: 'Mexican dish with tortilla',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_020',
    emoji: '🍜',
    question: '¿Qué plato líquido pides cuando hace frío?',
    options: ['una sopa', 'un helado', 'una ensalada'],
    correctAnswer: 'una sopa',
    hint: 'Soup - hot liquid dish',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_021',
    emoji: '🥗',
    question: '¿Qué pides si quieres comer vegetales?',
    options: ['una ensalada', 'un bistec', 'un pescado'],
    correctAnswer: 'una ensalada',
    hint: 'Salad - vegetables and greens',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_022',
    emoji: '🍝',
    question: '¿Qué comida italiana con salsa pides?',
    options: ['pasta', 'arroz', 'pan'],
    correctAnswer: 'pasta',
    hint: 'Italian noodles',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_023',
    emoji: '🍚',
    question: '¿Qué acompaña muchos platos latinos?',
    options: ['el arroz', 'el helado', 'la sopa'],
    correctAnswer: 'el arroz',
    hint: 'Rice - staple side dish',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_024',
    emoji: '🥖',
    question: '¿Qué te dan gratis en muchos restaurantes?',
    options: ['el pan', 'el postre', 'la bebida'],
    correctAnswer: 'el pan',
    hint: 'Bread - often complimentary',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_025',
    emoji: '🧈',
    question: '¿Qué le pones al pan?',
    options: ['la mantequilla', 'el agua', 'la sal'],
    correctAnswer: 'la mantequilla',
    hint: 'Butter - spread for bread',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_026',
    emoji: '🍟',
    question: '¿Qué acompañamiento pides con hamburguesa?',
    options: ['papas fritas', 'helado', 'sopa'],
    correctAnswer: 'papas fritas',
    hint: 'French fries - "patatas fritas" in Spain',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_027',
    emoji: '🐟',
    question: '¿Qué proteína del mar pides?',
    options: ['el pescado', 'el pollo', 'la carne'],
    correctAnswer: 'el pescado',
    hint: 'Fish - seafood option',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_028',
    emoji: '🦐',
    question: '¿Qué mariscos pequeños pides?',
    options: ['los camarones', 'las galletas', 'los huevos'],
    correctAnswer: 'los camarones',
    hint: 'Shrimp - "gambas" in Spain',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_029',
    emoji: '🍗',
    question: '¿Qué carne de ave pides?',
    options: ['el pollo', 'el pescado', 'el cerdo'],
    correctAnswer: 'el pollo',
    hint: 'Chicken - common meat option',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_030',
    emoji: '🥩',
    question: '¿Qué carne roja pides?',
    options: ['la carne de res', 'el pescado', 'el pollo'],
    correctAnswer: 'la carne de res',
    hint: 'Beef - red meat',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },

  // Drinks (31-45)
  {
    id: 'restaurant_031',
    emoji: '💧',
    question: '¿Qué bebida básica pides?',
    options: ['agua', 'vino', 'cerveza'],
    correctAnswer: 'agua',
    hint: 'Water - most basic drink',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_032',
    emoji: '🥤',
    question: '¿Qué bebida con gas pides?',
    options: ['un refresco', 'un café', 'un té'],
    correctAnswer: 'un refresco',
    hint: 'Soft drink/soda - carbonated',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_033',
    emoji: '☕',
    question: '¿Qué bebida caliente pides después de comer?',
    options: ['un café', 'un jugo', 'una cerveza'],
    correctAnswer: 'un café',
    hint: 'Coffee - hot beverage',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_034',
    emoji: '🍵',
    question: '¿Qué otra bebida caliente pides?',
    options: ['un té', 'un jugo', 'una leche'],
    correctAnswer: 'un té',
    hint: 'Tea - hot beverage alternative',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_035',
    emoji: '🍷',
    question: '¿Qué bebida alcohólica de uvas pides?',
    options: ['vino', 'cerveza', 'agua'],
    correctAnswer: 'vino',
    hint: 'Wine - made from grapes',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_036',
    emoji: '🍺',
    question: '¿Qué bebida alcohólica fría pides?',
    options: ['una cerveza', 'un café', 'un té'],
    correctAnswer: 'una cerveza',
    hint: 'Beer - cold alcoholic drink',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_037',
    emoji: '🧃',
    question: '¿Qué bebida de frutas pides?',
    options: ['un jugo', 'un café', 'una cerveza'],
    correctAnswer: 'un jugo',
    hint: 'Juice - "zumo" in Spain',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_038',
    emoji: '🥛',
    question: '¿Qué bebida blanca pides con cereal?',
    options: ['leche', 'agua', 'café'],
    correctAnswer: 'leche',
    hint: 'Milk - dairy drink',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_039',
    emoji: '🧊',
    question: '¿Qué le pides al mesero para enfriar tu bebida?',
    options: ['hielo', 'sal', 'azúcar'],
    correctAnswer: 'hielo',
    hint: 'Ice - to cool drinks',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_040',
    emoji: '🍋',
    question: '¿Qué le pones al agua para sabor?',
    options: ['limón', 'sal', 'mantequilla'],
    correctAnswer: 'limón',
    hint: 'Lemon - citrus flavor',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_041',
    emoji: '🍹',
    question: '¿Qué bebida tropical pides en la playa?',
    options: ['un cóctel', 'un café', 'una sopa'],
    correctAnswer: 'un cóctel',
    hint: 'Cocktail - mixed drink',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_042',
    emoji: '🥃',
    question: '¿Qué licor fuerte pides?',
    options: ['whisky', 'jugo', 'agua'],
    correctAnswer: 'whisky',
    hint: 'Whiskey - strong spirit',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_043',
    emoji: '🍾',
    question: '¿Qué bebida especial pides para celebrar?',
    options: ['champán', 'agua', 'café'],
    correctAnswer: 'champán',
    hint: 'Champagne - celebration drink',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_044',
    emoji: '🧋',
    question: '¿Qué bebida con burbujas es popular en Asia?',
    options: ['té de burbujas', 'café', 'cerveza'],
    correctAnswer: 'té de burbujas',
    hint: 'Bubble tea - boba drink',
    points: 15,
    category: 'restaurant',
    difficulty: 'hard',
  },
  {
    id: 'restaurant_045',
    emoji: '☕',
    question: '¿Cómo pides café con leche?',
    options: ['un café con leche', 'un café solo', 'un té con limón'],
    correctAnswer: 'un café con leche',
    hint: 'Coffee with milk - popular breakfast drink',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },

  // Desserts (46-55)
  {
    id: 'restaurant_046',
    emoji: '🍰',
    question: '¿Qué postre dulce y esponjoso pides?',
    options: ['el pastel', 'la sopa', 'la ensalada'],
    correctAnswer: 'el pastel',
    hint: 'Cake - sweet dessert',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_047',
    emoji: '🍦',
    question: '¿Qué postre frío pides en verano?',
    options: ['el helado', 'el café', 'la sopa'],
    correctAnswer: 'el helado',
    hint: 'Ice cream - frozen dessert',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_048',
    emoji: '🍮',
    question: '¿Qué postre cremoso español pides?',
    options: ['el flan', 'la pizza', 'la sopa'],
    correctAnswer: 'el flan',
    hint: 'Flan - caramel custard',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_049',
    emoji: '🍪',
    question: '¿Qué postre crujiente y dulce pides con café?',
    options: ['las galletas', 'las papas', 'las verduras'],
    correctAnswer: 'las galletas',
    hint: 'Cookies - sweet baked treats',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_050',
    emoji: '🥧',
    question: '¿Qué postre con frutas pides?',
    options: ['el pie', 'el arroz', 'el pescado'],
    correctAnswer: 'el pie',
    hint: 'Pie - "tarta" or "pastel" with fruit',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_051',
    emoji: '🍫',
    question: '¿Qué postre de cacao pides?',
    options: ['el chocolate', 'el queso', 'el pan'],
    correctAnswer: 'el chocolate',
    hint: 'Chocolate - cocoa dessert',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_052',
    emoji: '🧁',
    question: '¿Qué postre pequeño individual pides?',
    options: ['el cupcake', 'la pizza', 'la sopa'],
    correctAnswer: 'el cupcake',
    hint: 'Cupcake - small cake, "magdalena" in Spanish',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_053',
    emoji: '🍩',
    question: '¿Qué postre frito y redondo pides?',
    options: ['la dona', 'la ensalada', 'la sopa'],
    correctAnswer: 'la dona',
    hint: 'Donut - "donas" in Latin America',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_054',
    emoji: '🍨',
    question: '¿Qué helado con frutas y crema pides?',
    options: ['el sundae', 'el café', 'la sopa'],
    correctAnswer: 'el sundae',
    hint: 'Sundae - ice cream with toppings',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_055',
    emoji: '🍡',
    question: '¿Qué postre en palitos pides?',
    options: ['los dulces', 'las papas', 'los vegetales'],
    correctAnswer: 'los dulces',
    hint: 'Sweets/candy - "golosinas"',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },

  // Restaurant Types & Situations (56-70)
  {
    id: 'restaurant_056',
    emoji: '🍕',
    question: '¿A qué restaurante vas para pizza?',
    options: ['la pizzería', 'la cafetería', 'la panadería'],
    correctAnswer: 'la pizzería',
    hint: 'Pizzeria - pizza restaurant',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_057',
    emoji: '☕',
    question: '¿Dónde tomas café y pastel?',
    options: ['la cafetería', 'la carnicería', 'la pescadería'],
    correctAnswer: 'la cafetería',
    hint: 'Café - coffee shop',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_058',
    emoji: '🍔',
    question: '¿Qué tipo de restaurante sirve comida rápida?',
    options: ['comida rápida', 'comida gourmet', 'comida casera'],
    correctAnswer: 'comida rápida',
    hint: 'Fast food - quick service',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_059',
    emoji: '🍱',
    question: '¿Qué restaurante sirve comida para llevar?',
    options: ['comida para llevar', 'comida para aquí', 'comida para mañana'],
    correctAnswer: 'comida para llevar',
    hint: 'Takeout/to-go food',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_060',
    emoji: '🏪',
    question: '¿Dónde comes dentro del restaurante?',
    options: ['para comer aquí', 'para llevar', 'para mañana'],
    correctAnswer: 'para comer aquí',
    hint: 'Dine in - eat at restaurant',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_061',
    emoji: '🚗',
    question: '¿Dónde pides sin salir del carro?',
    options: ['servicio al auto', 'servicio a casa', 'servicio a pie'],
    correctAnswer: 'servicio al auto',
    hint: 'Drive-through - car service',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_062',
    emoji: '🏠',
    question: '¿Qué servicio trae comida a tu casa?',
    options: ['entrega a domicilio', 'comida para llevar', 'reservación'],
    correctAnswer: 'entrega a domicilio',
    hint: 'Delivery - food brought to you',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_063',
    emoji: '🍽️',
    question: '¿Qué tipo de restaurante es elegante?',
    options: ['restaurante fino', 'comida rápida', 'cafetería'],
    correctAnswer: 'restaurante fino',
    hint: 'Fine dining - upscale restaurant',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_064',
    emoji: '🎉',
    question: '¿Dónde comes mucha variedad pagando una vez?',
    options: ['el buffet', 'la pizzería', 'la cafetería'],
    correctAnswer: 'el buffet',
    hint: 'Buffet - all-you-can-eat',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_065',
    emoji: '🍜',
    question: '¿Qué restaurante sirve comida asiática?',
    options: ['restaurante asiático', 'restaurante mexicano', 'restaurante italiano'],
    correctAnswer: 'restaurante asiático',
    hint: 'Asian restaurant - serves Asian cuisine',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_066',
    emoji: '🌮',
    question: '¿Qué restaurante sirve tacos y burritos?',
    options: ['restaurante mexicano', 'restaurante chino', 'restaurante francés'],
    correctAnswer: 'restaurante mexicano',
    hint: 'Mexican restaurant',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_067',
    emoji: '🍝',
    question: '¿Qué restaurante sirve pasta y pizza?',
    options: ['restaurante italiano', 'restaurante mexicano', 'restaurante chino'],
    correctAnswer: 'restaurante italiano',
    hint: 'Italian restaurant',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_068',
    emoji: '🥘',
    question: '¿Qué restaurante sirve paella?',
    options: ['restaurante español', 'restaurante mexicano', 'restaurante chino'],
    correctAnswer: 'restaurante español',
    hint: 'Spanish restaurant',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_069',
    emoji: '🍣',
    question: '¿Qué restaurante sirve sushi?',
    options: ['restaurante japonés', 'restaurante mexicano', 'restaurante italiano'],
    correctAnswer: 'restaurante japonés',
    hint: 'Japanese restaurant',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_070',
    emoji: '🥖',
    question: '¿Qué restaurante sirve croissants?',
    options: ['restaurante francés', 'restaurante mexicano', 'restaurante chino'],
    correctAnswer: 'restaurante francés',
    hint: 'French restaurant',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },

  // Dining Preferences & Requests (71-85)
  {
    id: 'restaurant_071',
    emoji: '🌱',
    question: '¿Qué pides si no comes carne?',
    options: ['comida vegetariana', 'comida con carne', 'solo carne'],
    correctAnswer: 'comida vegetariana',
    hint: 'Vegetarian food - no meat',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_072',
    emoji: '🥜',
    question: '¿Qué le dices al mesero si tienes alergia?',
    options: ['soy alérgico a', 'me gusta', 'quisiera más'],
    correctAnswer: 'soy alérgico a',
    hint: 'Allergic to - important health info',
    points: 15,
    category: 'restaurant',
    difficulty: 'hard',
  },
  {
    id: 'restaurant_073',
    emoji: '🌶️',
    question: '¿Qué dices si no quieres comida picante?',
    options: ['sin picante', 'muy picante', 'extra picante'],
    correctAnswer: 'sin picante',
    hint: 'No spicy - mild preference',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_074',
    emoji: '🧂',
    question: '¿Qué dices si no quieres sal?',
    options: ['sin sal', 'con sal', 'mucha sal'],
    correctAnswer: 'sin sal',
    hint: 'Without salt - dietary preference',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_075',
    emoji: '🔥',
    question: '¿Cómo pides la comida caliente?',
    options: ['bien caliente', 'frío', 'congelado'],
    correctAnswer: 'bien caliente',
    hint: 'Very hot - temperature request',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_076',
    emoji: '❄️',
    question: '¿Cómo pides la bebida muy fría?',
    options: ['bien fría', 'caliente', 'sin hielo'],
    correctAnswer: 'bien fría',
    hint: 'Very cold - temperature request',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_077',
    emoji: '🍴',
    question: '¿Qué pides si necesitas tenedor?',
    options: ['un tenedor', 'un vaso', 'un plato'],
    correctAnswer: 'un tenedor',
    hint: 'Fork - eating utensil',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_078',
    emoji: '🥄',
    question: '¿Qué pides para comer sopa?',
    options: ['una cuchara', 'un tenedor', 'un cuchillo'],
    correctAnswer: 'una cuchara',
    hint: 'Spoon - for liquid foods',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_079',
    emoji: '🔪',
    question: '¿Qué pides para cortar carne?',
    options: ['un cuchillo', 'una cuchara', 'un vaso'],
    correctAnswer: 'un cuchillo',
    hint: 'Knife - for cutting',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_080',
    emoji: '🧻',
    question: '¿Qué usas para limpiarte la boca?',
    options: ['la servilleta', 'el menú', 'el plato'],
    correctAnswer: 'la servilleta',
    hint: 'Napkin - for cleaning',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_081',
    emoji: '🥤',
    question: '¿Qué pides para tomar tu refresco?',
    options: ['un popote', 'un plato', 'un tenedor'],
    correctAnswer: 'un popote',
    hint: 'Straw - "pajita" in Spain, "bombilla" in some regions',
    points: 15,
    category: 'restaurant',
    difficulty: 'hard',
  },
  {
    id: 'restaurant_082',
    emoji: '📦',
    question: '¿Qué pides para llevar lo que sobra?',
    options: ['una caja para llevar', 'otro plato', 'la cuenta'],
    correctAnswer: 'una caja para llevar',
    hint: 'Takeout box - "doggy bag"',
    points: 15,
    category: 'restaurant',
    difficulty: 'hard',
  },
  {
    id: 'restaurant_083',
    emoji: '🧊',
    question: '¿Qué dices si no quieres hielo?',
    options: ['sin hielo', 'con hielo', 'mucho hielo'],
    correctAnswer: 'sin hielo',
    hint: 'Without ice - drink preference',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_084',
    emoji: '🍋',
    question: '¿Qué pides para tu té?',
    options: ['limón', 'carne', 'pescado'],
    correctAnswer: 'limón',
    hint: 'Lemon - for tea',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_085',
    emoji: '🍯',
    question: '¿Qué le pones al té para endulzar?',
    options: ['miel', 'sal', 'pimienta'],
    correctAnswer: 'miel',
    hint: 'Honey - natural sweetener',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },

  // Final phrases & situations (86-100)
  {
    id: 'restaurant_086',
    emoji: '👍',
    question: '¿Qué dices cuando la comida está deliciosa?',
    options: ['está delicioso', 'está horrible', 'está frío'],
    correctAnswer: 'está delicioso',
    hint: 'It\'s delicious - compliment',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_087',
    emoji: '😋',
    question: '¿Qué dices cuando tienes hambre?',
    options: ['tengo hambre', 'tengo sed', 'tengo sueño'],
    correctAnswer: 'tengo hambre',
    hint: 'I\'m hungry - need food',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_088',
    emoji: '🥤',
    question: '¿Qué dices cuando tienes sed?',
    options: ['tengo sed', 'tengo hambre', 'tengo frío'],
    correctAnswer: 'tengo sed',
    hint: 'I\'m thirsty - need drink',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_089',
    emoji: '😊',
    question: '¿Qué dices al mesero al final?',
    options: ['gracias', 'hola', 'adiós'],
    correctAnswer: 'gracias',
    hint: 'Thank you - show appreciation',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_090',
    emoji: '🙏',
    question: '¿Qué dices para ser cortés al pedir?',
    options: ['por favor', 'ahora', 'nunca'],
    correctAnswer: 'por favor',
    hint: 'Please - polite request',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_091',
    emoji: '⏰',
    question: '¿A qué hora comes en la mañana?',
    options: ['el desayuno', 'el almuerzo', 'la cena'],
    correctAnswer: 'el desayuno',
    hint: 'Breakfast - morning meal',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_092',
    emoji: '🌞',
    question: '¿A qué hora comes a mediodía?',
    options: ['el almuerzo', 'el desayuno', 'la cena'],
    correctAnswer: 'el almuerzo',
    hint: 'Lunch - midday meal',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_093',
    emoji: '🌙',
    question: '¿A qué hora comes en la noche?',
    options: ['la cena', 'el desayuno', 'el almuerzo'],
    correctAnswer: 'la cena',
    hint: 'Dinner - evening meal',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_094',
    emoji: '🔄',
    question: '¿Qué dices para pedir más?',
    options: ['más, por favor', 'menos, por favor', 'nada más'],
    correctAnswer: 'más, por favor',
    hint: 'More, please - want additional',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_095',
    emoji: '✋',
    question: '¿Qué dices cuando no quieres más?',
    options: ['no más, gracias', 'más, por favor', 'todo'],
    correctAnswer: 'no más, gracias',
    hint: 'No more, thanks - satisfied',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_096',
    emoji: '🙋',
    question: '¿Qué dices para llamar al mesero?',
    options: ['disculpe', 'adiós', 'hola'],
    correctAnswer: 'disculpe',
    hint: 'Excuse me - get attention',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_097',
    emoji: '❓',
    question: '¿Qué preguntas para saber opciones?',
    options: ['¿qué me recomienda?', '¿cuánto cuesta?', '¿dónde está el baño?'],
    correctAnswer: '¿qué me recomienda?',
    hint: 'What do you recommend? - ask for suggestion',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_098',
    emoji: '💵',
    question: '¿Qué preguntas para saber el precio?',
    options: ['¿cuánto cuesta?', '¿qué me recomienda?', '¿dónde está?'],
    correctAnswer: '¿cuánto cuesta?',
    hint: 'How much does it cost? - price question',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_099',
    emoji: '🚻',
    question: '¿Qué preguntas para encontrar el baño?',
    options: ['¿dónde está el baño?', '¿cuánto cuesta?', '¿qué me recomienda?'],
    correctAnswer: '¿dónde está el baño?',
    hint: 'Where is the bathroom? - important question',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_100',
    emoji: '🎊',
    question: '¿Qué dices para disfrutar la comida?',
    options: ['¡buen provecho!', '¡adiós!', '¡hola!'],
    correctAnswer: '¡buen provecho!',
    hint: 'Enjoy your meal! - dining greeting',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
  {
    id: 'restaurant_101',
    emoji: '🚬',
    question: '¿Qué está prohibido en muchos restaurantes?',
    options: ['fumar', 'comer', 'beber'],
    correctAnswer: 'fumar',
    hint: 'Smoking - not allowed in most restaurants, "prohibido fumar"',
    points: 5,
    category: 'restaurant',
    difficulty: 'easy',
  },
  {
    id: 'restaurant_102',
    emoji: '🏮',
    question: '¿Qué ilumina y decora un restaurante elegante?',
    options: ['las lámparas', 'las mesas', 'los platos'],
    correctAnswer: 'las lámparas',
    hint: 'Lamps/lanterns - decorative lighting creates ambiance in fancy restaurants',
    points: 10,
    category: 'restaurant',
    difficulty: 'medium',
  },
];
