/**
 * SHOPPING Category Questions
 * Category: shopping
 */

export const shoppingQuestions = [
{
    id: 'shopping_001',
    emoji: '👕',
    question: '¿Qué prenda es esta?',
    translation: 'What garment is this?',
    options: ['la camisa', 'la camiseta', 'la blusa'],
    correctAnswer: 'la camisa',
    hint: 'Top with buttons and collar',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_002',
    emoji: '👟',
    question: '¿Qué calzado es este?',
    translation: 'What footwear is this?',
    options: ['el zapato', 'el tenis', 'la zapatilla'],
    correctAnswer: 'el zapato',
    hint: 'Footwear - "zapato" is masculine singular, "zapatos" for the pair',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_003',
    emoji: '👜',
    question: '¿Qué accesorio es este?',
    translation: 'What accessory is this?',
    options: ['la bolsa', 'el bolso', 'la cartera'],
    correctAnswer: 'la bolsa',
    hint: 'Bag - "bolsa" in Latin America, "bolso" in Spain for purse/handbag',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'shopping_004',
    emoji: '🕶️',
    question: '¿Qué son estos?',
    translation: 'What accessory is this?',
    options: ['las gafas de sol', 'los anteojos de sol', 'los lentes oscuros'],
    correctAnswer: 'las gafas de sol',
    hint: 'Protect eyes from bright light',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_005',
    emoji: '👖',
    question: '¿Qué prenda es esta?',
    translation: 'What garment is this?',
    options: ['el pantalón', 'los jeans', 'los vaqueros'],
    correctAnswer: 'el pantalón',
    hint: 'Pants - singular in Spanish, unlike English ("pants" vs "el pantalón")',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_006',
    emoji: '🧥',
    question: '¿Qué prenda es esta?',
    translation: 'What garment is this?',
    options: ['la chaqueta', 'el abrigo', 'la cazadora'],
    correctAnswer: 'la chaqueta',
    hint: 'Wear over other clothes when cool',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_007',
    emoji: '👗',
    question: '¿Qué prenda es esta?',
    translation: 'What garment is this?',
    options: ['el vestido', 'la falda', 'el traje'],
    correctAnswer: 'el vestido',
    hint: 'One-piece outfit for women',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'shopping_008',
    emoji: 'sombrero.png',
    question: '¿Cómo se llama este accesorio para la cabeza?',
    translation: 'What is this head accessory called?',
    options: ['el sombrero', 'la gorra', 'el gorro'],
    correctAnswer: 'el sombrero',
    hint: 'Protects your head from sun',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_009',
    emoji: '🧤',
    question: '¿Qué son estos?',
    translation: 'What accessory is this?',
    options: ['los guantes', 'los mitones', 'las manoplas'],
    correctAnswer: 'los guantes',
    hint: 'Keep your hands warm',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_010',
    emoji: '🧣',
    question: '¿Qué prenda usas para el cuello?',
    translation: 'What garment do you use for the neck?',
    options: ['la bufanda', 'la chalina', 'el chal'],
    correctAnswer: 'la bufanda',
    hint: 'Wraps around neck for warmth',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_011',
    emoji: 'corbata.png',
    question: '¿Qué accesorio formal llevas con traje?',
    translation: 'What formal accessory do you wear with a suit?',
    options: ['la corbata', 'la pajarita', 'el pañuelo'],
    correctAnswer: 'la corbata',
    hint: 'Formal neck accessory for suits',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'shopping_012',
    emoji: '👞',
    question: '¿Qué tipo de zapato es este?',
    translation: 'What type of shoe is this?',
    options: ['el zapato formal', 'el zapato de vestir', 'el mocasín'],
    correctAnswer: 'el zapato formal',
    hint: 'Dress shoes - "zapato de vestir" for business or formal occasions',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_013',
    emoji: '🩴',
    question: '¿Qué son estos?',
    translation: 'What are these?',
    options: ['las sandalias', 'las chanclas', 'las ojotas'],
    correctAnswer: 'las sandalias',
    hint: 'Sandals - open footwear for warm weather, "chanclas" for flip-flops',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'shopping_014',
    emoji: '👘',
    question: '¿Qué tipo de ropa es esta?',
    translation: 'What type of clothing is this?',
    options: ['el kimono', 'el yukata', 'el hanbok'],
    correctAnswer: 'el kimono',
    hint: 'Traditional Japanese robe - "kimono" used globally, stays masculine in Spanish',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'surprised',
  },
  {
    id: 'shopping_015',
    emoji: '🎒',
    question: '¿Qué bolsa llevas en la espalda?',
    translation: 'What bag do you carry on your back?',
    options: ['la mochila', 'el morral', 'el macuto'],
    correctAnswer: 'la mochila',
    hint: 'Bag you wear on your back',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_016',
    emoji: '⌚',
    question: '¿Qué usas para ver la hora?',
    translation: 'What do you use to see the time?',
    options: ['el reloj', 'el cronómetro', 'el cronógrafo'],
    correctAnswer: 'el reloj',
    hint: 'Tells you what time it is',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_017',
    emoji: '💍',
    question: '¿Qué joya llevas en el dedo?',
    translation: 'What jewelry do you wear on your finger?',
    options: ['el anillo', 'la sortija', 'el aro'],
    correctAnswer: 'el anillo',
    hint: 'Jewelry for your finger',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_018',
    emoji: '🧢',
    question: '¿Qué tipo de sombrero deportivo es este?',
    translation: 'What type of sports hat is this?',
    options: ['la gorra', 'la visera', 'el casquete'],
    correctAnswer: 'la gorra',
    hint: 'Baseball cap - "gorra" has a visor, "sombrero" has a brim all around',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_019',
    emoji: '👚',
    question: '¿Qué prenda es esta?',
    translation: 'What garment is this?',
    options: ['la blusa', 'la camisa', 'la camiseta'],
    correctAnswer: 'la blusa',
    hint: 'Blouse - feminine top, usually lighter and more decorative than "camisa"',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_020',
    emoji: '🥾',
    question: '¿Qué tipo de calzado es este?',
    translation: 'What type of footwear is this?',
    options: ['las botas', 'los botines', 'las botas altas'],
    correctAnswer: 'las botas',
    hint: 'Tall shoes for feet and ankles',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },

  // More Clothing Items (35 questions)
  {
    id: 'shopping_021',
    emoji: 'audífonos.png',
    question: '¿Qué usas en los oídos para escuchar música?',
    translation: 'What do you wear in your ears to listen to music?',
    options: ['los audífonos', 'los auriculares', 'los cascos'],
    correctAnswer: 'los audífonos',
    hint: 'Earbuds - small headphones worn in ears, "audífonos" in Latin America',
    points: 10,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'shopping_022',
    emoji: '🧥',
    question: '¿Qué te pones cuando hace frío?',
    translation: 'What do you put on when it\'s cold?',
    options: ['el abrigo', 'el sobretodo', 'el gabán'],
    correctAnswer: 'el abrigo',
    hint: 'Heavy coat for winter',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'shopping_023',
    emoji: '🧣',
    question: '¿Qué envuelves alrededor de tu cuello?',
    translation: 'What do you wrap around your neck?',
    options: ['la bufanda', 'la chalina', 'el echarpe'],
    correctAnswer: 'la bufanda',
    hint: 'Wraps around neck for warmth',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'shopping_024',
    emoji: '🧤',
    question: '¿Qué proteges tus manos del frío?',
    translation: 'What protects your hands from the cold?',
    options: ['los guantes', 'los mitones', 'las manoplas'],
    correctAnswer: 'los guantes',
    hint: 'Keep your hands warm',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'shopping_025',
    emoji: '🩳',
    question: '¿Qué usas en la playa o para hacer ejercicio?',
    translation: 'What do you wear at the beach or to exercise?',
    options: ['los pantalones cortos', 'los shorts', 'los bermudas'],
    correctAnswer: 'los pantalones cortos',
    hint: 'Think about when or where you use this',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'shopping_026',
    emoji: '👖',
    question: '¿Qué pantalón azul es muy popular?',
    translation: 'What blue pants are very popular?',
    options: ['los jeans', 'los vaqueros', 'los tejanos'],
    correctAnswer: 'los jeans',
    hint: 'Blue denim pants',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_027',
    emoji: '👗',
    question: '¿Qué prenda femenina es de una sola pieza?',
    translation: 'What women\'s garment is one piece?',
    options: ['el vestido', 'el jumper', 'el vestido de noche'],
    correctAnswer: 'el vestido',
    hint: 'One-piece outfit for women',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'shopping_028',
    emoji: '👘',
    question: '¿Qué prenda tradicional japonesa se usa?',
    translation: 'What traditional Japanese garment is worn?',
    options: ['el kimono', 'el yukata', 'el jinbei'],
    correctAnswer: 'el kimono',
    hint: 'Traditional Japanese garment - wrap-style robe with wide sleeves',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'surprised',
  },
  {
    id: 'shopping_029',
    emoji: '🥻',
    question: '¿Qué prenda tradicional india usan las mujeres?',
    translation: 'What traditional Indian garment do women wear?',
    options: ['el sari', 'el salwar kameez', 'el lehenga'],
    correctAnswer: 'el sari',
    hint: 'Indian draped garment - long fabric wrapped around body, elegant style',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'surprised',
  },
  {
    id: 'shopping_030',
    emoji: '🩱',
    question: '¿Qué usas para nadar en la piscina?',
    translation: 'What do you wear to swim in the pool?',
    options: ['el traje de baño', 'el bañador', 'la malla'],
    correctAnswer: 'el traje de baño',
    hint: 'Wear when swimming',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'shopping_031',
    emoji: '👙',
    question: '¿Qué traje de baño femenino tiene dos piezas?',
    translation: 'What women\'s swimsuit has two pieces?',
    options: ['el bikini', 'el tankini', 'el trikini'],
    correctAnswer: 'el bikini',
    hint: 'Two-piece swimsuit - "bikini" borrowed from French, same word globally',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_032',
    emoji: '🩲',
    question: '¿Qué prenda interior usan los hombres?',
    translation: 'What underwear do men wear?',
    options: ['los calzoncillos', 'los bóxers', 'los slips'],
    correctAnswer: 'los calzoncillos',
    hint: 'Men\'s underwear - "calzoncillos" from "calzón" (breeches), always plural',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_033',
    emoji: '🩳',
    question: '¿Qué ropa deportiva usas para correr?',
    translation: 'What sportswear do you wear to run?',
    options: ['los shorts deportivos', 'los pantalones deportivos', 'las mallas'],
    correctAnswer: 'los shorts deportivos',
    hint: 'Think about when or where you use this',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'shopping_034',
    emoji: '👚',
    question: '¿Qué blusa femenina es casual?',
    translation: 'What women\'s blouse is casual?',
    options: ['la camiseta', 'la remera', 'la playera'],
    correctAnswer: 'la camiseta',
    hint: 'T-shirt - casual cotton top, "playera" in Mexico, "remera" in Argentina',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_035',
    emoji: '👕',
    question: '¿Qué camisa informal de algodón es muy común?',
    translation: 'What casual cotton shirt is very common?',
    options: ['la camiseta', 'el polo', 'la camisa deportiva'],
    correctAnswer: 'la camiseta',
    hint: 'T-shirt - everyday basic garment, from "camisa" (shirt)',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_036',
    emoji: 'vitaminas.png',
    question: '¿Qué suplementos tomas para la salud?',
    translation: 'What supplements do you take for your health?',
    options: ['las vitaminas', 'los multivitamínicos', 'los suplementos'],
    correctAnswer: 'las vitaminas',
    hint: 'Vitamins - nutritional supplements for health and wellness',
    points: 10,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'shopping_037',
    emoji: '🧥',
    question: '¿Qué chaqueta ligera usas en primavera?',
    translation: 'What light jacket do you wear in spring?',
    options: ['la chaqueta', 'la cazadora', 'el cortavientos'],
    correctAnswer: 'la chaqueta',
    hint: 'Wear over other clothes when cool',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_038',
    emoji: '🥼',
    question: '¿Qué bata blanca usan los doctores?',
    translation: 'What white coat do doctors wear?',
    options: ['la bata de laboratorio', 'la bata médica', 'la bata blanca'],
    correctAnswer: 'la bata de laboratorio',
    hint: 'Lab coat - white coat for doctors/scientists, "bata" also means robe',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'shopping_039',
    emoji: '🦺',
    question: '¿Qué chaleco naranja usan los trabajadores?',
    translation: 'What orange vest do workers wear?',
    options: ['el chaleco de seguridad', 'el chaleco reflectante', 'el chaleco de alta visibilidad'],
    correctAnswer: 'el chaleco de seguridad',
    hint: 'Safety vest - bright orange/yellow for visibility at construction sites',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'determined',
  },
  {
    id: 'shopping_040',
    emoji: 'pijama.png',
    question: '¿Qué ropa usas para dormir?',
    translation: 'What clothing do you wear to sleep?',
    options: ['el pijama', 'la piyama', 'el piyama'],
    correctAnswer: 'el pijama',
    hint: 'Pajamas - sleepwear, can be masculine or feminine in Spanish',
    points: 10,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'shopping_041',
    emoji: 'souvenir.png',
    question: '¿Qué recuerdo compras cuando viajas?',
    translation: 'What memento do you buy when you travel?',
    options: ['el souvenir', 'el recuerdo', 'la artesanía'],
    correctAnswer: 'el souvenir',
    hint: 'Souvenir - memento purchased while traveling, "recuerdo" is also common',
    points: 10,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'shopping_042',
    emoji: '👒',
    question: '¿Qué sombrero de ala ancha usas en el sol?',
    translation: 'What wide-brimmed hat do you wear in the sun?',
    options: ['el sombrero de playa', 'el pamela', 'el canotié'],
    correctAnswer: 'el sombrero de playa',
    hint: 'Think about when or where you use this',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'shopping_043',
    emoji: 'pulsera.png',
    question: '¿Qué joya se usa en la muñeca?',
    translation: 'What jewelry is worn on the wrist?',
    options: ['la pulsera', 'el brazalete', 'la manilla'],
    correctAnswer: 'la pulsera',
    hint: 'Bracelet - jewelry worn around the wrist',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_044',
    emoji: '👑',
    question: '¿Qué accesorio dorado usan los reyes?',
    translation: 'What golden accessory do kings wear?',
    options: ['la corona', 'la diadema', 'la tiara'],
    correctAnswer: 'la corona',
    hint: 'Crown - royal headpiece, "corona" also means wreath or halo',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_045',
    emoji: '🎓',
    question: '¿Qué sombrero usas en la graduación?',
    translation: 'What hat do you wear at graduation?',
    options: ['el birrete', 'el capelo', 'el mortarboard'],
    correctAnswer: 'el birrete',
    hint: 'Think about when or where you use this',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'excited',
  },
  {
    id: 'shopping_046',
    emoji: '🧦',
    question: '¿Qué te pones en los pies antes de los zapatos?',
    translation: 'What do you put on your feet before shoes?',
    options: ['los calcetines', 'las medias', 'los leotardos'],
    correctAnswer: 'los calcetines',
    hint: 'Wear inside shoes',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_047',
    emoji: '👟',
    question: '¿Qué zapatos deportivos usas para correr?',
    translation: 'What athletic shoes do you wear to run?',
    options: ['los tenis', 'las zapatillas', 'las deportivas'],
    correctAnswer: 'los tenis',
    hint: 'Think about when or where you use this',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'shopping_048',
    emoji: '🥿',
    question: '¿Qué zapatos planos y cómodos usan las mujeres?',
    translation: 'What flat and comfortable shoes do women wear?',
    options: ['las bailarinas', 'las manoletinas', 'los slippers'],
    correctAnswer: 'las bailarinas',
    hint: 'Ballet flats - "bailarinas" named after ballet dancers, flat comfortable shoes',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_049',
    emoji: '👠',
    question: '¿Qué zapatos femeninos tienen tacón alto?',
    translation: 'What women\'s shoes have high heels?',
    options: ['los tacones', 'los stilettos', 'las plataformas'],
    correctAnswer: 'los tacones',
    hint: 'High heels - "tacón" means heel, "tacones altos" for very high heels',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'shopping_050',
    emoji: '👡',
    question: '¿Qué calzado abierto usas en verano?',
    translation: 'What open footwear do you wear in summer?',
    options: ['las sandalias', 'las chanclas', 'las alpargatas'],
    correctAnswer: 'las sandalias',
    hint: 'Think about when or where you use this',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'shopping_051',
    emoji: '👢',
    question: '¿Qué botas altas usan las mujeres?',
    translation: 'What tall boots do women wear?',
    options: ['las botas altas', 'las botas mosqueteras', 'las botas de caña alta'],
    correctAnswer: 'las botas altas',
    hint: 'Knee-high boots - fashionable and warm, cover calf or up to knee',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_052',
    emoji: '🥾',
    question: '¿Qué botas robustas usas para caminar en montañas?',
    translation: 'What sturdy boots do you wear to walk in mountains?',
    options: ['las botas de montaña', 'las botas de senderismo', 'las botas de trekking'],
    correctAnswer: 'las botas de montaña',
    hint: 'Think about when or where you use this',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'shopping_053',
    emoji: '🩴',
    question: '¿Qué sandalias simples usas en la playa?',
    translation: 'What simple sandals do you wear at the beach?',
    options: ['las chanclas', 'las chancletas', 'las hawaianas'],
    correctAnswer: 'las chanclas',
    hint: 'Think about when or where you use this',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'shopping_054',
    emoji: '👞',
    question: '¿Qué zapatos elegantes usan los hombres?',
    translation: 'What elegant shoes do men wear?',
    options: ['los zapatos de vestir', 'los zapatos formales', 'los mocasines'],
    correctAnswer: 'los zapatos de vestir',
    hint: 'Dress shoes - formal leather shoes for business or special occasions',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'shopping_055',
    emoji: '👟',
    question: '¿Qué calzado cómodo usas todos los días?',
    translation: 'What comfortable footwear do you wear every day?',
    options: ['los zapatos casuales', 'las zapatillas casuales', 'los zapatos informales'],
    correctAnswer: 'los zapatos casuales',
    hint: 'Think about when or where you use this',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },

  // Accessories & Jewelry (25 questions)
  {
    id: 'shopping_056',
    emoji: '👜',
    question: '¿Dónde guardas tus cosas personales cuando sales?',
    translation: 'Where do you keep your personal things when you go out?',
    options: ['el bolso', 'la cartera', 'el portamonedas'],
    correctAnswer: 'el bolso',
    hint: 'Carry your personal items',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_057',
    emoji: '🎒',
    question: '¿Qué bolsa llevas en la espalda a la escuela?',
    translation: 'What bag do you carry on your back to school?',
    options: ['la mochila', 'el morral', 'el macuto'],
    correctAnswer: 'la mochila',
    hint: 'Bag you wear on your back',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_058',
    emoji: '👝',
    question: '¿Qué bolso pequeño usas para eventos formales?',
    translation: 'What small bag do you use for formal events?',
    options: ['la cartera de mano', 'el clutch', 'el bolso de fiesta'],
    correctAnswer: 'la cartera de mano',
    hint: 'Think about when or where you use this',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_059',
    emoji: '💼',
    question: '¿Qué bolsa rectangular llevas al trabajo?',
    translation: 'What rectangular bag do you carry to work?',
    options: ['el maletín', 'el portafolio', 'el portadocumentos'],
    correctAnswer: 'el maletín',
    hint: 'Briefcase - professional bag for documents, "portafolios" also used',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'shopping_060',
    emoji: '🧳',
    question: '¿Qué llevas tu ropa cuando viajas?',
    translation: 'What do you carry your clothes in when you travel?',
    options: ['la maleta', 'la valija', 'el equipaje'],
    correctAnswer: 'la maleta',
    hint: 'Suitcase - "maleta" from French "mallette", wheels standard now',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_061',
    emoji: 'billetera.png',
    question: '¿Dónde guardas tu dinero y tarjetas?',
    translation: 'Where do you keep your money and cards?',
    options: ['la billetera', 'la cartera', 'el monedero'],
    correctAnswer: 'la billetera',
    hint: 'Wallet - "billetera" from "billete" (banknote), "cartera" also common',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_062',
    emoji: '🕶️',
    question: '¿Qué proteges tus ojos del sol?',
    translation: 'What protects your eyes from the sun?',
    options: ['las gafas de sol', 'los anteojos oscuros', 'los lentes de sol'],
    correctAnswer: 'las gafas de sol',
    hint: 'Protect eyes from bright light',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_063',
    emoji: '👓',
    question: '¿Qué usas para ver mejor?',
    translation: 'What do you use to see better?',
    options: ['las gafas', 'los anteojos', 'los lentes'],
    correctAnswer: 'las gafas',
    hint: 'Think about when or where you use this',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_064',
    emoji: '⌚',
    question: '¿Qué llevas en la muñeca para ver la hora?',
    translation: 'What do you wear on your wrist to see the time?',
    options: ['el reloj', 'el reloj de pulsera', 'el cronómetro'],
    correctAnswer: 'el reloj',
    hint: 'Tells you what time it is',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_065',
    emoji: '💍',
    question: '¿Qué joya te pones en el dedo?',
    translation: 'What jewelry do you put on your finger?',
    options: ['el anillo', 'la sortija', 'el aro'],
    correctAnswer: 'el anillo',
    hint: 'Jewelry for your finger',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'shopping_066',
    emoji: '💎',
    question: '¿Qué piedra preciosa brilla y es muy valiosa?',
    translation: 'What precious stone shines and is very valuable?',
    options: ['el diamante', 'el rubí', 'la esmeralda'],
    correctAnswer: 'el diamante',
    hint: 'Diamond - hardest natural material, "diamante" from Greek "adamas" (invincible)',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_067',
    emoji: '📿',
    question: '¿Qué collar largo tiene cuentas?',
    translation: 'What long necklace has beads?',
    options: ['el collar de cuentas', 'el rosario', 'el collar de perlas'],
    correctAnswer: 'el collar de cuentas',
    hint: 'Beaded necklace - "cuentas" are beads, often used for prayer beads',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_068',
    emoji: '💄',
    question: '¿Qué cosméticos te pones en los labios?',
    translation: 'What cosmetics do you put on your lips?',
    options: ['el lápiz labial', 'el brillo labial', 'el bálsamo labial'],
    correctAnswer: 'el lápiz labial',
    hint: 'Think about when or where you use this',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_069',
    emoji: '👑',
    question: '¿Qué joya elegante usas en la cabeza?',
    translation: 'What elegant jewelry do you wear on your head?',
    options: ['la tiara', 'la diadema', 'la corona'],
    correctAnswer: 'la tiara',
    hint: 'Think about when or where you use this',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_070',
    emoji: '🎀',
    question: '¿Qué decoración de tela atas en el cabello?',
    translation: 'What fabric decoration do you tie in your hair?',
    options: ['el moño', 'la cinta', 'el lazo'],
    correctAnswer: 'el moño',
    hint: 'Bow - "moño" for hair bow or bun hairstyle, from Latin "monutus"',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_071',
    emoji: '🧷',
    question: '¿Qué usas para sujetar tela temporalmente?',
    translation: 'What do you use to hold fabric temporarily?',
    options: ['el alfiler de seguridad', 'el imperdible', 'el broche'],
    correctAnswer: 'el alfiler de seguridad',
    hint: 'Think about when or where you use this',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'shopping_072',
    emoji: '🔗',
    question: '¿Qué tipo de collar es de eslabones?',
    translation: 'What type of necklace is made of links?',
    options: ['la cadena', 'la cadeneta', 'el collar de eslabones'],
    correctAnswer: 'la cadena',
    hint: 'Chain necklace - metal links connected together, masculine word',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_073',
    emoji: '📌',
    question: '¿Qué usas para decorar tu ropa con broches?',
    translation: 'What do you use to decorate your clothes with pins?',
    options: ['el pin', 'el prendedor', 'el broche'],
    correctAnswer: 'el pin',
    hint: 'Think about when or where you use this',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'pleased',
  },
  {
    id: 'shopping_074',
    emoji: '🪢',
    question: '¿Qué haces con los cordones de tus zapatos?',
    translation: 'What do you do with your shoelaces?',
    options: ['atar', 'amarrar', 'anudar'],
    correctAnswer: 'atar',
    hint: 'To tie - "atar" for making knots, "amarrar" also used in Latin America',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'shopping_075',
    emoji: '🧵',
    question: '¿Qué usas para coser ropa?',
    translation: 'What do you use to sew clothes?',
    options: ['el hilo', 'la hebra', 'el hilván'],
    correctAnswer: 'el hilo',
    hint: 'Think about when or where you use this',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_076',
    emoji: '🪡',
    question: '¿Con qué herramienta coses a mano?',
    translation: 'What tool do you sew with by hand?',
    options: ['la aguja', 'la aguja de coser', 'el alfiler'],
    correctAnswer: 'la aguja',
    hint: 'Needle - thin metal tool with eye for thread, "aguja" from Latin "acucula"',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_077',
    emoji: '🔖',
    question: '¿Qué etiqueta tiene información sobre la ropa?',
    translation: 'What label has information about clothing?',
    options: ['la etiqueta', 'la marca', 'el rótulo'],
    correctAnswer: 'la etiqueta',
    hint: 'Label - shows size, material, care instructions, "etiqueta" also means tag',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_078',
    emoji: '🎨',
    question: '¿Cómo describes una camisa con muchos colores?',
    translation: 'How do you describe a shirt with many colors?',
    options: ['colorida', 'multicolor', 'policromática'],
    correctAnswer: 'colorida',
    hint: 'Think about what color this usually is',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_079',
    emoji: '🌈',
    question: '¿Qué patrón tiene todos los colores del arcoíris?',
    translation: 'What pattern has all the colors of the rainbow?',
    options: ['multicolor', 'arcoíris', 'policromado'],
    correctAnswer: 'multicolor',
    hint: 'Think about what color this usually is',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'shopping_080',
    emoji: '🖤',
    question: '¿Qué color de ropa se usa en eventos formales?',
    translation: 'What color clothing is worn at formal events?',
    options: ['negro', 'azul oscuro', 'gris oscuro'],
    correctAnswer: 'negro',
    hint: 'Think about what color this usually is',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'determined',
  },

  // Shopping Actions & Store (30 questions)
  {
    id: 'shopping_081',
    emoji: '🏪',
    question: '¿Dónde compras comida y productos diarios?',
    translation: 'Where do you buy food and daily products?',
    options: ['la tienda', 'el almacén', 'la bodega'],
    correctAnswer: 'la tienda',
    hint: 'Place where you buy things',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_082',
    emoji: '🛒',
    question: '¿Qué empujas en el supermercado para poner tus compras?',
    translation: 'What do you push in the supermarket to put your purchases in?',
    options: ['el carrito', 'el carrito de compras', 'el carro'],
    correctAnswer: 'el carrito',
    hint: 'Shopping cart - "carrito" (little car), roll through store aisles',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_083',
    emoji: '🧺',
    question: '¿Qué canasta pequeña usas para pocas compras?',
    translation: 'What small basket do you use for few purchases?',
    options: ['la cesta', 'el cesto', 'la canasta'],
    correctAnswer: 'la cesta',
    hint: 'Think about when or where you use this',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_084',
    emoji: '💳',
    question: '¿Con qué pagas sin usar efectivo?',
    translation: 'What do you pay with without using cash?',
    options: ['la tarjeta', 'la tarjeta de crédito', 'la tarjeta de débito'],
    correctAnswer: 'la tarjeta',
    hint: 'Card - credit/debit card, "tarjeta de crédito" or "tarjeta de débito"',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_085',
    emoji: '💵',
    question: '¿Qué papel usas para pagar en efectivo?',
    translation: 'What paper do you use to pay in cash?',
    options: ['el billete', 'el papel moneda', 'el dinero en papel'],
    correctAnswer: 'el billete',
    hint: 'Think about when or where you use this',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_086',
    emoji: '💰',
    question: '¿Qué metal redondo usas para pagar cantidades pequeñas?',
    translation: 'What round metal do you use to pay small amounts?',
    options: ['la moneda', 'la monedita', 'el cambio'],
    correctAnswer: 'la moneda',
    hint: 'Think about when or where you use this',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_087',
    emoji: '🧾',
    question: '¿Qué te da el cajero como comprobante de pago?',
    translation: 'What does the cashier give you as proof of payment?',
    options: ['el recibo', 'el comprobante', 'el ticket'],
    correctAnswer: 'el recibo',
    hint: 'Receipt - proof of purchase, "recibo" or "comprobante" for returns',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_088',
    emoji: '💸',
    question: '¿Qué haces cuando das dinero por algo?',
    translation: 'What do you do when you give money for something?',
    options: ['pagar', 'abonar', 'cancelar'],
    correctAnswer: 'pagar',
    hint: 'Give money for something',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'shopping_089',
    emoji: '🏷️',
    question: '¿Dónde ves el precio de un producto?',
    translation: 'Where do you see the price of a product?',
    options: ['la etiqueta de precio', 'el precio', 'el rótulo'],
    correctAnswer: 'la etiqueta de precio',
    hint: 'Price tag - shows cost, "etiqueta" attached to item or shelf',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_090',
    emoji: '💲',
    question: '¿Qué símbolo indica cuánto cuesta algo?',
    translation: 'What symbol indicates how much something costs?',
    options: ['el precio', 'el costo', 'el valor'],
    correctAnswer: 'el precio',
    hint: 'Price - amount of money needed, "costar" means to cost',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_091',
    emoji: '🎁',
    question: '¿Cómo pides que envuelvan algo especial?',
    translation: 'How do you ask them to wrap something special?',
    options: ['envolver para regalo', 'empaquetar', 'empacar'],
    correctAnswer: 'envolver para regalo',
    hint: 'Gift wrap - "envolver" to wrap, decorative paper for presents',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_092',
    emoji: '📦',
    question: '¿En qué ponen productos grandes o frágiles?',
    translation: 'What do they put large or fragile products in?',
    options: ['la caja', 'el cartón', 'el paquete'],
    correctAnswer: 'la caja',
    hint: 'Box - cardboard container for shipping/storage, protects items',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_093',
    emoji: '🛍️',
    question: '¿En qué llevas tus compras a casa?',
    translation: 'What do you carry your purchases home in?',
    options: ['la bolsa de compras', 'la bolsa', 'el saco'],
    correctAnswer: 'la bolsa de compras',
    hint: 'Shopping bag - reusable or plastic, carries purchases home',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_094',
    emoji: '🔍',
    question: '¿Qué haces cuando buscas un producto específico?',
    translation: 'What do you do when you look for a specific product?',
    options: ['buscar', 'indagar', 'rastrear'],
    correctAnswer: 'buscar',
    hint: 'To search - "buscar" to look for something, ask staff for help',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'confused',
  },
  {
    id: 'shopping_095',
    emoji: 'aretes.png',
    question: '¿Qué joya se usa en las orejas?',
    translation: 'What jewelry is worn on the ears?',
    options: ['los aretes', 'los pendientes', 'los zarcillos'],
    correctAnswer: 'los aretes',
    hint: 'Earrings - jewelry worn on the ears, "aretes" common in Latin America',
    points: 10,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_096',
    emoji: '🪞',
    question: '¿En qué te miras cuando te pruebas ropa?',
    translation: 'What do you look at yourself in when you try on clothes?',
    options: ['el espejo', 'el reflejo', 'el cristal'],
    correctAnswer: 'el espejo',
    hint: 'Mirror - see how clothes look, "espejo" from Latin "speculum"',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_097',
    emoji: '📏',
    question: '¿Con qué miden tu talla?',
    translation: 'What do they measure your size with?',
    options: ['la cinta métrica', 'el metro', 'la regla de medir'],
    correctAnswer: 'la cinta métrica',
    hint: 'Think about size or measurements',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'confused',
  },
  {
    id: 'shopping_098',
    emoji: '🏬',
    question: '¿Dónde hay muchas tiendas bajo un mismo techo?',
    translation: 'Where are there many stores under one roof?',
    options: ['el centro comercial', 'el mall', 'la plaza comercial'],
    correctAnswer: 'el centro comercial',
    hint: 'Look at the emoji for a clue',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_099',
    emoji: '🛒',
    question: '¿Qué acción describes cuando pones cosas en el carrito?',
    translation: 'What action describes when you put things in the cart?',
    options: ['agregar al carrito', 'añadir al carrito', 'poner en el carrito'],
    correctAnswer: 'agregar al carrito',
    hint: 'Look at the emoji for a clue',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_100',
    emoji: '💯',
    question: '¿Qué significa cuando algo tiene descuento del 50%?',
    translation: 'What does it mean when something has a 50% discount?',
    options: ['mitad de precio', 'a mitad de precio', 'precio reducido'],
    correctAnswer: 'mitad de precio',
    hint: 'Half price - 50% off, "descuento" means discount or sale',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_101',
    emoji: '🏪',
    question: '¿Cuándo abre la tienda por la mañana?',
    translation: 'When does the store open in the morning?',
    options: ['la hora de apertura', 'la hora de abrir', 'el horario de apertura'],
    correctAnswer: 'la hora de apertura',
    hint: 'Opening time - when store opens, "apertura" from "abrir" (to open)',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_102',
    emoji: '🚪',
    question: '¿Cuándo cierra la tienda por la noche?',
    translation: 'When does the store close at night?',
    options: ['la hora de cierre', 'el horario de cierre', 'la hora de cerrar'],
    correctAnswer: 'la hora de cierre',
    hint: 'Closing time - when store closes, check hours before visiting',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_103',
    emoji: '🎯',
    question: '¿Qué buscas en una tienda cuando necesitas algo?',
    translation: 'What do you look for in a store when you need something?',
    options: ['el producto específico', 'el artículo específico', 'el producto deseado'],
    correctAnswer: 'el producto específico',
    hint: 'Specific product - know what you want, easier to find or ask',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'shopping_104',
    emoji: '💁',
    question: '¿Quién te ayuda en la tienda?',
    translation: 'Who helps you in the store?',
    options: ['el vendedor', 'el dependiente', 'el empleado'],
    correctAnswer: 'el vendedor',
    hint: 'Salesperson - "vendedor" from "vender" (to sell), assists customers',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_105',
    emoji: '🙋',
    question: '¿Qué haces cuando necesitas ayuda en una tienda?',
    translation: 'What do you do when you need help in a store?',
    options: ['preguntar', 'pedir ayuda', 'solicitar ayuda'],
    correctAnswer: 'preguntar',
    hint: 'To ask - "preguntar" to ask questions, staff will help you',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'anxious',
  },
  {
    id: 'shopping_106',
    emoji: '↩️',
    question: '¿Qué haces con un producto que no te gusta?',
    translation: 'What do you do with a product you don\'t like?',
    options: ['devolver', 'retornar', 'regresar'],
    correctAnswer: 'devolver',
    hint: 'To return - bring back with receipt, get refund or exchange',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'shopping_107',
    emoji: '🔄',
    question: '¿Qué haces cuando quieres cambiar por otra talla?',
    translation: 'What do you do when you want to change for another size?',
    options: ['intercambiar', 'cambiar', 'canjear'],
    correctAnswer: 'intercambiar',
    hint: 'Think about size or measurements',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_108',
    emoji: '✅',
    question: '¿Qué dices cuando quieres comprar algo?',
    translation: 'What do you say when you want to buy something?',
    options: ['lo llevo', 'me lo llevo', 'lo tomo'],
    correctAnswer: 'lo llevo',
    hint: 'I\'ll take it - "me lo llevo" common phrase when buying something',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'shopping_109',
    emoji: '❌',
    question: '¿Qué dices cuando no quieres comprar?',
    translation: 'What do you say when you don\'t want to buy?',
    options: ['no gracias', 'no, gracias', 'gracias, no'],
    correctAnswer: 'no gracias',
    hint: 'No thanks - polite way to decline, "solo estoy mirando" (just browsing)',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'shopping_110',
    emoji: '💭',
    question: '¿Qué dices cuando necesitas pensar antes de comprar?',
    translation: 'What do you say when you need to think before buying?',
    options: ['lo voy a pensar', 'voy a pensarlo', 'lo pensaré'],
    correctAnswer: 'lo voy a pensar',
    hint: 'I\'ll think about it - need time to decide, may return later',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'confused',
  },

  // Sizes & Fit (20 questions)
  {
    id: 'shopping_111',
    emoji: '📐',
    question: '¿Qué talla es más pequeña que mediana?',
    translation: 'What size is smaller than medium?',
    options: ['pequeña', 'chica', 'S (small)'],
    correctAnswer: 'pequeña',
    hint: 'Think about size or measurements',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_112',
    emoji: '📏',
    question: '¿Qué talla está entre pequeña y grande?',
    translation: 'What size is between small and large?',
    options: ['mediana', 'M (medium)', 'intermedia'],
    correctAnswer: 'mediana',
    hint: 'Think about size or measurements',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_113',
    emoji: '📊',
    question: '¿Qué talla es más grande que grande?',
    translation: 'What size is larger than large?',
    options: ['extra grande', 'XL', 'XXL'],
    correctAnswer: 'extra grande',
    hint: 'Think about size or measurements',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_114',
    emoji: '👕',
    question: '¿Cómo describes ropa que te queda muy apretada?',
    translation: 'How do you describe clothes that fit you very tight?',
    options: ['muy ajustada', 'apretada', 'estrecha'],
    correctAnswer: 'muy ajustada',
    hint: 'Too tight - uncomfortable fit, "apretado" also used for tight',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'shopping_115',
    emoji: '👔',
    question: '¿Cómo describes ropa que te queda muy grande?',
    translation: 'How do you describe clothes that are too big on you?',
    options: ['suelta', 'holgada', 'ancha'],
    correctAnswer: 'suelta',
    hint: 'Loose - too big, "grande" or "holgado" for baggy clothes',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'shopping_116',
    emoji: '👖',
    question: '¿Cómo describes ropa que te queda perfectamente?',
    translation: 'How do you describe clothes that fit you perfectly?',
    options: ['a la medida', 'justa', 'perfecta'],
    correctAnswer: 'a la medida',
    hint: 'Perfect fit - custom-fitted, "justo" for just right size',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'shopping_117',
    emoji: '📏',
    question: '¿Qué necesitas saber antes de comprar ropa?',
    translation: 'What do you need to know before buying clothes?',
    options: ['tu talla', 'tu medida', 'tu número'],
    correctAnswer: 'tu talla',
    hint: 'Your size - essential info, sizes vary by country and brand',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_118',
    emoji: '🩳',
    question: '¿Cómo describes pantalones que son cortos?',
    translation: 'How do you describe pants that are short?',
    options: ['cortos', 'bermudas', 'capri'],
    correctAnswer: 'cortos',
    hint: 'Short - above knee length, "pantalones cortos" or "shorts"',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_119',
    emoji: '👖',
    question: '¿Cómo describes pantalones que llegan al suelo?',
    translation: 'How do you describe pants that reach the floor?',
    options: ['largos', 'de talle largo', 'completos'],
    correctAnswer: 'largos',
    hint: 'Long - full length to floor, may need hemming if too long',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_120',
    emoji: '👔',
    question: '¿Qué dices cuando la ropa te queda bien?',
    translation: 'What do you say when clothes fit you well?',
    options: ['me queda bien', 'me sienta bien', 'me va bien'],
    correctAnswer: 'me queda bien',
    hint: 'It fits well - perfect phrase when trying on clothes in store',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_121',
    emoji: '👕',
    question: '¿Qué necesitas cuando la ropa es muy grande?',
    translation: 'What do you need when clothes are too big?',
    options: ['una talla más pequeña', 'una talla más grande', 'la misma talla'],
    correctAnswer: 'una talla más pequeña',
    hint: 'Smaller size - "una talla menos" also used for one size down',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'shopping_122',
    emoji: '👗',
    question: '¿Qué dices cuando el vestido es muy largo?',
    translation: 'What do you say when the dress is too long?',
    options: ['muy largo', 'muy corto', 'perfecto'],
    correctAnswer: 'muy largo',
    hint: 'Too long - can be hemmed/altered, "demasiado largo" for emphasis',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'confused',
  },
  {
    id: 'shopping_123',
    emoji: '🩳',
    question: '¿Qué dices cuando los pantalones son muy cortos?',
    translation: 'What do you say when the pants are too short?',
    options: ['muy cortos', 'muy largos', 'perfectos'],
    correctAnswer: 'muy cortos',
    hint: 'Too short - above preferred length, harder to fix than too long',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'shopping_124',
    emoji: 'ajustado.png',
    question: '¿Qué tipo de ajuste prefieres para ropa formal?',
    translation: 'What type of fit do you prefer for formal clothing?',
    options: ['ajustado', 'muy suelto', 'muy apretado'],
    correctAnswer: 'ajustado',
    hint: 'Fitted - tailored look for formal wear, follows body shape nicely',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_125',
    emoji: '👕',
    question: '¿Qué tipo de ajuste prefieres para ropa casual?',
    translation: 'What type of fit do you prefer for casual clothing?',
    options: ['cómodo', 'muy apretado', 'muy grande'],
    correctAnswer: 'cómodo',
    hint: 'Comfortable - relaxed fit for everyday wear, not too tight or loose',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'shopping_126',
    emoji: '📐',
    question: '¿Qué mides para saber tu talla de camisa?',
    translation: 'What do you measure to know your shirt size?',
    options: ['el pecho y la cintura', 'la altura', 'el peso'],
    correctAnswer: 'el pecho y la cintura',
    hint: 'Think about size or measurements',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'confused',
  },
  {
    id: 'shopping_127',
    emoji: '👞',
    question: '¿Qué número necesitas para comprar zapatos?',
    translation: 'What number do you need to buy shoes?',
    options: ['el número de calzado', 'la talla de camisa', 'la altura'],
    correctAnswer: 'el número de calzado',
    hint: 'Shoe size - European sizes differ from US/UK, try before buying',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_128',
    emoji: '👖',
    question: '¿Qué medida necesitas para pantalones?',
    translation: 'What measurement do you need for pants?',
    options: ['la cintura y el largo', 'el peso', 'la altura total'],
    correctAnswer: 'la cintura y el largo',
    hint: 'Waist and length - two key measurements for proper pants fit',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'confused',
  },
  {
    id: 'shopping_129',
    emoji: 'entallado.png',
    question: '¿Cómo describes ropa que sigue la forma del cuerpo?',
    translation: 'How do you describe clothes that follow the body\'s shape?',
    options: ['entallado', 'suelto', 'ancho'],
    correctAnswer: 'entallado',
    hint: 'Tailored/fitted - follows body contours, "entallado" from "talle" (waist)',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'pleased',
  },
  {
    id: 'shopping_130',
    emoji: '👕',
    question: '¿Cómo describes ropa que no está ajustada?',
    translation: 'How do you describe clothes that are not fitted?',
    options: ['holgado', 'apretado', 'entallado'],
    correctAnswer: 'holgado',
    hint: 'Loose/baggy - extra room, relaxed fit, "suelto" also common',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'neutral',
  },

  // Materials & Care (20 questions)
  {
    id: 'shopping_131',
    emoji: '🧵',
    question: '¿Qué tela natural y suave viene del algodón?',
    translation: 'What natural and soft fabric comes from cotton?',
    options: ['el algodón', 'el poliéster', 'el nailon'],
    correctAnswer: 'el algodón',
    hint: 'Cotton - natural fiber, breathable and soft, "algodón" from Arabic',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_132',
    emoji: '🐑',
    question: '¿Qué tela caliente viene de las ovejas?',
    translation: 'What warm fabric comes from sheep?',
    options: ['la lana', 'el algodón', 'la seda'],
    correctAnswer: 'la lana',
    hint: 'Wool - from sheep, warm insulation, "lana" keeps you cozy in winter',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'calm',
  },
  {
    id: 'shopping_133',
    emoji: '🦋',
    question: '¿Qué tela suave y brillante hacen los gusanos?',
    translation: 'What soft and shiny fabric do worms make?',
    options: ['la seda', 'el algodón', 'la lana'],
    correctAnswer: 'la seda',
    hint: 'Silk - silkworms produce, luxurious and smooth, expensive fabric',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_134',
    emoji: '👖',
    question: '¿Qué tela resistente azul es para jeans?',
    translation: 'What sturdy blue fabric is for jeans?',
    options: ['la mezclilla', 'la seda', 'el terciopelo'],
    correctAnswer: 'la mezclilla',
    hint: 'Denim - durable cotton fabric, "vaquera" also used, originally from France',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_135',
    emoji: '🧥',
    question: '¿Qué material viene de la piel de animales?',
    translation: 'What material comes from animal skin?',
    options: ['el cuero', 'el algodón', 'el poliéster'],
    correctAnswer: 'el cuero',
    hint: 'Leather - animal hide, durable for jackets and shoes, "piel" also used',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_136',
    emoji: '🌊',
    question: '¿Qué tela sintética se seca rápido?',
    translation: 'What synthetic fabric dries quickly?',
    options: ['el poliéster', 'el algodón', 'la lana'],
    correctAnswer: 'el poliéster',
    hint: 'Polyester - synthetic, quick-dry, wrinkle-resistant, common in sportswear',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_137',
    emoji: '👟',
    question: '¿Qué material sintético es elástico y resistente?',
    translation: 'What synthetic material is elastic and resistant?',
    options: ['el nailon', 'el algodón', 'la lana'],
    correctAnswer: 'el nailon',
    hint: 'Nylon - synthetic, stretchy and strong, invented 1930s, used in activewear',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'neutral',
  },
  {
    id: 'shopping_138',
    emoji: '👙',
    question: '¿Qué tela elástica se usa en ropa deportiva?',
    translation: 'What elastic fabric is used in sportswear?',
    options: ['el spandex', 'la seda', 'el lino'],
    correctAnswer: 'el spandex',
    hint: 'Spandex/Lycra - super stretchy, returns to shape, ideal for athletic wear',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'determined',
  },
  {
    id: 'shopping_139',
    emoji: '🌿',
    question: '¿Qué tela natural es fresca para el verano?',
    translation: 'What natural fabric is cool for summer?',
    options: ['el lino', 'la lana', 'el terciopelo'],
    correctAnswer: 'el lino',
    hint: 'Linen - breathable natural fiber from flax plant, cool in hot weather',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'pleased',
  },
  {
    id: 'shopping_140',
    emoji: '✨',
    question: '¿Qué tela suave y lujosa tiene pelo?',
    translation: 'What soft and luxurious fabric has fur?',
    options: ['el terciopelo', 'el algodón', 'el lino'],
    correctAnswer: 'el terciopelo',
    hint: 'Velvet - soft pile fabric, luxurious feel, "terciopelo" used for elegance',
    points: 15,
    category: 'shopping',
    difficulty: 'hard',
    emotion: 'excited',
  },
  {
    id: 'shopping_141',
    emoji: '🧼',
    question: '¿Qué haces para limpiar tu ropa?',
    translation: 'What do you do to clean your clothes?',
    options: ['lavar', 'planchar', 'doblar'],
    correctAnswer: 'lavar',
    hint: 'To wash - "lavar" with water and detergent, machine or hand wash',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_142',
    emoji: 'clothes-iron.png',
    question: '¿Qué haces para quitar arrugas de la ropa?',
    translation: 'What do you do to remove wrinkles from clothes?',
    options: ['planchar', 'lavar', 'secar'],
    correctAnswer: 'planchar',
    hint: 'To iron - heat removes wrinkles, "plancha" is the iron appliance',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'shopping_143',
    emoji: '☀️',
    question: '¿Dónde pones la ropa después de lavarla?',
    translation: 'Where do you put clothes after washing them?',
    options: ['a secar', 'a guardar', 'a planchar'],
    correctAnswer: 'a secar',
    hint: 'To dry - air dry or machine dry, sun drying natural and free',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_145',
    emoji: '🧷',
    question: '¿Qué usas para colgar ropa en el tendedero?',
    translation: 'What do you use to hang clothes on the clothesline?',
    options: ['las pinzas', 'las perchas', 'los ganchos'],
    correctAnswer: 'las pinzas',
    hint: 'Think about when or where you use this',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_146',
    emoji: 'percha.png',
    question: '¿En qué cuelgas camisas y chaquetas?',
    translation: 'What do you hang shirts and jackets on?',
    options: ['la percha', 'el gancho', 'el estante'],
    correctAnswer: 'la percha',
    hint: 'Hanger - keeps clothes wrinkle-free, "gancho" also used in some regions',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_147',
    emoji: '📦',
    question: '¿Dónde guardas ropa que no usas?',
    translation: 'Where do you store clothes you don\'t use?',
    options: ['la caja', 'la percha', 'la lavadora'],
    correctAnswer: 'la caja',
    hint: 'Think about when or where you use this',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_148',
    emoji: '🚪',
    question: '¿Dónde guardas tu ropa colgada?',
    translation: 'Where do you store your hanging clothes?',
    options: ['el armario', 'la caja', 'el cajón'],
    correctAnswer: 'el armario',
    hint: 'Closet/wardrobe - "armario" for hanging clothes, "clóset" in Latin America',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_149',
    emoji: '📁',
    question: '¿Dónde guardas ropa doblada como calcetines?',
    translation: 'Where do you store folded clothes like socks?',
    options: ['el cajón', 'la percha', 'el estante alto'],
    correctAnswer: 'el cajón',
    hint: 'Drawer - pull-out compartment for folded items, socks and underwear',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_150',
    emoji: '🧹',
    question: '¿Qué haces con manchas en la ropa?',
    translation: 'What do you do with stains on clothes?',
    options: ['quitar la mancha', 'dejarla', 'cortar'],
    correctAnswer: 'quitar la mancha',
    hint: 'Remove stain - treat quickly, use stain remover, "mancha" is stain',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'anxious',
  },
  {
    id: 'shopping_151',
    emoji: '🔋',
    question: '¿Qué necesitas para que funcione un control remoto?',
    translation: 'What do you need for a remote control to work?',
    options: ['la batería', 'la pila', 'el acumulador'],
    correctAnswer: 'la batería',
    hint: 'Battery - power source for electronic devices, "pila" also used in Spanish',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_152',
    emoji: '🥛',
    question: '¿Qué postre lácteo es fermentado?',
    translation: 'What fermented dairy dessert is this?',
    options: ['el yogur', 'el yogurt', 'el yoghurt'],
    correctAnswer: 'el yogur',
    hint: 'Yogurt - fermented dairy product, can be plain or flavored',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_153',
    emoji: '🗑️',
    question: '¿Dónde tieres la basura?',
    translation: 'Where do you throw the garbage?',
    options: ['la basura', 'los residuos', 'el desecho'],
    correctAnswer: 'la basura',
    hint: 'Garbage - waste thrown away, "tienes que tirar la basura" (you have to throw out the trash)',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'disgusted',
  },
  {
    id: 'shopping_154',
    emoji: '🧴',
    question: '¿Qué usas para el olor corporal?',
    translation: 'What do you use for body odor?',
    options: ['el desodorante', 'la colonia', 'el perfume'],
    correctAnswer: 'el desodorante',
    hint: 'Deodorant - stops body odor, "antitranspirante" prevents sweating too',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_155',
    emoji: '🪒',
    question: '¿Qué usas para afeitarte?',
    translation: 'What do you use to shave?',
    options: ['la navaja', 'la máquina de afeitar', 'la rasuradora'],
    correctAnswer: 'la navaja',
    hint: 'Razor - shaving tool, "máquina de afeitar" also used for electric shavers',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_156',
    emoji: '🔌',
    question: '¿Qué necesitas para cargar tu teléfono?',
    translation: 'What do you need to charge your phone?',
    options: ['el cargador de teléfono', 'el cargador', 'el adaptador'],
    correctAnswer: 'el cargador de teléfono',
    hint: 'Phone charger - device that charges your mobile phone battery',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'shopping_157',
    emoji: '🧵',
    question: '¿Qué cable conecta el cargador al teléfono?',
    translation: 'What cable connects the charger to the phone?',
    options: ['el cable del cargador', 'el cable USB', 'el cable de datos'],
    correctAnswer: 'el cable del cargador',
    hint: 'Phone charger cable - connects power adapter to phone, may be USB-C or Lightning',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_158',
    emoji: '🥽',
    question: '¿Qué te pones en los ojos para nadar?',
    translation: 'What do you put on your eyes to swim?',
    options: ['las gafas de natación', 'los lentes de agua', 'las antiparras de piscina'],
    correctAnswer: 'las gafas de natación',
    hint: 'Swimming goggles - protective eyewear worn for swimming to see underwater',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_159',
    emoji: '💱',
    question: '¿Qué haces cuando cambias dólares por euros?',
    translation: 'What do you do when you exchange dollars for euros?',
    options: ['cambio moneda', 'compro dinero', 'vendo billetes'],
    correctAnswer: 'cambio moneda',
    hint: 'Exchange currency - "cambiar moneda", converting one currency to another',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_160',
    emoji: '✂️',
    question: '¿Qué usas para cortar papel?',
    translation: 'What do you use to cut paper?',
    options: ['las tijeras', 'el cuchillo', 'la navaja'],
    correctAnswer: 'las tijeras',
    hint: 'Scissors - cutting tool with two blades, "tijeras" is always plural in Spanish',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_161',
    emoji: '💅',
    question: '¿Qué te pones en las uñas?',
    translation: 'What do you put on your nails?',
    options: ['el esmalte de uñas', 'el lápiz labial', 'la crema'],
    correctAnswer: 'el esmalte de uñas',
    hint: 'Nail polish - cosmetic product to color nails, "pintauñas" also used',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_162',
    emoji: '🏧',
    question: '¿Dónde sacas dinero del banco?',
    translation: 'Where do you take money out from the bank?',
    options: ['el cajero automático', 'la caja registradora', 'el mostrador'],
    correctAnswer: 'el cajero automático',
    hint: 'ATM - automated teller machine, "cajero" means cashier or ATM',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_163',
    emoji: '💇🏻‍♂️',
    question: '¿Qué servicio pides en la barbería?',
    translation: 'What service do you ask for at the barbershop?',
    options: ['un corte de pelo', 'un corte de cabello', 'cortarse el pelo'],
    correctAnswer: 'un corte de pelo',
    hint: 'Haircut - service at barbershop or salon, "cortar el pelo" means to cut hair',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_164',
    emoji: '📏',
    question: '¿Qué talla es más grande que la mediana?',
    translation: 'What size is larger than medium?',
    options: ['grande', 'extra grande', 'XL'],
    correctAnswer: 'grande',
    hint: 'Size that\'s larger than medium but not yet extra large',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_165',
    emoji: '🖼️',
    question: '¿Dónde expones tus pinturas?',
    translation: 'Where do you exhibit your paintings?',
    options: ['la galería', 'la galería de arte', 'el salón'],
    correctAnswer: 'la galería',
    hint: 'Art gallery - exhibition space for artwork, "galería de arte"',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_166',
    emoji: '📚',
    question: '¿Qué son estos?',
    translation: 'What are these?',
    options: ['los libros', 'los tomos', 'los volúmenes'],
    correctAnswer: 'los libros',
    hint: 'Books - "libro" from Latin "liber", reading for education and pleasure',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_168',
    emoji: 'máquina expendedora.png',
    question: '¿Qué máquina vende refrescos y bocadillos?',
    translation: 'What machine sells drinks and snacks?',
    options: ['la máquina expendedora', 'el dispensador automático', 'la máquina de venta'],
    correctAnswer: 'la máquina expendedora',
    hint: 'Vending machine - automatic machine that dispenses snacks and drinks',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'surprised',
  },
  {
    id: 'shopping_169',
    emoji: '🤿',
    question: '¿Qué equipo usas para bucear bajo el agua?',
    translation: 'What equipment do you use to dive underwater?',
    options: ['el equipo de buceo', 'el equipo de submarinismo', 'el equipo de inmersión'],
    correctAnswer: 'el equipo de buceo',
    hint: 'Scuba diving equipment - gear needed for underwater diving',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_170',
    emoji: 'kit de limpieza para celular.png',
    question: '¿Qué kit usas para limpiar tu teléfono celular?',
    translation: 'What kit do you use to clean your cell phone?',
    options: ['el kit de limpieza para celular', 'el kit de limpieza para móvil', 'el limpiador de pantallas'],
    correctAnswer: 'el kit de limpieza para celular',
    hint: 'Cell phone cleaning kit - tools to clean phone screens and devices',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_171',
    emoji: 'calculadora.png',
    question: '¿Qué usas para calcular el total de tus compras?',
    translation: 'What do you use to calculate the total of your purchases?',
    options: ['la calculadora', 'el calculador', 'la máquina de calcular'],
    correctAnswer: 'la calculadora',
    hint: 'Calculator - device used to calculate totals and prices when shopping',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_172',
    emoji: 'billetera.png',
    question: '¿Dónde guardas tu dinero y tarjetas cuando vas de compras?',
    translation: 'Where do you keep your money and cards when you go shopping?',
    options: ['la billetera', 'la cartera', 'el monedero'],
    correctAnswer: 'la billetera',
    hint: 'Wallet - accessory for carrying money and cards while shopping',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_173',
    emoji: 'carretilla.png',
    question: '¿Qué carrito usan en las tiendas para mover cajas pesadas?',
    translation: 'What cart do they use in stores to move heavy boxes?',
    options: ['la carretilla', 'el diablito', 'el carro de carga'],
    correctAnswer: 'la carretilla',
    hint: 'Dolly/hand truck - wheeled cart used in stores to move heavy boxes',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'shopping_174',
    emoji: 'bomba de aire.png',
    question: '¿Qué usas para inflar llantas y juguetes de playa?',
    translation: 'What do you use to inflate tires and beach toys?',
    options: ['la bomba de aire', 'el inflador', 'la bomba neumática'],
    correctAnswer: 'la bomba de aire',
    hint: 'Air pump - device used to inflate tires, beach toys, and other inflatable items',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_175',
    emoji: 'chupete.png',
    question: '¿Qué le das al bebé para que no llore?',
    translation: 'What do you give a baby to keep them from crying?',
    options: ['el chupete', 'el chupón', 'la chupeta'],
    correctAnswer: 'el chupete',
    hint: 'Pacifier - soothing device for babies to keep them from crying',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_176',
    emoji: '',
    question: '¿Qué producto usas para eliminar el mal olor de los zapatos?',
    translation: 'What product do you use to eliminate bad odor from shoes?',
    options: ['el desodorante para zapatos', 'el spray desodorante', 'el ambientador para calzado'],
    correctAnswer: 'el desodorante para zapatos',
    hint: 'Shoe deodorizer - product used to eliminate bad odor from shoes',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'disgusted',
  },
  {
    id: 'shopping_177',
    emoji: 'encendedor.png',
    question: '¿Qué usas para encender cigarros y fogatas?',
    translation: 'What do you use to light cigars and campfires?',
    options: ['el encendedor', 'el mechero', 'el yesquero'],
    correctAnswer: 'el encendedor',
    hint: 'Lighter - device used to light cigars, candles, and campfires',
    points: 10,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_178',
    emoji: 'plantillas.png',
    question: '¿Qué pones dentro de los zapatos para mayor comodidad?',
    translation: 'What do you put inside shoes for greater comfort?',
    options: ['las plantillas', 'las suelas interiores', 'los forros'],
    correctAnswer: 'las plantillas',
    hint: 'Insoles - cushioned inserts placed inside shoes for comfort and support',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_179',
    emoji: 'riñonera.png',
    question: '¿Qué bolsa usas en la cintura para proteger tus objetos de valor?',
    translation: 'What bag do you wear on your waist to protect your valuables?',
    options: ['la riñonera', 'la cangurera', 'la banano'],
    correctAnswer: 'la riñonera',
    hint: 'Fanny pack - small bag worn around the waist to keep valuables safe',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'determined',
  },
  {
    id: 'shopping_180',
    emoji: 'crema de afeitar.png',
    question: '¿Qué crema usas para afeitarte?',
    translation: 'What cream do you use to shave?',
    options: ['la crema de afeitar', 'la espuma de afeitar', 'el gel de rasurar'],
    correctAnswer: 'la crema de afeitar',
    hint: 'Shaving cream - product used to soften hair and protect skin during shaving',
    points: 10,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'neutral',
  },
  {
    id: 'shopping_181',
    emoji: 'collar para perro.png',
    question: '¿Qué compras para ponerle al cuello de tu perro?',
    translation: 'What do you buy to put around your dog\'s neck?',
    options: ['el collar para perro', 'el collar canino', 'la correa de cuello'],
    correctAnswer: 'el collar para perro',
    hint: 'Dog collar - accessory worn around a dog\'s neck for identification and control',
    points: 10,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_182',
    emoji: '⏰',
    question: '¿Qué compras para despertarte en la mañana?',
    translation: 'What do you buy to wake you up in the morning?',
    options: ['el despertador', 'el reloj despertador', 'la alarma'],
    correctAnswer: 'el despertador',
    hint: 'Alarm clock - device used to wake you up in the morning',
    points: 10,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'determined',
  },
  {
    id: 'shopping_183',
    emoji: 'higiene bucal.png',
    question: '¿Qué productos compras para mantener tu boca limpia y saludable?',
    translation: 'What products do you buy to keep your mouth clean and healthy?',
    options: ['los productos de higiene bucal', 'los artículos dentales', 'los productos de higiene oral'],
    correctAnswer: 'los productos de higiene bucal',
    hint: 'Oral hygiene products - items like toothpaste, toothbrush, floss, and mouthwash',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_184',
    emoji: 'dron.png',
    question: '¿Qué dispositivo volador compras para tomar fotos aéreas?',
    translation: 'What flying device do you buy to take aerial photos?',
    options: ['el dron', 'el drone', 'el cuadricóptero'],
    correctAnswer: 'el dron',
    hint: 'Drone - unmanned aerial vehicle used for aerial photography and videography',
    points: 10,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'shopping_185',
    emoji: 'teclado.png',
    question: '¿Qué compras para escribir en tu computadora?',
    translation: 'What do you buy to type on your computer?',
    options: ['el teclado', 'el keyboard', 'el tecladillo'],
    correctAnswer: 'el teclado',
    hint: 'Keyboard - input device used to type on a computer',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_186',
    emoji: 'desodorante.png',
    question: '¿Qué producto usas para controlar el olor corporal?',
    translation: 'What product do you use to control body odor?',
    options: ['el desodorante', 'el antitranspirante', 'el desodorizante'],
    correctAnswer: 'el desodorante',
    hint: 'Deodorant - personal care product used to control body odor',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_187',
    emoji: 'kit de cuidado.png',
    question: '¿Qué kit compras para cuidar tus uñas?',
    translation: 'What kit do you buy to take care of your nails?',
    options: ['el kit de cuidado de uñas', 'el set de manicura', 'el estuche de uñas'],
    correctAnswer: 'el kit de cuidado de uñas',
    hint: 'Nail care kit - set of tools for manicure and nail maintenance',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_188',
    emoji: 'juguetes inflables.png',
    question: '¿Qué juguetes inflables compras para llevar a la playa?',
    translation: 'What inflatable toys do you buy to take to the beach?',
    options: ['los juguetes inflables de playa', 'los flotadores de playa', 'los inflables playeros'],
    correctAnswer: 'los juguetes inflables de playa',
    hint: 'Inflatable beach toys - air-filled toys like floats, balls, and pool toys for the beach',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_189',
    emoji: 'colchón flotante.png',
    question: '¿Qué colchón inflable compras para flotar en la piscina o el mar?',
    translation: 'What inflatable mattress do you buy to float in the pool or ocean?',
    options: ['el colchón flotante', 'la colchoneta de agua', 'el flotador de piscina'],
    correctAnswer: 'el colchón flotante',
    hint: 'Floating mattress - inflatable mattress used for relaxing on water in pools or ocean',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'happy',
  },
  {
    id: 'shopping_190',
    emoji: '🥏',
    question: '¿Qué disco volador compras para jugar en la playa o piscina?',
    translation: 'What flying disc do you buy to play with at the beach or pool?',
    options: ['el frisbee', 'el disco volador', 'el platillo volador'],
    correctAnswer: 'el frisbee',
    hint: 'Frisbee - flying disc toy used for throwing and catching at the beach or pool',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'happy',
  },
  {
    id: 'shopping_191',
    emoji: 'caja registradora.png',
    question: '¿Qué máquina usa el empleado de la tienda para cobrar?',
    translation: 'What machine does the store clerk use to charge customers?',
    options: ['la caja registradora', 'el registro de ventas', 'la máquina de cobro'],
    correctAnswer: 'la caja registradora',
    hint: 'Cash register - machine used by store clerks to process payments and transactions',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_192',
    emoji: 'excelente servicio.png',
    question: '¿Qué esperas recibir del empleado cuando compras en una tienda?',
    translation: 'What do you expect to receive from the employee when shopping at a store?',
    options: ['un excelente servicio al cliente', 'una buena atención', 'un buen trato'],
    correctAnswer: 'un excelente servicio al cliente',
    hint: 'Great customer service - excellent assistance and care from store employees',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_193',
    emoji: 'puros.png',
    question: '¿Qué producto de tabaco enrollado compras en la tienda especializada?',
    translation: 'What rolled tobacco product do you buy at a specialty store?',
    options: ['los puros', 'los cigarros', 'los habanos'],
    correctAnswer: 'los puros',
    hint: 'Cigars - rolled tobacco products typically larger and more expensive than cigarettes',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_194',
    emoji: '',
    question: '¿Qué compras para que los niños jueguen?',
    translation: 'What do you buy for children to play with?',
    options: ['los juguetes', 'los juegos', 'los entretenimientos'],
    correctAnswer: 'los juguetes',
    hint: 'Toys - playthings for children such as dolls, action figures, games, and stuffed animals',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'shopping_195',
    emoji: 'mercado de artesanías.png',
    question: '¿Qué mercado visitas para comprar artesanías hechas a mano?',
    translation: 'What market do you visit to buy handmade crafts?',
    options: ['el mercado de artesanías', 'la feria artesanal', 'el mercado de manualidades'],
    correctAnswer: 'el mercado de artesanías',
    hint: 'Craft market - marketplace where artisans sell handmade items, crafts, and local artwork',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_196',
    emoji: 'esnórquel.png',
    question: '¿Qué tubo compras para respirar debajo del agua mientras nadas?',
    translation: 'What tube do you buy to breathe underwater while swimming?',
    options: ['el esnórquel', 'el tubo de respiración', 'el respirador acuático'],
    correctAnswer: 'el esnórquel',
    hint: 'Snorkel - breathing tube used for swimming underwater near the surface',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_197',
    emoji: 'barbería.png',
    question: '¿A dónde vas para cortarte el pelo?',
    translation: 'Where do you go to get your hair cut?',
    options: ['la barbería', 'el salón de barbería', 'la peluquería de hombres'],
    correctAnswer: 'la barbería',
    hint: 'Barbershop - establishment where men get haircuts, shaves, and grooming services',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'pleased',
  },
  {
    id: 'shopping_198',
    emoji: 'perfume.png',
    question: '¿Qué fragancia compras para oler bien?',
    translation: 'What fragrance do you buy to smell good?',
    options: ['el perfume', 'la colonia', 'la fragancia'],
    correctAnswer: 'el perfume',
    hint: 'Perfume - scented liquid worn on the body to smell pleasant',
    points: 5,
    category: 'shopping',
    difficulty: 'easy',
    emotion: 'excited',
  },
  {
    id: 'shopping_199',
    emoji: 'tabla de paddle.png',
    question: '¿Qué tabla compras para pararte y remar en el agua?',
    translation: 'What board do you buy to stand and paddle in the water?',
    options: ['la tabla de paddle', 'la tabla de remo', 'el paddleboard'],
    correctAnswer: 'la tabla de paddle',
    hint: 'Paddleboard - large surfboard-like board you stand on and paddle in the water (SUP)',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'excited',
  },
  {
    id: 'shopping_200',
    emoji: 'disco duro externo.png',
    question: '¿Qué dispositivo compras para guardar archivos fuera de tu computadora?',
    translation: 'What device do you buy to store files outside your computer?',
    options: ['el disco duro externo', 'el disco portátil', 'la unidad externa'],
    correctAnswer: 'el disco duro externo',
    hint: 'External hard drive - portable storage device for backing up and storing computer files',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'neutral',
  },
  {
    id: 'shopping_201',
    emoji: 'medallón.png',
    question: '¿Qué joya redonda compras para llevar en el cuello?',
    translation: 'What round jewelry do you buy to wear around your neck?',
    options: ['el medallón', 'el colgante redondo', 'la medalla'],
    correctAnswer: 'el medallón',
    hint: 'Medallion - round piece of jewelry worn on a chain around the neck',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
    emotion: 'pleased',
  },
  {
    id: 'shopping_202',
    emoji: 'agencia de viajes.png',
    question: '¿Dónde compras un viaje organizado con vuelos y hotel incluidos?',
    translation: 'Where do you buy an organized trip with flights and hotel included?',
    options: ['en la agencia de viajes', 'en la oficina de turismo', 'en el centro de viajes'],
    correctAnswer: 'en la agencia de viajes',
    hint: 'Travel agency - business that arranges trips, flights, hotels, and vacation packages',
    points: 10,
    category: 'shopping',
    difficulty: 'medium',
  },
];
