/**
 * TRANSPORTATION Category Questions
 * Category: transportation
 */

export const transportationQuestions = [
{
    id: 'transportation_001',
    emoji: '🚕',
    question: '¿Qué vehículo pagas para llevarte a tu destino?',
    options: ['el taxi', 'el cab', 'el libre'],
    correctAnswer: 'el taxi',
    hint: 'Taxi - paid car service, yellow in many countries, hail on street',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_002',
    emoji: '🚌',
    question: '¿En qué transporte público grande viajas en la ciudad?',
    options: ['el autobús', 'el camión', 'la guagua'],
    correctAnswer: 'el autobús',
    hint: 'Bus - large public vehicle, "camión" in Mexico, "guagua" in Caribbean',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_003',
    emoji: '🚂',
    question: '¿Qué viaja por rieles o vías?',
    options: ['el tren', 'el ferrocarril', 'la locomotora'],
    correctAnswer: 'el tren',
    hint: 'Train - runs on rails, "ferrocarril" is railway system',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_004',
    emoji: '✈️',
    question: '¿En qué vuelas a otro país?',
    options: ['el avión', 'el aeroplano', 'la aeronave'],
    correctAnswer: 'el avión',
    hint: 'Airplane - flies at high altitude, fastest way to travel long distances',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_005',
    emoji: '🚇',
    question: '¿Qué tren viaja bajo tierra?',
    options: ['el metro', 'el subterráneo', 'el subte'],
    correctAnswer: 'el metro',
    hint: 'Subway/metro - underground train, "subte" in Argentina',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_006',
    emoji: '🚗',
    question: '¿En qué vehículo privado manejas?',
    options: ['el coche', 'el carro', 'el auto'],
    correctAnswer: 'el coche',
    hint: 'Car - private vehicle, "carro" in Latin America, "auto" also used',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_007',
    emoji: '🛵',
    question: '¿Qué vehículo de dos ruedas tiene motor?',
    options: ['la moto', 'la motocicleta', 'el motociclo'],
    correctAnswer: 'la moto',
    hint: 'Motorcycle - motor-powered two-wheeler, "motocicleta" is full term',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_008',
    emoji: '🚲',
    question: '¿Qué pedaleas para moverte?',
    options: ['la bicicleta', 'la bici', 'el velocípedo'],
    correctAnswer: 'la bicicleta',
    hint: 'Bicycle - pedal-powered two wheels, "bici" for short',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_009',
    emoji: '⛴️',
    question: '¿En qué navegas por el agua?',
    options: ['el barco', 'el buque', 'la embarcación'],
    correctAnswer: 'el barco',
    hint: 'Boat/ship - water vessel, "buque" for large ship, "nave" for vessel',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_010',
    emoji: '🎫',
    question: '¿Qué compras para viajar en transporte público?',
    options: ['el boleto', 'el billete', 'el pasaje'],
    correctAnswer: 'el boleto',
    hint: 'Ticket - for transport, "billete" in Spain, "pasaje" for long trips',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_011',
    emoji: '🚏',
    question: '¿Dónde esperas el autobús?',
    options: ['la parada de autobús', 'la parada', 'el paradero'],
    correctAnswer: 'la parada de autobús',
    hint: 'Bus stop - designated waiting area, marked with sign and shelter',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_012',
    emoji: '🛂',
    question: '¿Qué documento necesitas para viajar internacionalmente?',
    options: ['el pasaporte', 'el pasaporte internacional', 'los papeles'],
    correctAnswer: 'el pasaporte',
    hint: 'Passport - travel document for international travel, shows nationality',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_013',
    emoji: '🧳',
    question: '¿Dónde guardas tu ropa cuando viajas?',
    options: ['la maleta', 'la valija', 'el equipaje'],
    correctAnswer: 'la maleta',
    hint: 'Suitcase - for packing clothes when traveling, check or carry-on',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_014',
    emoji: '🎒',
    question: '¿Qué llevas en la espalda cuando viajas ligero?',
    options: ['la mochila', 'el morral', 'el macuto'],
    correctAnswer: 'la mochila',
    hint: 'Backpack - bag worn on back, practical for hands-free travel',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_015',
    emoji: '🚦',
    question: '¿Qué controla el tráfico con luces de colores?',
    options: ['el semáforo', 'el disco', 'el faro'],
    correctAnswer: 'el semáforo',
    hint: 'Traffic light - controls traffic with red, yellow, green signals',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },

  // Public Transportation (30 questions)
  {
    id: 'transportation_016',
    emoji: '🚌',
    question: '¿Dónde esperas el autobús?',
    options: ['la parada de autobús', 'la parada', 'el paradero'],
    correctAnswer: 'la parada de autobús',
    hint: 'Bus stop - designated waiting point, usually has schedule posted',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_017',
    emoji: '🎫',
    question: '¿Qué necesitas para viajar en metro?',
    options: ['el boleto', 'el billete', 'el pasaje'],
    correctAnswer: 'el boleto',
    hint: 'Ticket - purchase at station, single or multi-ride pass',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_018',
    emoji: '🚇',
    question: '¿Qué transporte va bajo tierra?',
    options: ['el metro', 'el subterráneo', 'el subte'],
    correctAnswer: 'el metro',
    hint: 'Subway/metro - underground rapid transit, avoids traffic',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_019',
    emoji: '🚉',
    question: '¿Dónde tomas el tren?',
    options: ['la estación de tren', 'la estación', 'la terminal de tren'],
    correctAnswer: 'la estación de tren',
    hint: 'Train station - has platforms and ticket office, major transport hub',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_020',
    emoji: '🚃',
    question: '¿Qué transporte va sobre rieles?',
    options: ['el tren', 'el ferrocarril', 'la locomotora'],
    correctAnswer: 'el tren',
    hint: 'Train - runs on railroad tracks, "rieles" are rails',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_021',
    emoji: '🚆',
    question: '¿Qué tren va entre ciudades muy rápido?',
    options: ['el tren de alta velocidad', 'el tren rápido', 'el AVE'],
    correctAnswer: 'el tren de alta velocidad',
    hint: 'High-speed train - Spain\'s AVE reaches 310 km/h, connects major cities',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_022',
    emoji: '🚊',
    question: '¿Qué transporte eléctrico va por la calle?',
    options: ['el tranvía', 'el tram', 'el tren ligero'],
    correctAnswer: 'el tranvía',
    hint: 'Streetcar/tram - electric, runs on tracks in streets, common in Europe',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_023',
    emoji: '🚎',
    question: '¿Qué autobús usa electricidad?',
    options: ['el trolebús', 'el bus eléctrico', 'el trole'],
    correctAnswer: 'el trolebús',
    hint: 'Trolleybus - electric bus connected to overhead wires, eco-friendly',
    points: 15,
    category: 'transportation',
    difficulty: 'hard',
  },
  {
    id: 'transportation_024',
    emoji: '🚐',
    question: '¿Qué vehículo transporta muchas personas?',
    options: ['la furgoneta', 'la combi', 'la van'],
    correctAnswer: 'la furgoneta',
    hint: 'Van - 8-15 passengers, "combi" in Peru, "micro" in Chile',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_025',
    emoji: '🚍',
    question: '¿Qué autobús lleva estudiantes?',
    options: ['el autobús escolar', 'el bus escolar', 'el camión escolar'],
    correctAnswer: 'el autobús escolar',
    hint: 'School bus - yellow in US, white in Mexico, transports students',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_026',
    emoji: '🚌',
    question: '¿Dónde pagas en el autobús?',
    options: ['al conductor', 'al chofer', 'al operador'],
    correctAnswer: 'al conductor',
    hint: 'To the driver - pay when boarding, exact change often required',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_027',
    emoji: '💳',
    question: '¿Qué tarjeta usas en el transporte público?',
    options: ['la tarjeta de transporte', 'la tarjeta recargable', 'la Tarjeta Multi'],
    correctAnswer: 'la tarjeta de transporte',
    hint: 'Transit card - rechargeable for metro/bus, like Madrid\'s Tarjeta Multi',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_028',
    emoji: '🔔',
    question: '¿Qué presionas para bajar del autobús?',
    options: ['el timbre', 'el botón', 'la campanilla'],
    correctAnswer: 'el timbre',
    hint: 'Bell/buzzer - press to signal driver to stop at next stop',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_029',
    emoji: '🚏',
    question: '¿Dónde está el nombre de la parada?',
    options: ['el letrero', 'el cartel', 'la señal'],
    correctAnswer: 'el letrero',
    hint: 'Sign - displays stop name, route numbers, often has shelter',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_030',
    emoji: '🗺️',
    question: '¿Qué miras para ver las rutas?',
    options: ['el mapa de rutas', 'el plano de rutas', 'el mapa de líneas'],
    correctAnswer: 'el mapa de rutas',
    hint: 'Route map - shows all lines and connections, posted at stations',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_031',
    emoji: '⏱️',
    question: '¿Qué consultas para saber cuándo llega?',
    options: ['el horario', 'el itinerario', 'la frecuencia'],
    correctAnswer: 'el horario',
    hint: 'Schedule/timetable - lists arrival times, weekday vs weekend differ',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_032',
    emoji: '🚇',
    question: '¿Qué línea tomas para ir al centro?',
    options: ['la línea de metro', 'la línea', 'la ruta de metro'],
    correctAnswer: 'la línea de metro',
    hint: 'Metro line - identified by number or color, connects to downtown',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_033',
    emoji: '🔄',
    question: '¿Dónde cambias de línea de metro?',
    options: ['la estación de transferencia', 'la correspondencia', 'el transbordo'],
    correctAnswer: 'la estación de transferencia',
    hint: 'Transfer station - "correspondencia" in Spain, multiple lines intersect',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_034',
    emoji: '🚪',
    question: '¿Por dónde entras al metro?',
    options: ['el torniquete', 'el tornete', 'la barrera'],
    correctAnswer: 'el torniquete',
    hint: 'Turnstile - rotating gate, tap card or insert ticket to enter',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_035',
    emoji: '🎧',
    question: '¿Qué escuchas para saber tu parada?',
    options: ['el anuncio', 'el aviso', 'la notificación'],
    correctAnswer: 'el anuncio',
    hint: 'Announcement - automated voice announces upcoming stops',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_036',
    emoji: '🚌',
    question: '¿Cuál es la primera parada del día?',
    options: ['la terminal', 'la estación terminal', 'la base'],
    correctAnswer: 'la terminal',
    hint: 'Terminal - main station where routes start/end, has facilities',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_037',
    emoji: '🚇',
    question: '¿Qué es la última parada?',
    options: ['el final de línea', 'la terminal', 'la última estación'],
    correctAnswer: 'el final de línea',
    hint: 'End of the line - terminal stop, train reverses direction',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_038',
    emoji: '🧑‍✈️',
    question: '¿Quién conduce el autobús?',
    options: ['el conductor', 'el chofer', 'el operador'],
    correctAnswer: 'el conductor',
    hint: 'Driver - operates bus, "chofer" also used in Latin America',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_039',
    emoji: '👥',
    question: '¿Quién viaja en el autobús?',
    options: ['los pasajeros', 'los viajeros', 'los usuarios'],
    correctAnswer: 'los pasajeros',
    hint: 'Passengers - people riding public transport, from "pasar" (to pass)',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_040',
    emoji: '💺',
    question: '¿Dónde te sientas en el autobús?',
    options: ['el asiento', 'la silla', 'el lugar'],
    correctAnswer: 'el asiento',
    hint: 'Seat - from "asentar" (to settle/sit down), "silla" for chair',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_041',
    emoji: '🧓',
    question: '¿Qué asiento reservas para personas mayores?',
    options: ['el asiento preferencial', 'el asiento de cortesía', 'el asiento reservado'],
    correctAnswer: 'el asiento preferencial',
    hint: 'Priority seat - reserved for elderly, pregnant, disabled passengers',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_042',
    emoji: '🦽',
    question: '¿Qué espacio hay para sillas de ruedas?',
    options: ['el área de accesibilidad', 'el espacio accesible', 'la zona para discapacitados'],
    correctAnswer: 'el área de accesibilidad',
    hint: 'Accessibility area - designated space for wheelchairs, required by law',
    points: 15,
    category: 'transportation',
    difficulty: 'hard',
  },
  {
    id: 'transportation_043',
    emoji: '📱',
    question: '¿Qué app usas para ver horarios?',
    options: ['la app de transporte', 'la aplicación de transporte', 'la app de rutas'],
    correctAnswer: 'la app de transporte',
    hint: 'Transit app - shows real-time schedules, like Moovit or Citymapper',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_044',
    emoji: '⏰',
    question: '¿Cada cuánto pasa el autobús?',
    options: ['la frecuencia', 'el intervalo', 'la periodicidad'],
    correctAnswer: 'la frecuencia',
    hint: 'Frequency - how often buses run, e.g., every 10 minutes',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_045',
    emoji: '🌙',
    question: '¿Qué servicio funciona de noche?',
    options: ['el servicio nocturno', 'el búho', 'el servicio de noche'],
    correctAnswer: 'el servicio nocturno',
    hint: 'Night service - buses/trains that run late hours, "búho" (owl) routes',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },

  // Airport & Air Travel (35 questions)
  {
    id: 'transportation_046',
    emoji: '✈️',
    question: '¿Dónde tomas el avión?',
    options: ['el aeropuerto', 'el puerto aéreo', 'la terminal aérea'],
    correctAnswer: 'el aeropuerto',
    hint: 'Airport - "aero" (air) + "puerto" (port), compound word like English',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_047',
    emoji: '🛫',
    question: '¿Qué hace el avión al salir?',
    options: ['despegar', 'el despegue', 'salir'],
    correctAnswer: 'despegar',
    hint: 'Take off - "des-" (un-) + "pegar" (stick) = unstick from ground',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_048',
    emoji: '🛬',
    question: '¿Qué hace el avión al llegar?',
    options: ['aterrizar', 'el aterrizaje', 'llegar a tierra'],
    correctAnswer: 'aterrizar',
    hint: 'Land - "a-" + "tierra" (earth), to come down to ground',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_049',
    emoji: '🎫',
    question: '¿Qué documento necesitas para volar?',
    options: ['el boleto de avión', 'el pasaje aéreo', 'el billete de avión'],
    correctAnswer: 'el boleto de avión',
    hint: 'Plane ticket - "pasaje" for journey ticket, shows seat and flight info',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_050',
    emoji: '🛂',
    question: '¿Qué documento te piden en el aeropuerto?',
    options: ['el pasaporte', 'el pasaporte internacional', 'los papeles'],
    correctAnswer: 'el pasaporte',
    hint: 'Passport - required for international flights, shows nationality',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_051',
    emoji: '📋',
    question: '¿Dónde haces check-in?',
    options: ['el mostrador', 'el counter', 'la ventanilla'],
    correctAnswer: 'el mostrador',
    hint: 'Counter - desk where you check in, "mostrar" means to show',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_052',
    emoji: '🧳',
    question: '¿Qué entregas en el check-in?',
    options: ['el equipaje', 'las maletas', 'el equipaje facturado'],
    correctAnswer: 'el equipaje',
    hint: 'Luggage - checked bags stored in cargo hold during flight',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_053',
    emoji: '🎒',
    question: '¿Qué llevas contigo en el avión?',
    options: ['el equipaje de mano', 'el carry-on', 'el equipaje de cabina'],
    correctAnswer: 'el equipaje de mano',
    hint: 'Carry-on bag - "de mano" (by hand), fits in overhead bin',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_054',
    emoji: '🔖',
    question: '¿Qué recibes al hacer check-in?',
    options: ['el pase de abordar', 'la tarjeta de embarque', 'el boarding pass'],
    correctAnswer: 'el pase de abordar',
    hint: 'Boarding pass - shows seat, gate, boarding time, "tarjeta de embarque"',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_055',
    emoji: '🛃',
    question: '¿Por dónde pasas con tu equipaje?',
    options: ['la seguridad', 'el control de seguridad', 'el filtro de seguridad'],
    correctAnswer: 'la seguridad',
    hint: 'Security checkpoint - screening for dangerous items before boarding',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_056',
    emoji: '🔍',
    question: '¿Qué máquina revisa tu equipaje?',
    options: ['el escáner', 'el escáner de rayos X', 'la máquina de rayos X'],
    correctAnswer: 'el escáner',
    hint: 'X-ray scanner - examines bag contents for security',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_057',
    emoji: '🚪',
    question: '¿Dónde esperas para abordar?',
    options: ['la puerta de embarque', 'la puerta', 'la gate'],
    correctAnswer: 'la puerta de embarque',
    hint: 'Boarding gate - numbered departure area, "embarcar" (to board)',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_058',
    emoji: '🏢',
    question: '¿Qué edificio tiene las puertas de embarque?',
    options: ['la terminal', 'la terminal aérea', 'el edificio del aeropuerto'],
    correctAnswer: 'la terminal',
    hint: 'Terminal - airport building with gates, check-in, shops',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_059',
    emoji: '⏰',
    question: '¿A qué hora sale el vuelo?',
    options: ['la hora de salida', 'la hora de partida', 'la hora de despegue'],
    correctAnswer: 'la hora de salida',
    hint: 'Departure time - when plane leaves, board 30-45 minutes before',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_060',
    emoji: '🕐',
    question: '¿A qué hora llega el vuelo?',
    options: ['la hora de llegada', 'la hora de arribo', 'la hora de aterrizaje'],
    correctAnswer: 'la hora de llegada',
    hint: 'Arrival time - when plane lands at destination airport',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_061',
    emoji: '⏱️',
    question: '¿Cuánto tarda el vuelo?',
    options: ['la duración del vuelo', 'el tiempo de vuelo', 'las horas de vuelo'],
    correctAnswer: 'la duración del vuelo',
    hint: 'Flight duration - total time in air, e.g., Madrid-NYC 8 hours',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_062',
    emoji: '🔄',
    question: '¿Qué vuelo hace parada en otra ciudad?',
    options: ['el vuelo con escala', 'el vuelo con conexión', 'el vuelo con parada'],
    correctAnswer: 'el vuelo con escala',
    hint: 'Flight with layover - "escala" is stopover, change planes or wait',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_063',
    emoji: '➡️',
    question: '¿Qué vuelo no hace paradas?',
    options: ['el vuelo directo', 'el vuelo sin escala', 'el vuelo nonstop'],
    correctAnswer: 'el vuelo directo',
    hint: 'Direct flight - nonstop from origin to destination, faster',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_064',
    emoji: '❌',
    question: '¿Qué pasa si el vuelo no sale?',
    options: ['el vuelo cancelado', 'la cancelación', 'el vuelo anulado'],
    correctAnswer: 'el vuelo cancelado',
    hint: 'Cancelled flight - due to weather, technical issues, get refund',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_065',
    emoji: '⏰',
    question: '¿Qué pasa si el vuelo sale tarde?',
    options: ['el vuelo retrasado', 'el retraso', 'el vuelo demorado'],
    correctAnswer: 'el vuelo retrasado',
    hint: 'Delayed flight - "retraso" is delay, departs later than scheduled',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_066',
    emoji: '🎫',
    question: '¿Dónde está tu número de asiento?',
    options: ['en el pase de abordar', 'en la tarjeta de embarque', 'en el boarding pass'],
    correctAnswer: 'en el pase de abordar',
    hint: 'On boarding pass - shows row number and letter (A, B, C, etc.)',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_067',
    emoji: '💺',
    question: '¿Qué asiento está junto a la ventana?',
    options: ['el asiento de ventana', 'el asiento de ventanilla', 'el window seat'],
    correctAnswer: 'el asiento de ventana',
    hint: 'Window seat - best for views, usually A or F in row',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_068',
    emoji: '🚶',
    question: '¿Qué asiento está junto al pasillo?',
    options: ['el asiento de pasillo', 'el aisle seat', 'el asiento del corredor'],
    correctAnswer: 'el asiento de pasillo',
    hint: 'Aisle seat - easy bathroom access, usually C or D in row',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_069',
    emoji: '🧑‍✈️',
    question: '¿Quién pilotea el avión?',
    options: ['el piloto', 'el capitán', 'el aviador'],
    correctAnswer: 'el piloto',
    hint: 'Pilot - flies the plane, "capitán" for captain, co-pilot assists',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_070',
    emoji: '👩‍✈️',
    question: '¿Quién te atiende en el avión?',
    options: ['la azafata', 'el auxiliar de vuelo', 'la sobrecargo'],
    correctAnswer: 'la azafata',
    hint: 'Flight attendant - serves food, safety demo, "auxiliar de vuelo" neutral',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_071',
    emoji: '🔒',
    question: '¿Qué te pones al sentarte?',
    options: ['el cinturón de seguridad', 'el cinturón', 'el seatbelt'],
    correctAnswer: 'el cinturón de seguridad',
    hint: 'Seatbelt - mandatory during takeoff, landing, turbulence',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_072',
    emoji: '🎒',
    question: '¿Dónde guardas tu mochila?',
    options: ['el compartimento superior', 'el compartimiento superior', 'el overhead bin'],
    correctAnswer: 'el compartimento superior',
    hint: 'Overhead bin - "compartimiento" stores carry-on luggage above seats',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_073',
    emoji: '🍽️',
    question: '¿Qué te dan de comer en el avión?',
    options: ['la comida de avión', 'el servicio de comida', 'la comida a bordo'],
    correctAnswer: 'la comida de avión',
    hint: 'Airline meal - served on international flights, request special diets',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_074',
    emoji: '🥤',
    question: '¿Qué bebes en el avión?',
    options: ['la bebida', 'el refresco', 'la gaseosa'],
    correctAnswer: 'la bebida',
    hint: 'Beverage - water, juice, soda, coffee served during flight',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_075',
    emoji: '🎬',
    question: '¿Qué ves en la pantalla?',
    options: ['la película', 'el filme', 'el entretenimiento'],
    correctAnswer: 'la película',
    hint: 'Movie - in-flight entertainment, "entretenimiento a bordo"',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_076',
    emoji: '🎧',
    question: '¿Qué usas para escuchar música?',
    options: ['los audífonos', 'los auriculares', 'los headphones'],
    correctAnswer: 'los audífonos',
    hint: 'Headphones - "auriculares" in Spain, provided by airline',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_077',
    emoji: '🛄',
    question: '¿Dónde recoges tu maleta al llegar?',
    options: ['la recogida de equipaje', 'el carrusel de equipaje', 'la entrega de equipaje'],
    correctAnswer: 'la recogida de equipaje',
    hint: 'Baggage claim - carousel spins checked luggage after landing',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_078',
    emoji: '🛅',
    question: '¿Dónde declaras tus compras?',
    options: ['la aduana', 'el control aduanal', 'la aduana y migración'],
    correctAnswer: 'la aduana',
    hint: 'Customs - declare goods, "aduanero" is customs officer',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_079',
    emoji: '🚁',
    question: '¿Qué vuela sin alas?',
    options: ['el helicóptero', 'el helicóptero civil', 'el helicóptero de rescate'],
    correctAnswer: 'el helicóptero',
    hint: 'Helicopter - uses rotors, Greek "helix" (spiral) + "pteron" (wing)',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_080',
    emoji: '🛩️',
    question: '¿Qué avión es pequeño y privado?',
    options: ['la avioneta', 'el avión pequeño', 'el avioncito'],
    correctAnswer: 'la avioneta',
    hint: 'Small plane - diminutive of "avión", seats 2-10 people',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },

  // Cars & Road Travel (35 questions)
  {
    id: 'transportation_081',
    emoji: '🚗',
    question: '¿Quién maneja el coche?',
    options: ['el conductor', 'el chofer', 'el motorista'],
    correctAnswer: 'el conductor',
    hint: 'Driver - "manejar" in Latin America, "conducir" in Spain',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_082',
    emoji: '🔑',
    question: '¿Qué necesitas para encender el coche?',
    options: ['la llave', 'la llave del coche', 'la llave del carro'],
    correctAnswer: 'la llave',
    hint: 'Key - traditional metal or keyless fob, insert or push button',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_083',
    emoji: '⛽',
    question: '¿Dónde pones gasolina?',
    options: ['la gasolinera', 'la estación de servicio', 'la bomba'],
    correctAnswer: 'la gasolinera',
    hint: 'Gas station - "estación de servicio" also used, fill tank with fuel',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_084',
    emoji: '🚙',
    question: '¿Dónde te sientas para manejar?',
    options: ['el asiento del conductor', 'el asiento delantero', 'el seat del conductor'],
    correctAnswer: 'el asiento del conductor',
    hint: 'Driver\'s seat - left in most countries, right in UK/Japan',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_085',
    emoji: '🔧',
    question: '¿Dónde arreglan tu coche?',
    options: ['el taller mecánico', 'el taller', 'el mecánico'],
    correctAnswer: 'el taller mecánico',
    hint: 'Mechanic shop - repairs cars, "mecánico" is mechanic',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_086',
    emoji: '🛞',
    question: '¿Qué rodea las llantas del coche?',
    options: ['los neumáticos', 'las gomas', 'los cauchos'],
    correctAnswer: 'los neumáticos',
    hint: 'Tires - "gomas" in some regions, from Greek "pneuma" (air)',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_087',
    emoji: '🚨',
    question: '¿Qué suena en emergencia?',
    options: ['la sirena', 'la alarma', 'la bocina de emergencia'],
    correctAnswer: 'la sirena',
    hint: 'Siren - emergency vehicles, from Greek myth of alluring singers',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_088',
    emoji: '🚦',
    question: '¿Qué color significa "alto"?',
    options: ['el rojo', 'el color rojo', 'la luz roja'],
    correctAnswer: 'el rojo',
    hint: 'Red - stop completely, universal traffic signal worldwide',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_089',
    emoji: '🚦',
    question: '¿Qué color significa "continuar"?',
    options: ['el verde', 'el color verde', 'la luz verde'],
    correctAnswer: 'el verde',
    hint: 'Green - go/proceed, safe to continue through intersection',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_090',
    emoji: '🚦',
    question: '¿Qué color significa "precaución"?',
    options: ['el amarillo', 'el ámbar', 'el color amarillo'],
    correctAnswer: 'el amarillo',
    hint: 'Yellow - caution/slow down, prepare to stop, "ámbar" also used',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_091',
    emoji: '🛑',
    question: '¿Qué señal significa que debes parar?',
    options: ['el alto', 'el stop', 'la señal de alto'],
    correctAnswer: 'el alto',
    hint: 'Stop sign - octagonal red sign, mandatory full stop',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_092',
    emoji: '⚠️',
    question: '¿Qué señal te advierte de peligro?',
    options: ['la señal de peligro', 'la señal de advertencia', 'el aviso de peligro'],
    correctAnswer: 'la señal de peligro',
    hint: 'Warning sign - yellow triangle, alerts to hazards ahead',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_093',
    emoji: '📏',
    question: '¿Qué número indica qué tan rápido puedes ir?',
    options: ['el límite de velocidad', 'la velocidad máxima', 'el speed limit'],
    correctAnswer: 'el límite de velocidad',
    hint: 'Speed limit - posted in km/h in most countries, mph in US/UK',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_094',
    emoji: '🅿️',
    question: '¿Dónde dejas tu coche?',
    options: ['el estacionamiento', 'el aparcamiento', 'el parqueadero'],
    correctAnswer: 'el estacionamiento',
    hint: 'Parking - "aparcamiento" in Spain, "parqueadero" in some regions',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_095',
    emoji: '🛣️',
    question: '¿Qué vía conecta ciudades?',
    options: ['la autopista', 'la carretera', 'la autovía'],
    correctAnswer: 'la autopista',
    hint: 'Highway - high-speed multi-lane road, "carretera" also used',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_096',
    emoji: '🌉',
    question: '¿Qué cruzas sobre el río?',
    options: ['el puente', 'el viaducto', 'el paso elevado'],
    correctAnswer: 'el puente',
    hint: 'Bridge - crosses water or valley, from Latin "pons"',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_097',
    emoji: '🚇',
    question: '¿Qué cruzas bajo la montaña?',
    options: ['el túnel', 'el paso subterráneo', 'el tubo'],
    correctAnswer: 'el túnel',
    hint: 'Tunnel - underground passage through mountain or under water',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_098',
    emoji: '🔀',
    question: '¿Dónde se cruzan dos carreteras?',
    options: ['la intersección', 'el cruce', 'el cruce de caminos'],
    correctAnswer: 'la intersección',
    hint: 'Intersection - "cruce" also used, where roads meet',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_099',
    emoji: '↩️',
    question: '¿Cómo vuelves en dirección contraria?',
    options: ['la vuelta en U', 'el retorno', 'la U-turn'],
    correctAnswer: 'la vuelta en U',
    hint: 'U-turn - 180-degree turn, illegal in some locations',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_100',
    emoji: '🔄',
    question: '¿Qué círculo de tráfico reemplaza semáforos?',
    options: ['la rotonda', 'la glorieta', 'el roundabout'],
    correctAnswer: 'la rotonda',
    hint: 'Roundabout - traffic circle, "glorieta" in Spain, yield to left',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_101',
    emoji: '🚗',
    question: '¿Qué carril es para ir más rápido?',
    options: ['el carril izquierdo', 'el carril de adelantamiento', 'el fast lane'],
    correctAnswer: 'el carril izquierdo',
    hint: 'Left lane - passing lane, return to right after overtaking',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_102',
    emoji: '🚙',
    question: '¿En qué carril van los coches lentos?',
    options: ['el carril derecho', 'el carril lento', 'el slow lane'],
    correctAnswer: 'el carril derecho',
    hint: 'Right lane - for slower traffic, trucks often required here',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_103',
    emoji: '💸',
    question: '¿Dónde pagas para usar la autopista?',
    options: ['la caseta de peaje', 'el peaje', 'la cabina de peaje'],
    correctAnswer: 'la caseta de peaje',
    hint: 'Toll booth - "peaje" is toll, pay for highway use',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_104',
    emoji: '🚧',
    question: '¿Qué bloquea la carretera?',
    options: ['la obra en construcción', 'las obras', 'la construcción vial'],
    correctAnswer: 'la obra en construcción',
    hint: 'Construction zone - road work ahead, reduce speed',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_105',
    emoji: '🚗',
    question: '¿Qué haces cuando muchos coches van lento?',
    options: ['el tráfico', 'el embotellamiento', 'el tránsito'],
    correctAnswer: 'el tráfico',
    hint: 'Traffic - congestion, "embotellamiento" (bottleneck) for traffic jam',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_106',
    emoji: '🚘',
    question: '¿Qué servicio te lleva a donde quieras?',
    options: ['el taxi', 'el cab', 'el libre'],
    correctAnswer: 'el taxi',
    hint: 'Taxi - hail on street or call, meter shows fare',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_107',
    emoji: '📱',
    question: '¿Qué app pides para transporte privado?',
    options: ['la app de viajes compartidos', 'el rideshare', 'la app de taxi'],
    correctAnswer: 'la app de viajes compartidos',
    hint: 'Rideshare app - Uber, Lyft, Cabify, DiDi in different countries',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_108',
    emoji: '🚗',
    question: '¿Qué alquilas para manejar tú mismo?',
    options: ['el coche de alquiler', 'el carro de renta', 'el rental car'],
    correctAnswer: 'el coche de alquiler',
    hint: 'Rental car - "coche de renta" in Mexico, need driver\'s license',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_109',
    emoji: '🪪',
    question: '¿Qué licencia necesitas para manejar?',
    options: ['la licencia de conducir', 'el carnet de conducir', 'la licencia de manejo'],
    correctAnswer: 'la licencia de conducir',
    hint: 'Driver\'s license - "carnet de conducir" in Spain, required document',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_110',
    emoji: '🚓',
    question: '¿Quién te para si manejas mal?',
    options: ['el policía de tránsito', 'el policía de tráfico', 'el agente de tránsito'],
    correctAnswer: 'el policía de tránsito',
    hint: 'Traffic police - enforces road laws, "tráfico" in Spain',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_111',
    emoji: '💰',
    question: '¿Qué pagas si violas las reglas?',
    options: ['la multa', 'la infracción', 'la sanción'],
    correctAnswer: 'la multa',
    hint: 'Fine - penalty for traffic violations, speeding, parking illegally',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_112',
    emoji: '🚑',
    question: '¿Qué vehículo lleva enfermos?',
    options: ['la ambulancia', 'el vehículo de emergencia', 'el carro de emergencia'],
    correctAnswer: 'la ambulancia',
    hint: 'Ambulance - emergency medical transport, from French "ambulant" (mobile)',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_113',
    emoji: '🚒',
    question: '¿Qué vehículo apaga incendios?',
    options: ['el camión de bomberos', 'el carro de bomberos', 'la bomba'],
    correctAnswer: 'el camión de bomberos',
    hint: 'Fire truck - carries firefighters and water, "carro de bomberos" also',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_114',
    emoji: '🚚',
    question: '¿Qué vehículo transporta mercancía?',
    options: ['el camión', 'el truck', 'el camión de carga'],
    correctAnswer: 'el camión',
    hint: 'Truck - for cargo/goods, "camión" means bus in Mexico',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_115',
    emoji: '🚛',
    question: '¿Qué camión lleva contenedor?',
    options: ['el tractocamión', 'el tráiler', 'el semi'],
    correctAnswer: 'el tractocamión',
    hint: 'Semi-truck - tractor-trailer, "trailer" also used in Latin America',
    points: 15,
    category: 'transportation',
    difficulty: 'hard',
  },

  // Water & Other Transport (35 questions)
  {
    id: 'transportation_116',
    emoji: '⛴️',
    question: '¿Dónde salen los barcos?',
    options: ['el puerto', 'el puerto marítimo', 'el muelle'],
    correctAnswer: 'el puerto',
    hint: 'Port/harbor - where boats dock, from Latin "portus" (harbor)',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_117',
    emoji: '🚢',
    question: '¿Qué barco lleva pasajeros de vacaciones?',
    options: ['el crucero', 'el barco de crucero', 'el cruise ship'],
    correctAnswer: 'el crucero',
    hint: 'Cruise ship - luxury vacation vessel, "cruising" for pleasure',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_118',
    emoji: '⛴️',
    question: '¿Qué barco cruza el río?',
    options: ['el ferry', 'el transbordador', 'el ferri'],
    correctAnswer: 'el ferry',
    hint: 'Ferry - transports cars and people across water, short routes',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_119',
    emoji: '🛥️',
    question: '¿Qué barco privado y lujoso?',
    options: ['el yate', 'el yacht', 'la embarcación de lujo'],
    correctAnswer: 'el yate',
    hint: 'Yacht - luxury private boat, from Dutch "jacht" (hunting ship)',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_120',
    emoji: '🚤',
    question: '¿Qué barco pequeño va rápido?',
    options: ['la lancha', 'la lancha motora', 'la lancha rápida'],
    correctAnswer: 'la lancha',
    hint: 'Speedboat/motorboat - fast with outboard motor, for water sports',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_121',
    emoji: '🛶',
    question: '¿Qué barco pequeño usas con remo?',
    options: ['la canoa', 'el kayak', 'el bote de remos'],
    correctAnswer: 'la canoa',
    hint: 'Canoe - paddled manually, from Carib "kenu", ancient watercraft',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_122',
    emoji: '🚣',
    question: '¿Qué usas para mover la canoa?',
    options: ['el remo', 'la pala', 'el paddle'],
    correctAnswer: 'el remo',
    hint: 'Paddle/oar - "remar" to row, moves boat through water',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_123',
    emoji: '⛵',
    question: '¿Qué barco usa el viento?',
    options: ['el velero', 'el bote de vela', 'el sailboat'],
    correctAnswer: 'el velero',
    hint: 'Sailboat - "vela" is sail, powered by wind, eco-friendly',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_124',
    emoji: '⚓',
    question: '¿Qué baja el barco para no moverse?',
    options: ['el ancla', 'el anchor', 'el áncora'],
    correctAnswer: 'el ancla',
    hint: 'Anchor - heavy metal, holds boat in place, "levar ancla" to lift',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_125',
    emoji: '🧑‍✈️',
    question: '¿Quién dirige el barco?',
    options: ['el capitán', 'el patrón', 'el comandante'],
    correctAnswer: 'el capitán',
    hint: 'Captain - commands ship, "marinero" is sailor, from Latin "caput" (head)',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_126',
    emoji: '🛟',
    question: '¿Qué usas en emergencia en el agua?',
    options: ['el salvavidas', 'el chaleco salvavidas', 'el flotador'],
    correctAnswer: 'el salvavidas',
    hint: 'Life preserver - keeps you afloat, "salva" (saves) + "vidas" (lives)',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_127',
    emoji: '🚲',
    question: '¿Qué vehículo tiene dos ruedas y pedales?',
    options: ['la bicicleta', 'la bici', 'el velocípedo'],
    correctAnswer: 'la bicicleta',
    hint: 'Bicycle - "bi" (two) + "cycle" (wheels), eco-friendly transport',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_128',
    emoji: '🏍️',
    question: '¿Qué vehículo tiene motor y dos ruedas?',
    options: ['la motocicleta', 'la moto', 'el motociclo'],
    correctAnswer: 'la motocicleta',
    hint: 'Motorcycle - motorized bicycle, "moto" for short, requires license',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_129',
    emoji: '🛴',
    question: '¿Qué usas parado con dos ruedas?',
    options: ['la patineta', 'el scooter', 'el patín'],
    correctAnswer: 'la patineta',
    hint: 'Scooter - stand and push, "patineta eléctrica" is electric version',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_130',
    emoji: '🛹',
    question: '¿Qué tabla tiene ruedas?',
    options: ['la patineta', 'el skateboard', 'la tabla de patinar'],
    correctAnswer: 'la patineta',
    hint: 'Skateboard - for tricks, "tabla" is board, four small wheels',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_131',
    emoji: '🛼',
    question: '¿Qué zapatos tienen ruedas?',
    options: ['los patines', 'los roller skates', 'los patines de ruedas'],
    correctAnswer: 'los patines',
    hint: 'Roller skates - wheels on shoes, "patinar" to skate, inline or quad',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_132',
    emoji: '🚡',
    question: '¿Qué cable sube la montaña?',
    options: ['el teleférico', 'el cable car', 'el funicular'],
    correctAnswer: 'el teleférico',
    hint: 'Cable car - aerial lift, "tele" (far) + "férico" (carrying), for skiing',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_133',
    emoji: '🚠',
    question: '¿Qué transporte cuelga de cables?',
    options: ['la góndola', 'el teleféricode góndola', 'el cable car'],
    correctAnswer: 'la góndola',
    hint: 'Gondola - suspended cable car, famous in Venice and ski resorts',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_134',
    emoji: '🚟',
    question: '¿Qué tren va suspendido?',
    options: ['el monorraíl', 'el monoriel', 'el monorrail'],
    correctAnswer: 'el monorraíl',
    hint: 'Monorail - single rail track, elevated or suspended, Disney famous for',
    points: 15,
    category: 'transportation',
    difficulty: 'hard',
  },
  {
    id: 'transportation_135',
    emoji: '🚝',
    question: '¿Qué tren usa imanes para flotar?',
    options: ['el tren de levitación magnética', 'el maglev', 'el tren magnético'],
    correctAnswer: 'el tren de levitación magnética',
    hint: 'Maglev train - magnetic levitation, no friction, 600+ km/h in Japan',
    points: 15,
    category: 'transportation',
    difficulty: 'hard',
  },
  {
    id: 'transportation_136',
    emoji: '🐴',
    question: '¿Qué animal montas para viajar?',
    options: ['el caballo', 'el equino', 'el corcel'],
    correctAnswer: 'el caballo',
    hint: 'Horse - traditional transport, "montar a caballo" to ride horseback',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_137',
    emoji: '🐫',
    question: '¿Qué animal montas en el desierto?',
    options: ['el camello', 'el dromedario', 'la caravana'],
    correctAnswer: 'el camello',
    hint: 'Camel - desert transport, stores water in hump, "ship of the desert"',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_138',
    emoji: '🐘',
    question: '¿Qué animal grande montas en Asia?',
    options: ['el elefante', 'el paquidermo', 'el animal de carga'],
    correctAnswer: 'el elefante',
    hint: 'Elephant - traditional in India/Thailand, carries tourists on back',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_139',
    emoji: '🚶',
    question: '¿Cómo viajas a pie?',
    options: ['caminar', 'andar', 'ir a pie'],
    correctAnswer: 'caminar',
    hint: 'Walking - most basic transport, "ir a pie" (go on foot)',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_140',
    emoji: '🏃',
    question: '¿Cómo vas más rápido que caminando?',
    options: ['correr', 'trotar', 'sprintar'],
    correctAnswer: 'correr',
    hint: 'Running - faster than walking, "trotar" to jog at medium pace',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_141',
    emoji: '🚶',
    question: '¿Quién camina por la calle?',
    options: ['el peatón', 'el caminante', 'el transeúnte'],
    correctAnswer: 'el peatón',
    hint: 'Pedestrian - person on foot, from Latin "pedester" (on foot)',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_142',
    emoji: '🚸',
    question: '¿Dónde cruzan los peatones?',
    options: ['el paso de peatones', 'el paso de cebra', 'el cruce peatonal'],
    correctAnswer: 'el paso de peatones',
    hint: 'Crosswalk - marked pedestrian crossing, "paso de cebra" (zebra crossing) for stripes',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_143',
    emoji: '🌉',
    question: '¿Qué puente es solo para peatones?',
    options: ['el puente peatonal', 'la pasarela', 'el paso elevado'],
    correctAnswer: 'el puente peatonal',
    hint: 'Pedestrian bridge - footbridge, crosses roads safely, "pasarela" also used',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_144',
    emoji: '🚶',
    question: '¿Dónde caminas junto a la calle?',
    options: ['la acera', 'la banqueta', 'la vereda'],
    correctAnswer: 'la acera',
    hint: 'Sidewalk - "banqueta" in Mexico, "vereda" in some countries',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_145',
    emoji: '🚴',
    question: '¿Dónde van las bicicletas?',
    options: ['la ciclovía', 'el carril bici', 'la pista de bici'],
    correctAnswer: 'la ciclovía',
    hint: 'Bike lane - dedicated path for cyclists, promotes safe cycling',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_146',
    emoji: '🪖',
    question: '¿Qué proteges con casco?',
    options: ['la cabeza', 'el cráneo', 'la testa'],
    correctAnswer: 'la cabeza',
    hint: 'Head - helmet protects skull in accidents, mandatory for motorcycles',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_147',
    emoji: '🦺',
    question: '¿Qué usas para ser visible?',
    options: ['el chaleco reflectante', 'el chaleco de seguridad', 'el vest reflectante'],
    correctAnswer: 'el chaleco reflectante',
    hint: 'Reflective vest - hi-vis safety gear, required for roadside emergencies',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_148',
    emoji: '🔋',
    question: '¿Qué vehículo usa electricidad?',
    options: ['el coche eléctrico', 'el auto eléctrico', 'el vehículo eléctrico'],
    correctAnswer: 'el coche eléctrico',
    hint: 'Electric car - battery powered, zero emissions, Tesla pioneered',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_149',
    emoji: '🔌',
    question: '¿Dónde cargas el coche eléctrico?',
    options: ['la estación de carga', 'el cargador', 'el punto de recarga'],
    correctAnswer: 'la estación de carga',
    hint: 'Charging station - "cargador" for charger, plug in to recharge battery',
    points: 10,
    category: 'transportation',
    difficulty: 'medium',
  },
  {
    id: 'transportation_150',
    emoji: '🚗',
    question: '¿Qué coche se maneja solo?',
    options: ['el coche autónomo', 'el coche automático', 'el self-driving car'],
    correctAnswer: 'el coche autónomo',
    hint: 'Self-driving car - autonomous vehicle uses AI, future of transport',
    points: 15,
    category: 'transportation',
    difficulty: 'hard',
  },
  {
    id: 'transportation_151',
    emoji: '🌁',
    question: '¿Qué estructura cruza un río o valle?',
    options: ['el puente', 'el túnel', 'la carretera'],
    correctAnswer: 'el puente',
    hint: 'Bridge - structure that spans across obstacles like rivers or valleys',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_152',
    emoji: '⛽️',
    question: '¿Dónde llenas el tanque de gasolina?',
    options: ['la gasolinera', 'el estacionamiento', 'el taller'],
    correctAnswer: 'la gasolinera',
    hint: 'Petrol station - where you fill up your car with gas/petrol',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
  {
    id: 'transportation_153',
    emoji: '👩🏻‍🔧',
    question: '¿Quién repara tu coche cuando se avería?',
    options: ['el mecánico', 'el conductor', 'el policía'],
    correctAnswer: 'el mecánico',
    hint: 'Mechanic - person who repairs and maintains vehicles',
    points: 5,
    category: 'transportation',
    difficulty: 'easy',
  },
];
