/**
 * WEATHER & ENVIRONMENT Category Questions
 * Category: weather
 */

export const weatherQuestions = [
  // Basic Weather Conditions (1-20)
  {
    id: 'weather_001',
    emoji: '☀️',
    question: '¿Qué tiempo hace cuando no hay nubes?',
    options: ['hace sol', 'llueve', 'nieva'],
    correctAnswer: 'hace sol',
    hint: 'Sunny - "sol" means sun, clear sky weather',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_002',
    emoji: '🌧️',
    question: '¿Qué tiempo hace cuando cae agua del cielo?',
    options: ['llueve', 'nieva', 'hace viento'],
    correctAnswer: 'llueve',
    hint: 'Rain - from verb "llover" (to rain)',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_003',
    emoji: '❄️',
    question: '¿Qué cae del cielo cuando hace mucho frío?',
    options: ['nieve', 'lluvia', 'granizo'],
    correctAnswer: 'nieve',
    hint: 'Snow - white and cold, winter precipitation',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_004',
    emoji: '💨',
    question: '¿Qué tiempo hace cuando se mueven las ramas?',
    options: ['hace viento', 'hace calor', 'hace frío'],
    correctAnswer: 'hace viento',
    hint: 'Windy - "viento" means wind, air movement',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_005',
    emoji: '☁️',
    question: '¿Qué hay en el cielo cuando está gris?',
    options: ['nubes', 'estrellas', 'arcoíris'],
    correctAnswer: 'nubes',
    hint: 'Clouds - plural of "nube", cover the sky',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_006',
    emoji: '🌡️',
    question: '¿Cómo está el tiempo cuando hace 35 grados?',
    options: ['hace calor', 'hace frío', 'llueve'],
    correctAnswer: 'hace calor',
    hint: 'Hot - "calor" means heat, high temperature',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_007',
    emoji: '🥶',
    question: '¿Cómo está el tiempo cuando hace 0 grados?',
    options: ['hace frío', 'hace calor', 'hace viento'],
    correctAnswer: 'hace frío',
    hint: 'Cold - "frío" means cold, low temperature',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_008',
    emoji: '⛈️',
    question: '¿Qué tiempo hace durante una tormenta?',
    options: ['truena', 'nieva', 'hace sol'],
    correctAnswer: 'truena',
    hint: 'Thunder - from "trueno" (thunder), storms have thunder',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_009',
    emoji: '⚡',
    question: '¿Qué se ve en el cielo durante una tormenta?',
    options: ['relámpagos', 'estrellas', 'arcoíris'],
    correctAnswer: 'relámpagos',
    hint: 'Lightning - electrical discharge in storms',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_010',
    emoji: '🌈',
    question: '¿Qué aparece después de la lluvia con sol?',
    options: ['arcoíris', 'nubes', 'nieve'],
    correctAnswer: 'arcoíris',
    hint: 'Rainbow - "arco" (arc) + "iris" (iris), colorful arc',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_011',
    emoji: '🌫️',
    question: '¿Qué hay cuando no se ve bien por la mañana?',
    options: ['niebla', 'nieve', 'viento'],
    correctAnswer: 'niebla',
    hint: 'Fog - reduces visibility, common in mornings',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_012',
    emoji: '🌪️',
    question: '¿Cómo se llama el viento muy fuerte que gira?',
    options: ['tornado', 'huracán', 'brisa'],
    correctAnswer: 'tornado',
    hint: 'Tornado - spinning wind funnel, very dangerous',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_013',
    emoji: '🌀',
    question: '¿Cómo se llama la tormenta tropical muy grande?',
    options: ['huracán', 'tornado', 'tormenta'],
    correctAnswer: 'huracán',
    hint: 'Hurricane - large tropical storm system',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_014',
    emoji: '🧊',
    question: '¿Qué cae del cielo en forma de bolas de hielo?',
    options: ['granizo', 'nieve', 'escarcha'],
    correctAnswer: 'granizo',
    hint: 'Hail - ice pellets that fall during storms',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_015',
    emoji: '💧',
    question: '¿Cómo se llama la humedad en la mañana?',
    options: ['rocío', 'lluvia', 'niebla'],
    correctAnswer: 'rocío',
    hint: 'Dew - morning moisture on grass and plants',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_016',
    emoji: '🌬️',
    question: '¿Cómo se llama el viento suave?',
    options: ['brisa', 'huracán', 'tornado'],
    correctAnswer: 'brisa',
    hint: 'Breeze - gentle wind, pleasant on warm days',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_017',
    emoji: '🌡️',
    question: '¿Qué usamos para medir la temperatura?',
    options: ['termómetro', 'barómetro', 'anemómetro'],
    correctAnswer: 'termómetro',
    hint: 'Thermometer - measures hot and cold temperatures',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_018',
    emoji: '💦',
    question: '¿Cómo se llama el porcentaje de agua en el aire?',
    options: ['humedad', 'precipitación', 'temperatura'],
    correctAnswer: 'humedad',
    hint: 'Humidity - moisture content in the atmosphere',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_019',
    emoji: '🌅',
    question: '¿Cuándo sale el sol?',
    options: ['al amanecer', 'al anochecer', 'a mediodía'],
    correctAnswer: 'al amanecer',
    hint: 'Sunrise - dawn, when day begins',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_020',
    emoji: '🌇',
    question: '¿Cuándo se pone el sol?',
    options: ['al atardecer', 'al amanecer', 'a mediodía'],
    correctAnswer: 'al atardecer',
    hint: 'Sunset - evening, when day ends',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },

  // Seasons (21-30)
  {
    id: 'weather_021',
    emoji: '🌸',
    question: '¿En qué estación florecen las plantas?',
    options: ['primavera', 'invierno', 'otoño'],
    correctAnswer: 'primavera',
    hint: 'Spring - season of flowers and new growth',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_022',
    emoji: '☀️',
    question: '¿En qué estación hace más calor?',
    options: ['verano', 'invierno', 'primavera'],
    correctAnswer: 'verano',
    hint: 'Summer - hottest season, vacation time',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_023',
    emoji: '🍂',
    question: '¿En qué estación caen las hojas?',
    options: ['otoño', 'primavera', 'verano'],
    correctAnswer: 'otoño',
    hint: 'Autumn/Fall - leaves change colors and fall',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_024',
    emoji: '⛄',
    question: '¿En qué estación nieva más?',
    options: ['invierno', 'verano', 'primavera'],
    correctAnswer: 'invierno',
    hint: 'Winter - coldest season, snow and ice',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_025',
    emoji: '🌻',
    question: '¿Cuántas estaciones hay en un año?',
    options: ['cuatro', 'tres', 'cinco'],
    correctAnswer: 'cuatro',
    hint: 'Four seasons - spring, summer, autumn, winter',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_026',
    emoji: '🏖️',
    question: '¿Qué estación es perfecta para la playa?',
    options: ['verano', 'invierno', 'otoño'],
    correctAnswer: 'verano',
    hint: 'Summer - warm weather perfect for beach',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_027',
    emoji: '🍁',
    question: '¿De qué color están las hojas en otoño?',
    options: ['naranjas y rojas', 'verdes', 'blancas'],
    correctAnswer: 'naranjas y rojas',
    hint: 'Orange and red - autumn leaf colors',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_028',
    emoji: '🌷',
    question: '¿Qué flores son típicas de la primavera?',
    options: ['tulipanes', 'girasoles', 'crisantemos'],
    correctAnswer: 'tulipanes',
    hint: 'Tulips - classic spring flowers',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_029',
    emoji: '🎿',
    question: '¿En qué estación se practica el esquí?',
    options: ['invierno', 'verano', 'primavera'],
    correctAnswer: 'invierno',
    hint: 'Winter - skiing needs snow and cold',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_030',
    emoji: '🌾',
    question: '¿En qué estación se cosechan muchos cultivos?',
    options: ['otoño', 'invierno', 'primavera'],
    correctAnswer: 'otoño',
    hint: 'Autumn - harvest season for many crops',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },

  // Climate & Geography (31-45)
  {
    id: 'weather_031',
    emoji: '🏜️',
    question: '¿Cómo es el clima en el desierto?',
    options: ['seco y caluroso', 'húmedo y frío', 'lluvioso'],
    correctAnswer: 'seco y caluroso',
    hint: 'Desert climate - dry and hot, little rain',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_032',
    emoji: '🌴',
    question: '¿Cómo es el clima tropical?',
    options: ['caluroso y húmedo', 'frío y seco', 'templado'],
    correctAnswer: 'caluroso y húmedo',
    hint: 'Tropical - hot and humid year-round',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_033',
    emoji: '🏔️',
    question: '¿Cómo es la temperatura en las montañas?',
    options: ['más fría', 'más caliente', 'igual'],
    correctAnswer: 'más fría',
    hint: 'Mountains - higher altitude means colder temps',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_034',
    emoji: '🌊',
    question: '¿Qué clima tiene la costa?',
    options: ['templado', 'extremo', 'polar'],
    correctAnswer: 'templado',
    hint: 'Coastal - moderate climate, ocean influence',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_035',
    emoji: '🧊',
    question: '¿Cómo es el clima polar?',
    options: ['muy frío', 'muy caliente', 'templado'],
    correctAnswer: 'muy frío',
    hint: 'Polar - extremely cold, ice and snow',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_036',
    emoji: '🌲',
    question: '¿Qué clima tiene el bosque templado?',
    options: ['moderado con cuatro estaciones', 'siempre frío', 'siempre caliente'],
    correctAnswer: 'moderado con cuatro estaciones',
    hint: 'Temperate forest - four distinct seasons',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_037',
    emoji: '🌿',
    question: '¿Dónde llueve mucho todo el año?',
    options: ['selva tropical', 'desierto', 'tundra'],
    correctAnswer: 'selva tropical',
    hint: 'Rainforest - heavy rainfall year-round',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_038',
    emoji: '🌡️',
    question: '¿Qué es el cambio climático?',
    options: ['calentamiento del planeta', 'estaciones del año', 'lluvia ácida'],
    correctAnswer: 'calentamiento del planeta',
    hint: 'Climate change - global warming phenomenon',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_039',
    emoji: '🌍',
    question: '¿Cómo se llama la capa que protege de los rayos UV?',
    options: ['capa de ozono', 'atmósfera', 'estratosfera'],
    correctAnswer: 'capa de ozono',
    hint: 'Ozone layer - protects from UV radiation',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_040',
    emoji: '♻️',
    question: '¿Qué gas causa el efecto invernadero?',
    options: ['dióxido de carbono', 'oxígeno', 'nitrógeno'],
    correctAnswer: 'dióxido de carbono',
    hint: 'Carbon dioxide - main greenhouse gas',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_041',
    emoji: '🏞️',
    question: '¿Qué es un ecosistema?',
    options: ['comunidad de seres vivos', 'tipo de clima', 'estación del año'],
    correctAnswer: 'comunidad de seres vivos',
    hint: 'Ecosystem - living community and environment',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_042',
    emoji: '💨',
    question: '¿Qué energía produce el viento?',
    options: ['energía eólica', 'energía solar', 'energía nuclear'],
    correctAnswer: 'energía eólica',
    hint: 'Wind energy - renewable power from wind',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_043',
    emoji: '☀️',
    question: '¿Qué energía viene del sol?',
    options: ['energía solar', 'energía eólica', 'energía hidráulica'],
    correctAnswer: 'energía solar',
    hint: 'Solar energy - power from the sun',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_044',
    emoji: '💧',
    question: '¿Qué energía produce el agua?',
    options: ['energía hidráulica', 'energía solar', 'energía eólica'],
    correctAnswer: 'energía hidráulica',
    hint: 'Hydroelectric - power from moving water',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_045',
    emoji: '🌱',
    question: '¿Qué es la fotosíntesis?',
    options: ['plantas producen oxígeno', 'animales respiran', 'llueve'],
    correctAnswer: 'plantas producen oxígeno',
    hint: 'Photosynthesis - plants make oxygen from sunlight',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },

  // Natural Phenomena (46-60)
  {
    id: 'weather_046',
    emoji: '🌋',
    question: '¿Qué sale de un volcán?',
    options: ['lava', 'agua', 'nieve'],
    correctAnswer: 'lava',
    hint: 'Lava - molten rock from volcano',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_047',
    emoji: '🏔️',
    question: '¿Qué es una avalancha?',
    options: ['caída de nieve', 'caída de agua', 'caída de piedras'],
    correctAnswer: 'caída de nieve',
    hint: 'Avalanche - snow sliding down mountain',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_048',
    emoji: '🌊',
    question: '¿Qué es un tsunami?',
    options: ['ola gigante', 'terremoto', 'huracán'],
    correctAnswer: 'ola gigante',
    hint: 'Tsunami - giant wave caused by earthquake',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_049',
    emoji: '🌍',
    question: '¿Qué es un terremoto?',
    options: ['temblor de tierra', 'viento fuerte', 'lluvia intensa'],
    correctAnswer: 'temblor de tierra',
    hint: 'Earthquake - ground shaking from tectonic plates',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_050',
    emoji: '🔥',
    question: '¿Qué destruye los bosques en verano?',
    options: ['incendios forestales', 'inundaciones', 'nevadas'],
    correctAnswer: 'incendios forestales',
    hint: 'Forest fires - wildfires in dry conditions',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_051',
    emoji: '🌊',
    question: '¿Qué pasa cuando llueve mucho?',
    options: ['inundación', 'sequía', 'helada'],
    correctAnswer: 'inundación',
    hint: 'Flood - too much water, areas submerged',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_052',
    emoji: '🏜️',
    question: '¿Qué pasa cuando no llueve por mucho tiempo?',
    options: ['sequía', 'inundación', 'tormenta'],
    correctAnswer: 'sequía',
    hint: 'Drought - lack of rain, dry conditions',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_053',
    emoji: '🌙',
    question: '¿Qué es un eclipse solar?',
    options: ['luna cubre el sol', 'tierra cubre la luna', 'sol cubre la tierra'],
    correctAnswer: 'luna cubre el sol',
    hint: 'Solar eclipse - moon blocks the sun',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_054',
    emoji: '🌕',
    question: '¿Qué es un eclipse lunar?',
    options: ['tierra cubre la luna', 'luna cubre el sol', 'sol cubre la luna'],
    correctAnswer: 'tierra cubre la luna',
    hint: 'Lunar eclipse - earth\'s shadow on moon',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_055',
    emoji: '☄️',
    question: '¿Cómo se llama una roca del espacio?',
    options: ['meteorito', 'satélite', 'cometa'],
    correctAnswer: 'meteorito',
    hint: 'Meteorite - space rock that hits earth',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_056',
    emoji: '🌠',
    question: '¿Cómo se llama una estrella fugaz?',
    options: ['meteoro', 'planeta', 'satélite'],
    correctAnswer: 'meteoro',
    hint: 'Meteor - shooting star, burns in atmosphere',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_057',
    emoji: '🌑',
    question: '¿Cuándo no vemos la luna?',
    options: ['luna nueva', 'luna llena', 'cuarto creciente'],
    correctAnswer: 'luna nueva',
    hint: 'New moon - moon not visible from earth',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_058',
    emoji: '🌕',
    question: '¿Cuándo vemos toda la luna?',
    options: ['luna llena', 'luna nueva', 'cuarto menguante'],
    correctAnswer: 'luna llena',
    hint: 'Full moon - complete lunar disk visible',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_059',
    emoji: '🌌',
    question: '¿Cómo se llama nuestra galaxia?',
    options: ['Vía Láctea', 'Andrómeda', 'Orión'],
    correctAnswer: 'Vía Láctea',
    hint: 'Milky Way - our home galaxy',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_060',
    emoji: '⭐',
    question: '¿Qué es el sol?',
    options: ['una estrella', 'un planeta', 'una luna'],
    correctAnswer: 'una estrella',
    hint: 'Star - the sun is a star, not a planet',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },

  // Environmental Protection (61-75)
  {
    id: 'weather_061',
    emoji: '♻️',
    question: '¿Qué símbolo representa reciclar?',
    options: ['tres flechas en círculo', 'una hoja verde', 'un árbol'],
    correctAnswer: 'tres flechas en círculo',
    hint: 'Recycling symbol - three arrows in triangle',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_062',
    emoji: '🗑️',
    question: '¿Dónde ponemos la basura?',
    options: ['en el basurero', 'en el suelo', 'en el río'],
    correctAnswer: 'en el basurero',
    hint: 'Trash can - proper place for garbage',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_063',
    emoji: '🌳',
    question: '¿Qué absorbe el dióxido de carbono?',
    options: ['los árboles', 'los coches', 'las fábricas'],
    correctAnswer: 'los árboles',
    hint: 'Trees - absorb CO2 and produce oxygen',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_064',
    emoji: '💡',
    question: '¿Qué ahorra energía?',
    options: ['apagar las luces', 'dejar luces encendidas', 'usar más electricidad'],
    correctAnswer: 'apagar las luces',
    hint: 'Turn off lights - saves electricity',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_065',
    emoji: '🚰',
    question: '¿Cómo ahorramos agua?',
    options: ['cerrando el grifo', 'dejando el grifo abierto', 'usando más agua'],
    correctAnswer: 'cerrando el grifo',
    hint: 'Close faucet - conserve water resource',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_066',
    emoji: '🛍️',
    question: '¿Qué bolsa es mejor para el ambiente?',
    options: ['bolsa de tela', 'bolsa de plástico', 'bolsa desechable'],
    correctAnswer: 'bolsa de tela',
    hint: 'Cloth bag - reusable, eco-friendly',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_067',
    emoji: '🚴',
    question: '¿Qué transporte no contamina?',
    options: ['bicicleta', 'coche', 'camión'],
    correctAnswer: 'bicicleta',
    hint: 'Bicycle - zero emissions transport',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_068',
    emoji: '🌿',
    question: '¿Qué significa "verde"?',
    options: ['ecológico', 'contaminado', 'sucio'],
    correctAnswer: 'ecológico',
    hint: 'Green - environmentally friendly',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_069',
    emoji: '🐝',
    question: '¿Qué insectos ayudan a las plantas?',
    options: ['las abejas', 'las moscas', 'los mosquitos'],
    correctAnswer: 'las abejas',
    hint: 'Bees - pollinate plants, make honey',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_070',
    emoji: '🌺',
    question: '¿Qué proceso hacen las abejas?',
    options: ['polinización', 'fotosíntesis', 'evaporación'],
    correctAnswer: 'polinización',
    hint: 'Pollination - transfer of pollen between plants',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_071',
    emoji: '🐋',
    question: '¿Qué está en peligro de extinción?',
    options: ['muchas especies', 'todas las especies', 'ninguna especie'],
    correctAnswer: 'muchas especies',
    hint: 'Many species - endangered animals worldwide',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_072',
    emoji: '🌊',
    question: '¿Qué contamina los océanos?',
    options: ['el plástico', 'el agua', 'los peces'],
    correctAnswer: 'el plástico',
    hint: 'Plastic - major ocean pollutant',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_073',
    emoji: '🏭',
    question: '¿Qué producen las fábricas?',
    options: ['contaminación', 'aire puro', 'agua limpia'],
    correctAnswer: 'contaminación',
    hint: 'Pollution - factories emit harmful substances',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_074',
    emoji: '🌲',
    question: '¿Qué es la deforestación?',
    options: ['cortar árboles', 'plantar árboles', 'regar árboles'],
    correctAnswer: 'cortar árboles',
    hint: 'Deforestation - cutting down forests',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_075',
    emoji: '🌱',
    question: '¿Qué es la reforestación?',
    options: ['plantar árboles', 'cortar árboles', 'quemar bosques'],
    correctAnswer: 'plantar árboles',
    hint: 'Reforestation - planting new trees',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },

  // Water Cycle & Nature (76-90)
  {
    id: 'weather_076',
    emoji: '💧',
    question: '¿Qué es el ciclo del agua?',
    options: ['evaporación y lluvia', 'día y noche', 'las estaciones'],
    correctAnswer: 'evaporación y lluvia',
    hint: 'Water cycle - evaporation, condensation, precipitation',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_077',
    emoji: '☁️',
    question: '¿Cómo se forman las nubes?',
    options: ['vapor de agua', 'humo', 'polvo'],
    correctAnswer: 'vapor de agua',
    hint: 'Water vapor - condenses to form clouds',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_078',
    emoji: '🌊',
    question: '¿De dónde viene el agua de lluvia?',
    options: ['del océano', 'de los ríos', 'de los pozos'],
    correctAnswer: 'del océano',
    hint: 'Ocean - water evaporates and becomes rain',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_079',
    emoji: '🏞️',
    question: '¿Dónde fluye el agua de los ríos?',
    options: ['al mar', 'a las montañas', 'al desierto'],
    correctAnswer: 'al mar',
    hint: 'To the sea - rivers flow downhill to ocean',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_080',
    emoji: '🏔️',
    question: '¿Dónde nacen los ríos?',
    options: ['en las montañas', 'en el mar', 'en el desierto'],
    correctAnswer: 'en las montañas',
    hint: 'Mountains - rivers start from high elevations',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_081',
    emoji: '💦',
    question: '¿Qué es la evaporación?',
    options: ['agua se convierte en vapor', 'vapor se convierte en agua', 'agua se congela'],
    correctAnswer: 'agua se convierte en vapor',
    hint: 'Evaporation - liquid water becomes gas',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_082',
    emoji: '💧',
    question: '¿Qué es la condensación?',
    options: ['vapor se convierte en agua', 'agua se convierte en vapor', 'agua se congela'],
    correctAnswer: 'vapor se convierte en agua',
    hint: 'Condensation - water vapor becomes liquid',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_083',
    emoji: '❄️',
    question: '¿Qué es la congelación?',
    options: ['agua se convierte en hielo', 'hielo se derrite', 'agua se evapora'],
    correctAnswer: 'agua se convierte en hielo',
    hint: 'Freezing - water becomes ice at 0°C',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_084',
    emoji: '🧊',
    question: '¿A qué temperatura se congela el agua?',
    options: ['0 grados', '100 grados', '50 grados'],
    correctAnswer: '0 grados',
    hint: 'Zero degrees - freezing point of water',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_085',
    emoji: '💨',
    question: '¿A qué temperatura hierve el agua?',
    options: ['100 grados', '0 grados', '50 grados'],
    correctAnswer: '100 grados',
    hint: 'One hundred degrees - boiling point',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_086',
    emoji: '🌊',
    question: '¿Qué porcentaje de la Tierra es agua?',
    options: ['70%', '30%', '50%'],
    correctAnswer: '70%',
    hint: 'Seventy percent - most of earth is water',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_087',
    emoji: '🧂',
    question: '¿Qué tipo de agua está en el océano?',
    options: ['agua salada', 'agua dulce', 'agua mineral'],
    correctAnswer: 'agua salada',
    hint: 'Salt water - oceans contain salt',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_088',
    emoji: '🏞️',
    question: '¿Qué tipo de agua está en los ríos?',
    options: ['agua dulce', 'agua salada', 'agua marina'],
    correctAnswer: 'agua dulce',
    hint: 'Fresh water - rivers have drinkable water',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_089',
    emoji: '🏔️',
    question: '¿Dónde hay hielo permanente?',
    options: ['en los polos', 'en el ecuador', 'en el desierto'],
    correctAnswer: 'en los polos',
    hint: 'Poles - Arctic and Antarctic have permanent ice',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_090',
    emoji: '🌍',
    question: '¿Qué capa de aire rodea la Tierra?',
    options: ['atmósfera', 'hidrosfera', 'litosfera'],
    correctAnswer: 'atmósfera',
    hint: 'Atmosphere - layer of gases around earth',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },

  // Advanced Weather & Climate (91-100)
  {
    id: 'weather_091',
    emoji: '🌡️',
    question: '¿Qué mide la presión atmosférica?',
    options: ['barómetro', 'termómetro', 'higrómetro'],
    correctAnswer: 'barómetro',
    hint: 'Barometer - measures air pressure',
    points: 5,
    category: 'weather',
    difficulty: 'hard',
  },
  {
    id: 'weather_092',
    emoji: '💨',
    question: '¿Qué mide la velocidad del viento?',
    options: ['anemómetro', 'termómetro', 'pluviómetro'],
    correctAnswer: 'anemómetro',
    hint: 'Anemometer - measures wind speed',
    points: 5,
    category: 'weather',
    difficulty: 'hard',
  },
  {
    id: 'weather_093',
    emoji: '🌧️',
    question: '¿Qué mide la cantidad de lluvia?',
    options: ['pluviómetro', 'termómetro', 'barómetro'],
    correctAnswer: 'pluviómetro',
    hint: 'Rain gauge - measures precipitation',
    points: 5,
    category: 'weather',
    difficulty: 'hard',
  },
  {
    id: 'weather_094',
    emoji: '💦',
    question: '¿Qué mide la humedad del aire?',
    options: ['higrómetro', 'termómetro', 'barómetro'],
    correctAnswer: 'higrómetro',
    hint: 'Hygrometer - measures humidity levels',
    points: 5,
    category: 'weather',
    difficulty: 'hard',
  },
  {
    id: 'weather_095',
    emoji: '🌍',
    question: '¿Qué fenómeno causa las estaciones?',
    options: ['inclinación de la Tierra', 'distancia al sol', 'rotación de la Tierra'],
    correctAnswer: 'inclinación de la Tierra',
    hint: 'Earth\'s tilt - causes seasonal changes',
    points: 5,
    category: 'weather',
    difficulty: 'hard',
  },
  {
    id: 'weather_096',
    emoji: '🌐',
    question: '¿Cuántas horas tarda la Tierra en rotar?',
    options: ['24 horas', '12 horas', '48 horas'],
    correctAnswer: '24 horas',
    hint: 'Twenty-four hours - one complete rotation',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_097',
    emoji: '🌞',
    question: '¿Cuántos días tarda la Tierra en orbitar el sol?',
    options: ['365 días', '30 días', '12 días'],
    correctAnswer: '365 días',
    hint: 'Three hundred sixty-five days - one year',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_098',
    emoji: '🌙',
    question: '¿Cuánto tarda la luna en orbitar la Tierra?',
    options: ['28 días', '7 días', '365 días'],
    correctAnswer: '28 días',
    hint: 'Twenty-eight days - lunar month',
    points: 5,
    category: 'weather',
    difficulty: 'hard',
  },
  {
    id: 'weather_099',
    emoji: '🌏',
    question: '¿Qué línea divide la Tierra en hemisferios?',
    options: ['ecuador', 'trópico', 'meridiano'],
    correctAnswer: 'ecuador',
    hint: 'Equator - divides north and south hemispheres',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_100',
    emoji: '⚡',
    question: '¿Qué se ve primero, el relámpago o el trueno?',
    options: ['el relámpago', 'el trueno', 'los dos juntos'],
    correctAnswer: 'el relámpago',
    hint: 'Lightning - light travels faster than sound',
    points: 5,
    category: 'weather',
    difficulty: 'medium',
  },
  {
    id: 'weather_101',
    emoji: '☔️',
    question: '¿Qué usas cuando caminas bajo la lluvia?',
    options: ['el paraguas', 'los lentes de sol', 'la bufanda'],
    correctAnswer: 'el paraguas',
    hint: 'Umbrella - "paraguas", protects you when walking in the rain',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
  {
    id: 'weather_102',
    emoji: '🌓',
    question: '¿Cómo se llama cuando la luna está mitad iluminada?',
    options: ['la media luna', 'la luna llena', 'la luna nueva'],
    correctAnswer: 'la media luna',
    hint: 'Half moon - lunar phase when half of the moon is illuminated',
    points: 5,
    category: 'weather',
    difficulty: 'easy',
  },
];
